### ISSUE TITLE
Maximum cache size

### ISSUE THREAD

**Issue by jonaskello** [verdaccio/verdaccio#100]
Is there some way to limit the cache? I would like to set a limit in GB and when that is reached the packages that have not been requested for the longest time are evicted from the cache.

**Comment by juanpicado** [comment]
There is no such thing in the config file. https://github.com/verdaccio/verdaccio/blob/master/conf/full.yaml
I think would be hard to implement, verdaccio does not support background jobs or at least wasn't in the original sinopia. If it make sense or not to implement, let's wait more thoughts.

**Comment by jonaskello** [comment]
Maybe it is something that makes more sense to add to the docker file.

**Comment by juanpicado** [comment]
that's a good point

**Comment by silkentrance** [comment]
How about making this a cronjob of some sort which simply does a ``find`` on the local store on the tarballs and automatically deletes all tarballs which have not been accessed for a specific amount of time. This way, the meta data is kept intact and verdaccio can once again fetch the tarballs if necessary.

**Comment by juanpicado** [comment]
I think this **feature** should be in a (future) local storage plugin, due in next major releases will be multiple ways to storage tarballs via plugins and won't make sense whether users decides, for instance, to store in a database. I think  #131 provides a cleaner solution to this issue.
