### ISSUE TITLE
after publishing a package, the /-/verdaccio/search/ does not pick it up until restart 

### ISSUE THREAD

**Issue by DimitarChristoff** [verdaccio/verdaccio#1005]
**Describe the bug**

The `/-/verdaccio/packages` returns a newly published package after page reload immediately. the search does not.

**To Reproduce**

- npm publish a new package
- reload web-ui
- package is now listed
- try to search for the package by name yields 0 results.
- restart verdaccio
- try to search now correctly returns the package 

Additionally, publishing a _new_ version does not get picked up either, only the old versions show - this also fails for the main list or package view

Minimal package.json that produces this:

```json
{
  "name": "test-package",
  "version": "1.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^16.5.1"
  }
}
```

**Expected behaviour**

- the search should pick it up (this.localStorage only seems to add package if latest cond)

**Comment by juanpicado** [comment]
I was debugging this and there is a big difference between `master` (3.x) and `4.x` https://github.com/verdaccio/verdaccio/pull/915

On `4.x` we use a new indexer, I'd suggest trying with the `alpha` release. I could not reproduce it with latest release or alpha.
