### ISSUE TITLE
npm token create support

### ISSUE THREAD

**Issue by varijkapil13** [verdaccio/verdaccio#1007]
**Is your feature request related to a problem? Please describe.**
Yes. I want to deploy a verdaccio docker instance for publishing private npm modules instead of using Nexus Pro. And I have version and publish automation with `semantic-release` npm module. In my CI server it specifically requires an npm access toekn generated via `npm token create` command. But whenever I try to execute that command on verdaccio, I get a `404` error.

**Describe the solution you'd like**
The `npm token create` command should be able to generate tokens just like npmjs.org

**Describe alternatives you've considered**
I have tried copying the token from my `.npmrc` file to the CI server. Tried creating a base64 encoded value of the username and password using `echo -n 'user:password' | openssl base64` and tried the output as authentication token as well. But to no success

**Comment by juanpicado** [comment]
We are working on this, we had to improve some parts of the application before getting to this, it will be part of next major release. 

Dupe, let's follow up here https://github.com/verdaccio/verdaccio/issues/541
