### ISSUE TITLE
Verdaccio as E2E Tooling

### ISSUE THREAD

**Issue by ayusharma** [verdaccio/verdaccio#1010]
It is a blog issue. We are going to keep track our internal blog writing here before publishing so other contributors can also suggest.

**Comment by juanpicado** [comment]
👉 Babel issue on publishing:
https://github.com/babel/babel/releases/tag/v7.1.1
https://twitter.com/left_pad/status/1045770889051164672

**Comment by ayusharma** [comment]
@juanpicado I am considering following points. 

- About Verdaccio:
- What are the E2E tests ? Why they are important.
- How verdaccio can help ? 
- Overcoming the fear of NPM publish.
- Integrating verdaccio in your Ecosystem.
- Where to look for help ?
- Some examples. (Git Repo)
- References

**Comment by juanpicado** [comment]
The list looks good to me. Don't forget to mention Lerna which is kinda the main topic here. 

I've been looking into this https://github.com/babel/babel/issues/6134 . Perhaps we can help.

**Comment by juanpicado** [comment]
Also [Gastby](https://www.gatsbyjs.org/) is running some experiments to achieve e2e with verdaccio.
https://github.com/gatsbyjs/gatsby/issues/4948
https://github.com/DSchau/verdaccio-circleci?files=1

**Comment by arcanis** [comment]
Not directly related, but on the Yarn v2 integration tests we currently use [a super-light mock server](https://github.com/yarnpkg/berry/blob/master/packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts#L165-L335) for npm.

It's not super urgent, but I sometimes wonder whether it would be possible to use Verdaccio to avoid having to reimplement the publish workflow etc ... 🤔

**Comment by juanpicado** [comment]
@arcanis I'd love to do it. Actually, I was reading the berry's source code the other day I had the same thought 😄 ... why not Verdaccio instead? ... I'll run some test locally.

**Comment by arcanis** [comment]
That would be awesome! Feel free to ping me on [Discord](https://discord.gg/yarnpkg) if you need any help 😃
