### ISSUE TITLE
Migrate react-router from hash to history API

### ISSUE THREAD

**Issue by ayusharma** [verdaccio/verdaccio#1013]
For @ayusharma https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/testing.md

**Breaking Change**

* Browser Bookmarks
* Proxies 🤔 ?

**Comment by roemhildtg** [comment]
Lots of readme's use #Heading to link to different sections of a README.md. When I click on one of these links in Verdaccio, it routes me to a different page. Would this change fix this use case?

**Comment by juanpicado** [comment]
Yes, that's the main idea.

**Comment by juanpicado** [comment]
Solved #1197
