### ISSUE TITLE
Prefer-Cache / Private / Offline preferred mode for uplink 

### ISSUE THREAD

**Issue by natew** [verdaccio/verdaccio#1021]
I know of [this issue](https://github.com/verdaccio/verdaccio/issues/256) but basically want to have a verdaccio flag to "skip checking the uplink if it already has it in cache". Right now it does a lot of network requesting even if it already has a cached version.

To be clear, I still want the uplink to be used as the "backup" if the cache doesn't have the version, but otherwise for it to stay offline if possible.

**Comment by juanpicado** [comment]
@natew when you execute `npm i jquery` asumming you use `npm` in your terminal, as first step the client will ask for metadata, all of it. Eg:

```
GET http://registry.npmjs.org/aaa
```
Independently the `package@version` you are requesting, based on the fetched metadata will decide whether the version exist or not, if the resource exist will fetch for the tarball or thrown any sort of error acording your request. 

**In other words, it's the client which decides the flow to resolve all dependencies**. I'm afraid I cannot do anything aside recommend increment time lookups for a specific uplink. Eg:

```
uplinks:
  npmjs:
    maxage: 7h
    url: https://registry.npmjs.org/
```

`maxage` will check with the cache whether is time for an uplink metadata update, a high value will reduce network request. 

Here a complete example

```
➜ npm i jquery -d        
npm info it worked if it ends with ok
npm info using npm@6.3.0
npm info using node@v10.1.0
npm http fetch GET 200 http://localhost:4873/jquery 78ms
npm http fetch GET 200 http://localhost:4873/jquery/-/jquery-3.3.1.tgz 73ms
npm timing stage:loadCurrentTree Completed in 338ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 6ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 9ms
npm timing stage:loadIdealTree Completed in 17ms
npm timing stage:generateActionsToTake Completed in 7ms
npm timing audit compress Completed in 3ms
npm info audit Submitting payload of 272bytes
npm timing action:extract Completed in 521ms
npm timing action:finalize Completed in 4ms
npm timing action:refresh-package-json Completed in 35ms
npm info lifecycle jquery@3.3.1~preinstall: jquery@3.3.1
npm timing action:preinstall Completed in 2ms
npm info linkStuff jquery@3.3.1
npm timing action:build Completed in 4ms
npm info lifecycle jquery@3.3.1~install: jquery@3.3.1
npm timing action:install Completed in 1ms
npm info lifecycle jquery@3.3.1~postinstall: jquery@3.3.1
npm timing action:postinstall Completed in 1ms
npm timing stage:executeActions Completed in 620ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 989ms
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN @scope/example@1.0.0 No repository field.

npm timing audit submit Completed in 1183ms
npm http fetch POST 200 http://localhost:4873/-/npm/v1/security/audits/quick 1183ms
npm timing audit body Completed in 1ms
+ jquery@3.3.1
```

I hope that helps.

**Comment by natew** [comment]
Actually this didn’t solve it quite. This prevents me from force publishing
on top of my old packages in verdaccio and having the new content be picked
up.

I guess what I need is more akin to not caching in verdaccio but caching
the uplink.
