### ISSUE TITLE
Verdaccio Docker container crashes on viewing package details with malformed contributors field

### ISSUE THREAD

**Issue by drochgenius** [verdaccio/verdaccio#1022]
**Describe the bug**

Verdaccio crashes when viewing a package details, if `contributors` section is malformed in the package.json.

In my case, I've mistakenly added contributors as an object, instead of an array of objects.

Take note that my service is powered by the latest Verdaccio Docker container, version `3.8.1`.

The crash happens on viewing the details page on a web browser, not on publishing.

**To Reproduce**

1. Set the contributors field in you `package.json` to an object instead of an array like this:
```javascript
    "contributors": {
        "name": "Barney Rubble",
        "email": "b@rubble.com",
        "url": "http://barnyrubble.tumblr.com/"
    },
```

2. Bump the version of your package and publish it.
3. Open Verdaccio UI, and browser to your package. 
4. Notice the message `Loading package information...` on the right side of the details page.
5. At this moment, Verdaccio crashes.

**Expected behavior**

I expect the service not to crash.

**Comment by drochgenius** [comment]
This seems to be related to #853.

**Comment by juanpicado** [comment]
It'll be shipped soon.

**Comment by ayusharma** [comment]
Please try `verdaccio@3.8.2`.

**Comment by drochgenius** [comment]
Awesome! thanks for the quick fix @juanpicado !
I will try it out as soon as the Docker image is available for `verdaccio@3.8.2`.

**Comment by juanpicado** [comment]
Due Docker issues. `https://status.docker.com/pages/533c6539221ae15e3f000031`

We cannot publish docker images yet.

**Comment by drochgenius** [comment]
No worries, thanks for the update.
These things happen!

**Comment by juanpicado** [comment]
:) I did it manually, docker hub is not deploying properly. It's ready.
