### ISSUE TITLE
verdaccio/sinopia is not yet cluster ready

### ISSUE THREAD

**Issue by wzrdtales** [verdaccio/verdaccio#103]
Currently verdaccio/sinopia has an internal cache of which packages exists. It does not reparse the `.sinopia-db`, therefore if you run sinopia in a cluster, there will be nodes that are out of sync and even more problematic, you may overwrite the `.sinopia-db` with different states.

Therefore we need to add the capability to either:
Create a communication channel (EventBus, MQ, whatsoever) or just a central configuration, like a database.

**Comment by juanpicado** [comment]
#54 @trentearl mention something interesting. But I was thinking to add kinda of 'adapters' features in order to delegate different kind of storages, by default would be the current one as a fallback.

**Comment by juanpicado** [comment]
I've been working in a small demo about how to scale this properly which I'll push in the following days hopefully. My idea is the following:

## The Problem
 Verdaccio persist only in the file storage in a file called `.sinopia-db.json` and handled internally by `local-data.js` and currently there is not way to change this unless we create a way via configuration to choose different sort of (I named it) **adapters**, but I'm not good naming stuff, so, help 👍 .

## Possible solution

#### Adapters

It would be a way to switch from different persistence sources, like databases, file storage, NFS (#54) and so on. This approach, at least, would eliminate the first barrier and handle state in one single place. eg: `local-mongo.js`, `local-xxx.js`.

Configuration example for MongoDB

````yalm
adapter:
  mongo:
    url: 'mongodb://127.0.0.1:27017/verdaccio'
    user: foo
    password: barr
   ## additional parameters
````
If there is no adapter defined (as a fallback) the file storage would be used by default, otherwise, the adapter would be used. 

#### Caveats

* Adapters would be asynchronous, the current implementation is synchronous and that force me to move to `Promises` or different alternatives (async await, but we do not use ES6 transpilers sadly ) to defer requests. In other words, huge changes in the code base.
* The packages are still stored in the file system, it might be a possible problem of sync if a a package exist in the file system but not in the persisten source. eg: (corrupt backups)
* How they will be integrated? bundle-in? plugins? 
* Maybe more, I'm just starting to see future problems. (<-- your opinion would be great for me)

<hr>

As I mentioned before. I'm working in a small implementation with MongoDB and  already have  persistence connection, trying to solve those small issues I've been finding.

I'd love your suggestions, comments to see if I'm addressing this correctly.

**Comment by Igmat** [comment]
@juanpicado, great suggestion. I there some way to look at your current solution?

**Comment by wzrdtales** [comment]
@juanpicado NFS is probably a bad choice if the plan is to actually distribute the system. :)

Having adapters and having a database, would help to solve the problem of concurrency. We would also need a strategy to persist data, where there are multiple ways. One would be to check for the checksum of the package and compare it with the existing ones. Another one would be a 3 step persist, insert into db first, persist, update db and mark as persisted.

About the integration: both. There should be plugins, but officially maintained one and community ones

> Adapters would be asynchronous, the current implementation is synchronous

Which implementation do you talk about? I'm not that deep into the source of sinopia/verdaccio, but I think everything should be already async. At least everything I see from quickly overseeing it, is. Or do you mean something specific like the persistence of the current `json`?

If so, then switching away from that `sync` write of the json, would not be really a problem, as with databases we wouldn't reparse files anymore, anyway though.

> and that force me to move to Promises or different alternatives (async await, but we do not use ES6 transpilers sadly ) to defer requests. In other words, huge changes in the code base.

Isn't async/await an ES7 feature? :p

Back to topic, this, as far as I have overseen it, is not true, but I might be wrong. Where do you see big problems with sync code? Almost everything that  I have seen is async, apart from the store of the json file which just makes sense.Or do you really just talk about that bit?

> The packages are still stored in the file system, it might be a possible problem of sync if a a package exist in the file system but not in the persisten source. eg: (corrupt backups)

If you would store them in a database, they would be also still stored in the filesystem though. Just kidding with you :)

But there are distributed network filesystems as well, ceph, glusterfs and others, which wouldn't affect the code base at all. And to be honest, in my opinion corrupt backups are not a problem that we should solve for those creating them. Actually being in sync after a desaster recovery, is something you can work on afterwards and having a package where its reference is missing, is actually the lucky case. It would be worse to miss the package but still having the reference, which is at least easy to solve, just look for it, if it is not there execute tasks trying to restore them or clean up if impossible.

All in all, good think you're working on this :) +1

**Comment by fforres** [comment]
Hey, sounds like a really neat Idea, we have been playing with verdaccio for a while,
But scaling is my biggest concern for pushing it forward in the company.
Part of our infrastructure is in AWS, so we considered S3 to create an adapter.
Do you have it in a current branch @wzrdtales ?  Would love to help if possible

**Comment by juanpicado** [comment]
@fforres I was doing that, but I posponed it until I finish a reliable plugin system (https://github.com/verdaccio/verdaccio/tree/refactoring-plugin). Actually, storages are not "pluginable" at all, only the authorization (as far I know) . Then, it would make sense make all adapters as plugins. I created a `yeoman` plugin generator in order to do this process less painful as possible (https://github.com/verdaccio/generator-verdaccio-plugin). In short words, please be welcome to collaborate 👍 I need all help as possible.

**Comment by juanpicado** [comment]
Using a local `couchdb` and with changes I got from #44 I manage to make it works, It cache package.json and `publish` and `unpulish` seems to works. This is just a early stage, no plugin support, but, that should be that hard. The branch is `origin/storage_pluggable`.

Here we can see a previous private package published.
<img width="1218" alt="screen shot 2017-05-21 at 11 59 00 am" src="https://cloud.githubusercontent.com/assets/558752/26283110/a2f38b86-3e21-11e7-901f-544fa7e0c14a.png">
A public packages published
<img width="1436" alt="screen shot 2017-05-21 at 12 35 31 pm" src="https://cloud.githubusercontent.com/assets/558752/26283134/1ed2582c-3e22-11e7-8e2d-6a68c66e66ad.png">
Overview of the size database, after some popular packages cached.
<img width="1438" alt="screen shot 2017-05-21 at 12 35 19 pm" src="https://cloud.githubusercontent.com/assets/558752/26283135/1ed8ec64-3e22-11e7-86ed-7f79dbed5132.png">

**Comment by juanpicado** [comment]
@p3x-robot no,  why you ask?

**Comment by juanpicado** [comment]
@p3x-robot how would to handle the persistence of packages and database of private modules?

**Comment by juanpicado** [comment]
Ohhh !! now I see your point and also I love redis, it's damn fast. I like it and I'm agreed with your approach.  

As you said, the main goals  🥇  here for the short future are:

* It have to be pluggable 👍 
* File storage system must remain as default (as a plugin) and any other storage must be pluggable 👍 
* Really simple installation `./verdaccio` and that's all  (https://github.com/verdaccio/verdaccio/pull/44#issuecomment-231864007) 👍 .

My current small roadmap with this:
1. Clean up the code base (not ready yet) and still is a mess and really hard to read and maintain
2. Plugins first #192 #169 ( In order allow others to hook their own stuff as you mentioned 👍  )
  2.1 Storage Plugins (eg: this ticket)
  2.2 Auth Plugins
  2.3 etc etc ..
3. Improve WebUI

**Comment by wzrdtales** [comment]
Redis or not really doesn't matter :) But good to see you guys make progress here. CouchDB is not that wrong at all, I'm personally not a big fan of it, but the official npmjs also uses CouchDB, so you're not that far from right.

**Comment by wzrdtales** [comment]
@juanpicado Auth plugins are also a good thing :) As this is a central component (besides docker registries) within many corporate infrastructures.

**Comment by wzrdtales** [comment]
@juanpicado Sry for spamming here though, but I just read bottom up everything :)

I can't assure to have enough spare time to help out, but I would be happy to review and help out on questions if there are any.

**Comment by wzrdtales** [comment]
And one comment on the way, don't spend too much time on scaling with the node cluster module. It doesn't work out as well as many think. Anyone that wants to scale should just use a proper loadbalancer and orchestration.

**Comment by wzrdtales** [comment]
@p3x-robot Well I opened this issue, so clearly no...

It was never intended to target the *node* cluster module. It just adresses the fact that this module is/was not yet ready to be run with multiple instances referring to the same target, which is what you call a cluster though.

I don't think that there is a real need for any kind of locks here. You can just have **one** module with the same version. So an existing entry for that version would already solve the concurrency problem. First serves first.

> there are multiple cores and verdaccio uses 1. that is why a cluster is important, together with everything async.

Just requoting myself:  It doesn't work out as well as many think. 

The cluster module of *node* comes with a lot of trouble, and it is way more flexible to scale a single core process. Just put the application into docker and scale as you wish with a proper orchestrator.

But feel free to ignore my advice, you may or may not run into the trouble, that the cluster module brings with it.

**Comment by wzrdtales** [comment]
?

**Comment by wzrdtales** [comment]
@p3x-robot ... I will just stop here witth that answer and will leave that alone, as there just seems a big huge language barrier, as you seem to completely understand me wrong though, just letting you know I do know node.js and b/c I do for many years, I know about many culprits and the *cluster* module is just not the way you go to scale in complicated environments. Using the cluster module is just the most easy way to go for, with a couple of problems that you will note very very late, maybe already too late, though. As already noted above, do whatever you want, I obviously don't care how you do it, I just gave an advice.

And to give an answer to the json file "lock", well yes kind of, but for a standalone server of this (which is the only version which the json file is suitable for) writing it sync was probably the easiest way to stop any concurrency there. 

And as a last thing to the c++ statement, I always use the c++ bits just for the interface for node, the rest I write in c when I look for speed though.

**Comment by juanpicado** [comment]
Just FYI

`npm install -g verdaccio@alpha` in the alpha version the door is open to create new storage plugins. There is no documentation yet, but, I'm working on a dummy plugin as an experiment and see whether the API has well shape.

https://github.com/verdaccio/verdaccio-memory

**Comment by juanpicado** [comment]
Related tickets

CouchDB #475
Firebase #474 
Amazon S3 #472 
Google Storage #473

**Comment by wzrdtales** [comment]
#1 thanks for your work on this going to have a look here soon.
