### ISSUE TITLE
Centralize Loading

### ISSUE THREAD

**Issue by priscilawebdev** [verdaccio/verdaccio#1036]
We have a spinner displayed twice in our app ... it's so fast .. you might not even see it ... but it's while loading the data.

**Comment by ayusharma** [comment]
Please describe. Is it about <Loading /> component ?

**Comment by priscilawebdev** [comment]
@ayusharma We have a spinner displayed twice in our app ... it's so fast .. you might not even see it ... but it's while loading the data.
