### ISSUE TITLE
Update to CircleCI 2.1 and add support for workspaces

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/verdaccio#1038]
We need to improve our workflow in order to keep it up & running on CircleCI (there is no EoL for 2.0, but keeping up to date would be the best).

Also, saving project in workspaces across steps would be a better alternative to not letting cache run out of space.

**Comment by sergiohgz** [comment]
That has a simple answer, the tag filter for releasing only looks for version with numbers only starting with ‘v’, like v1.0.0 or v.4.0.0.0.0

We should allow versioning tags following [Semver specification, paragraph 9](
https://semver.org/#spec-item-9) (I have created a regex for work recently, so let me remember how it was and I will set it tomorrow)

**Comment by juanpicado** [comment]
Sure, I think we have the same issue at Docker Hub, it only catches `x.x.x` this format.
