### ISSUE TITLE
Post publish hook?

### ISSUE THREAD

**Issue by lexon** [verdaccio/verdaccio#1072]
I am looking for a possibility to watch for package changes. In my scenario I want to run a script (bash/nodejs) after a specific plugin has been published. In this case I want to install the new published version and redeploy + start the server again.

Something similar to notifications but with custom script.

**Comment by juanpicado** [comment]
For this, I think you might have 2 options

* Create a middleware plugin to "inspect" each request and whether something match with your criteria triggers your stuff (https://verdaccio.org/docs/en/dev-plugins#middleware-plugin)
* We might add some hooks implementation as we do with notifications, but, it won't happen soon unless someone does PR, and whether this happens, it will go on `verdaccio@4` which is still an alpha.

I'd suggest option 1.

**Comment by lexon** [comment]
Thanks for the suggestion, unfortunately option 1 won’t work, since I have to wait until data has been written to fs.
I ended up with a separate script observing the package folder for new files.

**Comment by lexon** [comment]
Thanks for the suggestion, unfortunately option 1 won’t work, since I have to wait until data has been written to fs.
I ended up with a separate script observing the package folder for new files.
