### ISSUE TITLE
html style bug

### ISSUE THREAD

**Issue by zhump** [verdaccio/verdaccio#1074]
![image](https://user-images.githubusercontent.com/7962067/46944750-7c656080-d0a5-11e8-8b1f-1921cbb51e65.png)

**Comment by ayusharma** [comment]
@zhump We are aware of it. It'll be solved in verdaccio@4. Thanks for reporting.

**Comment by priscilawebdev** [comment]
@ayusharma @zhump  I fixed it in this PR [(PR 1064)](https://github.com/verdaccio/verdaccio/pull/1064) -> it will soon be approved and merged into 4.x.

**Comment by ayusharma** [comment]
Shipped in verdaccio@3.8.5.
