### ISSUE TITLE
Show docs for old version of package 

### ISSUE THREAD

**Issue by kishok** [verdaccio/verdaccio#1079]
**Is your feature request related to a problem? Please describe.**
we can display docs for old version packages when select a version in **LastSync** section. And also load all versions of a package in drop-down list so we can choose required version documentation rather currently supported last three versions and this change impacts other sections in package sidebar.so please provide some solution for this use-case.

**Comment by kwarpechowski** [comment]
@juanpicado Do you think that this issue to be good for the first issue? I would like to develop this improvement.

**Comment by juanpicado** [comment]
Sorry @kwarpechowski I did not see your message. 

V4 will display all versions, but not navigation enabled yet. We are not storing all READMEs files, only the latest one. Store multiple files might require big changes and if someone is willing to do it, I'm cool, but I would enable it only by demand, I don't think this has to be enabled by default.

**Comment by juanpicado** [comment]
We will ship soon a new beta with this feature. Stay tuned. I'll close this one since is done in one of our branches.
