### ISSUE TITLE
Add Package Problem

### ISSUE THREAD

**Issue by BlackSkyJY** [verdaccio/verdaccio#1087]
The package I originally published on the sinopia, now I want to use verdaccio, do I have to re-publish the original private package? Can directly change the address of the distribution package download?

**Comment by juanpicado** [comment]
>  do I have to re-publish the original private package? 

No, you should not. If you run into problems let us know. The migration should clean, the configuration is the same for latest sinopia vs latest verdaccio. 

> Can directly change the address of the distribution package download?

I don't know what do you mean with that.

**Comment by BlackSkyJY** [comment]
> > do I have to re-publish the original private package?
> 
> No, you should not. If you run into problems let us know. The migration should clean, the configuration is the same for latest sinopia vs latest verdaccio.
> 
> > Can directly change the address of the distribution package download?
> 
> I don't know what do you mean with that.

I want to match verdaccio's release address to the sinopia release address, so I don't have to re-publish the package on verdaccio

**Comment by juanpicado** [comment]
> I want to match verdaccio's release address to the sinopia release address, so I don't have to re-publish the package on verdaccio

If your concern is about the `tarball` path, it should not change at all, the storage structure is exactly the same. 

We did it in that way because we know plenty of users are still using sinopia and eventually they might move to Verdaccio.
