### ISSUE TITLE
High availability using ECS cluster

### ISSUE THREAD

**Issue by roddy-toomim-sp** [verdaccio/verdaccio#1089]
I'd like to install Verdaccio (as a set of docker containers) in an ECS cluster which has raised a couple questions, and I hope this is an appropriate forum for them:

- Can Verdaccio be used in an HA fashion? 
- If pointed at an AWS s3 bucket, will multiple containers "fight" over which published packages are "correct"?

**Comment by juanpicado** [comment]
cc: perhaps @apexskier have thoughts here.

**Comment by apexskier** [comment]
Unfortunately I don't really have any knowledge here. I'm not sure what sort of availability metrics you're looking for, but my use case hasn't seen any issues running a single verdaccio instance.

Verdaccio and S3 have no concurrent protections built in, so it's pretty likely that multiple instances would conflict if trying to write or delete the same file.

**Comment by roddy-toomim-sp** [comment]
Thanks, @apexskier. I'm not looking for metrics per se, just a dev's gut feeling of whether or not we could setup Verdaccio with an HA mindset. I had an inkling already that what you stated would be the case, but haven't completely setup the infrastructure for the service, so no testing completed. I appreciate your insight and attention here.

Thanks again!
