### ISSUE TITLE
Puppet module to install is linking to sinopia not verdaccio

### ISSUE THREAD

**Issue by Cosaquee** [verdaccio/verdaccio#109]
Right now the puppet module linked in README.md will install sinopia, not Verdaccio. In my opinion this readme entry should be deleted until we have working Puppet module for Verdaccio.

Right now I`m going to install Verdaccio in my company, I`m going to use Puppet for that and I`m willing to publish Puppet module for Verdaccio and maintain it.

**Comment by juanpicado** [comment]
I hope someone (hopefully you) with Puppet support helps to solve #87 . In the meantime, it was removed as you requested.
