### ISSUE TITLE
安装报错 ( Installation error )

### ISSUE THREAD

**Issue by 9188** [verdaccio/verdaccio#1091]
version: 3.7.1

安装 update-notifier 这个的时候会报错

![image](https://user-images.githubusercontent.com/10806354/47499011-6f105900-d891-11e8-8fd6-06c63465343a.png)

**Comment by ayusharma** [comment]
Please try this https://docs.npmjs.com/troubleshooting/try-clearing-the-npm-cache

**Comment by 9188** [comment]
Or that's the way it is.

![image](https://user-images.githubusercontent.com/10806354/47499497-acc1b180-d892-11e8-9c8b-9f7b7b1ea975.png)

**Comment by ayusharma** [comment]
Remove `package-lock.json` and try to reinstall it. NPM client is try to finding the package which is not available or updated somehow.

**Comment by ayusharma** [comment]
Please feel free to open, if issue persist.
