### ISSUE TITLE
Configure email for package notification ?

### ISSUE THREAD

**Issue by BlackSkyJY** [verdaccio/verdaccio#1092]
I don't know how to use notification feature, Who can receive notification information if the endpoint is configured in the configuration file,
![image](https://user-images.githubusercontent.com/29111051/47549018-56558100-d92d-11e8-99ba-1114d0229159.png), Besides, Can the endpoint configure the recipient's mail address ? Must you use webhooks with the notification feature?

**Comment by ayusharma** [comment]
No. You can not configure email. It is the webhook endpoint on which Verdaccio makes an API call with notification message.

**Comment by BlackSkyJY** [comment]
Could you offer demo for notification feature?

**Comment by BlackSkyJY** [comment]
In fact, I want to  everyone on the team gets updated information by email or rss Everyone on the team gets updated information

**Comment by juanpicado** [comment]
Right now is not possible send email or anything similar. You might create a simple app with a simple endpoint (that send an email or create a rss entry) and call it from verdaccio with the notification feature.  It is not the best solution but is the unique I have in mind now.

**Comment by GibranLara** [comment]
Is it a characteristic that is contemplated? Right now it is something that I was investigating, the possibility that when creating a new repository an email was sent notifying of this action.

**Comment by BlackSkyJY** [comment]
@juanpicado , Thank your reply, i set the rss entry on endpoint, pass rss-node and koa to complete RSS feeds feature

**Comment by juanpicado** [comment]
Cool perfect, feel free to close this ticket :)

**Comment by BlackSkyJY** [comment]
if endpoint support setting email address feature,  That is better

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/issues/1097 There is an thread already there. Closing this one.
