### ISSUE TITLE
Google App Engine/Docker HTTPS without generating certs?

### ISSUE THREAD

**Issue by serratedserenade** [verdaccio/verdaccio#1096]
Hey guys,

so I want to deploy verdaccio to a Google App Engine container, which is essentially a Docker container. I want to force all connections to be https. According to the documentation, I can simply set `PROTOCOL` env var to be `https`. However, it seems to break and provides this error:

```
 fatal--- You have enabled HTTPS and need to specify either
    "https.key", "https.cert" and "https.ca" or
    "https.pfx" and optionally "https.passphrase"
to run https server
To quickly create self-signed certificate, use:
 $ openssl genrsa -out /verdaccio/conf/verdaccio-key.pem 2048
 $ openssl req -new -sha256 -key /verdaccio/conf/verdaccio-key.pem -out /verdaccio/conf/verdaccio-csr.pem
 $ openssl x509 -req -in /verdaccio/conf/verdaccio-csr.pem -signkey /verdaccio/conf/verdaccio-key.pem -out /verdaccio/conf/verdaccio-cert.pem
```

Would it be possible to be able to ignore this warning? I'm letting App Engine handle all the https connections so I don't think I need to set this up. Thanks!

**Comment by kwarpechowski** [comment]
I think that this issue can`t be connected with this project.  You should get cert files and put the reference in 'verdaccio' config. I made simple research google app engine docs. You may able to generate custom ssl certificate and upload via web configurator.

**Comment by serratedserenade** [comment]
So I can't avoid this step then to force HTTPS? I was hoping to leave SSL to be managed by Google. I only ask because other Node projects we have deployed on App Engine can be forced to HTTPS without any extra steps.

**Comment by juanpicado** [comment]
@serratedserenade to enable HTTPs in Node we must provide certificates (https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) otherwise is gonna fail later on on start the server. If you want to handle HTTPS by your own you have one option, Proxy pass (we have couple of examples here (https://github.com/verdaccio/docker-examples), aside of that as @kwarpechowski has argued, you must provide certificates (https://verdaccio.org/docs/en/configuration#https) via config file. 

> other Node projects we have deployed on App Engine can be forced to HTTPS without any extra steps.

I'm not super expert on Google Cloud, perhaps you can provide us a bit more context about it.

**Comment by serratedserenade** [comment]
Just to preface, I'm not 100% experienced with how Node actually handles HTTPS/SSL connections, so maybe my current implementation may be questionable.

So I have gcloud App Engine handle the SSL for us, so we don't have to generate it ourselves. App Engine essentially uses Docker, but also does all the stuff like autoscaling and load balancing for us, so all I have to do is code and deploy and not care about server configuration.

Currently for some of our applications, we use Express 4 and during the connection, we force the request to be secure like this:

```
app.use((req, res, next) => {
  if (!req.secure) {
    return res.redirect(['https://', req.get('Host'), req.url].join(''));
  }
  return next();
});
```
So it's impossible to connect to our app by http. So far we haven't really experienced any errors.

Which is kinda why I brought up this issue/question regarding Verdaccio.

Just to link, we actually made it so it's possible to connect to it by https. https://npm.publift.com/

However, you can also reach the page with http. http://npm.publift.com but trying to login throws an error because we use a plugin to use Github for auth management, and we set up Github to use callbacks through a https url.

**Comment by juanpicado** [comment]
@serratedserenade I see your corcerns, thanks for the detailed explanation.

I'll check this next week when I'm back home. I have poor resources where I'm now. I'll back to you after run some test.

**Comment by beauremus** [comment]
I am interested in this solution also.
