### ISSUE TITLE
Send notifications via email

### ISSUE THREAD

**Issue by GibranLara** [verdaccio/verdaccio#1097]
**Is your feature request related to a problem? Please describe.**
The need to notify of the creation of new repositories through a formal and common way, such as email.

Sending an email helps with the persistence of notifications. It helps making decisions in a corporate environment.

**Describe the solution you'd like**
A module or own API of Verdaccio that allows to receive the information generated by the notification system.

The information of the notification is sent to the mail service and this is responsible for decomposing the information received and from this the body of the mail is constructed and sent.

The desired configuration of the postal service would be to modify the structure of the mail, sender, recipient, subject, etc.

In the same way, the possibility of having a mechanism that allows the pending emails to be sent in a queue.

**Describe alternatives you've considered**
Build a small API in node that is responsible for receiving the post requests for notifications and this generates an email is sent.

The idea I suppose is the same as the one mentioned by @juanpicado in [https://github.com/verdaccio/verdaccio/issues/1092#issuecomment-433368165](url)

**Comment by kwarpechowski** [comment]
Great idea, but I think that this project should be `lightweight`. In my opinion, 'verdaccio' may be able to implement webhooks for main events.

**Comment by juanpicado** [comment]
I agreed with @kwarpechowski. I’be been thinking to extend plugin API for notifications or like he said some sort of better organized web hook API for notifications. It does sound crazy?

**Comment by juanpicado** [comment]
I'll follow up this extension in a different ticket.
