### ISSUE TITLE
Supporting documentation for new user registrations from respective roles

### ISSUE THREAD

**Issue by hansiemithun** [verdaccio/verdaccio#1110]
At present, we can add users pointing to the registry directly.

But wondering if there is a way to disable the registrations and add users and give necessary access privileges to the repos from admin or any other roles only? 

Will it support such a requirement?

Basically, if there is any possibility a centralized login system should take care of providing access to private repos as well. Please clarify

**Comment by juanpicado** [comment]
> But wondering if there is a way to disable the registrations and add users and give necessary access privileges to the repos from admin or any other roles only?

This depends on the auth plugin you are using, do you refer to the default one?

> Basically, if there is any possibility a centralized login system should take care of providing access to private repos as well. Please clarify

It depends on your auth provider (https://verdaccio.org/docs/en/plugins#authorization-plugins). Could you elaborate a bit more your environment?
