### ISSUE TITLE
url_prefix with a path passes path to upstream registry

### ISSUE THREAD

**Issue by argh** [verdaccio/verdaccio#1112]
I'm trying to host verdaccio behind haproxy, and need a "path" to hook to, as there are dozens of other services also hosted through the proxy and I can't serve it at the root level.

When I set url_prefix with a child path, either relative "/wat" or absolute "https://myserver.io/wat", it passes the "/wat" upstream to registry.npmjs.org, resulting in a 404.

config:
```
storage: /verdaccio/storage
url_prefix: https://myserver.io/wat/
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
...
```

.npmrc:
`registry=https://myserver.io/wat/
`

example run:
`
ip-10-1-27-32:tmp rg$ npm install --save underscore
npm ERR! code E404
npm ERR! 404 Not Found: underscore@latest
`

what haproxy sees (correctly invokes verdaccio, which then returns a 404):
`
2018-11-10T19:02:41+00:00 localhost haproxy[683]: 10.1.2.152:50846 [10/Nov/2018:19:02:41.071] dynamic~ cluster-npm-service/cluster-npm-service-1018d0f50d1f6d68e0d85f53ade4ed27fdb010b9aff9c05e95fa49ae835a7778 0/0/1/176/177 404 363 - - ---- 1/1/0/0/0 0/0 {|npm/6.4.1 node/v8.1.4 darwin x64|install underscore|||||myserver.io} "GET /wat/underscore HTTP/1.1"
`
verdaccio log:
`
info <-- 10.1.4.237 requested 'GET /wat/underscore'
info --> making request: 'GET https://registry.npmjs.org/wat'
http --> 304, req: 'GET https://registry.npmjs.org/wat' (streaming)
http --> 304, req: 'GET https://registry.npmjs.org/wat', bytes: 0/0
debug-=- updating package wat info
http <-- 404, user: null(10.1.2.152 via 10.1.4.237), req: 'GET /wat/underscore', error: version not found: underscore
`

I'd expect that verdaccio would trim the entire url_prefix off the request url, and only request the remaining path, i.e. in this case /underscore

npm version 6.4.1

**Comment by juanpicado** [comment]
**haproxy** related:
https://github.com/verdaccio/verdaccio/issues/395
https://github.com/verdaccio/verdaccio/issues/695
