### ISSUE TITLE
Inconsistent behaviour of $all vs $unauthenticated in package access with auth plugins

### ISSUE THREAD

**Issue by dlouzan** [verdaccio/verdaccio#1120]
**Describe the bug**
While trying to implement the package access behaviour of verdaccio-gitlab as close as possible to the default behaviour of verdaccio default auth plugin (htpasswd).

In my tests, when configuring different authentication plugin setups, there's inconsistent results between `$all` and `$anonymous`:

1. If I configure htpasswd as auth plugin, both `$all` and `$anonymous` behave the same, just allow access irrespective of the login status
1. If I configure verdaccio-gitlab and I disable verdaccio-gitlab for a specific package definition, then `$all` behaves as it doesn't matter the login status, but `$anonymous` forces to be logged out.

I can't find this behaviour documented anywhere :question: There is some kind of default access control implemented in verdaccio when no auth plugin takes over, and it seems that it distinguishes between both states as opposed to htpasswd.

My tests are done with the latest 3.8.5 version and the following configuration:

```
storage: ./storage

auth:
  gitlab:
    url: http://localhost:50080

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '**':
    access: $anonymous
    publish: $authenticated
    proxy: npmjs
    gitlab: true

logs:
  - {type: stdout, format: pretty, level: trace}
```

If I try to login with a user logged in and uncomment `gitlab: true` my plugin takes over:
```
 warn --- config file  - /home/one/.config/verdaccio/config.yaml
 info --- [gitlab] url: http://localhost:50080
 info --- [gitlab] initialized auth cache with ttl: 30 seconds
 info --- [gitlab] publish control level: $maintainer
 warn --- Plugin successfully loaded: gitlab
 warn --- http address - http://localhost:4873/ - verdaccio/3.8.5
 info <-- 127.0.0.1 requested 'GET /url-join'
 trace--- [gitlab] authenticate called for user: diego
 trace--- [gitlab] user: diego not found in cache
 trace--- [gitlab] querying gitlab user groups with params: { min_access_level: 40 }
 debug--- [gitlab] saving data in cache for user: diego
 info --- [gitlab] user: diego successfully authenticated
 debug--- [gitlab] user: diego, with groups: { publish: [ 'diego', 'verdaccio-gitlab' ] }
 debug--- [gitlab] allow user: diego anonymous access to package: url-join
 info --> making request: 'GET https://registry.npmjs.org/url-join'
 http --> 304, req: 'GET https://registry.npmjs.org/url-join' (streaming)
 http --> 304, req: 'GET https://registry.npmjs.org/url-join', bytes: 0/0
 debug-=- updating package url-join info
 http <-- 200, user: diego(127.0.0.1), req: 'GET /url-join', bytes: 0/2496
```

The same case if I leave `gitlab: true` commented, the default behaviour kicks in and I get:
```
 warn --- config file  - /home/one/.config/verdaccio/config.yaml
 info --- [gitlab] url: http://localhost:50080
 info --- [gitlab] initialized auth cache with ttl: 30 seconds
 info --- [gitlab] publish control level: $maintainer
 warn --- Plugin successfully loaded: gitlab
 warn --- http address - http://localhost:4873/ - verdaccio/3.8.5
 info <-- 127.0.0.1 requested 'GET /url-join'
 trace--- [gitlab] authenticate called for user: diego
 trace--- [gitlab] user: diego not found in cache
 trace--- [gitlab] querying gitlab user groups with params: { min_access_level: 40 }
 debug--- [gitlab] saving data in cache for user: diego
 info --- [gitlab] user: diego successfully authenticated
 debug--- [gitlab] user: diego, with groups: { publish: [ 'diego', 'verdaccio-gitlab' ] }
 http <-- 403, user: diego(127.0.0.1), req: 'GET /url-join', error: user diego is not allowed to access package url-join
```

Authenticate is successful in both cases as my plugin is the only auth plugin configured, but the access control is different.

Any guidance will be very welcome.

@bufferoverflow

**Comment by dlouzan** [comment]
This is by the way, why I think this issue was filed on our end: https://github.com/bufferoverflow/verdaccio-gitlab/pull/54

The user had to explicitly set `true` on success to avoid going through the plugin chain and receive this inconsistent behaviour, when the only auth plugin was verdaccio-gitlab.

**Comment by juanpicado** [comment]
@dlouzan I've been checking on this, still no outcome. 🔎

**Comment by juanpicado** [comment]
> 1. If I configure htpasswd as auth plugin, both `$all` and `$anonymous` behave the same, just allow access irrespective of the login status

Actually, htpasswd does not apply (https://github.com/verdaccio/verdaccio-htpasswd/blob/master/src/htpasswd.ts) `allow_access`, `allow_publish` and the new `allow_unpublish`. It fallsback to default behaviour at Verdaccio. Which only match whether the user has any of those groups, which is the 100% of the cases. `htpasswd` is not the most flexible plugin and basically, there is no difference between `$all` and $anonymous`.

> 2\. If I configure verdaccio-gitlab and I disable verdaccio-gitlab for a specific package definition, then `$all` behaves as it doesn't matter the login status, but `$anonymous` forces to be logged out.

You have here total freedom, it depends of the plugin, so, I'd recommend always implement `allow_access`, `allow_publish` and the new `allow_unpublish`.


I will improve the plugin development docs after v4. That's my next goal, make plugin development a delicious experience.

**Comment by juanpicado** [comment]
I'll close this, I'll follow https://github.com/verdaccio/website/issues/46

**Comment by dlouzan** [comment]
Thanks, I still don't fully understand what is happening under the hood but this sheds some light.
