### ISSUE TITLE
403 forbidden: package.json@^2.0.1

### ISSUE THREAD

**Issue by shinstudio** [verdaccio/verdaccio#1127]
**Describe the bug**
I think there may be a discrepant behavior between verdaccio and official npm repo when it comes to `package.json` package. 

**To Reproduce**
1. `npm set registry https://registry.npmjs.org`
2. `npm install package.json`
3. `ls node_modules | grep package.json`
   ```git-package-json
   package-json
   package.json
   package-json-patch```
   ...
4. rm -r *
5. `npm set registry https:{your verdaccio repo}`
6. `npm install package.json`
7. error message is:
   ```npm ERR! code E403
   npm ERR! 403 Forbidden: package.json@latest

   npm ERR! A complete log of this run can be found in:
   npm ERR!     /home/{whoami}/.npm/_logs/2018-11-19T06_46_27_794Z-debug.log```


**Expected behavior**
Should install package.json package

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

url_prefix: https://npm.myrepo.com/
# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: My private repo

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: 1 

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  'private-*':
    access: $all
    publish: mybuild
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: mybuild 

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: rotating-file, format: json, path: /home/verdaccio/verdaccio/log/log.json, level: info, options: { period: 2d } }
  #- {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

# listen address (or a port)
listen: 0.0.0.0:4873
```

**Debugging output**
This is log info grep'ing package.json on the repo:
```
{"name":"verdaccio","hostname":"xxx","pid":23352,"sub":"in","level":30,"req":{"method":"GET","url":"/package.json","headers":{"host":"npm.myrepo.com:443","x-real-ip":"x.x.x.x","x-forwarded-for":"x.x.x.x","x-forwarded-proto":"https","connection":"close","user-agent":"npm/6.2.0 node/v10.9.0 linux x64","npm-in-ci":"false","npm-scope":"","npm-session":"d510c4c313a46e56","referer":"install","pacote-req-type":"packument","pacote-pkg-id":"registry:manifest","accept":"application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*","authorization":"<Classified>","accept-encoding":"gzip,deflate"},"remoteAddress":"127.0.0.1","remotePort":33900},"ip":"127.0.0.1","msg":"127.0.0.1 requested 'GET /package.json'","time":"2018-11-19T06:39:01.767Z","v":0}
{"name":"verdaccio","hostname":"xxx","pid":23352,"sub":"in","level":35,"request":{"method":"GET","url":"/package.json"},"user":"mybuild","remoteIP":"x.x.x.x via 127.0.0.1","status":403,"error":"invalid package","bytes":{"in":0,"out":33},"msg":"403, user: mybuild(47.152.46.150 via 127.0.0.1), req: 'GET /package.json', error: invalid package","time":"2018-11-19T06:39:01.771Z","v":0}
{"name":"verdaccio","hostname":"xxx","pid":23352,"sub":"in","level":30,"req":{"method":"GET","url":"/package.json","headers":{"host":"npm.myrepo.com:443","x-real-ip":"x.x.x.x","x-forwarded-for":"x.x.x.x","x-forwarded-proto":"https","connection":"close","user-agent":"npm/6.2.0 node/v10.9.0 linux x64","npm-in-ci":"false","npm-scope":"","npm-session":"4b3f43c621f4e30d","referer":"install package.json","pacote-req-type":"packument","pacote-pkg-id":"registry:manifest","accept":"application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*","authorization":"<Classified>","accept-encoding":"gzip,deflate"},"remoteAddress":"127.0.0.1","remotePort":33916},"ip":"127.0.0.1","msg":"127.0.0.1 requested 'GET /package.json'","time":"2018-11-19T06:46:27.957Z","v":0}
{"name":"verdaccio","hostname":"xxx","pid":23352,"sub":"in","level":35,"request":{"method":"GET","url":"/package.json"},"user":"mybuild","remoteIP":"x.x.x.x via 127.0.0.1","status":403,"error":"invalid package","bytes":{"in":0,"out":33},"msg":"403, user: mybuild(x.x.x.x via 127.0.0.1), req: 'GET /package.json', error: invalid package","time":"2018-11-19T06:46:27.978Z","v":0}
```

**Additional context**
n/a

**Comment by juanpicado** [comment]
As temporary workaround while this is changed. I'd suggest if someone is stuck on this for some reason, use scoped packages for that specific package to main registry (https://nitayneeman.com/posts/understanding-scoped-packages-in-npm/)

**Comment by juanpicado** [comment]
Ok @shinstudio. Let me see what I can do about it. thanks for the feedback

**Comment by shinstudio** [comment]
@juanpicado thanks and appreciated!

**Comment by juanpicado** [comment]
Well, it was easier as I expected. I'll publish in the next release in a few days after code reviews.
![screen shot 2018-12-04 at 8 37 46 pm](https://user-images.githubusercontent.com/558752/49468250-ad8c2280-f804-11e8-8e07-a2b1a0f3b974.png)

**Comment by juanpicado** [comment]
`verdaccio@3.10.0`

**Comment by shinstudio** [comment]
@juanpicado appreciated! Updated verdaccio on my server and could install it again! 👍
