### ISSUE TITLE
How to login

### ISSUE THREAD

**Issue by danielo515** [verdaccio/verdaccio#113]
Hello everyone,

I want to use verdaccio as a private npm registry, however I'm having problems logging in.
I have disabled user registration, and I have created an `htpasswd` file with a couple of users.

If I try to install a package, I get an error that says `unregistered users are not allowed to access package x`, fantastic, exactly what I want. BUT, how can I log in? If i try `npm login` what it does is an attempt to create an user, which is of course not allowed. I feel that I'm on a deadlock here.

Thanks in advance.

**Comment by danielo515** [comment]
Ok the problem was the format of the passwor.
It was not the one that verdaccio expects, it was generated using `htpasswd` on my MAC.
The error was very confusing, because the problem was not the user existing already, it was because passwords did not match.

Consider adding this to the documentation, most of the people that ends up checking verdaccio is for having totally private npm repositories. How to achieve this configuration is not clear, and I was forced to dive on several sinopia forks and old blog ports to figure out how.

Regards

**Comment by juanpicado** [comment]
The PR https://github.com/verdaccio/verdaccio/pull/112 add support for `md5` being created with unix `htpasswd`. I'd wait for others opinion. **verdaccio** uses an `sha512` encryption by default. That's the reason why does not match. It's intended in that way, I'd recommend use  `npm adduser --registry http://localhost:1443` 
in order to create users to ensure high compability.

**Comment by danielo515** [comment]
Dear @juanpicado, that's what I did, but it is a bit uncomfortable to spawn a server just to add a couple of users. I want my repository to remain private ,and to achieve that I have to disable users registration. What it's really lacking is a system where only administrators can add new users .

Regards

**Comment by juanpicado** [comment]
Currently there is no such support, but, it seems a good idea. Let's see how ends up the #112 to helps you to add users.

**Comment by oomathias** [comment]
Hi,

I'm trying to use verdaccio, I created some users which work fine.
Then when I try to login `npm login --registry https://npm.somedomain.com --scope myscope` I get:

```
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html>
npm ERR! <head><title>405 Not Allowed</title></head>
npm ERR! <body bgcolor="white">
npm ERR! <center><h1>405 Not Allowed</h1></center>
npm ERR! <hr><center>nginx</center>
npm ERR! </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Server side:
```
http <-- 409, user: undefined, req: 'PUT /-/user/org.couchdb.user:lensys', error: this user already exists
```

I'm able to login via the web GUI but not via npm (only the first login works aka creating one).

So how to login?

**Comment by juanpicado** [comment]
@oomathias please create a new ticket and add the same command verbose with `-ddd`

**Comment by axelrindle** [comment]
If this helps anyone, I fixed this issue for myself by just appending a trailing slash at the end of the url (like this: `https://example.com/verdaccio/`).
