### ISSUE TITLE
[new UI] show dist-tags in frontend?

### ISSUE THREAD

**Issue by JannikZed** [verdaccio/verdaccio#1130]
**Is your feature request related to a problem? Please describe.**
I would like to see the dist-tags of my packages visible at the verdaccio registry. Right now just the versions are visible, but tags like `beta` or `latest` are super important for us, too.

**Comment by juanpicado** [comment]
@JannikZed we are working on it, new UI.

https://github.com/verdaccio/verdaccio/projects/10

**Comment by JannikZed** [comment]
Really cool! Looking forward for it :) thank you

**Comment by JannikZed** [comment]
a sh*t, we should keep this open, right?

**Comment by juanpicado** [comment]
![verdaccio](https://user-images.githubusercontent.com/558752/51071418-ed8ac480-1650-11e9-8be9-94ac9d5f3e18.png)

I'll add this on 4.x. It will be available on next alpha or next Docker image in the same branch.
