### ISSUE TITLE
If there is no packages

### ISSUE THREAD

**Issue by priscilawebdev** [verdaccio/verdaccio#1131]
We have a white blank page
There is no welcome message nothing

**Comment by juanpicado** [comment]
I think this is fixed already. @ayusharma Am I wrong?

**Comment by ayusharma** [comment]
@priscilawebdev Are you still facing this issue? I have fixed this in #1118. If the issue persists, Please let me know.

**Comment by juanpicado** [comment]
I checked, it works.
