### ISSUE TITLE
Unexpected token < in JSON at position 0 while parsing near '<html>

### ISSUE THREAD

**Issue by Pegase745** [verdaccio/verdaccio#1143]
Hello everyone,

**Describe the bug**
Fail to `npm install` a certain package. It does not apply to all the packages we try to install.

**To Reproduce**
After a verdaccio 2->3 migration, we installed a new instance and synced the storage folder from the old one to the new one.
Everything seemed going fine, until we ran on some packages, which gave us this error `Unexpected token < in JSON at position 0 while parsing near '<html>` after an `npm install`.

After investigating, here's my conclusion:
- For a working package, https://<my_registry>/<my_package> returns the `package.json`.
- For a non working package: https://<my_registry>/<my_package> returns the below HTML response
```html
<html>
	<head><title>Index of /my_package/</title></head>
	<body bgcolor="white">
		<h1>Index of /my_package/</h1>
		<hr>
		<pre>
			<a href="../">../</a>
			<a href="package.json">package.json</a>                                       29-Nov-2018 12:40    266K
		</pre>
		<hr>
	</body>
</html>
```
![issue_verdaccio](https://user-images.githubusercontent.com/1678801/49220388-5e925780-f3d6-11e8-864d-7b92d7f087a2.png)

My question is, what happens for a package to be served like this ? On a completely new instance of verdaccio with a clean storage, everything goes well. But after a migration, is there something to clean up?

**Comment by Pegase745** [comment]
nevermind, found the issue with our nginx conf :) sorry for the trouble ! keep up the good work ~

**Comment by juanpicado** [comment]
no worries ! thanks @Pegase745

**Comment by pSnehanshu** [comment]
I'm having that bug. Please help [here](https://github.com/strongloop/loopback-next/issues/2441).
