### ISSUE TITLE
Show peerDependencies for Packages

### ISSUE THREAD

**Issue by fabb** [verdaccio/verdaccio#1147]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I get warnings in `npm install` about missing peerDependencies, and I would like to inspect the affected package.

**Describe the solution you'd like**
I would be immensely helpful if Verdaccio would show the `peerDependencies` of a package in the web gui as well.

**Describe alternatives you've considered**
n/a

**Additional context**
![screenshot 2018-12-04 at 12 29 50](https://user-images.githubusercontent.com/153960/49439052-51071400-f7c0-11e8-8bca-af88c73946f3.png)
_Not true and not helpful, there actually are peer dependencies needed_

**Comment by juanpicado** [comment]
@fabb it was just merged to master this week. https://github.com/verdaccio/verdaccio/pull/1144

**Comment by fabb** [comment]
Awesome, thanks! Sorry, I searched for `peerDependencies` in the issues before posting, but didn‘t find it.

**Comment by juanpicado** [comment]
:) no worries, we will release it soon.

**Comment by juanpicado** [comment]
released on `verdaccio@3.9.0`

**Comment by dkebler** [comment]
running verdaccio@4.0.0-alpha.4
and it's not there.  now come?
