### ISSUE TITLE
Is there anyway to change the sort of packages in webUI

### ISSUE THREAD

**Issue by hljwwyy123** [verdaccio/verdaccio#1163]
I see current sort rule is sort by packages name , is there anyway change the sort rule?

**Comment by juanpicado** [comment]
Nop, it's by default like that, any other preference you may share to keep it on mind?

**Comment by juanpicado** [comment]
@hljwwyy123 I need your feedback. Vote :-) 
Proposal 1: 👍 
```
web:
  sort_packages: asc | desc
```
Proposal 2 : 👀 
```
web:
  packages:
       sort: asc | desc 
```
Proposal 3 🚀 
```
web:
   sorted_packages: true (descending == true, asccending == false)
```
Or propose something different. I run out of ideas.

**Comment by juanpicado** [comment]
I'm done, just need to define the interface. 
```
  Utilities
    API utilities
      Sort packages
        ✓ should order ascending (7ms)
        ✓ should order descending (3ms)
```
