### ISSUE TITLE
[Question] Remove auth token

### ISSUE THREAD

**Issue by agalisteo** [verdaccio/verdaccio#1169]
Type: Quesion

There is any way to remove an auth token from .npmrc generated file?

We need invalidate some generated tokens.

**Comment by juanpicado** [comment]
Just change the secret field within the database (`.sinopia-db.json` or `.verdaccio-db.json`) value for something different and restart the server. 
![screen shot 2019-01-02 at 10 54 03](https://user-images.githubusercontent.com/558752/50587097-d42d8f80-0e7c-11e9-9767-29130f777f46.png)

That will invalidate all tokens in all clients.

**Comment by agalisteo** [comment]
@juanpicado Is the ability to invalidate a single user in the roadmap?

**Comment by juanpicado** [comment]
We have something in progress (https://github.com/verdaccio/verdaccio/issues/541) and in addition with `v4` JWT (JSON Web Token) you can set a expired time (https://github.com/verdaccio/verdaccio/pull/896). In `v3` the token never expires unless you change the secret key.
