### ISSUE TITLE
activedirectory authenticate() returns user name instead of group name

### ISSUE THREAD

**Issue by mlamothe** [verdaccio/verdaccio#1187]
**Describe the bug**
When using the [activedirectory](https://www.npmjs.com/package/verdaccio-activedirectory) plugin, and specifying a groupName, when the plugin authenticates the user it returns the _user name_, not the _group name_.

**To Reproduce**
1. Configure Verdaccio to use ActiveDirectory including an AD group
2. Configure package access to use the name of the AD group
3. Log into the web UI using a valid user

**Expected behavior**
I should see the packages because I authenticated as a user in the specified AD group, but it doesn't work. To see anything, I have to change the configuration's "package: access" to use my user name.

This is a problem because I want to be able to give access to anyone in the group, not to a specific user.

Also, according to [this documentation](https://verdaccio.org/docs/en/dev-plugins#callback), the plug in is supposed to return (as the second parameter) "'groups' is an array of strings where the user is part of."

**Additional context**
The source code of the plugin looks like this:
`if(isMember) {
	self._logger.info('Active Directory authentication succeeded and user is member of ' + self._config.groupName)
	callback(null, [user]);
}`
Clearly it's returning the user name and not the group name.

**Comment by juanpicado** [comment]
@mlamothe have you tried asked on his repo?. I wonder whether is intended such behavior. 

https://github.com/nowhammies/verdaccio-activedirectory/blob/master/index.js#L43 

Unfortunately I got no access to such code

**Comment by mlamothe** [comment]
There's no "Issues" tab on that project?

**Comment by mlamothe** [comment]
Okay, so I'm assuming there's no Issues tab because it's a fork of sinopia-activedirectory... and looking at that code, it also returns user instead of group (so clearly this goes back a long ways - pre Verdaccio).  I'm going to close this ticket - thanks for your help Juan.
