### ISSUE TITLE
[Feature] Add install section onto package sidebar

### ISSUE THREAD

**Issue by JacobWeyer** [verdaccio/verdaccio#1188]
**Is your feature request related to a problem? Please describe.**
A small QOL change, can we add a section on the package sidebar with a `npm install @package/name`? Many of my coworkers (especially some not as versed with the javascript ecosystem would find this extremely helpful). 

**Describe the solution you'd like**
Add a section to the package sidebar with a quick, simple copy-able command. Similar to the main npm registry.

**Describe alternatives you've considered**
The alternative would be to include a section in my README.md at the top with a simple:
```
npm install @package/name
```

It's not a huge update, but it's something simple that I think is missing to make Verdaccio as user friendly as possible. 

I'd be happy to do it myself and start being a contributor to the project with some others input on what item it should display under.

**Comment by JacobWeyer** [comment]
This makes me so happy! I'd be glad to contribute to this redesign if you need the UI help for v4! I'll probably do a little patch for v3 as well.

**Comment by juanpicado** [comment]
Sure, `v3` if you want it, I'd suggest do it on top of `Last Sync
`, following the same design and let me know if you run into troubles. For `v4` the task is already taken, thanks anyway 👍, but I'll let you know if the condition changes.

**Comment by juanpicado** [comment]
Follow up on #1195 closing this one.
