### ISSUE TITLE
verdaccio folder permission issue on ubuntu

### ISSUE THREAD

**Issue by aimarjs** [verdaccio/verdaccio#1199]
**Describe the bug**
If running verdaccio image on Ubuntu 18.04 host, docker container doesn't set proper recursive permissions for /verdaccio folder.

**To Reproduce**
1. install Ubuntu 18.04.1 and docker version 18.09.1
2. Pull and run verdaccio image
3. docker exec into to image and check ls -la for /verdaccio

**Expected behavior**
verdaccio user permissions should be set recursively 

**Screenshots**

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio/verdaccio:3.10.1 
 - Docker commands docker run verdaccio/verdaccio:latest
 - Docker Version 18.04.1

**Additional context**
Problem is that in ubuntu user management is different. Normally you do not want to work on root but under user who has sudo permissions.

**Recommended fix**
Just add su root before addgroup 

```
RUN **su root** && addgroup -S verdaccio && adduser -S -G verdaccio verdaccio && \
    chown -R verdaccio:verdaccio "$APPDIR" && \
    chown -R verdaccio:verdaccio /verdaccio
```

I don't mind to do pull request and implement the fix

**Comment by juanpicado** [comment]
@aimarjs if I'm not wrong, the new Dockerfile in `4.x` allows you to set the user. https://github.com/verdaccio/verdaccio/blob/4.x/Dockerfile#L29

**Comment by aimarjs** [comment]
@juanpicado thanks for the tip.
Is version 4.x stable enough to use in production?

**Comment by juanpicado** [comment]
Well, it is quite stable, but I cannot guarantee it 100%. 
In any case, don't use `4.x-next` tag for production, in such case `4.0.0-alpha.x` pattern. 

But as far I can see, there are no bugs on `4.x` reported and changes are mostly on UI until we do the release `4v`.

**Comment by juanpicado** [comment]
https://cloud.docker.com/u/verdaccio/repository/registry-1.docker.io/verdaccio/verdaccio/tags

**Comment by aimarjs** [comment]
Ok, let's close it. 
I fixed v3 within my own fork for now and I'll wait for the v4 release.

Thank you!
