### ISSUE TITLE
Use of crypt3

### ISSUE THREAD

**Issue by steve-p-com** [verdaccio/verdaccio#12]
There is an optional dependency on [sendanor/node-crypt3](https://github.com/sendanor/node-crypt3)

This is used for password encryption. It does not install at all on Windows. This would prevent or hamper deployment on Windows. It would also hamper contributors, because it is used in one of the tests.

A multi-platform alternative would be better.

It is actually not used in the main project. It is installed by Verdaccio, but only used by a dependency (`sinopia-htpasswd`). It is only installed by Verdaccio because one of the tests makes reference to its install location, and therefore tries to force the location. This is problematic anyway if they ever use different versions.

I think we should consider how to replace `sinopia-htpasswd` with a self-contained equivalent, which does not rely on `crypt3`. Relying on `sinopia-htpasswd` might cause problems if that project is also abandonware.

**Comment by steve-p-com** [comment]
I would like to know what people's attitude would be to pre-existing passwords not being backward compatible. I have a working `Verdaccio` using an Apache encryption replacement. It may generate different hashes though.

For anyone who has their users defined inside their `config.yaml` like this:

    users:
      test:
        password: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3
      authtest:
        password: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3

That type of password **is** backward compatible, because then we don't even use `crypt3` (it still gets installed with a load of compiler warnings though).

The issue is with the newer (and better) scheme triggered by the setting:

    auth:
      htpasswd:
        file: ./htpasswd
        # Maximum amount of users allowed to register, defaults to "+inf".
        # You can set this to -1 to disable registration.
        #max_users: 1000

When a user registers using `npm add user`, a line will then be added to the specified `htpasswd` file, like this:

    steve-p-com:$6vMMKhEVcWvs:autocreated 2016-04-20T08:20:43.474Z

It's these passwords that might become invalid. Although they may be the same on Linux, they will not be the same on OS X, and on Windows, a different scheme again is used.

A further gotcha is that if, like me, you started your original registry using `full.yaml` then you are not using the `htpasswd` mechanism. But if you instead started with `default.yaml`, then you are using `htpasswd`. That is a bit inconsistent.

So different platforms already generate different hashes and use differing schemes, so are not portable, and the defaults are inconsistent.

I propose to change `Verdaccio` to eliminate `crypt3` use and internalize `sinopia-htpasswd` which is what actually uses `crypt3`. The effects for anyone using an existing `htpasswd` file is that it might still work on Linux, but if not, the file needs to be emptied and users have to add their details again (`npm add user`).

The advantages will be consistency across platforms, zero install errors or warnings, and going forward we will be able to change the hashing scheme if necessary. I have this working already, it just needs a bit of tidying and removal of some debug code.

Thoughts?

**Comment by trentearl** [comment]
I personally use `sinopia-gitlab`, so this issue doesnt directly affect me.

That said I also agree with you, while I don't have access to a windows computer I think we should do our best to support it. Also since this verdaccio is a response to an unmaintained project it doesn't seem like a good idea to have unmaintained dependencies. We don't have a released version so I don't have a problem breaking backwards compatibility.

This does bring up and interesting question, when we publish the first version we will have to decide if it will start at `1.0.0` or if we try to follow sinopia's versions.

**Comment by steve-p-com** [comment]
OK, I will pursue the current path. I might have it all ready to go by the end of the weekend. If not, probably early next week. At that point, it should be fully cross-platform. and install with zero warnings or errors. I have not submitted the merge request for removing `fs-ext` yet because it is also used in `sinopia-htpasswd`. It makes sense to wait and do it in one, as there will be shared code.

I'm not sure what we should do about versioning. I wonder what other forks have done. Going straight to `1.0.0` makes sense from the point of view that it's an indicator that we believe it to be production-ready. Also it's more of a line in the sand that separates the old and new.
