### ISSUE TITLE
error on starting verdaccio on Mac OS X: dyld: lazy symbol binding failed: Symbol not found: _usdt_create_provider

### ISSUE THREAD

**Issue by jbeard4** [verdaccio/verdaccio#1205]
**Describe the bug**

jbeard4@Jacobs-MacBook-Pro-3:~$ npm install -g verdaccio
/Users/jbeard4/.nvm/versions/v8.12.0/bin/verdaccio -> /Users/jbeard4/.nvm/versions/v8.12.0/lib/node_modules/verdaccio/bin/verdaccio

> dtrace-provider@0.8.7 install /Users/jbeard4/.nvm/versions/v8.12.0/lib/node_modules/verdaccio/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp
+ verdaccio@3.10.2
added 210 packages from 395 contributors in 29.96s
jbeard4@Jacobs-MacBook-Pro-3:~$ verdaccio
dyld: lazy symbol binding failed: Symbol not found: _usdt_create_provider
  Referenced from: /Users/jbeard4/.nvm/versions/v8.12.0/lib/node_modules/verdaccio/node_modules/dtrace-provider/src/build/Release/DTraceProviderBindings.node
  Expected in: flat namespace

dyld: Symbol not found: _usdt_create_provider
  Referenced from: /Users/jbeard4/.nvm/versions/v8.12.0/lib/node_modules/verdaccio/node_modules/dtrace-provider/src/build/Release/DTraceProviderBindings.node
  Expected in: flat namespace

Abort trap: 6

**Comment by juanpicado** [comment]
I think this is an error in your side, I don't see any relationship with `verdaccio`, I also use Mac. Closing.

**Comment by Wdfitzpat007** [comment]
I also have this bug.

Note: I installed as cocao pod. Also, I installed the swift 3 version after the original. Could this be the problem?

**Comment by icfantv** [comment]
@juanpicado I'm also getting a similar error:
```
dyld: lazy symbol binding failed: Symbol not found: _usdt_create_provider
  Referenced from: /Users/adam.gordon/.nodenv/versions/11.9.0/lib/node_modules/verdaccio/node_modules/dtrace-provider/src/build/Release/DTraceProviderBindings.node
  Expected in: flat namespace

dyld: Symbol not found: _usdt_create_provider
  Referenced from: /Users/adam.gordon/.nodenv/versions/11.9.0/lib/node_modules/verdaccio/node_modules/dtrace-provider/src/build/Release/DTraceProviderBindings.node
  Expected in: flat namespace
```

Given that it's referencing a verdaccio dependency as the issue, I'd sort of argue (without knowing more) that it IS an issue w/ verdaccio.

**Comment by DanielRuf** [comment]
It is not an issue with / in verdaccio but dtrace-provider. Please report it at https://github.com/chrisa/node-dtrace-provider/issues.

Also see https://github.com/chrisa/node-dtrace-provider/issues/118

**Comment by juanpicado** [comment]
Furthermore, https://github.com/verdaccio/verdaccio/issues/1334 will get rid of `dtrace-provider@~0.8` soon. So this issue will became irrelevant soon.
