### ISSUE TITLE
I get this error info "tarball tarball data for XXX" 

### ISSUE THREAD

**Issue by luguidong** [verdaccio/verdaccio#1209]
**Describe the bug**
I get error info as the screenshots when I do it "npm  i" with private registry, but it's worked when I use npm registry.

**Screenshots**
![image](https://user-images.githubusercontent.com/12067418/51820403-93585780-2310-11e9-83a2-a46dda790215.png)

**Additional context**
npm version:  6.6.0
node version: 10.15.0
system: mac os 10.14.2

**Comment by juanpicado** [comment]
Have you tried with a clean storage? how does your environment looks like? I have no enough information

**Comment by luguidong** [comment]
> Have you tried with a clean storage? how does your environment looks like? I have no enough information
yes,I tried run "cache clean -f" and delete node_modules and delete .npmrc, there is not effect. it's worked when I install package one by one, and verdaccio will cache the correct package in the storage. but it's not worked when I use "npm i" and verdaccio not cache correct package version in the storage. It maybe caused by proxy config.

![image](https://user-images.githubusercontent.com/12067418/51838240-abe06600-2340-11e9-911c-dc99cee21544.png)

**Comment by luguidong** [comment]
Today,the project install echarts@4.0.4 but verdaccio cache the 4.1.0.  It's reason of previous question I guess.

**Comment by luguidong** [comment]
It worked after update node version to 10.15.0
