### ISSUE TITLE
Can I turn off storage?

### ISSUE THREAD

**Issue by ktalebian** [verdaccio/verdaccio#1218]
I'm using Verdaccio on my local machine as a mean to proxy the same scope to multiple registries. I do not want Verdaccio to cache and store the installed packages on my machine.

Is it possible to turn storage off so nothing is cached?

**Comment by juanpicado** [comment]
hi @ktalebian I have a couple of ideas on my mind, but could you tell me more about the reason if no cache anything at all?

**Comment by ktalebian** [comment]
@juanpicado mostly out of curiosity if this is possibility.

**Comment by juanpicado** [comment]
@ktalebian 
Well ... with the default setup there is a property on uplink section (https://verdaccio.org/docs/en/uplinks#configuration) to disable cache tarballs, but metadata will remains.
If you don't want I/O persistence at all, perhaps using memory for it (https://github.com/verdaccio/verdaccio-memory), by the way, we use it for functional testing in order do not cache at all.

If you are thinking more in long term, as a proxy passthrough, perhaps a custom storage plugin that does not write anything at all, including metadata.

**Comment by juanpicado** [comment]
Oh, and for authentication, also handle in memory via https://github.com/verdaccio/verdaccio-auth-memory
