### ISSUE TITLE
[doc] configuration#listen-port not working as descriped

### ISSUE THREAD

**Issue by crazyx13th** [verdaccio/verdaccio#1219]
hey there!

small hint: your write here
https://verdaccio.org/docs/en/configuration#listen-port

```
listen:
# - localhost:4873            # default value
# - http://localhost:4873     # same thing
# - 0.0.0.0:4873              # listen on all addresses (INADDR_ANY)
# - https://example.org:4873  # if you want to use https
# - "[::1]:4873"                # ipv6
# - unix:/tmp/verdaccio.sock    # unix socket
```
but this not working for me, e.g.
```
listen:
 - 162.87.5.122:4873
```

working now like descriped here (writing in one line WORKS!)
https://verdaccio.org/docs/en/server-configuration#listening-on-all-addresses
e.g with
```
listen: 162.87.5.122:4873
```

thx for this cool product!

greetings
crazyx13th

**Comment by juanpicado** [comment]
```
- 162.87.5.4873
``` 
🤔 is that a valid address?

**Comment by crazyx13th** [comment]
was only a quick example with typo :-) I Edit it...

**Comment by juanpicado** [comment]
Seems to work with my local IP. It would be great you share the error. 
```
$ verdaccio
 warn --- config file  - /Users/xxxxx/.config/verdaccio/config.yaml
 warn --- Plugin successfully loaded: htpasswd
 warn --- Plugin successfully loaded: audit
 warn --- http address - http://192.168.xx.xx:4873/ - verdaccio/4.0.0-alpha.4
```

**Comment by crazyx13th** [comment]
uff, sorry, I try to reproduce, but now it's working... maybe it was a mixure of something or I had to less coffee this time :-) pls close!

**Comment by juanpicado** [comment]
Sure :)
