### ISSUE TITLE
npm owner ls return 'admin party!'

### ISSUE THREAD

**Issue by MrGrigri** [verdaccio/verdaccio#122]
I'm trying to set an owner to our instance of Sinopia (taken from this repo). and every time I try `npm owner ls` it returns `admin party!`. Any ideas on how to add an owner or list owners of specific packages?

**Comment by juanpicado** [comment]
Related https://github.com/rlidwka/sinopia/issues/386

**Comment by juanpicado** [comment]
According this https://github.com/npm/npm/blob/1284a4f335e585f07889b01d33f980b12b4ae461/lib/owner.js#L125

The origin of that messages comes from `npm 3.10.10`
```javascript
 var owners = data.maintainers
      if (!owners || !owners.length) {
        msg = 'admin party!'
      } else {
        msg = owners.map(function (o) {
          return o.name + ' <' + o.email + '>'
        }).join('\n')
      }
      output(msg)
      cb(er, owners)
    })
````
I found out, the data received from Verdaccio never delivers `data.maintainers` and that's the origin of the bug.

**Comment by juanpicado** [comment]
`npm` doesn't include the list of maintainers if the auth is token based when you publish a package as you can see here
https://github.com/npm/npm-registry-client/blob/master/lib/publish.js#L76
```
  if (!auth.token) {
    root.maintainers = [{ name: auth.username, email: auth.email }]
    data.maintainers = JSON.parse(JSON.stringify(root.maintainers))
  }
```
That information never reaches `verdaccio` thus by default if the maintainers field is missing `npm` returns `admin party!`.  I've noticed `npm` never sends that information not even on the main npm registry if the auth is token based. It seems that data is handled internally, so, this issue rather sounds as a enhancement than a bug.
