### ISSUE TITLE
cache tarballs don't work correctly

### ISSUE THREAD

**Issue by crazyx13th** [verdaccio/verdaccio#1220]
Hey there,

I have the problem that verdaccio don't cache ALL tarballs. I don't understand when he loads/stores the tar-files and when not?

current:
![grafik](https://user-images.githubusercontent.com/8912561/52420871-2eacb200-2af3-11e9-99b0-afcf50a8e295.png)

and before ( i deleted all "cache-folders" between current and before)
![grafik](https://user-images.githubusercontent.com/8912561/52421084-9ebb3800-2af3-11e9-87e2-5b57248530f9.png)

do he remember the downloaded tars somewhere?
Thx!

Greetings
crazyx13th

**Comment by crazyx13th** [comment]
ok, sorry for wasting you time today :-)
now I got it... he only store files if npm really download it
- but npm used local cached modules (after clearing cache he store the tarballs)
- and if npm skip an optional module (no download / no tarball)

thx! &close

Greetings
crazyx13th

**Comment by juanpicado** [comment]
Interesting :) thanks for sharing
