### ISSUE TITLE
Get rid of async dependency

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#1225]
`async` is a library that I've been trying to get rid of. But unfortunately we are still using it. I want to get rid of it the two places still remain in `storage.js`. 

```
import async from 'async';
```

```
async.eachSeries(Object.keys(this.uplinks), function(up_name, cb) {
```
and
```
async.map(upLinks, (upLink, cb) => {
```
Using pure ES6, no more dependencies.

**Comment by iDaN5x** [comment]
Here's a simple implementation of both in TS:
```typescript
/* async.js */
type Iteratee<T> = (item: T) => Promise<any>;

export async function map<T>(coll: Iterable<T>, iteratee: Iteratee<T>): Promise<Array<any>> {
    const promises = [];

    for (const item of coll) {
        promises.push(item);
    }

    return Promise.all(promises);
}

export async function eachSeries<T>(coll: Iterable<T>, iteratee: Iteratee<T>): Promise<void> {
    for (const item of coll) {
        await iteratee(item);
    }
}
```

**However, I'm concerned about two possible efficiency issues:**
* The `map` function does not place a limit on the number of concurrent operations, which can cause intensive resource-consumption and even crashes on extreme cases. This applies to our usage, as the repository might contain a huge number of packages. I suggest we implement `async.mapLimit` instead.
* The `eachSeries` iterates over the collection _synchronously_ which is inefficient. A quick look at the usage tells me we might want something like `async.queue`.

Also important to mention that, depending on our `tsconfig.strictNullChecks` we might need to add null-checks to the code above.

**Comment by iDaN5x** [comment]
@juanpicado ?

**Comment by juanpicado** [comment]
Sorry, I forgot to reply @iDaN5x . Thanks for your examples, I haven't had time yet to go into this topic, but I will definitely highly value your opinion. The main reason for my request was like research whether we can replace such methods with vanilla JS. Do you have any thoughts that does not include `async` as an alternative?

**Comment by iDaN5x** [comment]
@juanpicado, no problem 😉

I mentioned the `async` methods, as they could be more fitting performance-wise. We can most definitely implement them ourselves.
However, I think we should first decide what are the correct methods to implement for our use-cases.

**Comment by juanpicado** [comment]
Sure, I appreciate that :-) for sure all options are still open. Performance is a must for me 👍 . I'll back to this topic when I finish a PR I have in progress.

**Comment by iDaN5x** [comment]
@juanpicado sure. Let me know when we can discuss this further. I would be happy to help with the implementation when we get to it.

**Comment by juanpicado** [comment]
Btw, I forgot to mention, here as well we have that problem. 
https://github.com/verdaccio/local-storage/blob/4fe314b4d401c872731880acd177a6a4cb34790c/src/local-database.ts#L72

**Comment by juanpicado** [comment]
@iDaN5x PR was merged, a good moment to address this issue.

**Comment by indiescripter** [comment]
Hi @juanpicado & @iDaN5x, just letting you know I'd be happy to throw my hat in the ring to help out disposing of `async` as well unless @iDaN5x you have taken, or want to take, ownership of this ticket.

fwiw, I've been dabbling in area of async performance fairly recently [(see here)](https://twitter.com/typeverse/status/1102563316491157504).

Pretty much my investigations conclude that async/await idiom is the slowest of all async coding idioms in JS though I have no idea how much of a hot spot the current `async` code is in verdaccio.

Anyway no problem if either of you already have a handle on completing this ticket.

**Comment by iDaN5x** [comment]
@indiescripter I appreciate your input here and your kind suggestion to help with the implementation.

**My opinion on the matter is as follows:**
The benchmarks you provided are very useful for performance-critical native-is application.
However, tanspiled application, like those who use TypeScript/Babel have the advantage of choosing the build-target rules.
What this means for Verdacio is that we can use Async/Await for code clarity and maintainability, while choosing the most performant async-code method for the transpilled code.
It is my believe that we should write new code using Async/Await, while transforming existing code to use it as well.

Putting this aside, I have recently read through the implementation of verdacio/local-storage, and believe we should actually use either NodeJs Stream or AsyncIterables.
AsyncIterables are a new standard, already supported by TypeScript & NodeJs, allowing for pull-based iterables that return values asynchronously. Together with async-generators and ‘for await’, they make for a great language feature.

I’m planning to open a detailed ticket about reimplementing local-storage soon enough on the dedicated repo. In the meantime, your thoughts would be much appreciated.

If we do decide to stay with promises (at least for now), I’ll implement the required functions this weekend.

**Comment by iDaN5x** [comment]
?

**Comment by indiescripter** [comment]
Hi @iDaN5x , yes be good to get Juan's take on this too. Spoke to him via Twitter DM other night about something else and he mentioned he's really snowed under with a bunch of things.

**Comment by juanpicado** [comment]
@indiescripter @iDaN5x sorry guys, I'll back to this as soon I have a bit of time.

**Comment by juanpicado** [comment]
> What this means for Verdacio is that we can use Async/Await for code clarity and maintainability, while choosing the most performant async-code method for the transpilled code.
It is my believe that we should write new code using Async/Await, while transforming existing code to use it as well.

@iDaN5x Agree, for me, what I most value in this projects are contributions. So a modern code base is important to make people more comfortable. For the performance side, that also important but the benchmarks do not display a big big difference IMHO. 

> I’m planning to open a detailed ticket about reimplementing local-storage soon enough on the dedicated repo. In the meantime, your thoughts would be much appreciated.

Let's open a discussion there, I'm in to move away from callback progressively in those places that make sense, I made some progress at Verdaccio, but still a lot of room for improvement. 

> Pretty much my investigations conclude that async/await idiom is the slowest of all async coding idioms in JS though I have no idea how much of a hot spot the current async code is in verdaccio.

`async/await` this mostly depends of the compiler, V8 is moving away of ES5 and as far I know (https://www.youtube.com/watch?v=r5OWCtuKiAk&feature=youtu.be&list=PL9ioqAuyl6UL-7hTmxb3WQjMwQmANbVPL) I'd recommend the BlinkOn playlist for this, ES6/7/8 is getting fast in each new V8 realease, so, that would be my main reason to use a modern code base which is the main eason why I want to get rid of `asycn` library.

But, returning to the original issue here, I just wanted to spread my voice, but, I'd need a bit more time to back to the original topic :-) , sorry for that.
