### ISSUE TITLE
this package is already present

### ISSUE THREAD

**Issue by thib3113** [verdaccio/verdaccio#1229]
**Describe the bug**
Sometimes when checking the logs, I see the error : 
```
 warn --- error saving file { url:,
   'https://registry.npmjs.org/jest-config/-/jest-config-23.6.0.tgz',,
  sha: 'f82546a90ade2d8c7026fbf6ac5207fc22f8eb1d',,
  registry: 'npmjs' }: this package is already present,
ConflictError: this package is already present,
    at Object.getConflict (/usr/local/app/build/lib/utils.js:384:37),
    at UploadTarball.writeStream.on.err (/usr/local/app/build/lib/local-storage.js:420:53),
    at UploadTarball.emit (events.js:187:15),
    at _fs2.default.exists.exists (/usr/local/app/node_modules/@verdaccio/local-storage/lib/local-fs.js:188:22),
    at suppressedCallback (fs.js:200:5),
    at FSReqWrap.oncomplete (fs.js:141:20)
```

**To Reproduce**
Not sure of the process to reproduce, but, I use verdaccio has a cache for npm registry, when using in CI . And This bug appear when I restart container verdaccio (so without any cache) .

I think it could come from multiple users (scripts in my case), requesting the same package, at the same time ?

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: latest
 - Docker commands : docker swarm with stack : 
```
  verdaccio:
    image: verdaccio/verdaccio
    ports:
     - "4873:4873"
```
 - Docker Version : 18.09.2

**Comment by juanpicado** [comment]
> I think it could come from multiple users (scripts in my case), requesting the same package, at the same time?

It seems something is trying to publish a package that already exists according to the stack trace. Perhaps the error looks scary, but it is intended to fail at that point.

**Comment by thib3113** [comment]
@juanpicado : in fact I'm just using `yarn install` In multiple projects at same time (CI) ... not publishing ( or yarn will publish something ? ) . 

I never set any user on verdaccio, and the web UI show 0 projects .
