### ISSUE TITLE
How can I get the info: who published a certain package？

### ISSUE THREAD

**Issue by StinsonZhao** [verdaccio/verdaccio#1233]
What I have got from api about the package don't include the info, that's who published the package. The `_npmUser` field is blank even though I logined and published. So how can I get this info? 

Thanks a lot.

**Comment by juanpicado** [comment]
Verdaccio does not store such info at the moment.

**Comment by StinsonZhao** [comment]
> Verdaccio does not store such info at the moment.

But in Notifications webhook, verdaccio provide 'publisher' info. So can get this info but not to save?

**Comment by juanpicado** [comment]
You might use the notification feature to call an endpoint and save it by your own (https://verdaccio.org/docs/en/notifications#metadata), but, it will be under your control, verdaccio only spread the info if there is something defined, otherwise nothing happens.

**Comment by StinsonZhao** [comment]
> You might use the notification feature to call an endpoint and save it by your own (https://verdaccio.org/docs/en/notifications#metadata), but, it will be under your control, verdaccio only spread the info if there is something defined, otherwise nothing happens.

Fine
