### ISSUE TITLE
about upgrade verdaccio 

### ISSUE THREAD

**Issue by webliving** [verdaccio/verdaccio#1235]
#### My reason:
Thank you. I want to ask questions. How to upgrade? Run commands npm update verdaccio ?
#### App Version:
3.8.5

**Comment by juanpicado** [comment]
Just install the package with the desired version (I suggest latest) .

**Comment by webliving** [comment]
so: 😃 
>> pm2 stop verdaccio
>> npm update verdaccio  -g 
>> pm2 restart verdaccio

Will it affect private packages stored in history?

**Comment by juanpicado** [comment]
No, package storage should not be affected. But, since my knowledge about your environment is limited I always suggest do a backup

**Comment by webliving** [comment]
👌 ok, thank you !

**Comment by juanpicado** [comment]
I wrote this recently, a migration guide
https://verdaccio.org/blog/2019/02/24/migrating-verdaccio
