### ISSUE TITLE
[HELP REQUEST] npm UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by Distil62** [verdaccio/verdaccio#1239]
I have a private Verdaccio server under https protocol. My certificate has been generated by certbot and recently I had to renew it. But now npm throw me a error

```
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! errno UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! request to https://myserver.com/-/v1/login failed, reason: unable to verify the first certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myusername\AppData\Roaming\npm-cache\_logs\2019-02-21T16_54_52_853Z-debug.log
```

I don't want to npm set strict-ssl false for security reason How can i fix that ?
Thank

**Comment by juanpicado** [comment]
Without disable that in the client side I am afraid we cannot do anything, that is a client side error 

https://stackoverflow.com/a/43379713/308341
