### ISSUE TITLE
uplink credentials

### ISSUE THREAD

**Issue by danielo515** [verdaccio/verdaccio#124]
Hello,

I'm using verdaccio both on raspberrypi on my local network and on a server on the cloud.
The one on the cloud it's restricted to a small collection of users. I want to be able to publish to my local verdaccio registry on my raspberry pi, and defer the publication to the cloud to it.

I have the uplink of my PI configured to point to my verdaccio running on the cloud. I have also generated a .npmrc file with the login credentials of the uplink registry.

However, I'm unable to install packages that are not on my local PI registry. The remote verdaccio is not getting the required credentials, therefore it is returning a 403 response. How can I make verdaccio pick the credentials?

Thanks in advance.

**Comment by juanpicado** [comment]
@danielo515  Could you provide any verbose log, configuration?

**Comment by danielo515** [comment]
Sure @juanpicado, what is the correct setting for verdaccio ? Just setting the level to debug is enough ?

**Comment by juanpicado** [comment]
@danielo515 for extreme debug you could do the following in each instance
```bash
DEBUG=express:* verdaccio
```
and then `npm` in verbose mode using `npm install --verbose xxxx`

**Comment by jachstet-sea** [comment]
@danielo515 When you say "you created a .npmrc file with the login credentials of the uplink registry", the registry your client uses is still your RPi, right? The verdaccio server running there won't pass the credentials provided by npm to the upstream registry. At least I wouldn't know that this is currently supported.
If you want the verdaccio server running on your RPi to authenticate against the verdaccio server running in the cloud you have to configure it that way (i.e. provide the credentials for the upstream server in your verdaccio config file). Here's an example config snippet to do so:
```uplinks:
  npmjs:
    SOMEOTHEROPTIONS
    headers:
       Authorization: "Basic dXNlcjpwYXNzd29yZA=="

**Comment by danielo515** [comment]
Dear @jachstet-sea,
Thank you for your answer. The scenario you described is almost the one I have except for one detail : mi RPI has a global .npmrc file that defined the uplink and the credentials. I thought that was enough, but since verdaccio uses plain HTTP requests it is probably not. Can I specify tokens auth instead of basic auth ? Where is the documentation of the option you mentioned ? Can I use for something that is not npmjs?

**Comment by jachstet-sea** [comment]
Yes, the verdaccio server running on the RPi won't read the .npmrc file. With the config snippet I posted, you can send any static headers to the server you like. So if your tokens are valid for a looooong time, I don't see a problem. If they are only valid for a day, you'd have to change/update the config every day which is not a good option.
The option I mentioned is "documented" in conf/full.yaml. The other option is that someone implements a proper username/password auth option in verdaccio that does not use a static header. OR a way to pass on headers provided by the client to the upstream server. But this has to be done carefully since it could leak auth credentials to servers who should not see them.

**Comment by danielo515** [comment]
Thank you @jachstet-sea 

I'll try your suggestions.

**Comment by danielo515** [comment]
Any idea about how to use npm tokens instead of basic auth? I want to get socped packages from npm

**Comment by juanpicado** [comment]
This will be shipped on `v2.4.1`. Closing this ticket.

**Comment by danielo515** [comment]
Hello @juanpicado 
What is exactly being shipped ? The ability to read a .npmrc ? What is the new feature exactly ?

Thanks in advance

**Comment by juanpicado** [comment]
@danielo515 check #332 . I'll ship as soon this milestone is completed https://github.com/verdaccio/verdaccio/milestone/13
