### ISSUE TITLE
After unpublishing a package the package can still be installed

### ISSUE THREAD

**Issue by typeversity** [verdaccio/verdaccio#1243]
**Describe the bug**
After unpublishing a package the package can still be installed

**To Reproduce**
1. Install package A that you are developing locally
2. Test that another package B that has A as a dependency installs A
3. Delete node_modules for A and B
4. Unpublish A
5. Restart verdaccio to see if problem is just a caching issue (btw I did not delete ~/.npm in case this matters)
6. cd back into B and npm install
7. Check B's package-lock.json and node_modules and see that A got installed even though was previously unpublished and does not appear in UI view

**Expected behavior**
cd back into B package and `npm install` from scratch should fail for package A not found in registry

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
cat ~/.config/verdaccio/config.yam
cat says: No such file or directory

**Additional context**

verdaccio --version
3.11.6

**Comment by KukuruzaAndrey** [comment]
if this issue doesnt appear again after `npm cache clean --force` (which clean ~/.npm), then this is not a verdaccio problem, its just npm caching packages local. (i think so)

**Comment by indiescripter** [comment]
Thanks for suggestion @KukuruzaAndrey and also @juanpicado for **waiting-user-feedback** label.

I'll rework my scenario with `npm cache clean --force` and report back, Hope this issue can be dismissed real quick.

**Comment by indiescripter** [comment]
Sorry for delay in getting back in this one, @juanpicado.

After further investigation I lean towards what @KukuruzaAndrey commented re `npm cache clean --force` but am not 100% certain as when I first ran into the problem there was also a prior version of the package in question installed in verdacchio.

This prior package had a lower semver than what got installed after unpublishing the later version (and the later version was still installed).

For expediency, for the moment, I'm happy to have this issue closed and hopefully not to be reopened unless more concrete forensics warrant it.

Thanks.

**Comment by juanpicado** [comment]
Sure @typeversity @indiescripter let me know whether you find something else. Closing :-)
