### ISSUE TITLE
Image not starting with the following configurations on Linux OS

### ISSUE THREAD

**Issue by dockeruserIndia** [verdaccio/verdaccio#1244]
When Docker-compose file has the following value, image is in constant restart mode. While if i remove the mapping **"/verdaccio/conf"** then the image is getting running fine , but i do so then i am not able to tweek the configurations to increase max_body_size. 
verdaccio:
  image: verdaccio/verdaccio:2.1 to latest
  container_name: verdaccio
  ports:
    - "4873:4873"
  volumes:
    - "/compose/verdaccio/data/storage:/verdaccio/storage"
    - "/compose/verdaccio/data/conf:/verdaccio/conf"

any suggestion on what am I doing wrong?

**Comment by risayew** [comment]
I think, that you have troubles, because latest (version 4.x) Docker image runs as
USER $VERDACCIO_USER_UID
And in version 2.1 Docker image runs as root.
I have similar issue while installing verdaccio on rancher with volumes.
To be honest, i don't understand the idea behind of running Verdaccio image with user other than root.

**Comment by juanpicado** [comment]
cc: @dlouzan

**Comment by dockeruserIndia** [comment]
Was able to run after changing permission from root to verdaccio user. Thanks so this thread is not needed so I am closing the issue .

**Comment by dlouzan** [comment]
I'm always happy when tickets are opened and closed before I have a chance to check them :-D

> To be honest, i don't understand the idea behind of running Verdaccio image with user other than root.

@risayew Running docker containers as root is by itself a bad practice, even if you are running in a virtualized environment, the same considerations apply as to any other environment, specially on shared machines. If somebody breaks your code and manages to run something as the uid of your software, root gives a much greater attack vector.

Plus, there's environments in which this is enforced, when starting up an image, your user is "downgraded" and even randomized (e.g. OpenShift).

More info:\
https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b

**Comment by risayew** [comment]
thank you for explanation @dlouzan !
