### ISSUE TITLE
Nombres de repositorios/packetes (suggest new naming for plugins and packages)

### ISSUE THREAD

**Issue by paulomcnally** [verdaccio/verdaccio#1245]
Uso `loopaback` desde hace un tiempo y he visto que los nombres de los repositorios están nombrados de la siguiente forma:

# Connector
<img width="419" alt="captura de pantalla 2019-03-06 a la s 00 46 05" src="https://user-images.githubusercontent.com/181533/53861259-4455b000-3fa9-11e9-84ea-531b69edf3a7.png">

# Component
<img width="500" alt="captura de pantalla 2019-03-06 a la s 00 46 56" src="https://user-images.githubusercontent.com/181533/53861406-c3e37f00-3fa9-11e9-9235-3b994718cf6f.png">

Y viendo la estructura de sus repositorios me topo con:

# storage

* local-storage
* verdaccio-google-cloud
* verdaccio-memory

# Propuesta:

Nombres de repositorios

* storage-local
* storage-google-cloud
* storage-memory

Nombres de paquetes

* @verdaccio/storage-local
* @verdaccio/storage-google-cloud
* @verdaccio/storage-memory

Esto deja más claro de una identificar para qué es cada repositorio.

**Comment by juanpicado** [comment]
Usually, we use English over this channel, mostly as a generic way everybody understands the topic.  We might discuss in Spanish over Discord if you wish. I'll continue in Spanish and then a copy in English.

> storage-local
> storage-google-cloud
> storage-memory

El problema, son plugins, los plugins deben tener el prefijo `verdaccio-` por SEO, usuarios facilmente pueden buscarlos en npmjs.  Quizas podamos estudiar algo asi siguiendo tu consejo, `verdaccio-storage-xxx` y lo mismo para los demas tipos de plugins.

Los paquetes `@verdaccio/` sin de publicacion restringida solo para developers autorizados (core team), lo cual invalida el uso publico, pero cualquiera pueden descargarlos.

Voy a tener encuenta el prefijo que sugieres para la version 5 de verdaccio, ya que ahora mismo es muy tarde.

The problem, plugins, they must have the prefix `verdaccio-` for SEO reasons, users easily can find them over npmjs. We might discuss following your advice `verdaccio-storage-xxx` and the same for the other sort of plugins.

The packages under `@verdaccio/` scope are restricted to be published only for authorize developers (core team), which invalidate anyone can publish over that scope, but anyone can downloaded them.

I'll keep on mind the prefix you are suggesting for version 5, for the current version 4 is too late.
