### ISSUE TITLE
All requests will be reverse proxied by nginx，including its own

### ISSUE THREAD

**Issue by tingtien** [verdaccio/verdaccio#1250]
All requests will be reverse proxied by nginx when the url_prefix is enabled. but I don't want that the Intranet requests are delegated by the nginx proxy。

**Comment by juanpicado** [comment]
It would be great have more context, I am not sure what is the reques here.

**Comment by tingtien** [comment]
![avatar](https://raw.githubusercontent.com/tingtien/issueimg/img/0312.jpg)

**Comment by ayusharma** [comment]
Hi @tingtien,

This is a very nice diagram,  Unfortunately, I am not getting clear context from it, but I'll try to explain the situation:

**I think you are facing problem with the NGINX**  
You can take a look in nginx configuration here https://github.com/verdaccio/docker-examples/blob/master/nginx-verdaccio/conf/nginx/sites-enabled/verdaccio-conf

Please give us more context of the problem. It looks like it is not the verdaccio issue.

**Comment by tingtien** [comment]
Hi @ayusharma ，
verdaccio  configuration：url_prefix: https://www.xxx.com/

npm source：https://www.xxx.com/
Such a source is allowed by the nginx proxy，That's fine.

BUT:

npm source：http://10.1.56.12:4873/
Because enable url_prefix, all requests will be reverse proxied by nginx. This is not what I want.  I want to connect directly to the target service.  I guess that first request connect directly to the target service, then verdaccio asked for nginx

thanks

**Comment by tingtien** [comment]
@juanpicado 
I have fixed bug

metadata = convertDistRemoteToLocalTarballUrls(metadata, req, config.url_prefix);

To:

let url_prefix =  config.url_prefix === '127.0.0.1' ? "" : url_prefix;
metadata = convertDistRemoteToLocalTarballUrls(metadata, req, url_prefix);

**Comment by juanpicado** [comment]
It seems you are covering a single use case, what if the IP is different? I think harcode config stuff is not a good idea.
```
let url_prefix = req.ip === '127.0.0.1' ? "" : config.url_prefix;
```

**Comment by tingtien** [comment]
@juanpicado 
that's right. There should be a filter. When the url prefix is enabled，I do not want the native IP and the IP in the filter to be reverse profiled by nginx. This is shown above

**Comment by juanpicado** [comment]
I'll close this, is to old
