### ISSUE TITLE
Prepending protocol to script src URL causes http downgrade

### ISSUE THREAD

**Issue by atkinchris** [verdaccio/verdaccio#1251]
**Describe the bug**
If `https` termination happens before a request reaches Verdaccio, the bundle links rewritten in the `index.html` file will be prepended with `http`. This will cause the browser to attempt to downgrade requests, which is not allowed in modern browsers.

This happens because the server rewrites the `index.html` file on the fly, prepending the protocol from the incoming request to the bundled asset URLs.

https://github.com/verdaccio/verdaccio/blob/28a50bfe081ceedd6aac0a94f93a098eba2ae2bb/src/api/web/index.js 

**To Reproduce**
Run Verdaccio within a container, where `https` termination happens in a layer before the service.

**Expected behavior**
Verdaccio should not rewrite the bundle URLs in `index.html`, instead allowing Webpack to provide a relative path for them.

If this is not possible, the protocol should be omitted when constructing the URL to be injected as `ToReplaceByVerdaccio`. This will allow the browser to handle protocol choices, and prevent attempts to downgrade.

**Comment by juanpicado** [comment]
I'll take of this #2122 please follow up there.
