### ISSUE TITLE
Can verdaccio use more than one CPU?

### ISSUE THREAD

**Issue by nemca** [verdaccio/verdaccio#1253]
Hi there.
I'm use verdaccio and I see that it uses only one CPU. Can verdaccio use several CPU? Or, maybe I can run some instances and add them to nginx proxy config (upstream), that will be work correctly?

**Comment by juanpicado** [comment]
No by default, you need some extra power as a different Storage API, the default file system is not good enough for scaling.
https://medium.com/verdaccio/verdaccio-3-released-feb06ef38558

Please check these threads
https://github.com/verdaccio/verdaccio/issues?q=is%3Aissue+scale+is%3Aclosed+label%3Ascale

**Comment by juanpicado** [comment]
A functional example, here 
https://github.com/verdaccio/docker-examples/tree/master/amazon-s3-docker-example

**Comment by nemca** [comment]
Thanks for answer!

**Comment by juanpicado** [comment]
I will close this, feel free to ask more or find me in our chat :)
