### ISSUE TITLE
.sinopia-db.json update with npm install

### ISSUE THREAD

**Issue by serdaryesilmurat** [verdaccio/verdaccio#1256]
.sinopia-db.json file is only updated with npm publish. "npm install" puts the packages from the global npm registry (if not exist) but .sinopia-db.json file is not updated.

Also, is there a way to fill .sinopia-db.json file from the existing storage folder content. That will really help :)

**Comment by juanpicado** [comment]
Hi @serdaryesilmurat 

`.sinopia-db.json ` only store private packages. It's intended in that way. Why would you like to have them on `.sinopia-db.json ` ?

**Comment by serdaryesilmurat** [comment]
Because verdaccio server is used as private npm server that also serves 3rd party npm modules besides our private modules. 3rd party modules are installed to another verdaccio instance with npm registry is set as uplink and then via file sync, manually files in that storage are copied to the internal verdaccio that has no internet connection. We develop our private modules using that internal verdaccio. Basically, we want to see those 3rd party npm packages on verdaccio web ui. There are many different teams using that repo. It is helpful to see whether a package (with a specific version) is served through the web ui. If I write each package name to json file (via a script probably), I can see them in web ui. I thought it would add value to verdaccio to add this feature as well. It would be shame to limit verdaccio for only serving private packages IMHO. Just a suggestion :)

**Comment by juanpicado** [comment]
>  we want to see those 3rd party npm packages on verdaccio web ui. There are many different teams using that repo. It is helpful to see whether a package (with a specific version) is served through the web ui.

I see, your request is legitimate and I agree with you, but we have a running task for it already, see here https://github.com/verdaccio/verdaccio/issues/706

We are working on it, not likely included on `4.0.0` but in the first minor releases will be. The main problem is we need to find a way to paginate packages, right now all are displayed in once shooting, not the best idea if we have to display thousands. Please let's follow up in the ticket above.
