### ISSUE TITLE
Make packages scoped with username private to that user

### ISSUE THREAD

**Issue by IRT-fbachmann** [verdaccio/verdaccio#127]
If not yet possible somehow.... Would be convenient to allow users to have their own private scope.

**Comment by juanpicado** [comment]
This will require a customizable storage + authentification that now is not possible, perhaps #376 might be an open window for someone to create customizable plugins for that.

**Comment by juanpicado** [comment]
I think via configuration file you can achieve what you were asking for. Now we can provide a follow-guide here
http://www.verdaccio.org/docs/en/protect-your-dependencies.html
