### ISSUE TITLE
Why /verdaccio/* has to be mounted separately?

### ISSUE THREAD

**Issue by takuyahara** [verdaccio/verdaccio#1274]
In docs it is said that `/verdaccio/*` should be mounted separately like this.

```
V_PATH=/path/for/verdaccio; docker run -it --rm --name verdaccio -p 4873:4873 \
  -v $V_PATH/conf:/verdaccio/conf \
  -v $V_PATH/storage:/verdaccio/storage \
  -v $V_PATH/plugins:/verdaccio/plugins \
  verdaccio/verdaccio
```

I thought that mounting `/verdaccio` like the following is enough but actually it doesn't work as expected; published package exists on container's `/verdaccio/storage/data/` but doesn't on local directory. What is the reason?

```
V_PATH=/path/for/verdaccio; docker run -it --rm --name verdaccio -p 4873:4873 \
  -v $V_PATH:/verdaccio \
  verdaccio/verdaccio
```

**Comment by juanpicado** [comment]
Hi @takuyahara, I'd suggest follow up this ticket which was the reason for such change https://github.com/verdaccio/verdaccio/issues/836
or
https://github.com/verdaccio/verdaccio/pull/864

I close this one.
