### ISSUE TITLE
Displays 'No Package Published Yet' after a package has been published

### ISSUE THREAD

**Issue by antictor** [verdaccio/verdaccio#1277]
I installed a new copy of Verdaccio and publish a namespaced package to it. The package is successfully deployed but when I goto the registry homepage it still says 'No Package Published Yet'

The package has been uploaded as I can see it on the server storage and https://npm.scropt.com/-/all shows it.

** To Reproduce **

1. Run Verdaccio in a docker container (latest production release AND 4.0.0-beta1)
2. Add a new user
3. Publish a name-spaced package '@thing/react-component-library'
4. Confirm in the console the package was deployed
5. Goto the server storage folder and confirm the package was stored
6. Goto https://my.registry.com/-/all and confirm the package appears there
7. Goto the registry home page and see the message 'No Package Published Yet.'
8. Scratch head

** Expected behavior **
I expect a page to be served, listing the packages available at the registry

**Screenshots**
<img width="872" alt="Screenshot 2019-04-17 at 12 23 09" src="https://user-images.githubusercontent.com/48056118/56284602-daced280-610c-11e9-9fcd-b6b80f7b0f2b.png">
<img width="852" alt="Screenshot 2019-04-17 at 12 22 44" src="https://user-images.githubusercontent.com/48056118/56284603-daced280-610c-11e9-955d-6591a210c30d.png">
<img width="872" alt="Screenshot 2019-04-17 at 12 24 36" src="https://user-images.githubusercontent.com/48056118/56284604-daced280-610c-11e9-88eb-114b6770be6e.png">

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
storage: /verdaccio/storage
plugins: ./plugins

web:
  title: Scropt

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@royal-navy/*":
    access: $all
    publish: $authenticated

  "@/*":
    access: $all
    publish: $authenticated
    proxy: npmjs

  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
storage: /verdaccio/storage
plugins: ./plugins

web:
  title: Scropt

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@royal-navy/*":
    access: $all
    publish: $authenticated

  "@/*":
    access: $all
    publish: $authenticated
    proxy: npmjs

  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
storage: /verdaccio/storage
plugins: ./plugins

web:
  title: Scropt

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@royal-navy/*":
    access: $all
    publish: $authenticated

  "@/*":
    access: $all
    publish: $authenticated
    proxy: npmjs

  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
storage: /verdaccio/storage
plugins: ./plugins

web:
  title: Scropt

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@royal-navy/*":
    access: $all
    publish: $authenticated

  "@/*":
    access: $all
    publish: $authenticated
    proxy: npmjs

  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
storage: /verdaccio/storage
plugins: ./plugins

web:
  title: Scropt

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@royal-navy/*":
    access: $all
    publish: $authenticated

  "@/*":
    access: $all
    publish: $authenticated
    proxy: npmjs

  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

**Comment by antictor** [comment]
My bad.. nginx reverse proxy was caching...

**Comment by juanpicado** [comment]
Thank u for the feedback @antictor
