### ISSUE TITLE
Two Network Interfaces Ethernets (eth0 uplink, eth1 internal)

### ISSUE THREAD

**Issue by lixaotec** [verdaccio/verdaccio#1279]
Dear fellows, 

I´m facing an issue regrading my npm server that has two network interfaces (eth0 for uplink, eth1 for internal).

Only eth0 has the internet conection, and eth1 has the internal lan that npm machines access.

Therefore I could not get it to work, as it seems verdaccio is using eth1 for making requests, and gets timeout err.

**To Reproduce**
Just have a two nic scenario (one for internet another for internal)

**Expected behavior**
Verdaccio should handle it? or am I missing linux config?

**Screenshots**
![image](https://user-images.githubusercontent.com/40803484/56504419-d6306280-64ee-11e9-8aa4-375b2ca97bb7.png)

**Additional context**
When I let it with one nic (the internet conection) it does works, however I end moving my internal machine to dmz (not wanted)

**Comment by lixaotec** [comment]
Dear @juanpicado , thanks for quick answer.

Well, I cannot assure its an app issue. Just got here to grab help once you-re more experienced than me.

Wish I had more Knowledge at linux, however I know that verdaccio has to grab an interface IP to listen and to request. And there could be a solution.

The setup is quite simple:
eth0: 192.168.100.10 (.1 gateway) has the internet link
eth1: 192.168.1.107 (.1 gateway) has the internal lan

Perhaps its a linux conf of packets priority. 

Appreciate any help of path for reseach, this of linux priority I was no lucky yet

thanks

**Comment by sateffen** [comment]
I think the problem has two sides.

When verdaccio does a http request without an interface specified, node will choose the default-gateway to do the request. You can check the default gateway (the output is guessed based on your information) by calling `ip route` as root:
```sh
ip route
default via 192.168.1.1 dev eth1 ...
192.168.100.0/24 dev eth0 ...
192.168.1.0/24 dev eth1 ...
```
So you could change the default gateway for your system, but that affects your complete system, so make sure you know what you're doing.

The second way is a verdaccio patch, as node can do requests over a special gateway. To do a request with another gateway than the default one, you have to pass `localAddress` as option, with the corresponding interface IP. Verdaccio uses the `request` library, but that library supports this option as well. So there could be an option added to set `localAddress` for all outgoing requests.

The first option is a solution for you personally, the second option is something like a feature-request for verdaccio, @juanpicado could evaluate that maybe.

Cheers

**Comment by lixaotec** [comment]
@sateffen 

Thank you very much. Indeed your information helped me to get it done.

In fact there were two default gateway comming from dhcp. So I struggled a bit to make it work at ubuntu 18.04.2 as there were a bug at netplan.io. I just founf ouy that upgrading netplan.io to the latest version would make the flag use-router: false for the internal lan interface.

references:
https://askubuntu.com/questions/1115213/lxd-how-to-avoid-double-default-gateway-in-ubuntu-18-04

I think that would be nice verdaccio to have this under its control, however it is upon manteiners decision.

For instance I´ll close it as I accomplish my desire, and will let under their decision to have it as a feature or not.

Thanks

**Comment by Insopitus** [comment]
@lixaotec Hi, have you encountered the issue when a client in eth1 request verdaccio and verdaccio returns a url only available in eth0? How did you solved it?

**Comment by lixaotec** [comment]
Sorry @Insopitus ..

I was trying to recall it, however i realize that I gave up that configuration of 2 interfaces. Since then, did not retry the tests.

I´ll probably try again in a near future with latest version to see if it is achievable.. and appreciate if you have done something and can share results btw

**Comment by Insopitus** [comment]
> Sorry @Insopitus ..
> 
> I was trying to recall it, however i realize that I gave up that configuration of 2 interfaces. Since then, did not retry the tests.
> 
> I´ll probably try again in a near future with latest version to see if it is achievable.. and appreciate if you have done something and can share results btw

For me, the internet interface is the default one, so I didn't meet the issue you have encountered. 

These are the other isssues I have observed:

Verdaccio randomly returns unusable links when I `npm i`.
 
The website randomly requests assets from wrong links.

In both cases, Verdaccio returns links that are only available on the other network interface.
