### ISSUE TITLE
Feature request: deprecate packages

### ISSUE THREAD

**Issue by belyan** [verdaccio/verdaccio#1280]
**Describe the bug**
I already logged as npm user and when I try to deprecate specific version of package with following command:
```
npm deprecate @scope/my-package@1.1.0-rc.0 "critical bug found"
```

I get the following error:
```
npm ERR! code E400
npm ERR! unsupported registry call : @scope/my-package
```

**Expected behavior**
This command should work as described in [documentation](https://docs.npmjs.com/cli/deprecate.html).

**Additional context**
`verdaccio -V`
2.7.4

**Comment by juanpicado** [comment]
hi @belyan 

`npm deprecate` is not supported yet (PR are Welcome 😉) and described here
https://github.com/verdaccio/verdaccio#advanced-package-control. 

Furthermore `v2.7.4` is quite old and I'd suggest a move to v3 soon, we do not provide support for v2 anymore.

**Comment by belyan** [comment]
Hi @juanpicado,

Thank you for quick response. This feature is not very important for my project right now.

As for your suggestion, I am going to migrate from 2.x to 3.x in the nearest time.

**Comment by juanpicado** [comment]
Thank u, I will leave this open as feature request, so anyone can PR and if is need it I can guide them to achieve a merge :)

**Comment by frank-dspeed** [comment]
@juanpicado ok then lets pair to get that landed it is already near done but there are a lot of questions about a lot of internal details. how can i reach you are you on gitter? https://gitter.im/ msg frank-dspeed

**Comment by detj** [comment]
Just stumbled upon this. This would be a useful feature. Often there is a need to point people to updated/different packages in a private registry setting.

**Comment by juanpicado** [comment]
It is implemented on the backend, just need UI to display the deprecated packages https://github.com/verdaccio/ui/issues/499 PR are welcome

**Comment by frank-dspeed** [comment]
@juanpicado how do we handle the sync? for example when we have a package in the registry but it got now deprecated on npm?

when we deprecate on verdaccio do we then also deprecate npm?

**Comment by juanpicado** [comment]
No, verdaccio does not change anything in remote registries, that's something you need to do on your own.

**Comment by frank-dspeed** [comment]
@juanpicado does it now inhire deprecated when it comes from the remote registry?

**Comment by juanpicado** [comment]
it should, but I don't know by heart.

**Comment by frank-dspeed** [comment]
https://github.com/verdaccio/ui/issues/67 ui related

**Comment by Amorites** [comment]
> @juanpicado does it now inhire deprecated when it comes from the remote registry?

@frank-dspeed @juanpicado Sadly deprecation status won't update at local package because of #1967.
