### ISSUE TITLE
Update Documentation: Docker User Id

### ISSUE THREAD

**Issue by molnar-ps** [verdaccio/verdaccio#1284]
Hello guys,

[in the documentation](https://verdaccio.org/docs/en/docker#running-verdaccio-using-docker) it is mentioned that the docker *verdaccio* user is using the user id 101.
Take a look at [the Docker file](https://github.com/verdaccio/verdaccio/blob/master/Dockerfile) where the user id is 10001.

So the documentation should be updated there, right?

Have a nice day y'all :)

**Comment by juanpicado** [comment]
The new UID was introduced here https://github.com/verdaccio/verdaccio/commit/9ba61c346f2f3518e4e613036c4b00059afa19c3 by @dlouzan (he is our Docker master mind 🤓 ) if there is a mistake in our docs I'm sure he can give us an answer. Perhaps we forgot to update the docs.

**Comment by juanpicado** [comment]
I will also recommend going through the Docker label https://github.com/verdaccio/verdaccio/issues?q=label%3ADocker+is%3Aclosed and check all comments while Diego reply you. Our chat is full also of information about Docker, is easy to search in Discuss and Diego has explained the new Docker image details several times over there.

**Comment by molnar-ps** [comment]
I just wanted to mention that situation. For me everything is working fine with the user id 10001 :)
Still thanks for that information.
Also, thanks for that amazing project ;)

**Comment by dlouzan** [comment]
As always I'm late to the party :-)

Yes, the documentation was wrong, the used uid is `10001`. I think it would also work with `1001`, it was just a choice of a uid that had low possibilities of being already in use by any of the possible base images.

The important part was to choose a fixed uid number that can be later overwritten by the runtime in environments that use random uid execution, such as OpenShift.

Thanks for the contribution!
