### ISSUE TITLE
DeprecationWarning when adding a user

### ISSUE THREAD

**Issue by Nautigsam** [verdaccio/verdaccio#1285]
**Bug Description**
I get a depreciation warning in the logs when adding a user.

**To Reproduce**
1. Follow logs (`docker logs -f verdaccio_container_name`)
2. Run `npm adduser`
3. See warning : 
```
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Expected behavior**
No warning.

**Screenshots**

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: **latest**
 - Docker commands `docker logs -f`
 - Docker Version **18.09.5**

**Comment by juanpicado** [comment]
hi @Nautigsam I think with the latest `beta` should not happen, could you try?

**Comment by Nautigsam** [comment]
Hey, you are right, this is resolved in beta. I close.
