### ISSUE TITLE
Plugins should get access to verdaccio's logger

### ISSUE THREAD

**Issue by moon-stripe** [verdaccio/verdaccio#1294]
**Is your feature request related to a problem? Please describe.**
Presumably we want all logging from verdaccio to go through it's logger implementation, but right now we're resorting to `console.log` (which is blocking) since plugins don't get access to verdaccio's logger. 

**Describe the solution you'd like**
```javascript
module.exports = {
  register_middlewares: (app, auth, storage, logger) => {
    app.use((req, res, next) => {
      logger.log('a log message');
      logger.warn('a warning');
    });
  }
}
```
**Describe alternatives you've considered**
```javascript
module.exports = {
  register_middlewares: (app, auth, storage) => {
    app.use((req, res, next) => {
      app.logger.log('a log message');
      app.logger.warn('a warning');
    });
  }
}
```

```javascript
const logger = require('verdaccio').logger;
module.exports = {
  register_middlewares: (app, auth, storage) => {
    app.use((req, res, next) => {
      logger.log('a log message');
      logger.warn('a warning');
    });
  }
}
```
**Additional context**

**Comment by juanpicado** [comment]
Actually, you have access to the `logger` object. A plugin cannot be a literal object, it is a function that can be constructed. eg

https://github.com/verdaccio/verdaccio-audit/blob/master/src/audit.ts#L13

**Comment by moon-stripe** [comment]
🎉
