### ISSUE TITLE
package-lock.json - Resolved field points to npmjs registry

### ISSUE THREAD

**Issue by dlarr** [verdaccio/verdaccio#1300]
**Describe the bug**
Resolved filed sometimes point to npmjs registry instead of the installed registry verdaccio (see example below)

**To Reproduce**
1. npm i on some project with a registry set to verdaccio
2. Check package-lock.json
3. Check resolved fields

Example below at screenshot section

**Expected behavior**
All resolved field should point to verdaccio registry

**Screenshots**
![image](https://user-images.githubusercontent.com/2865021/57137616-b2073800-6db0-11e9-8c3d-f282db5f2021.png)

**Docker || Kubernetes (please complete the following information):**
Not able to provide info (no acces to verdaccio installation)

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
Not able to provide info (no acces to verdaccio installation)

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
```
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\PP01-YOOP\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '-ddd' ]
npm info using npm@6.4.1
npm info using node@v8.11.3

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    completion, config, create, ddp, dedupe, deprecate,
    dist-tag, docs, doctor, edit, explore, get, help,
    help-search, hook, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, profile, prune, publish, rb, rebuild, repo, restart,
    root, run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    C:\Users\PP01-YOOP\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.4.1 C:\Users\PP01-YOOP\AppData\Roaming\npm\node_modules\npm
```
 - `$ npm config get registry` prints:
Point to our verdaccio (cf screenshot)

**Additional context**

**Comment by sergiohgz** [comment]
Please, remove lock file and node_modules. Then, ensure registry is set to your verdaccio instance and finally install again to regenerate the lock file. Ensure that every url points to verdaccio instance and not to npmjs registry

**Comment by dlarr** [comment]
Worked like a charm thanks a lot
