### ISSUE TITLE
pm2 cluster mode support

### ISSUE THREAD

**Issue by moon-stripe** [verdaccio/verdaccio#1301]
**Is your feature request related to a problem? Please describe.**
> Warning: Verdaccio does not currently support PM2's cluster mode, running it with cluster mode may cause unknown behavior.

I looked through existing open and closed issues, but couldn't figure out why that warning exists, or which versions it applies to. It looks like it was added with a 4.x beta. If we're still on 3.x, does that warning still apply?

Also, any idea what the problem is? The only discussion I saw about this was an older one before there were storage plugins.

**Comment by juanpicado** [comment]
Hi @moon-stripe 

I think the answer is here https://github.com/verdaccio/verdaccio/issues/103#issuecomment-277095781

and here you can read more about the Storage API shipped on Verdaccio 3

https://medium.com/verdaccio/verdaccio-3-released-feb06ef38558

Hope that clear your doubts!

**Comment by moon-stripe** [comment]
@juanpicado thanks for the quick response!

I didn't read that whole thread, but it looks like the warning was due to verdaccio < 3.x only having file system storage. So does that mean when using s3 storage plugin for example, the warning about using pm2 does not apply? (this makes sense to me)

If that's the case, I can contribute a PR to update that warning to clarify this.

**Comment by juanpicado** [comment]
Frankly I could not fin that warning. But here I built an example with local-stack 

https://github.com/verdaccio/docker-examples/tree/master/amazon-s3-docker-example

for scale with the S3 Storage.

**Comment by moon-stripe** [comment]
Sorry, I should have been more specific: https://github.com/verdaccio/verdaccio/blame/master/README.md#L85

**Comment by juanpicado** [comment]
Ahh, yes.  Some context (as far I know):

That's a warning for users that want to use **PM2 in cluster mode**. Not everybody is aware of how verdaccio works internally (file based) and a few years ago PM2 was a popular option, nowadays Docker/Kubernetes is the "new PM2", but still, **Verdaccio** cannot be scaled with the default storage. So the warning makes sense.

Sinopia was created with the main objective to be a local solution, but Verdaccio is evolving to be more scalable and perhaps in the future even more flexible :-) Anyhow, perhaps the message is too specific (valid for that period of time) but now might be misleading.

**Comment by moon-stripe** [comment]
@juanpicado thanks for the context. So just to make sure I understand, the pm2 in cluster mode warning only applies when you're using the default (file system) storage option? So if you're using S3 storage plugin for example, pm2 cluster mode should be ok?

**Comment by juanpicado** [comment]
> So if you're using S3 storage plugin for example, pm2 cluster mode should be ok?

Yes. :-)

**Comment by moon-stripe** [comment]
Ok, thanks!
