### ISSUE TITLE
option to force https on heroku

### ISSUE THREAD

**Issue by ilovett** [verdaccio/verdaccio#1305]
I have verdaccio running in a container on heroku running in http but can be accessed through SSL using their reverse proxy.  Their method of forcing redirect to https is like this:

https://devcenter.heroku.com/articles/http-routing#heroku-headers

> X-Forwarded-Proto: the originating protocol of the HTTP request (example: https)

method for redirecting with node/express -- see https://jaketrent.com/post/https-redirect-node-heroku/

```
  app.use((req, res, next) => {
    if (req.header('x-forwarded-proto') !== 'https')
      res.redirect(`https://${req.header('host')}${req.url}`)
    else
      next()
  })
```

**Describe the solution you'd like**

Might be great to have some way to redirect non-http to https.  Not sure what would be most flexible, a configuration option where I can say "when" to redirect, something like:

```
redirect:
  when:
    header: X-Forward-Proto
  is:
    http
  to:
     https
```

or perhaps some javascript if statement that can be `eval`ed to keep it open ended as possible

**Comment by honzahommer** [comment]
I think there is possibility to use middleware (https://verdaccio.org/docs/en/plugins#middleware-configuration) and extending config with another options is not necessary.

**Comment by honzahommer** [comment]
@ilovett Check this https://github.com/honzahommer/verdaccio-https.

**Comment by juanpicado** [comment]
Awesome !! @honzahommer

**Comment by honzahommer** [comment]
@juanpicado I think we should close this issue.

**Comment by ilovett** [comment]
Thanks @honzahommer !
