### ISSUE TITLE
Getting a 404 when npm token create

### ISSUE THREAD

**Issue by Jbonavita** [verdaccio/verdaccio#1306]
I'm trying to create a token that our Jenkins pipeline process can use to publish.

**To Reproduce**
npm token create

and I get back:

npm ERR! code E404
npm ERR! 404 Registry returned 404 for POST on https://xxxxx/-/npm/v1/tokens

for the npm password I use the default admin since we haven't changed it yet (still in the eval stage)

We're using 3.11.6

**Comment by Eomm** [comment]
Yeah, this feature is under construction

Relates to #541 and #1271
