### ISSUE TITLE
Add cache option to uplinks

### ISSUE THREAD

**Issue by silkentrance** [verdaccio/verdaccio#131]
I have here a scenario where I use one instance of verdaccio as my private registry and a second instance of verdaccio acting as a simple proxy.

Since both reside on the same network, it does not make much sense for the proxy to cache the tarballs  it gets from the private registry. (and maybe this should be extended to also the meta data)

It would be nice to be able to disable caching for specific uplinks in the proxy. For example via a  ``cache:false`` setting, e.g.

```
uplinks:
  private:
    url: ...
    # defaults to true
    cache: false
```
This will then instruct the proxy to always fetch all data from the uplink.

Similarly, and on the internal registry instance, I would then configure the proxy as an uplink, so that all requests to packages not deployed to the private registry would be resolved via the proxy, again, with ``cache: false`` being set, so that I do not pollute the private registry's local storage with packages from npmjs.com, except for the meta data of course.

What do you think?

**Comment by juanpicado** [comment]
Fixed on #132
