### ISSUE TITLE
artifact urls for scoped package format doesn't play nicely with yarn --offline

### ISSUE THREAD

**Issue by moon-stripe** [verdaccio/verdaccio#1310]
**Describe the bug**

verdaccio returns artifact urls for scoped packages that look like this:
`https://{verdaccio-url}/@babel%2fcode-frame/-/code-frame-7.0.0.tgz#06e2ab19bdb535385559aabb5ba59729482800f8`

as opposed to in public registry:

`https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.0.0.tgz#06e2ab19bdb535385559aabb5ba59729482800f8`

i.e. basically identical except verdaccio url encodes the scope/package as `@babel%2fcode-frame` instead of `@babel/code-frame`

But yarn's regex for finding packages in its offline cache don't work with this: https://github.com/yarnpkg/yarn/blob/master/src/fetchers/tarball-fetcher.js#L21

**To Reproduce**
1. `yarn add` a scoped package
2. follow steps [here](https://yarnpkg.com/blog/2016/11/24/offline-mirror/) to populate offline mirror

**Expected behavior**
Offline mirror should have all the scoped packages.

Is there a reason why verdaccio url encodes the `/` there?

**Comment by moon-stripe** [comment]
I found https://github.com/verdaccio/verdaccio/blob/master/src/api/middleware.js#L73

I assume this is to avoid writing extra routes for scoped packages, but if that's the only concern, would you accept a PR to remove that middleware and add the extra routes necessary to preserve the `/`?

**Comment by juanpicado** [comment]
@moon-stripe, to be honest, this was done even before me as a contributor, so I'd need to find out the reason of the encoded URL first. Other questions might be how pnpm or npm are handling this?

**Comment by moon-stripe** [comment]
@juanpicado afaict, npm doesn't have an equivalent offline mode. I'm not sure how pnpm's offline mode interacts. But in general, it seems best to mimc upstream npm behavior as closely as possible so as to not behaviors such as yarn's offline caching.

**Comment by juanpicado** [comment]
> Is there a reason why verdaccio url encodes the / there?

Perhaps, that's legacy code. So, first, we need to know why is encoded and whether either yarn or use owns the bug.

**Comment by juanpicado** [comment]
FYI:
https://github.com/rlidwka/sinopia/issues/104#issuecomment-120666205
https://github.com/rlidwka/sinopia/pull/275

**Comment by moon-stripe** [comment]
@juanpicado Interesting, thanks for those links! Reading through the thread and looking at the commits, it looks like it was simply the most expedient way to support scoped packages? And it seems to have caused issues with using an nginx proxy, which required some special-casing.

**Comment by juanpicado** [comment]
Exactly, so, what I'm not sure is whether that still required or not, we have some examples with NGINX https://github.com/verdaccio/docker-examples/tree/master/reverse_proxy/nginx and should be easy to try.

**Comment by DanielRuf** [comment]
cc @zkochan what would you recommend?

**Comment by zkochan** [comment]
I think it would be better if Verdaccio would use the same URL format as the npmjs.org. But pnpm works fine with the encoded URL format. pnpm normalizes the URL before saving it to the cache.

**Comment by DanielRuf** [comment]
Only yarn seems to have an issue with this.
So should we better open an issue for yarn?

**Comment by juanpicado** [comment]
@DanielRuf @zkochan I think he is aware https://twitter.com/arcanis/status/1131121028573388801

**Comment by maxx07** [comment]
I have exactly the same issue with pnpm (version 3.4.1). So as I see that isn't only an issue with yarn.

**Comment by juanpicado** [comment]
I think this can be closed https://github.com/yarnpkg/yarn/commit/b8af7e05acf965e612f2f8fafa240aa9bd069a41
https://github.com/yarnpkg/yarn/pull/7499
@moon-stripe please try again or :-) just tell me so I can close this ticket.
