### ISSUE TITLE
\@ in web.scope causes JSON.parse error?

### ISSUE THREAD

**Issue by Codelica** [verdaccio/verdaccio#1316]
**Describe the bug**
Use of configuration variable web.scope seems to have changed(?).

**To Reproduce**
Launch container with config.yml that includes:

```yaml
web:
  scope: \@something
```

**Expected behavior**
Should use that scope as part of instructions header. 

**Screenshots**
JSON.parse fails resulting in error and blank Web interface.

<img width="489" alt="Codelica NPM Registry 2019-05-19 13-47-55" src="https://user-images.githubusercontent.com/386101/57987301-ce57d580-7a3c-11e9-98ab-a9d1c877f9f4.png">

<img width="1762" alt="Codelica NPM Registry 2019-05-19 13-51-40" src="https://user-images.githubusercontent.com/386101/57987361-9ef59880-7a3d-11e9-9f2d-1abe5884854b.png">

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: 4.x-next

**Additional context**
This worked fine as of alpha-6. Updating to beta-8 is when the error appeared.  If there was a change made to the config required, I couldn't find it?  Just going off this page that still says \@scopename : https://verdaccio.org/docs/en/webui

**Comment by Codelica** [comment]
Just quoting the string seems to work fine:

```yaml
web:
  scope: "@something"
```

**Comment by juanpicado** [comment]
Thanks @Codelica  . I update the docs. Closing this.
