### ISSUE TITLE
Different resolved field content when using Verdaccio (urlencoded slash)

### ISSUE THREAD

**Issue by DanielRuf** [verdaccio/verdaccio#1325]
**Describe the bug**
Currently when I run `yarn --registry https://registry.npmjs.org` I get the correct `resolved` field, for example `https://registry.npmjs.org/@webassemblyjs/floating-point-hex-parser/-/floating-point-hex-parser-1.8.5.tgz#1ba926a2923613edce496fd5b02e8ce8a5f49721`.

When I use `yarn --registry http://localhost:4873` the field is now changed to `http://localhost:4873/@webassemblyjs%2ffloating-point-hex-parser/-/floating-point-hex-parser-1.8.5.tgz#1ba926a2923613edce496fd5b02e8ce8a5f49721`.

It seems there is some encoding issue as `%2f` is `/`.

**To Reproduce**
1. Run `yarn --registry https://registry.npmjs.org`
2. `git add yarn.lock`
3. `rm yarn.lock`
4. `yarn --registry http://localhost:4873`
5. `git diff`

**Expected behavior**
The paths in `resolved` should be the same.

**Additional context**
```
verdaccio --version
4.0.0-beta.8
```

**Comment by NathanaelA** [comment]
Appears to be related to #1310

**Comment by DanielRuf** [comment]
Ah, thanks for the hint. I'm going to close my issue then.
