### ISSUE TITLE
Uplink connection timeout returns incorrect status code

### ISSUE THREAD

**Issue by ianschmitz** [verdaccio/verdaccio#1328]
This issue may be related to #720.

**Describe the bug**
We discovered this issue while porting `create-react-app` over to Azure DevOps build pipeline (https://github.com/facebook/create-react-app/pull/7096). If a connection to the uplink (e.g. `registry.npmjs.org`) times out, Verdaccio returns a `404` status code, which causes the npm/yarn client to fail.

**Expected behavior**
Verdaccio should return a `503` status code which tells the npm/yarn client to try again.

@willsmythe helped us fix this in a fork of his. You can see the diff here: https://github.com/verdaccio/verdaccio/compare/master...willsmythe:fix-404-on-uplink-timeout.

**Comment by juanpicado** [comment]
Thanks @ianschmitz the commit provided have really interesting things, I'll check it myself.

**Comment by willsmythe** [comment]
I just pushed a few updates to my branch and will open a PR so we can discuss the changes.
