### ISSUE TITLE
Expose HTTP Agent options

### ISSUE THREAD

**Issue by ianschmitz** [verdaccio/verdaccio#1329]
**Is your feature request related to a problem? Please describe.**
We discovered the need to supply custom HTTP Agent options when using Verdaccio to work around some issues we experienced while porting Create React App over to Azure DevOps build pipeline (https://github.com/facebook/create-react-app/pull/7096). Specifically we needed to enable `keepAlive`, and restrict the number of sockets used by Verdaccio when connecting to an uplink (registry.npmjs.org). This allowed us to work around Azure VM specific issue caused when too many sockets are opened. See https://docs.microsoft.com/en-us/azure/app-service/app-service-web-nodejs-best-practices-and-troubleshoot-guide#my-node-application-is-making-excessive-outbound-calls for more context.

**Describe the solution you'd like**
Allow specifying the HTTP Agent options. @willsmythe worked around this for us in a fork of his by hard coding the `agentOptions` like such: 

> ```diff
>     const req = request(
>       {
>         url: uri,
>         method: method
>         headers: headers,
>         body: json,
>         ca: this.ca,
>         proxy: this.proxy,
>         encoding: null,
>         gzip: true,
>         timeout: this.timeout,
>         strictSSL: this.strict_ssl,
> +       agentOptions: {
> +         keepAlive: true,
> +         maxSockets: 40,
> +         maxFreeSockets: 10
> +       }
> ```

**Comment by juanpicado** [comment]
@ianschmitz I've been following your thread, looks good to me, would you like to PR?

**Comment by willsmythe** [comment]
Opened #1332, and will open a doc PR as well.

**Comment by willsmythe** [comment]
Hi @juanpicado - can you take a look at my question in the PR about the general approach being proposed to solve this? See https://github.com/verdaccio/verdaccio/pull/1332#issuecomment-496959264

**Comment by juanpicado** [comment]
Thanks for the extended info provided, give me some days to review this.

**Comment by juanpicado** [comment]
@willsmythe done :-) LGTM
