### ISSUE TITLE
ERROR integrity checksum failed when using sha1

### ISSUE THREAD

**Issue by kimphi** [verdaccio/verdaccio#1330]
When installing @vue/cli from  Verdaccio registry,it always report a bug,Here's an example of a failed install:
 
![image](https://user-images.githubusercontent.com/12759862/58541127-61f38800-822d-11e9-9383-0f5ea240078b.png)

**Comment by kimphi** [comment]
verdaccio version is 4.0.1
error Report as picture shown

**Comment by juanpicado** [comment]
Does it happen with other libraries?
Have you clean local cache?
Have you try to remove the affected dependency from the shortage and try again to install?

I’ve seen this error on other tickets, I would suggest you take a look how they have solved it.

**Comment by kimphi** [comment]
![image](https://user-images.githubusercontent.com/12759862/58619739-0fcb6900-82f8-11e9-856a-25f70d60e57b.png)
I have clean local cache,but it can't fixed.
This error happen with few libraries
