### ISSUE TITLE
Doc needs up date for https & docker

### ISSUE THREAD

**Issue by ghost** [verdaccio/verdaccio#1337]
**Describe the bug**
https://verdaccio.org/docs/en/ssl is outdated in regards to the docker environment variable names that have been renamed in 4.0:
```
If you are using the Docker image, you have to set the PROTOCOL environment variable to https, as the listen argument is provided in the Dockerfile and thus ignored from your config file.

You can also set the PORT environment variable if you are using a port other than 487
```

**To Reproduce**
see the url https://verdaccio.org/docs/en/ssl

**Expected behavior**
Fix the environment variables from `PROTOCOL` to `VERDACCIO_PROTOCOL` and `PORT` to `VERDACCIO_PORT` according to https://verdaccio.org/blog/2019/02/24/migrating-verdaccio.

**Comment by DanielRuf** [comment]
Hi @stefanheine,

Thanks for reporting this.

Do you want to provide a PR? The file which has to be updated is https://github.com/verdaccio/website/blob/master/docs/ssl.md

**Comment by stefanheine** [comment]
ok: https://github.com/verdaccio/website/pull/139

**Comment by DanielRuf** [comment]
Closing as resolved. Thanks for your contribution to Verdaccio.
