### ISSUE TITLE
Update dayjs

### ISSUE THREAD

**Issue by DanielRuf** [verdaccio/verdaccio#1339]
**Describe the bug**
> warning verdaccio > dayjs@1.8.13: critical bug fixed in v1.8.14 .format API retu
rns UTC offset when value is 0

**To Reproduce**
1. `yarn global add verdaccio`

**Expected behavior**
No warnings.

**Comment by juanpicado** [comment]
Make sense to me

**Comment by juanpicado** [comment]
I already update to the latest version, could you check wether we can close this one?
