### ISSUE TITLE
Verdaccio Installing on IIS server: Can not find iisnode-verdaccio on npmjs

### ISSUE THREAD

**Issue by khanh-h-nguyen** [verdaccio/verdaccio#1345]
As I browse npmjs.com to look for iisnode-verdaccio, I could no longer find it.  Any ideas?

**Comment by DanielRuf** [comment]
Hi @khanh-h-nguyen,

The package does not seem to have existed at all. See https://www.npmjs.com/package/iisnode-verdaccio

**Comment by DanielRuf** [comment]
Please see https://verdaccio.org/docs/en/iss-server which describes an example package that you have to create. The `iisnode-verdaccio` name field is just an example.

**Comment by khanh-h-nguyen** [comment]
On that site:  https://verdaccio.org/docs/en/iss-server, it shows how to set up verdaccio on iis web server.  So iisnode-verdaccio is inside the package.json.  I don't see it as just an example package that I have to create.
{
  "name": "iisnode-verdaccio",
  "version": "1.0.0",
  "description": "Hosts verdaccio in iisnode",
  "main": "start.js",
  "dependencies": {
    "verdaccio": "^3.11.0"
  }
}

**Comment by DanielRuf** [comment]
Hi @khanh-h-nguyen,

you can put anything into the `"name"` field. It does not really matter What matters is the following:

```
"dependencies": {
"verdaccio": "^3.11.0"
}
```

**Comment by DanielRuf** [comment]
The needed script files are on the same page (start.js and so on).

**Comment by khanh-h-nguyen** [comment]
Reading the instructions on : https://verdaccio.org/docs/en/iss-server makes me think that the below steps are all required steps to set up verdaccio on iis server instead of being an example.

These instructions were written for Windows Server 2016, IIS 10, Node.js 10.15.0, iisnode 0.2.26 and verdaccio 3.11.0.

- Install IIS Install iisnode. Make sure you install prerequisites (Url Rewrite Module & node) as explained in the instructions for iisnode.
- Create a new folder in Explorer where you want to host verdaccio. For example C:\verdaccio. Save package.json, start.js and web.config in this folder.
- Create a new site in Internet Information Services Manager. You can name it whatever you want. I'll call it verdaccio in these instructions. Specify the path to where you saved all files and a port number.
- Go back to Explorer and give the user that runs the application pool modify rights to the folder you just created. If you've named the new site verdaccio and did not change the app pool, it's running under an ApplicationPoolIdentity and you should give the user IIS AppPool\verdaccio modify rights see instructions if you need help. (You can restrict access later if you want so that it only has modify rights on the iisnode and verdaccio\storage)
- Start a command prompt and execute the commands below to download verdaccio: npm install

If you say that package.json is just an example, then I still don't see how we would install verdaccio.

**Comment by khanh-h-nguyen** [comment]
Now I am confused...
I thought I could cache npm packages into a private network site like: http://privatenetworkste/verdaccio

**Comment by DanielRuf** [comment]
> I thought I could cache npm packages into a private network site like: http://privatenetworksite.com/verdaccio

Yes. But you have to run verdaccio behind this using NodeJS. So you need a package.json with `verdaccio` as dependency and the given `start.js` file too and so on.

**Comment by DanielRuf** [comment]
The 3 needed files are under the text:

https://verdaccio.org/docs/en/iss-server#packagejson
https://verdaccio.org/docs/en/iss-server#startjs
https://verdaccio.org/docs/en/iss-server#webconfig

**Comment by khanh-h-nguyen** [comment]
I see C:\verdaccio binding to http://privatenetworksite.com/verdaccio and that supports just one npm package because the way package.json is specified.  How do we set up so one entry point http://privatenetworksite.com/verdaccio support multiple npm packages?

**Comment by DanielRuf** [comment]
> I see C:\verdaccio binding to http://privatenetworksite.com/verdaccio

This is the entry point of your verdaccio instance. Did you actually run `node start.js` on the server in this folder? It should provide you with the needed port.

**Comment by DanielRuf** [comment]
> I stopped the "Default Web Site" and only start the site "verdaccio" site in IIS
> I set the bindings to "http", ip address "All Unassigned" on port 80, ok any warning or prompts

And also see the config file.

**Comment by khanh-h-nguyen** [comment]
Make progress. But get an error:


HTTP Error 500.19 - Internal Server Error

The requested page cannot be accessed because the related configuration data for the page is invalid.



Detailed Error Information:



Module
   IIS Web Core 

Notification
   BeginRequest 

Handler
   Not yet determined 

Error Code
   0x80070021 

Config Error
   This configuration section cannot be used at this path. This happens when the section is locked at a parent level. Locking is either by default (overrideModeDefault="Deny"), or set explicitly by a location tag with overrideMode="Deny" or the legacy allowOverride="false".  

Config File
   \\?\C:\npmpackage\web.config 



Requested URL
   http://localhost:80/npmpackage/ 

Physical Path
   C:\npmpackage\ 

Logon Method
   Not yet determined 

Logon User
   Not yet determined 




Config Source:
    8:     to be handled by the iisnode module -->
    9:     <handlers>
   10:             <remove name="WebDAV" />




More Information:
This error occurs when there is a problem reading the configuration file for the Web server or Web application. In some cases, the event logs may contain more information about what caused this error. 
View more information »

**Comment by khanh-h-nguyen** [comment]
Thanks, DanielRuf.  You guide me to the right direction.  This thread can be closed for this particular question.

**Comment by juanpicado** [comment]
Thanks @khanh-h-nguyen for the feedback and @DanielRuf 🥇 for the good support.
