### ISSUE TITLE
WebUI: requested an insecure script 

### ISSUE THREAD

**Issue by nevernet** [verdaccio/verdaccio#1346]
**Describe the bug**
verdaccio is behind the nginx 

when open site: `https://reigistry.example.com`, then got error from console: 
```
Mixed Content: The page at 'https://registry.example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://registry.example.com/-/static/0.style.cdd1fdf79cd6bec30c42.css'. This request has been blocked; the content must be served over HTTPS.
```

nginx configuration: 
```
server
{
    listen       443;
    ...

    location / {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass http://10.0.2.201:4873;
      proxy_redirect off;
    }


}
```

please help

**Comment by juanpicado** [comment]
@nevernet in this example I use `$host` instead, it works for me. Have you tried that?

https://github.com/verdaccio/docker-examples/blob/master/reverse_proxy/nginx/relative_path/nginx_ssl/nginx-default.conf#L23

**Comment by nevernet** [comment]
@juanpicado it does not work for me. 

nginx server is on 10.0.2.10
npm server is on 10.0.2.201: 4873

is there a problem?

**Comment by juanpicado** [comment]
I think you would need to provide more info, verdaccio version, configuration, otherwise would take ages to find the reason.  Please follow the https://github.com/verdaccio/verdaccio/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md issue template.

**Comment by DanielRuf** [comment]
> proxy_pass http://

Isn't this the problem?

**Comment by juanpicado** [comment]
That might be ... it was my first clue, we will see.

**Comment by nevernet** [comment]
@DanielRuf not exactly :) 

i have been enabled `http` access, and then everything well

@juanpicado maybe we need to add new configuration option for how to load static files
