### ISSUE TITLE
Option to only call uplink if package is missing/not in cache

### ISSUE THREAD

**Issue by jose-pr** [verdaccio/verdaccio#1348]
**Is your feature request related to a problem? Please describe.**
I want to use Verdaccio to mirror npmjs on a place with a laggy and slow internet connection to improve downloads.

**Describe the solution you'd like**
An option on package/uplink that if a package/version requested has already been cached before dont make any calls to uplinks.
Or create a timer or service that calls periodically (user set?  daily/hourly) to check for new versions of the cached packages and not do it every time a user ask verdaccio for a package/info to speed up performance/download. 

**Describe alternatives you've considered**
Is there something i can do to force this behavior?

**Comment by juanpicado** [comment]
Unfortunately, this feature is not possible. Uplinks are "all or nothing" feature. If you want to know more feel free to ask, I'm closing this.
