### ISSUE TITLE
Verdaccio Installing on iis: How is config.yaml created?

### ISSUE THREAD

**Issue by khanh-h-nguyen** [verdaccio/verdaccio#1350]
After I follow the instructions on https://verdaccio.org/docs/en/iss-server, I don't see config.yaml get created.  
When I open the page http://myprivatenetworksite.com/verdaccio, the page shows the error:
"iisnode encountered an error when processing the request".
I check the folder iisnode and see stdout text file indicating:
"fatal ---- cannot open config file C:\...\config.yaml: ENOENT: no such file or drectory, open 'C:\....\config.yaml'.

According to the instructions, this config.yaml should be generated.  I don't know when this file is generated and how to debug the issue.
Can you guide me how to debug the issue of config.yaml not being generated?

**Comment by DanielRuf** [comment]
Hi @khanh-h-nguyen,

Thanks for reporting this. I think the docs are outdated. Verdaccio automatically creates a config. You can see the path when you manually start Verdaccio.

**Comment by khanh-h-nguyen** [comment]
For Verdaccio installing on iis, Verdaccio is installed into node_modules folder like C:\InstalledFolder\node_modules\verdaccio.   C:\InstalledFolder is bound to http://myprivatenetwork.com/InstalledFolder.   I thought that node.js and iis server somehow work together to run start.js and generate the config.yaml file. 
I don't know if we can start Verdaccio manually when it is installed on iis server because  I try to execute CLI "verdaccio" at any levels of the folder path, but the system seems not to recognize "verdaccio".

**Comment by khanh-h-nguyen** [comment]
Now I read the instructions again:
**Installing on IIS server**
These instructions were written for Windows Server 2016, IIS 10, Node.js 10.15.0, iisnode 0.2.26 and verdaccio 3.11.0.

I manually install Node.js and iisnode.  But for verdaccio, I follow the instructions and somewhere in the instructions, it says:
Start a command prompt and execute the commands below to download verdaccio:
cd c:\verdaccio
npm install

For verdaccio installing on iis server, I did not manually execute on CLI: npm install -g verdaccio

**Comment by DanielRuf** [comment]
Verdaccio 4 is a bit different. Try `node ./node_modules/.bin/verdaccio` to manually start it.

**Comment by DanielRuf** [comment]
Just follow the instructions.

**Comment by khanh-h-nguyen** [comment]
node .\node_modules\.bin\verdaccio
C:\npmpackage\node_modules\.bin\verdaccio:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by khanh-h-nguyen** [comment]
I manually execute "verdaccio" in c:\\installedfolder\\node_modules\\.bin and the execution works fine.
Config.yaml gets generated under ...\\Appdata\\Roaming\\... folder
The page http://localhost:4873 works.

However when browsing to http://myprivatenetwork.com/verdaccio.  It still complains about not able to find c:\\InstalledFolder\\config.yaml. 
My first question is if I can use that config.yaml file in ...\\Appdata\\Roaming\\... folder for the issue on http://myprivatenetwork.com/verdaccio.

My second question is: What script try to access to c:\\InstalledFolder\\config.yaml? I can modify that to point to the config.yaml inside ...\\Appdata\\Roaming\\...

**Comment by khanh-h-nguyen** [comment]
I copy config.yaml generated from:  execute "verdaccio" in c:\\installedfolder\\node_modules\\.bin 
into the Installedfolder which is  bound  to iis and the  http://myprivatenetwork.com/verdaccio page returns:
{
   "error": "no such package available"
 }

**Comment by DanielRuf** [comment]
> Config.yaml gets generated under ...\Appdata\Roaming\... folder
> The page http://localhost:4873 works.
> 
> However when browsing to http://myprivatenetwork.com/verdaccio. It still complains about not able to find c:\InstalledFolder\config.yaml.

Try to copy the generated file from `...\Appdata\Roaming\...` and use this =)

**Comment by DanielRuf** [comment]
> {
> "error": "no such package available"
> }

This should be fine by default as you have no package `verdaccio` in there. Please check your current config of the entry path / hostname where the server runs.

**Comment by DanielRuf** [comment]
> My second question is: What script try to access to c:\InstalledFolder\config.yaml? I can modify that to point to the config.yaml inside ...\Appdata\Roaming\...

The start.js file uses it.

**Comment by khanh-h-nguyen** [comment]
> > {
> > "error": "no such package available"
> > }
> 
> This should be fine by default as you have no package `verdaccio` in there. Please check your current config of the entry path / hostname where the server runs.
> 
> Try http://myprivatenetworksite.com/ for the registry endpoint of Verdaccio.

Since  the three files start.js, package.json, and web.config inside c:\InstalledFolder which is bound to http://myprivatenetworksite.com/verdaccio, so I expect http://myprivatenetworksite.com/verdaccio would be the entry point just like http://localhost:4873 - showing a verdaccio package admin page.

Instead http://myprivatenetworksite.com/verdaccio shows
{
"error": "no such package available"
}

**Comment by DanielRuf** [comment]
Not sure about this one. In general the error is not quite clear. What do the logs say?

**Comment by khanh-h-nguyen** [comment]
warn --- config file - C:\npmpackage\config.yaml
warn --- Plug successfully loaded: verdaccio-htpasswd
warn --- Plug successfully loaded: verdaccio-audit
warn --- http address - unix:\\.pipe\******************************* - verdaccio/4.0.1
http ---> ERR, req: 'GET https://registry.npmjs.org/npmpackage', error: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
http <-- 404, user: null(undefined), req: 'GET /npmpackage', error: no such package available

**Comment by DanielRuf** [comment]
https://registry.npmjs.org/npmpackage so somwhere it tries to fetch the package `npmpackage` which does not exist.

**Comment by DanielRuf** [comment]
https://registry.npmjs.org/npmpackage so somewhere it tries to fetch the package `npmpackage` which does not exist.

**Comment by khanh-h-nguyen** [comment]
"npmpackage" is the local folder name of my environment named c:\npmpackage and the URL  path  http://myprivatenetworksite.com/npmpackage.
I don't know how that folder name is concatenated into https://registry.npmjs.org.

**Comment by khanh-h-nguyen** [comment]
Another log file along with the error above:
(node:9752) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues.  Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by DanielRuf** [comment]
> DeprecationWarning

Just a warning and can be ignored =)

**Comment by DanielRuf** [comment]
> DeprecationWarning

Just a warning and can be safely ignored =)

**Comment by khanh-h-nguyen** [comment]
DanielRuf,
Don't know what happens but now I try http://myprivatenetworksite.com/ (without npmpackage on the path) for the registry endpoint of Verdaccio, it shows like a registry endpoint.

Though it works, I'd like to understand how the registry endpoint is on http://myprivatenetworksite.com instead of http://myprivatenetworksite.com/npmpackage.  And nothing on the documentation is mentioned this.

Also, I am willing to update the docs "Installing on IIS" to help others in the future, if I can understand.   Some of instructions seem to have missing steps or details which lead me to this thread.

**Comment by khanh-h-nguyen** [comment]
To be clear and up to date: 
* Browsing to: http://myprivatenetworksite.com/ now shows the registry page.  Look good.
* Browsing to:  http://myprivatenetworksite.com/npmpackage, the log says:
http ---> ERR, req: 'GET https://registry.npmjs.org/npmpackage', error: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
http <-- 404, user: null(undefined), req: 'GET /npmpackage', error: no such package available
warn ---> host registry.npmjs.org is now offline


The last line in the log is understandable, because my server is disconnected from Wifi or any WWW network.

**Comment by khanh-h-nguyen** [comment]
The instructions  https://verdaccio.org/docs/en/iss-server might miss the step to require the user to run:
npm set registry http://myprivatenetworksite.com/

For experienced users, that might not be necessary.  But for new users, we are not aware of that.
That might be the reason, we see:
```
http ---> ERR, req: 'GET https://registry.npmjs.org/npmpackage', error: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
http <-- 404, user: null(undefined), req: 'GET /npmpackage', error: no such package available
warn ---> host registry.npmjs.org is now offline
```

**Comment by khanh-h-nguyen** [comment]
I tried the command:
npm set registry http://myprivatenetworksite.com/
and then rebooted the server.
However, after logging and browsing the page http://myprivatenetworksite.com/npmpacakge,  the log still says:

> http ---> ERR, req: 'GET https://registry.npmjs.org/npmpackage', error: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443

**Comment by khanh-h-nguyen** [comment]
I think the browse cache causes the issue.  After having another reboot, it no longer shows error above.

Thanks  DanielRuf for helping me on this issue.

I will review the issues I have encountered and have resolved and will post a thread on an up to date docs "Installing on IIS".  I would say most of instructions on docs "Installing on IIS" are useful but it just misses to guide the users on a few steps or deal with some scenarios which experienced users can resolve and not document.

**Comment by juanpicado** [comment]
@khanh-h-nguyen would be great if you document your experience updating the documentation? https://github.com/verdaccio/website/blob/master/docs/iis-server.md
