### ISSUE TITLE
Set config.server.keepAliveTimeout to 0 should disable keep-alive

### ISSUE THREAD

**Issue by toddwong** [verdaccio/verdaccio#1352]
It seems setting config.server.keepAliveTimeout to 0 doesn't disable keep-alive, but using the default value (5000ms according to the nodejs doc).

https://github.com/verdaccio/verdaccio/blob/e40083a6be4abf1a3539b776d3a4053f484e0002/src/lib/bootstrap.js#L51

**Comment by DanielRuf** [comment]
Hi @toddwong,

> server.keepAliveTimeout to 0

This evaluates to false as it seems.

**Comment by toddwong** [comment]
@DanielRuf 

Yes, and leaves the webServer.keepAliveTimeout untouched.  But I want setting it to 0 instead.

**Comment by DanielRuf** [comment]
Please see the `FIXME` line and https://github.com/verdaccio/verdaccio/blob/master/conf/default.yaml#L69

**Comment by DanielRuf** [comment]
The fallack seems to be the NodeJS default when it is `0`.

Otherwise we have to do a `typeof === "undefined"` check.

https://github.com/verdaccio/verdaccio/blob/e40083a6be4abf1a3539b776d3a4053f484e0002/src/lib/bootstrap.js#L52

**Comment by DanielRuf** [comment]
Default is `5000` (= 5 seconds). https://nodejs.org/api/http.html#http_server_keepalivetimeout

**Comment by DanielRuf** [comment]
I'll propose a PR based on

> A value of 0 will disable the keep-alive timeout behavior on incoming connections. A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.

**Comment by DanielRuf** [comment]
Please check out https://github.com/verdaccio/verdaccio/pull/1353

**Comment by toddwong** [comment]
Thanks @DanielRuf 

Very looking forward to the release

**Comment by DanielRuf** [comment]
If you need it earlier you can use `patch`, `git apply` or `patch-package` with https://github.com/verdaccio/verdaccio/pull/1353.patch or https://github.com/verdaccio/verdaccio/pull/1353.diff

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/releases/tag/v4.0.4
