### ISSUE TITLE
How does caching work in Verdaccio?

### ISSUE THREAD

**Issue by khanh-h-nguyen** [verdaccio/verdaccio#1355]
Let's say I have verdaccio already set up on IIS server.  My system is online connecting to https://registry.nmpjs.org 
At the folder containing config.yaml , I issue the command "npm i  glob".  I check and see glob and its six dependency packages and their sub-dependency packages get installed into nodes_modules.
However, I don't see any npm packages of glob and its dependency packages showing on the http://localhost:xxxx registry point or see anthing inside ./storage folder.

I thought as I run "npm i glob", the npm packages would be pulled to local from http://npmjs.com/ and then cache (store into ./storage) and publish into the local registry http://localhost:xxxx.

I see the documentation mentioning about caching but it does not go into the details of explaining what happens as "npm i glob" executes.

**Comment by DanielRuf** [comment]
Hi @khanh-h-nguyen,

you can go to localhost/glob.
The UI lists only packages published by you.
The storage folder contains all cached packages.

**Comment by DanielRuf** [comment]
Also see https://verdaccio.org/docs/en/webui

**Comment by khanh-h-nguyen** [comment]
@DanielRuf,
I don't see anything relating to "glob" or its dependencies inside storage folder.
Do I need to run anything else to see them there?

And  localhost/glob just says:
{
   "error": "no such package available"
}

**Comment by khanh-h-nguyen** [comment]
> Also see https://verdaccio.org/docs/en/webui
> 
> > Verdaccio has a web user interface to display only the private packages

Can we publish locally the pacakges which we get from npmjs.com?

**Comment by khanh-h-nguyen** [comment]
One question:
Right now, though http://localhost  registry just shows the private packages, does it know anything about packages which we install from npmjs.com?

**Comment by DanielRuf** [comment]
Well, did you run `npm install glob --registry https://localhost:...` in any other directory outside of this project?

**Comment by DanielRuf** [comment]
> does it know anything about packages which we install from npmjs.com?

Yes, it proxies them. Go to the web ui and then to `/glob` or `/-/web/detail/glob`.

> Can we publish locally the packges which we get from npmjs.com, to show them at the registry endpoint http://locahost:xxx?

This makes not much sense.

**Comment by khanh-h-nguyen** [comment]
> Well, did you run `npm install glob --registry https://localhost:...` in any other directory outside of this project?

I don't recall if I did but I might.
Can you expalin what if I did run that command in any other directory outside of this project?

**Comment by DanielRuf** [comment]
Well, it makes not much sense to install some packages into the node_modules of verdaccio unless you want to extend it.

With the right `--registry` flag value your storage should be filled.

**Comment by DanielRuf** [comment]
> Can you explain what if I did run that command in any other directory outside of this project?

Not relevant where this happens but the `--registry` part is important.

**Comment by khanh-h-nguyen** [comment]
When I run "npm i glob --registry http://locahost:xxxx", is package.json residing that direcotry relevant or has anything to do  with the execution?  I ask because after I run that command, it generates a file called package-lock.json file containing lots of dependencies.  I don't know if that file package-lock.json is the result of that command "npm i glob --registry http://locahost:xxxx" or verdaccio or both?

**Comment by DanielRuf** [comment]
The lockfile (package-lock.json for npm, yarn.lock for yarn) is generated by the client, npm in thus case.

Also see https://docs.npmjs.com/files/package-locks

In the background the requests go through the provided registry that you have defined in some .npmrc file or with the `--registry` flag.

So in this case verdaccio stores the downloaded tarballs in it storage folder.

The lockfile also points to your set registry (take a look into it and check the `resolved` entries).

**Comment by khanh-h-nguyen** [comment]
Thanks for your answer!

**Comment by khanh-h-nguyen** [comment]
> 
> 
> With the right `--registry` flag value your storage should be filled.

I see the storage get filled now.  Thanks.

**Comment by khanh-h-nguyen** [comment]
I might have been misunderstood of when **being cached**  and when **being published** in the private registry

**Comment by DanielRuf** [comment]
Closing as resolved.
