### ISSUE TITLE
After unpublishing a package，I can't publish a package that the version is same to the unpublishing one

### ISSUE THREAD

**Issue by Tiny-Fendy** [verdaccio/verdaccio#1358]
version: 4.0.2

**Describe the bug**
使用unpublish命令撤回已上线npm包后，log信息显示撤回成功，但是再次发布同版本信息时却无法发布，log信息显示覆盖上传请更新版本，即使在发布命令后面加上了force参数也是一样的结果。

**To Reproduce**
1. 用”npm publish“命令发布一个npm包。
2. 用”npm unpublish --force“命令撤销这个包。
3. 用”npm publish“命令再次发布这个包。
4. See error。

**Expected behavior**
发布成功。

**Comment by juanpicado** [comment]
I appreciate your time for creating a ticket, but, unfortunately, I don't speak Chinese. I'd suggest re-think your content or find some help to write it in English and then I will reopen the ticket. Thanks for understanding.

**Comment by DanielRuf** [comment]
I guess the registry was not correctly set. It does work for Verdaccio but npmjs blocks previously published package + version combinations which is normal.

**Comment by MareoRaft** [comment]
moved to #1359
