### ISSUE TITLE
After unpublish a package，I can't publish the package

### ISSUE THREAD

**Issue by Tiny-Fendy** [verdaccio/verdaccio#1359]
version: 4.0.2

I'm sorry, my English is poor.
Now I try to describe my problem in english, 
I hope it helps you understand what I am talking about.

**Describe the bug**
I published a package twice(version 1.0.0 & version 1.0.1)，after some minutes I unpublished the package which version was 1.0.1 by used the commend "npm unpublish --force".
No problem until this step.

But when I tried to publish the package which version was 1.0.1 once again, it didn't work。
It told me that I need to update my version, but you know, the version 1.0.1 has been unpublish successly.

Then I got into the path which storing the package file，I found the package file(.tgz) had been deleted actually. But the file package.json in the same path didn't be changed, it still record the information of version 1.0.1.

**To Reproduce**
1. Publish a package which version is 1.0.0.
2. Update the version of the package to 1.0.1 and publish it.
3. Unpublish the package which version 1.0.1 by commend ”npm unpublish --force".
3. Publish the package which version 1.0.1 once again.
4. See error.

I wish I had made it clear.

**Comment by juanpicado** [comment]
Thanks @Tiny-Fendy for trying again, no worries about the English, it is also not my mother tongue. I'll follow you detailed steps and back to you when I can verify the bug. Please feel free to ask o add any other information that might be useful.

**Comment by Tiny-Fendy** [comment]
I have re-edited the step 4th from '1.0.0' to '1.0.1'

**Comment by MareoRaft** [comment]
@juanpicado @Tiny-Fendy This is arguably **not** a bug, but the **correct** behavior.

Imagine that when 1.0.1 was first published, somebody installed it.

Then when you republished a different 1.0.1, somebody else installed it.

Now you have two people with two different packages, and yet they both have the same version number.

This is very dangerous.  Versioning is meant to protect you against this.  You should update your version number to a new number.

**Comment by juanpicado** [comment]
I think might be a bug, I need to dive into this more. I had a similar experience recently but I could not reproduce it.

**Comment by morganfree** [comment]
@MareoRaft I think it should be an option in verdaccio whether it should protect from re-publishing or not. Verdaccio is also used for local development (correct generation of lock files, testing, etc.) and re-publishing is a must-have. Without this option the storage must be destroyed, (or server restarted) to re-publish.

**Comment by mathieu-bour** [comment]
I confirm that I can reproduce this behavior (version 4.0.2). While it makes sens to not let developers override their packages on the npm registry, as @morganfree said, for local developement, destroy the storage manually is quite painful.

**Comment by Tiny-Fendy** [comment]
@juanpicado What can I do for you?

**Comment by AllenBird** [comment]
> I think might be a bug, I need to dive into this more. I had a similar experience recently but I could not reproduce it.

we had some problem in such case.
I found 'npm unpublish' had delete attachments, but not change the versions information,
may I create a PR?

**Comment by juanpicado** [comment]
@AllenBird be my guest :-) I also confirm the issue. Let me know whether you need help. I think we need to work also in the unit test since should be properly tested there as well.

**Comment by AllenBird** [comment]
😄 sorry I forgot the UT last night, I'will do better this time.

**Comment by AllenBird** [comment]
> @AllenBird be my guest :-) I also confirm the issue. Let me know whether you need help. I think we need to work also in the unit test since should be properly tested there as well.

Hi !
@juanpicado @MareoRaft @mathieu-bour  @morganfree @DanielRuf 

Can we discuss the solution here?
1. As my pull request, Delete unpublished versions and history in package.json, and change the last version.
2. Change it when doing 'npm publish', Check if it has been deleted, and then cover it.
3. or ......

**Comment by AllenBird** [comment]
1. Test in npmjs.com
![image](https://user-images.githubusercontent.com/8787182/61259547-462c4d00-a7ad-11e9-9fed-86f7dbd6a476.png)

 2. npm unpublish --force 
![image](https://user-images.githubusercontent.com/8787182/61259599-8b507f00-a7ad-11e9-861d-caee846ed729.png)

3.  publish again
![image](https://user-images.githubusercontent.com/8787182/61259630-a28f6c80-a7ad-11e9-9cf2-01084afd9626.png)

4. patch version and publish
![image](https://user-images.githubusercontent.com/8787182/61259676-c9e63980-a7ad-11e9-8041-4ec0f1d46e1c.png)

**Comment by juanpicado** [comment]
I found the bug, it is related with https://github.com/verdaccio/verdaccio/pull/1248

**Comment by juanpicado** [comment]
@AllenBird npmjs does not allow unpublish packages for security reasons, https://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy thus their behaviour is not comparable with verdaccio project.

**Comment by sathyarajagopal** [comment]
@juanpicado I confirm that the unpublish issue is not found in 3.x.x and it is found only in 4.x.x.

**Comment by juanpicado** [comment]
thanks @sathyarajagopal, you are right, it is a bug the tests did not caught after me added new things on v4. 👍

**Comment by sathyarajagopal** [comment]
In the meantime I just wanted to let you know that I have done the below enhancement to the verdaccio code base to handle "SNAPSHOT" versions during development stage.

Change:
When packages are published with version as x.x.x-SNAPSHOT, if the same version already exists then I am overwriting that version if it has the string "SNAPSHOT".

I will send in a PR today with that change.

**Comment by juanpicado** [comment]
Mmmm, one thing, SNAPSHOT is a random term which if I'm not wrong, comes from Maven and Java world. I understand the objetive you are pursuing, but, I am afraid that won't cover all scenarios.

**Comment by juanpicado** [comment]
Try https://www.npmjs.com/package/verdaccio/v/4.2.1
