### ISSUE TITLE
Package management (unpublish/remove) on UI

### ISSUE THREAD

**Issue by whins** [verdaccio/verdaccio#1361]
**Is your feature request related to a problem? Please describe.**
I had issue with unpublishing when package name was same on npmjs.org. I solved it by manual removing data from file system on the server and it was hard

**Describe the solution you'd like**
Add buttons on package details page

**Comment by juanpicado** [comment]
hi @whins which issue did you have?

**Comment by DanielRuf** [comment]
Hi @whins,

I guess you mean the proxy which fetches and delivers the package + version combo from npmjs. Publishing the same combination in Verdaccio does not make much sense as this would create a conflicht (same but not really same).

**Comment by MareoRaft** [comment]
@juanpicado I believe this is a feature request.  He wants the ability to **easily unpublish a package**.  Is this a feature you plan on supporting?

**Comment by juanpicado** [comment]
I think admin tooling is hard to achieve now, not on my plans. I would rather to now how to reproduce his error so I can understand the issue itself.

**Comment by whins** [comment]
Hi
I'm sorry. It's my mistake. 
I run unpublish command incorrectly (without package name).

**Comment by juanpicado** [comment]
Thanks @whins for the update
