### ISSUE TITLE
Include a dedicated command which shows up local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [verdaccio/verdaccio#1364]
**Is your feature request related to a problem? Please describe.**
Presently, the issue template (bug report) doesn't prompt the user to provide his local environment information, which might prove useful to better understand the problem.

**Describe the solution you'd like**
In the typical scenario, he/she would be asked to manually enter those details as required.

**Describe alternatives you've considered**
Have a dedicated command `verdaccio info` which prints out the local environment information. With that all the user has to do is copy and paste the relevant information.

**Comment by jamesgeorge007** [comment]
@juanpicado Thoughts :thinking: 
I would be happy to submit a PR if the idea seems fine :+1:

**Comment by juanpicado** [comment]
hi @jamesgeorge007 could you give me an idea what output you are expecting for of such command?

**Comment by jamesgeorge007** [comment]
@juanpicado Check out [envinfo](https://www.npmjs.com/package/envinfo)

**Comment by juanpicado** [comment]
Thoughts @verdaccio/collaborators ?

**Comment by DanielRuf** [comment]
Sounds good, we have somwthing similar in gatsby.

**Comment by DanielRuf** [comment]
Sounds good, we have something similar in gatsby.

**Comment by juanpicado** [comment]
Also looks good to me, I think that's a yes @jamesgeorge007 go ahead. Please use this branch https://github.com/verdaccio/verdaccio/tree/4.1.x instead master and I'd suggest update the lock file if you add new dependencies, feel free to tag me if you need something else or any advice.

**Comment by dlouzan** [comment]
Also +1 from me
