### ISSUE TITLE
Add allowed users directly on the config.yaml file in customConfigMap (helm)

### ISSUE THREAD

**Issue by hugoazevedosoares** [verdaccio/verdaccio#1369]
I'm having a problem with verdaccio when deploying it with a helm chart. The deploy is working perfectly, but I do not want users to add thenselves to the repository, since it uses a public URL. A VPN is unwanted. 

I wish there was a way to set a list of allowed users on the config.yaml file used by helm on deploy, so only these users can download/publish packages.

Also, there is a way to restrict access to the packages pages if the user it's not logged in?

**Comment by juanpicado** [comment]
Something like this ?
https://github.com/verdaccio/verdaccio-auth-memory#config

**Comment by hugoazevedosoares** [comment]
Exaclty @juanpicado , thanks.

How do I install this package using the helm chart deployment?

**Comment by juanpicado** [comment]
@hugoazevedosoares that might depends of the Verdaccio version. Perhaps https://github.com/verdaccio/docker-examples/ gives you some inspiration. That plugin supports `max_users` so I think fits exactly what you need.
