### ISSUE TITLE
Is there a way we can use verdaccio as an upstream npm registry just like an registry.npmjs.org

### ISSUE THREAD

**Issue by suveerrao** [verdaccio/verdaccio#1372]
Hi.. 

we have multiple npm registries and would like to add all these to a azure npm registry as an upstream. we can add only registry.npmjs.org as it is a couchdb endpoint but not a web. just wondering if we can add this as an upstream.

**Comment by juanpicado** [comment]
Hi, could you elaborate the sections ? Would be great more context about the question.

**Comment by sergiohgz** [comment]
Take a look at the configuration yamls in this docker example: https://github.com/verdaccio/docker-examples/tree/master/multi-registry-uplink

**Comment by suveerrao** [comment]
Solution that I am looking is other way around.. I have a verdaccio private npm registry and uplink for this is registry.npmjs.org which is working fine but because of the load it is getting restarted and we are unable to scale it up in kubernetes as it is a file system based instance.. But Idea is to use a azure devops npm registry and add our private npm registry to azure devops npm registry as an upstream. we are able to add registry.npmjs.org as an upstream but not our private npm registry.

**Comment by suveerrao** [comment]
I think output from our private registry should be something like https://registry.npmjs.org where as with verdaccio it is not.

**Comment by juanpicado** [comment]
Have your doubts been cleared ? I am not sure if I understood your request.
