### ISSUE TITLE
run in background

### ISSUE THREAD

**Issue by bhabgs** [verdaccio/verdaccio#1375]
i'm use verdaccio in linux, 
i want to use in background verdaccio 
/usr/local/node/bin/verdaccio /usr/local/log/verdaccio.log &

**Comment by DanielRuf** [comment]
Hi @bhabgs,

You can use pm2 or any other solution to run `verdaccio`, also you can always send processes to the background on Linux (using `&`, `screen` and more).

**Comment by bhabgs** [comment]
Thank you, I'm use forever in linux success.
