### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by bhabgs** [verdaccio/verdaccio#1378]
I build an component and i publish to my verdaccio serve.
but i install error.
what this error?
![image](https://user-images.githubusercontent.com/19221378/60852745-98a8bf00-a22b-11e9-9b0c-c6c00a7d3150.png)

my component package.json
![image](https://user-images.githubusercontent.com/19221378/60852917-5a5fcf80-a22c-11e9-9680-9d1f748b91e7.png)

**Comment by bhabgs** [comment]
my english is not good, but i studying all the time.
Please understand.

**Comment by DanielRuf** [comment]
Hi @bhabgs,

`cb() never called` is a bug in npm itself and with cache issues. It is not caused by your code.

Please try `npm i -g npm@latest` and check if you can change the owner and group of the mentioned file(s).

**Comment by bhabgs** [comment]
i have update npm to latest, but show this error
![image](https://user-images.githubusercontent.com/19221378/60932323-0ae2d780-a2f0-11e9-9b79-d80e2fbaa037.png)

**Comment by bhabgs** [comment]
thank for you, i have update npm to latest and  remove node_module folder. try it ok.
