### ISSUE TITLE
adduser command Error :'verdaccio/conf/htpasswd'  permission denied

### ISSUE THREAD

**Issue by heifengli001** [verdaccio/verdaccio#1379]
I pull this image  and run it .
after i run this image , i can  access to the page via a browser.
But I can't adduser to the command line
I gave the file all permissions and gave a 100:101 grouping
But the problem still exists

---

my docker run command ：
```
docker run -it --rm --name verdaccio \
  -p 4873:4873 \
  -v /usr/verdaccio/conf:/verdaccio/conf \
  -v /usr/verdaccio/storage:/verdaccio/storage \
  -v /usr/verdaccio/plugins:/verdaccio/plugins \
  verdaccio/verdaccio
```
When I use the `adduser` command, I enter the email address and the command line interface is stuck.
I used the `docker logs verdaccio` command to view the logs and found the following error message:
```
  Trace--- the user yangkesi could not be added. Error: { message:
    'EACCES: permission denied, open \'/verdaccio/conf/htpasswd\'',
   Name: 'Error',
   Stack:
    'Error: EACCES: permission denied, open \'/verdaccio/conf/htpasswd\'',
   Code: 'EACCES',
   Signal: undefined }
  Error--- unexpected error: EACCES: permission denied, open '/verdaccio/conf/htpasswd'
Error: EACCES: permission denied, open '/verdaccio/conf/htpasswd'

```

**Comment by juanpicado** [comment]
@heifengli001 https://github.com/verdaccio/verdaccio/issues/1324#issuecomment-501362414

**Comment by savokiss** [comment]
This may help:

```bash
sudo chown 10001:65533 htpasswd
```

**Comment by ishowman** [comment]
> This may help:
> 
> ```shell
> sudo chown 10001:65533 htpasswd
> ```

where to input this command? host linux or container inner?

**Comment by savokiss** [comment]
@ishowman host machine

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
This is also mentioned at https://verdaccio.org/docs/en/docker.html

You might want to add the `-R` flag.

**Comment by ishowman** [comment]
> @ishowman host machine

thanks，it works。
By the way, the `Note` part of link [running-verdaccio-using-docker](https://verdaccio.org/docs/en/docker.html#running-verdaccio-using-docker) works as well.
