### ISSUE TITLE
Add integrity check

### ISSUE THREAD

**Issue by Robinfr** [verdaccio/verdaccio#138]
I have had a corruption in my NPM server. Some of the packages + `package.json` files have been corrupted. It would be nice if there was a way we could run an integrity check for all downloaded and published packages.

This would make it easier to fix these kinds of situations.

**Comment by carlos-bbt** [comment]
I am seeing the same problem. I am using Verdaccio 2.3.4.

**Comment by Robinfr** [comment]
@carlos-bbt I had a different situation where the disk actually got corrupted by a power outage, regardless it would be nice if we could run an integrity check. I do believe the MD5s of the packages are stored, so this shouldn't be too difficult as long as the `package.json` is intact.

**Comment by Meeeeow** [comment]
@Robinfr Every version have a "shasum", so it's possible to verify data.

Maybe a standalone tool? like `verdaccio-cli`, then we could use it to verify data, export backup, etc. @juanpicado

**Comment by Robinfr** [comment]
It would be really nice, I have some time in a few weeks, so maybe I'll take a look at what I can produce. @Meeeeow asides from integrity check and backups, what else would you like to see in such a tool?

**Comment by juanpicado** [comment]
Closing in favor of #343
