### ISSUE TITLE
413 Payload Too Large

### ISSUE THREAD

**Issue by manoranjan25** [verdaccio/verdaccio#1388]
I have set the max_body_size: 100mb but still get this error while publishing.
Unpacked Size is 39.6Mb

**Comment by juanpicado** [comment]
@manoranjan25 please read https://github.com/verdaccio/verdaccio/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by manoranjan25** [comment]
@juanpicado thanks.Issue is now resolved.
