### ISSUE TITLE
Use tokens for auth?

### ISSUE THREAD

**Issue by emcniece** [verdaccio/verdaccio#139]
I need to build an app in a CI pipeline, so the application must be built without human intervention. 

Is it possible to get and pass a token as a header, or as part of the URL? What is the method for CI builds without having a human perform `npm login` first?

**Comment by juanpicado** [comment]
Have you read this thread ? perhaps is useful. I haven't tried this solution but it's a worthile to try. https://github.com/npm/npm/issues/8356#issuecomment-174320077

**Comment by emcniece** [comment]
Thank you. I have implemented the `.npmrc` file population approach and it is working well.
