### ISSUE TITLE
uplink behind a proxy - 502 connectError

### ISSUE THREAD

**Issue by SWORDFISH354** [verdaccio/verdaccio#1390]
uplink behind a proxy - 502 connectError

**Comment by SWORDFISH354** [comment]
uplink behind a proxy - **502 connectError**

I am trying to install lodash as an example and it's not working for me. Below is a screenshot and npm log. I have setup the http_proxy and https_proxy in my env path. I am on a MAC OS. 

![image](https://user-images.githubusercontent.com/7824573/61105086-71a1f580-a496-11e9-9701-ec223344510b.png)



npm log: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'lodash',
1 verbose cli   '--registry',
1 verbose cli   'http://localhost:4873' ]
2 info using npm@6.4.1
3 info using node@v8.14.0
4 verbose config Skipping project config: /Users/XBBNNSZ/.npmrc. (matches userconfig)
5 verbose npm-session 042bc864b4b4c066
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 502 http://localhost:4873/lodash 71953ms attempt #3
9 silly fetchPackageMetaData error for lodash@latest 502 cannotconnect: lodash@latest
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 72326ms
12 verbose stack Error: 502 cannotconnect: lodash@latest
12 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
12 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
12 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
12 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
12 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
12 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
12 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
12 verbose stack     at runCallback (timers.js:810:20)
12 verbose stack     at tryOnImmediate (timers.js:768:5)
12 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
13 verbose cwd /Users/XBBNNSZ
14 verbose Darwin 18.6.0
15 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "lodash" "--registry" "http://localhost:4873"
16 verbose node v8.14.0
17 verbose npm  v6.4.1
18 error code E502
19 error 502 cannotconnect: lodash@latest
20 verbose exit [ 1, true ]

**Comment by juanpicado** [comment]
Please fill this template before report and issue, that makes more easy to understand to track source of the problem.
https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/ISSUE_TEMPLATE/Bug_report.md
