### ISSUE TITLE
verdaccio 4.1.0 shows the unpublished component version in UI 

### ISSUE THREAD

**Issue by sathishchandran97** [verdaccio/verdaccio#1391]
**Describe the bug**
I've installed verdaccio 4.1.0 ,  and published a package with version 1.0.0 and 1.0.1. I've unpublished version 1.0.1 but still verdaccio displays the package vesion as 1.0.1. But when i try to install the package@1.0.1 it shows package doesn't exists. But the 1.0.1 is there in UI(verdaccio front end). 

**Expected behavior**
The correct version should be there in verdaccio UI.

**Screenshots**
![verdaccio-UI](https://user-images.githubusercontent.com/50132149/61111096-6656c600-a4a6-11e9-8035-51b3f7dd387b.PNG)
![bug-verdaccio](https://user-images.githubusercontent.com/50132149/61111097-6656c600-a4a6-11e9-9d0e-37a02c74b6d0.PNG)

**Comment by lirantal** [comment]
I can confirm that this indeed happens.
It looks like the top level `package.json` for the package in the local storage directory still keeps a reference of an unpublished version, yet there's no tarball for such unpublished version available.

Is this by design so that no one can create a version that was unpublished or should it be allowed?

**Comment by juanpicado** [comment]
Duplicated https://github.com/verdaccio/verdaccio/issues/1359 👍

**Comment by juanpicado** [comment]
Thanks @sathishchandran97 for reporting :-) there is a possible solution in the #1359 perhaps you want go for it 🤓

**Comment by juanpicado** [comment]
> Is this by design so that no one can create a version that was unpublished or should it be allowed?

@lirantal  it is a bug :-) version unpublish should be removed from the `package.json`.

**Comment by lirantal** [comment]
Yes indeed! :-)

**Comment by sathishchandran97** [comment]
Okay @juanpicado . Thanks :-)
