### ISSUE TITLE
Switching to Koa (instead of Express)

### ISSUE THREAD

**Issue by buschtoens** [verdaccio/verdaccio#1395]
Since some breaking releases will eventually land, has there been some consideration regarding replacing Express?

I would suggest [Koa](https://koajs.com/), which seems to be more lightweight / performant, and has a subjectively better middleware programming model.

It might even be possible to stay backwards compatible with existing then-legacy Express middleware plugins.

**Comment by buschtoens** [comment]
Can't argue with that! 😄 

I only wanted to make sure to have suggested it, since I personally prefer Koa. Primarily for the two reasons listed above: more lightweight and subjectively better programming model (async middleware).

Feel free to close this issue. ✌️

**Comment by juanpicado** [comment]
🙃 I understand, it's fine, it just a proposal, it does not harm. I always appreciate suggestions and I help to move them forward if they fit within the vision of this project. Thanks anyway.
