### ISSUE TITLE
Open up the default browser automatically

### ISSUE THREAD

**Issue by jamesgeorge007** [verdaccio/verdaccio#1398]
The default browser window opens automatically on firing in `verdaccio`

## Demo

![simplescreenrecorder-2019-07-20_13 22 41](https://user-images.githubusercontent.com/25279263/61576084-bfe87180-aaf2-11e9-9b49-77b665cb2e2b.gif)

Utilizes [open](https://npmjs.com/package/open)

**Comment by jamesgeorge007** [comment]
cc @juanpicado

**Comment by jamesgeorge007** [comment]
cc @juanpicado

**Comment by juanpicado** [comment]
Keep on mind the 90% uses verdaccio in the server side and docker.  I think this won't work for the big majority.

**Comment by DanielRuf** [comment]
Also many terminals make URLs clickable.
