### ISSUE TITLE
Consider stop using node:onbuild

### ISSUE THREAD

**Issue by danielo515** [verdaccio/verdaccio#140]
#### My reason:

I guess that when you first built the docker image the `onbuild` tag of node was a good choice to start with. However it does not provide enough control over what is happening, how or where.
According to official node image documentation, it is discouraged for anything except tests:

> While the onbuild variant is really useful for "getting off the ground running" (zero to Dockerized in a short period of time), it's not recommended for long-term usage within a project due to the lack of control over when the ONBUILD triggers fire

Not to mention that the image size is huge. I would recommend using `node:alpine` as a base instead. The image size will be significantly smaller (from 600mb to less than 200), and the control over what happens will be much fine grained.
	
#### Additional information:

Official node docker image documentation: https://hub.docker.com/_/node/ (search for `node:onbuild` section)

**Comment by juanpicado** [comment]
Thanks @danielo515 I'll let this open to discussion. I'm not Docker expert so at least for my side seems a good enhancement.

**Comment by juanpicado** [comment]
Proposed at #181 I hope the author reply soon .

**Comment by juanpicado** [comment]
Done
