### ISSUE TITLE
403 forbidden - invalid package

### ISSUE THREAD

**Issue by jstephen-pa** [verdaccio/verdaccio#1400]
I am attempting to download a package hosted on npmjs.org using my Verdaccio installation as a mirror.  This works for many other packages I have used.  The package in question is here:

https://www.npmjs.com/package/@ember-data/-build-infra

I suspect the problem is the leading dash in the name.  When I attempt to install through Verdaccio, I get a 403 invalid package error.  The expected behavior is that the package successfully installs.

In the console:

```
$ npm install @ember-data/-build-infra
npm ERR! code E403
npm ERR! 403 Forbidden - GET https://<<HOSTNAME>>/@ember-data%2f-build-infra - invalid package
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deploy/.npm/_logs/2019-07-22T21_34_35_025Z-debug.log
[deploy@ip-172-31-26-34 ~]$ npm install @ember-data/-build-infra
npm ERR! code E403
npm ERR! 403 Forbidden - GET https://npm-registry.power.auction/@ember-data%2f-build-infra - invalid package

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deploy/.npm/_logs/2019-07-22T21_34_41_594Z-debug.log
```

In the verdaccio log:

```
{"name":"verdaccio","hostname":"<<HOSTNAME>>","pid":29999,"sub":"in","level":30,"req":{"method":"GET","url":"/@ember-data%2f-build-infra","headers":{"host":"npm-registry.power.auction","x-forwarded-for":"34.228.153.10","x-forwarded-proto":"https","connection":"close","user-agent":"npm/6.9.0 node/v10.16.0 linux x64","npm-in-ci":"false","npm-scope":"","npm-session":"9279a6842df72517","referer":"install [REDACTED]","pacote-req-type":"packument","pacote-pkg-id":"registry:@ember-data/-build-infra","accept":"application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*","authorization":"<Classified>","accept-encoding":"gzip,deflate"},"remoteAddress":"127.0.0.1","remotePort":44598},"ip":"127.0.0.1","msg":"127.0.0.1 requested 'GET /@ember-data%2f-build-infra'","time":"2019-07-22T21:38:55.442Z","v":0}
{"name":"verdaccio","hostname":"<<HOSTNAME>>","pid":29999,"sub":"in","level":35,"request":{"method":"GET","url":"/@ember-data%2f-build-infra"},"user":null,"remoteIP":"34.228.153.10 via 127.0.0.1","status":403,"error":"invalid package","bytes":{"in":0,"out":33},"msg":"403, user: null(34.228.153.10 via 127.0.0.1), req: 'GET /@ember-data%2f-build-infra', error: invalid package","time":"2019-07-22T21:38:55.444Z","v":0}
```

> Environment Info:
> 
>   System:
>     OS: Linux 3.10 Red Hat Enterprise Linux Server 7.6 (Maipo)
>     CPU: (32) x64 Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
>   Binaries:
>     Node: 10.16.0 - /usr/bin/node
>     Yarn: 1.17.3 - /usr/bin/yarn
>     npm: 6.9.0 - /usr/bin/npm
>   Virtualization:
>     Docker: 18.09.8 - /usr/bin/docker
>   Browsers:
>     Chrome: 75.0.3770.142

**Comment by juanpicado** [comment]
@jstephen-pa are you using any reverse proxy? Your environment description seems incomplete. Please read and follow these steps https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by jstephen-pa** [comment]
@juanpicado this occurs without any proxy.  The reproduction should be very quick, just `npm install @ember-data/-build-infra` with npm set to use your verdaccio.  Does it not happen for you?

I am doing it with a very minimal case, just running verdaccio directly:

`./node_modules/.bin/verdaccio --config /deploy/verdaccio/config.yaml`

Here are the contents of my config.yaml:

```
listen: 127.0.0.1:4873

storage: /deploy/verdaccio/storage

web:
  enable: true
  title: Verdaccio

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
```

Versions and such are above in the original comment.

**Comment by juanpicado** [comment]
Thanks for that, but still I do not see the verdaccio version. latest?

**Comment by jstephen-pa** [comment]
Apologies for that:

```
$ ./node_modules/.bin/verdaccio --version
4.1.0
```

**Comment by juanpicado** [comment]
https://github.com/bertdeblock/verdaccio-1400-test

**Comment by raido** [comment]
Could we get this backported to v2 and v3?
