### ISSUE TITLE
Handle package name and version in middleware

### ISSUE THREAD

**Issue by mehmet-erim** [verdaccio/verdaccio#1401]
I would like to handle the package name and version in my middleware. But I can't. If I handle package info, I can stop this process. Actually, I am developing a License Management Middleware. When finished the license of the user on version 2.1.3, the user can download 2.1.0, 2.1.1, ... 2.1.9 versions. If the user wants to download version 3. I must stop this request.

Sometimes user can request a package like below:

`npm install @scope/package@1.0.1 --registry http://localhost:4873`
I want to handle `@scope/package` and  `1.0.1`

Another case:
`npm install @scope/package --registry http://localhost:4873`
I want to handle `@scope/package` and return package version.

**Comment by ismcagdas** [comment]
@juanpicado do you have any insight about this ? If you need more information, we can provide.

Thanks.

**Comment by ismcagdas** [comment]
Any news ? We just want to know if it is possible to change the requested package version somewhere in verdaccio. For example, even if the package version 3.1 is requested we want to return 2.9 according to some rules.

Thanks.
