### ISSUE TITLE
Unable to unpublish specific package from registry

### ISSUE THREAD

**Issue by sathyarajagopal** [verdaccio/verdaccio#1405]
Hello,

I have my private verdaccio set up which is integrated with S3 bucket where my uploaded packages are stored. I am trying to run the below command to unpublish existing version from my registry.
npm unpublish @<pkgname>@<version> --force
This removes the package version specified from S3 bucket. However it doesn't unpublish from the registry. I am still seeing the package version in Verdaccio UI. Can someone help me here?

**Comment by juanpicado** [comment]
Seems related https://github.com/verdaccio/verdaccio/issues/1359

**Comment by sathyarajagopal** [comment]
Yes its the same issue. Is it fixed in 4.1.0?

**Comment by juanpicado** [comment]
Not fixed yet. I will close this one, please follow #1359.

**Comment by sathyarajagopal** [comment]
Sure. Thanks Juan.... Looking forward to that fix.

**Comment by juanpicado** [comment]
It will ve released with 4.2.0 and the end of this month. Keep tuned

**Comment by sathyarajagopal** [comment]
Juan,

I see that v4.2.0 is released. I am still unable to unpublish with v4.2.0.

**Comment by juanpicado** [comment]
The issue was not fixed in time, perhaps next minor patch.

**Comment by sathyarajagopal** [comment]
Ok cool.

**Comment by sathyarajagopal** [comment]
will this be fixed this month end? Currently in development stage we are unable to unpublish and re-publish it. And because of that we have to increment the version everytime to get around this and it really crowds the S3 bucket.

**Comment by juanpicado** [comment]
I never define dates on tickets because this is a voluntary work. Since is a bug can be fixed and releases anytime for anyone or any maintainer. PR are 🙏 welcome. We provide guidance and code reviews to ensure the code shipped won’t cause any trouble.

**Comment by sathyarajagopal** [comment]
Ok cool :)

**Comment by juanpicado** [comment]
Try https://www.npmjs.com/package/verdaccio/v/4.2.1
