### ISSUE TITLE
Question regarding the NPM "protocol"

### ISSUE THREAD

**Issue by blendsdk** [verdaccio/verdaccio#141]
Hi,

Is there an npmjs API/protocol description on which verdaccio/sinopia is built up on? Or is the npmjs API reverse engineered in order to make this project possible?

Thanks

**Comment by juanpicado** [comment]
I think sinopia was born as a API reverse engineered from `npm`. I haven't found any hint of design either on commits, wiki or history of tickets on the original project. Anyway, I was documenting which features of npm `latest` are actually supported by `verdaccio`.
https://github.com/verdaccio/verdaccio/wiki/Registry-Endpoints 
Why the question?

**Comment by blendsdk** [comment]
I was implementing my own registry based on trail/error until i found sinopia and later verdaccio. I wanted to compare my own implementation with another one. It looks like that npmjs themselves do not provide a good documentation regarding the API implementation.

**Comment by juanpicado** [comment]
@blendsdk The closer thing I've found that can be called API is https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md and it doesn't contains all endpoints. I hope it helps you. If you find something else, don't hesitate to share.
