### ISSUE TITLE
Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by cjking-wang** [verdaccio/verdaccio#1416]
0|verdaccio  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
0|verdaccio  |     at ServerResponse.setHeader (_http_outgoing.js:470:11)
0|verdaccio  |     at ServerResponse.header (/home/ping.wang/.nvm/versions/node/v10.16.0/lib/node_modules/verdaccio/node_modules/express/lib/response.js:771:10)
0|verdaccio  |     at ServerResponse.send (/home/ping.wang/.nvm/versions/node/v10.16.0/lib/node_modules/verdaccio/node_modules/express/lib/response.js:170:12)
0|verdaccio  |     at final (/home/ping.wang/.nvm/versions/node/v10.16.0/lib/node_modules/verdaccio/build/api/middleware.js:197:7)
0|verdaccio  |     at Layer.handle_error (/home/ping.wang/.nvm/versions/node/v10.16.0/lib/node_modules/verdaccio/node_modules/express/lib/router/layer.js:71:5)
0|verdaccio  |     at trim_prefix (/home/ping.wang/.nvm/versions/node/v10.16.0/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:315:13)
0|verdaccio  |     at /home/ping.wang/.nvm/versions/node/v10.16.0/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:284:7
0|verdaccio  |     at Function.process_params (/home/ping.wang/.nvm/versions/node/v10.16.0/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:335:12)
0|verdaccio  |     at next (/home/ping.wang/.nvm/versions/node/v10.16.0/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:275:10)
0|verdaccio  |     at /home/ping.wang/.nvm/versions/node/v10.16.0/lib/node_modules/verdaccio/build/api/index.js:108:14
0|verdaccio  |  http <-- 200, user: null(172.20.13.254), req: 'GET /typescript/-/typescript-3.2.4.tgz', bytes: 0/7605040

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/issues/877
