### ISSUE TITLE
clear cache endpoint?

### ISSUE THREAD

**Issue by qballer** [verdaccio/verdaccio#142]
this is more of an enhancement request. I feel like that invalidating a cached package (not the kind you publish as private repo) can be very useful. In many complex production environments it could be that the cache holds the wrong tar and I want to drop it so verdaccio will get the version again.

**Comment by juanpicado** [comment]
I'm agreed. Any idea how to this endpoint should be called? web/cli/npm? .

**Comment by qballer** [comment]
web 
something you can do with curl from terminal or from cli script.

**Comment by DeDuckProject** [comment]
+1

**Comment by juanpicado** [comment]
And endpoint should be accesible either by the npm (not suitable because there is no npm command for such funtionality) or web (not secure at all where any person might trigger that, I'm wrong?). IMHO, That let's us use the CLI as a unique option. 

Perhaps ..?
```
verdaccio -cl 
```

**Comment by qballer** [comment]
I understand the deter from web. I was thinking on placing this on a separate host:port pair. It would be great if the CLI command would operate on a live instance. Something like this: `verda -cl [name] -pid [number]`

**Comment by juanpicado** [comment]
@qballer what would be `[name]`? Could you elaborate a bit more?

**Comment by qballer** [comment]
name would best be either package name (meaning drop all cache) or package@version meaning drop that specific project

example 
`verda -cl react -pid 4172` will remove all react version from the verdaccio endpoint at pid 4172
`verda -cl react@0.14.7 -pid 4172` will drop only the specific version 

The cli can write a file to a predefined folder and then send an os event to the process which will cause verdaccio to read the messages. 

cli will always append new files and verdaccio will consume them.

**Comment by qballer** [comment]
related to: #138

**Comment by juanpicado** [comment]
@qballer I wonder, How this could be used with Docker?

**Comment by qballer** [comment]
A couple of options from the top of my head.

You can make sure the docker image has a shared file system with the host machine. Than configure 
verdaccio to read messages from the docker path. CLI can leave messages there. 

Connect to docker via ssh and run the command locally.

Still some kind of API end point configure on a different `ip:port` seems easy.

**Comment by qballer** [comment]
@juanpicado I would like to move forward with this. Would you like to decide on a basic design and I will implement it?

**Comment by juanpicado** [comment]
Sorry the delay @qballer . I've been busy with others improvements.  

Starting by the `cli` already has access to the config file and somehow access to the `Storage` class, you might not need the `pid` at all, isn't? 

#### Storage API

Perhaps add a new interface to `Storage` would looks like as:

```
Storage.clear(pkg:string, version:string);
```
Whether you do not provide any data will remove all package excluding local packages
```
Storage.clear();
```
This won't affect any future storage implementation since `Storage` is the main class and any plug-ing will depend of it.

The cli would be as you suggested, I like the format, excluding the `pid`.

#### Cleaning specific package
```
verdaccio -cl react --config /foo/bar/config.yaml
````
#### Cleaning specific package + version
```
verdaccio -cl react@0.14.7 --config /foo/bar/config.yaml
````
#### Clear all cache (it would exclude all local packages)
```
verdaccio -cl --config /foo/bar/config.yaml
````

That's what I had on mind, let me know what do you think. Perhaps I forgot something.

**Comment by juanpicado** [comment]
@qballer what do you think about #132 ?

**Comment by juanpicado** [comment]
Since `2.2.0` you can set a boolean `cache` property to each uplink.

```yaml
uplinks:
 npmjs:
   url: https://registry.npmjs.org/
   cache: false

 yarn:
   url: https://registry.yarnpkg.com/
   cache: false
```
That will avoid cache the tarballs, that does not fix this problem, but it helps.

**Comment by pward123** [comment]
I'd be happy with something as simple as a separate storage folder for published packages vs cached from npm.  Stop the docker container, wipe the cached npm folder and start the docker container

**Comment by juanpicado** [comment]
@pward123 we are working to create pluggable storage. Then anyone could create their own storage. We are planning that for `v3.0.0`.

**Comment by Meeeeow** [comment]
@pward123 Here is a sample config to separate them, but... don't wipe cache directory, database still there...

```yaml
storage: /mnt/external/verdaccio/cache

uplinks:
  npmjs:
    url: https://registry.npmjs.org

packages:
  '@private/*':
    access: $authenticated
    publish: $authenticated
    storage: /mnt/external/verdaccio/packages

```

**Comment by juanpicado** [comment]
Closing in favor of #343
