### ISSUE TITLE
After moving a package to a new server, the package doesn't show in the web.

### ISSUE THREAD

**Issue by Tiny-Fendy** [verdaccio/verdaccio#1420]
version: 3.12.0

I had moved some packages to a new server from an old server and I can install the package successfully in my project.

But what the problem was that the packages which I moved didn't show in  the web.

**Comment by Tiny-Fendy** [comment]
<img width="798" alt="packages" src="https://user-images.githubusercontent.com/8954107/62211568-77be2e80-b3d1-11e9-89cb-54ffa33475b4.png">
<img width="888" alt="storage" src="https://user-images.githubusercontent.com/8954107/62211623-9f14fb80-b3d1-11e9-8dbe-8e0241136c5d.png">

**Comment by carlosen14** [comment]
did you move also the `.json` file?

**Comment by Tiny-Fendy** [comment]
@carlosen14 Could you tell me the detail path of the .``json`` file?

**Comment by carlosen14** [comment]
Yeah, I'll tell you tomorrow

**Comment by Tiny-Fendy** [comment]
ok, tkx!

**Comment by juanpicado** [comment]
@Tiny-Fendy the `verdaccio-db.json` or `sinopia-db.json` file is the tiny database that holds all the names of your private packages + the secret key that salt your passwords (keep it in secret). 
The location should be here https://verdaccio.org/docs/en/cli#default-database-file-location depending of your OS.

That being said, you should provide more detailed info about your environment, please read and fill the following template in markdown format https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/ISSUE_TEMPLATE/Bug_report.md and perhaps we can have a better overview of your issue.

**Comment by carlosen14** [comment]
@Tiny-Fendy We don't know if you are running on Docker, if it was your case, then here it is `/verdaccio/storage/data/.verdaccio-db.json` you won't see it normally because it is hidden.

You need to move this file along with the folders on migration.

**Comment by Tiny-Fendy** [comment]
@carlosen14 @juanpicado Thanks for your help，I had resolve this question yesterday.

**Comment by juanpicado** [comment]
How to ? Could you share it?

**Comment by Tiny-Fendy** [comment]
I haven't moved the ``sinopia-db.json`` file to the new server.

**Comment by juanpicado** [comment]
Thanks !!
