### ISSUE TITLE
How to put the open source package on the verdaccio server?

### ISSUE THREAD

**Issue by jianwenjuan** [verdaccio/verdaccio#1428]
We hope to put the third-party open source package that the project depends on in the verdaccio server. How can we do it?

**Comment by juanpicado** [comment]
hi @jianwenjuan , could you give a bit more context? I'm not pretty sure what's que doubt.

**Comment by jianwenjuan** [comment]
> hi @jianwenjuan , could you give a bit more context? I'm not pretty sure what's the doubt.

Our project uses a lot of open source libraries, such as react, redux and so on. We now hope to put the npm package of these open source libraries on the verdaccio server for us to better manage. In other words, this verdaccio server not only manages our private libraries, but also manages the open source third-party libraries we rely on.

**Comment by juanpicado** [comment]
What do you mean with manages Open Source third party libraries ? Do you mean cache them or you actually modified them ?

Verdaccio cache any dependencies you install through the registry.

**Comment by jianwenjuan** [comment]
> What do you mean with manages Open Source third party libraries ? Do you mean cache them or you actually modified them ?
> 
> Verdaccio cache any dependencies you install through the registry.

Do not modify them. Is to publish these open source third party packages to our own verdaccio server. And need to be able to see them on the package list

**Comment by juanpicado** [comment]
Ok I know what you mean, you can access this libraries via URL but are not displayed or searchable yet. If you click in any dependency in the browser and then click on dependencies you will see all the deps of your package, then click in any of them and you can browse all those packages.

This will work only if you use verdaccio as full cache solution, if you are fetch other dependencies via other source you won’t find them in verdaccio.

**Comment by jianwenjuan** [comment]
> Ok I know what you mean, you can access this libraries via URL but are not displayed or searchable yet. If you click in any dependency in the browser and then click on dependencies you will see all the deps of your package, then click in any of them and you can browse all those packages.
> 
> This will work only if you use verdaccio as full cache solution, if you are fetch other dependencies via other source you won’t find them in verdaccio.

What you mean is that verdaccio can cache these third-party dependencies. However, at the same time, I also hope that the web UI can display a list of third-party packages that I cache. Can this be done?

**Comment by juanpicado** [comment]
All can be done, :-), just matter of time and resources ;)  

I mean when you do npm install through verdaccio, all dependencies are cached in the server and at the same time downloaded to your node modules folder even if you don’t see them in the UI, but if you inspect the storage folder you will see them.

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/issues/706

**Comment by jianwenjuan** [comment]
> All can be done, :-), just matter of time and resources ;)
> 
> I mean when you do npm install through verdaccio, all dependencies are cached in the server and at the same time downloaded to your node modules folder even if you don’t see them in the UI, but if you inspect the storage folder you will see them.



> All can be done, :-), just matter of time and resources ;)
> 
> I mean when you do npm install through verdaccio, all dependencies are cached in the server and at the same time downloaded to your node modules folder even if you don’t see them in the UI, but if you inspect the storage folder you will see them.

I hope to see them on the list of web UI. Is there a version support now?

**Comment by juanpicado** [comment]
Nop, there was not develop yet, vote up if you want the feature.

Closing it, I think I already answer you.

If you want to know more I would suggest joint the chat, others users can give you more ideas.

Thanks !
