### ISSUE TITLE
Private only repository

### ISSUE THREAD

**Issue by Bram-Zijp** [verdaccio/verdaccio#1430]
**Is your feature request related to a problem? Please describe.**
When I use Verdaccio, I only wanna host private packages. Commonly people only wanna publish public packages to npm itself. I would like to get the option to toggle all modules to be private while keeping group access options.

**Describe the solution you'd like**
Create an environment variable that makes all projects private while maintaining group policy.

**Comment by juanpicado** [comment]
> I would like to get the option to toggle all modules to be private while keeping group access options.

I don't understand. https://verdaccio.org/docs/en/protect-your-dependencies packages can be private if you use a specific set up in the packages section. Perhaps you can elaborate a bit more this request.

**Comment by Bram-Zijp** [comment]
I think one can manage making a private only repo without adding additional layers is by disabling the adduser and setting all packages to be scoped to private groups.
