### ISSUE TITLE
Problem with making verdaccio seeing my program as a plugin.

### ISSUE THREAD

**Issue by liams98** [verdaccio/verdaccio#1439]
Hello guys,
So I want to use the local-storage plugin and  made small changes to it. after cloning "local-storage" plugin and making verdaccio realizing the plugin by editing config.yaml like this:
```middlewares:
  audit:
    enabled: true
  local-storage-test:
    enabled: true
```

plus I did this but not sure if this helps
```
store:
  local-storage-test:
```
plus i added the cloned plugin to the verdaccio's file with the main folder plugins.

The directory will look like this: verdaccio --> plugins --> local-storage-test

after this I save the program by : 
`npm release`
`npm i -g  .`

after all this I run verdaccio in terminal and I get this error

```
error--- verdaccio-local-storage-test doesn't look like a valid plugin
(node:13068) UnhandledPromiseRejectionWarning: Error: sanity check has failed, "local-storage-test" is not a valid plugin
```

the error was that while checking sanitycheck on the plugin it's returning true and as you can see the returning the plugin doesn't look like a plugin

Here is the rest of the error that comes after the error I showed you maybe you can know what am I doing wrong.

```
at Object.keys.map.pluginId (C:\Users\user\AppData\Roaming\npm\node_modules\verdaccio\build\lib\plugin-loader.js:142:13)
    at Array.map (<anonymous>)
    at loadPlugin (C:\Users\user\AppData\Roaming\npm\node_modules\verdaccio\build\lib\plugin-loader.js:62:37)
    at defineAPI (C:\Users\user\AppData\Roaming\npm\node_modules\verdaccio\build\api\index.js:71:45)
    at _default (C:\Users\user\AppData\Roaming\npm\node_modules\verdaccio\build\api\index.js:127:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

What am I doing wrong, is there something I missed in the documentation.
I want to add that Ik local storage is already install in verdaccio but I didn't know how to find the program and edit it so I'm trying to manually adding it to my computer.

Thank you.

**Comment by liams98** [comment]
Okay for some reason what I did is that commented out the:
```
audit:
    enabled: true
 -> local-storage-test:
    ->enabled: true
```
and then verdaccio was able to load the plugin, it was very strange and I still would like to know if what happend.

To make it work I commented out the plugin from middleware and left
```
store: 
   local-storage-test:
```

and like that it got loaded.

**Comment by juanpicado** [comment]
Mmmm, 
```
store: 
   local-storage-test:
```
is correct, but `audit` is an useful plugin and should be defined as 

```
middlewares:
  audit:
    enabled: true
```
