### ISSUE TITLE
Unpublish does't unpublish version

### ISSUE THREAD

**Issue by optimistic5** [verdaccio/verdaccio#1443]
**Describe the bug**
In my verdaccio storage I have tar with version `0.5.0-beta`
I did `unpublish --force`
Tar is deleted from storage, but version `0.5.0-beta` is still on verdaccio.

**To Reproduce**
1. `ls` in your storage
![image](https://user-images.githubusercontent.com/25054050/63244008-deae6500-c264-11e9-987f-def4c0f76be0.png)
Not that I have version `0.5.0-beta`
2. In your library, with version `0.5.0-beta` in your `package.json` do `npm unpublish --force`
![image](https://user-images.githubusercontent.com/25054050/63244157-511f4500-c265-11e9-999e-aa337a782e9e.png)

3. `ls` in storage
tar with version `0.5.0-beta` is gone
![image](https://user-images.githubusercontent.com/25054050/63244194-66946f00-c265-11e9-94e5-820fdadb896e.png)

4. Go to verdaccio, see the version `0.5.0-beta` is still present.
![image](https://user-images.githubusercontent.com/25054050/63244221-79a73f00-c265-11e9-9fd7-86d037e31a08.png)

**Expected behavior**
After unpublish version it deletes tar and version should gone from verdaccio site.

**Docker:**
 - Docker verdaccio 0.4.2

**Comment by liarco** [comment]
@optimistic5, does running the `unpublish` command twice "fix" the issue? If so it might be related to #1435.

**Comment by optimistic5** [comment]
@liarco no. Actually this is screenshot from the command running second time.

**Comment by sergiohgz** [comment]
Please, can you try the unpublish command providing name and version explicitly `npm unpublish --force <pkg_name>@0.5.0-beta` and capture the output if it's wrong?
Also, the trace given by the Verdaccio instance is important to discover what's happening :smiley:
