### ISSUE TITLE
bug: default can install alpha version

### ISSUE THREAD

**Issue by henryzp** [verdaccio/verdaccio#1447]
**Describe the bug**
when I publish a version like `2.0.0-alpha.1`。
I don't want anyone to be able to install the alpha version by default, only @next can, with the NPM rules of the public network

**To Reproduce**

1. publish package like `2.0.0-alpha.1`
2.`yarn install`，can get the version `2.0.0-alpha.1`

**Expected behavior**

cannot get the `alpha` version

**Comment by DanielRuf** [comment]
Hi @henryzp,

Please fill out our issue template, especially please provide the configuration.

By default all the packages are available for all users.

**Comment by henryzp** [comment]
@DanielRuf ,I can publish with `--tag`。it can work
