### ISSUE TITLE
Detach from "rlidwka/sinopia"

### ISSUE THREAD

**Issue by jamietre** [verdaccio/verdaccio#145]
Sinopia's pretty dead, seems like not much reason to keep that relationship. From a practical standpoint, Github doesn't allow searching forks, it would be nice if that was possible.

**Comment by juanpicado** [comment]
Read #75 . I'm agree with you but, it's really hard to do it. Github came up with keywords and since then the project is easier to find. Closing this one for duplicated.

**Comment by jamietre** [comment]
Ha - I tried to search the issues but obv didn't use the right keywords.

If the concerns have to do with the complexity of getting de-forked or losing history, this indicates that you can just as github to do it:

http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

Ref: https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support. If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."

If the main concern is being found from Sinopia then I guess that's a dealbreaker.

**Comment by juanpicado** [comment]
I filed a request, let's see what Github folks says. Thanks for the info @jamietre
