### ISSUE TITLE
Can the project be deployed to serverless?

### ISSUE THREAD

**Issue by jiankafei** [verdaccio/verdaccio#1453]
Can the project be deployed to serverless?

**Comment by juanpicado** [comment]
do you mean https://serverless.com/ or https://www.cloudflare.com/learning/serverless/what-is-serverless/ ? It is kinda generic word.

**Comment by jiankafei** [comment]
@juanpicado 
`// @flow
import serverless from 'serverless-http';
import { startVerdaccio } from './lib/bootstrap';

export const submit = async (event, context) => {
  const { app } = await new Promise((resolve, reject) => {
    startVerdaccio({}, '4873', '', module.exports.version, module.exports.name, (webServer, addr, pkgName, pkgVersion) => {
      resolve({
        app: webServer,
      });
    });
  });

  const handler = serverless(app);
  return await handler(event, context);
};
`
This is the handler file. I compiled the project, uploaded the file to serverless, and then responded to the result of 403.

**Comment by acao** [comment]
@juanpicado i'd like to know for the latter, the generic case. zeit now, aws lambda, etc, any plans for targeting these kinds of platforms?

**Comment by juanpicado** [comment]
hi @acao, unless someone with experience in such platforms and willing to invest time on research, integration, testing and documentation, it will remain like it is. It is possible? I don't know is even is possible with the current design, unfortunately have 0 experience with those. 

I'm focused only on Docker and traditional installations.
