### ISSUE TITLE
Can I choose the windows install path instead of %appdata%

### ISSUE THREAD

**Issue by leon-kfd** [verdaccio/verdaccio#1458]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leon-kfd** [comment]
![image](https://user-images.githubusercontent.com/30256102/64166194-36f68100-ce79-11e9-96eb-d48ba4b9208a.png)
I don't want to install it in the %appdata%

**Comment by juanpicado** [comment]
could you explain me why this is a problem and why we might parametrize it?

**Comment by leon-kfd** [comment]
It may be a small problem. When my windows server restart, the path of %appdata% will be clean. Then the storage data will be empty. Can’t I install it to another path like “npm install -g verdaccio —path=...”. This just a small suggestion.

**Comment by sergiohgz** [comment]
If I understand your problem, the issue is with npm client, not with Verdaccio itself.
