### ISSUE TITLE
How can I publish an existing package from my node_modules to the registry

### ISSUE THREAD

**Issue by LOLdevelopr** [verdaccio/verdaccio#1460]
## First of all , I am sorry if I am approaching this wrong or I missed some docs or any relevant info

**Is your feature request related to a problem? Please describe.**
**It is not a feature request though but still using this template**
It is more like better usage docs

I have installed this and as mentioned in the docs, set the npm registry to verdaccio and also added the profile and user. now how do I publish a package from my node_modules to here. I tried by navigating to my project directory which is having `package.json` and ran the `verdaccio publish` command but it telling please update the version of the package. Here how can I update the 3rd party package's version which is not even built. Like I am doing this for `@bable/core` and I really dont want to change the `package.json` version property for this package from my `node_modules`

**Describe the solution you'd like**
writing better docs for the usage sections

**Describe alternatives you've considered**
None
**Additional context**
![image](https://user-images.githubusercontent.com/50070488/64449842-6d90fd80-d0fe-11e9-94d3-3b3357f5a1e2.png)

**Comment by favoyang** [comment]
Are you trying to publish a modified version of @babel/core to your private registry, which uplink to npm?

**Comment by LOLdevelopr** [comment]
No I am trying to publish the same version which came upon installation

**Comment by favoyang** [comment]
It sounds similar to this https://github.com/verdaccio/verdaccio/issues/1203.

Make sure you actually publish to the privacy register with `npm publish --registry http://REGISTRY_ADDR`

**Comment by LOLdevelopr** [comment]
Yeah I did the same command which was mentioned in the verdaccio local page. Still same

**Comment by sergiohgz** [comment]
As I understand, what you really want to do is keep the same package as you have installed in your node_modules. This is done by the cache option. If cache is enabled, you don't need to publish any package you install from your node_modules, because they are cached. Take a look at this [use case](https://verdaccio.org/docs/en/caching) in docs, cache is enabled by default (you can see [here](https://verdaccio.org/docs/en/uplinks)

**Comment by juanpicado** [comment]
@LOLdevelopr you need to be your your process follow the following constrains. 

- **The version** you are trying to publish does not exist in any of the uplinks (which if you are using the default one will be the case `@babel/core@7.4.4`. ✅ 
* **Uplinks** if the package access match `'@*/*'` must not contains a `proxy` property.

If you cannot afford any of those above. Then the last option is create a specific package section for `@babel/core` without `proxy`.

```
 '@babel/core':
   access: $all
   publish: $authenticated
  unpublish: $authenticated
'@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
```
*Reminder, the order is important, your section always above the default one*

**Comment by LOLdevelopr** [comment]
Ohh, yeah it (https://github.com/verdaccio/verdaccio/issues/1460#issuecomment-529121719) striked me but then I thought that publishing here may be adding some more features like keeping sync with the upstream.

**Comment by LOLdevelopr** [comment]
Thats what, 
I was approaching this all in wrong way
I thought we can publish an existing package without bumping the version. Okay This clarifies a lot 
Again thanks a lot
