### ISSUE TITLE
Is there any way to run Verdaccio on AWS Lambda?

### ISSUE THREAD

**Issue by MohsenneChaverdie** [verdaccio/verdaccio#1464]
I am looking for a solution to run Verdaccio on a serverless compute. Based on this[ cloud formation](https://github.com/verdaccio/website/blob/master/docs/amazon.md), aparently, it is possible to run it with Dockers. Do you have any suggestions how to run it with Lambda?

**Comment by juanpicado** [comment]
I personally did not have experience with Lambda. But the author of the template might have something for you @alexjurkiewicz hopefully. Otherwise I'd recommend just rather ask on StackOverflow, Lambda is not a popular topic around here.

**Comment by alexjurkiewicz** [comment]
i doubt it is possible. you need persistent block storage. whats wrong with ecs fargate?

**Comment by juanpicado** [comment]
Thanks @alexjurkiewicz for the answer. I'll close this one, feel free to keep discussing.
