### ISSUE TITLE
[Question] Push locally installed npm packages from /node_modules to /storage

### ISSUE THREAD

**Issue by bluefangs** [verdaccio/verdaccio#1466]
Hello.

I've just recently stumbled accross verdaccio when I went looking for methods to make use of npm and npm install in an **air gapped (no internet) server using docker**. After reading a few issues here and articles, I have a basic understanding of how it works.

Since I need to have this running in a offline scenario, from the suggestions, I need to do the following:

1. Install verdaccio on an internet connected machine
2. Install all the npm packages so that verdaccio caches them in the /storage/ dir
3. Move the /storage/ dir onto the non-internet facing server and set appropriate permissions.
4. Everything should work 

Since I usually have all the packages installed locally on my dev machine, would it suffice if I move everything from my local /node_modules directory to /storage on the offline server? Or do I necessarily need to follow the above steps every time?

Thanks.

**Comment by juanpicado** [comment]
> would it suffice if I move everything from my local /node_modules directory to /storage on the offline server?

No, `node_modules` is the final result by the package manager where all tarballs are **unpackaged** and what you are goinf to have in your storate is the **packaged** tarballs. So, you cannot copy them and expect that works.

> Or do I necessarily need to follow the above steps every time?

What you need to do is, make an installation through Verdaccio with internet, Verdaccio will persist all tarballs in your storage, them copy the folder to the offline computer and repeate the installation, Verdaccio will be able to find all the tarballs in the cache, so, no internet is required for a final installation.

I will close this, but keep asking if you have more questions.
