### ISSUE TITLE
i want to konw how to delete the package that had published

### ISSUE THREAD

**Issue by shijianzhong** [verdaccio/verdaccio#1467]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by juanpicado** [comment]
Not sure what you exactly wants, but, there I go.

- Unpublish a package https://docs.npmjs.com/cli/unpublish
- Remove a package in Verdaccio storage
  - Find the folder in your storage and delete it
  - Update `.verdaccio-db.json` file and remove the reference define inside of it is is a private package.
