### ISSUE TITLE
Verdaccio freezes my Raspberry Pi and my Amazon EC2

### ISSUE THREAD

**Issue by martppa** [verdaccio/verdaccio#1468]
First I thought it was an issue with the ARM version, but it also occurs in my EC2 instance. Sometimes Verdaccio runs just fine. Somehow the system manages to kill the process where it runs and I have to start it again. Many times after the restart, Verdaccio starts using lot of RAM and CPU and just freezes the machine. It happens on my Raspberri Pi 3b and to my EC2 Micro instance. Is it only happening to me? Any idea? I am trying to reach my Raspberry Pi (it is frozen once again after Verdaccio start) to post a shot of htop. Thanks in advance.

**Comment by juanpicado** [comment]
Please fill this template before report and issue, that makes more easy to understand to track source of the problem.
https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/ISSUE_TEMPLATE/Bug_report.md

Furthermore, there are 16 different models of Raspberry Pi in the market, you need to be specific and provide enough information, remember you are the owner of your environment and without deep info we cannot do anything to help you.
