### ISSUE TITLE
[Feature] Dockerfile verdaccio 4.2.2 with verdaccio-ldap example

### ISSUE THREAD

**Issue by kopax** [verdaccio/verdaccio#1476]
Congratulation everyone who tested, contributed to Verdaccio :tada: v4 ! :balloon:

I am creating this ticket to help others, its aims to provide information to people whiling to use Verdaccio `v4.2.2` and `verdaccio-ldap` with :whale: Docker.

## Dockerfile

```Dockerfile
FROM verdaccio/verdaccio:4.2.2
USER root
RUN npm i && npm i verdaccio-ldap
USER verdaccio
```

Note: you need to switch to `root` user in order to use `npm`.

## Testing

Status: in progress

### plugin

- [x] it should work with `verdaccio-htaccess` when `verdaccio-ldap` is **not** installed. :heavy_check_mark:
- [x] it should work with `verdaccio-htaccess` when `auth.ldap` is disabled and `verdaccio-ldap` is installed. :heavy_check_mark:
- [x] it should work with one `verdaccio-ldap`. :heavy_check_mark:
- [x] it should work with `verdaccio-htaccess` and fallback to `verdaccio-ldap` through **web**. :heavy_check_mark:
- [x] it should work with `verdaccio-htaccess` and fallback to `verdaccio-ldap` through **npm**. :x: *This is annoying, either use ldap or htaccess, even if the web work, the npm will fail making it useless to have both.*

### `npm`

- [x] `npm --adduser` should work with different users. :heavy_check_mark:
- [x] `npm --adduser` should fail with wrong user/password. :heavy_check_mark:
- [ ] `npm i` in CI that download from the registry should not spam the LDAP with authentication requests without JWT.
- [ ] `npm i` in CI that download from the registry should not spam the LDAP with authentication requests with JWT.

### Web

The new design with material-UI is super nice btw.

- [x] it should authenticate with different users. :heavy_check_mark:
- [x] it should fail to authenticate with different users and wrong password. :heavy_check_mark:
- [x] it should show packages to users with `access` permissions. :heavy_check_mark:
- [x] it should hide packages to users without `access` permissions. :heavy_check_mark:

## Packages permissions

- [x] `access` should work with a user with perms. :heavy_check_mark:
- [ ] `access` should fail with a user without perms.
- [x] `access` should work with a user in ldap group with perms. :heavy_check_mark:
- [ ] `access` should fail with a user not in ldap group with perms.
- [ ] `publish` should work with a user with perms.
- [ ] `publish` should fail with a user without perms.
- [x] `publish` should work with a user in ldap group with perms. :heavy_check_mark: *For this, I add to configure  the environment `VERDACCIO_USER_UID` to be as my host account (within docker you can't chown/chmod), and from my host I had to give `chmod -R 777` to the `storage` directory, otherwise I was having `404` with `http <-- 404, user: dka(127.0.0.1), req: 'PUT /@scope%2fdocx2latex', error: no such package available`*
- [x] `publish` should fail with a user not in ldap group without perms.
- [ ] `unpublish` should work with a user with perms.
- [ ] `unpublish` should fail with a user without perms.
- [x] `unpublish` should work with a ldap group with perms. :heavy_check_mark: **For this one**:*I'd like to know if users with permissions can unpublish a package that is one year's old, or there is a limit of time like in npm registry to unpublish* @juanpicado?
- [ ] `unpublish` should fail with a user not in ldap group with perms.

## `config.yaml`

- [x] `web.logo` should support base64. :x: *It split the string and take the last part after a backslash, there is no way to escape them. (is this expected? verdaccio 3 could use base64 for logo)* 
- [x] `web.logo` should support `logo.png` from volumes. :heavy_check_mark:

**Comment by juanpicado** [comment]
hi @kopax, thanks for the kind words. Since I see you are in action again, I'd recommend the following:

- We have an example with LDAP https://github.com/verdaccio/docker-examples/tree/master/ldap-verdaccio, why don't bulk all your research there? 
- Tickets create a lot of noise for user are not that interested on LDAP, so, the better is write about it, you have better SEO (80% traffic goes through search engines anyway) https://github.com/verdaccio/website/tree/master/website/blog and furthermore you help use to raise money with ads.

For me a ticket, means either an issue or a feature request. Even I still allow questions due the low traffic, the better is pick one of options above rather pollute this ticket.

LDAP is out of my scope, since is not part our organization I cannot help, that's the plugin author responsibility, about, the web.logo issue you are reporting, if is a bug, then, the better is create a ticket with full information on it and put it in the queue, eventually will be fixed.

This format does not work with Verdaccio 4 anymore.
```
FROM verdaccio/verdaccio:4.2.2
USER root
RUN npm i --prod && npm i verdaccio-ldap
USER verdaccio
```

Docker permissions was a common issue, there are plenty of references in our database, se an example https://github.com/verdaccio/docker-examples/blob/master/amazon-s3-docker-example/v4/s3Plugin/Dockerfile

**Comment by kopax** [comment]
@juanpicado I just got through the permissions and fixed it (see my comment). Now I am a bit tired so I will pursue the testing tomorrow.

About the issue remark, I'll close it. It was for:

- people who want to get those information, I see some of them even you being interest
- me, until I have the production ready solution to share with the others. 

I agree it is not the best place but since it is not ready, I had two choices;

1. start this conversation in [verdaccio/docker-examples](https://github.com/verdaccio/docker-examples) 
1. start it here. 

I took the 2nd option because there are more issues research regarding that matter in the official repo, I'm pretty sure it will help even if closed.

You can be sure that I will upgrade all of the examples stuff with a maximum of details as soon as I have a production and stable server to share.

By now, I close the issue for not increasing the number of issues and I'll keep updating it until I a, done.

LDAP plugin works fine, and now with the JWT feature, I expect to solve all the past issues I had with this plugin.

Great job again.

**Comment by kopax** [comment]
Hi @juanpicado, I've successfully tested and deployed the v4, it honestly took me 3 days of work but it totally worth it.

FYI the `verdaccio-ldap` plugin, `verdaccio@4` and `jwt` totally play well together. Spamming issue is gone.

If you want me to write a blog post about the setup, just let me know how to proceed and I'll do it when I have free time.

**Comment by juanpicado** [comment]
>  I've successfully tested and deployed the v4, it honestly took me 2 days of work but it totally worth it.
> FYI the verdaccio-ldap plugin, verdaccio@4 and JWT totally play well together. Spamming issue is gone.

👏 👏 👏 👏 👏 👏 

> If you want me to write a blog post about the setup, just let me know how to proceed and I'll do it when I have free time.

Here one example: https://github.com/verdaccio/website/pull/188 we don't use Medium or dev.to platforms anymore.

**Comment by kopax** [comment]
> Here one example: verdaccio/website#188 we don't use Medium or dev.to platforms anymore.

Thanks, I will do my best to write something soon while it is still fresh in my head.
