### ISSUE TITLE
Where to mount web.logo static files in docker?

### ISSUE THREAD

**Issue by kopax** [verdaccio/verdaccio#1477]
I have been trying to mount a volume for `web.logo` into `/verdaccio/logo.png` and set the same value in the yaml, without success.

I've tried to find where was the static asset in the docker container but I couldn't find.

The actual default logo seems to be imported within webpack and is a hash, it doesn't exist on the repo.

**Comment by Mr-jiangzhiguo** [comment]
@kopax 
Do you make it?
I also have this question, could you share?
