### ISSUE TITLE
403: Forbidden Access error 

### ISSUE THREAD

**Issue by sameerinfodb** [verdaccio/verdaccio#1479]
**Describe the bug**
 Getting 403 Access Forbidden when accessing verdaccio api , We had a fresh installation of verdaccio and have set the registry setting in the npm to http://localhost:8083 . But when we try to install any npm package via npm install {package name} we are getting 403 error.
But when we access the UI of http://localhost:8083portal it is working fine.

We tried sending request to http://localhost:8083 via postman as well but we are getting 403 foridden access error from squid server

**To Reproduce**
1. npm install -g verdaccio
2. npm set --registry http://localhost:8083
3. verdaccio

**Expected behavior**
 package from https://registry.npmjs.org/ need get installed.

**Screenshots**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

storage: ./storage

plugins: ./plugins

web:
  title: Verdaccio
auth:
  htpasswd:
    file: ./htpasswd
listen:
    localhost:8083
security:
  api:
    legacy: true
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d
      notBefore: 1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':

    access: $all
    publish: $authenticated
    unpublish: $authenticated

    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

**log settings**
logs:
  - { type: stdout, format: pretty, level: info }

**Environment information**

verdaccio 4.2.2

**Debugging output**

**Comment by juanpicado** [comment]
Please format the markdown correctly.
