### ISSUE TITLE
Data statistics

### ISSUE THREAD

**Issue by porcelainHeart** [verdaccio/verdaccio#1482]
I want to be able to look at the statistics of downloads per package, weekly downloads, monthly downloads, people who download.
Like npmjs.org which I think is a very valuable feature.

**Comment by juanpicado** [comment]
Well, perhaps worth to share how hard is already achieve it with the npmjs, https://youtu.be/QtChaxbsw7U?t=670 so you can have an idea how hard would be.

Anyway, I will refer to my comment while ago https://github.com/verdaccio/verdaccio/issues/1201#issuecomment-457559066

**Comment by DanielRuf** [comment]
Some logging database for time series data or similar would be needed. Not sure if we could use the current logs and parse them - probably not.

**Comment by porcelainHeart** [comment]
> Well, perhaps worth to share how hard is already achieve it with the npmjs, https://youtu.be/QtChaxbsw7U?t=670 so you can have an idea how hard would be for us.
> 
> Anyway, I will refer to my comment while ago [#1201 (comment)](https://github.com/verdaccio/verdaccio/issues/1201#issuecomment-457559066)

Thanks for your reply.
Can I add a callback hook when the verdaccio is accessed.
So that I can customize the log output or store the log in the database for my own analysis.

**Comment by juanpicado** [comment]
Hooks will be improved in Verdaccio 5, but that is next year hopefully, depends of the available resources, but that is my wish. So things as you suggest will be more easy to address.

**Comment by juanpicado** [comment]
I will close this one since we have already other similar tickets.
