### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by theblackhole** [verdaccio/verdaccio#1483]
Hello,

Could you add the slack app to your repo so we could have notifications when there's a new release ?

In our company we receive release notifications on slack for tools we use (via the `/github subscribe <repository>` command). For this to work, the slack app must be installed on the repository you want to subscribe.
All tools we use has already this integration except verdaccio, could you add it please?

Here's how to do it :
- install the github app on your Slack workspace (https://slack.github.com/)
- type `/github subscribe verdaccio/verdaccio` on a channel
- it will reply :
> Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
> _Note: You need to be an organization owner to install the app (or ask one to install it for you)._
> [Install GitHub App]
- click on "Install GitHub App" and select the verdaccio repo
- Voilà, the notifications will be available to everyone :)

Thanks! (And thanks for providing an awesome tool !)

**Comment by juanpicado** [comment]
I'm not pretty familiar with their API, but, what we have at this stage is this https://verdaccio.org/docs/en/notifications  

Does it help you? or perhaps you can explain me what you expect to see on slack?

**Comment by theblackhole** [comment]
Hello,
Sorry, I think I wasn't clear. I will take time to explain.

I'm not talking about a verdaccio feature but I'm talking about the github repository itself.

Here's an example :
In our company, we're using [VMWare Harbour](https://github.com/goharbor/harbor) to store our docker images. In order to know when it's updated (and for us to plan a maintenance), we did a `/github subscribe goharbor/harbor` to receive notifications in our it/cloud channel.

![image](https://user-images.githubusercontent.com/7818904/66063876-90b79d00-e544-11e9-9f1d-c3bfb12ab4a5.png)
_slack notification on the left, release page on github on the right_

This is working because the Harbor repository owners authorized slack to have access to their repository. This is what slack asks when you use the `/github subscribe` command for the first time : 
![image](https://user-images.githubusercontent.com/7818904/66064449-af6a6380-e545-11e9-8ab8-6b6b84e475d4.png)
_if you're the owner of the repository you want to subscribe, you can click on "Install GitHub App" and it will ask permissions to access the repository_

![image](https://user-images.githubusercontent.com/7818904/66064841-80a0bd00-e546-11e9-8a34-883e57db0f6a.png)
_it will ask where to install slack (organization or personnal account) - on the left, then ask which repositories you want slack to have access - on the right_

![image](https://user-images.githubusercontent.com/7818904/66065119-0886c700-e547-11e9-8806-67e027f23905.png)
_after confirming with my password, the app appears on my repository and everyone, including me, can subscribe to notifications for commits, issues, releases... for this repository_

Since slack is not installed on the verdaccio repository and since I'm not an owner of the repository, I can't install the app by myself and subscribe to new verdaccio releases.

I hope this is more clear now 🙂

**Comment by juanpicado** [comment]
Thanks, I'll read a bit more and then back to you.

**Comment by DanielRuf** [comment]
Wouldn't we have to know the channel which gets access to the notifications?

https://slack.com/intl/en-us/help/articles/232289568-GitHub-for-Slack

https://user-images.githubusercontent.com/3877742/36522927-f1d596b6-1753-11e8-9f85-2495e657b16b.png

Also it needs specific rights: https://github.com/integrations/slack#github-permission-scopes

When I start the process it asks for my workspace so it is on a per workspace basis. I don't think that it works across workspaces and I doubt that you want it in our verdaccio.slack.com instance.

I don't think that this is the way it should work.
At least I do not yet understand where and how others should be able to get the notifications. This would mean that anyone could subscribe to events from my (private) repos?

And there is no clear permission / rights management.

**Comment by theblackhole** [comment]
Hello,

Sorry for my late response, I didn't see your reply.
What happens on your own slack workspace doesn't matter (you can choose "no channel" if you want. I'm not sure but I think you can even remove slack from your workspace after it has been added to your repository) as long as the app this installed on your repository (see my last screenshot from my last reply) and your repository is public, everyone can use the slack app on their own workspace, as I did with mine :
![image](https://user-images.githubusercontent.com/7818904/81555882-a538ff00-9389-11ea-82f1-4899f86455b9.png)
Btw, nobody, even if you're the owner, can subscribe to private repositories.

Slack has a high reputation (github even made an official page for them : https://slack.github.com/) but you're right, it doesn't seems to have fine permission management.

I think, in general, If you're concerned about privacy for your private repository, the only way is to self-host them.

Since I can subscribe to notifications now, I'm closing this issue.
