### ISSUE TITLE
Merge in code from https://github.com/fl4re/sinopia

### ISSUE THREAD

**Issue by czardoz** [verdaccio/verdaccio#15]
A few very important commits have gone into that fork, perhaps it would make sense to merge them here as well.

**Comment by trentearl** [comment]
Awesome, i'll try to look into this when I have time. @czardoz is there anything you know of that is especially important?

**Comment by czardoz** [comment]
Yes, https://github.com/fl4re/sinopia/commit/50e5baf5418fbe2a59cdacccec3b4f7841815677

It ensures that the Web UI does not show packages if the user is not signed in. But almost all the 31 commits in that fork are useful in one way or another :)

**Comment by trentearl** [comment]
@czardoz I created merge request #17 can you review this?

**Comment by czardoz** [comment]
@trentearl Totally unsure about the code base, so I doubt my review is of much help. I can confirm that the all important commit if protecting the search endpoint is indeed present.

I'll try actually running your branch later this week, and report back. :)
