### ISSUE TITLE
How to send an email on publish

### ISSUE THREAD

**Issue by kopax** [verdaccio/verdaccio#1509]
When I publish a package on npmjs registry, I get the following email:

```
Hi kopax!

A new version of the package @rollup-umd/deploy (1.2.2) was published at 2019-10-03T16:27:38.742Z from
34.66.25.221. The shasum of this package was 0a073de0fb253b82fac324a88acc4a88efb6d399.

If you have questions or security concerns, you can reply to this message or
email support@npmjs.com.

npm loves you.
```

Is there a similar feature in verdaccio?

**Comment by juanpicado** [comment]
hi @kopax , we don't do that, we can call hooks ok publish, whatever the endpoint does is up to you. You might have an endpoint that send emails. 

https://verdaccio.org/docs/en/notifications

**Comment by kopax** [comment]
Wow, impressive, I was 99% sure it was out of concerns. And that's a perfect start for sending email notifications from verdaccio.
I didn't saw that part I was writing in the search input "`email`".
