### ISSUE TITLE
Multiple nodes?

### ISSUE THREAD

**Issue by arcivanov** [verdaccio/verdaccio#151]
For redundancy the multiple node support is a must.

However, there seems to be some stateful caching going on when multiple nodes use the same verdaccio file system.

Can verdaccio be fully stateless? I.e. lock database for writing per request and not cache the results?

**Comment by juanpicado** [comment]
In short, no, the data storage is tight to file system. There is a thread  #103  about it already. I'll close this one to avoid duplicates.
