### ISSUE TITLE
custom storage path not storing npm packages

### ISSUE THREAD

**Issue by dilippatidar123** [verdaccio/verdaccio#1514]
Hi Team,
We are providing following custom path to storage in config.yml.
storage: /verdaccio/storage

In above path we can't see any packages available but verdaccio UI showing all the packages properly.

If we will not provide any path then it will store in below path. 
./storage and path will be ./config/verdaccio/storage

Can you please suggest from where we can get installed packages and put in others source or is there any other way we can export the packages and use in other sever.

Please let me know if you need other info.

Thanks,
Dilip

**Comment by juanpicado** [comment]
Please provide more context, I would recommend follow the issue template recommendations.

**Comment by sergiohgz** [comment]
@dilippatidar123, we need more context, like how you are executing Verdaccio (the command used) or if you are running in a Docker container and how are you passing the config.
But, as far I can see, you are running Verdaccio but it is not retrieving your custom config file.
