### ISSUE TITLE
When the corresponding version is selected, the readme.md does not correspond to the corresponding version

### ISSUE THREAD

**Issue by s952787097** [verdaccio/verdaccio#1519]
The operation is as follows：
Click any version, the URL will follow the change, but switch to readme, and the content of readme.md corresponding to the version will not be displayed.
![01](https://user-images.githubusercontent.com/26595017/66887226-d0828800-f00c-11e9-9a0a-1a5ca11d6114.png)
![02](https://user-images.githubusercontent.com/26595017/66887216-c496c600-f00c-11e9-9660-7ffa72702fb4.png)
![03](https://user-images.githubusercontent.com/26595017/66887221-ca8ca700-f00c-11e9-9100-32ef6dc7223d.png)

**Comment by juanpicado** [comment]
Hi, thanks for reporting this issue, I love when I see so much details. But In this case is not a bug, I added a not here 

https://verdaccio.org/blog/2019/09/30/verdaccio-430-release#browse-web-packages-by-version-https-githubcom-verdaccio-verdaccio-issues-1457-by-juanpicado

It is intended in that way.

**Comment by s952787097** [comment]
thanks
