### ISSUE TITLE
Is it possible to secure package installation with username password?

### ISSUE THREAD

**Issue by royaldevbrat** [verdaccio/verdaccio#1525]
First of all, I would like to thank you all for your great work.

**I have a question:**
I wanted to know that is there any option to secure package installation with username password?

**Comment by juanpicado** [comment]
> First of all, I would like to thank you all for your great work.

Thanks 😊 

> I wanted to know that is there any option to secure package installation with username password?

Sure you can, just use `$anonymous` on publish access.

```
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $anonymous
    unpublish: $authenticated
    proxy: npmjs
    # storage: public-packages
  '**':
    access: $authenticated
    publish: $anonymous
    unpublish: $authenticated
    proxy: npmjs
```

You can find more info here 

https://verdaccio.org/docs/en/packages 
or
https://verdaccio.org/docs/en/protect-your-dependencies

💯

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
If your question is not answered please let us know and we will reopen the issue.
