### ISSUE TITLE
Please add a functionality to take a dump of a registry like mongodump tool for mongoDB

### ISSUE THREAD

**Issue by jitesh-powankar** [verdaccio/verdaccio#1531]
**Is your feature request related to a problem?**
I want to keep taking a dump of registry for backup and HA.
**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions
 or features you've considered.

**Additional context**

**Comment by juanpicado** [comment]
Do a backup is so easy (copy and paste) that do not make sense to create a tool for it. What is the scenario you have in mind for this request ? Please give us a bit more context.

**Comment by DanielRuf** [comment]
It seems the person wants some command to easily do that (collecting, zipping and copying to the current directory).

We may need to improve the docs to make it easier for users.
