### ISSUE TITLE
Verdaccio doesn't meet npm spec. ls-collaborators

### ISSUE THREAD

**Issue by MarkLyck** [verdaccio/verdaccio#1534]
**Describe the bug**
the command `npm access ls-collaborators %package-name%` fails with "file not found"

It doesn't seem to support the npm spec for `npm access ls-collaborators`

full error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET http://verdaccio.xxxxx.com/-/package/%40xxx%2Fxxxxx/collaborators?format=cli - File not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marklyck/.npm/_logs/2019-10-24T17_42_33_951Z-debug.log
```

**To Reproduce**

package.json bits:
```
"private": false,
  "publishConfig": {
    "registry": "http://verdaccio.xxxxxx.com/"
  },
```

.npmrc file
```
registry = "http://verdaccio.xxxxxx.com/"
```

1. set up registry, login, adduser etc.
2. Publish a package to Verdaccio registry
3. run `npm access ls-collaborators %package-name%`

**Expected behavior**
ls-collaborators: Show all of the access privileges for a package. Will only show permissions for packages to which you have at least read access. If <user> is passed in, the list is filtered only to teams that user happens to belong to.

**Configuration File (cat values.yaml)**
  service:
    type: NodePort
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    port: 4873
  nodeSelector: {}
  tolerations: []
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
  uplinks:
    npmjs:
      url: https://registry.npmjs.org/
  packages:
    '@xxx/*':
      access: $all
      publish: $authenticated
    '**':
      access: $all
      publish: $authenticated
      proxy: npmjs
    '**':
  web:
    title: Verdaccio
  storage: /verdaccio/storage/data
  ingress:
    enabled: true
    hosts:
      - verdaccio.xxxxx.com
    annotations:
      kubernetes.io/ingress.global-static-ip-name: mon-prod-xxxxx
      ingress.gcp.kubernetes.io/pre-shared-cert: ${PRE_SHARED_CERT:-wildcard-xxxxxx}

**Environment information**

np@5.1.1
node@v12.12.0
npm@6.12.0
OS: Macos Catalina
git version 2.21.0 (Apple Git-122)

**Comment by juanpicado** [comment]
hi @MarkLyck , we don't support `npm access ls` 
https://github.com/verdaccio/verdaccio#compatibility

**Comment by MarkLyck** [comment]
it doesn't mention any reason why you wouldn't support it though? It's not on the list at all.

It seems like a pretty important thing to support as an npm registry? But I guess this should be a feature request then and not a bug 😞

**Comment by juanpicado** [comment]
> Feature request for this was opened over a year ago: #937

Ticket is tagged as PR-Welcome, so, hopefully someday.
