### ISSUE TITLE
[Question] Specifying the hostname on the web interface

### ISSUE THREAD

**Issue by flavienbwk** [verdaccio/verdaccio#1548]
Hello,

Is it possible with Verdaccio 4.3.4 to a custom hostname in order for the **web interface** to display the hostname instead of "localhost" ?

![image](https://user-images.githubusercontent.com/14158127/68116908-3b342e80-fefc-11e9-8a60-804ab182c0e2.png)

Thank you !

**Comment by flavienbwk** [comment]
**Partial answer :** the web interface automatically retrieves the content of the URL to display it in the help modal.

But, is it possible to fix a specific hostname in the config file of the web interface ?

**Comment by juanpicado** [comment]
hi @flavienbwk , it is not possible, it uses the one defined as `host`. See technical details here,  https://github.com/verdaccio/verdaccio/blob/master/src/api/web/index.ts#L79 

We do that due most of the users use proxies as `Nginx` or `HAProxy`. Otherwise would be missleading.

**Comment by flavienbwk** [comment]
Thank you for your quick answer !
