### ISSUE TITLE
Verdaccio authentication using customized database,MYSQL

### ISSUE THREAD

**Issue by sathishchandran97** [verdaccio/verdaccio#1549]
**Is your feature request related to a problem?**
Hi all, I'm struck with the situation that , I need to authenticate the verdaccio using my MYSQL database.

**Describe the solution you'd like**
Is there any plugin or any other way to achieve this

**Additional context**
Thanks in Advance

**Comment by juanpicado** [comment]
As far I know there is no plugin, but you could built one :) and share it.

**Comment by sathishchandran97** [comment]
Oh... Okay thanks @juanpicado
