### ISSUE TITLE
Support for spaces in group names

### ISSUE THREAD

**Issue by kerbs17** [verdaccio/verdaccio#1550]
**Is your feature request related to a problem?**
We are using verdaccio-ldap plugin and many of our users belong to groups that contain spaces or perhaps special characters like `@ {division} {location}`

**Describe the solution you'd like**
Is there support for groups that have spaces in them?

**Describe alternatives you've considered**
Alternatively I can use only groups that fit the criteria of groups in verdaccio, but wanted to check if perhaps there was a way of making it work out of the box.

**Comment by juanpicado** [comment]
Questions related with the plugin, better here:

https://github.com/Alexandre-io/verdaccio-ldap

> Is there support for groups that have spaces in them?

Nop, due the design, spaces are interpreted as different groups, we get a string and split it by spaces.

**Comment by kerbs17** [comment]
Thanks @juanpicado, I will close this and take alternative approach.
