### ISSUE TITLE
How do I only back-up private packages

### ISSUE THREAD

**Issue by daimingru** [verdaccio/verdaccio#1553]
**Is your feature request related to a problem?**
I wanna back-up private packages, but there are many useless packages in this folder.

**Describe the solution you'd like**
can i upload private packages to other folder ? 

**Describe alternatives you've considered**
as long as i upload private packages to other folder , i will only back-up this folder to other computer.

**Comment by juanpicado** [comment]
hi @daimingru 

here is explained https://github.com/verdaccio/verdaccio/issues/965#issuecomment-423724276

**Comment by daimingru** [comment]
@juanpicado okay it's great!
