### ISSUE TITLE
怎么删除干净

### ISSUE THREAD

**Issue by fish-uncle** [verdaccio/verdaccio#1563]
怎么删除干净，包括用户npm包之类
因为我一开始做个测试
但是在正式使用后
npm uninstall verdaccio
数据还都在

**Comment by jachstet-sea** [comment]
Please post issues in English language. Thanks 👍

**Comment by fish-uncle** [comment]
How to delete it, including user NPM package and so on

Because I started with a test

But after the official use
```
npm uninstall verdaccio
```
The data is still there

**Comment by jachstet-sea** [comment]
Indeed, the data will still be there if you just uninstall the npm package.
All data is stored in `~/.config/verdaccio`. It's prefectly fine to delete that folder if you don't need that data anymore.

**Comment by fish-uncle** [comment]
thanks :smile:
