### ISSUE TITLE
Some resources point to 127.0.0.1

### ISSUE THREAD

**Issue by fish-uncle** [verdaccio/verdaccio#1564]
![](http://cdn.shenzhepei.com/QQ%E6%B5%8F%E8%A7%88%E5%99%A8%E6%88%AA%E5%9B%BE20191108221803.jpg)
In the figure, some resources point to 127.0.0.1

I don't know what's going on

I tried to change config.yml

Added
```
listen: 0.0.0.0:4873
```
But it didn't work

I tried it, too.
```
verdaccio -c config.yml
```
But he reported.
```
Error: CONFIG: it does not look like a valid config file
```
I didn't change the other parts. It's normal to start

This is a wrong hint, I think

**Comment by fish-uncle** [comment]
![http://cdn.shenzhepei.com/QQ%E6%B5%8F%E8%A7%88%E5%99%A8%E6%88%AA%E5%9B%BE20191108221803.jpg](http://cdn.shenzhepei.com/QQ%E6%B5%8F%E8%A7%88%E5%99%A8%E6%88%AA%E5%9B%BE20191108221803.jpg)

Supplementary pictures :smile:

**Comment by juanpicado** [comment]
Verdaccio takes the host delivered by the browser. Just like that :)

**Comment by fish-uncle** [comment]
But I use the http://npm.example.com to visit
127.0.0.1 in page resources

**Comment by juanpicado** [comment]
If you are using a reverse proxy, be aware you need to provide the right host to Verdaccio

https://github.com/verdaccio/docker-examples/tree/master/reverse_proxy/nginx
https://verdaccio.org/docs/en/reverse-proxy

https://www.ctrl.blog/entry/how-to-httpd-reverseproxy-hostheader.html

This something completely is under your control, so I'll close this.

**Comment by fish-uncle** [comment]
i fixed it.
nginx added the following configuration
```
proxy_set_header Host            $host:$server_port;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;
```
This alone will cause the above problems

```
server {
        listen       80;
        server_name  npm.example.com;
        location / {
            proxy_pass http://127.0.0.1:4873;
        }
    }
```
Trample through the pit :smile_cat:

**Comment by juanpicado** [comment]
👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻 Cool thanks for sharing !
