### ISSUE TITLE
IIS hosting using the iisnode in a virtual directory

### ISSUE THREAD

**Issue by miscalencu** [verdaccio/verdaccio#1565]
If you try to install verdaccio in IIS using the tutorial at https://verdaccio.org/docs/en/iss-server, this will only work if you host the application in the root of a website (default 80 port or a different one).

If you want to host it in a virtual folder (example: /iisverdaccio), the app will start, but it will always try to resolve _/iisverdaccio/packagename_. Not even the web interface is displayed, because instead the API searches for _/iisverdaccio_ package and you get:

`http <-- 404, user: null(undefined), req: 'GET /iisverdaccio', error: no such package available`

As a solution, I think **url_prefix** should be considered and the correct path should be passed to the API. Now if I am not mistaken, the **url_prefix** is only considered to correctly resolve the static resources for the web interface. So, if I set the **url_prefix** to '/iisverdaccio/', the API should try to resolve the package _/packagename_ (instead of _/iisverdaccio/packagename_). This does not happen now.

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/pull/2122
