### ISSUE TITLE
Verdaccio private proxy "npm install" won't function offline

### ISSUE THREAD

**Issue by nrydevopswatch** [verdaccio/verdaccio#1566]
Hello,

I have been working on this for several days and coming up with a custom Verdaccio setup on Docker so it is can be used with the project I'm working on. The key requirement here that is unique is the environment for this project is on an offline network for security reasons. I have cached all of the required NPM packages using https://www.npmjs.com/package/npm-offline-packager

However, no matter what I try I can't get Verdaccio to work when there is no internet connection (offline). I have a duplicate test environment setup in the cloud with the same Linux OS so I can test with and without internet so I can confirm it is working when online. 

### Environment:
CentOS 6.9
Docker version 1.7.1, build 786b29d

I'm using the latest Verdaccio container from Docker Hub. The reason I have to use Docker 1.7.1 is because that is the latest version of Docker that works and is stable with CentOS 6.9. However, the Verdaccio Docker container appears to be running and functioning perfectly fine on here when internet is connected on my testing environment. 

## here is my Verdaccio config.yaml file:
```
#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://github.com/verdaccio/verdaccio/blob/master/wiki/docker.md#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage
# path to a directory with plugins to include
plugins: /verdaccio/plugins

listen:
    0.0.0.0:4873

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000
security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d

# a list of other known repositories we can talk to
uplinks:
  private:
    url: 0.0.0.0:4873

packages:
  '@nrydevops/*':
      access: $all
      publish: $all
      proxy: private
      allow_offline: true

  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: private
    allow_offline: true

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $all

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: trace}
  #- {type: file, path: verdaccio.log, level: info}
```

The docker run command I am using is:
```
docker run -v ~/verdaccio/storage/:/verdaccio/storage/ -v ~/verdaccio/storage.tar:/verdaccio/storage.tar -v ~/verdaccio/conf/:/verdaccio/conf/  -p 4873:4873 {Container Image ID}
```
I can docker exec into the container and confirm that the (storage, conf, and storage.tar) are going into the correct directory inside the Verdaccio container. 

Steps to reproduce the issue:
-with above config and with internet connected I run:
```
npm install --registry http://localhost:4873/
```

Verdaccio works as expected and pulls the NPM modules from the tarballs in the cached storage. 

-IMPORTANT STEP:
-I enable some firewall rules on the cloud server test environment which disabled public internet. 
-I can still do:   curl http://localhost:4873/   and I get the Verdaccio web GUI html output
-I can also ping the CentOS 6.9 server where the Verdaccio server is running from my Node client machine on the same local network. I can ping the CentOS host server from my Node client machine as well. All local network traffic is working fine. 

## For some reason Verdaccio fails and will not pull the NPM modules from the Verdaccio storage and eventually the "npm install" command fails with:
```
error--- unexpected error: connect ETIMEDOUT 104.16.19.35:443
Error: connect ETIMEDOUT 104.16.19.35:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
 http <-- 500, user: null(10.150.0.23), req: 'POST /-/npm/v1/security/audits/quick', error: internal server error
 error--- unexpected error: connect ETIMEDOUT 104.16.16.35:443
Error: connect ETIMEDOUT 104.16.16.35:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
 http <-- 500, user: null(10.150.0.23), req: 'POST /-/npm/v1/security/audits/quick', error: internal server error
```

### Here is a sample of the output when internet is connected and Verdaccio is functioning as it is expected:
```
trace--- [local-storage/getPackageStorage]: storage path: /verdaccio/storage/object-visit
 debug--- [local-storage/readPackage] read a package: object-visit
 trace--- [local-storage/_readStorageFile] read a file: /verdaccio/storage/object-visit/package.json
 info <-- 10.150.0.23 requested 'GET /has-values'
 trace--- [middleware/allow][access] allow for undefined
 trace--- allow access for has-values
 trace--- [auth/allow_action]: user: undefined
 trace--- [auth/allow_action]: hasPermission? true for user: undefined
 trace--- auth/allow_action: access granted to: undefined
 trace--- allowed access for has-values
 trace--- [local-storage/getPackageStorage]: storage selected: /verdaccio/storage
 trace--- [local-storage/getPackageStorage]: storage path: /verdaccio/storage/has-values
 debug--- [local-storage/readPackage] read a package: has-values
 trace--- [local-storage/_readStorageFile] read a file: /verdaccio/storage/has-values/package.json
 trace--- [local-storage/_readStorageFile] read file succeed: /verdaccio/storage/object-copy/package.json
 trace--- [local-storage/readPackage/_readStorageFile] read a package succeed: object-copy
 http <-- 304, user: null(10.150.0.23), req: 'GET /object-copy', bytes: 0/0
 trace--- [local-storage/_readStorageFile] read file succeed: /verdaccio/storage/map-visit/package.json
 trace--- [local-storage/readPackage/_readStorageFile] read a package succeed: map-visit
 http <-- 304, user: null(10.150.0.23), req: 'GET /map-visit', bytes: 0/0
 trace--- [local-storage/_readStorageFile] read file succeed: /verdaccio/storage/has-values/package.json
 trace--- [local-storage/readPackage/_readStorageFile] read a package succeed: has-values
 http <-- 304, user: null(10.150.0.23), req: 'GET /has-values', bytes: 0/0
 trace--- [local-storage/_readStorageFile] read file succeed: /verdaccio/storage/object-visit/package.json
 trace--- [local-storage/readPackage/_readStorageFile] read a package succeed: object-visit
 http <-- 304, user: null(10.150.0.23), req: 'GET /object-visit', bytes: 0/0
 info <-- 10.150.0.23 requested 'GET /has-values'
 trace--- [middleware/allow][access] allow for undefined
 trace--- allow access for has-values
 trace--- [auth/allow_action]: user: undefined
 trace--- [auth/allow_action]: hasPermission? true for user: undefined
 trace--- auth/allow_action: access granted to: undefined
 trace--- allowed access for has-values
 trace--- [local-storage/getPackageStorage]: storage selected: /verdaccio/storage
 trace--- [local-storage/getPackageStorage]: storage path: /verdaccio/storage/has-values
 debug--- [local-storage/readPackage] read a package: has-values
 trace--- [local-storage/_readStorageFile] read a file: /verdaccio/storage/has-values/package.json
 trace--- [local-storage/_readStorageFile] read file succeed: /verdaccio/storage/has-values/package.json
 trace--- [local-storage/readPackage/_readStorageFile] read a package succeed: has-values
 http <-- 304, user: null(10.150.0.23), req: 'GET /has-values', bytes: 0/0
 info <-- 10.150.0.23 requested 'GET /copy-descriptor'
 trace--- [middleware/allow][access] allow for undefined
 trace--- allow access for copy-descriptor
 trace--- [auth/allow_action]: user: undefined
 trace--- [auth/allow_action]: hasPermission? true for user: undefined
 trace--- auth/allow_action: access granted to: undefined
 trace--- allowed access for copy-descriptor
 trace--- [local-storage/getPackageStorage]: storage selected: /verdaccio/storage
 trace--- [local-storage/getPackageStorage]: storage path: /verdaccio/storage/copy-descriptor
 debug--- [local-storage/readPackage] read a package: copy-descriptor
 trace--- [local-storage/_readStorageFile] read a file: /verdaccio/storage/copy-descriptor/package.json
 trace--- [local-storage/_readStorageFile] read file succeed: /verdaccio/storage/copy-descriptor/package.json
 trace--- [local-storage/readPackage/_readStorageFile] read a package succeed: copy-descriptor
 http <-- 304, user: null(10.150.0.23), req: 'GET /copy-descriptor', bytes: 0/0
 info <-- 10.150.0.23 requested 'POST /-/npm/v1/security/audits/quick'
```

As you can see it is working as expected with internet and that is the only difference. Isn't Verdaccio supposed to be able to work in "Offline Mode" ? 

I greatly appreciate any help with this as I have been working on it for several days and I really need to get it working. Thank you in advance!

**Comment by juanpicado** [comment]
I see you have `proxy: npmjs` in your config file. Actually I'm not aware what `npm-offline-packager` does.

The **offline** mode has a IF you must keep on mind, it works whether in the local cache  you have all required dependencies already cached or as it seems to be in your case, you have a sort of mirror, but not all proxies seems to point there.

The `http://104.16.19.35:443/` seems to point to cloudfare, which is where npmjs` is being hosted.

**Comment by nrydevopswatch** [comment]
@juanpicado Thank you for your reply! 'npm-offline-packager' is an NPM module that just fetches the tarballs of the NPM modules from npmjs public repo. It is compatible with Verdaccio as they state on their npmjs page. 

I did remove the reference your referring to 'proxy: npmjs' and on my cloud testing environment I was able to get this all to work with no public internet connection. The issue I'm still having is that I can't get it to work on the actual offline environment where I'm needing to use this solution. I tested on the cloud environment with the same CentOS 6.9 version and made sure that the public internet is completely disabled through firewall rules. 

I can go into one of my React project directories without any node_modules folder and run 'npm install' and it will pull the NPM packages from the tarballs from the mirror I setup. It works great and I am then able to run 'npm start' and that project launches and functions as it should. 

However, when I try the same thing with the exact same config.yaml file on the offline network that is local and I need to get this working on; it keeps failing when it tries to reach out to 'npmjs' even though I do not have 'npmjs' in the config file at all anymore. 

Any idea why it is trying to reach out to 'npmjs' when it is completely removed from the config.yaml? Even though the exact same setup works great on my replicated "offline" test environment I setup in the cloud? 

I also tried to use the command 'npm cache clean --force' on my Node.js client machine to make sure there are not some sort of artifacts referencing to 'npmjs'

**Comment by juanpicado** [comment]
> 
> However, when I try the same thing with the exact same config.yaml file on the offline network that is local and I need to get this working on; it keeps failing when it tries to reach out to npmjs even though I do not have npmjs in the config file at all anymore.

Then remove all `proxy` props in your `config.yaml`. If you use `proxy` Verdaccio will try to fetch from default uplinks.

**Comment by juanpicado** [comment]
> Any idea why it is trying to reach out to 'npmjs' when it is completely removed from the config.yaml? Even though the exact same setup works great on my replicated offline test environment I setup in the cloud?

Yes, if you remove all uplinks, it will fallback to `npmjs` by default, this is something added in **sinopia era** and since we have backward compability I did not want to remove it.

So, the better is define uplinks empty.

Real `offline` is a bit tricky and require some knowledge but also require some previous action from your side.

1. Cache everything with right uplinks and proxy conf.
2. Remove proxies
3. Comment out all uplinks

Then you got real offline sugar.

**Comment by nrydevopswatch** [comment]
@juanpicado Thanks again for the help with this! 
I have tried all of these suggestions but each time it keeps trying to reach out to ```npmjs```
I just tried to:
-remove proxies
-comment out all uplinks
-everything is cached already using ```npm-offline-packager``` and I can 100% confirm that I'm able to use Verdaccio to pull and install all of the NPM packages when I test it on the cloud environment. 

```
One thing I did noticed that I want to ask about is this error I'm getting:
'GET /npm' error: loop detected
'GET /npm' error no such package available
```

I know that NPM is certainly installed on my local node client machine. The machine I'm running ```npm install``` from.

**Comment by nrydevopswatch** [comment]
I can see from the Docker Logs that it is using ```local-storage...``` but it seems like the main problem I am having is that Verdaccio is not detecting the packages because it keeps saying ```package not available``` but like I said before this exact same setup worked on my other environment. I just can't figure out what is different on the local dev environment that is causing it to fail.

**Comment by nrydevopswatch** [comment]
@juanpicado 
So I spent some more time trying to get this to work. I followed your steps above:
```
-Cache everything with right uplinks and proxy conf.
-Remove proxies
-Comment out all uplinks
```
However, after following these steps, no matter what I try Verdaccio still tries to connect to npmjs.org and fails. I even went through all of the Node.js sample project code and tried removing/replacing https://npmjs.org:4873/@packagename_package-version   with  https://localhost:4873/@packagename_package-version and while that seemed to help a little bit; it still fails to fully resolve the entire package.json dependencies. 

Is there anything else I can try before giving up on using Verdaccio as a solution to this problem? I can't continue spending significant time on this unless there is something simple I'm missing. However I really do need a working solution that is usable in an offline private development environment. At this point if this does not work then I will have to go back to getting NPM updates by downloading them on another network and moving them over to the development network that does not have internet. I have this all setup in Docker with a working Docker Compose yaml and my main goal is to be able to use NPM scripts which currently do not work on the offline private network. 
My Docker Setup:-Container 1: Verdaccio (with "config" and "storage" data is mounted to the Docker container using Docker Volumes)-Container 2: Node (with Node.js sample code mounted into container using Docker Volumes)
Permissions inside Docker containers are setup correctly and I also confirmed that the two containers can communicate between each other on a Docker network. 
Something is broken with NPM or Node from manually moving all the files over to that network. Of course in a normal environment I could delete the "node_modules" folder and package-lock.json file and simply run "npm install" to fix NPM/Node. That is not possible in this situation as the development network does not and cannot have public internet connectivity. 
Any other suggestions on this before I move on?
Is it possible for Verdaccio to be updated to have an actually "offline mode"??? I think that would be incredibly helpful to many people as it is one of the primary use-case for Artifactory and Nexus. 

Thank you in advance for you help!

**Comment by nrydevopswatch** [comment]
@juanpicado I would like to make a proposal for Verdaccio to have a dedicated feature for "offline mode" and I'm interested in getting involved as a developer to help out if possible. I'm not sure if this is viable or if it would require the entire Verdaccio code base to be re-architected. 

Earlier you said, "this is something added in sinopia era and since we have backward compability I did not want to remove it." so I'm wonder if it could be added to the project in a reasonable manner. If so then I would like to volunteer my time as I think it would be a worthwhile effort for many in the community. Happy Holidays and I look forward to your response.

**Comment by DanielRuf** [comment]
Related:

https://github.com/verdaccio/verdaccio/issues/1634
https://github.com/verdaccio/verdaccio/issues/1633

**Comment by DanielRuf** [comment]
Please see https://github.com/verdaccio/verdaccio/issues/1633 for details, the `serveFile` method is probably the relevant part.
