### ISSUE TITLE
Show snippet of changelog in notifications

### ISSUE THREAD

**Issue by soraryu** [verdaccio/verdaccio#1567]
**Is your feature request related to a problem?**
I've set up Slack notifications for our custom Verdaccio registry, and everyone loves it. However, one big thing missing is that there's no way to see a changelog. There isn't on the Verdaccio website, either; I found #813 which seems to have suggested having it for the website as well but was closed as "not possible".
Has the situation changed?

**Describe the solution you'd like**
I'd like users to be able to see what has changed, not just that a change has happened. We're using semantic versioning (as nearly everyone is by now) so the changelog actually follows pretty strict conventions and should be parseable pretty easily.
Ideally, I would want that to be integrated with notification hooks so I can integrate the full Changelog or the last Changelog in the notification.

**Describe alternatives you've considered**
Only alternative is to have a separate channel for showing what has changed, which increases maintenance effort considerably.

**Additional context**
Some more context: Unity Technologies is [recommending Verdaccio as External Package Registry](https://docs.unity3d.com/Manual/upm-scoped.html) for their Unity Package Manager (link here), so expect more people to use it in the future. Unity does have a specific structure for packages, for example they always come with a CHANGELOG.md on the top level.

Our Slack integration would be even better with Changelog info or at least the changelog on the registry website;)
![image](https://user-images.githubusercontent.com/2693840/68906974-601f7180-0746-11ea-8cb4-f0ecf7142db1.png)

**Comment by juanpicado** [comment]
Hi @soraryu , thanks for the detailed ticket. Unfortunately the situation is the same as #813 due Verdaccio does not unpack the tarballs and due limitations of **package managers that only provides the README as text format** we cannot do anything about it. So, even if we would do something, you still need a package manager that interacts with Verdaccio properly.
