### ISSUE TITLE
run behind nginx, with different port and domain name

### ISSUE THREAD

**Issue by GongT** [verdaccio/verdaccio#157]
I run verdaccio behind nginx, let nginx listen "0.0.0.0:80", and verdaccio listen "127.0.0.1:8888".     
user will not able to download package tarball, because the url will be "http://127.0.0.1:8888/xxxx"     

searched document and code, seems no "domain" option ?

**Comment by juanpicado** [comment]
@GongT  Does this helps https://github.com/verdaccio/verdaccio/wiki/Reverse-Proxy-Setup ?

**Comment by GongT** [comment]
said... this is not work at all...

**Comment by GongT** [comment]
ok... just set “url_prefix” in config file...

**Comment by juanpicado** [comment]
@GongT I didn't get it. What's the fix? Would make sense update the wiki for future references?

**Comment by GongT** [comment]
I think you can just add a link  to config example in README.
I use verdaccio about half a year, but I did not know there is a "url_prefix". 
I kown this project from npm serach, install with npm cli, and did some simple config by reading README.
I won't know there is a usefull "conf" folder without "looking into source code".

**Comment by Meeeeow** [comment]
@juanpicado I have done it, see #160

**Comment by GongT** [comment]
thanks!
