### ISSUE TITLE
v4 and JWT, my CI got disconnected after 30 days, is there a way to make 1 password persistent and the others expire ?

### ISSUE THREAD

**Issue by kopax** [verdaccio/verdaccio#1578]
Hello,

I am using verdaccio v4 and JWT authentication.

My CI got disconnected after 30 days due to the password expire policy, is there a way to make 1 password persistent and the other expires?

**Comment by juanpicado** [comment]
Perhaps https://github.com/auth0/node-jsonwebtoken/issues/417

**Comment by kopax** [comment]
Yes you can disable it, but there's no way to have just 1 credential at the moment.

**Comment by juanpicado** [comment]
Do you mean for each token ? Some expire others does not ?

**Comment by kopax** [comment]
No I mean just for one. We have a CI account. We do not want to expire this one

**Comment by juanpicado** [comment]
No, it is not possible. Even if were possible, how would you differentiate between tokens?

At this point, if you want to have no expiring token, perhaps, setup your config accordingly and generate such token and then rollback the conf with expire tokens. 

Analyzing what others do, I don't know any service or tool that provide such advanced feature.

**Comment by kopax** [comment]
> At this point, if you want to have no expiring token, perhaps, setup your config accordingly and generate such token and then rollback the conf with expire tokens.


I am not sure if I understand, I believe you are telling me to disable the expiring date so they are lifetime jwt. I feel like that's a less good security if people left the organization they still have a valid lifetime jwt unless we revoke them.

> Analyzing what others do, I don't know any service or tool that provide such advanced feature.


> No, it is not possible. Even if were possible, how would you differentiate between tokens?

I am not sure how to achieve that. So far I see multiple options:

- allowing two authentication modules with choosable authentication strategy between legacy and jwt, use one database for robot such as `verdaccio-htaccess`
- automatically renewing the jwt every month, that seems like a good option and I'll probably go that way.


Thanks for giving your opinion.
