### ISSUE TITLE
Problem installing on fresh CentOS 7 server

### ISSUE THREAD

**Issue by rmgmediaval** [verdaccio/verdaccio#1592]
I am having issues installing Verdaccio on a fresh CentOS 7 server. Please see below.
Can someone help me out?

````
[root@localhost ~]# npm i -g verdaccio
/usr/bin/verdaccio -> /usr/lib/node_modules/verdaccio/bin/verdaccio

> dtrace-provider@0.8.8 install /usr/lib/node_modules/verdaccio/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/root/.cache/node-gyp/10.17.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/verdaccio/node_modules/dtrace-provider/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/verdaccio/node_modules/dtrace-provider/.node-gyp'
gyp ERR! System Linux 3.10.0-1062.4.3.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/verdaccio/node_modules/dtrace-provider
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

> leveldown@5.4.1 install /usr/lib/node_modules/verdaccio/node_modules/leveldown
> node-gyp-build

> level@5.0.1 postinstall /usr/lib/node_modules/verdaccio/node_modules/level
> opencollective-postinstall || exit 0

Thank you for using level!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/level/donate

npm WARN jsdom@15.2.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.

+ verdaccio@4.3.5
added 307 packages from 276 contributors in 9.362s
[root@localhost ~]#
````

**Comment by juanpicado** [comment]
You clearly have Node.js permission issues, My suggestion, I would find the way to use nvm rather global Node.js installation.

**Comment by rmgmediaval** [comment]
Thank you. I Followed your suggestion and installed nvm.
Please note that I used ``--unsafe-perm=true --allow-root``

``[root@localhost ~]# npm install -g verdaccio --unsafe-perm=true --allow-root
/root/.npm-global/bin/verdaccio -> /root/.npm-global/lib/node_modules/verdaccio/bin/verdaccio
npm WARN jsdom@15.2.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
+ verdaccio@4.3.5
updated 1 package in 7.747s
[root@localhost ~]#``

**Comment by juanpicado** [comment]
`--unsafe-perm=true` = https://geedew.com/What-does-unsafe-perm-in-npm-actually-do/
and `--allow-root` seems to be used to allow root usage. 

Just as a side note, **Verdaccio do not requires root** user to work and we never tested in that way, any further issue originated, it is up to you 🙃 . Thus, future note, those flags are not required to use Verdaccio.
