### ISSUE TITLE
Use custom favicon 

### ISSUE THREAD

**Issue by daolou** [verdaccio/verdaccio#1593]
![image](https://user-images.githubusercontent.com/22312092/69472764-340c8c00-0de9-11ea-80ec-dc121da41ad8.png)

How to change this favicon

**Comment by juanpicado** [comment]
Hi,

It is not possible at this stage.

**Comment by AimLuo** [comment]
> Hi,
> 
> It is not possible at this stage.

😭

**Comment by DanielRuf** [comment]
Theoretically it can be changed by patching / replacing https://github.com/verdaccio/ui/blob/master/src/template/favicon.ico

**Comment by qtiki** [comment]
I was looking for this too. Nowadays the config supports setting the logo as well as the primary color which is already great for giving the Verdaccio instance a "company feel". I would very much like to be able to set the favicon similar to how the logo is set from the config.

So could this issue be converted to a feature request - maybe with a more descriptive title?

**Comment by DanielRuf** [comment]
> So could this issue be converted to a feature request - maybe with a more descriptive title?

That would be great.

**Comment by juanpicado** [comment]
cc: @priscilawebdev

**Comment by juanpicado** [comment]
Closing, support provided by #2122
