### ISSUE TITLE
I can't publish a package over existing version, even add '--force'

### ISSUE THREAD

**Issue by Tiny-Fendy** [verdaccio/verdaccio#1594]
Version: 4.3.5;
What's the problem: I have publish a package which version is 1.0.1，but when I publish  force it throw an error:
npm ERR! code E400
npm ERR! 400 Bad Request - PUT http://localhost:4873/{my package} - unsupported registry call.

The same problem exists when I publish the version which I have unpublished.

The steps are as follows:
1. publish a package v1.0.0
2. unpublish it
3. publish the package v1.0.0 again
then you can see the error.

**Comment by Tiny-Fendy** [comment]
I have a discovery about the above problem.
After I unpublish a package successsly, the file storage/.sinopia-db.json and storage/{package}/package.json updated correctly, but the package.tgz has't been delete.

**Comment by Tiny-Fendy** [comment]
I hope I have described the problem clearly.

**Comment by favoyang** [comment]
`.sinopia-db.json` that sounds very old version. Which verdaccio version you use? If it's already the latest version, then the issue maybe a duplication of https://github.com/verdaccio/verdaccio/issues/1435

**Comment by DanielRuf** [comment]
> `.sinopia-db.json` that sounds very old version. Which verdaccio version you use? If it's already the latest version, then the issue maybe a duplication of #1435

This should be from a verdaccio 3 or older instance. Not sure if this is automatically renamed. Because we still support it.

See https://github.com/verdaccio/monorepo/blob/5e677f7ea5316a35ba73b6a9696cf3339b90f805/plugins/local-storage/src/local-database.ts#L25 and https://github.com/verdaccio/monorepo/blob/5e677f7ea5316a35ba73b6a9696cf3339b90f805/plugins/local-storage/src/local-database.ts#L389-L399

**Comment by DanielRuf** [comment]
@Tiny-Fendy does this still happen with the latest 4.4.x release?

**Comment by favoyang** [comment]
This link https://github.com/verdaccio/verdaccio/issues/1435#issuecomment-559977118 explains why republish package is not fixable because of the npm-cli behavior.

**Comment by DanielRuf** [comment]
I agree with you on that. So there are the options in the linked comment. Shall we close this as `wontfix` as this always produces issues in production? You can only publish a new version because of metadata and other things which are checked.

**Comment by pawelrudnicki** [comment]
@Tiny-Fendy which version of node do you use?

**Comment by DanielRuf** [comment]
> @Tiny-Fendy which version of node do you use?

I don't think that this is related to the Node version.

**Comment by Tiny-Fendy** [comment]
> @Tiny-Fendy does this still happen with the latest 4.4.x release?

Let me have a try.

**Comment by Tiny-Fendy** [comment]
@DanielRuf yes, it still happened with v4.4.4.

It throw  an error after I unpublish a plugin @wukong/wukong-vscode v1.0.1.

"http <-- 403, user: fengdi(127.0.0.1), req: 'PUT /@wukong%2fwukong-vscode/-rev/42-b55f99cebd35f9a7', error: user fengdi is not allowed to unpublish package @wukong/wukong-vscode"

But the second arguments value which the callback function in allow_publish and allow_unpublish.
`
allow_publish(user, pkg, callback) { callback(null, true) },
allow_unpublish(user, pkg, callback) { callback(null, true) }
 `
And an other  appearance is the 1.0.1 has been deleted but the file wukong-vscode-1.0.1.tgz hasn't  been removed.
![image](https://user-images.githubusercontent.com/8954107/76626798-c7bebf80-6574-11ea-81a2-8edaa9abaff1.png)
![image](https://user-images.githubusercontent.com/8954107/76626886-eae96f00-6574-11ea-9461-cbae0c139f17.png)
