### ISSUE TITLE
Support request: What is the default password?

### ISSUE THREAD

**Issue by 030** [verdaccio/verdaccio#1599]
https://devops.stackexchange.com/q/9964/210

Perhaps this should be added to the README, but there is probably a good reason for the omission. I basically wanted to test something quickly.

**Comment by favoyang** [comment]
No default password, you need regsiter an user first.

**Comment by 030** [comment]
@favoyang It seems to work now. I added comment to the DevOps SE Q&A that contains the issues I experienced.
