### ISSUE TITLE
node v6 issues

### ISSUE THREAD

**Issue by mr47** [verdaccio/verdaccio#16]
So it's more like that https://github.com/rlidwka/sinopia goes away. RIP.
Once again i think we need get call here all from https://github.com/rlidwka/sinopia/issues/376

Just started with testing on node v6. It works. In few days will try to test this fork.

If some one find npm/node related issue i think this is right place.

Thanks.

**Comment by iyel** [comment]
Glad that project received second breathe

**Comment by trentearl** [comment]
Ok sorry for the delay tests on node 6 are fixed, 0.10 tests dont pass on OSX. Travis still passes them though. I think this is just because the tests are running by starting the server in a new process. I am trying to get the server in test to start in the same process.
