### ISSUE TITLE
Support the weekly downloads feature

### ISSUE THREAD

**Issue by fkyq** [verdaccio/verdaccio#1606]
Hello, I want to know, does the verdaccio support the weekly downloads feature such as npmjs.com?
We can get the weekly downloads of the package that i pushed.
Hope to your opinion.

**Comment by juanpicado** [comment]
hi @fkyq 

Of course, I'm here to share all I know 🙃 . I've been asked for this in the past, here some references

https://github.com/verdaccio/verdaccio/issues/1482#issuecomment-537231345 and https://github.com/verdaccio/verdaccio/issues/1201#issuecomment-457559066

Hopefully that covers and answer your question.

**Comment by DanielRuf** [comment]
Closing as we won't support this in the near future.

**Comment by favoyang** [comment]
Base on my experiences of implementing such counting record system, the proper design depends on the demand of query. If you want to know who downloads what package, then a time-series database / parse-able logging system is required. But it seems not the case here - verdaccio only need to know monthly, weekly, lifetime downloads. Pre-computing data to fit these queries is an okay practice and sometimes the only right way to go for a scalable deployment.

I checked the video on https://github.com/verdaccio/verdaccio/issues/1482#issuecomment-537231345, which barely mentioned the download stats is moved to Redis. It's highly possible they're following the same approach. Which means whenever a tarball download URL is touched

- Redis `dl:<package-name>` the life time downloads, increases 1
- Redis `dl-mo:<package-name>:<yyyymm>` the monthly downloads, increases 1
- Redis `dl-wk:<package-name>:<yyyymmdd>` the weekly downloads (stores to the Monday), increases 1

The approach delegates the persistent of download stats to Redis. The approach won't support history download stats data, an one-time parse-log-then-upload-to-redis script is needed.

This is an affordable solution for me, I'd like to know your thought.
