### ISSUE TITLE
seperate s3 subfolders (key prefix for different packages)

### ISSUE THREAD

**Issue by tetrohed** [verdaccio/verdaccio#1608]
**Is your feature request related to a problem?**
 Currently, the s3 plugin adds all packages (proxy or none proxy) flat out in the root of s3 bucket.
**Describe the solution you'd like**
Ideally, the storage: custom_folder for every package regex should also work for the s3.

```packages:
'@*/*':
access: $all
publish: $all
proxy: npmjs
storage: custom_folder
```

this would cache the packages to s3/bucket/custom_folder

**Rationale** 
 we want to have our private packages persistently in S3, and cache npmjs packages there as well. But be able to clear the whole cache at regular intervals without touching our own private packages. Having these two separated makes maintenance easier.

**Alternatives**
For now we have been setting cache:false for npmjs uplinks to avoid polluting our s3 instance

**Additional context**
I would be able to make a PR on this, but I have a couple of questions in this regard:
 - Do plugins get instantiated per package section? if thats the case the key prefix in aws-s3-storage can be utilized to achieve the goal
 - currently, when we are setting the store to aws-s3-storage, local storage seems to be automatically turned off. How does this happen architecturally? Is s3-plugin turning the local storage off? Or is this simply a bug?

**Comment by tetrohed** [comment]
moved to verdaccio/monorepo

https://github.com/verdaccio/monorepo/issues/298

**Comment by DanielRuf** [comment]
Just fyi, we can also transfer issues.

<img width="243" alt="Bildschirmfoto 2019-12-24 um 16 15 35" src="https://user-images.githubusercontent.com/827205/71417997-a252a180-2668-11ea-93fb-0298505dd2a5.png">
