### ISSUE TITLE
Kubernetes | How to use plugins?

### ISSUE THREAD

**Issue by ThaDaVos** [verdaccio/verdaccio#1609]
**Is your feature request related to a problem?**
Please describe a clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

I saw this issue: https://github.com/verdaccio/verdaccio/issues/532 and it doesn't solve the issue when running Verdaccio on Kubernetes really because you can't really prepare a volume with some folders as far as I know so I would suggest the following:

Add a new configMap option which can contain an array of strings, each string represents the name of a verdaccio plugin - maybe even use an env for this - on startup install these plugins, maybe in such a way that they can be cached using a volume so they don't need to be installed on the next boot/deploy only if there's an update

**Describe the solution you'd like**

Add a new configMap option which can contain an array of strings, each string represents the name of a verdaccio plugin - maybe even use an env for this - on startup install these plugins, maybe in such a way that they can be cached using a volume so they don't need to be installed on the next boot/deploy only if there's an update

**Describe alternatives you've considered**

Making my own Verdaccio image on our own private docker registery containing the plugins we need, only downside is, no automatic updates when Verdaccio releases a new image...

**Additional context**

**Comment by juanpicado** [comment]
Unfortunately I still not skilled on https://github.com/verdaccio/verdaccio/issues/532#issuecomment-360772778 kubernetes, I labeled the ticket, but I'm not sure whether you will get any quick answer here. We documented how to use it with Docker, that's all I know and I can answer.

**Comment by ThaDaVos** [comment]
My proposal actually hasn't anything to do with Kubernetes, if, you could pass a env variable which is a comma seperated list of package names, maybe Verdaccio could automatically install these on boot-up if they aren't found in the corresponding folder (this will make it way easier to add plugins), for example:

Env name is: VERDACCIO_PLUGINS
I would define it as follows
```bash
VERDACCIO_PLUGINS="verdaccio-plugin-a;verdaccio-plugin-b;verdaccio-plugin-c"
```

On bootup, Verdaccio checks this env, if set, parses it and goes on to check if the mentioned plugins are available, if not, verdaccio will for example call:

```bash
npm install -g {PLUGIN_NAME}
```

To install it globally and then load it

It's just an idea, I can always try to make a PR for if after I have dived into the codebase :D

**Comment by ThaDaVos** [comment]
Also, the `--prefix` argument can be used with the `-g` or `--global` option to install the package anywhere
https://stackoverflow.com/questions/14469515/how-to-npm-install-to-a-specified-directory
https://docs.npmjs.com/files/folders#more-information

**Comment by DanielRuf** [comment]
This sounds very interesting and I would like to see this as a new feature.

So do we first have to decide on the technical details or do you already have some solution in your mind?

Dynamic require / import would be a good idea.
Reminds me a bit of my very simple plugin solution at https://github.com/seppevs/migrate-mongo/pull/65/files and in a few other projects.

**Comment by ThaDaVos** [comment]
@DanielRuf  - I've got some idea's for it, mostly leveraging the current plugin loading functionality

**Comment by juanpicado** [comment]
Hi, there already few tickets related with improvements for plugins, feel free to contribute them, you can find them here https://github.com/verdaccio/verdaccio/issues/1690

Just small thought, I don't think so the job to install dependencies is up to this project, rather up to the owner of the environment, you need to ensure those libraries are installed, verdaccio relies on `require()`  thus *node require algorithm* is the one that decides where to look.  

I will close this since seems there is nothing else to discuss.
