### ISSUE TITLE
how to configure protocols and ciphers in https

### ISSUE THREAD

**Issue by max56-prog** [verdaccio/verdaccio#1610]
Hi
In the config.yaml do we have a syntax to use to enforce the protocols and ciphers to be used in https. ?
Thanks
Nathan

**Comment by juanpicado** [comment]
hi @max56-prog 

What ciphers means? Perhaps you can provide a bit more context.

**Comment by jachstet-sea** [comment]
A "cipher suite" is a term from cryptography and describes the parameters used for an encrypted communication.
In the context of HTTPS, it describes which algorithm (AES, ...), key lengths and MACs will be used. For example, TLS 1.3 introduced new algorithms that couldn't be used before.
For more details, see https://en.wikipedia.org/wiki/Cipher_suite

In the context of verdaccio it will depend on whether NodeJS API allows us to set these parameters, which version of NodeJS verdaccio is being run on and against which crypto library it has been linked.

**Comment by jachstet-sea** [comment]
Closest hit to answer the question: https://nodejs.org/api/tls.html#tls_modifying_the_default_tls_cipher_suite

**Comment by DanielRuf** [comment]
We use express under the hood which uses the default cipphersuite of NodeJS. Currently it is not possible to configure this.

Do you have to configure this as feature?

**Comment by DanielRuf** [comment]
> do we have a syntax to use to enforce the protocols and ciphers to be used in https.

Short answer: no (currently not)
