### ISSUE TITLE
npm login doesn't accept the email id as an username

### ISSUE THREAD

**Issue by sathishchandran97** [verdaccio/verdaccio#1627]
Hello all,
I have to use my email id as my user name. But npm login does not accept the email id as user name. 
can anyone help me out?

Thanks in advance :)

**Comment by juanpicado** [comment]
I guess .. the question should rather go to https://github.com/npm/cli

Anyway, according my knowledge, id should be a nickname with [a-z][A-Z] characters, email do not fit in such rule.

**Comment by DanielRuf** [comment]
Login for all registries is always username + password. The email is only additional metadata for a pubished package / release.
