### ISSUE TITLE
Bug: exact search phrase does not work

### ISSUE THREAD

**Issue by DanielRuf** [verdaccio/verdaccio#1632]
**Describe the bug**
When searching for `jquer` the search API correctly returns `jquery`. If we input `jquery` it returns an empty array and so the search suggestions are also empty in the UI.

**To Reproduce**
Search for `jquery` and `jquery`. See the responses in the network tab.

1. Go to verdaccio frontend
1. Input `jquer`
1. Check results
1. Input `jquery`
1. Check results

**Expected behavior**
A direct match should return the packages.

**Screenshots**

<img width="947" alt="Bildschirmfoto 2019-12-25 um 15 39 55" src="https://user-images.githubusercontent.com/827205/71447336-4ef65700-272d-11ea-8230-a8b50fd4c82c.png">

<img width="851" alt="Bildschirmfoto 2019-12-25 um 15 39 46" src="https://user-images.githubusercontent.com/827205/71447335-4d2c9380-272d-11ea-9c0a-ffd1136138c2.png">

**Comment by nair-sreerag** [comment]
This is an issue with the stemmer of the lunr package; on which the package - **lunr-mutable-indexes** (used in this project) is based. I published [jquery](https://github.com/jquery/jquery) and [commander](https://github.com/tj/commander.js) to my local verdaccio instance. The issue occured in both the cases (for the word **jquery** as mentioned above and for the words **commande** and **commander**). 
Here's the link to the issue in lunr package - [issue 38](https://github.com/olivernn/lunr.js/issues/38)
Here is how to ascertain what the package names stem to - 
1. Go to http://9ol.es/porter_js_demo.html
2. Clear the input box.
3. Enter the words **commander** and **jquery** one below the other.
4. Click on **Stem the above content**
5. Check the results. Try inputting those exact words in the verdaccio search bar. It returns the original package name.

**Comment by juanpicado** [comment]
Thanks for the feedback @nair-sreerag, you are right, but unfortunately the link you have provided has been detected as malware, please, remove that link or I'll be forced to remove your comment in the next 48 hours.

**Comment by nair-sreerag** [comment]
which link are you talking about?

**Comment by juanpicado** [comment]
The point 1. That's the unique problem. Sorry,  that's what my antivirus is suggesting. I have no issues with the other content which I fully agree.

**Comment by nair-sreerag** [comment]
Its weird. Anyways, can u try this one http://proiot.ru/jssnowball/? I'll remove this comment after u approve this website.

**Comment by juanpicado** [comment]
I don't see a reason to post more links ( I won't click on it), that's not need it. 

If you want to share content, the best way is sharing a repo where user can see what's behind he hood. And please, be kind and don't post more links.

**Comment by nair-sreerag** [comment]
Okies. I'll edit the comment in a different way so that the user can reproduce the issue. Thanks :)

Regards,
Sreerag Nair

**Comment by DanielRuf** [comment]
The link was detected as malware because it references / loads a bitcoin miner script from coin-hive in the source code but the website of bitcoin-hive was shut down / is offline.

You can see it with view-source:the-url

**Comment by DanielRuf** [comment]
I think the link to https://github.com/olivernn/lunr.js/issues/38 is sufficient, which also includes a possible solution.

No need to show different stemmer implementations.

**Comment by nair-sreerag** [comment]
Thanks for explaining what exactly the issue was with the link, @DanielRuf. I will refrain from posting links of anything other than github in the future. And also, I have edited my comment, @juanpicado .

**Comment by juanpicado** [comment]
Thanks @nair-sreerag , thanks for having such nice attitude 👏 and document properly your feedback .
