### ISSUE TITLE
feature: offline usage

### ISSUE THREAD

**Issue by frank-dspeed** [verdaccio/verdaccio#1634]
Will refactor code to allow offline usage.

**Comment by DanielRuf** [comment]
Hi @frank-dspeed,

can you explain in detail what this issue is about? Offline usage should already work when the cache of verdaccio is filled. Same applies to the clients (yarn and npm).

**Comment by juanpicado** [comment]
Related https://stackoverflow.com/a/59485999/308341

**Comment by frank-dspeed** [comment]
i found also others reporting that this don't works i want that it works thats why i will investigate,....

**Comment by DanielRuf** [comment]
Related:

https://github.com/verdaccio/verdaccio/issues/1566
https://github.com/verdaccio/verdaccio/issues/1633

**Comment by DanielRuf** [comment]
It worked before (in v3) using `cache: true`(which should be the default.

**Comment by nrydevopswatch** [comment]
IMHO this is a critical feature for Verdaccio and it is simply not usable for my work without it. Unfortunately Nexus and Artifactory are too expensive for most projects and I always prefer FOSS. If there is anything I can do to help with this please let me know. I spent several days trying to get Verdaccio to work in "Offline Mode" and was unsuccessful. 

Related: (the recent testing I did using https://www.npmjs.com/package/npm-offline-packager together with Verdaccio:

#1566

**Comment by frank-dspeed** [comment]
@nrydevopswatch at present i am reverse engineering the http calls via patched node_modules that do all kind of logging. it will take time to identify the places that are affacted but i found at last some already.

**Comment by DanielRuf** [comment]
We just may have to bisect this, only tarballs are not stored and db not filled.

The offline feature (uplink cache) should already work.

I saw in your screenshot that you have tarballs @juanpicado. Not sure why it does not work on my side. How can we bisect this the best way?

**Comment by DanielRuf** [comment]
`git checkout v4.x`, `git bisect start | bad | good` are the only things that we need here.

**Comment by nrydevopswatch** [comment]
It works fine if you have internet connection but when you disconnect completely from public internet there are several parts of the process that try to go out and contact npmjs public. This occurred no matter what settings I tried in the config. 

I was using Google Cloud instances Ubuntu and Centos (tried both) and I created a firewall rule to block all public (WAN) traffic but still allow communication between my Verdaccio server and the server I was running the Node sample web code on. I hope this is helpful; but the same effect can be achieved by disconnecting your system from the WAN locally.

**Comment by DanielRuf** [comment]
As already mentioned it is a regression bug on our side. It worked with previous releases.

Closing as duplicate. Let's discuss this in the other issues.

**Comment by DanielRuf** [comment]
Also related: https://github.com/verdaccio/verdaccio/issues/1157

I think there is still a bug.

**Comment by nrydevopswatch** [comment]
@DanielRuf Does this mean that "offline mode" won't be a working feature in Verdaccio anytime in the near future? If it is a bug, then can't the bug be fixed? I really appreciate you guys looking into this. Happy New Year! ;-)

**Comment by DanielRuf** [comment]
@nrydevopswatch verdaccio already works offline. There is just a reintroduced bug that prevents storing the tarballs in the latest version. We will check this. One issue is sufficient to track this.

Please let's keep the discussion at one place.

https://github.com/verdaccio/verdaccio/issues/1634#issuecomment-569422989

This issue is just marked and closed as duplicate.

**Comment by nrydevopswatch** [comment]
@DanielRuf Okay, sounds great! Thank you again and I will follow #1634 (comment)
