### ISSUE TITLE
What can I do to count the number of the package in my server

### ISSUE THREAD

**Issue by Tiny-Fendy** [verdaccio/verdaccio#1640]
Now I want to count the number of the package and the number of the developer in my server.
And I can't to login the server because it's not allowed in my company.
So what do I need to do.

**Comment by juanpicado** [comment]
> Now I want to count the number of the package and the number of the developer in my server.

There is no endpoint for that

> And I can't to login the server because it's not allowed in my company.

You would need to elaborate this, I don't get it.

**Comment by DanielRuf** [comment]
I guess he means that he has no direct access to the server (filesystem).

Theoreticalöy the package list should be at https://registry.verdaccio.org/-/all but we provide not much information there.

Regarding users: no endpoint for this (at least no users count).

**Comment by juanpicado** [comment]
> https://registry.verdaccio.org/-/all

True, but that endpoint will disappear soon or later. The new search endpoint should replace it #310 and not sure wether will have the same output.

**Comment by DanielRuf** [comment]
Ah ok. We should then also return a deprecation message on `/-/all` probably.

**Comment by juanpicado** [comment]
Yes :) when #310 is ready, at this point npmjs still support the old one.

**Comment by Tiny-Fendy** [comment]
Thanks for your help!!

**Comment by Tiny-Fendy** [comment]
Maybe I need to  develop this feature by myself.

**Comment by juanpicado** [comment]
You might create a custom endpoint with a middleware plugin to achieve what you need, read here https://verdaccio.org/docs/en/next/plugin-middleware
