### ISSUE TITLE
gyp ERR! find VS

### ISSUE THREAD

**Issue by sujitwarrier11** [verdaccio/verdaccio#1646]
Whenever I try to install i get this error. why is visual studio required for the latest version. 
You need to install the latest version of Visual Studio
 including the "Desktop development with C++" workload.
 For more information consult the documentation at:
 find VS https://github.com/nodejs/node-gyp#on-windows

**Comment by juanpicado** [comment]
Hi, I doubt this error is related with Verdaccio. I suggest you search on StackOverflow, most likely you need to install something in your computer as the message suggest.

I will close this issue since the solution is in your hands.

**Comment by DanielRuf** [comment]
Try `npm i -g windows-build-tools`. This should resolve your issue.
