### ISSUE TITLE
Incorrect npm/pnpm/yarn register info when viewed from a package

### ISSUE THREAD

**Issue by qtiki** [verdaccio/verdaccio#1648]
**Describe the bug**

Pressing the ( i ) button in the title bar shows the register info for npm, pnpm and yarn. The url here is correct. However if you click on a package to view the package details and then click the ( i ) button in the title bar you will see incorrect urls for the register info.

The incorrect url will contain the package's path, for example `https://your.npm.repo/-/web/detail/your-package` instead of `https://your.npm.repo/`

**To Reproduce**

1. Open Verdaccio Web UI
2. Click on any package
3. Click on the ( i ) button in the title
4. Observe incorrect urls

**Expected behavior**

The repository url should always point to the base url.

**Screenshots**

Screenshot of the correct Register Info viewed from the home screen:

![image](https://user-images.githubusercontent.com/752359/71984959-80dde200-3232-11ea-87b7-b58738e929f4.png)

Screenshot of the incorrect Register Info viewed from the package screen:

![image](https://user-images.githubusercontent.com/752359/71985157-9d7a1a00-3232-11ea-9877-b5cb1d5bbf4b.png)

**Comment by DanielRuf** [comment]
Hi @qtiki,

Please provide further details about your verdaccio version.

**Comment by DanielRuf** [comment]
Hi @qtiki,

Please provide further details about your verdaccio version and configuration.

**Comment by DanielRuf** [comment]
@juanpicado didn't we have some related issue or issue comment?

**Comment by juanpicado** [comment]
I think if is not fixed, there is an issue already.

**Comment by DanielRuf** [comment]
Can be reproduced at https://registry.verdaccio.org/-/web/detail/@juanpicado/registry_test

**Comment by DanielRuf** [comment]
getCLISetConfigRegistry

https://github.com/verdaccio/ui/blob/master/src/components/RegistryInfoContent/RegistryInfoContent.tsx#L24

https://github.com/verdaccio/ui/blob/master/src/utils/cli-utils.ts#L24

renderNpmTab

https://github.com/verdaccio/ui/blob/master/src/components/Header/HeaderInfoDialog.tsx#L15

https://github.com/verdaccio/ui/blob/master/src/components/Header/Header.tsx#L60

https://github.com/verdaccio/ui/blob/master/src/components/Header/Header.tsx#L4

https://github.com/verdaccio/ui/blob/master/src/utils/url.ts#L19

https://github.com/verdaccio/ui/commit/d955268c25e58db11622bb26dd8278a93ba08310

https://github.com/verdaccio/ui/pull/300

https://github.com/verdaccio/ui/pull/300#issuecomment-557917138

https://github.com/verdaccio/ui/pull/300#issuecomment-557919199

I meant this issue =)

**Comment by DanielRuf** [comment]
A `base` tag could solve all these issues with juggling paths.

**Comment by DanielRuf** [comment]
Or build it from the same details (host, port, prefix).

**Comment by DanielRuf** [comment]
https://github.com/verdaccio/ui/pull/300#issuecomment-557917138

<img width="566" alt="Bildschirmfoto 2020-01-08 um 21 13 38" src="https://user-images.githubusercontent.com/827205/72012229-dda1c280-325b-11ea-843c-212139f52dd3.png">

I will work on this.

**Comment by DanielRuf** [comment]
https://github.com/verdaccio/verdaccio/pull/1647/files

**Comment by DanielRuf** [comment]
In general https://github.com/verdaccio/ui/blob/ae73772a37121ac92e2bbeb8e805e6b64a43f2fa/tools/webpack.dev.config.babel.js#L40 is the problem in dev mode.

It should probably be `base: new URL('/', 'https://localhost:4872'),`.

**Comment by DanielRuf** [comment]
In production it should work with `const base = (0, _utils.combineBaseUrl)(protocol, host, url_prefix);` and the new `combineBaseUrl`.

**Comment by juanpicado** [comment]
refer https://github.com/verdaccio/ui/pull/413
