### ISSUE TITLE
Document how to install plugins

### ISSUE THREAD

**Issue by ir-fuel** [verdaccio/verdaccio#1677]
**Is your feature request related to a problem?**

I just started using Verdaccio on an AWS Amazon Linux 2 EC2 instance and I have no idea on how to install plugins.

I installed Verdaccio using `npm install -g verdaccio` and it runs fine, I can access the web interface.

Now I want to add the github oauth plugin but I have no idea on how to get this working. I tried

`npm install -g verdaccio-github-oauth-ui`

and modifying the config file for this plugin, but restarting Verdaccio only gives me:

```
Error: verdaccio-github-oauth-ui plugin not found. try "npm install verdaccio-github-oauth-ui"
```

I saw there is a plugins directory in the config file, but I have no idea how to install a plugin there, as running an `npm install` in that directory will just create a `node_modules` subdirectory containing the plugin and all its dependencies. (I tried this too btw and it also didn't work)

**Describe the solution you'd like**
I would like to see a few lines of documentation on how to install plugins, the same way the installation of Verdaccio itself is clearly explained. The only ones I find are about using Docker and extending the image to add plugins.

Thanks a lot!

**Comment by agar23** [comment]
There are a few guides on usage [here](https://verdaccio.org/docs/en/plugins#usage) the READMEs are also a good place to find usage information also. Please note `verdaccio-github-oauth-ui` is a community plugin they seem to have some good instructions on usage on the README [here](https://github.com/n4bb12/verdaccio-github-oauth-ui#verdaccio-config)

**Comment by ir-fuel** [comment]
Thanks for the quick reply. I already read all those docs, but I don't see what else I can do besides simply running `npm install -g verdaccio-github-oauth-ui` ?

Also unless I am mistaken there is zero documentation about using the plugin directory that's configured in the config file.

I am currently reading your source code to understand the way the loading works in order to see if I can understand why it doesn't find the plugin I installed.

This is my global `node_modules` directory:

```
[ec2-user@ip-172-31-27-65 node_modules]$ ls
npm  pm2  verdaccio  verdaccio-github-oauth-ui
```

**Comment by ir-fuel** [comment]
I just added some logging in the plugin loader code and these are the paths where it tries to load the plugin:

```
/home/ec2-user/.nvm/versions/node/v10.16.3/lib/node_modules/verdaccio/build/plugins/github-oauth-ui
/home/ec2-user/.nvm/versions/node/v10.16.3/lib/node_modules/verdaccio/build/lib/plugins/github-oauth-ui
/home/ec2-user/.nvm/versions/node/v10.16.3/lib/node_modules/verdaccio/build/lib/plugins/verdaccio-github-oauth-ui
/home/ec2-user/.nvm/versions/node/v10.16.3/lib/node_modules/verdaccio/build/lib/plugins/sinopia-github-oauth-ui
verdaccio-github-oauth-ui
sinopia-github-oauth-ui
github-oauth-ui
```

It only seems to check a directory inside the Verdaccio installation directory. 

So next I tried setting the global node_modules directory as plugin directory, in the config file.

This time it did seem to find the plugin, but it immediately bailed out with a dependency error (added some more logging)

```
/home/ec2-user/.nvm/versions/node/v10.16.3/lib/node_modules/verdaccio-github-oauth-ui
{ Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.16.3/lib/node_modules/verdaccio-github-oauth-ui/dist/server.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by ir-fuel** [comment]
Some more info:

manually doing `npm install lodash` inside the plugin's directory managed to fix the issue.

So that's an issue with the plugin itself, but that still doesn't explain why I need to add the global `node_modules` directory to my config file

**Comment by n4bb12** [comment]
The main issue is that you are installing things globally. Despite what the Verdaccio docs say, installing plugins globally does it work with npm with any plugin that is not shipped with verdaccio itself.

**Comment by n4bb12** [comment]
Your options are
- install things locally with a package.json
- use yarn

**Comment by ir-fuel** [comment]
So the docs are wrong? I need to go inside the `/home/ec2-user/.nvm/versions/node/v10.16.3/lib/node_modules/verdaccio/` folder and `npm install` the plugin there?

**Comment by juanpicado** [comment]
Here one good example https://github.com/barolab/verdaccio-minio/blob/master/example/Dockerfile#L10

**Comment by martin-paulus** [comment]
Actually, I was struggling with this as well. So I intended to create a PR for a docs update. Only your docs do not seem to be exposed on GItHub?

Here is what I came up with:

* switch into a suitable working dir
* create a path for the plugins volume: 
  `mkdir volume`
* start the current stable release of Verdaccio with the plugins path mounted: 
  `docker run --name verdaccio --volume $(pwd)/volume:/var/tmp/volume verdaccio/verdaccio:4`
* enter the running container as root user: 
  `docker exec -it -u root verdaccio /bin/sh`
* change owner of the plugins volume path to the application user: 
  `chown -R verdaccio /var/tmp/volume`
* switch to the application user: 
  `su -s /bin/sh - verdaccio`
* switch to the plugins volume path: 
  `cd /var/tmp/volume`
* install the plugin(s) you desire, in this case verdaccio-aws-s3-storage: 
  `npm install --global-style --no-bin-links --no-optional --registry https://registry.verdaccio.org verdaccio-aws-s3-storage@9.4.0`
* after successful plugin(s) install, stop the container (and remove any anonymous volumes: -v): 
  `docker rm -fv verdaccio`
* ensure your plugins configuration is added to docker.yaml (from: https://github.com/verdaccio/verdaccio/blob/master/conf/docker.yaml), in this case verdaccio-aws-s3-storage config: 
  ```
  store:
    aws-s3-storage:
      bucket: 'some-bucket'
      region: 'eu-central-1'
  ```
* start a clean Verdaccio container, while mounting your customized config file and plugins volume: 
  `docker run --name verdaccio --volume $(pwd)/docker.yaml:/verdaccio/conf/config.yaml:ro --volume $(pwd)/volume/node_modules:/verdaccio/plugins:ro verdaccio/verdaccio:4`

**Comment by diamondarts** [comment]
I got started with the docker compose instructions from [Using docker-compose](https://verdaccio.org/docs/en/docker#using-docker-compose), which worked well. I picked one [config.yaml](https://github.com/verdaccio/docker-examples/blob/master/docker-local-storage-volume/conf/config.yaml) (from [verdaccio / docker-examples](https://github.com/verdaccio/docker-examples)) by chance.

Then I wanted to add the active directory auth plugin and stumbled across **ir-fuel**'s problem.

My solution was

1.  Copy locally installed plugin(s) from `node_modules` to `plugins`
2. **Add the following line** in `config.yaml`:

       plugins: /verdaccio/plugins

(I suppose alternatively you may change `docker-compose.yml` to read `"./node_modules:/verdaccio/plugins"`.)

**Comment by tommcc** [comment]
Thanks to @martin-paulus for the key to success installing , which is the use of the `--global-style` switch with npm. I was able to shorten the procedure with help from @diamondarts and tips from the docs:

1. In an arbitrary folder on the docker host:
    ```bash
    npm install --global-style --no-bin-links --no-optional verdaccio-acl-plugin
    ```
    This will produce a `package-lock.json` and `node_modules/` folder. Critically, the `global-style` option ensures that the plugin's dependencies are nested instead of flattened as siblings, which won't work.
2. Set ownership to what will be the `verdaccio` user's ID inside the container and `no-group` ID:
    ```bash
    chown -R 10001:65533 ./node_modules/
    ```
3. Mount the docker container's `plugins` volume to the `node_modules` folder, e.g.:
    ```
    ./node_modules:/verdaccio/plugins
    ```

**Comment by johanhelsing-attensi** [comment]
Thanks @tommcc !

I managed to adapt your solution so I could use it in a Dockerfile instead

This is what I currently do

```Dockerfile
FROM verdaccio/verdaccio
USER root
ENV NODE_ENV=production
RUN npm install -g --no-bin-links --prefix /tmp/verdaccio-auth-memory-install verdaccio-auth-memory \
    && mv /tmp/verdaccio-auth-memory-install/lib/node_modules/verdaccio-auth-memory /verdaccio/plugins \
    && chown -R $VERDACCIO_USER_UID:root /verdaccio/plugins \
    && rm -rf /tmp/verdaccio-auth-memory-install
USER verdaccio
```

It's pretty ugly, but I think I prefer it over having to deal with setting up a plugin volume

**Comment by stephen-dahl** [comment]
adapting your adaption into a multistage build 😉 

```
FROM verdaccio/verdaccio:5 as builder
USER root
ENV NODE_ENV=production

RUN apk add alpine-sdk python
RUN npm i --global-style verdaccio-bitbucket

FROM verdaccio/verdaccio:5
COPY config.yml /verdaccio/conf/config.yml
COPY --from=builder --chown=$VERDACCIO_USER_UID:root /opt/verdaccio/node_modules/verdaccio-bitbucket /verdaccio/plugins/verdaccio-bitbucket
```

**Comment by juanpicado** [comment]
Thanks guys for your comments. I think  would looks even better in the website, easy to find and SEO friendly. PR is welcome 🙏

**Comment by pjlsergeant** [comment]
To anyone else scratching their head, while @stephen-dahl's solution works great, note that you may also need to have explicitly set `plugins: /verdaccio/plugins/` in your config file.

**Comment by stephen-dahl** [comment]
I might pr docs for this next week.

**Comment by juanpicado** [comment]
Docs were moved to this repository so you all are aware 
https://github.com/verdaccio/verdaccio/tree/master/docs

**Comment by dlewis-irse** [comment]
This is helpful - are there any guides to help with actual plug-in development that includes the ability to set breakpoints?

I need to build an OKTA Authentication plugin as the one listed in the docs (https://github.com/hogarthww-labs/verdaccio-okta-auth) is unfinished and does not work

**Comment by jrj2211** [comment]
I've spent quite a bit of today trying to figure out how to actually get plugins to load when running verdaccio in docker compose. Figured I'd post my solution here since as it took piece mealing a bunch of info to finally get it to work.

For this, the simplest way seems to be extending the verdaccio docker image with your own. Remove `image: verdaccion/verdaccio:latest` from the docker-compose and add in `build: ./`. Place a Dockerfile in the same folder and use yarn to install the plugin.

```
# /var/docker/verdaccio/docker-compose.yml
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1
  azure-ad-login:
    tenant: "FILL THIS OUT"
    client_id: "FILL THIS OUT"
    client_secret: "FILL THIS OUT"
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@*/*":
    access: $all
    publish: $authenticated
    proxy: npmjs
  "**":
    proxy: npmjs
log: { type: stdout, format: pretty, level: http }
```

```
# /var/docker/verdaccio/Dockerfile
FROM verdaccio/verdaccio:latest
USER root
RUN yarn add verdaccio-azure-ad-login
USER verdaccio
```

I typically use NPM but I found that doing `RUN npm install verdaccio-azure-ad-login` would still give me the error that the plugin was not found. Not sure what the difference is between `yarn add` and `npm install` but this is what made it work for me.

**Comment by juanpicado** [comment]
I will tackle this topic on this month:

Starting with 
- Refactor and upgrade https://github.com/verdaccio/generator-verdaccio-plugin
- Improve docs 
- Add API docs
- Document using Docker and plugins 

So all your knowledge and experience is vital for me, please if you haven't share example or open source plugins, techniques and so on please share here, I would need your help.

**Comment by juanpicado** [comment]
Thanks folks for all your examples, I'm creating some docs upgrades + docker examples ready to use here

https://github.com/verdaccio/verdaccio/pull/3217

please give me your feedback 🙏🏼 I will try to add more and then update the docs website.

**Comment by juanpicado** [comment]
Ok I consider this done.

- [Plugin generator has been improved](https://github.com/verdaccio/generator-verdaccio-plugin/releases/tag/v4.0.0)
- [Examples how to install plugins with Docker](https://github.com/verdaccio/verdaccio/tree/master/docker-examples/v5/plugins)
- [How to debug Docker](https://github.com/verdaccio/verdaccio/wiki/Debugging-Verdaccio#with-docker)

**Comment by ganeshsacharya** [comment]
> For that and other things, I think verdaccio shouldn't be planned to be installed globally. Why not use it as any other package? Seems simpler, more straight-forward, easier to keep track in git, see plugins installed, configs used, etc. Add plugin package to your project and it should be done.
> 
> (I've managed to do that locally in my company after some days expent on it - which was harder to do with pm2! If anyone finds helpful I've posted in https://stackoverflow.com/a/72522554/3645375)

Did you manage to get the azure login working? for me it always keep saying below

`npm ERR! 409 Conflict - PUT http://localhost:8001/-/user/org.couchdb.user:ganesh.abcd..workingdomain.com - bad username/password, access denied`

any idea what i might look at?

**Comment by brysoncatboost** [comment]
Check this clarification



https://nodejser.space/questions/what-is-the-process-for-connecting-to-my-verdaccio-service-running-as-a-docker-container-from-a-different-docker-container
