### ISSUE TITLE
Error publishing first package

### ISSUE THREAD

**Issue by rmgmediaval** [verdaccio/verdaccio#1683]
I was wondering if anybody can help me with this error? I am still learning the ropes.

`[centos@verdaccio tests]$ npm publish --registry https://verdaccio.uat-xxxxxxx.com:443
npm notice 
npm notice 📦  @MyCompany/packages@0.1.0
npm notice === Tarball Contents === 
npm notice 62B package.json
npm notice === Tarball Details === 
npm notice name:          @MyCompany/packages                     
npm notice version:       0.1.0                                   
npm notice package size:  154 B                                   
npm notice unpacked size: 62 B                                    
npm notice shasum:        56eb3093555bb16af8a474a04d3ae81e94aa9b41
npm notice integrity:     sha512-Elq9YdSMIkhe1[...]txOHVQ7+fUbvQ==
npm notice total files:   1                                       
npm notice 
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://verdaccio.uat-xxxxxxx.com:443/@MyCompany%2fpackages - user val is not allowed to publish package @MyCompany/packages
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/centos/.npm/_logs/2020-01-24T15_30_09_871Z-debug.log
`

Contents of package.json
`{
    "name": "@MyCompany/packages",
    "version": "0.1.0"
}
`

This is my config.yaml
`packages:
  '*':
    allow_access: all
    allow_publish: all
    proxy: npmjs
`
Here is the log:
`0 info it worked if it ends with ok
1 verbose cli [ '/opt/nvm/versions/node/v10.18.0/bin/node',
1 verbose cli   '/opt/nvm/versions/node/v10.18.0/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--registry',
1 verbose cli   'https://verdaccio.uat-xxxxxxx.com:443' ]
2 info using npm@6.13.4
3 info using node@v10.18.0
4 verbose npm-session 758cd095be39486f
5 verbose publish [ '.' ]
6 info lifecycle @MyCompany/packages@0.1.0~prepublish: @MyCompany/packages@0.1.0
7 info lifecycle @MyCompany/packages@0.1.0~prepare: @MyCompany/packages@0.1.0
8 info lifecycle @MyCompany/packages@0.1.0~prepublishOnly: @MyCompany/packages@0.1.0
9 info lifecycle @MyCompany/packages@0.1.0~prepack: @MyCompany/packages@0.1.0
10 info lifecycle @MyCompany/packages@0.1.0~postpack: @MyCompany/packages@0.1.0
11 notice
12 notice 📦  @MyCompany/packages@0.1.0
13 notice === Tarball Contents ===
14 notice 62B package.json
15 notice === Tarball Details ===
16 notice name:          @MyCompany/packages
16 notice version:       0.1.0
16 notice package size:  154 B
16 notice unpacked size: 62 B
16 notice shasum:        56eb3093555bb16af8a474a04d3ae81e94aa9b41
16 notice integrity:     sha512-Elq9YdSMIkhe1[...]txOHVQ7+fUbvQ==
16 notice total files:   1
17 notice
18 http fetch PUT 403 https://verdaccio.uat-xxxxxxx.com:443/@MyCompany%2fpackages 35ms
19 verbose stack Error: 403 Forbidden - PUT https://verdaccio.uat-xxxxxxx.com:443/@MyCompany%2fpackages - user val is not allowed to publish package @MyCompany/packages
19 verbose stack     at res.buffer.catch.then.body (/opt/nvm/versions/node/v10.18.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
19 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
20 verbose statusCode 403
21 verbose pkgid @MyCompany/packages@0.1.0
22 verbose cwd /home/centos/packages/tests
23 verbose Linux 3.10.0-957.1.3.el7.x86_64
24 verbose argv "/opt/nvm/versions/node/v10.18.0/bin/node" "/opt/nvm/versions/node/v10.18.0/bin/npm" "publish" "--registry" "https://verdaccio.uat-xxxxxxx.com:443"
25 verbose node v10.18.0
26 verbose npm  v6.13.4
27 error code E403
28 error 403 403 Forbidden - PUT https://verdaccio.uat-xxxxxxx.com:443/@MyCompany%2fpackages - user val is not allowed to publish package @MyCompany/packages
29 error 403 In most cases, you or one of your dependencies are requesting
29 error 403 a package version that is forbidden by your security policy.
30 verbose exit [ 1, true ]`

Thanks in advance.

**Comment by rmgmediaval** [comment]
Looking further, it looks like the error happens whenever I use `@mycompany` in the package.json:
`"name": "@mycompany/myfirstpackage",'
If I use ` "name": "mycompany-myfirstpackage",` then the error does not come up.

Does anybody know how I can use `@mycompany` and avoid this error?

**Comment by juanpicado** [comment]
Use `$all`.  `all` is taken as an username. You can read here more 
https://verdaccio.org/docs/en/authentification#the-meaning-of-all-and-anonymous
