### ISSUE TITLE
Deprecation Warning: crypto.createDecipher is deprecated.

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#1689]
**Is your feature request related to a problem?**

Verdaccio uses `crypto.createDecipher(algorithm, password[, options])` for encrypt and decrypt the token in the legacy mode (without JWT). This method is deprecated and future Node.js versions might be removed.

https://nodejs.org/api/crypto.html#crypto_crypto_createdecipher_algorithm_password_options

**Describe the solution you'd like**

We must switch to `crypto.createDecipheriv(algorithm, key, iv[, options])` and there is no other way to solve this. In legacy mode tokens do not expire (since Sinopia) and applying this new method might invalidate all tokens, this is a breaking change.

https://nodejs.org/api/crypto.html#crypto_crypto_createdecipheriv_algorithm_key_iv_options

**Comment by DanielRuf** [comment]
> We must switch to `crypto.createDecipheriv(algorithm, key, iv[, options])` and there is no other way to solve this. In legacy mode tokens do not expire (since Sinopia) and applying this new method might invalidate all tokens, this is a breaking change.

In which way is this breaking when both return the same result?

**Comment by DanielRuf** [comment]
Also we can check the Node version or if the method exists (should be the case as it is very old).

crypto.createDecipheriv(algorithm, key, iv[, options])

Version | Changes
-- | --
v11.6.0 | The key argument can now be a KeyObject.
v11.2.0 | The cipher chacha20-poly1305 is now supported.
v10.10.0 | Ciphers in OCB mode are now supported.
v10.2.0 | The authTagLength option can now be used to restrict accepted GCM authentication tag lengths.
v9.9.0 | The iv parameter may now be null for ciphers which do not need an initialization vector.
v0.1.94 | Added in: v0.1.94

**Comment by DanielRuf** [comment]
`iv` is optional / can be null:

> If the cipher does not need an initialization vector, iv may be null.

**Comment by juanpicado** [comment]
Thanks for dive into this @DanielRuf , then if can be easily solved if someone is willing to take it I think can easily prove via unit test the tokens won't be invalidated and shipped even before v5.

**Comment by DanielRuf** [comment]
I am currently checking something. It seems the ìv`can not be null so the docs are not correct.

**Comment by DanielRuf** [comment]
We might be able to use this migration script in our code as it derives the iv and key from the secret:

https://gist.github.com/bnoordhuis/2de2766d3d3a47ebe41aaaec7e8b14df

**Comment by juanpicado** [comment]
Thanks :) I will give it a try !

**Comment by juanpicado** [comment]
@DanielRuf I'm about to merge this and I'd like to know your opinion about the new token signature and the algorithm selected https://github.com/verdaccio/verdaccio/pull/1953/files#diff-344122784181466000b2f2b662e5ba89R13
