### ISSUE TITLE
Improve plugin system

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#169]
#### My reason:

Currently, the plugin system is tight to [authentication plugins](https://github.com/verdaccio/verdaccio/wiki/Plugins) that avoid extending different parts of the application and use different *storages* #103 to allow scale the app.

#### Proposal:

* Plugin [helper generator](https://github.com/verdaccio/generator-verdaccio-plugin) based on *Yeoman* that build the basic scald-folding for different sort of plugins as (storage, auth, middleware etc...) eg: `yo verdaccio-plugin:{name}`. 
  * Plugin names might be something as:  *verdaccio-{name}*
     * Auth: *verdaccio-gitlab*
     * Storage: *verdaccio-memory* (https://github.com/verdaccio/verdaccio-memory)
     * Middleware: *verdaccio-middleware-{name}* Fixed on #394

* [x]  ~~Upgrade `Storage.js` and `express layer` to allow plugins~~
* [x] Local file system would be a *default* and by default plugin 
* [x]  Default  authentication `htpasswd` will remains using them as default one #192

#### Caveats:

* It would be a breaking change 

The current functionality will remain as it is but allowing the user to extend basic application parts.

**Comment by Meeeeow** [comment]
We should also improve source code commend and document(I will write some), it's hard to find out how it works without any comment.

And... Have you done ES6 refactoring? what can i do?

**Comment by juanpicado** [comment]
I was working on ES6 partial migration, due Node 4 only supports 58%. I'll merge tomorrow #159 all my progress.

**Comment by Meeeeow** [comment]
OKey, If i can do something with syntax upgrade, i will open a new issue with checkbox let you know what we have done and what i'm doing

**Comment by juanpicado** [comment]
Awesome that would be great 🤜🏻 🤛🏻

**Comment by juanpicado** [comment]
This feature is partially present on version `3.x`

**Comment by juanpicado** [comment]
http://www.verdaccio.org/docs/en/dev-plugins.html
