### ISSUE TITLE
Is there a way to find all packages dependent on a given package?

### ISSUE THREAD

**Issue by Vijay-Nirmal** [verdaccio/verdaccio#1692]
I want to find all the packages dependent on a given package. Is there an API for it?

**Comment by juanpicado** [comment]
Hi 👋 

There is no such thing at Verdaccio.

**Comment by Vijay-Nirmal** [comment]
😥

So my only option is to find all packages ( /-/all ) and process the JSON to find the dependent packages?

**Comment by juanpicado** [comment]
Yes,  GitHub or npmjs achieve that with huge infrastructure, so, you would need to figure it out or build something on top of  Verdaccio.

I'm closing this, but feel free to post your thoughts.
