### ISSUE TITLE
UnhandledPromiseRejectionWarning: RPError: JWT not active yet, now 1580794298, nbf 1580794302

### ISSUE THREAD

**Issue by Zubair-Ashraf** [verdaccio/verdaccio#1693]
Use NodeJs version 12.14.0 and npm version 6.13.4

![Error](https://user-images.githubusercontent.com/57169065/73718564-b0531200-473e-11ea-9019-572548a6ea9b.PNG)

**Comment by jachstet-sea** [comment]
Could you please give some more information?
What did you do, what did you expect to happen, what happened?
Are multiple systems (server, client) involved? Are their clocks in sync?

**Comment by DanielRuf** [comment]
Hi @Zubair-Ashraf,

please use the issue template: https://github.com/verdaccio/verdaccio/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by Zubair-Ashraf** [comment]
> Could you please give some more information?
> What did you do, what did you expect to happen, what happened?
> Are multiple systems (server, client) involved? Are their clocks in sync?

I am using xero accounting app https://www.xero.com/us/  for generating invoices so for hitting the invoices API i need access_token, refresh_token and xero_tenant_id and so for getting these things xero provides a sample project that is posted in this repo https://github.com/XeroAPI/xero-node.  I just cloned the repo and started the server. My app connected successfully with xero but after that when navigates to "/callback", it throws an error which says "UnhandledPromiseRejectionWarning: RPError: JWT not active yet, now 1580794298, nbf 1580794302"

invoices api enpoints is: https://developer.xero.com/documentation/api/invoices

**Comment by juanpicado** [comment]
@Zubair-Ashraf perhaps you should try with more orthodox way rather than clone the repo, then you play under your own rules. So I'd suggest use either a released npm version or docker and fill the template appropriately. An specific environment leads you to specific errors we don't see and thus cannot help.

**Comment by jachstet-sea** [comment]
> I am using xero accounting app https://www.xero.com/us/ for generating invoices so for hitting the invoices API i need access_token, refresh_token and xero_tenant_id and so for getting these things xero provides a sample project that is posted in this repo https://github.com/XeroAPI/xero-node. I just cloned the repo and started the server. My app connected successfully with xero but after that when navigates to "/callback", it throws an error which says "UnhandledPromiseRejectionWarning: RPError: JWT not active yet, now 1580794298, nbf 1580794302"
> 
> invoices api enpoints is: https://developer.xero.com/documentation/api/invoices

I don't understand how verdaccio is related to all this. Verdaccio is a NPM server/registry.
If you took an example that uses a specific's company/project's API and that example returns an error, this is nothing verdaccio is responsible for.

**Comment by juanpicado** [comment]
I'm closing this, too old, please if the error persist don't hesitate to comment and provide more information 👍
