### ISSUE TITLE
`npm owner add` support

### ISSUE THREAD

**Issue by aokhotin** [verdaccio/verdaccio#1695]
Hi,
As I see in #1527 `npm owner add` does not supported. 
We are really interested in this feature and ready to make a pull request. Did you have any ideas or suggestions about this feature implementation? We are ready to discuss the feature request.

We have a lot of internal packages supported by different teams of our company, and we need to forbid publishing of non-owned packages.

**Comment by juanpicado** [comment]
Feel free to share your thoughts, I haven’t seen before any need (if it were possible according the vision of this project ) to achieve such support. Again, feel free to describe your proposal so can be discussed.
