### ISSUE TITLE
how to develop a plugin in development mode?

### ISSUE THREAD

**Issue by favoyang** [verdaccio/verdaccio#1696]
I wonder what's the proper way to develop a plugin. Developing for verdaccio main repository is simple, just run `yarn dev:start -c config-file`. But when it comes to a plugin in the monorepo (say changed types and a plugin at the same time). I didn't find a good way to develop. I ended up with writing a helper script to build and bundle the plugins into tarballs, then install them into my verdaccio checkout (which makes the checkout dirty) , quite a painful process. Any tips to share?

**Comment by juanpicado** [comment]
Did you consider `yarn link`?

**Comment by favoyang** [comment]
Looks promising. Didn't know this tip before. Probably worth to update wiki of [plugins development](https://github.com/verdaccio/verdaccio/wiki/Plugin-Development), which is empty so far.

Thanks for help.

Issue closed.

**Comment by juanpicado** [comment]
I will mention it as side note, thanks 🙏
