### ISSUE TITLE
GET /-/all does not have Content-Type in the response header

### ISSUE THREAD

**Issue by fliperamma** [verdaccio/verdaccio#1697]
**Describe the bug**
Requesting `/-/all` returns a valid JSON but the response header is missing a `Content-Type` `application/json; charset=utf-8`

**To Reproduce**
- Make a request to Verdaccio `GET /-/all`

**Expected behavior**
- `Content-Type` `application/json; charset=utf-8` in the response header

**Screenshots**
![Screenshot 2020-02-07 at 10 32 47](https://user-images.githubusercontent.com/2085490/74017856-3bc5e080-4995-11ea-9616-853be9d2acb8.png)

**config.yaml**
Using default provided one, just added `listen: 0.0.0.0:4873`

**Environment information**
Environment Info:

  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (1) x64 Intel(R) Xeon(R) CPU @ 2.00GHz
  Binaries:
    Node: 12.14.1 - /usr/bin/node
    npm: 6.13.4 - /usr/bin/npm
  npmGlobalPackages:
    verdaccio: 4.4.2

**Comment by soraryu** [comment]
For reference, note that this became an issue when Unity3D made their package manager requests more strict: https://forum.unity.com/threads/scoped-registry-packages-not-displayed-in-2019-3-0f6.818358/#post-5476020

Unity is in the process of loosening the requirements again to fix it but it would still be better if Verdaccio sent the right headers.

**Comment by fliperamma** [comment]
> For reference, note that this became an issue when Unity3D made their package manager requests more strict: https://forum.unity.com/threads/scoped-registry-packages-not-displayed-in-2019-3-0f6.818358/#post-5476020
> 
> Unity is in the process of loosening the requirements again to fix it but it would still be better if Verdaccio sent the right headers.
 
We solved this by rewriting the header (adding the `Content-Type` manually) in our proxy.

**Comment by juanpicado** [comment]
@soraryu I agree, I think seems to have an easy fix. Anyone up to PR this?
