### ISSUE TITLE
Cache `no such package available` responses

### ISSUE THREAD

**Issue by velut** [verdaccio/verdaccio#1707]
**Is your feature request related to a problem?**

I noticed that Verdaccio queries the upstream registry for non-existing packages each time they are accessed.

For example, accessing `http://localhost:4873/not-a-package` two times results in the following behaviour:

```
 http --> 404, req: 'GET https://registry.npmjs.org/not-a-package' (streaming)
 http --> 404, req: 'GET https://registry.npmjs.org/not-a-package', bytes: 0/21
 http <-- 404, user: null(127.0.0.1), req: 'GET /not-a-package', error: no such package available
 http <-- 404, user: null(127.0.0.1), req: 'GET /not-a-package', error: no such package available
 http --> 404, req: 'GET https://registry.npmjs.org/not-a-package' (streaming)
 http --> 404, req: 'GET https://registry.npmjs.org/not-a-package', bytes: 0/21
 http <-- 404, user: null(127.0.0.1), req: 'GET /not-a-package', error: no such package available
 http <-- 404, user: null(127.0.0.1), req: 'GET /not-a-package', error: no such package available
```

**Describe the solution you'd like**

Verdaccio should be able to cache `no such package available` responses up to a specified `maxage`, thus reducing queries to the upstream registry.

Thank you for your time.

**Comment by juanpicado** [comment]
Verdaccio saves the last access time into the metadata, if the package is 404, there is no cache possible.
