### ISSUE TITLE
NPM Token doesn't list created tokens

### ISSUE THREAD

**Issue by kave** [verdaccio/verdaccio#1715]
**Describe the bug**
This feature doesn't work as documented when you create a token 

**To Reproduce**
enable tokens 
```
experiments:
  # support for npm token command
  token: true
```
`npm token create --registry http://localhost:4873/` 
returns this error
```
npm ERR! code E500
npm ERR! 500 Internal Server Error - POST http://localhost:4873/-/npm/v1/tokens - [saveToken] method not implemented
```
but if you look at the logs it did create one, but now you cannot list it
`npm token --registry http://localhost:4873/`
Error
```
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET http://localhost:4873/-/npm/v1/tokens - [readTokens] method not implemented
```

**Expected behavior**
Should list created tokens according to https://github.com/verdaccio/verdaccio/pull/1427

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
experiments:
  # support for npm token command
  token: true
```
**Additional context**

**Comment by juanpicado** [comment]
Well, message is quite clear.  Your storage does not handle tokens. I don't see many details in the ticket, so I think the error is on your side.

```
npm ERR! 500 Internal Server Error - POST http://localhost:4873/-/npm/v1/tokens - [saveToken] method not implemented
```
