### ISSUE TITLE
How to use custom authentication plugin in config.yaml file 

### ISSUE THREAD

**Issue by Abishake968** [verdaccio/verdaccio#1718]
I created a custom authentication plugin using below docuement. How to use this in config.yaml file.
https://verdaccio.org/docs/en/plugin-auth

**Comment by juanpicado** [comment]
For a custom plugin the config looks like:

Let's imagine your plugin package is named `verdaccio-awesome-auth`, then:

```
auth:
  awesome-auth:
    foo: bar
    bar: foo
```

Where `foo` is a custom properties and the naming (at least until Verdaccio 4) you need to remove the sufix `verdaccio-` and then should be enabled.

**Comment by Abishake968** [comment]
But i found this error 
![image](https://user-images.githubusercontent.com/36999537/75011577-faa9f200-54a5-11ea-931e-151227bfb12b.png)

Conifg file auth section:
```
auth:
  authplugin:
       url: string
```
