### ISSUE TITLE
Can I restrict adduser access?

### ISSUE THREAD

**Issue by riggerthegeek** [verdaccio/verdaccio#172]
I'm trying to restrict `npm adduser` access. I want to put this on a publicly available webserver (we have devs in multiple locations), but prevent unauthorised people from adding themselves onto the system.

Is there a way of doing this?

**Comment by jollycic** [comment]
I am afraid the answer is no, as the endpoint for `npm adduser` is registering any new user by default, if I read the [code](https://github.com/verdaccio/verdaccio/blob/472e8e94b00a5c58e61f49dd6535f2c5784a98a9/lib/index-api.js#L207) correctly. 

A possible workaround for now could be to keep your server local to your LAN and give the devs a VPN access.

**Comment by riggerthegeek** [comment]
If I were to come up with a proposition of adding this, would this be something people would like to be added?

**Comment by jachstet-sea** [comment]
In the config `full.yaml`, there's an option that has "to disable registration" as description: https://github.com/verdaccio/verdaccio/blob/master/conf/full.yaml#L31. Did you try that?

**Comment by riggerthegeek** [comment]
Aaaaaaah, that's perfect. Thanks @jachstet-sea
