### ISSUE TITLE
Hide pnpm instructions on web interface

### ISSUE THREAD

**Issue by mwgamble** [verdaccio/verdaccio#1720]
**Is your feature request related to a problem?**
We don't use pnpm at all in my office. I worry that people may get confused by what `pnpm` even is, especially since it's always prioritised over `yarn` which we do use.

**Describe the solution you'd like**
Provide the ability to choose which package managers show up in the web interface. The ordering isn't important to me.

**Describe alternatives you've considered**
I couldn't find any reference to any existing config setting that would make this possible.

**Comment by juanpicado** [comment]
There is a similar request, the idea in Verdaccio 5 is able to configure the UI and hide features. I added to the plan https://github.com/verdaccio/verdaccio/issues/1690 since I also want to hide many things by demand.

**Comment by juanpicado** [comment]
cc: @priscilawebdev

**Comment by amitgilad3** [comment]
Can we unpin this issue?? @juanpicado
