### ISSUE TITLE
3.8 update 4.4.4, the url_prefix is not work.

### ISSUE THREAD

**Issue by PolanZ** [verdaccio/verdaccio#1722]
**Describe the bug**
when update verdaccio, 
set the `url_prefix: http://domain/npm` is not work. **but in 3.8 is usable.**

the error:
unfound the assets. like:
`http://domain/-/static/main.dd59eb46bf53c7374cce.js` , the `npm` prefix is gone.

if when use IP to visit, return the error:
`Unsafe attempt to load URL <URL> from frame with URL <URL>. Domains, protocols and ports must match.`
`Unsafe attempt to load URL http://domain/npm/-/static/b1e0d4d4ee23474aee6616f444fc7aa9.svg from frame with URL http://ip:4873/. Domains, protocols and ports must match.`
`Refused to connect to 'http://www.southsmart.com/npm/-/verdaccio/packages' because it violates the following Content Security Policy directive: "connect-src 'self'".`
`Refused to connect to 'http://www.southsmart.com/npm/-/verdaccio/packages' because it violates the document's Content Security Policy.
`

**Expected behavior**

I found 3.8+ is not work.... 

**Screenshots**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
listen:
  - 0.0.0.0:4873
 
# http_proxy: http://domain/

url_prefix: 'http://domain/npm/'
```

**Environment information**
verdaccio 4.4.4

**Comment by juanpicado** [comment]
Dupe, please follow up here https://github.com/verdaccio/verdaccio/issues/1722
