### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [verdaccio/verdaccio#1724]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/verdaccio/verdaccio)](https://www.tickgit.com/browse?repo=github.com/verdaccio/verdaccio)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/verdaccio/verdaccio)](https://www.tickgit.com/browse?repo=github.com/verdaccio/verdaccio)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit`)

**Comment by juanpicado** [comment]
Haha this is so cool 😎 

![image](https://user-images.githubusercontent.com/558752/75454913-81634100-5976-11ea-807e-ebd73c623070.jpeg)

**Comment by juanpicado** [comment]
Haha this is so cool 😎 

![image](https://user-images.githubusercontent.com/558752/75454913-81634100-5976-11ea-807e-ebd73c623070.jpeg)

**Comment by patrickdevivo** [comment]
You never know what it will find!

**Comment by juanpicado** [comment]
@verdaccio/core-team thoughts?

**Comment by anikethsaha** [comment]
+1 for this.
