### ISSUE TITLE
Verdaccio as an internal npm registry for package stability

### ISSUE THREAD

**Issue by tomknappramos** [verdaccio/verdaccio#1727]
**Use-Case:**
I am trying to implement an internal npm registry in order to achieve,
- Package stability _(for safety in case the public npm registry package goes down)_
- Limit packages _(to only packages/versions which we internally approve)_
- Distributing our internal packages/modules amongst our team

**Idea (what I tried):**
My idea was to use Verdaccio as so:
- Set Verdaccio config to uplink to the public npm registry
- _Start Verdaccio server_
- Install whatever packages/versions we want using "npm install ..."
- _Turn off Verdaccio server_
- _(Get our code audited)_
- Update Verdaccio config to NOT use an uplink
- _Start Verdaccio server (for good)_
- Set all of our projects to use our Verdaccio server as the registry
- _(When we re-audit, we won't need to look through node_modules again because they would be untouched)_ 

**Problem(s):**
I thought my use-case seemed reasonable for Verdaccio, but I found that there is a "max-age" after which time, the Verdaccio server tries to grab a fresh versions of packages from the uplink?? Is that true? What if there is no uplink configured? If so, then that functionality is somewhat opposite of my desired goal of "preserving 'safe' snapshots" of npm modules "forever".

**Solution(s):**
I was wondering if there are ways to use Verdaccio in a way that naturally fits the my use-case. Including perhaps,
- Allowing packages/versions to "never be grabbed again" once they are in storage?
- Allowing a max-age of "infinite"?
- Indication of which packages are new when adding to the registry (nice-to-have).
- Etc.
  
**PS:**
Sorry if this has already been answered somewhere else... The closest thing I could find was this https://github.com/verdaccio/verdaccio/issues/119. And, @cmdelatorre's solution was to use a maxage of 10 years... Which seemed a bit hacky to me... 

Also, perhaps, if Verdaccio isn't meant for this use-case, then could you guys possibly suggest alternatives that you might know of?

Lastly, I just want to say Verdaccio seems like a very useful tool! I'll definitely donate if I end up using it! 😃 

Thanks!

**Comment by juanpicado** [comment]
hi @tomknappramos 

> Problem(s):
I thought my use-case seemed reasonable for Verdaccio, but I found that there is a "max-age" after which time, the Verdaccio server tries to grab a fresh versions of packages from the uplink?? Is that true? What if there is no uplink configured? If so, then that functionality is somewhat opposite of my desired goal of "preserving 'safe' snapshots" of npm modules "forever".

I'm not really clear what exactly have you tried out, or your thoughts are just theoretical? 

Verdaccio can work in offline mode serving what's in only in the cache, there are few days to achieve this, but you need to touch the config file.  Your use case is double, unless I am getting it wrong.

**Comment by tomknappramos** [comment]
Hi @juanpicado, 

Thanks for getting back!

The procedure in the "Idea:" section is what I tried out. I've updated my question to reflect that. And, yes it did require touching the config file. To test it, I disabled the uplink (by commenting it out), and did "npm i" on my project, and it worked great. (I even turned off my internet connection and "npm i" still worked, which was also great! 😃).
```yaml
# config
...
packages:
  ...
    # proxy: npmjs
```

I think, when the uplink is off (I'm assuming that is what "Offline Mode" is??), then my use-case seems to be totally fine. But, my area of concern is **what happens when we reactivate the uplink to grab new packages?**.

In that event, I actually **do not** want Verdaccio to re-retrieve existing packages. (this is where the max-age is an issue... I actually don't want a max-age at all. Ie I want the local tarball to remain untouched).

Furthermore, if we have uploaded our own packages into our Verdaccio registry, I would not want those to have a max-age either. (again, max-age is also undesirable because those packages obviously wouldn't exist in the public npm registry). But, perhaps Verdaccio is aware of the fact that it didn't come from npm and therefore doesn't try to grab fresh copies of it from uplinks?? Is that true?

**Summary:**
At a high level, to make my use-case more clear, I understand that Verdaccio is advertised to be a **"private proxy registry"**, but I think I'm trying to use it as just a **"private registry"** that **"grabs from uplinks by command"**.

And, naturally for that use-case, anything/everything that supports "package permanence" and "change awareness" is good. (as opposed to being volatile ~ ie with a max-age before fresh copies are retrieved from uplinks)

Thanks again!

**Comment by juanpicado** [comment]
> what happens when we reactivate the uplink to grab new packages?.
> In that event, I actually do not want Verdaccio to re-retrieve existing packages. (this is where the max-age is an issue... I actually don't want a max-age at all. Ie I want the local tarball to remain untouched).
> in that event, I actually do not want Verdaccio to re-retrieve existing packages.

Then, why bother defining uplinks? if you want an offline experience, don't use them or disable them.

> think I'm trying to use it as just a "private registry" that "grabs from uplinks by command".

One thing to clarify here. **Verdaccio does not download packages**, the package manager starts the request and Verdaccio re-route the request. The package manager decides following semantic versioning what to update. Verdaccio will cache and update metadata from the remotes but never download tarballs. In other words, the magic wand is on the client-side. So, **by command** how do you plan to run those commands? or perhaps you meant something I did not understand.

> perhaps Verdaccio is aware of the fact that it didn't come from npm and therefore doesn't try to grab fresh copies of it from uplinks?? Is that true?

Verdaccio is not aware of which package manager you are using, all follow the same rules.
- First download metadata (packument)
- Resolve in client-side what to update
- Triggers request with a specific version and package name
- In case a new version arrives start to stream the tarball

Verdaccio will proxy (cache) whatever the client aims to download, either metadata or tarballs. If you don't want to the client download new dependencies, then you will need to pin them, but metadata will be updated constantly if you have uplinks enabled.

In case you want to be selective in which packages are updated and which one does not, just you can define multiple package sections 

```
packages:
  '@my-company/*':
    access: $all
    publish: none
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
```
and Verdaccio won't update those, if [you scope packages is much easier to match multiple ones](https://verdaccio.org/docs/en/best#private-registry).

Hopefully, this give you more lights on your thoughts.
