### ISSUE TITLE
package.json is empty in storage package 

### ISSUE THREAD

**Issue by sxqwaade** [verdaccio/verdaccio#1731]
![image](https://user-images.githubusercontent.com/7403258/75671064-e8576180-5cb8-11ea-881a-8ec5309deb65.png)
![image](https://user-images.githubusercontent.com/7403258/75671157-12108880-5cb9-11ea-9680-f46104a58cc7.png)

**Comment by sxqwaade** [comment]
verdaccio version: 4.3.4

**Comment by juanpicado** [comment]
Might be corrupted, remove it and fetch again. 

Also :) I would try to keep updated, latest is 4.4.4.
