### ISSUE TITLE
stability issues with project unit tests when multiple mockServer are executed

### ISSUE THREAD

**Issue by bartsidee** [verdaccio/verdaccio#1733]
**Describe the bug**
The outcome of `npm run test` seems to vary due to some stability issues with the test services that are spin-up for the tests. See also some of the automated PR that are failing:
https://github.com/verdaccio/verdaccio/pulls

**To Reproduce**
execute `npm run test` multiple times on a 'standard' machine or CI

**Background**
The issue is not present if the unit tests are executed sequentially by adding `--runInBand`, further review is that the issues are caused by timeouts of the "beforeAll" methods in the API test where `mockServer` promise is not resolved.
https://github.com/verdaccio/verdaccio/blob/master/test/unit/modules/api/token.spec.ts#L64
https://github.com/verdaccio/verdaccio/blob/master/test/unit/modules/api/api.spec.ts#L49

This is specifically true if they are spin-up in parallel for the different API tests, which also explains why in some cases they succeed and in some cases they fail and why the sequential test do work.

it would be recommended to review the logic in:
https://github.com/verdaccio/verdaccio/blob/master/test/unit/__helper/mock.ts
or re-use the same mock service in between the different API test to prevent multiple processes need to be spin up in parallel.

**Comment by juanpicado** [comment]
I've been working heavily on this topic the last months, I'd recommend you check the branch `5.x` https://github.com/verdaccio/verdaccio/tree/5.x/packages

your feedback would be great, I've separated test un different packages, which will reduce race conditions and scope. 

> This is specifically true if they are spin-up in parallel for the different API tests, which also explains why in some cases they succeed and in some cases, they fail and why the sequential test do work.

I don't see this issue reflected on CI, I'm not saying does not happen, but would be great to know which ones are flaky.
