### ISSUE TITLE
setup verdaccio storage server for 3rd party libraries 

### ISSUE THREAD

**Issue by vlfc** [verdaccio/verdaccio#1736]
I recently implemented verdaccio as a docker image and everything is working fine when I use npmjs in my uplinks. However, what I would like to do is have my designated server, not connected to internet, house 3rd party library tarballs. Now in my uplinks, instead of pointing to npmjs, I am pointing to the designated personal server proxy so it can serve me the same way as npmjs. I placed the 3rd party libraries in ~/verdaccio/storage path. I have set the registry to http://localhost:4873 and added listen: 0.0.0.0:4873 in my config.yml file. This setup is currently failing when I run npm i command despite the packages being present in the storage folder. Is there any guide that can help me with my desired setup?

**Comment by juanpicado** [comment]
Please fill this template before report and issue, that makes more easy to understand to track source of the problem.
https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by vlfc** [comment]
**Describe the bug**
I am trying to implement a private npm registry to house 3rd party libraries
The storage repository will be on a lan server
This will serve as a repository replacing npmjs and house the third party library.
The tarballs in storage folder structure for example in case of lodash package is:
lodash/lodash-1.0.0.tgz

**To Reproduce**
I created a directory on the lan server /verdaccio/storage
Loaded storage folder with 3rd party libraries

Steps to reproduce the behavior on the laptop:
1.	Loaded latest verdaccio as a docker image
2.	Set the registry to http://localhost:4873
3.	Updated the uplinks to point to my proxy server
4.	Updated the proxy section as well
5.	Removed npmjs uplink and proxy from config.yaml
Steps to reproduce the behavior on the server:
1.	Loaded verdaccio as a docker image
2.	Set the registry to http://localhost:4873
3.	changed the config.yaml file uplinks from npmjs to my lan server proxy 
4.	changed the proxy section in the yaml file
5.	Removed npmjs from the uplinks and its proxy 
6.	Added another entry - listen: http:localhost:4873
•	Verdaccio home page can be reached from the proxy via browser

**Expected behavior**
Expected to get the package from the server and caches it on my laptop 
$ npm i lodash
Npm ERR! 404
npm ERR! Not Found – GET http://localhost:4873/lodash - no package available
npm ERR!  
npm ERR!  ‘lodash@^4.17.15’ is not in the npm registry.
npm ERR! You should bug the author to publish it (or use the name yourself)



**Docker information
 - Docker verdaccio tag:  verdaccio:latest
 - Docker commands:   docker load --input verdaccio-latest.tar
 - Docker Version 19.03.1

•	Since I loaded verdaccio as a docker image I did not run: npm install --global verdaccio
•	With the same exact configuration above, it works if I have npmjs in my uplinks and the proxy section but this is not ideal in the near future as we will be using an offline server.

**Comment by juanpicado** [comment]
And what the registry logs says so ? I need more info

**Comment by vlfc** [comment]
I was not able to see the registry logs. what is the command for that, I want to share it so it may help others... But it looks like this is working now. The issue was my config.yaml file was stale. All I did was changed the storage path in the yaml file located on my server and tried to connect to it from my laptop then I reversed my changes to back as it was before /verdaccio/storage, which is the default, and started working without doing anything else. This is very strange but I am a happy camper now. Thanks for your quick response @juanpicado!

**Comment by juanpicado** [comment]
yw @vlfc thank for sharing your solution, the community will appreciate it ❤️ .

I'll close this one then 👍
