### ISSUE TITLE
[Question] npm set registry http://localhost:4873/

### ISSUE THREAD

**Issue by scheung38** [verdaccio/verdaccio#1738]
Doc says
 
    npm set registry http://localhost:4873/

but within corporate site,  in an Angular/Cypress E2E context, client is already using

.npmrc file:

    registry = http://repo.sys.xxx.com/artifactory/api/npm/npm-nx-repos

and corresponding Jenkinsfile:

    stage('Npm Config') {
        steps {
            withDockerContainer(...cypress-latest) {
                sh '''
                    npm config set registry http://repo.sys.xxx.com/artifactory/api/npm/npm-nx-repos
                '''
            }
        }
    }

So how to use Verdaccio when it is already set ?

**Comment by juanpicado** [comment]
hi @scheung38 

Well, I'm not sure what exactly you are trying to achieve, but there are three ways to publish.

* Using global config as you described above 
* Using `.npmrc` in the root of your file
* Using `--registry http://localhost:4873/` flag after each of any `npm` command
* Using `publishConfig` in your `package.json`.

I think you can dive more into this topic here https://docs.npmjs.com/misc/registry

**Comment by scheung38** [comment]
Thanks for reply @juanpicado, my question is if npm config set registry is already used by client, then I will not be able to reuse this Verdaccio again to set it to  npm set registry http://localhost:4873/ ?

**Comment by juanpicado** [comment]
> Thanks for reply @juanpicado, my question is if npm config set registry is already used by the client, then I will not be able to reuse this Verdaccio again to set it to npm set registry http://localhost:4873/ ?

if you have `registry` in thi file`.npmrc` can be overwritten by `--registry` flag. You can decide when to use Verdaccio. I have little information about what you are trying to do.

**Comment by scheung38** [comment]
I just would like to config it so that in Jenkins pipeline npm install is cached, but as I said the .npmrc file is already pointing registry to client private repo, so can I use it on top of their repo

**Comment by jachstet-sea** [comment]
In that case, configure your company's artifactory server as uplink in Verdaccio's config and point your NPM clients to your verdaccio server.

**Comment by scheung38** [comment]
Could you give example how to uplink etc?

**Comment by juanpicado** [comment]
@scheung38 https://github.com/verdaccio/docker-examples/tree/master/multi-registry-uplink
