### ISSUE TITLE
Adding multiple packages from different server

### ISSUE THREAD

**Issue by rluvaton** [verdaccio/verdaccio#1740]
There is currently no way (that I'm aware of) for transferring multiple packages from one server to another.
This is why I created this tool [bulk-npm-publish](https://www.npmjs.com/package/bulk-npm-publish) for publishing multiple packages from 1 verdaccio server to another by bulk publishing

**Comment by juanpicado** [comment]
Hi, nop, there is no way. Your tool seems to be a solution. I haven’t tried but I will take a look. 

Thanks for sharing I will share my thoughts later on 👍

**Comment by juanpicado** [comment]
@rluvaton I'm having a hard time understanding how to use it. Could you give me some examples, what to run ? Readme is good but I don't fully understand how to run it.

**Comment by rluvaton** [comment]
> @rluvaton I'm having a hard time understanding how to use it. Could you give me some examples, what to run? Readme is good but I don't fully understand how to run it.

## Steps
> I assume you installed the package globally

### 1 PC
> The common use case is that you will get the storage from another PC, we just emulating new storage
1. Open the _verdaccio_ config file
2. Change the storage path to new folder (for example `./temp-storage`)
3. Run _verdaccio_
4. Install some package
5. Stop _verdaccio_
6. Change back the storage path to the original one
7. Continue in **2 PCs**

### 2 PCs
1. Run _verdaccio_
2. Open terminal and type `bulk-npm-publish`
3. Write at the first question your folder that contains the packages from another PC
  > if you continued from 1 PC this is the folder you wrote in step 2
4. Type your publish script path that will be created or just press enter for default
5. Type the _verdaccio_ registry URL (no need if in the `.npmrc` file the registry URL is the _verdaccio_ one)
6. If you want to add only new packages press enter and type your current storage path
7. Run the batch file that created (it’s in the path you provided in step 4)

I hope it helps 👍🏻

**Comment by juanpicado** [comment]
Unfortunately is failing the latest version, ` bulk-npm-publish@1.3.0` and nvm `v13.1.0`

```
➜ bulk-npm-publish
 line 1: use strict: command not found
 line 2: syntax error near unexpected token `('
 line 2: `var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {'
```

**Comment by rluvaton** [comment]
> Unfortunately is failing the latest version, ` bulk-npm-publish@1.3.0` and nvm `v13.1.0`
> 
> ```
> ➜ bulk-npm-publish
>  line 1: use strict: command not found
>  line 2: syntax error near unexpected token `('
>  line 2: `var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {'
> ```

Can you please open an issue at the repo so we can further discuss it there, and trying to solve it

**Comment by juanpicado** [comment]
Done https://github.com/rluvaton/bulk-npm-publish/issues/33
