### ISSUE TITLE
where store the user data

### ISSUE THREAD

**Issue by Tender2233** [verdaccio/verdaccio#1751]
I realize a problem when my verdaccio crashed.
i use it in the kubernetes and it worked well ,but when the cpu limits ,the verdaccio may restart.

I have save the packages well but when it return the user data is gone.
I can't see any packages in the web,only data in storage saved

So I'd like to know how to store these import data

**Comment by juanpicado** [comment]
Here https://verdaccio.org/docs/en/cli#default-storage-location

**Comment by Tender2233** [comment]
thx for that
