### ISSUE TITLE
docker container execute pm2 start verdaccio. After reboot Verdaccio Web no Already Publish Package

### ISSUE THREAD

**Issue by ccz-Eric** [verdaccio/verdaccio#1757]
docker container execute pm2 start verdaccio. 
After reboot Verdaccio Web no Already Publish Package，but my can be in storage See him。
How to make my published package，in Verdaccio web sure watch

**Comment by ccz-Eric** [comment]
All of my previous resource packs are not available on the verdaccio web page. But these packages exist in the storage. And when I first contract, he will prompt me "verdaccio database is locked, please contact your administrator to checkout logs during verdaccio startup"

**Comment by juanpicado** [comment]
hi @ccz-Eric, unfortunately, I don't understand your request. I'd suggest you structure your context following this template and add a screenshot, code examples
https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by ccz-Eric** [comment]
version:4.0
When I publish with NPM publish，An error message appears：”verdaccio database is locked, please contact your administrator to checkout logs during verdaccio startup“。The last uploaded package will not be updated to .verdaccio-db.json。How should I solve database locking

**Comment by ccz-Eric** [comment]
#276 I think I ran into this problem, which occurred in verdaccio 4.0。

**Comment by juanpicado** [comment]
I can see you are using `pm2` and I have not enough info, but if you are trying to run in a cluster, won't work

**Comment by ccz-Eric** [comment]
. verdaccio-db.json may be locked unexpectedly during a reboot, resulting in the published package never being written. I need to delete the. Verdaccio-db.json file before the added package can be written normally. Unfortunately, I need to resend all the previous packages. I want to know how to unlock. Verdaccio-db.json after it is locked? Or after locking, it means that the file is damaged and can never be used until you delete it.

**Comment by ccz-Eric** [comment]
Thank you for your reply, I will close this question. The corruption of the DB file is confusing because the process has been running normally.
