### ISSUE TITLE
Display package unpacked size

### ISSUE THREAD

**Issue by adamtay** [verdaccio/verdaccio#1764]
**Is your feature request related to a problem?**
To show package 'unpacked size', similarly to npmjs to allow users to make a conscious decision whether to add in the dependency into their project or not.

**Describe the solution you'd like**
Show 'Unpacked Size' in package UI

**Additional context**
![image](https://user-images.githubusercontent.com/3335306/78297081-65614980-758b-11ea-94a4-585029292b27.png)

**Comment by juanpicado** [comment]
I think this has been already asked before, the answer was not very positive, I’d recommend look into the tickets :) to read about the reasons why we cannot achieve this.
