### ISSUE TITLE
Migrate Helm Chart to our Organization

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#1767]
**Is your feature request related to a problem?**

For a while, Kubernetes helm charts have been hosted here: https://github.com/helm/charts

* Stable chart: https://github.com/helm/charts/tree/master/stable/verdaccio

We are running in issues, due the chart is out of the control of this organization, updates get harder and furthermore, the current repo was deprecated and we have until 13th November 2020, to [migrate the chart to this organization](https://github.com/helm/charts#deprecation-timeline).

@kav has [offered his help](https://github.com/helm/charts/pull/20396#issuecomment-608076315) to migrate all to our organization and this is what about this ticket.

**Describe the solution you'd like**

We will host the Helm chart in this organization

Let's describe what we need to setup this.
https://github.com/helm/charts/pull/20396#issuecomment-609093146

👍 If any of you (readers) have skills in Kubernetes, please don't hesitate to help me here (I'm just learning Kubernetes).

**Comment by jhonmike** [comment]
If you need I can also help, issues:
- Create a new repository, something like `verdaccio-helm` (I like the way `argocd` did, repo example: https://github.com/argoproj/argo-helm)
- Migrate the verdaccio chart to the charts directory
- Create deployment script on gh-pages (Use github-actions or another solution)

What do you think? @juanpicado @kav

**Comment by juanpicado** [comment]
> Create deployment script on gh-pages (Use github-actions or another solution)

We have a custom CDN in DigitalOcean, I was thinking to use that one. 

> Create a new repository, something like verdaccio-helm ..

I've created https://github.com/verdaccio/charts , but I just picked one name from the air.

**Comment by kav** [comment]
If we use github packages they should handle the CDN side as well, and it integrates nicely with Actions of course. I'll take a stab at that as a first step

**Comment by kav** [comment]
Here's the action from the Helm team. Looks like it publishes to ghpages which should also be fine
https://github.com/marketplace/actions/helm-chart-releaser

**Comment by juanpicado** [comment]
@kav I've given you enough permissions to put in shape the repo.  Let me know how can assist you to achieve all we need.

**Comment by jhonmike** [comment]
@kav and @juanpicado, do we use this github action anyway?
if so I can start by doing a PR to set the standard recommended by the action.

**Comment by jhonmike** [comment]
Something like: https://github.com/verdaccio/charts/pull/1

It remains to configure the token, and add a linter and some doc if necessary.

**Comment by juanpicado** [comment]
Migration is ongoing, thanks @jhonmike  @kav . I'd like to have your point of view about what are the next steps we should take.

I'm doing my best to catch up the helm stuff and help on this one.

**Comment by jhonmike** [comment]
I think there are few improvements, something like:

- **Adjust the DOC that is available on the graph page**, could not identify where it is reading the content.
- **We need to do a test and run the "new chart" with the helm on kubernetes**. _I can do this here!_

**Comment by juanpicado** [comment]
> We need to do a test and run the "new chart" with the helm on kubernetes. I can do this here!

Nice !

> Adjust the DOC that is available on the chart page, could not identify where it is reading the content.

I'm lost, what DOC stand for? and which content?

**Comment by jhonmike** [comment]
this page here https://charts.verdaccio.org/

I am uncomfortable with this blank page 😁

**Comment by juanpicado** [comment]
Ahh ! same here ...  that was my intent today, but :( the build did fail.

**Comment by jhonmike** [comment]
>     We need to do a test and run the "new chart" with the helm on kubernetes
![image](https://user-images.githubusercontent.com/2499937/79123277-2ba0f780-7d70-11ea-815b-92e006bfc04d.png)

**Comment by jhonmike** [comment]
it looks like it wasn't the release:
https://github.com/verdaccio/charts/runs/573750604?check_suite_focus=true

**Comment by juanpicado** [comment]
Do you know what 

```
Releasing charts...
Error: error creating GitHub release: POST https://api.github.com/repos/verdaccio/charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
Usage:
  cr upload [flags]
```
means?

**Comment by kav** [comment]
Yes, it means the version in the chart didn't get changed even though the chart changed so it's trying to release it on top of an existing release and failing.

**Comment by juanpicado** [comment]
Should be fixed now :) 

```
charts on  gh-pages at ☸️  docker-desktop 
➜ helm repo add verdaccio https://charts.verdaccio.org
"verdaccio" has been added to your repositories

charts on  gh-pages at ☸️  docker-desktop 
````

**Comment by jhonmike** [comment]
## Test: Done
```sh
Switched to context "docker-desktop".
➜ ~ (⎈ docker-desktop:default) helm repo add verdaccio https://charts.verdaccio.org
"verdaccio" has been added to your repositories
➜ ~ (⎈ docker-desktop:default) helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "verdaccio" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
➜ ~ (⎈ docker-desktop:default) helm install --name verdaccio verdaccio/verdaccio
NAME:   flippant-iguana
LAST DEPLOYED: Tue Apr 14 10:19:47 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME                       DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
flippant-iguana-verdaccio  1        1        1           0          0s

==> v1/Pod(related)
NAME                                        READY  STATUS   RESTARTS  AGE
flippant-iguana-verdaccio-6856f79cbd-knstg  0/1    Pending  0         0s

==> v1/ConfigMap
NAME                       DATA  AGE
flippant-iguana-verdaccio  1     0s

==> v1/PersistentVolumeClaim
NAME                       STATUS  VOLUME                                    CAPACITY  ACCESS MODES  STORAGECLASS  AGE
flippant-iguana-verdaccio  Bound   pvc-8791c953-4c5a-45f5-8398-584b6c466009  8Gi       RWO           hostpath      0s

==> v1/Service
NAME                       TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)   AGE
flippant-iguana-verdaccio  ClusterIP  10.99.36.229  <none>       4873/TCP  0s


NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app=verdaccio,release=verdaccio" -o jsonpath="{.items[0].metadata.name}")
  kubectl port-forward --namespace default $POD_NAME 8080:4873
  echo "Visit http://127.0.0.1:8080 to use your application"

➜ ~ (⎈ docker-desktop:default) k get pods
NAME                                         READY   STATUS              RESTARTS   AGE
verdaccio-6856f79cbd-knstg   0/1     ContainerCreating   0          8s
```

**Comment by juanpicado** [comment]
I think next step is notify oficial repo our new address, it is that correct ?

**Comment by jhonmike** [comment]
I think it's cool to put a `deprecate` in the Readme of https://github.com/helm/charts/tree/master/stable/verdaccio and adjust the documentation pointing to the new repository

**Comment by juanpicado** [comment]
Done https://github.com/helm/charts/pull/21929

Please PR your name here https://github.com/juanpicado/hub to add your name and email as maintainer list if you wish before https://github.com/helm/hub/pull/307 is being merged.

**Comment by juanpicado** [comment]
Furthermore, update docs https://github.com/verdaccio/website/pull/242

**Comment by juanpicado** [comment]
We are already in the Hub, but might be confusing due the versions are equals for some reason.
https://hub.helm.sh/charts?q=verdaccio
https://artifacthub.io/package/chart/verdaccio/verdaccio

**Comment by juanpicado** [comment]
Closing this, let's keep chats https://github.com/verdaccio/charts/issues
