### ISSUE TITLE
Cannot publish a package with same version after previous unpublish

### ISSUE THREAD

**Issue by Temtaime** [verdaccio/verdaccio#1768]
Somestimes when package is unpublished, its tgz file rests in the storage while all the info about this version is erased from package.json.
Next publish with same version yields following error:
error code E400
30 error 400 Bad Request - PUT http://*** - unsupported registry call

This issue is very rare and i am unable to find corresponding lines in the log.
Can we add somewhere a check if tgz is exists and remove it when publishing?

**Comment by juanpicado** [comment]
Please fill the template, there are so many versions being used, template helps to narrow down the solutions.

**Comment by juanpicado** [comment]
Some improvements were made on `verdaccio@6-next` regarding unpublished, could someone try it out?
