### ISSUE TITLE
Missing time for package?

### ISSUE THREAD

**Issue by Temtaime** [verdaccio/verdaccio#1769]
Sometimes when a package is publised, there's no corresponding entry in "time" field of package metadata.
So verdaccio doesn't show when a version was publised, it shows "Not Available".
Is it a known problem?

**Comment by Temtaime** [comment]
I think this is due to https://github.com/verdaccio/verdaccio/blob/a616250e331e6dc06b909951bf1319cf063128c4/src/lib/local-storage.ts#L189

**Comment by juanpicado** [comment]
Please, follow the issue template format, steps to reproduce etc etc.
