### ISSUE TITLE
Search results are not updated when package is added

### ISSUE THREAD

**Issue by Temtaime** [verdaccio/verdaccio#1770]
**Steps to reproduce:**
Run verdaccio.
Publish a package to it.
Try search it in the search toolbox.

**Expected behavior:**
Package is present.

**Actual behavior:**
Package is absent.

Meanwhile, package is present on the main page.
Restarting verdaccio makes it appear in the search.

Also i noticed another one strange thing: if i serach full package name, eg package is named QWERTY, typing QWERT shows it in the search, while if i type QWERTY there's no search results at all.

**Comment by juanpicado** [comment]
Thanks 🙏 for reporting this, it is duplicated there is already one reported by @DanielRuf
