### ISSUE TITLE
escaped slash in namespaced packages

### ISSUE THREAD

**Issue by TrejGun** [verdaccio/verdaccio#1778]
**Describe the bug**

when packages  are installed with https://registry.npmjs.org/
i see following lines in my package-lock.json

```
    "@ampproject/toolbox-runtime-version": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/@ampproject/toolbox-runtime-version/-/toolbox-runtime-version-1.1.1.tgz",
      "integrity": "sha512-ibmw5p+0Sz+wingbX/Dyboe8a0+XDkMfFGSM7KFE0h2z3Op9MADup8ZPLeHT54Z7cYKmB6ob60FVHtQQDhEXNw==",
      "requires": {
        "@ampproject/toolbox-core": "^1.1.1"
      }
    },
```

but with verdaccio slash in package name is converted to `%2f` 
```
      "resolved": "http://192.168.0.239:8080/@ampproject%2ftoolbox-runtime-version/-/toolbox-runtime-version-1.1.1.tgz",
```

I don't mind actully and i had no any side effects because of this, it is just strange

**To Reproduce**

install any namespaced package and check package-lock.json

**Expected behavior**

slash should not be escaped

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**
➜  ~ node -v
v12.16.0
➜  ~ npm -v
6.13.7

verdaccio 4.4.4 docker image

**Debugging output**

 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Additional context**

**Comment by simonfr** [comment]
maybe similar to #1777

**Comment by lvming6816077** [comment]
This bug also in Sinopia.

**Comment by amitgilad3** [comment]
Hey, i decided to take a crack at this issue  #2193 , would appreciate your thoughts and comments
