### ISSUE TITLE
Publish to npmjs registry, except for @mynamespace

### ISSUE THREAD

**Issue by Richie765** [verdaccio/verdaccio#178]
When I publish a package it's being published to my Verdaccio registry.

I'd like to be able to publish to npmjs as well. It would be nice if the packages in @mynamespace would be published to Verdaccio, and all the other packages to npmjs.

Is this already possible? If so how? I couldn't find a way to configure it. If not, can it be implemented?

**Comment by juanpicado** [comment]
No, it's not possible. The main reason is `npm` is who handles the process to publish, whereas `verdaccio` requires a token to publish also `npmjs` requires a different token, so, it would be impossible to do that with one `npm`\`yarn` execution.

**Comment by Richie765** [comment]
Wouldn't it be possible to have a npmjs token in the Verdaccio config and then proxy the publish through using that token? Just like you proxy the install's if the package isn't in Verdaccio yet. Only this time it uses the token in the config. Any reason why that couldn't work?

Btw, you wouldn't believe all the impossible things I've done in my programming career.  😉 It's usually a question of 'how can it be done' than 'can it be done'.

**Comment by Meeeeow** [comment]
You can set registry in package.json, then they will publish to verdaccio, and others publish to npmjs

**Comment by Richie765** [comment]
Thanks @Meeeeow, another impossible accomplishment added to the list.

https://docs.npmjs.com/misc/registry#i-dont-want-my-package-published-in-the-official-registry-its-private

**Comment by dkebler** [comment]
@Richie765 

Yet another impossible accomplishment.  How about a bash script.  Luckily npm does not remove the tokens when you switch from one to another so this works fine.
```
#!/bin/bash
cur=$(cat ~/.npmrc | grep -0 'registry=.*' | cut -f2 -d=)
echo changing from registry $cur to npm
npm set registry https://registry.npmjs.org/
echo publishing to npm
npm publish --access=public 
echo resetting registry to $cur
npm set registry $cur
```

**Comment by Richie765** [comment]
@dkebler, that's a good one! Thanks!
