### ISSUE TITLE
USR2 process signal causes crash: Logger.reopenFileStreams is not a function

### ISSUE THREAD

**Issue by zeeshanmuhammad** [verdaccio/verdaccio#1781]
**Describe the bug**
When USR2 signal is sent to a running verdaccio process, it hard crashes as follows:

`{"name":"verdaccio","hostname":"example.com","pid":12345,"level":60,"err":{"message":"Logger.reopenFileStreams is not a function","name":"TypeError","stack":"TypeError: Logger.reopenFileStreams is not a function\n    at process.<anonymous> (/usr/local/node-v13.11.0-linux-x64/lib/node_modules/verdaccio/build/lib/logger.js:170:12)\n    at process.emit (events.js:327:22)"},"msg":"uncaught exception, please report this\nTypeError: Logger.reopenFileStreams is not a function\n    at process.<anonymous> (/usr/local/node-v13.11.0-linux-x64/lib/node_modules/verdaccio/build/lib/logger.js:170:12)\n    at process.emit (events.js:327:22)","time":"2020-04-24T17:08:39.485Z","v":0}`

I am looking to send a signal to verdaccio so I can rotate its log files. Issue #420 suggests one can send signal USR2 to the actively running verdaccio process to make it reload its file handles.

Normally folks use the HUP signal for this standard "reload" behaviour, but verdaccio ignores this and terminates immediately.

**To reproduce bag**
Run verdaccio
kill -USR2 $(ps -ef | grep ^verdacc+ | awk {'print $2'})
Process will crash, see above log dump

Node version: v13.11.0
verdaccio version: v4.5.1
OS: CentOS Linux release 7.7.1908 (Core)

**Comment by juanpicado** [comment]
Just fixed, please try latest release https://github.com/verdaccio/verdaccio/blob/master/CHANGELOG.md#bug-fixes

**Comment by juanpicado** [comment]
For future readers, a future major release will remove this feature, consider it deprecated. 
https://github.com/verdaccio/verdaccio/issues/1334

I'd recommend using `logrotate` instead (which I guess what you are using).

**Comment by zeeshanmuhammad** [comment]
Thank you for the prompt fix. The community appreciates your hard work and the vivid effort you are putting in.
