### ISSUE TITLE
DEPTH_ZERO_SELF_SIGNED_CERT when trying to publish to registry

### ISSUE THREAD

**Issue by JSchermers** [verdaccio/verdaccio#1783]
Hello all,

** the bug **
I'm running the latest windows preview build (19613) with wsl2 enabled and i can finally build my own docker container out of verdaccio sources with ubuntu on wsl2. I wanted my verdaccio to run https so i followed the instructions on the documentation [here](https://verdaccio.org/docs/en/ssl).

I generated the certificates and put them in my docker.yaml. I added the certificates in the dockerfile

**** Docker.yaml ****

https:
  key: /verdaccio/conf/verdaccio-key.pem
  cert: /verdaccio/conf/verdaccio-cert.pem
  ca: /verdaccio/conf/verdaccio-csr.pem

packages:
      '@myscope/*':
        # scoped packages
        access: $all
        publish: $authenticated
        unpublish: $authenticated
        proxy: npmjs
        storage: private-webam-packages

**** -- end docker.yaml --****

When i run the image everything is fine.  Woohoo . tnx guys!! :)
When i want to publish to this registry I do npm publish --registry=https://localhost:4873 with this configuration:

**** -- package.json -- ****
{
  "name": "@myscope/webcomponents-template",
  "version": "1.0.1",
  "scripts": {
    "build": "rollup -c --watch"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.5",
    "@rollup/plugin-json": "^4.0.2",
    "@rollup/plugin-node-resolve": "^7.1.3",
    "cssnano": "^4.1.10",
    "http-server": "^0.12.1",
    "postcss-modules": "^2.0.0",
    "rollup-plugin-babel": "^4.4.0",
    "rollup-plugin-livereload": "^1.2.0",
    "rollup-plugin-postcss": "^2.6.4",
    "rollup-plugin-serve": "^1.0.1",
    "rollup-plugin-terser": "^5.3.0"
  },
  "dependencies": {
    "haunted": "^4.7.0",
    "lighterhtml": "^3.0.0"
  },
  "browserslist": [
    "> 2% in NL",
    "defaults"
  ]
}

**** -- end package.json -- ****

My result is this error.

**** Error ****
 DEPTH_ZERO_SELF_SIGNED_CERT
npm ERR! errno DEPTH_ZERO_SELF_SIGNED_CERT
npm ERR! request to https://localhost:4873/@myscope%2fwebcomponents-template failed, reason: self signed certificate

**** --End error-- ***

At first i thought it was the npm config .

**** NPM Config ****

python=c:python2.7
@myscope:registry=https://localhost:4873/
//localhost:4873/:_authToken="mytoken"
strict-ssl=false
cafile=C:\Users\[USER]\.config\verdaccio\verdaccio-cert.pem

**** -- end NPM Config -- ****

But this did not help!

I also tried adding the certificates to my trusted root certificates, both local en personal.
No luck either.

Any ideas?

many tnx in advance. I'm really stuck.

Joost

**Comment by sergiohgz** [comment]
Are certificates volume mounted in the container and path inside container matches with one specified in YAML file?

**Comment by JSchermers** [comment]
Hi Sergio,

tnx for your fast reply. I do not really understand you. I have not mounted the drive.  So i will try that. I am new to docker and verdaccio. Can you elaborate why this is important?

The second part i did not understand ".. and path inside container matches with one specified in YAML file?"

i have this 

**** -- docker.yaml -- ****
https:
  key: /verdaccio/conf/verdaccio-key.pem
  cert: /verdaccio/conf/verdaccio-cert.pem
  ca: /verdaccio/conf/verdaccio-csr.pem

**** -- end docker.yaml -- ****

and this for copying the certs from the folder in the source

**** -- dockerfile  -- ****
ADD conf/certs/* /verdaccio/conf/

**** -- end dockerfile  -- ****

I think the path is correct. Am i wrong?

kind regards, Joost

**Comment by sergiohgz** [comment]
That seems to be correct, but let's check anyway. You can go inside container to check if file permissions and path are correct running `docker exec - it <container_id> sh` :wink:

**Comment by JSchermers** [comment]
are these the file permissions?
~/conf/certs $ ls -l
total 12
-rwxrwxrwx    1 root     root          1237 Apr 22 08:14 verdaccio-cert.pem
-rwxrwxrwx    1 root     root          1094 Apr 22 08:14 verdaccio-csr.pem
-rwxrwxrwx    1 root     root          1675 Apr 22 08:12 verdaccio-key.pem



When i stop and start the container and npm publish again i get 401. Now the token is invalid.  Should i set the registry again?
Create a user again and login again

This is my log

---start log ------------

 warn --- config file  - /verdaccio/conf/config.yaml
 warn --- Verdaccio started
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - https://0.0.0.0:4873/ - verdaccio/4.5.1
(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use 
the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:8) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
 http <-- 401, user: null(172.17.0.1), req: 'PUT /@myscope%2fwebcomponents-template', error: authorization required to publish package @webam/webcomponents-template
 http <-- 401, user: null(172.17.0.1), req: 'PUT /@myscope%2fwebcomponents-template', error: authorization required to publish package @webam/webcomponents-template

------- end Log ---------

the log when i could login was (yesterday)

----------------------------- Start log --------------
npm notice name:          @myscope/webcomponents-template
npm notice version:       1.0.1
npm notice package size:  81.9 kB
npm notice unpacked size: 256.2 kB
npm notice shasum:        1ad1ae8b4dd329259b89643e4fead0316f1fb55f
npm notice integrity:     sha512-V07Bqlmj4Dgci[...]7sHC9/sreESxQ==
npm notice total files:   18
npm notice
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT
npm ERR! errno DEPTH_ZERO_SELF_SIGNED_CERT
npm ERR! request to https://localhost:4873/@webam%2fwebcomponents-template failed, reason: self signed certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/webam/.npm/_logs/2020-04-26T14_35_14_260Z-debug.log

---------- end Log --- 

I hope this all helps a little

**Comment by JSchermers** [comment]
is there anything you can tell out of the log? Or is this not the correct detailed information?

**Comment by jachstet-sea** [comment]
Try setting the env var `NODE_TLS_REJECT_UNAUTHORIZED` to `0` on the client machine (the one where you run `npm` on)

**Comment by JSchermers** [comment]
hi @jachstet-sea tnx for your reply. I changed it envrinoment variables on windows and i'm a little further i think. Only no i get a 403

------- Start log ------
$ npm publish --registry https://localhost:4873
npm notice 
npm notice package: @webam/webcomponents-template@1.0.1
npm notice === Tarball Contents ===
npm notice 29B     src/app.css
npm notice 57B     dist/bundle.css        
npm notice 61B     dist/bundle.min.css
npm notice 373B    dist/index.html        
npm notice 595B    test/test.html
npm notice 144B    babel.config.js
npm notice 228.3kB dist/bundle.js
npm notice 21.7kB  dist/bundle.min.js
npm notice 1.0kB   test/helpers.js
npm notice 28B     src/main.js
npm notice 84B     src/model.js
npm notice 1.1kB   rollup.config.js
npm notice 848B    test/test-view.js
npm notice 639B    src/view.js
npm notice 859B    package.json
npm notice 151B    dist/bundle.css.map
npm notice 155B    dist/bundle.min.css.map
npm notice 99B     readme.md
npm notice === Tarball Details ===
npm notice name:          @myscope/webcomponents-template

npm notice version:       1.0.1

npm notice package size:  81.9 kB

npm notice unpacked size: 256.2 kB

npm notice shasum:        cb4357ba30230e7eeb3eed8aad88beeccdde4489
npm notice integrity:     sha512-bKNqxxTMRjM2Y[...]GxKNtOKWzVyyg==
npm notice total files:   18

npm notice 
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://localhost:4873/@webam%2fwebcomponents-template - user webam is not allowed to publish package @webam/webcomponents-template
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

----- End log ---

When i run 

npm whoami --regsitry https://localhost:4873  i can see i'm logged in.

tnx again in advance

**Comment by JSchermers** [comment]
i have tried the same on ubuntu 18.04

same log only is see a little difference in the trace

(node:3573) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://localhost:4873/node - user webam is not allowed to access package node
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/webam/.npm/_logs/2020-04-28T20_48_02_149Z-debug.log


The get shows a /node after https://localhost:4873, becoming https://localhost:4873/node . Could that be the problem?

tnx

**Comment by JSchermers** [comment]
It sure look a lot like this issue

https://github.com/verdaccio/verdaccio/issues/487

with this fix
https://github.com/verdaccio/verdaccio/issues/212#issuecomment-308578500

But i have a specific authtoken in npm config edit

//localhost:4873/:_authToken="mytoken=="

So this does not fix it.... anything else i could try?

**Comment by JSchermers** [comment]
when i publish via yarn i see 

$ yarn publish --registry https://localhost:4873 --verbose
yarn publish v1.22.4
verbose 0.2887928 Checking for configuration file "C:\\Users\\[user]\\Documents\\projects\\rollupTemplate\\.npmrc".
verbose 0.2902813 Checking for configuration file "C:\\Users\\[user]\\.npmrc".
verbose 0.3295486 Found configuration file "C:\\Users\\[user]\\.npmrc".
verbose 0.333241599 Checking for configuration file "C:\\Program Files\\nodejs\\etc\\npmrc".
verbose 0.3356676 Found configuration file "C:\\Program Files\\nodejs\\etc\\npmrc".
verbose 0.337999 Checking for configuration file "C:\\Users\\[user]\\Documents\\projects\\rollupTemplate\\.npmrc".
verbose 0.3391308 Checking for configuration file "C:\\Users\\[user]\\Documents\\projects\\.npmrc".
verbose 0.3398182 Checking for configuration file "C:\\Users\\[user]\\Documents\\.npmrc".
verbose 0.342605499 Checking for configuration file "C:\\Users\\[user]\\.npmrc".
verbose 0.3738088 Found configuration file "C:\\Users\\[user]\\.npmrc".
verbose 0.411859399 Checking for configuration file "C:\\Users\\.npmrc".
verbose 0.4620124 Checking for configuration file "C:\\Users\\[user]\\Documents\\projects\\rollupTemplate\\.yarnrc".
verbose 0.4866603 Checking for configuration file "C:\\Users\\[user]\\.yarnrc".
verbose 0.4882906 Found configuration file "C:\\Users\\[user]\\.yarnrc".
verbose 0.4900424 Checking for configuration file "C:\\Program Files\\nodejs\\etc\\yarnrc".
verbose 0.5233867 Checking for configuration file "C:\\Users\\[user]\\Documents\\projects\\rollupTemplate\\.yarnrc".
verbose 0.528269199 Checking for configuration file "C:\\Users\\[user]\\Documents\\projects\\.yarnrc".
verbose 0.530478599 Checking for configuration file "C:\\Users\\[user]\\Documents\\.yarnrc".
verbose 0.532672499 Checking for configuration file "C:\\Users\\[user]\\.yarnrc".
verbose 0.5335759 Found configuration file "C:\\Users\\[user]\\.yarnrc".
verbose 0.534829 Checking for configuration file "C:\\Users\\.yarnrc".
verbose 0.5428923 current time: 2020-04-30T14:52:35.701Z
[1/4] Bumping version...
info Current version: 1.0.4
question New version:
[2/4] Logging in...
[3/4] Publishing...
verbose 3.9333557 Performing "PUT" request to "https://localhost:4873/@myscope%2fwebcomponents-template".
verbose 3.991823099 Error: Couldn't publish package: "https://localhost:4873/@myscope%2fwebcomponents-template: self signed certificate"
    at MessageError.ExtendableBuiltin (C:\Users\[user]\AppData\Roaming\nvm\v13.12.0\node_modules\yarn\lib\cli.js:721:66)
    at new MessageError (C:\Users\[user]\AppData\Roaming\nvm\v13.12.0\node_modules\yarn\lib\cli.js:750:123)     
    at C:\Users\[user]\AppData\Roaming\nvm\v13.12.0\node_modules\yarn\lib\cli.js:90466:13
    at Generator.throw (<anonymous>)
    at step (C:\Users\[user]\AppData\Roaming\nvm\v13.12.0\node_modules\yarn\lib\cli.js:310:30)
    at C:\Users\[user]\AppData\Roaming\nvm\v13.12.0\node_modules\yarn\lib\cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Couldn't publish package: "https://localhost:4873/@myscope%2fwebcomponents-template: self signed certificate"

-----------

so yarn display another message then npm. Don't know why that is.

So can something be wrong with the certificate. I created it according to the [documentation]("https://verdaccio.org/docs/en/ssl")

**Comment by JSchermers** [comment]
this is a log of what happens

 http <-- 404, user: null(172.17.0.1), req: 'POST /-/v1/login', bytes: 24/150
 http <-- 404, user: null(172.17.0.1), req: 'POST /-/v1/login', bytes: 24/150
 http <-- 201, user: webam(172.17.0.1), req: 'PUT /-/user/org.couchdb.user:webam', bytes: 125/361
 http <-- 201, user: webam(172.17.0.1), req: 'PUT /-/user/org.couchdb.user:webam', bytes: 125/361
 http <-- 404, user: webam(172.17.0.1), req: 'POST /-/v1/login', bytes: 24/150
 http <-- 404, user: webam(172.17.0.1), req: 'POST /-/v1/login', bytes: 24/150
 http <-- 201, user: webam(172.17.0.1), req: 'PUT /-/user/org.couchdb.user:webam', bytes: 125/589
 http <-- 201, user: webam(172.17.0.1), req: 'PUT /-/user/org.couchdb.user:webam', bytes: 125/589
 http <-- 403, user: webam(172.17.0.1), req: 'PUT /@webam%2fwebcomponents-template', error: user webam is not allowed to publish package @webam/webcomponents-template
 http <-- 403, user: webam(172.17.0.1), req: 'PUT /@webam%2fwebcomponents-template', error: user webam is not allowed to publish package @webam/webcomponents-template

**Comment by JSchermers** [comment]
Ok so i updated to the latest version of verdaccio and  everything works ok .I guess this [fix](https://github.com/verdaccio/verdaccio/commit/416d41fa08a92422365599c29b78a49b5e34ec3f) caused my problems...
