### ISSUE TITLE
I want to download the latest version package cached in my server, not the latest version on npmjs, if no version is assigned.

### ISSUE THREAD

**Issue by xtfge** [verdaccio/verdaccio#1786]
e.g. 
The latest version of jquery is 3.5.0,but on my server it is 3.0.0.

exec `npm i jquery`

I expect version 3.0.0 package of jquery to be download  instead of throwing an error， because my server can't access the Internet

**Comment by juanpicado** [comment]
Verdaccio is just a proxy, it does not calculate in anyway what to returns to the client, the package manager does it. If the package is not in the cache, the natural is return a 404. The package manager is the one which decides what to fetch.

I hope that helps.
