### ISSUE TITLE
Search fails for scoped packages

### ISSUE THREAD

**Issue by moss-admin** [verdaccio/verdaccio#1791]
**Describe the bug**

When searching for scoped packages like `@company/core`, the search returns "No results found".

**To Reproduce**

1. Start a fresh instance of the latest Verdaccio version. (e.g. latest available docker image).
2. Publish a scoped package `@company/core`.
3. Open Verdaccio and search for  `@company/core`.

**Expected behavior**

The search result should list the scoped package.

**Additional context**

The bug seems to be a server issue, because in the network log /-/verdaccio/search/ returns an empty array. Propably the describe behavior is related to an inapropriate URL decoding.

Please let me know, if you need further input.

**Comment by brion-fuller** [comment]
Looks like an issue with the lunr-mutable-indexes lib.  Looks like lunr.js has had a few open issues for special characters but none that were addressed.  
What I see from the '@' sign is that is this ignored during indexing.  
If I have a package `@sample/sample` and index.search('sam*') this will return back @sample/sample.

One possible solution is to ignore special characters (not ideal but should get the user what they are looking for)
Another is see if we can get a fix in for lunr.js and handling of special characters.

**Comment by juanpicado** [comment]
> Looks like an issue with the lunr-mutable-indexes lib. Looks like lunr.js has had a few open issues for special characters but none that were addressed.
> What I see from the '@' sign is that is this ignored during indexing.
> If I have a package `@sample/sample` and index.search('sam*') this will return back @sample/sample.
> 
> One possible solution is to ignore special characters (not ideal but should get the user what they are looking for)
> Another is see if we can get a fix in for lunr.js and handling of special characters.

Thanks for diving into it, could you link the issues?

**Comment by brion-fuller** [comment]
Yeah so reading this ticket https://github.com/olivernn/lunr.js/issues/275#issue-233878770. 
It looks to be a feature in lunrjs trimmer function.  I guess one way to handle this I’d use the trimmer on the search term being used.

**Comment by juanpicado** [comment]
Does anyone know a different library alternative to `lunr-mutable-indexes` ?

**Comment by brion-fuller** [comment]
Possibility I saw was fuse.js.  It looks like it's a bit more widely used.  I did an initial test with it and looks like it works well with minimal changes.
https://fusejs.io/

**Comment by crper** [comment]
I have this question, the first search.

Ordinary text can retrieve internal ones, but it's not good to start with @.

Then after searching once, @ will take effect again. Magic.
