### ISSUE TITLE
sidebar API endpoint does not check access

### ISSUE THREAD

**Issue by SheetJSDev** [verdaccio/verdaccio#1793]
**Describe the bug**
The `/-/verdaccio/sidebar/....` endpoint does not authenticate, even external users can query package info.

**To Reproduce**
create a package that only one user can access or publish, then try hitting the sidebar URL for that package.

**Expected behavior**
401 Unauthorized

There seems to be a missing check in https://github.com/verdaccio/verdaccio/blob/master/src/api/web/endpoint/package.ts#L109

The `/package/readme` endpoint integrates some middleware:

```ts
  route.get('/package/readme/(@:scope/)?:package/:version?', can('access'), function(req: $RequestExtend, res: $ResponseExtend, next: $NextFunctionVer): void {
```

That `can('access')` middleware is not used in the sidebar:

```ts
  route.get('/sidebar/(@:scope/)?:package', function(req: $RequestExtend, res: $ResponseExtend, next: $NextFunctionVer): void {
```

**Comment by juanpicado** [comment]
Solved on `v4.6.2` 👍 thanks for the report.
