### ISSUE TITLE
Working with private repositories (confused by documentation)

### ISSUE THREAD

**Issue by comatory** [verdaccio/verdaccio#180]
#### My reason:

I am marking a repo as private, hence in my `package.json`, I have "private" set to "true". When I try to push to verdaccio, I get an error:

```
npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
```

In the documentation it says:

> You can add users and manage which users can access which packages.
> 
> It is recommended that you define a prefix for your private packages, for example "local", so all your private things will look like this: local-foo. This way you can clearly separate public packages from private ones.

I already ran `npm set registry http://localhost:4873` and `npm adduser --registry http://localhost:4873` but it fails, I also tried `npm login` but no luck.

What I'm trying to do is to I created a scoped/namespaced package and I want it to be private.

#### Steps to reproduce:

1.  install verdaccio
2. npm set registry http://localhost:4873
3. npm adduser --registry http://localhost:4873
4. create empty package only with index.js:

```
{
  "name": "@test/table",
  "version": "1.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "registry": "http://localhost:4873",
  "private": "true",
}
```

5. npm publish

####  App Version:	

node: 7.1.0
npm: 3.10.9
verdaccio: 2.15

#### Additional verbose log:

P.S. sorry I hope this is not a wrong place to ask for this

**Comment by juanpicado** [comment]
Hi @comatory `private:true` only avoid to publish in any registry, that includes, `verdaccio` and the official public `npmjs`. If you wish publish, just remove that field from your `package.json`, you can read more about it [here](https://docs.npmjs.com/files/package.json).

About ...

> It is recommended that you define a prefix for your private packages, for example "local", so all your private things will look like this: local-foo. This way you can clearly separate public packages from private ones.

Seems to be just a design suggestion. But is not related with the `private:true`. I'll let this open if you have further questions.

**Comment by comatory** [comment]
Ah I see. Well that is actually what I want, to avoid accidental publishing. But I guess I can control that by user access in verdaccio (I can set up users and only allowed some of the to publish packages).

**Comment by Meeeeow** [comment]
@juanpicado I remember you have commend on another issue and says we can add options to allow user set who can publish package, i can't find it, did you remember?

**Comment by lucianosemerini** [comment]
Quoting npm registry help

> I don't want my package published in the official registry. It's private.
       Set "private": true in your package.json to prevent it from being published at all, or "publishConfig":{"registry":"http://my-internal-registry.local"} to force it to
       be published only to your internal registry.

       See npm help 5 package.json for more info on what goes in the package.json file.
