### ISSUE TITLE
Any ideas

### ISSUE THREAD

**Issue by JSchermers** [verdaccio/verdaccio#1806]
Hello all,

My verdaccio docker container is running in azure and i'm happy it worked out allright. Only it's self generated. So i want to use a docker container with letsencript and compose it with verdaccio docker. 

That's the idea. But i don't know how to do it. And searching the internet did not help me much.  Is this thought possible and if so where  do i have to start or what documentation should i read? My docker experience is low level , just as my understanding of the inner workings of verdaccio itself.

any help much appreciated.

regards, Joost

**Comment by sergiohgz** [comment]
Hi @JSchermers, nice to hear that question. Next time I suggest to visit our discord chat to have a faster talk 😉

About your question, if you want certs generated automatically with let's encrypt, I suggest to share them using a volume. By example, I like to have a container with let's encrypt, other with Verdaccio and link share certs though volume (let's encrypt with write permissions and Verdaccio with read permissions).

Another possibility is with an Nginx as a securized proxy and keep Verdaccio unsecured inside network (but this is less secure)

**Comment by JSchermers** [comment]
Tnx Sergio, I created a question inside discord. If someone can review my steps i think are nescessary [question](https://discord.com/channels/388674437219745793/388675051710447616/709059288727027812) . That would be greatly appreciated since i don't understand the full package.

**Comment by juanpicado** [comment]
> Another possibility is with an Nginx as a securized proxy and keep Verdaccio unsecured inside network (but this is less secure)

Adjust the Firewall would be great advice using Nginx and hide verdaccio port only local access. 

https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-20-04#step-2-%E2%80%93-adjusting-the-firewall
