### ISSUE TITLE
Restrict verdaccio access to only localhost

### ISSUE THREAD

**Issue by jarrod19** [verdaccio/verdaccio#1808]
Hi

I want to restrict access to verdaccio only from localhost. In other words I want verdaccio only to be available from the host machine.

I tried to set the listening to localhost, but this did not seem to work.

**Comment by sergiohgz** [comment]
I think this is not a Verdaccio task. You only need to not expose port from your machine.

**Comment by sergiohgz** [comment]
If this still applies, feel free to reopen issue and we can review, but as I said before, this seems to be network stuff outside Verdaccio scope
