### ISSUE TITLE
Verdaccio is empty after migration  I have synced the configuration file and storage

### ISSUE THREAD

**Issue by huyifanstar** [verdaccio/verdaccio#1809]
I have adjusted the configuration based on historical issues ".sinopia-db.json-> .verdaccio-db.json"

![image](https://user-images.githubusercontent.com/15685376/82040827-c7a88080-96d9-11ea-85f6-a2a18535315e.png)

![image](https://user-images.githubusercontent.com/15685376/82041018-135b2a00-96da-11ea-94cf-3be78b2217c4.png)

**Comment by sergiohgz** [comment]
@huyifanstar there is no need to rename .sinopia-db.json, it's supported by Verdaccio.

If you still have issues, please, fill the template provided, with logs and more information like purpose, versions, etc.

**Comment by juanpicado** [comment]
You would need to relate your migration, past and future, fill the template please.

**Comment by huyifanstar** [comment]
docker image migration


![image](https://user-images.githubusercontent.com/15685376/82112799-24ac4100-9783-11ea-92d1-f12afb9dd1ac.png)

![image](https://user-images.githubusercontent.com/15685376/82112805-368de400-9783-11ea-80c2-dcbdb495b7d7.png)

**Comment by juanpicado** [comment]
I hardly understand your reply, please, without enough information we cannot help you, please follow the format. Your environment description has to be accurate enough so anyone can help you.

**Comment by huyifanstar** [comment]
What information needs to provide?

Logs and docker images? Is there anything?

**Comment by juanpicado** [comment]
Ok, could you read the messages above?

here -> https://github.com/verdaccio/verdaccio/issues/1809#issuecomment-629218075

template: https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/ISSUE_TEMPLATE/Bug_report.md
