### ISSUE TITLE
More UI changes or new UI by own

### ISSUE THREAD

**Issue by amirhbakan** [verdaccio/verdaccio#1810]
Thanks for very wonderful tool. I run the verdaccio on own server and use it. I need 
add some features to UI to have better use for my team. Is there solution to add some components to UI (I mean big changes not for example logo,... ) or change the UI from scratch?

**Comment by sergiohgz** [comment]
By the way, you can create your own UI from scratch, but it could be a hard work. @priscilawebdev can tell you if there is a way to customize UI without creating from scratch.

Also, you can fork UI and touch the parts you want to modify, but you have to follow License specified in repo 😉

**Comment by juanpicado** [comment]
> Thanks for very wonderful tool. I run the verdaccio on own server and use it. I need
> add some features to UI to have better use for my team. Is there solution to add some components to UI (I mean big changes not for example logo,... ) or change the UI from scratch?

It is not easy to extend, actually was not designed with such purpose rather to be bundled with webpack as the final step. The easier is to build your own, but as @sergiohgz mentioned, it is hard hard work for sure.

We rely a lot on React Context API, so, you might somehow replace modules with Webpack and build your own parts, we have tried to split the UI in several components, I'm just speaking louder without check whether is possible or not.

So I guess you would need to evaluate what is easier for you.

**Comment by juanpicado** [comment]
I'm closing this, feel free to keep discussing.

**Comment by gaurav5430** [comment]
So, currently how much of the UI is customizable? I can see some config options here: https://verdaccio.org/docs/en/webui#configuration, is there anything apart from this that can be easily customized?

**Comment by juanpicado** [comment]
> So, currently how much of the UI is customizable? I can see some config options here: https://verdaccio.org/docs/en/webui#configuration, is there anything apart from this that can be easily customized?

That + you can add custom endpoints (via plugins middleware) can be invoked from a README.
