### ISSUE TITLE
Verdaccio not pulling from npmjs registry

### ISSUE THREAD

**Issue by mmeyers45** [verdaccio/verdaccio#1811]
I setup verdaccio running in docker and configured allow all users to publish and access verdaccio. 

I ran the commands:

npm set registry http://localhost:4873
npm install express 

and then I get an internal server error. It appears verdaccio is not attempting to retrieve express from the npmjs registry since express is not local. 

The following is the full log

]$ npm install express
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET http://localhost:4873/express - internal server error

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2020-05-16T21_20_42_820Z-debug.log
[ec2-user@ip-10-0-1-76 ods-api]$ wget http://localhost:4873/express
-bash: wget: command not found
[ec2-user@ip-10-0-1-76 ods-api]$ curl https://localhost:4873/express
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ec2-user@ip-10-0-1-76 ods-api]$ cat  /home/ec2-user/.npm/_logs/2020-05-16T21_20_42_820Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'express' ]
2 info using npm@6.13.4
3 info using node@v10.19.0
4 verbose npm-session 6771b941225ac16b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 500 http://localhost:4873/express 70256ms attempt #3
8 silly fetchPackageMetaData error for express@^4.17.1 500 Internal Server Error - GET http://localhost:4873/express - internal server error
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 70828ms
11 verbose stack Error: 500 Internal Server Error - GET http://localhost:4873/express - internal server error
11 verbose stack     at res.buffer.catch.then.body (/usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose statusCode 500
13 verbose pkgid express@^4.17.1
14 verbose cwd /home/ec2-user/ods-api
15 verbose Linux 4.18.0-193.el8.x86_64
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "express"
17 verbose node v10.19.0
18 verbose npm  v6.13.4
19 error code E500
20 error 500 Internal Server Error - GET http://localhost:4873/express - internal server error
21 verbose exit [ 1, true ]

This is my config:

# path to a directory with all packages
storage: /verdaccio/storage/data
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc
  # darkMode: true

# translate your registry, api i18n not available yet
# i18n:
# list of the available translations https://github.com/verdaccio/ui/tree/master/i18n/translations
#   web: en-US

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    # max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '**':
    access: $all
    publish: $all

    proxy: npmjs

logs:
  - { type: stdout, format: pretty, level: http }

**Comment by juanpicado** [comment]
Hi, error seems in your side. I would check if your container has logs to display and then reproducible steps. As far I can see there is no issue in our side.

I will close it, if you need docker users help feel free to ask in our chat. 

I am closing this.
