### ISSUE TITLE
[Question] There there any way to get the number of times a package was downloaded?

### ISSUE THREAD

**Issue by StephenHodgson** [verdaccio/verdaccio#1813]
I'd really like to know the stats for my packages, like download counts etc. Is this something that is offered out of the box?

If not, is there some direction anyone can point me to get started on supporting such a feature?

**Comment by StephenHodgson** [comment]
Found an old thread #1482

**Comment by StephenHodgson** [comment]
Found another #1201

**Comment by juanpicado** [comment]
> Is this something that is offered out of the box?

No, as far I know. 

Well, my unique idea about this is rotating logs and post-process them counting the request and somehow making your stats if you don't need real-time stats.

Another idea might be https://github.com/verdaccio/verdaccio/issues/1606#issuecomment-582781151

**Comment by juanpicado** [comment]
@StephenHodgson can we close this ?

**Comment by StephenHodgson** [comment]
I mean I guess if the answer is no 😅

Doesn't seem like it's on the roadmap, but it'd be a great feature

**Comment by sergiohgz** [comment]
I don't think we need to perform analytics to packages for everyone. I mean, if I use Verdaccio for e2e testing, why i need those analytics to be executed in my tests?

Also, providing analytics system will require a database to keep those information, listeners to update dB state, etc. These things will make a lightweight registry into a heavy weight registry.

I think you can create a plugin with your own analytics, listening storage events to update data, with some endpoints to get them.

What do you think @juanpicado ?

**Comment by StephenHodgson** [comment]
I can understand the desire to possibly have this as a plugin and not in the core itself, but I still think it is a very valuable feature that should come with the solution by default.

**Comment by juanpicado** [comment]
> Doesn't seem like it's on the roadmap, but it'd be a great feature

Nop, this is the roadmap 

https://github.com/verdaccio/verdaccio/issues/1690
https://github.com/verdaccio/verdaccio/milestone/22

Yeah would be cool, but if we try to keep core small and features as plugins. If someone manage to create this small and performance to be in the core, he will have all my support.


> I think you can create a plugin with your own analytics, listening storage events to update data, with some endpoints to get them.
> What do you think @juanpicado @StephenHodgson ?

Either via middleware (counting requests, parsing url) or analysing logs in posteriori might works, but I guess you will need extra stuff running in separated. 

I'll close this but feel free to post more ideas.
