### ISSUE TITLE
/-/all endpoint doesn't use access groups

### ISSUE THREAD

**Issue by hybridherbst** [verdaccio/verdaccio#1839]
**Describe the bug**
We're using the simple htpasswd auth plugin currently. Tried using https://github.com/btshj-snail/snail-verdaccio-group/ but unfortunately couldn't get it to work yet, so we ended up with just regular lists of users instead of groups.

However, it seems that the /-/all endpoint stopped working - expectation here would be that authenticated users get all packages they are authenticated for when using that endpoint, but instead no packages are returned for anyone now (even if that person has explicit access to all packages).

**To Reproduce**
Set up explicit access instead of using $all or $authenticated:
```
'**':
    # scoped packages
    access: user-01 user-02
    publish: user-01
    unpublish: user-01
```
- Log in in the web backend or through npm
- Use the /-/all endpoint and see that it's empty

The same happens with explicit package access. The web interface lists the correct results, just that (important) all endpoint isn't working (which is important since we're using this with Unity Package Manager which accesses that endpoint to determine which packages it allows to download).

**Expected behavior**
user-01 and user-02 see all packages in /-/all endpoint

**Actual behavior**
/-/all endpoint is empty

**EDIT:** it seems the search endpoint, on the other hand, always returns all packages, also ignoring any auth! This is so weird.

**EDIT 2:** to summarize:
- current auth does not influence the outcome of search and /all
- search always returns all packages
- /all always returns 0 packages (unless for packages where $all is used)
- web interface lists the correct packages the user has auth for

**Comment by hybridherbst** [comment]
Hi! Could I get some additional information here? To me it sounds like a pretty big bug in terms of security if `search` just doesn't care about auth, and a UX bug if `all` doesn't. Just want to understand if you see it similar, or you think this is by design.

**Comment by juanpicado** [comment]
> Hi! Could I get some additional information here? To me it sounds like a pretty big bug in terms of security if `search` just doesn't care about auth, and a UX bug if `all` doesn't. Just want to understand if you see it similar, or you think this is by design.

https://github.com/verdaccio/verdaccio/blob/master/src/api/endpoint/api/search.ts#L67

Search endpoint checks to allow access. I haven't dive into that plugin. Have you reproduced this with a default configuration?

**Comment by hybridherbst** [comment]
This reproduces easily with the default htpasswd configuration when you remove "$all", "$authenticated" and replace them by explicit user name lists (e.g. replace $all by a list of all registered user names).

**Comment by juanpicado** [comment]
Ahh I see. You are hitting https://github.com/verdaccio/verdaccio/pull/1732 which was classified as incomplete.

eg:

````
 http <-- 200, user: null(127.0.0.1), req: 'GET /-/v1/search?text=verdaccio&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5', bytes: 0/1132
```

 This is on live since `v4.5.0`. It seems `npm` hits first that one and then if there is nothing just fallback to `/-/all`. 

I did not understand your request since server log was not provided, always is important share all relevant info so I can act quick :).

Ok, I'll flag this endpoint as experimental and they the `/-/all ` remains as default and future minor release I'll move it by default when we have auth and required set of test (most likely in v5). 

 Thanks for the report.

**Comment by juanpicado** [comment]
Just fyi, the npm local cache
<img width="603" alt="Screen Shot 2020-06-22 at 12 46 40 PM" src="https://user-images.githubusercontent.com/558752/85279288-79c82a80-b486-11ea-9b46-8e48916d88ac.png">

can cheat you time on time, since the original endpoint was made to fetch all modules (not double nowadays with +1m already) has as strong cache and even if you are logged out the package might show up, to fix this just remove the file and try again.

Anyway, the older endpoint still works fine so I'll add the flag.

**Comment by hybridherbst** [comment]
Not quite sure I fully understand what you're saying but you seem to know what's going on :)

Note we're **not** using the default npm registry upstream, this also happens for just the packages hosted in the Verdaccio instance.

What will the behaviour of your proposed solution be? Will `/all` and `/search` behave as intended (taking auth into account)?

**Comment by juanpicado** [comment]
> Not quite sure I fully understand what you're saying but you seem to know what's going on :)
> 
> Note we're **not** using the default npm registry upstream, this also happens for just the packages hosted in the Verdaccio instance.
> 
> What will the behaviour of your proposed solution be? Will `/all` and `/search` behave as intended (taking auth into account)?

`/all` is and endpoint deprecated by npmjs. At verdaccio we proxy all search request to the registry upstream and we aggregate the local private packages. It default search endpoint until someone contributed with a new endpoint #1732 which does not provide authentication layer.  The one you are reporting the issue happens on the new endpoint, the old one is ok, has no bugs. On run `npm search` the CLI will try to hit the newest endpoint, if is not there will get 404 and fallback to `/all`.

My quick fix is disable `v1` endpoint  so you won't have the issue and I buy some time until the endpoint `v1` is ready for production.

Does this answer your doubts?

**Comment by hybridherbst** [comment]
I see. I think so! 

Note that for the time being we actually need the /all endpoint, not the v1 one, since we're using [Verdaccio as package registry for Unity Package Manager](https://docs.unity3d.com/Manual/upm-scoped.html#:~:text=limitations) which does only support` /all` and not the new search if I understand that correctly.

**Comment by juanpicado** [comment]
> I see. I think so! 
> 
> 
> 
> Note that for the time being we actually need the /all endpoint, not the v1 one, since we're using [Verdaccio as package registry for Unity Package Manager](https://docs.unity3d.com/Manual/upm-scoped.html#:~:text=limitations) which does only support` /all` and not the new search if I understand that correctly. 

Well I tested locally and following your steps all works as expected. But as I mentioned above be carful with the strong cache for the all en point has, even logged out might return  same data when you were logged in.

**Comment by juanpicado** [comment]
@hybridherbst try `4.7.1` and let me know whether that helps.

**Comment by juanpicado** [comment]
ping @hybridherbst

**Comment by hybridherbst** [comment]
Sorry, didn't get to it yet, will try over the next week

**Comment by hybridherbst** [comment]
OK tested this again.

It seems that
`/-/all` now returns the packages everyone is allowed to see, but not the extra ones in case I'm logged in - is this expected?
`npm search` now returns the "right" packages as per who's authenticated, after clearing the cache (thanks for mentioning).

**Comment by juanpicado** [comment]
> but not the extra ones in case I'm logged in - is this expected?

I tested that and works for me, I'll double check but be careful with the cache, even logged in `npm search` tend to rely on local cache for a while.
