### ISSUE TITLE
Hope to add changelog display area

### ISSUE THREAD

**Issue by crper** [verdaccio/verdaccio#1844]
**By default, you can read the changelog.md in the root directory or the custom field specified in package.json changelog, is similar to homepage.**

![image](https://user-images.githubusercontent.com/8272877/84976016-7452a380-b159-11ea-8344-e74480d72524.png)

thanks!!

**Comment by hybridherbst** [comment]
https://github.com/verdaccio/verdaccio/issues/1567

**Comment by juanpicado** [comment]
If someones come up with a double idea (within our limits), I'll be more than happy to support it.

**Comment by juanpicado** [comment]
I will close this one, all is clear since #1567 and #813 . Feel free to drop more thoughts or open a new ticket if someone has a double solution.
