### ISSUE TITLE
Doc issue: do published packages remain private?

### ISSUE THREAD

**Issue by jsshapiro** [verdaccio/verdaccio#1845]
This is a tiny thing. The docs say that I can publish a package to verdaccio. That's very useful.

Question: does that package remain local (private), or does verdaccio turn around and publish it upstream?

Perhaps a sentence could be added to the description of publishing to say which way this works?

**Comment by juanpicado** [comment]
No, verdaccio does not have capabilities to publish in any upstream remote connected. All packages remain private by design. 

Could you point out which sentence might be confusing ?
