### ISSUE TITLE
[verdaccio v5]Can you provide a scanning mechanism for package security like github or gitlab?(Security Policy)

### ISSUE THREAD

**Issue by crper** [verdaccio/verdaccio#1847]
## Github
![image](https://user-images.githubusercontent.com/8272877/85093517-1daf9d00-b21f-11ea-925e-ae1f2903a71a.png)

## Gitlab
![image](https://user-images.githubusercontent.com/8272877/85093600-53548600-b21f-11ea-9919-6f619a33a653.png)

solution workflow : https://docs.gitlab.com/ee/user/application_security/

It is hoped that verdaccio will become a heavyweight open source npm repository, a very well-known open source project like gitlab.thanks

**Comment by juanpicado** [comment]
Hi @crper :)

Do you know Verdaccio is not a company right ? . We cannot have those things, it is just impossible. 

Thanks for boosting my hopes :) but I am afraid this is asking too much. Could you close the ticket ?

**Comment by lirantal** [comment]
hey @crper, chiming in here as a dev advocate at [Snyk](https://snyk.io)
have you looked into that before? it's free for open source (for private repos too with a limited scan threshold) and I'm wondering maybe we can build some kind of integration within verdaccio if you're interested in working on it.

You can of course use snyk from the CLI (`npm install -g snyk`), as a docker container or simply connect it to your GitHub repo and you'd get the same automated fix PRs you were showing above.
