### ISSUE TITLE
How to check how many users have been added?

### ISSUE THREAD

**Issue by 030** [verdaccio/verdaccio#186]
`npm ERR! maximum amount of users reached : -/user/org.couchdb.user:sh-developers/-rev/undefined`

**Comment by Meeeeow** [comment]
Check your htpasswd file

**Comment by 030** [comment]
`/home/verdaccio/verdaccio/htpasswd`

**Comment by juanpicado** [comment]
@030 You might double check the value following value in your config file:
`
 max_users: xxxx
`

**Comment by Meeeeow** [comment]
You might need disable registration for a private registry
