### ISSUE TITLE
feat: allow scopes in loading plugins

### ISSUE THREAD

**Issue by IhToN** [verdaccio/verdaccio#1867]
**Describe the bug**
Verdaccio is not able to load @verdaccio/active-directory plugin when using the config setup from the documentation.

**To Reproduce**
Install @verdaccio/active-directory
Set the proper config file
Retrieve error: _verdaccio-activedirectory plugin not found. try "npm install verdaccio-activedirectory"_

**Expected behavior**
Get the plugin to load

If we install the _verdaccio-activedirectory_ package it works as intended, it looks like Verdaccio is not able to load or retrieve the plugin from the @verdaccio scope.

**Comment by juanpicado** [comment]
On the roadmap ;-) @IhToN 

Could be added to `4.x` if someones pick it up.

**Comment by IhToN** [comment]
After some _after-work_ investigations I found that it was possible to reference the plugin name directly on the config.yaml file, example:
`yaml
auth:
  '@verdaccio/active-directory':`

In any case I've added a new condition after _verdaccio-_ and _sinopia-_ prefixes it'll try to load _@verdaccio/_ prefix.

It also changes the Plugin successfully loaded message to follow this structure:
`Plugin successfully loaded: @verdaccio/active-directory || From: locally installed plugin`

From can be: _external plugin folder_, _locally installed plugin_ and _config folder_

**Comment by juanpicado** [comment]
@IhToN one suggestion, this is something I've been thinking for a while .. what if .... the `prefix` is configurable ... ? I mean, nobody could publish under `verdaccio` scope at npmjs, so the feature would have limited use cases. 

I'd suggest a new configuration parameter:

```
plugin_prefix: 'whatever` 
```

Then we could override the default here:

```
export default function loadPlugin<T extends IPlugin<T>>(
  config: Config,
  pluginConfigs: any = {},
  params: any,
  sanityCheck: any,
  prefix: string = 'verdaccio'
): any[] {
```

That will solve your issue and you wouldn't have to do this

```
auth:
  '@verdaccio/active-directory':
```

rather a default configuration

```
plugin_prefix: '@verdaccio` 
auth:
  active-directory:
```

This scalable for private plugins :) for all needs.

what do you think?

**Comment by IhToN** [comment]
@juanpicado That would be another possibility but then we would still have the struggle that it may be that different plugins have different prefixes.

If we have the packages
```
@verdaccio/active-directory
@foo/bar
@zoo/bar
@joo/bar
```
the problem will persist, and for the end user it will be simplier just to use the full plugin name.

The way it is right now it's kind of a way to have "official" plugins (@verdaccio/, verdaccio- and sinopia-) and it would still let the end user include an infinite amount of plugins wihtout problems.

It may be needed to document properly how the plugin loading works though.

**Comment by juanpicado** [comment]
A workaround for this is here https://github.com/xlts-dev/verdaccio-prometheus-middleware#installation

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/pull/3227
