### ISSUE TITLE
Fail to get package from npmjs.org

### ISSUE THREAD

**Issue by rodrigogrow** [verdaccio/verdaccio#187]
#### My reason:

Fail to get package from npmjs.org 
http  --> ERR, req: 'GET https://registry.npmjs.org/gulp', error: unable to verify the first certificate
http  <-- 404, user: undefined, req: 'GET /gulp', error: no such package available

#### Steps to reproduce:

run verdaccio server
npm set registry "http://localhost:4873"
npm install gulp

####  App Version:	
verdaccio@2.1.5
ubuntu14.04

#### Additional information:

If I try set npm again to 
npm set registry "https://registry.npmjs.org/"

it works fine

   - [x] I use local environment
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS.

**Comment by juanpicado** [comment]
Could you provide your config file?

**Comment by Meeeeow** [comment]
Did you try `curl https://registry.npmjs.org`? If this command failed, you may need install ca certificate on your system

**Comment by rodrigogrow** [comment]
Hi @Meeeeow i try this command and works fine:
{"db_name":"registry","doc_count":558408,"doc_del_count":350,"update_seq":5783690,"purge_seq":0,"compact_running":false,"disk_size":3197748950,"data_size":2495491039,"instance_start_time":"1494323134231907","disk_format_version":6,"committed_update_seq":5783690}

**Comment by rodrigogrow** [comment]
When I change uplink url from https to http protocol in config file it works fine.. Maybe there is something wrong in my certificate..

**Comment by juanpicado** [comment]
@rodrigogrow try to display more verbose and you might figure out what's wrong in your request
` curl -v https://registry.npmjs.org `

eg:
```bash
* Rebuilt URL to: https://registry.npmjs.org/
*   Trying 151.101.132.162...
* TCP_NODELAY set
* Connected to registry.npmjs.org (151.101.132.162) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: npmjs.org
* Server certificate: GlobalSign Extended Validation CA - SHA256 - G2
* Server certificate: GlobalSign
> GET / HTTP/1.1
> Host: registry.npmjs.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< server: CouchDB/1.5.0 (Erlang OTP/R16B03)
< Content-Type: text/plain
< Cache-Control: max-age=300
< Content-Length: 262
< Accept-Ranges: bytes
< Date: Wed, 10 May 2017 13:49:15 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-mad9429-MAD
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1494424155.044550,VS0,VE461
< Vary: Accept-Encoding
< 
* Curl_http_done: called premature == 0
* Connection #0 to host registry.npmjs.org left intact
```

**Comment by rodrigogrow** [comment]
HI @juanpicado thanks for suggestion.

I found problem in SSL handshake in my side.. So I will close this issue.

Thanks
