### ISSUE TITLE
modclean breaks verdaccio because of module readme

### ISSUE THREAD

**Issue by joequant** [verdaccio/verdaccio#1883]
When I run modclean on a directory with verdaccio, it causes verdaccio to break.  It appears that modclean will remove files called "readme*" and there is a module in verdaccio called readme.

**Comment by juanpicado** [comment]
Would you explain what is modclean? I have no clue what it does.

**Comment by joequant** [comment]
https://www.npmjs.com/package/modclean

modclean is a very useful utility that goes into the node_modules directory and slims things by 
removing unnecessary files.  I use it with docker images to slim down the image.

The issue is that one thing that modclean does is to remove files called "readme*" and it appears
that verdaccio has a module called readme.

**Comment by juanpicado** [comment]
Well, yes, we have a `@verdaccio/readme` that's true. But, wouldn't be an issue more related with `modclean` rather with Verdaccio? 🙃 I am not sure what I can do from my position to be honest.

**Comment by DanielRuf** [comment]
> Well, yes, we have a @verdaccio/readme that's true. But, wouldn't be an issue more related with modclean rather with Verdaccio?

I agree with that, modclean probably warns about potential issues in their docs. Do they provide some option for setting a list of ignored paths?

**Comment by DanielRuf** [comment]
I suggest to open an issue at the modclean repo.

Also:

https://github.com/ModClean/modclean/wiki/Custom-Pattern-Plugins

![Screenshot_20200725-140029](https://user-images.githubusercontent.com/827205/88456645-7a861f00-ce7f-11ea-8f90-c5fe84c72322.jpg)

**Comment by juanpicado** [comment]
I'll close this since is an external issue, no more actions from our side. Feel free to leave feedback anytime.
