### ISSUE TITLE
External Travis build failure graphic in README.md

### ISSUE THREAD

**Issue by steve-p-com** [verdaccio/verdaccio#19]
At the top of `README.md` there is a red graphic which says 'build: failing'. This is an external link to `https://travis-ci-org`. I haven't used this stuff before, but basically what happens is that whenever a commit is made, `GitHib` tells `travis-ci-org`, which then checks out the code and runs all the tests. It emails if there's a failure, and it enables the dynamic icon in the `README.md` as well.

If we want to make use of this, then we will need a free account on https://travis-ci.org for user `verdaccio`, which will have to be created and owned by @trentearl . It will need `verdaccio/verdaccio` on GitHub linking to it. Then we can change the link in  `README.md` from https://travis-ci.org/rlidwka/sinopia to https://travis-ci.org/verdaccio/verdaccio.

The eagle-eyed may have spotted that in the original `sinopia` version, it says the build is failing. And so was `Verdaccio`, but it appears that eliminating the messy optional dependencies in #18 has fixed the external Travis build, as some sort of bonus. So if we do set this up, our icon will turn green, because our version does build 😄

**Comment by steve-p-com** [comment]
This is Sinopia: ![travis badge](https://travis-ci.org/rlidwka/sinopia.svg)

Here's my fork after #18 : ![travis badge](https://travis-ci.org/steve-p-com/verdaccio.svg)

https://travis-ci.org/steve-p-com/verdaccio/

**Comment by trentearl** [comment]
Fixed and passing 👍

**Comment by steve-p-com** [comment]
Awesome :smile: I guess we should start publishing it soon so people can `npm install verdaccio`.
