### ISSUE TITLE
Error installing verdaccio

### ISSUE THREAD

**Issue by luisvidal86** [verdaccio/verdaccio#1901]
When you try to install verdaccio using npm, you will get this error code:

npm ERR! 404 Not Found: @verdaccio/commons-api@9.7.1

Besides, if you try to install any other package under @verdaccio/xxxxxx you will get a 404. I guess it is a problem after the migration to @verdaccio/monorepo

I'm using this versions of node and npm:
# node --version
v10.11.0

# npm --version
6.4.1

I'm working with Windows 10 x64 version 1909

**Comment by DanielRuf** [comment]
Please see https://status.npmjs.org/

![grafik](https://user-images.githubusercontent.com/827205/89529309-c8d6de80-d7ec-11ea-8e29-35385cc90699.png)


We can not do much. Alternatively you can use the Docker version which is hosted on Docker Hub.

**Comment by DanielRuf** [comment]
Closing as this should be resolved later today and this is a general issue with npmjs - we have no control over this. You may want to use `npm install --global --force verdaccio` to bypass local caches.
