### ISSUE TITLE
Verdaccio encountered problems when deploying on macos system to expose services through nginx

### ISSUE THREAD

**Issue by ZhengHuang-20** [verdaccio/verdaccio#1907]
my nginx conf ：
![image](https://user-images.githubusercontent.com/61463534/90598821-5b807000-e226-11ea-8e5e-03ec33c915bd.png)
when myClient visit website 
![image](https://user-images.githubusercontent.com/61463534/90599012-adc19100-e226-11ea-88e2-b79e2b889eb2.png)

**Describe the solution you'd like**
Why are there only a few static resources requesting local resources?
Is it necessary to modify the web application to meet the requirements?

**Comment by juanpicado** [comment]
hi @ZhengHuang-20 

please check https://github.com/verdaccio/docker-examples/blob/master/reverse_proxy/nginx/root_path/conf/nginx/sites-enabled/verdaccio-conf

**Comment by jackason** [comment]
这个是是一个window服务器
