### ISSUE TITLE
export uplink search result config

### ISSUE THREAD

**Issue by joebnb** [verdaccio/verdaccio#1909]
https://github.com/verdaccio/verdaccio/blame/66f4197236d9d71af149314aae15102b336f45e1/src/api/web/endpoint/search.ts

could export export uplink search result by config ?

![image](https://user-images.githubusercontent.com/1646883/90618186-326dd880-e242-11ea-9a96-ab60927b81b6.png)

in many cases user's private pacakges  are scoped,and sarch some package unscoped in uplinks ,and i if hold a private package repo,i will search private packages either public package on it

**Comment by juanpicado** [comment]
Could you elaborate an scenario with examples for better understanding your point of view?

**Comment by joebnb** [comment]
i was implement this feature
