### ISSUE TITLE
htpasswd bcrypt support

### ISSUE THREAD

**Issue by AshtonRoute** [verdaccio/verdaccio#191]
#### My reason:

Seems that `verdaccio/lib/plugins/htpasswd/utils.js` `verify_password` doesn't support bcrypt encryption.

####  App Version:	
2.1.7

Would be cool if you can add bcrypt :)

**Comment by juanpicado** [comment]
Hi @AshtonRoute.  I'd recommend create a plugin for that,  please take a look th e following list of plugins as an idea. https://github.com/verdaccio/verdaccio/wiki/Plugins . The main point here, is, make `verdaccio` pluggable as possible. Would you like that as challenge?

**Comment by AshtonRoute** [comment]
Hello @juanpicado. I completely agree with your idea, but I think it will be better to implement it as a plugin when you deal with #192. For now I think its better to just add it as another option (separate file) to `verify_password`. It won't break anything and it will be much easier to move it to `htpasswd` plugin as you suggested in #192.

Anyway, adding [bcrypt](https://www.npmjs.com/package/bcrypt) to current code base is easy.
I can send a PR on this weekend if I have time :)

**Comment by juanpicado** [comment]
Cool :) looking forward to see the PR. thanks 👍

**Comment by juanpicado** [comment]
I'll close it, follow up here https://github.com/verdaccio/verdaccio-htpasswd/issues/4
