### ISSUE TITLE
Allow other password hashing algorithms

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#1917]
#### My reason:

Currently, we support verify on multiple formats but we do not on the sign the password, we shoud allow this plugin to sign with something different than `CRYPT`

https://httpd.apache.org/docs/2.4/misc/password_encryptions.html

**Comment by piraz** [comment]
What a coincidence I'm working on the same issue on some of my projects. I don't have full knowledge about what you do to fix the issue but I just bump to those articles:

This one is for strengthening ldap passwords using linux crypt: https://www.redpill-linpro.com/techblog/2016/08/16/ldap-password-hash.html. I don't even know that crypt would generate passwords in another formats, so on ldap you generate a SHA512, SHA256 or Blowfish and stored it the hash signaled as crypt and ldap will use the lib with that strong algo pointed in the hash.

This one is about peper and how to validate the generated hash: https://crackstation.net/hashing-security.htm. In the case of pepper that must be considered well as old passwords are not peppered so you have a compatibility issue that should be solved in your system before.

On my projects I can get direct interface to unix cyrpt but I don't know if there is anything available in JavaScript.

I hope that could be useful information on this task.

**Comment by juanpicado** [comment]
Thanks @piraz really appreciated 👏
