### ISSUE TITLE
BUG - author & contributors are not displayed

### ISSUE THREAD

**Issue by xstable** [verdaccio/verdaccio#1923]
I've entered the needed fields in my package.json like that: 
![image](https://user-images.githubusercontent.com/1778068/91547002-9881ec00-e923-11ea-853b-242bb21f15a6.png)

But they don't appear in the output-page of verdaccio.

```json
{
  "name": "@xstable/gatsby-theme-onepager",
  "description": "Gatsby Theme for SEO & Performance optimized Onepager's",
  "autor": "Samuel Suthe <foo@bar.com> (https://fobar.com)",
  "contributors": ["Bim Bom <bim@bom.net>"],
  "bugs": "https://gitlab.com/xstcodebase/gatsby-bootstrap-project/-/issues",
  "version": "0.1.1",
  "main": "index.js",
  "license": "SEE LICENSE IN LICENSE.md",
  "keywords": [
    "gatsby",
    "onepager"
  ],
}
```

**Comment by juanpicado** [comment]
You have *autor* instead *author*. That explains why you see **Anonymous**

**Comment by xstable** [comment]
Yep, that's it.
Do you have an Idea, what's wrong with contributors?

**Comment by juanpicado** [comment]
> Yep, that's it.
> Do you have an Idea, what's wrong with contributors?

I'd need to check, not 100% sure.
