### ISSUE TITLE
Request: get rid of LevelDB

### ISSUE THREAD

**Issue by rix0rrr** [verdaccio/verdaccio#1925]
**Is your feature request related to a problem? Please describe.**

Right now, the Verdaccio local storage plugin uses LevelDB to store tokens.

This is a rather heavyweight dependency; it requires compiling a native extension using node-gyp (which itself requires Python and a compiler). 

It also means that using Verdaccio out of the box on a plain Windows machine is out of the question, and makes Verdaccio a pain to use in CI/CD setups where we use simple plain Windows images. I'm now forced to build a pipeline to manage my Windows testing image.

What's worse, Verdaccio seems to use simple gets and puts in a way that doesn't seem very performance sensitive, so no need for a compiled component. A simple JS-powered storage solution would do the just just as easily.

When LevelDB was introduced here: https://github.com/verdaccio/local-storage/pull/168 there were some initial misgivings, but they were ultimately put aside.

**Describe the solution you'd like**

Use a pure-JavaScript KV store so I don't need to install Python and a C compiler before I can use Verdaccio. If you're concerned about performance, make the token storage backend configurable, or opportunistically use leveldb (turn leveldb into an optional dependency and use it if it has been installed).

**Describe alternatives you've considered**

I've considered not using Verdaccio, but you seem to be the only game in town so that would mean reimplementing my own NPM registry and I really don't want to do that.

**Comment by juanpicado** [comment]
I'll replace level by https://github.com/typicode/lowdb , buyan #1334  is not part anymore of `5.x` branch so the issue here should be solved.
