### ISSUE TITLE
Allow url_prefix to define only url path

### ISSUE THREAD

**Issue by BartDubois** [verdaccio/verdaccio#193]
#### My reason:

While i'm using Docker on Windows 2016 i can't define full URL in `url_prefix` (see [docker/for-win#458](https://github.com/docker/for-win/issues/458)). All my CI/CD environment is setup on one machine so inside worker node I need to use Docker internal Verdaccio container name, but outside i use the host machine name.

Generally speaking i need to define only the path with in config file inkstand o full protocol, host, port and custom path in `url_prefix`. When the value is defined as `/some-path` the all seams to work beside downloading the gziped packages. The reason is that package.json  in the registry has invalid tarball value. The host is missing.

I made a fix at https://github.com/BartDubois/verdaccio/tree/url_prefix-as-path that allow define only the path as `url_prefix`.

#### Steps to reproduce:

Define in config file `url_prefix`
```yaml
url_prefix: /my-path
```

Configure reverse proxy using the same path (I used ngnix).
Configure registry settings through `npm set` and try to install some public package.

#### Additional information:
	
 - Windows
 - Container:
   - [x] I use local environment
   - [x] I develop / deploy using Docker.

**Comment by juanpicado** [comment]
@BartDubois could you PR your solution?
