### ISSUE TITLE
Requirements of Web UI configuration function

### ISSUE THREAD

**Issue by niubg** [verdaccio/verdaccio#1934]
he footers in the Web UI can be removed by configuration. The help at the top of the web page and whether the dark night mode should be added to the configuration file. Some UI interface display functions are not what we want to use. We hope to set the hyperlinks of the logo to customizable configuration hyperlinks

**Comment by juanpicado** [comment]
hi @niubg, it would be great if you follow the template suggested, helps with readability and engagement (if you want to get few 👍 ).

**Comment by juanpicado** [comment]
Closing until this get more clear and detailed.
