### ISSUE TITLE
How can I transfer my old sinopia storage to verdaccio?

### ISSUE THREAD

**Issue by TheZadok42** [verdaccio/verdaccio#1936]
I have an old sinopia server and I want to move to verdaccio.  
I tried to configure verdaccio's storage path to sinopia's one but I don't see any node-modules.

Is there a way to transfer all of them or should I write a script for mass-publish?

**Comment by juanpicado** [comment]
hi @TheZadok42 

did you read https://verdaccio.org/blog/2019/02/24/migrating-verdaccio#migrating-from-sinopia140-to-verdaccio-2x3x ?
