### ISSUE TITLE
Option to enable HeaderIds in marked

### ISSUE THREAD

**Issue by mknj** [verdaccio/verdaccio#1938]
**Is your feature request related to a problem?**
It would be helpful if you could jump directly to a give location the project page/README.md.
Today tools like oclif create README.md files that contain e.g. a TOC that relies on HTML anchors.
Websites like github or gitlab also support these anchors.

**Describe the solution you'd like**
The marked package used by verdaccio can generate these anchors( as id=...) by setting `marked.use({renderer,headerIds: true})`
If there are usecases where headerIds are not welcome, i'd like to have a config option where i can enable them manually for my verdaccio installation.

**Comment by juanpicado** [comment]
@mknj do you mean (branch `5.x`) `packages/core/readme/src/index.ts`  here

```
 return DOMPurify.sanitize(
      marked(readme, {
        sanitize: false,
      }).trim()
    );
```

https://marked.js.org/using_advanced ?

Have you tried already?

**Comment by mknj** [comment]
just tried with verdaccio/verdaccio:5.x-next.

 **curl http://localhost:4873/-/verdaccio/package/readme/minipackage shows the header id**
```
curl http://localhost:4873/-/verdaccio/package/readme/minipackage
<p>hallo</p>
<h1 id="some-header">some header</h1>
<p>demo</p>
```
**but the webapp http://localhost:4873/-/web/detail/minipackage still has**
```
<h1>some header</h1>
```
**it seems that the webapp does some sanitize() too.**

Is there some way to customize the webapp rendering?

**Comment by juanpicado** [comment]
@mknj could you PR your patch so we are sure we are testing the same thing?

**Comment by mknj** [comment]
i hacked some files in the container, maybe my changes were not picked up correctly.

I have problems setting up the dev env, so i can't do a proper PR. how do i set up a dev env?

# shell fails
```bash
$ pnpm install
... 
$ pnpm build
... ok
$ pnpm test
... ok
$ pnpm start
... Error: Cannot find module 'core-js/modules/es.promise'
$ pnpm dev

> @ dev /home/bob/js/verdaccio
> cross-env BABEL_ENV=registry babel-node --extensions ".ts,.tsx" packages/cli/src

/home/bob/js/verdaccio/packages/cli/src/cli.ts:4
import commander from 'commander';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

# docker fails
```bash
$ git clone git@github.com:verdaccio/verdaccio.git
...
$ cd verdaccio
$ git checkout 5.x
...
$ pnpm docker
...
Successfully built f35cc2e9236c
Successfully tagged verdaccio/verdaccio:local

$ docker run -it --rm verdaccio/verdaccio:local
internal/modules/cjs/loader.js:968        
  throw err;                                
  ^                                                                                        
                                                                                           
Error: Cannot find module 'kleur'                                                          
Require stack:                                                                             
- /opt/verdaccio/packages/cli/build/cli.js                                                 
- /opt/verdaccio/packages/cli/build/index.js                                               
- /opt/verdaccio/packages/verdaccio/bin/verdaccio              
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
```

# versions
```
$ pnpm version
{
  npm: '6.14.8',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.0.4',
  modules: '83',
  napi: '6',
  nghttp2: '1.41.0',
  node: '14.7.0',
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.38.1',
  v8: '8.4.371.19-node.12',
  zlib: '1.2.11'
}
$ LANG="" git status
On branch 5.x
Your branch is up to date with 'origin/5.x'.

nothing to commit, working tree clean
```

**Comment by mknj** [comment]
In earlier versions of verdaccio this problem was causes by the xss module that was replaaced by dompurify in the latest master.

Unfortunately i still can't get `pnpm run docker` working with the latest master. 

The 5.x-next version on docker-hub is 2 months old and still uses xss in some places.

**Comment by juanpicado** [comment]
@mknj master uses still `yarn v1`. The master only allows deps updates or urgent bug fixes. New development happens only on `5.x` otherwise is crazy keep both on sync. 

The `5.x-next ` on Docker hub yeah, it is old, I should remove that tag. I'm deploying here https://github.com/verdaccio/verdaccio/packages/13531 in every merge to `5.x`
