### ISSUE TITLE
Prepopulate Verdaccio Container with User

### ISSUE THREAD

**Issue by manuschillerdev** [verdaccio/verdaccio#1942]
**Is your feature request related to a problem?**
Right now we deploy verdacccio to a kubernetes cluster which works fine. However after the depyloment we manually add a User with `kubectl exec -it verdaccio -- /bin/sh -> npm adduser`. We have not found a way to automate that so far.

**Describe the solution you'd like**
We would love to be able to populate the instance with a default user from our configs when the service gets deployed and that user does not exist yet.

**Describe alternatives you've considered**
- We looked into the configuration options and did not find a fitting option.
- We thought about using a custom entrypoint, but we couldn't manage to edit it our selves properly

Thanks for any hints or help!

**Comment by juanpicado** [comment]
hi @manuschillerdev 

The user must to be created using a package manager. That's the right way. 

The unique way I know to pre-populate users is with this plugin https://github.com/verdaccio/monorepo/tree/master/plugins/auth-memory
