### ISSUE TITLE
Did data statistics implemented in version 5?

### ISSUE THREAD

**Issue by joebnb** [verdaccio/verdaccio#1948]
according #1482 .

i want to implement this feature by myself，but it will add a lot of works,such data collect,api develope,ui develope,and it will not to common to use (the redis way),and it may make more upgrade coast,im request to official to implement a simple statistics such use filelock and sqlite etc.,and web api.

**Comment by juanpicado** [comment]
I'm not sure whether I understood correctly, but please feel free to rephrase your question in any case. I don't aim to create statistics, rather create the API so anyone can do it, that's what I meant on #1482 .

**Comment by joebnb** [comment]
> Hooks will be improved in Verdaccio 5, but that is next year hopefully, depends of the available resources, but that is my wish. So things as you suggest will be more easy to address.

sorry,i got wrong understood,hook just mean callback hooks in logs

**Comment by juanpicado** [comment]
I don't know what sort of metrics you need, but the logger is the best way to get some. Eg: you might interpret Nginx logs with any third party tool (eg: kibana + logstash) and then get interesting data from there like file downloads, access to a specific package, and version, but all of that is made out of the verdaccio world (theoretically <-- I never tried myself) . 

So, as the final answer, it won't be data statitics implementation within Verdaccio 5, but we want to allow others to do it. 

I'm closing this, feel free to ask more if you have any doubt.
