### ISSUE TITLE
[SECURITY] Insecure password hashing

### ISSUE THREAD

**Issue by rmi7** [verdaccio/verdaccio#195]
#### My reason:

- I saw `sha1` is used for hashing the password, yet it's a deprecated insecure hashing algorithm, next to that it's not meant for hashing passwords!!!
- If the above wasn't bad enough, **you don't even use a salt** --> https://github.com/verdaccio/verdaccio/blob/6d8d05b0ccbedcf38868e65c226400c66783a4f2/lib/plugins/htpasswd/utils.js#L57

####  App Version:	
all

#### Solution
use a hashing algorithm made for password hashing: (`pbkdf2`, `bcrypt`, `scrypt`).

I would suggest bcrypt (npm `bcrypt`), It will automatically take care of adding a salt!

#### Conclusion
get your crypto together this app is highly insecure currently

**Comment by jmwilkinson** [comment]
I think the code is just confusing and should probably be re-written.

If you trace through what actually happens, [crypt3 is required](https://github.com/verdaccio/verdaccio/blob/6d8d05b0ccbedcf38868e65c226400c66783a4f2/lib/plugins/htpasswd/utils.js#L4), and [used by default](https://github.com/verdaccio/verdaccio/blob/6d8d05b0ccbedcf38868e65c226400c66783a4f2/lib/plugins/htpasswd/utils.js#L54), and that [uses sha512 with a salt](https://github.com/verdaccio/verdaccio/blob/master/lib/plugins/htpasswd/crypt3.js#L40). So it is secure. Just needs a re-write for clarity.

**Comment by juanpicado** [comment]
Something to have on mind for #192

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/releases/tag/v3.0.0-beta.6 includes ** bcrypt support**
