### ISSUE TITLE
Website link appears broken

### ISSUE THREAD

**Issue by ryanve** [verdaccio/verdaccio#196]
<figure>
<h2>2017-05-18 <a href="https://verdaccio.github.io">verdaccio.github.io</a> screenshot</h2>
<blockquote>The domain <a href="http://verdaccio.org">verdaccio.org</a> is no longer parked by GoDaddy.</blockquote>
<img width="1670" alt="The domain verdaccio.org is no longer parked by GoDaddy." src="https://cloud.githubusercontent.com/assets/949985/26212247/cb0cafdc-3ba9-11e7-89a0-6de20ad0b69b.png">
</figure>

**Comment by juanpicado** [comment]
Thanks. I was working on it :) . There is no website yet anyway, I haven't had time :(

**Comment by juanpicado** [comment]
It seems fixed already, Could you try again?

**Comment by ryanve** [comment]
It still redirects to a godaddy landing page `http://verdaccio.org/?reqp=1&reqr=`

I recommend then removing the website link from the repository header info because a lot of people will probably link to that. Or create a `gh-pages` page and put a landing page there.

**Comment by juanpicado** [comment]
I removed it already. The page is here https://github.com/verdaccio/verdaccio.github.io . It's seems to be a DNS issue, thanks for the quick test.

**Comment by juanpicado** [comment]
I think DNS was refreshed already. Please try again to close this one :)

**Comment by ryanve** [comment]
Cool yes https://verdaccio.github.io is working now : )

**Comment by Meeeeow** [comment]
@ju

**Comment by juanpicado** [comment]
@Meeeeow what do you mean?

**Comment by Meeeeow** [comment]
@juanpicado https://verdaccio.github.io using an old screenshot, it should replace with current one in README.md

**Comment by juanpicado** [comment]
@Meeeeow ahh yes 👍  ... old README, you are 100% right. I was thinking to develop a new web site :D perhaps a kind soul wanna help us with that
