### ISSUE TITLE
Can not add user

### ISSUE THREAD

**Issue by mhalp** [verdaccio/verdaccio#1970]
**Describe the bug**
The adduser command get the error npm ERR! Registry returned 407 for PUT on http://localhost:4873/-/user/org.couchdb.user:XX

**To Reproduce**
Working with npm behind proxy, running verdaccio according to the documentation

**Expected behavior**
Add a user

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
storage: ./storage
http_proxy: http://XX:YYYY@ZZZ
https_proxy: http://XX:YYYY@ZZZ
plugins: ./plugins

web:
  title: Verdaccio
auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

    access: $all
    publish: $authenticated
    unpublish: $authenticated

    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }

________________________________________________________

**Environment information**
  System:
    OS: Windows Server 2016 10.0.14393
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by juanpicado** [comment]
407 means https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407 , the error seems to be in your side.
