### ISSUE TITLE
No matching version found for some package.

### ISSUE THREAD

**Issue by cobolbaby** [verdaccio/verdaccio#1987]
**Describe the bug**

Occasionally, when installing some packages, you will encounter the following error:

```
(base)  ✘ cobolbaby@itc180012  /media/cobolbaby/data/ubuntu/opt/workspace/git/rpi-manager   S03F ●  npm i @vue/compiler-dom@3.0.2
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/compiler-dom@3.0.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cobolbaby/.npm/_logs/2020-10-28T01_48_42_538Z-debug.log
```

verdaccio storage:

![2020-10-28 09-58-52屏幕截图](https://user-images.githubusercontent.com/11460848/97381510-32eeb380-1904-11eb-8e98-0e23e0c68994.png)

verdaccio response:

![2020-10-28 09-59-18屏幕截图](https://user-images.githubusercontent.com/11460848/97381536-426dfc80-1904-11eb-872b-c25dea7f1c32.png)

**Comment by juanpicado** [comment]
Hello,

Well, not sure what to suggest. Could you build a set of reproducible steps ? Example repo. You might have external factors. Unfortunately the log provided does not says much.

**Comment by cobolbaby** [comment]
This problem occurs occasionally, and there is no clear way to reproduce it. 

However, when this problem occurs, you can see that the response code of verdaccio is 304. I am not sure which part of the request has the problem.

**Comment by jszejner** [comment]
I am seeing a similar issue and it seems to occur when the versions property in the storage/<PACKAGE_NAME>/package.json file is not populated at all. Populating this with values from registry.npmjs.org seems to allow downstream npm clients to work correctly.

**Comment by juanpicado** [comment]
> I am seeing a similar issue and it seems to occur when the versions property in the storage/<PACKAGE_NAME>/package.json file is not populated at all. Populating this with values from registry.npmjs.org seems to allow downstream npm clients to work correctly.

yeah, in your case seems the file was corrupted, I've seen that happening before.

**Comment by cobolbaby** [comment]
@juanpicado The bug is concentrated in the latest packages under @babel.

**Comment by juanpicado** [comment]
?? Could you elaborate your comment ?

**Comment by cobolbaby** [comment]
If the project depends on a dependent package of a different version, will the server return 304 response code?

**Comment by juanpicado** [comment]
> If the project depends on a dependent package of a different version, will the server return 304 response code?

The server only returns what the package manager ask for. The 304 only happens if the cache has not expired yet `eTag`.

Can we close this issue?

**Comment by cobolbaby** [comment]
Under normal circumstances, the last modification time of package.json of a package is the same as the creation time of the latest version of the package, but under abnormal conditions, these two values are different. 

This situation is the same as no rollback when the database transaction is abnormal.

**Comment by juanpicado** [comment]
Any way to reproduce this ?

**Comment by cobolbaby** [comment]
Temporarily unable to reproduce the problem stably.

**Comment by cobolbaby** [comment]
@juanpicado  After several verifications, it was found that the problem occurred when multiple uplinks were configured.

Ref: https://verdaccio.org/docs/en/packages#use-multiple-uplinks

**Comment by cobolbaby** [comment]
@juanpicado The previous conjecture is verified, this is a similar transaction problem.

The following is the information I captured the last time I encountered this problem.

![L_4D37 tmp](https://user-images.githubusercontent.com/11460848/117521758-0cf84900-afe2-11eb-9d32-a4c929a30695.PNG)

![2021-05-08 09-33-06屏幕截图](https://user-images.githubusercontent.com/11460848/117521575-159c4f80-afe1-11eb-9dd1-27c0ed89f1d4.png)

[cli-plugin-router.tar.gz](https://github.com/verdaccio/verdaccio/files/6444935/cli-plugin-router.tar.gz)

**Comment by cobolbaby** [comment]
When I executed the following command, I also encountered this problem. 

```
(base)  ✘ cobolbaby@itc180012  /tmp/demo  npm i --save --verbose @babel/types@7.14.4
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'i',
npm verb cli   '--save',
npm verb cli   '--verbose',
npm verb cli   '@babel/types@7.14.4' ]
npm info using npm@6.7.0
npm info using node@v11.14.0
npm verb npm-session db05d4415b559497
npm http fetch GET 304 http://npm.itc.inventec/@babel%2ftypes 111ms (from cache)
npm http fetch GET 304 http://npm.itc.inventec/@babel%2ftypes 72ms (from cache)
npm timing stage:rollbackFailedOptional Completed in 2ms
npm timing stage:runTopLevelLifecycles Completed in 223ms
npm verb type version
npm verb stack @babel/types: No matching version found for @babel/types@7.14.4
npm verb stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:101:11)
npm verb stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:43:18)
npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
npm verb stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm verb stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at processImmediate (internal/timers.js:443:21)
npm verb cwd /tmp/demo
npm verb Linux 4.15.0-142-generic
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save" "--verbose" "@babel/types@7.14.4"
npm verb node v11.14.0
npm verb npm  v6.7.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@7.14.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm verb exit [ 1, true ]
npm timing npm Completed in 518ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cobolbaby/.npm/_logs/2021-06-01T09_23_09_543Z-debug.log
```
Package related files stored on the server side:

[types.tar.gz](https://github.com/verdaccio/verdaccio/files/6575286/types.tar.gz)

Ps: In summary, I found that verdaccio always has problems pulling some packages released in the last one or two days

**Comment by cobolbaby** [comment]
@juanpicado 

Today I saw a reply https://github.com/verdaccio/verdaccio/issues/1854#issuecomment-867158431 from you. I finally realized the root cause of the issue. I set the `maxage` of the `npmjs` uplink to `7d`, which may cause problems when installing the latest package.

Please correct the description of `maxage` in [the official document](https://verdaccio.org/docs/en/uplinks#configuration). Obviously, the current description can easily cause some misunderstandings.

> the time threshold to the cache is valid

Finally, I want to confirm again whether the downloaded package has no expiration time?

**Comment by juanpicado** [comment]
> the downloaded package has no expiration time?

the tarball does not, only the `package.json` === metadata does expires. 

This is just a quick reply, I'll extend my thoughts later.
