### ISSUE TITLE
How configure verdaccio offline?

### ISSUE THREAD

**Issue by ceoaliongroo** [verdaccio/verdaccio#199]
I have a Web development in my office, all the developer has a network blocked to access directly to the NPM registry and get packages (Security Policy).  

I have the alternative to get the package from a computer with Internet and then pass through a file scanner, check it the files, and finally copy to the project.  I did a partial solution using npmbox but is difficult to support the frequently updates and did not get the devDependencies  

I tried verdaccio to proxy the NPM registry, get the npm modules to the project, and then disconnect the computer from internet (to simulate no internet enviroment) 

but verdaccio always check the registry in [http:\\registry.npmjs.org](#).

There is a way to use only the cache modules? (without connect to registry.npmjs.org)?

**Comment by juanpicado** [comment]
Have you tried to comment out `proxy: npmjs` to disable the uplinks in your config file?

**Comment by ceoaliongroo** [comment]
Works great! 

Thanks

**Comment by Buddikawidu** [comment]
Appreciated!

Thanks

**Comment by ZFHung** [comment]
how to add user in offline ?
