### ISSUE TITLE
Cleaning up storage folder

### ISSUE THREAD

**Issue by AlexShemeshWix** [verdaccio/verdaccio#200]
#### My reason:

> 	I want to be able to clean up storage folder. Along with package.json in it. Its ver bug , takes a lot of space during  backups and generally hard to manage.Ive tried to patch package.json manually. I removed keys for versions and _distfiles and _attachments in pacakge json.Strangely it made npm install procedure longer. Is there other configurationi files i need to be aware of?

**Comment by juanpicado** [comment]
Unfortunately no yet, that was proposed already here #142 and #132  I encourage you to follow and contribute there the discussion.
