### ISSUE TITLE
Package Version Limit for dependency's dependency

### ISSUE THREAD

**Issue by sorinmircioiu** [verdaccio/verdaccio#2004]
Hi @ayusharma,

You mentioned below that a maintainer has to define/publish versions very carefully and maybe use fix versions of the packages, and you're right.
But, if I'm using "css-loader": "3.6.0" fix version in package.json and a dependency's dependency is using "css-loader": "^3.6.0", what will be the installed version for "css-loader" in node_modules ? Probably a bigger version than "3.6.0" (if that's available) right ?

For PHP I'm using "Satis - For a full private Composer repo use Private Packagist" and there you can add fix versions without having the problem mentioned above.

What is your opinion on this ?

Hi @danbrianwhite,

Thanks for asking a question. I am not getting a clear picture of your requirements but as far as I understand: 

> I'm always frustrated by the NPM versioning process breaking builds. When a dependency's dependency updates because of a fuzzy version and breaks my application

I think as a maintainer you have to define/publish versions very carefully. You can keep the fix versions in that case.  https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-consumers

>  Alternatively, I would like to set specific dependency version limits within Verdaccio's web UI.

I think it is not the objective of npm registry, You publish some packages it serves them. Limiting them is another kind of thing.  It will require to develop a new project here. 

> Since I'm not as familiar with Verdaccio, is there currently way to add a plugin that would allow me to achieve this?

We have some plugins. You can find more here https://www.verdaccio.org/docs/en/dev-plugins 

> Would a custom middleware plugin allow me to limit this? Sounds like I can possibly restrict api calls based on version.

We have middleware functionality but It is not applicable here.

Please feel free to ask or discuss your issue in more depth.

_Originally posted by @ayusharma in https://github.com/verdaccio/verdaccio/issues/779#issuecomment-399777827_

**Comment by juanpicado** [comment]
hi @sorinmircioiu 

> But, if I'm using "css-loader": "3.6.0" fix version in package.json and a dependency's dependency is using "css-loader": "^3.6.0", what will be the installed version for "css-loader" in node_modules ? Probably a bigger version than "3.6.0" (if that's available) right ?

That would be a question for a package manager, Verdaccio does not resolve dependencies ranges, only obey the package manager.

The original request https://github.com/verdaccio/verdaccio/issues/779 was quite specific for an specific scenario and usually a plugin is recommended for such things unless the request gains public interest.

Verdaccio also has an experimental filter plugins that could help on this, you can search over the tickets.
