### ISSUE TITLE
Publishing fails with SocketTimeOut

### ISSUE THREAD

**Issue by SoubhagyaPrustyTR** [verdaccio/verdaccio#2009]
**Describe the bug**

We installed Verdaccio 3.0 via docker pull. And configured the storage path. Get request has been going well. The issue is with the PUT request while publishing through yarn. Put request for logging is a success but when it comes to package publish, the process fails. 

**To Reproduce**
[FOE:shared] ~/test_registry> yarn publish --registry http://<host>:4873 --verbose
yarn publish v1.22.5
verbose 0.208 Checking for configuration file "/home/foe/test_registry/.npmrc".
verbose 0.209 Checking for configuration file "/home/foe/.npmrc".
verbose 0.209 Found configuration file "/home/foe/.npmrc".
verbose 0.209 Checking for configuration file "/home/foe/.nvm/versions/node/v10.11.0/etc/npmrc".
verbose 0.209 Checking for configuration file "/home/foe/test_registry/.npmrc".
verbose 0.209 Checking for configuration file "/home/foe/.npmrc".
verbose 0.21 Found configuration file "/home/foe/.npmrc".
verbose 0.21 Checking for configuration file "/home/.npmrc".
verbose 0.211 Checking for configuration file "/home/foe/test_registry/.yarnrc".
verbose 0.212 Checking for configuration file "/home/foe/.yarnrc".
verbose 0.212 Found configuration file "/home/foe/.yarnrc".
verbose 0.212 Checking for configuration file "/home/foe/.nvm/versions/node/v10.11.0/etc/yarnrc".
verbose 0.212 Checking for configuration file "/home/foe/test_registry/.yarnrc".
verbose 0.212 Checking for configuration file "/home/foe/.yarnrc".
verbose 0.212 Found configuration file "/home/foe/.yarnrc".
verbose 0.213 Checking for configuration file "/home/.yarnrc".
verbose 0.215 current time: 2020-11-24T15:47:28.891Z
[1/4] Bumping version...
info Current version: 1.0.0
question New version:
[2/4] Logging in...
info npm username: foe
info npm email: foe@tr.com
question npm password:
verbose 3.589 Performing "PUT" request to "http://<host>:4873/-/user/org.couchdb.user:foe".
verbose 3.606 Request "http://<host>:4873/-/user/org.couchdb.user:foe" finished with status code 201.
success Logged in.
[3/4] Publishing...
verbose 3.622 Performing "PUT" request to "http://<host>:4873/test_registry".
verbose 33.633 Error: Couldn't publish package: "http://<host>:4873/test_registry: ESOCKETTIMEDOUT"
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at /usr/share/yarn/lib/cli.js:90467:13
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:323:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Couldn't publish package: "http://<host>:4873/test_registry: ESOCKETTIMEDOUT"
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.

This is the Linux host with RHEL OS.

**Expected behavior**

**Screenshots**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
/verdaccio/conf $ cat config.yaml
#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://github.com/verdaccio/verdaccio/blob/master/wiki/docker.md#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

**Environment information**

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Comment by juanpicado** [comment]
There no support for -> `We installed Verdaccio 3.0 via docker pull.`

**Comment by SoubhagyaPrustyTR** [comment]
Thanks, Which version will support then. We are migrating our servers. Our old system has 2.7.4 but when the node packages already present are configured with Verdaccio 4.0 with storage path, those are not visible on UI.

**Comment by juanpicado** [comment]
What is defined here. https://github.com/verdaccio/verdaccio/security/policy 

> but when the node packages already present are configured with Verdaccio 4.0 with storage path, those are not visible on UI.

There is info in the tickets, people got into the same issue, docker permissions issues.
