### ISSUE TITLE
`deprecated` field in package.json causes all old packages to be deleted at the time of publish

### ISSUE THREAD

**Issue by Amorites** [verdaccio/verdaccio#2017]
**Describe the bug**

If package.json in the project has a `"deprecated"` field, other versions of the package will be lost during publish.

**To Reproduce**

- add `"deprecated": "message"` in package.json
- bump version
- npm publish --registry localhost:4873

All the old packages are lost.

**Expected behavior**

At registry.npmjs.org:

- `"deprecated": false` will do nothing
- `"deprecated": "message"` will deprecate the current package (won't delete older packages)

**Screenshots**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

`master` branch of this repo

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:

npm info using npm@6.14.8
npm info using node@v12.19.0

 - `$ npm config get registry` prints:

**Comment by flavienbwk** [comment]
That's a huge issue for me

**Comment by juanpicado** [comment]
@flavienbwk Please if you give me your info and scenarios maybe we can move this on. The more info the better, reproducible uses cases.

**Comment by GravityMsc** [comment]
verdaccio 5.0.1
nodejs 14.17.4
npm 6.14.14

It seems I also found this problem.
I wanna upload all node_modules files to my personal registry, enter every folder to run `npm publish --ignore-scripts`. Sometimes it shows `bug the author...`. And I only see the latest version via website. But actually I can find all old versions from storage.

**Comment by juanpicado** [comment]
Check https://github.com/verdaccio/verdaccio/issues/2017 probably land on the v5.3.2

**Comment by juanpicado** [comment]
Fixed on https://github.com/verdaccio/verdaccio/releases/tag/v5.3.2

**Comment by jdmarshall** [comment]
So what version range was this issue effective on?  

Asking for a friend.
