### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound] - “Creative Commons license”

### ISSUE THREAD

**Issue by MrCull** [verdaccio/verdaccio#2018]
**Describe the bug**
The markup version of the readme that is displayed for the main page in this repo contains the following link:

“Creative Commons license”
Status code [404:NotFound] - Link: https://github.com/verdaccio/verdaccio/blob/master/LICENSE-docs

Looking in the files in the repo I’m not sure which one it should link to as I cannot see another relevant license file.

**To Reproduce**
Click the link

**Expected behavior**
Link should work

**Screenshots**
N/A

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
N/A

**Environment information**
N/A

**Debugging output**
N/A

**Extra**

This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fverdaccio%2fverdaccio
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=verdaccio

--

I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback, or long an “Issue”.

**Comment by juanpicado** [comment]
Verdaccio used `marked` for rendering the markdown, if there is an issue maybe you should report it there, we don't apply any special treatment to it.

**Comment by DanielRuf** [comment]
I guess this is meant:

<img width="993" alt="Bildschirmfoto 2020-12-06 um 22 57 09" src="https://user-images.githubusercontent.com/827205/101294241-659a9e80-3816-11eb-92e9-2f8084378c0d.png">

**Comment by DanielRuf** [comment]
Should be probably https://github.com/verdaccio/verdaccio/blob/master/LICENSE

You can fork and edit the file, create a commit and provide a PR for this @MrCull

<img width="986" alt="Bildschirmfoto 2020-12-06 um 22 58 57" src="https://user-images.githubusercontent.com/827205/101294295-b1e5de80-3816-11eb-9daa-08fdfb0b4ded.png">

**Comment by DanielRuf** [comment]
Mh, I guess this can be removed as the docs were moved to the website which is also MIT licensed.

You can fork and edit the file, create a commit and provide a PR for this @MrCull

<img width="986" alt="Bildschirmfoto 2020-12-06 um 22 58 57" src="https://user-images.githubusercontent.com/827205/101294295-b1e5de80-3816-11eb-9daa-08fdfb0b4ded.png">

See https://github.com/verdaccio/verdaccio/blob/master/docs/where-are-docs.md

https://github.com/verdaccio/website/blob/master/LICENSE

**Comment by juanpicado** [comment]
fixed https://github.com/verdaccio/verdaccio/commit/9b25761786b1beebc404b41403943280e994b74b 

Thanks @MrCull @DanielRuf
