### ISSUE TITLE
npm5 compatibility

### ISSUE THREAD

**Issue by dharapvj** [verdaccio/verdaccio#202]
Hello,

Does this software work with npm5? npm5 was released [last week](http://blog.npmjs.org/post/161081169345/v500).  There are whole bunch of changes in npm client about how to deal with caching. I hope verdaccio continues to run with npm5 without a hitch.

Also, since npm5 has brought several changes to how it perceives caching etc, does this project also needs to look at it's caching architecture to see if anything can be improved upon.

**Comment by juanpicado** [comment]
I've been testing the same day of the release and I haven't found any issue. The changes are mostly in the client side, the endpoints are the same. The unique potential change that could affect is (https://github.com/npm/npm/releases/tag/v5.0.0) the `integrity` field which as far I know, works perfectly. 

Currently `verdaccio` compares (https://github.com/verdaccio/verdaccio/blob/master/lib/local-storage.js#L272) based con the `sha` field whether a tarball exist or not, but, I only see that as an enhancement in case is need it.

 Unless someone report any issue, I do not see reason to do not move to `npm5` ( I did it already ). Caching is just as `yarn`, it's local. `verdaccio` provides more than that.

**Comment by dharapvj** [comment]
Thank you for quick revert and details.
