### ISSUE TITLE
crypt sha512 

### ISSUE THREAD

**Issue by adsftt** [verdaccio/verdaccio#203]
#### My reason:
I try to migrate from sinopia to verdaccio. But old passwd file not supported by  verdaccio
sinopia format:
````
asdf:$6$vVO4oZU9MTLCuQ==$pCqmSjyzQ6A87bSmPzpi9lJr1k0FhdxS/mIVSnw.m1Zcr5oxyy0mJg/aH7Bd1HBdYbKVWEDOV7WgKwltaAFLH/:autocreated 2017-05-29T12:26:53.424Z
here is new password format:
asdf:$6fJgmALoe/zg:autocreated 2017-05-29T12:27:49.830Z
````

it seems that `unix-crypt-td-js` doesn't support `sha512` with `$6$` id

#### Steps to reproduce:
1) adduser to sinopia
2) upgrade sinopia to verdaccio
3) try to auth

####  App Version:	
2.1.7

####  Config file:
auth:
  htpasswd:
    file: `/etc/verdaccio/htpasswd`

**Comment by juanpicado** [comment]
What do you mean with `$6$ id` ?

**Comment by juanpicado** [comment]
Also, from which version of sinopia are you migrating?

**Comment by adsftt** [comment]
sinopia-1.4.0

I mean $6$ part in salt.
glibc crypt supports additional encryption algorithms. Salt starting from $6$ should be hased by sha-512, but unix-crypt-td-js use DES.

**Comment by juanpicado** [comment]
@adsftt Unfortunately I think can't do anything about it,  have you tried to ask in their repository? https://github.com/TimDumol/unix-crypt-td-js, the unique reference I found about this is https://github.com/verdaccio/verdaccio/issues/106#issuecomment-277089207 .  The auth is a build-in plugin, but, soon will be a external one. You might use the `sinopia-htpasswd` instead the build-in and it should works.
