### ISSUE TITLE
long-term flakiness on install in github actions powered CI

### ISSUE THREAD

**Issue by JamesHenry** [verdaccio/verdaccio#2038]
**Describe the bug**

Hi there 👋 

Thank you for verdaccio, it's a fantastic tool.

I have been using it for quite a while now on `angular-eslint` and it has been hugely useful for me when builing out a realistic suite of integration tests.

However, in (github actions) CI it has been consistently flaky for months now. Errors like SOCKET TIMEOUT are particularly common.

It may well be that I have messed up the setup, and I apologies in advance if that is the case.

The good thing is this is OSS, so you have full access to the project and usage to be able to troubleshoot! (I know how hard it can be without that access). Please let me know if I can help in any way.

**To Reproduce**

Here is an example tiny PR showing the behaviour:
https://github.com/angular-eslint/angular-eslint/pull/261

And here you can see just how often it fails on master: https://github.com/angular-eslint/angular-eslint/commits/master

Often just a single re-run will resolve, but sometimes it takes a couple of goes.

It's starting to bug my OCD that master is often red just because of this verdaccio flakiness 😄  and it does result in PRs taking longer to merge than would otherwise be required (because of having to frequently rerun everything).

### NOTE: I have never been able to reproduce any of the failures locally

**Expected behavior**

It shouldn't ever fail to install the dependencies from verdaccio when they are valid.

**Screenshots**

All relevant files, config and usage are in the integration-tests package:
https://github.com/angular-eslint/angular-eslint/tree/master/packages/integration-tests

**Environment information**

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Comment by juanpicado** [comment]
hi, quick reply

I see -> https://github.com/angular-eslint/angular-eslint/blob/11782a2ba94e9f1ac684e0ed6436da9b183ae21f/packages/integration-tests/local-registry/config.yml

You would need check on this,
https://github.com/microsoft/react-native-windows/issues/6313#issuecomment-716207436
https://twitter.com/jotadeveloper/status/1331494081319624706

I have this setup in my own registry and performance has increased quite a lot recently, also enabled by default not while ago #2014
