### ISSUE TITLE
README symlink not displaying in Web UI

### ISSUE THREAD

**Issue by TheoryOfNekomata** [verdaccio/verdaccio#2040]
**Describe the bug**

README symlinks are not displaying in Web UI. Instead, a placeholder "ERROR: No README data found!" text is shown.

**To Reproduce**

- Create package with README/README.md as symlink to an existing file within said package.
- Publish.

**Expected behavior**
Contents of the target of the symlink will display on the Web UI.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/2346301/103205918-a11c1a80-4935-11eb-81a3-03f1ea3a668b.png)

**Environment information**

```
Environment Info:

  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
  Binaries:
    Node: 14.5.0
    Yarn: 1.22.4
    npm: 6.14.5
  npmGlobalPackages:
    verdaccio: 4.7.2
```

**Comment by juanpicado** [comment]
This is not a bug, verdaccio only displays what the package manager sends.
