### ISSUE TITLE
PM2 start failed

### ISSUE THREAD

**Issue by Brolly0204** [verdaccio/verdaccio#2044]
Hello all,

I am getting this error, verdaccio just crashed and no longer working after a server restart. When I try to pm2 start verdaccio , I get the following error

Error: Cannot find module '/home/ec2-user/verdaccio'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:53:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)

pm2 show verdaccio

│ name              │ verdaccio                                      │
│ restarts          │ 255                                            │
│ uptime            │ 0                                              │
│ script path       │ /home/ec2-user/verdaccio                       │
│ script args       │ N/A                                            │
│ error log path    │ /home/ec2-user/.pm2/logs/verdaccio-error-0.log │
│ out log path      │ /home/ec2-user/.pm2/logs/verdaccio-out-0.log   │
│ pid path          │ /home/ec2-user/.pm2/pids/verdaccio-0.pid       │
│ interpreter       │ node                                           │
│ interpreter args  │ N/A                                            │
│ script id         │ 0                                              │
│ exec cwd          │ /home/ec2-user                                 │
│ exec mode         │ fork_mode                                      │
│ node.js version   │ 7.10.0                                         │
│ watch & reload    │ ✘                                              │
│ unstable restarts │ 0                                              │
│ created at        │ N/A                             `
My config file is as follows:

storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
   'av-*':
      allow_access: $all
      allow_publish: $all

   '*':
      allow_access: $all
      allow_publish: $all
      proxy: npmjs

   '@*/*':
      allow_access: $all
      allow_publish: $authenticated
      proxy: npmjs

https:
  key: /home/ec2-user/verdaccio/verdaccio-keynew.pem
  cert: /home/ec2-user/verdaccio/verdaccio-certnew.pem
  ca: /home/ec2-user/verdaccio/server.ca

logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

listen:
- https://devnpm2:4873

max_body_size: 300mb

**Comment by juanpicado** [comment]
All good on this side, I'd ask `pm2` community then, I had been running for over two years with no issue.
