### ISSUE TITLE
Scoped packages cannot be installed using an apache proxy 

### ISSUE THREAD

**Issue by r3wald** [verdaccio/verdaccio#205]
I am using apache 2.2 as a proxy for verdaccio. This way I was unable to install any scoped package while other packages could be installed. The only suggested solution I could find was to add `@*/*` to my config.yaml. Without success.
But using a bare verdaccio I could install scoped packages.

That's actually a duplicate of #104 and possible #120.

Problem was the handling of slashes between npm and apache. When I try to install `@sailshq/lodash` npm generates an url which contains `@sailshq%2flodash`. Apache by default refuses to handle urls containing `%2f`.

Solution was to add `AllowEncodedSlashes NoDecode`. After I knew what I was looking for I found the documentation in SERVER.md.

I think you should emphathize this point a little bit more.

**Comment by juanpicado** [comment]
Thanks @r3wald  you are right, even for me sometimes is hard to locate stuff. I'll try to improve the documentation, refers to #198 . Do you have any suggestion about whether we should put all in readme and discard server.md ?

**Comment by juanpicado** [comment]
I pushed this new repository with the objective to test more easily this sort of issues 
https://github.com/verdaccio/docker-examples

**Comment by r3wald** [comment]
Hi,

I added a merge request. Please have a look at it. I hope this helps.

Thanks for you work!
Robert

**Comment by juanpicado** [comment]
Cool !! :) Thanks to you for the PR

**Comment by LayZeeDK** [comment]
How do I configure IIS proxy to support `npm info @scoped/package`?
