### ISSUE TITLE
Incomplete URL decoding.

### ISSUE THREAD

**Issue by samliddicott** [verdaccio/verdaccio#2088]
**Describe the bug**

If I make a request with a leading @, it may succeed, but if I urlencode the @ as %40 it will fail.
registry.npmjs.org will access %40 and decode it to @ but verdaccio will return a 404 error.

Some software (e.g. bitbake npmws fetcher) legitimately url encodes the @ to %40 and then fails with verdaccio but not registry.npmjs.org

**To Reproduce**

both work:
wget https://registry.npmjs.org/%40mapbox/geojson-types/-/geojson-types-1.0.2.tgz
wget https://registry.npmjs.org/@mapbox/geojson-types/-/geojson-types-1.0.2.tgz

only the second one works works (assuming the module is found):
wget https://test-vedaccio.local/%40mapbox/geojson-types/-/geojson-types-1.0.2.tgz
wget https://test-vedaccio.local/@mapbox/geojson-types/-/geojson-types-1.0.2.tgz

**Expected behavior**
%40 should be decoded to @. URL percent decoding should generally apply (RFC 3986)

> 6.2.2.2.  Percent-Encoding Normalization
> 
>    The percent-encoding mechanism (Section 2.1) is a frequent source of
>    variance among otherwise identical URIs.  In addition to the case
>    normalization issue noted above, some URI producers percent-encode
>    octets that do not require percent-encoding, resulting in URIs that
>    are equivalent to their non-encoded counterparts.  These URIs should
>    be normalized by decoding any percent-encoded octet that corresponds
>    to an unreserved character, as described in Section 2.3.

It's not normal for @ to be a special delimiting character in the path part of an http or https URL.

**Comment by juanpicado** [comment]
Seems fixed here https://github.com/verdaccio/verdaccio/pull/2193
