### ISSUE TITLE
Cannot pass Github action install stage after configuring yarn to use local registry

### ISSUE THREAD

**Issue by budarin** [verdaccio/verdaccio#2124]
**Describe the bug**
**To Reproduce**

- configure yarn to use local registry `yarn config set registry http://localhost:4873`
- install all dependencies
- pull request to Github
- got the error 
```
Run yarn install --production=true --non-interactive --frozen-lockfile
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "http://localhost:4873/commander/-/commander-4.1.1.tgz: connect ECONNREFUSED 127.0.0.1:4873".
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/raketa-web-app-boilerplate/raketa-web-app-boilerplate/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

**Expected behavior**
Expected to install all dependencies locally and in Github actions

**Comment by budarin** [comment]
I realized-this is a private repository only
I thought it was just a caching proxy

**Comment by jachstet-sea** [comment]
Which `pull request to Github` do you mean?
Verdaccio can act as both, a purely private repository and/or a caching proxy. It depends on use cases and configuration.
