### ISSUE TITLE
https behnid reverse proxy without headers

### ISSUE THREAD

**Issue by devnet-io** [verdaccio/verdaccio#2129]
I am attempting to run the docker container behind a reverse proxy where the certificates are terminated at the proxy and have ran into the issue described in the documentation here: https://verdaccio.org/docs/en/reverse-proxy. Verdaccio is making insecure requests to resources, such as `http://mydomain.com/-/static/940.a9eeba1cb9422cea1232.js.` With my current setup it is not possible to set the proxy headers as the docs suggest.

If possible it would be very helpful to allow one of the following: 

* Set a static domain/host in configuration that will be used for all resources.  For example setting this config option to `https://npm.mydoman.com/` would force Verdaccio to make requests such as `https://npm.mydomain.com.io/-/static/940.a9eeba1cb9422cea1232.js`
* A configuration option to force protocolless or relative paths. If this option was set Verdaccio would make requests such as `/-/static/940.a9eeba1cb9422cea1232.js` instead of including the domain.

**Comment by juanpicado** [comment]
>  With my current setup it is not possible to set the proxy headers as the docs suggest.

why not? if you explain your situation help to understand.

> Set a static domain/host in configuration that will be used for all resources. For example setting this config option to https://npm.mydoman.com/ would force Verdaccio to make requests such as

In the next major I am using this https://github.com/verdaccio/verdaccio/blob/5.x/docs/env.variables.md#verdaccio_public_url where you can override the static domain via environment variable. Is this what you meant?

> A configuration option to force protocolless or relative paths. If this option was set Verdaccio would make requests such as /-/static/940.a9eeba1cb9422cea1232.js instead of including the domain.

I don't get this, maybe provide an example.

**Comment by devnet-io** [comment]
> why not? if you explain your situation help to understand.

Essentially its a complex container orchestration setup with multiple levels of load balancing and proxying. I can provide a diagram of the details if its helpful.

> I don't get this, maybe provide an example

Say for example you are including a script tag. This would simply be using the tag like so, allowing for any protocol to work: 

```
<script type="text/javascript" src="/-/static/940.a9eeba1cb9422cea1232.js"> 
// or
<script type="text/javascript" src="//mydomain.com/-/static/940.a9eeba1cb9422cea1232.js"> 
```


> In the next major I am using this https://github.com/verdaccio/verdaccio/blob/5.x/docs/env.variables.md#verdaccio_public_url 

Yes, thank you! This is exactly what I'm looking for. Do you know when this version will go live?

**Comment by juanpicado** [comment]
I see, thanks for the feedback.

ok, it was planned for the next major but I'll include it here https://github.com/verdaccio/verdaccio/pull/2122 so stay tuned, most likely by end of the month.

I'll close this one and let's follow up here https://github.com/verdaccio/verdaccio/issues/1523

**Comment by devnet-io** [comment]
Perfect, looking forward to the update.

**Comment by juanpicado** [comment]
@devnet-io I would love to have your opinion here https://github.com/verdaccio/monorepo/issues/250 (last comment)

There are two possible configurations possible, trying to find the best one for the env variable.
