### ISSUE TITLE
Add "X-Forwarded-For" header value to the log file.

### ISSUE THREAD

**Issue by chronum** [verdaccio/verdaccio#215]
Since there is no built in module to limit a number of login requests in verdaccio, it makes sense to use some log parser to find and block client with too many incorrect login attempts.

Unfortunately in the case of "behind the reverse proxy" setup, only proxy's IP address is logged.
Since the proxy is capable of sending X-Forwarded-For HTTP header it would be nice to have it included in the logs too.

**Comment by Meeeeow** [comment]
Thanks for report, I will look into it.

**Comment by Meeeeow** [comment]
@chronum You should see this feature in next patch release

**Comment by juanpicado** [comment]
Done on 2.2.1
