### ISSUE TITLE
New and modern UI based on React

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#217]
We want to replace the old UI based on jQuery, there is no ui test, is hard to extend. This will add a new ui based on
* React (ui)
* Jest (test)
* Webpack (build)

Nothing fancy, just a simple UI that replicate the current one, but modern and easy to be tested.

**Comment by Meeeeow** [comment]
That's what i'm thinking last few days! We should add new api to check plugin enabled or not, so we can disable some entry from menu

**Comment by juanpicado** [comment]
Yeah, that is the idea  be able to extend the Ui with admin tools or perhaps new endpoints to display a package peer page and so on. I will take a look Ant Design ( it sounds familiar)

**Comment by juanpicado** [comment]
The new UI is ready at the branch `refactor-ui`. I will publish a tag soon to allow others test it as beta.

**Comment by Meeeeow** [comment]
It should be familiar, lol. Made by peoples at Ant Financial, a company of Alibaba Group.
Material design also good, except new Chrome settings page, really ugly.

BTW: callemall/material-ui, 100% Javascript, really unbelievable

**Comment by Meeeeow** [comment]
Here are some problem/question:

- Did you implement login feature? I can't find such code
- Why not use regular component with css-module? CSS embed in template string is difficult to write/debug/lint, if i'm not misunderstood something, styled-components is difficult to extend.
- `const` or `let`
- Magic! In Item.js, Line 74, I can't find define about `req`
- Move to class property, forget `Component.propTypes = ...` (https://github.com/tc39/proposal-class-fields)

**Comment by juanpicado** [comment]
@Meeeeow  

* Login is not ready yet 
* Just trying `styled-components` but as you said, hard to debug.
* `const` for requires and `let` just only for those variables will mutate.
* `req` my bad 👍 
* I have to read more about it :)

**Comment by Meeeeow** [comment]
I heard `styled-components` from our react native engineers at few days ago, maybe it's is a good tool for some "really small" component, if a component may need extend or customize in future, it should not use `styled-components`.

You can bind `this` with `class-fields` or call it `class property`, just like this: 
```js
class FooBar {
  someFunc = () => {
    // ...
  }
}
```
I just mean this feature can do this, to use this code must disable eslint `invalid-this` rule, which i don't wanna to do. i just use it define propTypes or state

**Comment by juanpicado** [comment]
@Meeeeow I PR #220 is gonna be easier to start a code review, feel free to create all reviews your consider appropriate

**Comment by stanleyxu2005** [comment]
Please use Bootstrap v4 instead of v3. It looks much better.

**Comment by juanpicado** [comment]
@stanleyxu2005 There is any React library using Bootstrap v4?

**Comment by stanleyxu2005** [comment]
@juanpicado I don't familiar with React (normally use Angular), I think Bootstrap is just a layout and visual component library. There are a lot of React libraries use Bootstrap. Current Verdaccio uses Bootstrap v3, so upgrade to v4 will not be quite difficult. (And this is an open source project, if the team is decide to use v4, I'd be glad to contribute some work to help)

**Comment by Meeeeow** [comment]
@stanleyxu2005 Also prefer Bootstrap v4, but @juanpicado already implement a preview version used material-ui, we have not decide use material-ui / ant-design or other library, any suggest?

**Comment by juanpicado** [comment]
@Meeeeow up to you to decide the UI library, I use at work (https://react-bootstrap.github.io/) but it's Bootstrap v3 still and they do not have a major release yet. I think for the small UI we have we could workaround Bootstrap v4 + CSS Modules, what do you think?

**Comment by Meeeeow** [comment]
@juanpicado https://github.com/reactstrap/reactstrap Here is another react ui library with Bootstrap v4, but... i will choose another one with 14k or 26k stars

**Comment by juanpicado** [comment]
Closing it, this was achieved already and works pretty good.
