### ISSUE TITLE
Integrate es6 transpiler like Babel or Typescript

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#219]
To build #217 and extendible to whole code base to avoid delays of implementation on es6 features (yeah we still support Node4,5 and 6)
 (it's gonna be needed by the UI, why don't use it for back-end and take advance of ES next features).

**Comment by Meeeeow** [comment]
Why not compile before publish it to npm? I don't think bundle compiler/transpiler with verdaccio is a good idea...

**Comment by juanpicado** [comment]
Yeah, that is the point, compile and then publish ES5.

**Comment by Meeeeow** [comment]
Good. I think i can refactoring current code (logger) to template string.

**Comment by juanpicado** [comment]
Yeah, please check the branch `refactor-ui`, there is a extreme make over of all api endpoints

**Comment by juanpicado** [comment]
Thanks for the help I really appreciate it :)

**Comment by juanpicado** [comment]
Babel 6 was the winner. Closing.
