### ISSUE TITLE
Config path of docker container can't be mapped

### ISSUE THREAD

**Issue by Disane87** [verdaccio/verdaccio#2196]
If I want to run verdaccio on my unraid server, I can't map the folders `/config/` to a host folder. If I want to map them, the container won't start. There are no logs.

The same occurs when I want to start the start the container on my Windows 10 system with WSL2 by following command:
```ps
docker run -it --rm --name verdaccio -p 4873:4873 -v C:\temp\verdaccio\conf:/verdaccio/conf -v C:\temp\verdaccio\storage:/verdaccio/storage -v C:\temp\verdaccio\plugins:/verdaccio/plugins  verdaccio/verdaccio
```

If I run the container without the port mapping, it starts flawlessly by this command:

```ps
docker run -it --rm --name verdaccio -p 4873:4873  verdaccio/verdaccio
```

The container should start with mapped `/config/` folder.
Unfortunatly there is currently nothing more I could share with you.

I guess there is something strange with the permissions itself. IMHO there are missing permission mappings for the `/config` at this line:

https://github.com/verdaccio/verdaccio/blob/b02dab1c2f8fc9c2e7cafe6510535ff491a7b1aa/Dockerfile#L44

Unfortunatly I'm not that docker expert to debug this.

**Comment by juanpicado** [comment]
Mmmm I wonder why https://github.com/verdaccio/verdaccio/blob/5.x/docker-examples/v4/reverse_proxy/nginx/relative_path/docker-compose.yml#L25 works fine.

**Comment by Disane87** [comment]
Could you reproduce it with the mentioned commands locally at your machine? Or is this only a problem at my machine?

**Comment by juanpicado** [comment]
@Disane87 I'll give it a try on windows and ubuntu. I'll post here my results when I'm done.

**Comment by Disane87** [comment]
> @Disane87 I'll give it a try on windows and ubuntu. I'll post here my results when I'm done.

ok  great, thank you in advance! :)

**Comment by Disane87** [comment]
Any updates on this? If not, how can I assist you to get a solution?

**Comment by juanpicado** [comment]
Please try with 

```
 docker run -it --rm --name verdaccio -p 4873:4873 -v 'C:\Users\xxx\projects\docker-example\:/verdaccio/confd/' -e DEBUG=* verdaccio/verdaccio:fix-docker-ps
```

**Comment by juanpicado** [comment]
If you add `-e DEBUG=verdaccio*` you will be able to see interesting debug code in the terminal

**Comment by Disane87** [comment]
> If you add `-e DEBUG=verdaccio*` you will be able to see interesting debug code in the terminal

Oh totally forgot it, shame on me. Will try it later :) enjoy Father's Day!

**Comment by Disane87** [comment]
Unfortunately it's nor working, neither on my windows nor on my unraid server. I tried it with your mentioned command:

> Please try with `verdaccio/verdaccio:fix-docker-ps`
> 
> ```
>  docker run -it --rm --name verdaccio -p 4873:4873 -v 'C:\Users\xxx\projects\docker-example\:/verdaccio/conf/' -e DEBUG=* verdaccio/verdaccio:fix-docker-ps
> ```
> 
> ;-) I had to install windows

Only a bit changed to use `C:\temp\verdaccio-docker`

On my unraid server it's not working too:
![image](https://user-images.githubusercontent.com/956158/118148896-4a5d3c00-b411-11eb-8c7f-1188a24526c9.png)

Used command (internally by unraid):
> docker run -d --name='verdaccio' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'DEBUG'='verdaccio*' -p '4873:4873/tcp' -v '/mnt/user/appdata/verdaccio/storage/':'/verdaccio/storage/':'rw' -v '/mnt/user/appdata/verdaccio/plugins/':'/verdaccio/plugins/':'rw' -v '/mnt/user/appdata/verdaccio/conf/':'/verdaccio/conf/':'rw' -it 'verdaccio/verdaccio:fix-docker-ps'
2b1b148ace2a9b891ce8fd884b9fd1efe2a760adc07692ebd8f87600f98a19e3

**Comment by juanpicado** [comment]
> verdaccio yaml parse failed +0ms

This means the config file was not found. I did manage to map the config on Windows 10 and works fine using the same script to shared (file within config file must be named `config.yaml`. Unfortunately I don't have RAID (I not even know what it is) so I cannot help there.

**Comment by Disane87** [comment]
Unraid is a server software for creating NAS/Server systems. It's cheap hypervisor :) 
But what I don't understand is why this image is running on your windows and not on mine? I use the same command to start the container :-(

**Comment by Disane87** [comment]
Just tested it again with your command on windows. It's not working when I want to map the conf folder. All other folders are ok.

**Comment by juanpicado** [comment]
> All other folders are ok.

🤔 https://github.com/verdaccio/verdaccio/pull/2249/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R50 

It's listed there, I wonder why does not work for you. Maybe someone else with Windows can give it a try @verdaccio/kubernetes @verdaccio/collaborators

**Comment by Disane87** [comment]
I guess this is a general issue since this even occurs on my unraid (linux machine) too. But this is totally against your observation that this fix is working on your windows machine. This is pretty strange.

**Comment by SL-CodeBlaster** [comment]
same issue for me also

**Comment by juanpicado** [comment]
> same issue for me also

Please try the custom tag image I posted above (possible fix)

**Comment by SL-CodeBlaster** [comment]
> > same issue for me also
> 
> Please try the custom tag image I posted above (possible fix)

you mean this?
`verdaccio/verdaccio:fix-docker-ps`

**Comment by Disane87** [comment]
> > > same issue for me also
> > 
> > 
> > Please try the custom tag image I posted above (possible fix)
> 
> you mean this?
> `verdaccio/verdaccio:fix-docker-ps`

yes

**Comment by SL-CodeBlaster** [comment]
already tried it.but didn't work

**Comment by Disane87** [comment]
@juanpicado which version of docker are you using? 
> Docker version 20.10.5, build 55c4c88

This is my version. Maybe an version issue?

BTW: My windows system was only a system to check if the problem is reproducable on other systems. The main system where it should run is a linux one.

**Comment by juanpicado** [comment]
> already tried it.but didn't work

share context please what command are you running and exact output, versions etc.

**Comment by juanpicado** [comment]
> @juanpicado which version of docker are you using?
> 
> > Docker version 20.10.5, build 55c4c88
> 
> This is my version. Maybe an version issue?
> 
> BTW: My windows system was only a system to check if the problem is reproducable on other systems. The main system where it should run is a linux one.

Docker version 20.10.6, build 370c289

**Comment by Disane87** [comment]
Wow, this is really pretty weird.

**Comment by juanpicado** [comment]
I just tried on a clean ubuntu installation, works for me using `verdaccio/verdaccio:latest`.  I'll double check in Windows 10.

<img width="802" alt="Screenshot 2021-05-15 231515" src="https://user-images.githubusercontent.com/558752/118378347-89d38600-b5d3-11eb-9888-dd5d955e4394.png">


```
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins
web:
  title: Verdaccio Docker
  primary_color: #444444
  darkMode: true
auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
server:
  keepAliveTimeout: 60
middlewares:
  audit:
    enabled: false
logs: { type: stdout, format: pretty, level: http }
````

**Comment by juanpicado** [comment]
Same in Windows with the same conf above (only config file)

<img width="1217" alt="Screenshot 2021-05-15 232752" src="https://user-images.githubusercontent.com/558752/118378632-6d384d80-b5d5-11eb-9945-82220d80ecff.png">

ok, that's my 0.5 cents, I'd suggest you check more in your side what's the problem.

**Comment by Disane87** [comment]
Thank you! Do you have the created `config.yaml` accessible under the given mapped folder?
Did you created the config file manually before you started the container or does this automagically happen?

I updated docker to the latest version on my windows only for reference) and the following command, it's one by one identical with yours (only the username is changed) is not working:
>  docker run -it --rm --name verdaccio -p 4873:4873 -v 'C:\Users\[username]\projects\verdaccio-docker:/verdaccio/conf' -e DEBUG=verdaccio* verdaccio/verdaccio
  verdaccio:logger setup logger +0ms
  verdaccio:logger logging stdout enabled +0ms
  verdaccio:logger has prettifier? true +1ms
  verdaccio yaml parse failed +0ms
  
  
![image](https://user-images.githubusercontent.com/956158/118378895-087df280-b5d7-11eb-9fd8-38fd998d6aee.png)

**Comment by juanpicado** [comment]
> Thank you! Do you have the created `config.yaml` accessible under the given mapped folder?
> 
> Did you created the config file manually before you started the container or does this automagically happen?
> 
> 
> 
> I updated docker to the latest version on my windows only for reference) and the following command, it's one by one identical with yours (only the username is changed) is not working:
> 
> >  docker run -it --rm --name verdaccio -p 4873:4873 -v 'C:\Users\[username]\projects\verdaccio-docker:/verdaccio/conf' -e DEBUG=verdaccio* verdaccio/verdaccio
> 
>   verdaccio:logger setup logger +0ms
> 
>   verdaccio:logger logging stdout enabled +0ms
> 
>   verdaccio:logger has prettifier? true +1ms
> 
>   verdaccio yaml parse failed +0ms
> 
>   
> 
>   
> 
> ![image](https://user-images.githubusercontent.com/956158/118378895-087df280-b5d7-11eb-9fd8-38fd998d6aee.png)
> 
> 

The file must be there.

**Comment by Disane87** [comment]
Aaaaah. I guess this is the issue. I actually anticipated this file would be created automatically. LIke the default config when you start it via npm.

And now it's working...

Would this be a good shot for the docker docs? I've read this section very carefully but I couldn't find a hint for this.

**Comment by juanpicado** [comment]
> Aaaaah. I guess this is the issue. I actually anticipated this file would be created automatically. LIke the default config when you start it via npm.
> 
> 
> 
> And now it's working...
> 
> 
> 
> Would this be a good shot for the docker docs? I've read this section very carefully but I couldn't find a hint for this.

:) be my guest repo 'verdaccio/website' hint: read contributions guideline.

**Comment by Disane87** [comment]
Here you go :)
https://github.com/verdaccio/website/pull/365

**Comment by Disane87** [comment]
@juanpicado You can consider this a closed. Thank you fpr your patience and assistance :)

**Comment by SL-CodeBlaster** [comment]
i have got it fixed after i added the config.yaml to my mapped folder, now i can't push the packages its' getting errors like that

on server 
```
 info --- auth/allow_action: access granted to: undefined
 info --- gihan is allowed publish for @sky/purets
 info --- auth/allow_action: access granted to: undefined
 info --- gihan allowed unpublish for @sky/purets
 http --- 404, user: gihan(182.172.22.49), req: 'PUT /@sky%2fpurets', error: no such package available
```
on Local
```
npm ERR! code E404
npm ERR! 404 Not Found - PUT http://skysoftlk.com:4873/@sky%2fpurets - no such package available
npm ERR! 404
npm ERR! 404  '@sky/purets@1.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gihan\AppData\Roaming\npm-cache\_logs\2021-05-16T07_37_24_457Z-debug.log
```

**Comment by SL-CodeBlaster** [comment]
`docker run -it --name verdaccio -p 487:4873 -v /home/gihan/verdaccio/conf/:/verdaccio/conf -v /home/gihan/verdaccio/storage/:/verdaccio/storage verdaccio/verdaccio`

**Comment by Disane87** [comment]
You should open a separate issue for your publish problem, since there is no connection between the startup problem and you current issue :)
