### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by AdrianoCahete** [verdaccio/verdaccio#22]
In "Installation" section, still shows sinopia.All Links points to siopia too.

**Comment by juanpicado** [comment]
It's looks like good now? After  ahttps://github.com/verdaccio/verdaccio/commit/fea001efcf7d99e99ef9e47d0e9341325a354494

**Comment by trentearl** [comment]
looks good to me, I reviewed it before i did the initial publish. There are still a few references but I think those should still be there. Feel free to disagree :)
