### ISSUE TITLE
Web UI and npm access isn't working in v5 with non-standard config file location

### ISSUE THREAD

**Issue by hybridherbst** [verdaccio/verdaccio#2204]
**Describe the bug**

- npm search hitting a Verdaccio v5 backend seems to return nothing. 
- Also, the Web UI is broken for me after updating from 4.12 to 5.0.
- My assumption is that something is now broken with config files that are not in /.config, but that's just a guess (seems to be the only specialty about our setup).

**To Reproduce**

- Have your configuration file in a non-standard location, such as /verdaccio/config.yaml, and use an `url_prefix`, e.g. `/my-prefix/`
- Run `verdaccio -c /verdaccio/config.yaml`
- From a local machine, run an npm search against that endpoint OR
- Open the Web UI

**Expected behavior**

- Web UI shows a list of packages
- npm search returns something

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (1) x64 Intel Xeon Processor (Skylake, IBRS)
  Binaries:
    Node: 14.16.1 - /usr/bin/node
    npm: 6.14.12 - /usr/bin/npm
  npmGlobalPackages:
    verdaccio: 4.12.0
```

**EDIT: WORKAROUND**
Seems one point not mentioned in the migration guide is that paths now need to be server-absolute, and can't be config-relative anymore. We previously had `./storage` as storage path, now needs to be `/absolute/path/storage`. The same is true for plugins.

A minor issue related to this: logo access from a server-absolute or config-relative path is both broken now.

**Comment by juanpicado** [comment]
> Also, the Web UI is broken for me after updating from 4.12 to 5.0.

https://verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide#troubleshooting

**Comment by juanpicado** [comment]
> npm search hitting a Verdaccio v5 backend seems to return nothing.

`npm search` works for me, but the `/-/all` endpoint or old search support was removed from `npm@7` here

https://github.com/npm/cli/commit/504384bbdc8b51d311f79da2d41d37f2e70ba933

So workaround use npm6 until `v1` endpoint is ready, or use `pnpm` latest which still support `all` endpoint.

**Comment by tholiebig** [comment]
The "logo" issue (not shown anymore) is still there. Any workaround for this in the meantime? Our page looks ugly now.

**Comment by juanpicado** [comment]
It is a open bug. No workaround yet. Hopefully next release will have a fix
