### ISSUE TITLE
Custom Logo from Filesystem Not Loading Behind ReverseProxy

### ISSUE THREAD

**Issue by 9ae8sdf76** [verdaccio/verdaccio#2206]
**Describe the bug**
When using a ReverseProxy that sets the `url_prefix` and setting `web.logo` to a file on the filesystem, the URI generated for the `<img src="...">` does not include the `url_prefix` and causes the image to not load. The URL for the logo is generated correctly, but not the URI for the image.

**Comment by juanpicado** [comment]
This should be fixed already.
