### ISSUE TITLE
【bug in v5.0.4】    DeprecationWarning: crypto.createDecipher is deprecated.

### ISSUE THREAD

**Issue by oscxc** [verdaccio/verdaccio#2215]
I login and 'GET /-/verdaccio/packages'，return [] array, but in fact, I have a package.

At the same time the server output:
 verdaccio[28760]: (node:28760) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.

I use nodejs v14.16.1, and I saw the documentation, crypto.createDecipher is deprecated.

**Comment by juanpicado** [comment]
hi @oscxc thanks for reporting, this has already been developed for the next major https://github.com/verdaccio/verdaccio/issues/1689

It was intended no to be introduced on v5 to avoid big breaking changes.

**Comment by oscxc** [comment]
Okey, go ahead!
