### ISSUE TITLE
local-storage leaks cached uplinked packages via search

### ISSUE THREAD

**Issue by favoyang** [verdaccio/verdaccio#2220]
**Describe the bug**

Local-storage leaks cached uplinked packages via search or the `/-/all` endpoints.

**To Reproduce**

The config.yml set up the uplink of npmjs for the `is-number` package.
```yaml
storage: ./storage
plugins: ./plugins
listen: 127.0.0.1:4873

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  'is-number*':
    access: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated

logs:
  - {type: stdout, format: pretty, level: trace}

experiments:
  search: true
```

Start the server.

Search for the is-number package - not found.
```bash
$ npm --registry http://127.0.0.1:4873 search is-number
No matches found for "is-number"
```

Fetch the is-number package info.

```sh
$ npm --registry http://127.0.0.1:4873 view is-number

is-number@7.0.0 | MIT | deps: none | versions: 15
...

$ find ./storage/
./storage/
./storage/.verdaccio-db.json
./storage/is-number
./storage/is-number/package.json

$ cat ./storage/.verdaccio-db.json
{"list":[],"secret":"..."}
```

Search for the is-number package - found the package.
```bash
$ npm --registry http://127.0.0.1:4873 search is-number
NAME                      | DESCRIPTION          | AUTHOR          | DATE        | VERSION  | KEYWORDS
is-number                 | Returns true if a…   | =undefined…     | prehistoric |          | cast check coerce coercion finite integer is isnan is-nan is-num is-number isnumber isfinite i
```

**Expected behavior**

Search and all endpoints shouldn't include content from uplinks. Other storage plugins like aws-s3-storage only search the database (verdaccio-s3-db.json), but the local-storage search of all files under the storage directory results in inconsistent behaviors.

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

See above.

**Environment information**

Verdaccio 5.0.4
```
Environment Info:
  System:
    OS: Linux 4.19 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    npm: 7.9.0 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Virtualization:
    Docker: 20.10.5 - /usr/bin/docker
```

**Debugging output**

```sh
 warn --- config file  - /home/favo/projects/verdaccio-test/server/config-fs.yaml
 warn --- ⚠️  experiments are enabled, we recommend do not use experiments in production, comment out this section to disable it
 warn ---  - support for search is enabled
(node:2207) Warning: deprecate: multiple logger configuration is deprecated, please check the migration guide.
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - http://127.0.0.1:4873/ - verdaccio/5.0.4
 http --- 127.0.0.1 requested 'GET /-/v1/search?text=is-number&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5'
(node:2207) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
 http --- 200, user: null(127.0.0.1), req: 'GET /-/v1/search?text=is-number&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5', bytes: 0/63
 http --- 127.0.0.1 requested 'GET /is-number'
 info --- auth/allow_action: access granted to: undefined
 info --- allowed access for is-number
 info --- making request: 'GET https://registry.npmjs.org/is-number'
 http --- 200, req: 'GET https://registry.npmjs.org/is-number' (streaming)
 http --- 200, req: 'GET https://registry.npmjs.org/is-number', bytes: 0/32181
 http --- 200, user: null(127.0.0.1), req: 'GET /is-number', bytes: 0/6770
 http --- 127.0.0.1 requested 'GET /-/v1/search?text=is-number&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5'
 http --- 200, user: null(127.0.0.1), req: 'GET /-/v1/search?text=is-number&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5', bytes: 0/614
```

**Comment by juanpicado** [comment]
Seems the same https://github.com/verdaccio/verdaccio/issues/1839

**Comment by favoyang** [comment]
> Seems the same #1839

Seems not. #1839 is about the access permission of search endpoints. But this issue is about the local-storage's search method implementation that didn't exclude cached uplinks packages.

local-storage goes through all files under the storage path to filter keywords. This includes the uplink cached contents.

https://github.com/verdaccio/monorepo/blob/36362ec77d8c12714467f597a8cbcf8acaae158f/plugins/local-storage/src/local-database.ts#L76:L87

Other storage plugins (aws-s3-storage) go through the package database to filter keywords. This excludes the uplink cached contents.

https://github.com/verdaccio/monorepo/blob/36362ec77d8c12714467f597a8cbcf8acaae158f/plugins/aws-s3-storage/src/index.ts#L89-L96

The inconsistent behavior also applies to the `/-/all` endpoint.

Because the internal search feature has a way to query uplinks, controlled by `options.req.query.local`. I assume the storage plugin should always exclude cached uplink contents. (Feedback is welcome).

https://github.com/verdaccio/verdaccio/blob/255650b91a747599408a509586e424f5b4ab6df2/src/lib/storage.ts#L367-L379

BTW local is always true in the current search endpoint implementation that disabled the uplink query feature.

https://github.com/verdaccio/verdaccio/blob/255650b91a747599408a509586e424f5b4ab6df2/src/api/endpoint/api/v1/search.ts#L54

**Comment by juanpicado** [comment]
Well, checking the code, there is nothing strange imho. It was just designed in such way and has never changed since sinopia. 
It stream from local and uplinks in order to search and while streams check if the viewer has access to see it in the final results.

The `all` endpoint with the header `referer: search xxx` which is basically the way they query and work just fine with `npm@6`, but does not with `npm@7` which only supports v1.

eg: 
```
curl -H "referer: search juan" -X GET https://registry.npmjs.org/-/all
```

About the `v1` search or the one flagged, it is incomplete, so I'd not even use it. 

I think there is no issue here, it is just how it works, the search endpoint does not download anything in your computer aside a json in the `.npm` cache with just names.

**Comment by favoyang** [comment]
It could be just the behavior of sinopia.

My point (for `v1` search) is the inconsistent behavior across different storage backends. I'm okay with either of the below,
- Search results return local packages only.
- Search results return local packages and all uplink content.
- Search results return local packages + cached uplink content. While this is the current behavior of the local storage backend, it feels a bit weird, but this can be a design choice as well.

What I don't like is that when I switch from one storage to another, the behavior suddenly changed. I think we need a standard here, just align with the web UI list which only consists of local packages as I remember.

**Comment by mbtools** [comment]
- `/-/all` was removed 
- `/-/v1/search` working properly 

![chrome_9HEs8u4dmQ](https://github.com/user-attachments/assets/ad2cb687-717e-45ec-8192-5a67d06e8624)

Closing
