### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#224]
#### My reason:

The original project had `WTFPL` and that's the current one in this project remains the same. Since that license is not listed in GitHub I wonder what kind of license this project should have.

* It should remains `WTFPL`? 
* It should we choose a compatible one according what Github list?

The new community tab ask to fill those fields. License is the most important for companies that decides to use `verdaccio` internally. I'm asking the community what do you think about it.

<img width="398" alt="screen shot 2017-06-19 at 8 55 30 pm" src="https://user-images.githubusercontent.com/558752/27300973-e8f4e856-5531-11e7-8523-8fc393ae687a.png">
<img width="858" alt="screen shot 2017-06-19 at 8 55 12 pm" src="https://user-images.githubusercontent.com/558752/27300974-e8fabc40-5531-11e7-9f39-ea518323e4f0.png">

**Comment by OmgImAlexis** [comment]
Personally I'd like to see this keep the `WTFPL` license to show that the fork is as open as the original.

**Comment by juanpicado** [comment]
@OmgImAlexis I'm wondering. Do you have any particular reason?

**Comment by Meeeeow** [comment]
Vote for GPLv3

**Comment by OmgImAlexis** [comment]
Changing the license to something more restrictive after it's been forked just feels "wrong".

**Comment by jmwilkinson** [comment]
If the licensing is changed, it should be to MIT. That keeps it pretty much as permissive from a practical standpoint and is a broadly accepted license.

**Comment by timothyswt** [comment]
@jmwilkinson is correct. If you want enterprise-level adoption, it needs to be MIT. companies like GM have very tight restrictions and don't even consider any OSS that is not Apache or MIT licensed.

**Comment by OmgImAlexis** [comment]
Why not a dual license then? Let the user choose between `WTFPL` or `MIT` or can `MIT` not be dual license?

**Comment by timothyswt** [comment]
What benefit does WTFPL have over MIT?

**Comment by jmwilkinson** [comment]
It's edgier?

**Comment by OmgImAlexis** [comment]
It's more over principal. Software shouldn't be forked and relicensed with a more restrictive license it goes against what the WTFPL is meant for.

**Comment by juanpicado** [comment]
A simple poll, vote with emojis reactions

👍 for MIT
❤️ for GPLv3
😄 for BSD
👎 I do not want to change the license
😕 Apache License

I wonder if this makes sense, but would be great to measure what people think without comment. This does not mean the winner will be the chosen one, it's just a thermometer.

**Comment by juanpicado** [comment]
It seems MIT is a popular alternative. Just recently Facebook is moving all to MIT. https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

Any thoughts against or in favor MIT?

**Comment by mlucool** [comment]
I am strongly in favor of moving away from WTFPL with 3.x. I disagree with @OmgImAlexis. MIT is more flexible because it is blessed as a license that is compatible with open source. WTFPL is not listed, so any open source project has to make a judgement call. See https://opensource.org/licenses/alphabetical for a list of licences which are approved. The lack of approval here is why Facebook moved to MIT.

**Comment by juanpicado** [comment]
I'm agreed with @mlucool, I think this project should be licensed as MIT
