### ISSUE TITLE
An error occurred while uploading the package

### ISSUE THREAD

**Issue by 1414044032** [verdaccio/verdaccio#2240]
**Describe the bug**
 When my package.json contains "deprecated": false, I will not be able to publish successfully

**To Reproduce**
1: Prerequisite: Verdaccio private server
2: Local `NPM init`
3: edit package.json file，add  "deprecated": false。like `{
  "name": "wlq-test",
  "version": "0.1.1",
  "main": "dist/zby-live-sdk.cjs.js",
  "module": "dist/zby-live-sdk.esm.js",
  "browsers": "dist/zby-live-sdk.umd.js",
  "scripts": {
    "build": "cross-env NODE_ENV=development npx rollup -c"
  },
  "bundleDependencies": false,
  "dependencies": {
    "axios": "^0.18.0",
    "debug": "^3.1.0",
    "md5": "^2.2.1",
    "pako": "^1.0.11",
    "pomelo-protobuf": "^0.4.0",
    "pomelo-protocol": "^0.1.6",
    "qs": "^6.9.4",
    "socket.io": "^2.1.1"
  },
  "deprecated": false,
  "description": "This is a live SDK for weclassroom.",
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.2.3",
    "cross-env": "^5.2.0",
    "rollup": "^1.1.0",
    "rollup-plugin-babel": "^4.0.3",
    "rollup-plugin-commonjs": "^9.1.6",
    "rollup-plugin-eslint": "^5.0.0",
    "rollup-plugin-json": "^3.0.0",
    "rollup-plugin-node-resolve": "^3.4.0",
    "rollup-plugin-replace": "^2.0.0",
    "rollup-plugin-uglify-es": "0.0.1",
    "rollup-pluginutils": "^2.3.1",
    "standard-version": "^4.4.0"
  },
  "license": "ISC"
}`
4. npm publish this package will fail。
5. when i remove `"deprecated": false` from package.json。it is will publish success.

**Expected behavior**
I think it should be uploaded successfully

**Screenshots**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
`#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

# url_prefix: /verdaccio/ 正式环境这个没有
web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: 10000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npm.taobao.org
    cache: false
packages:
  '@test*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    #publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incomming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enought.
server:
  keepAliveTimeout: 60

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

listen: 0.0.0.0:4872
max_body_size: 100mb
# log settings
logs:
  - { type: stdout, level: info }
  #- {type: file, path: verdaccio.log, level: info}

`

**Environment information**
 System:
    OS: Linux 3.10 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (64) x64 Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  npmGlobalPackages:
    verdaccio: 4.11.3

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Comment by juanpicado** [comment]
Please provide reproducible steps and if you can format the markdown the better.

**Comment by SL-CodeBlaster** [comment]
i have same issue
https://github.com/verdaccio/verdaccio/issues/2261

**Comment by juanpicado** [comment]
Please create a new ticket, **well documented**, I don't understand this one. Closing.
