### ISSUE TITLE
cross-domain issue

### ISSUE THREAD

**Issue by cobolbaby** [verdaccio/verdaccio#2275]
**Describe the bug**

You can get the list of private package when accessing the domain name of private server. But once you switch to the IP, the webpage shows that `No Package Published Yet.`, and the browser console indicates that there is a cross-domain problem.

**To Reproduce**

```bash
docker run -it --rm --name verdaccio -p 4873:4873 registry.inventec/proxy/verdaccio/verdaccio:5.1
npm adduser --registry http://cobolbaby.tj.inventec.com:4873
# create a private package
npm publish --registry http://cobolbaby.tj.inventec.com:4873/
```

**Expected behavior**

**Screenshots**

![2021-05-31 12-11-35屏幕截图](https://user-images.githubusercontent.com/11460848/120138579-4ef36400-c209-11eb-990e-0d915e16a3de.png)
![2021-05-31 12-11-44屏幕截图](https://user-images.githubusercontent.com/11460848/120138586-531f8180-c209-11eb-9430-da3dd057ce3f.png)

Ps: The thumbnail is blurry, please click on the thumbnail to view the original image.

**Environment information**

- version: 5.1.0

**Comment by A-aronYang** [comment]
I have the same problem and don't know how to solve it

**Comment by juanpicado** [comment]
>  But once you switch to the IP

The web only will rely in your server configuration, you won't be able to use something different that the domain you have setup

**Comment by gitn00b1337** [comment]
This stops our minikube build from working. Is there any work around?

**Comment by juanpicado** [comment]
Maybe this helps

https://verdaccio.org/docs/next/reverse-proxy#run-behind-reverse-proxy-with-different-domain-and-port
