### ISSUE TITLE
Uplink is offline?

### ISSUE THREAD

**Issue by fireflysemantics** [verdaccio/verdaccio#2278]
**Describe the bug**

If I try to install `del` using with Verdaccio running I get the following:

```
Oles-MacBook-Pro:NC oleersoy$ npm i del
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET http://localhost:4873/del/-/del-6.0.0.tgz - uplink is offline

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oleersoy/.npm/_logs/2021-06-04T02_06_36_689Z-debug.log
Oles-MacBook-Pro:NC oleersoy$ npm i del
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET http://localhost:4873/del/-/del-6.0.0.tgz - uplink is offline
```

If I switch to using NPM directly it works fine:

```
Oles-MacBook-Pro:NC oleersoy$ npm i del

added 20 packages, and audited 386 packages in 2s

16 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

```
Environment Info:
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    npm: 7.13.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.0.3
  npmGlobalPackages:
    verdaccio: 5.0.4
```

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Comment by fireflysemantics** [comment]
When I restarted verdaccio it fixed itself ...

**Comment by juanpicado** [comment]
That means when the proxy detects too many failures, you can increase the timeout or number of max fail. Check docs for it.

**Comment by njleonzhang** [comment]
version: 4.11.0

i tried to restart server or change some config, but no good luck. at last, i try to rename the storage folder, and then  issue is gone. after then i delete the new storage folder, and rename the previous storage back, everything is ok now.

```
// config.yaml

# path to a directory with all packages
storage: ./storage
```

```
mv ./storage ./storage1

# make the npm install, issue is fixed, but a new storage is generated, so u need rename previous back.
rm -rf ./storage
mv ./storage1 ./storage
```
