### ISSUE TITLE
Support searching by keyword via the search API

### ISSUE THREAD

**Issue by raygesualdo** [verdaccio/verdaccio#2307]
**Is your feature request related to a problem?**

Searching by keywords (e.g. `keywords:vscode`) is not currently supported by the `/-/v1/search` API endpoint. The lack of support is noted in [the source file](https://github.com/verdaccio/verdaccio/blob/3d45cecf04827712eb724a113e415dbda8ea2d90/packages/api/src/v1/search.ts#L26) (or [here in v5](https://github.com/verdaccio/verdaccio/blob/4fe8ddf7c705b27c362d96389dcade2534f323b4/src/api/endpoint/api/v1/search.ts#L74)).

**Describe the solution you'd like**

Ideally, searching by keyword works the same as it does with NPM.

**Describe alternatives you've considered**

I can search by strings that are in package titles, but it's not as precise.

**Additional context**

I'm willing to take a swing at adding this to both v5 and v6.

**Comment by juanpicado** [comment]
Great @raygesualdo , you might want to start with v5 (5.x branch), feel free to tag me for review.

**Comment by juanpicado** [comment]
After https://github.com/verdaccio/verdaccio/pull/2340 lands, will be easier to filter but whatever is required, keyword, etc etc, the whole `query` object is gonna be passed to the storage plugin.
