### ISSUE TITLE
same client config different registry(same verdaccio) will cache the first config and cannot cleanup

### ISSUE THREAD

**Issue by WindsonFF** [verdaccio/verdaccio#2374]
**Your Environment**
  
 * **verdaccio version**: v5.1.2
 * **node version** [12.x.x, 14.x.x]: v14.17.3
 * **package manager**: [npm@7, pnpm@6, yarn@2] 6.14.13
 * **os**: [mac, windows@10, linux] linux
 * **platform**: [npm, docker, helm, other] npm

**Describe the bug**

i've deploy a registry on an intranet linux server (ip: 192.168.**.*),and the server can access by a domain name (http://npm.*.*)
then i start the `verdaccio`. 

when i config the registry to  `http://npm.*.*` in `.npmrc`, then execute `yarn`, it will work, and in `yarn.lock`, it shows like this.
```
"name@^1.0.6":
  version "1.0.6"
  resolved "http://npm.*.*/name-1.0.6.tgz#eeca39f0a76edb54fa44c25326acb9b095c9c7b6"
```
but if i config the registry to `http://192.168.**.*`, in `yarn.lock`,it shows the same.

this will cause a problem. if i start the `verdaccio`,and on mac ,i config a intranet registry, 
the `verdaccio` server will memomize my mac.and if i leave the intranet environment and config `registry` to domain name. i execute `yarn` will get errors at end.
error message like this: `you can not access to http://192.168.**.*....tgz`.
**To Reproduce**

- start a verdaccio, and config to map to internet(or another intranet ip).
- config the registry to verdaccio's intranet ip. and execute `yarn`
- on same client,  execute `yarn cache clean -f`, remove  `node_modules`. rename `yarn.lock` to `yarn1.lock`
- on same client,  config registry to verdaccio's another ip (intranet or internet), then execute`yarn`
- compare `yarn.lock` and `yarn1.lock`, you will see ,they are equal.

**Expected behavior**

the lock file shows the tgz download url will equal to config registry.

**Screenshots, server logs, package manager log**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by WindsonFF** [comment]
when first get package with intranet.
<img width="565" alt="2" src="https://user-images.githubusercontent.com/11462711/129146381-1c31d786-0153-455d-9ef7-b88dbc8b1f92.png">
then use domain. it show the same intranet dist url.
<img width="779" alt="1" src="https://user-images.githubusercontent.com/11462711/129146501-230abee3-033f-43c5-8437-bd2d7f208392.png">

expected behavior:
<img width="583" alt="3" src="https://user-images.githubusercontent.com/11462711/129146567-9047915e-5d79-48e8-8f9a-7dbfda5a3cea.png">
<img width="538" alt="4" src="https://user-images.githubusercontent.com/11462711/129146576-a180dd50-5725-432a-9e03-dae0fbfc95eb.png">

**Comment by juanpicado** [comment]
hi @WindsonFF I understand your confusion, but that's not verdaccio issue. You might want to read 
https://medium.com/verdaccio/verdaccio-and-deterministic-lock-files-5339d82d611e

and in other words, if you don't want to deal with this issue use other package manager different than `npm`, for instance

* `pnpm` https://pnpm.io/
* yarn v2 or higher: https://yarnpkg.com/getting-started/install

**Comment by juanpicado** [comment]
> when first get package with intranet.
> <img alt="2" width="565" src="https://user-images.githubusercontent.com/11462711/129146381-1c31d786-0153-455d-9ef7-b88dbc8b1f92.png">
> then use domain. it show the same intranet dist url.
> <img alt="1" width="779" src="https://user-images.githubusercontent.com/11462711/129146501-230abee3-033f-43c5-8437-bd2d7f208392.png">
> 
> expected behavior:
> <img alt="3" width="583" src="https://user-images.githubusercontent.com/11462711/129146567-9047915e-5d79-48e8-8f9a-7dbfda5a3cea.png">
> <img alt="4" width="538" src="https://user-images.githubusercontent.com/11462711/129146576-a180dd50-5725-432a-9e03-dae0fbfc95eb.png">

To force different domain you can use env variables, check this out
https://verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide#a-new-public-url-environment-variable

**Comment by WindsonFF** [comment]
@juanpicado thks.

i've seen the code https://github.com/verdaccio/verdaccio/blob/2e995f5981c1a5eca6f43b14e52f06564acf6d8e/src/lib/utils.ts#L165
looks like this is cached. 
and when i change registry in client, is the `req.host` changed? and if it changed, then the `memoizedgetPublicUrl` maybe should not cache ?
