### ISSUE TITLE
API /verdaccio/package/readme/<package> ignores query "v"

### ISSUE THREAD

**Issue by Amorites** [verdaccio/verdaccio#2383]
**Your Environment**
  
 * **verdaccio version**: 5.1.0
 * **node version** [12.x.x, 14.x.x]:
 * **package manager**: [npm@7, pnpm@6, yarn@2]
 * **os**: [mac, windows@10, linux]
 * **platform**: [npm, docker, helm, other]

**Describe the bug**

https://registry.verdaccio.org/-/web/detail/verdaccio/v/2.3.3 display README of  5.x

**To Reproduce**

**Expected behavior**

https://registry.verdaccio.org/-/web/detail/verdaccio/v/2.3.3 display README of  2.3.3

**Screenshots, server logs, package manager log**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
Hi @Amorites 

Verdaccio only store the latest README, it is by design.
