### ISSUE TITLE
the published packages disappeared

### ISSUE THREAD

**Issue by A-aronYang** [verdaccio/verdaccio#2390]
the published packages disappeared

Sorry, I'm not a native speaker.
I have puslished one packge
![image](https://user-images.githubusercontent.com/52499709/130739129-4fde5ca2-1741-45a8-85f5-f150fe594ceb.png)

If I restart my linux , the packges I have published disappeared.
![image](https://user-images.githubusercontent.com/52499709/130738855-cb0a510e-ed7d-4d60-bd37-11abcf1dd364.png)

I don't know why it happend and how to config it
Please help me，If you see the question and thank you!

**Comment by pataar** [comment]
I have the same issue though. After upgrading to version 5 the packages seem to disappear. After downgrading back to 4, they come back.

**Comment by juanpicado** [comment]
> I have the same issue though. After upgrading to version 5 the packages seem to disappear. After downgrading back to 4, they come back. The log won't tell anything useful unfortunately.

https://verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide#after-upgrade-i-dont-see-packages-on-the-ui

**Comment by pataar** [comment]
Whoops, missed that one. Works like a charm, thanks!

**Comment by hellorayza** [comment]
> > I have the same issue though. After upgrading to version 5 the packages seem to disappear. After downgrading back to 4, they come back. The log won't tell anything useful unfortunately.
> 
> [verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide#after-upgrade-i-dont-see-packages-on-the-ui](https://verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide#after-upgrade-i-dont-see-packages-on-the-ui)

Not work. I can see my packages in the storage folder.

Question:
The published packages disappeared after the computer restarted.
I wonder if I posted to localhost:4873 but I can't login locahost:4873.


I tried a few tricks.
1. Use the absolute path to storage.
2. Add 
```
listen:
  - 192.168.xxx.xxx:4873  # or 0.0.0.0:4873
```

Environment:
```
windows11 22000.376
node v16.11.0
npm 8.0.0
pnpm 6.24.1
verdaccio v5.3.1
storage path: C:\Users\xxx\AppData\Roaming\verdaccio\storage
```

Any help is appreciated.

**Comment by genki** [comment]
Recently I have faced this issue too.
If you are using verdaccio via the Docker, there is a pitfall that you lost all data after each restart if you have mounted a volume not to `/verdaccio/storage` but  `/verdaccio`.

**Comment by tomosterlund** [comment]
I just experienced this too, that most of my releases were gone all of a sudden. I don't know what context data would help here, but:

1) I'm on v5.31.0, and
2) @juanpicado I would be willing to share more data, but am not quite sure what exact data would be needed here.

Will keep the old server with Verdaccio around for a few more weeks, so until then I can gladly share any context data if wanted.

**Comment by mbtools** [comment]
Please open a new [discussion](https://github.com/orgs/verdaccio/discussions). Share your config yml and how you are running Verdaccio (OS, docker y/n, which docker image).

**Comment by mbtools** [comment]
Also check the info in https://verdaccio.org/docs/configuration#.verdaccio-db
