### ISSUE TITLE
Does not work with npm 5 and node 8 (on the client)

### ISSUE THREAD

**Issue by sergeyjsg** [verdaccio/verdaccio#244]
Hello! I spend two days trying to launch verdaccio in docker. After failing I installed it through npm and ran with forever. Result always was the same. Commands `npm login` and `npm adduser --registry http://repo.myknowtions.com:4873` did not work. They just hang up. And hang up whole terminal so even `ctrl + c` did not work. Then I downgraded my node to v7 (so npm 4.2 was installed automatically) and everything just started to work without any changes to server side. 

With npm 4 I can see in server logs following entry when doing `npm adduser`: `http <-- 201, user: eqw, req: 'PUT /-/user/org.couchdb.user:eqw', bytes: 140/72`. With npm 5 this record does not appear.

So my question is: is there any plans to add npm 5 support?

**Comment by juanpicado** [comment]
`verdaccio` runs agains all Node version everyday, so, I doubt node 8 might be an issue. Have you tried with `yarn` ? It happens in all `verdaccio` versions or just the latest one? Do you have any `npm` log? 

refers to #202

**Comment by juanpicado** [comment]
It works for me locally and using the latest `Docker` build. It sounds as a local `npm` issue. I had that in the past, somehow, solved magically, but, it wasn't `verdaccio` related. But let's wait your feedback.

<img width="1403" alt="gh_209" src="https://user-images.githubusercontent.com/558752/27924292-0da29b42-6281-11e7-8aaf-415723c6cc70.png">

**Comment by Aigeec** [comment]
I have a sinopia install and it does not appear to work with npm 5 so I would imagine this is an issue for you too.

**Comment by juanpicado** [comment]
@Aigeec unless you provide a specific error, it's hard to prove. It works for me in the daily basis. Also you have to be aware the fast iteration of release `npm5` is having lately. They have fixed plenty of bugs. https://github.com/npm/npm/releases

**Comment by Aigeec** [comment]
Aye, was thinking it wasn't the most helpful comment. Booting up now to get
a bit more info. Like you say might all be resolved. A

**Comment by Aigeec** [comment]
Looks like you are correct that recent bug fixes seem to have resolved the issue.

Thanks A

**Comment by juanpicado** [comment]
Cool, then we can close the issue.
