### ISSUE TITLE
contributors list does not show when npm view is executed in a package

### ISSUE THREAD

**Issue by pranay06** [verdaccio/verdaccio#249]
#### My reason: 
When there are multiple publishers in a package then each user who is publishing the package should be logged somewhere and when 'npm view' is executed then it should show the same as it shows in the case of public npm.

When I try do 'npm view ." in the module dir then it gives this output.
 ```
{ name: 'first-try',
  versions: [ '1.0.0', '1.0.2', '1.0.3', '1.0.4', '1.2.0', '1.2.9', '1.3.0' ],
  'dist-tags': { latest: '1.3.0' },
  time: 
   { modified: '2017-07-10T07:54:26.056Z',
     created: '2017-07-06T14:29:01.879Z',
     '1.0.0': '2017-07-06T14:29:01.879Z',
     '1.0.2': '2017-07-06T14:30:13.456Z',
     '1.0.3': '2017-07-06T15:08:08.114Z',
     '1.0.4': '2017-07-06T15:09:07.791Z',
     '1.2.0': '2017-07-06T15:19:58.878Z',
     '1.2.9': '2017-07-10T07:45:52.948Z',
     '1.3.0': '2017-07-10T07:54:26.056Z' },
  version: '1.3.0',
  description: '',
  main: 'index.js',
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  author: '',
  license: 'ISC',
  dist: 
   { shasum: '1da965c03927d507680e3460553174905ec807c0',
     tarball: 'http://localhost:4873/first-try/-/first-try-1.3.0.tgz' } }
```

**Comment by juanpicado** [comment]
**Contributors** are not supported by any version, but, I think #221 will have a detail view of the package, so, there will be enough space to display them (ping @Meeeeow ), with the limited UI space right now is not that possible.

**Comment by juanpicado** [comment]
Verdaccio `3.x` already display contributors in the UI, so, as long the storage host that data, you are served.

<img width="371" alt="screen shot 2018-01-20 at 1 19 23 am" src="https://user-images.githubusercontent.com/558752/35177498-1b816eb0-fd80-11e7-9fc6-6f58db18d813.png">

in the other side, when you use a `npm/yarn` client, Verdaccio uses as a default storage (https://github.com/verdaccio/local-storage) a File-based system, which is quite limited and does not manage contributors list, but, it cache public packages including contributors. 

The simple solution here would create a custom storage plugin with more features than the default one, either a fork or a more complex File-based storage plugin.
