### ISSUE TITLE
modules could not be restricted access

### ISSUE THREAD

**Issue by pranay06** [verdaccio/verdaccio#250]
#### My reason:

I have been struggling to restrict the access of modules in my private npm registry setup using verdaccio.
I created a scoped npm module -  @pg/three
In the config file I mentioned the strickness 
	
	packages:
	  '@pg/*':
	    # scoped packages
	    access: $all
	    publish: $authenticated
Now other users are still been able to publish on this package. Moreover if I tried to restrict it explicitly
```
       npm access restricted @pg/three
    then I got this output
    npm ERR! registry error parsing json
	npm ERR! Linux 4.8.0-58-generic
	npm ERR! argv "/home/radical/.nvm/versions/node/v6.11.0/bin/node" "/home/radical/.nvm/versions/node/v6.11.0/bin/npm" "access" "restricted" "@pg/three"
	npm ERR! node v6.11.0
	npm ERR! npm  v3.10.10

	npm ERR! Unexpected token < in JSON at position 0
	npm ERR! <!DOCTYPE html>
	npm ERR! <html lang="en">
	npm ERR! <head>
	npm ERR! <meta charset="utf-8">
	npm ERR! <title>Error</title>
	npm ERR! </head>
	npm ERR! <body>
	npm ERR! <pre>Cannot POST /-/package/%40pg%2Fthree/access</pre>
	npm ERR! </body>
	npm ERR! </html>
	npm ERR! 
 ```
And after executing this I also tried to see the output on the server which hosts npm registry
```
http <-- 404, user: pranay(127.0.0.1), req: 'POST /-/package/%40pg%2Fthree/access', bytes: 23/340
```

node version - `v6.11.0`
npm version `3.10.10`

**Comment by juanpicado** [comment]
Have you read https://github.com/verdaccio/verdaccio/blob/master/wiki/packages.md ?

**Comment by pranay06** [comment]
Hi Juan, 
	I read it before also and I re-read it after your suggestion. But nothing was of much help.

	I have a few packages starting with pg (pattern pg-*). I want to have the ability to give the authIorization to only selected users to publish these packages
	So when I tried to use (Case-1)
		'pg-*':
		    access: $authenticated
		    publish: $authenticated
	Everybody was able to publish, no matter if I have given the permission to the users or not
	 
	When I tried this (case-2)
		'pg-*':
		    access: npmuser
		    publish: npmuser
	Even I (username: pranay) wasn't able to publish the content itself

	When I tried to publish a scoped package ex- @pg/one (case-3), I changed the config file like this
		'@pg/*':
			access: npmuser
			publish: npmuser
	Now only I was able to publish and nobody else was able to publish. In this case when I tried to add owner ( npm owner add kaktawanamit @pg/three) to one package then I could not able to do it, error-log file has been attached. And this user does exist.

	I would be glad if you could help me to achieve what I told. I must be not doing some step in desired manner to get the results.

	Thanks
	Pranay

**Comment by juanpicado** [comment]
@pranay06 could you follow this guide to format properly your message ? https://guides.github.com/features/mastering-markdown/ it's really hard to read.

**Comment by pranay06** [comment]
@juanpicado  thanks for pointing it out. I have formatted the same comment.

**Comment by juanpicado** [comment]
@pranay06 `npm owner add` is not supported unfortunately https://github.com/verdaccio/verdaccio#compatibility

About being selective to allow some users to access packages. Have you tried?
https://github.com/verdaccio/verdaccio/blob/master/wiki/packages.md#set-multiple-groups
```yaml
'@pg/*':
   access: npmuser user1 user2 user3
  publish: npmuser user1 user2 user3
```

**Comment by pranay06** [comment]
Thanks a ton Juan. This worked. 
I thought these values( npmuser user1 user2) are groups in the registry since it was termed - set multiple groups and I could not find the way to create groups in verdaccio.
Correct me if I am wrong, I believe one needs to ask the admin of this registry to change this in the config file of verdaccio  whenever  there is a need to change these permissions for any module since a normal user might not have access to it.

**Comment by juanpicado** [comment]
@pranay06 the current auth plugin is quite limited, actually if you see in detail the source code says clearly what I quoted below. 

https://github.com/verdaccio/verdaccio/blob/master/wiki/packages.md#usage

> All users recieves all those set of permissions independently of is anonymous or not plus the groups provided by the plugin, in case of htpasswd return the username as a group. For instance, if you are logged as npmUser the list of groups will be.

> Correct me if I am wrong, I believe one needs to ask the admin of this registry to change this in the config file of verdaccio whenever there is a need to change these permissions for any module, since a normal user might not have access to it.

So, in short the answer is a big **yes**. In the way this was coded it works like that. You will have to change manually and restart verdaccio using that plugin. 

If you need something something more advanced, you can look in the plugin list (https://github.com/verdaccio/verdaccio/blob/master/wiki/plugins.md) perhaps there is something you like it. I personally recommend the (https://github.com/nowhammies/verdaccio-activedirectory) LDAP plugin which is suitable to organizations.

I hope this helps you.

**Comment by pranay06** [comment]
This is of great help. Thanks Juan.
