### ISSUE TITLE
using verdaccio as a cache

### ISSUE THREAD

**Issue by fr0** [verdaccio/verdaccio#256]
Is there a way to configure verdaccio as a read-through cache for the public npm repo?

Basically, I want to set my registry to it, and then any time I do `npm install`, I want it to use the verdaccio private registry. If the module it's trying to install isn't in the private registry, then I want it to be automatically added to the private registry.

Based on the README, it seems like it should do this, but I've already installed a few packages, and the verdaccio web frontend still says "No Packages".

**Comment by juanpicado** [comment]
Let me see whether I understood correctly. You want to use `verdaccio` as proxy and when you run `npm install --registry xxxx` in your project all those downloaded packages should be displayed in the verdaccio UI?

**Comment by fr0** [comment]
Yes, that's exactly what I want. I thought that was what it did by default, but I think I've misunderstood.

**Comment by Meeeeow** [comment]
Maybe we can add refresh interval for package? @juanpicado 
Such as skip read package info from upstream for package download < 1 day (configurable)
if we always read local package, the registry will "disconnect" from upstream, not able to get latest version of package

**Comment by juanpicado** [comment]
Exactly is what @Meeeeow  said, what @fr0 is asking is not possible.
1. I would not make sense replace https://npmjs.com or https://yarnpkg.com/
2. The index system won't be able to handle such amount of packages along the time, currently only index local packages, so, it requires more than a normal File System to handle GB of packages in memory.

I do not get this @Meeeeow 

> Maybe we can add refresh interval for package? @juanpicado
Such as skip read package info from upstream for package download < 1 day (configurable)
if we always read local package, the registry will "disconnect" from upstream, not able to get latest version of package

**Comment by fr0** [comment]
Perhaps I should clarify my requirements. My organization wants to be able to guarantee that we can build our software any time, even if npmjs is down or defunct. That includes having guaranteed access to the specific versions of the libraries we depend on.

As a side goal, I'd like to provide an on-site local cache of the 3rd party libraries we use for performance reasons, so our developers can do `npm install` without waiting as long.

Can I use verdaccio to accomplish either of these goals?

**Comment by fr0** [comment]
Perhaps I should be using this instead:  https://github.com/heikkipora/registry-sync

**Comment by juanpicado** [comment]
`verdaccio` caches all packages/dependencies in the local storage. For instance if you run `npm install react`,  it will cache react and his inner dependencies. **It caches all, local and external dependencies.** 

If you set up property the uplinks https://github.com/verdaccio/verdaccio/blob/master/wiki/uplinks.md#configuration should work like a charm. 

The unique incident reported with offline is #223 which will be solved soon. I've worked in my quite large organization for a while with 0 incidents related to offline issues.

You can do a dummy test in your computer:

1. Run `verdaccio`
2. Clean `~/.npm/` 
3. Clean `./node_modules`
4. Install `npm install --registry http://localhost:5555/`
5. Go offline
6. Clean `~/.npm/` 
7. Clean `./node_modules`
8. Install `npm install --registry http://localhost:5555/`

All should be installed with any issue. You might see some errors in `verdaccio` console, but that's normal, just a notification the `uplink` is down.

I hope that helps.

**Comment by fr0** [comment]
I got it to work -- thanks for your help.
The only remaining problem is that the Web UI doesn't show cached packages, but it sounds like that is intended behavior. If you agree that it is intended and don't want to change that behavior, we can close this issue.

**Comment by juanpicado** [comment]
@fr0 yes, that's an intended behaviour since since the very beginning at sinopia.  The default local storage system is quite limited. In the roadmap there is a #169 to improve the plugin system, that will helps to switch to different storage systems and thus cache whatever you want 🚀  .

**Comment by Meeeeow** [comment]
@juanpicado Verdaccio will try get package info from `upstream`/`uplink` in every request, if there is a options allow user set `refresh interval`, package install will be super fast, the `refresh interval` mean don't try get package info from `uplinks`

**Comment by juanpicado** [comment]
@Meeeeow sounds like a good improvement, can you create a ticket with more details?
