### ISSUE TITLE
Anonymous publish

### ISSUE THREAD

**Issue by Corporalis** [verdaccio/verdaccio#258]
Is there any way to allow anonymous/unauthenticated publishing of packages?
I've tried the following settings in the general packages ('*') section of the yaml file:

```
publish: $anonymous 
```
and 
```
publish: $all
```
 However I always get the same authorization error:
> need auth auth required for publishing

I have no issues with adding a user and subsequently publishing packages, but I seem to be unable to publish as an anonymous user. Given that this instance is in a locked down network (no internet access), there is a requirement to investigate allowing any user to publish a package. Any ideas welcome.

**Comment by Meeeeow** [comment]
It's a limit of npm, impossible to publish as anonymous, but you can open register then everyone have permission to `npm adduser`

**Comment by juanpicado** [comment]
Yeah, you have to fake a token in the `.npmrc`. Look at the closed issues there is an example over there.

**Comment by Corporalis** [comment]
Ahh... thank you very much for that.

**Comment by juanpicado** [comment]
yw, thanks for asking :)

**Comment by juanpicado** [comment]
FYI: `yarn` allow anonymous publish.
