### ISSUE TITLE
Verdaccio is generating the same API token for a given user.

### ISSUE THREAD

**Issue by manast** [verdaccio/verdaccio#2619]
**Your Environment**
  
 * **verdaccio version**: 5.2.0
 * **node version** [12.x.x, 14.x.x]:
 * **package manager**: [npm@7, pnpm@6, yarn@2]
 * **os**: [ linux]
 * **platform**: [AWS EC2]

Using ```npm token create``` always generates the same token.

**To Reproduce**

Just call npm token create several times.

**Expected behavior**

Every call to ```npm token create``` should generate a new unique token.

**Screenshots, server logs, package manager log**

contents of  ```.token-db.json```:

```
cat storage/.token-db.json
{
  "manast": [
    {
      "user": "manast",
      "token": "PM3Vt...g0ee9",
      "key": "01fe6e66aa59cedab36150a38d26a879",
      "cidr": [],
      "readonly": false,
      "created": 1635827752701
    },
    {
      "user": "manast",
      "token": "PM3Vt...g0ee9",
      "key": "01fe6e66aa59cedab36150a38d26a879",
      "cidr": [],
      "readonly": false,
      "created": 1635827757611
    },
    {
      "user": "manast",
      "token": "PM3Vt...g0ee9",
      "key": "01fe6e66aa59cedab36150a38d26a879",
      "cidr": [],
      "readonly": false,
      "created": 1635827762253
    },
}
```

Not only is the same token generated always for the same user, but the token itself is truncated, not sure how it is the validation performed with this, normally you salt-hash the token and use that for validation. The "key" itself is a standard MD5 sum which is not safe for authenticating purposes.

As far as I can tell, the culprit is in getAPIToken: https://github.com/verdaccio/verdaccio/blob/13310814da60e7f9113347f1ab5529dcc10fd80d/packages/auth/src/utils.ts#L115

It seems like it is generating the token based on the username and the user's encripted password :/. So the question is why it works in this way and what implications it would have if we generate a random generated token here?

```ts
export async function getApiToken(
  auth: TokenEncryption,
  config: Config,
  remoteUser: RemoteUser,
  aesPassword: string
): Promise<string | void> {
  debug('get api token');
  const { security } = config;

  if (isAESLegacy(security)) {
    debug('security legacy enabled');
    // fallback all goes to AES encryption
    return await new Promise((resolve): void => {
      resolve(auth.aesEncrypt(buildUser(remoteUser.name as string, aesPassword)));
    });
  }
  const { jwt } = security.api;

  if (jwt?.sign) {
    return await auth.jwtEncrypt(remoteUser, jwt.sign);
  }
  return await new Promise((resolve): void => {
    resolve(auth.aesEncrypt(buildUser(remoteUser.name as string, aesPassword)));
  });
}
```

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

It is a default config.yaml.

**Environment information**

```
Environment Info:
  System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
  Binaries:
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.1/bin/npm
  npmGlobalPackages:
    verdaccio: 5.2.0
```

**Contribute to Verdaccio**

- [x] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
@manast it is by design in v5, the reason is due the algorithm used for the default legacy token signature. It was improved for v6 here https://github.com/verdaccio/verdaccio/pull/1953 . As a workaround please use JWT token signature instead.
