### ISSUE TITLE
JSON logs do not hydrate template placeholders

### ISSUE THREAD

**Issue by edclement** [verdaccio/verdaccio#2649]
### Discussed in https://github.com/verdaccio/verdaccio/discussions/2286

<div type='discussions-op-text'>

<sup>Originally posted by **capps1994** June 11, 2021</sup>
We have updated our Verdaccio instance, to 5.1.0 and now logging seems to be not working as expected.

In our logs we see `{"level":25,"time":1623421647904,"pid":8,"hostname":"e643fb945f2c","request":{"method":"GET","url":"/-/verdaccio/packages"},"user":null,"remoteIP":"172.18.0.1","status":304,"bytes":{"in":0,"out":0},"msg":"@{status}, user: @{user}(@{remoteIP}), req: '@{request.method} @{request.url}', bytes: @{bytes.in}/@{bytes.out}"}`

We have the following in our config `logs:`
  `- { type: stdout, format: pretty, level: http }`

Has anything changed?
  </div>
<br>

@juanpicado I was in the process of opening a PR against `master` (for Verdaccio 6) but it looks like the unit tests for `packages/logger` are busted as are a number of other unit tests for other packages. I read the [Contributing Guidelines](https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md) and followed the instructions for [_Running test_](https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#running-test) but continue (even after some troubleshooting) to receive errors:
```text
packages/logger test$ cross-env NODE_ENV=test BABEL_ENV=test jest --runTestsByPath
│ FAIL test/logger.spec.ts
│   ● Test suite failed to run
│     Cannot find module '@verdaccio/core' from 'test/logger.spec.ts'
│     > 1 | import { warningUtils } from '@verdaccio/core';
│         | ^
│       2 |
│       3 | import { logger, setup } from '../src';
│       4 |
│       at Resolver.resolveModule (../../node_modules/.pnpm/jest-resolve@27.3.1/node_modules/jest-resolve/build/resolver.js:324:11)
│       at Object.<anonymous> (test/logger.spec.ts:1:1)
│ -----------|---------|----------|---------|---------|-------------------
│ File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
│ -----------|---------|----------|---------|---------|-------------------
│ All files  |       0 |        0 |       0 |       0 |
│  index.ts  |       0 |        0 |       0 |       0 |
│  logger.ts |       0 |        0 |       0 |       0 | 7-156
│ -----------|---------|----------|---------|---------|-------------------
│ Test Suites: 1 failed, 1 total
│ Tests:       0 total
│ Snapshots:   0 total
│ Time:        1.612 s
│ Ran all test suites within paths .
└─ Failed in 2.4s
packages/plugins/active-directory test$ cross-env NODE_ENV=test BABEL_ENV=test jest
[2 lines collapsed]
│     Cannot find module '@verdaccio/core' from 'tests/active-directory.test.ts'
│       1 | import ActiveDirectory from 'activedirectory2';
│       2 |
│     > 3 | import { HTTP_STATUS } from '@verdaccio/core';
│         | ^
│       4 |
│       5 | import ActiveDirectoryPlugin, { NotAuthMessage } from '../src/active-directory';
│       6 | // eslint-disable-next-line jest/no-mocks-import
│       at Resolver.resolveModule (../../../node_modules/.pnpm/jest-resolve@27.3.1/node_modules/jest-resolve/build/resolver.js:324:11)
│       at Object.<anonymous> (tests/active-directory.test.ts:3:1)
└─ Running...
```

I listed only 2 of the failing packages in the output above (`logger` package included) but there there were a few others with the same exact issue related to *`Cannot find module '@verdaccio/core' from <some_other_package>`*. As mentioned, I spent some time trying to troubleshoot but I'm not intimately familiar with Verdaccio's build process/configuration or `pnpm` in general.

I have a fix for the issue from the discussion but don't want to submit the PR without working unit tests. Any guidance that can be provided would be appreciated. Thanks.

**Comment by juanpicado** [comment]
🤔 maybe you could upload the branch, I see the package is defined correctly on the manifest, but a close look would help.

**Comment by edclement** [comment]
I figured it out, I didn't do a build against the full project. Thanks.
