### ISSUE TITLE
Param web.title from config.yaml does not work on docker image

### ISSUE THREAD

**Issue by leoloko** [verdaccio/verdaccio#265]
#### My reason:

I just updated from version 2.2.5 to 2.3.1 and the title configured in config file is not shown.

#### Steps to reproduce:

Just open the the localhost:4873

####  App Version:	

2.3.1

####  Config file:	

web:
  title: 'My Custom Title'
storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}

#### Additional information:

The config file above is not formatted, the real file is formatted properly.

#### Additional verbose log:

N/A

**Comment by juanpicado** [comment]
The new UI doesn't support it, we have to develop it again. I'll put in the queue. Thanks for report it.

**Comment by juanpicado** [comment]
I'll be fixed in the next patch version
