### ISSUE TITLE
Implementing functionality like unpkg.com

### ISSUE THREAD

**Issue by RogueRonin** [verdaccio/verdaccio#267]
Not everyone will think this makes sense for a private repository since you would then make them publicly available.
But I'd like to think that it would add value.

I personally use unpkg for quick projects so I don't have to go through the whole build process setup or for small packages I want to include as a whole and don't need them to integrate in the build process, like I often do with http://blazecss.com/ for example.

url could be something like this then `verdaccio.local/unpkg/repo@1.0.1`, but would of course be customizable.

**Comment by Meeeeow** [comment]
I don't think it's easy to implement @juanpicado 
First, allow public access any package as a CDN server may cause abuse by other people(huge bandwidth)
And, if we allow public access to private package, it's not private anymore.

**Comment by juanpicado** [comment]
I think is out of scope of this project. I'll let it open for while and see if anyone want to share his thoughts.

**Comment by wenerme** [comment]
This is very helpful, consider the browser now support import esm, if verdaccio provide unpkg/jsdeliver like cdn access, can easily do full esm dev based on verdaccio's repo.

**Comment by andi4000** [comment]
> This is very helpful, consider the browser now support import esm, if verdaccio provide unpkg/jsdeliver like cdn access, can easily do full esm dev based on verdaccio's repo.

Hey thanks for the hint, I found https://esm.sh and it seems to provide the functionality of unpkg, plus the benefit of self-hosting!
