### ISSUE TITLE
Plugin Generator page is missing

### ISSUE THREAD

**Issue by hybridherbst** [verdaccio/verdaccio#2676]
**Describe the bug**

Plugin Generator page https://verdaccio.org/docs/plugin-middleware/plugin-generator is missing (linked from https://verdaccio.org/docs/plugin-middleware/#generate-an-middleware-plugin)

**To Reproduce**

Go to https://verdaccio.org/docs/plugin-middleware/#generate-an-middleware-plugin and click on the "plugin generator" link.

![image](https://user-images.githubusercontent.com/2693840/142047142-5ea2a4f2-e094-420a-acd9-bbe9ff3c8af6.png)

**Comment by juanpicado** [comment]
Plugin generator is deprecated, too much work for maintain and I couldn't find anyone take care of it. We should update docs.

**Comment by juanpicado** [comment]
@hybridherbst I cannot reproduce. Anyway I just changed my mind and I updated the generator.
