### ISSUE TITLE
Is there an option to auto reload `conf/config.yaml`?

### ISSUE THREAD

**Issue by loynoir** [verdaccio/verdaccio#2680]
**Is your feature request related to a problem?**
Emm, not a problem, but inconvenience. After update upstream registry, or said `uplinks`, within `conf/config.yaml`, need to restart docker container.

**Describe the solution you'd like**
Watch `conf/config.yaml` and reload, so no need to restart relatively heavier docker container.

**Describe alternatives you've considered**
Maybe restful api for CLI to restart verdaccio?

**Additional context**
Day1 on verdaccio. How! verdaccio is very amazing! 👏

**Comment by juanpicado** [comment]
No, it is not possible. It has been asked before but you might want workaround with `nodemon` if you like.

**Comment by loynoir** [comment]
I inspect into docker, but seems docker version verdaccio have no nodemon. Anyway, thanks for your reply. 😃

**Comment by juanpicado** [comment]
I understand, there was a PR https://github.com/verdaccio/verdaccio/pull/1775 which kind of seek the same request.
