### ISSUE TITLE
Markdown anchor links in package readMe.md broken

### ISSUE THREAD

**Issue by coolsp** [verdaccio/verdaccio#2712]
**Your Environment**

 * **verdaccio version**: 5.2.2
 * **node version**: 14.18.1
 * **package manager**: yarn@1.22.15
 * **os**: mac
 * **platform**: npm, docker

**Describe the bug**

Anchor links in `readMe.me` rendered by the UI use a wrong base URL.
E.g.:
For module `mysample` in private registry `@peter`, local test URL would be: 
`http://localhost:4873/-/web/detail/@peter/mysample`.
Markdown `[Sample](#sample)` resolves to `<a href="http://localhost:4873/#sample">Sample</a>` instead of `<a href="http://localhost:4873/-/web/detail/@peter/mysample#sample">Sample</a>`

This can't be fixed by adding `baseUrl` as option to `marker` seen `marker` does not add `baseUrl` to non origin independent URL's.

**To Reproduce**

Add a link in the package `readMe.md` (e.g.; `[Sample](#sample)`) and observe how this is rendered when viewing the package using the web-ui.

**Expected behavior**

When clicking the anchor link, view should jump to that section in the `readMe.md`

**Screenshots, server logs, package manager log**

- Not relevant

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

- Not relevant

**Environment information**

- Not relevant

**Debugging output**

- Not relevant

**Contribute to Verdaccio**

- [x] I'm willing to fix this bug 🥇 

I'll create a PR shortly.

**Comment by juanpicado** [comment]
@coolsp  https://www.npmjs.com/package/verdaccio/v/5.3.0
