### ISSUE TITLE
Incorrect definition of Package interface in public @verdaccio/types

### ISSUE THREAD

**Issue by koteisaev** [verdaccio/verdaccio#2719]
**Your Environment**
 * **verdaccio version**: 5.2.2
 * **node version** [14.18.1]:
 * **package manager**: [npm 6.14.15]
 * **os**:[windows 11]
 * **platform**: [all platforms, starting verdaccio as part of larger system, not CLI]

**Describe the bug**

In the `@verdaccio/types` the `Package` has property defined as `GenericBody` while it really `string/number` according to Verdaccio internal types.

**To Reproduce**

1. install `@verdacco/types`
2. import `Package` from `@verdaccio/types`
3. Write a code e. g. to serialize the Package object to Datastore or load it back.

**Expected behavior**

the properties of exposed types in `@verdaccio/types` must be same as same exposed types  used within verdaccio core.

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

This issue does not scoped to specific settings in config

**Environment information**

This issue affects development experience.

**Comment by juanpicado** [comment]
Hi @koteisaev thanks for the report, I would imagine you are using the latest published package but I wonder if you have checked https://github.com/verdaccio/verdaccio/tree/master/packages/core/types which is newer (and  I hope better) and (not compatible with v5) rather with the future v6.

Not sure what's the usage you are doing but would be great to know more.

**Comment by koteisaev** [comment]
Hello! Thanks for reply.
I implementing a standard integration in a corporate environment.
I added a mini-plugin for auth, using our private auth API, and added a storage plugin to store packages in our private google cloud DB and bucket.
I had also wrap the real verdaccio with an express-based "proxy" whose sole purpose is to override the url path from `/some/prefix/to/npm` into just `/` - because I can not just say with `url_prefix` that all requests, including from NPM CLI, should be at that `/some/prefix/to/npm` . The `http-proxy-middleware` npm package helped with this a lot, making this proxy literally a one-liner.

Such requirement for this behavior for `url_prefix` to be applied to all requests even to 
```
PUT /@scope/package-name
``` 
 comes from fact that for security reasons we can not expose repository existence at dns level with domain like `npm.example.com` 
Only with this mini-proxy I was able to achieve verdaccio (5.x.x) to accept package requests at proper urls (with `url_prefix` applied) there, without updating `verdaccio` internals.

BTW I guess that problem I reported seems to start to happen when I tried first to integrate not `verdaccio` package but rather `@verdaccio/core` or `@verdaccio/server` with being pubished `@verdaccio/types` referenced.

So for now the published `@verdaccio/types` compatible only with published `verdaccio` package.

**Comment by juanpicado** [comment]
`@verdaccio/core` or `@verdaccio/server` both are 6.x and are alpha, not suitable for production environments.  It can be a bit confusing now because the project is in a phase of refactoring migration to packages, while 5.x only few packages are still living https://github.com/verdaccio/monorepo.

```
@verdaccio/types@10.0.1 | MIT | deps: none | versions: 105
verdaccio types definitions
https://verdaccio.org

keywords: verdaccio, typescript, types

dist
.tarball: https://registry.npmjs.org/@verdaccio/types/-/types-10.0.1.tgz
.shasum: 40e281aaf3737c92b909115a9b9095b012bb6a48
.integrity: sha512-ValRhRpY8aKehcTrA6QypU2n3Wg2PEtEKDWBlA4FeDWD0CzBvuyCDc0Sm055wMX0836DIqBibDcnxyIJwCRm/w==
.unpackedSize: 37.8 kB

maintainers:
- sergiohgz <sergio@sergiohgz.eu>
- verdaccio.npm <verdaccio.npm@gmail.com>
- jotadeveloper <juanpicado19@gmail.com>
- ayusharma <ayush.aceit@gmail.com>

dist-tags:
6-next: 11.0.0-6-next.9  feat-token: 6.2.0        next: 8.0.1-next.1
beta: 5.0.0-beta.4       latest: 10.0.1
```
The compatible version with `5.x` is `10.0.x` at this point.

**Comment by juanpicado** [comment]
Somehow, the version `10.0.x` is just a TypeScript module.

```
declare module '@verdaccio/types' {
...
```

which can be override with declaration merging strategies https://www.typescriptlang.org/docs/handbook/declaration-merging.html as far I know.

**Comment by juanpicado** [comment]
Types were refactored with several improvements:
- v5 https://github.com/verdaccio/monorepo/pull/581
- v6 https://github.com/verdaccio/verdaccio/pull/3308

I consider this ticket outdated, so closing it.
