### ISSUE TITLE
Fail to npm install in docker when using nightly-master (extend base docker image)

### ISSUE THREAD

**Issue by matiboy** [verdaccio/verdaccio#2738]
**Your Environment**
 * **verdaccio version**: nightly-master (docker)
 * **node version** [12.x.x, 14.x.x]: 14.18.1
 * **package manager**: [npm@7, pnpm@6, yarn@2]: npm 6.14.15
 * **os**: [mac, windows@10, linux] Ubuntu on WSL2
 * **platform**: [npm, docker, helm, other] docker

**Describe the bug**

Unable to run npm install in nightly-master docker. 

**To Reproduce**
Run docker build for the following Dockerfile

```Dockerfile
FROM verdaccio/verdaccio:nightly-master

USER root

ENV NODE_ENV=production

RUN npm install --verbose
RUN npm install verdaccio-aws-s3-storage

```

**Expected behavior**

Installs successfully.
Note: it works when using older docker images (verdaccio:4)

**Environment information**

N/A (doesn't reach that stage)

**Debugging output**

Docker build output (from the npm install --verbose part)

```
#4 0.394 npm info it worked if it ends with ok
#4 0.395 npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install', '--verbose' ]
#4 0.395 npm info using npm@6.14.15
#4 0.396 npm info using node@v14.18.1
#4 0.396 npm verb config Skipping project config: /opt/verdaccio/.npmrc. (matches userconfig)
#4 0.573 npm verb npm-session 5cbd7daf9aa3a6ff
#4 0.613 npm info lifecycle verdaccio-dev@~preinstall: verdaccio-dev@
#4 1.233 npm timing stage:loadCurrentTree Completed in 619ms
#4 1.237 npm timing stage:loadIdealTree:cloneCurrentTree Completed in 4ms
#4 1.323 npm timing stage:loadIdealTree:loadShrinkwrap Completed in 85ms
#4 1.325 npm timing stage:rollbackFailedOptional Completed in 0ms
#4 1.325 npm timing stage:runTopLevelLifecycles Completed in 734ms
#4 1.414 npm verb stack Error: Unsupported URL Type "workspace:": workspace:*
#4 1.414 npm verb stack     at unsupportedURLType (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:200:15)
#4 1.414 npm verb stack     at fromURL (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:258:13)
#4 1.414 npm verb stack     at Function.resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:77:12)
#4 1.414 npm verb stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:493:20
#4 1.414 npm verb stack     at Array.map (<anonymous>)
#4 1.415 npm verb stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:492:47
#4 1.415 npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
#4 1.415 npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
#4 1.415 npm verb stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
#4 1.416 npm verb stack     at Promise._settlePromiseCtx (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:611:10)
#4 1.416 npm verb stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:142:12)
#4 1.416 npm verb stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
#4 1.416 npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
#4 1.417 npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
#4 1.417 npm verb stack     at processImmediate (internal/timers.js:464:21)
#4 1.417 npm verb cwd /opt/verdaccio
#4 1.418 npm verb Linux 5.4.72-microsoft-standard-WSL2
#4 1.419 npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
#4 1.419 npm verb node v14.18.1
#4 1.419 npm verb npm  v6.14.15
#4 1.420 npm ERR! code EUNSUPPORTEDPROTOCOL
#4 1.431 npm ERR! Unsupported URL Type "workspace:": workspace:*
#4 1.431 npm verb exit [ 1, true ]
```

**Comment by matiboy** [comment]
Works even with `latest` just not `nightly-master`

**Comment by juanpicado** [comment]
Extend `nightly-master` still not working fine, since we use `pnpm` and at least me I haven't worked on making it stable. 

I would recommend don't use `nightly-master` until having a stable v6 version, but I was planning to work on this soon. But some help is also welcome.

**Comment by juanpicado** [comment]
See https://github.com/verdaccio/verdaccio/tree/master/docker-examples/v6/plugins

**Comment by jweyrich** [comment]
Had a similar problem today. I ran verdaccio on Docker using `docker run -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio` and then just tried to `npm i express --registry http://localhost:4873/` right away. It failed with the following message:

> [... lots of lines removed for brevity]
> npm http fetch GET 200 http://localhost:4873/@typescript-eslint%2fparser 376ms (cache revalidated)
> npm http fetch GET 200 http://localhost:4873/eslint 90ms (cache revalidated)
> npm timing idealTree Completed in 3769ms
> npm timing command:i Completed in 3785ms
> npm ERR! code EUNSUPPORTEDPROTOCOL
> **_npm ERR! Unsupported URL Type "workspace:": workspace:*_**
> npm timing npm Completed in 3969ms

FWIW, I'm running Docker version 20.10.16, build aa7e414.

**Comment by juanpicado** [comment]
@jweyrich 

```
npm timing idealTree Completed in 3769ms
npm timing command:i Completed in 3785ms
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```
This seems to be a client side error, how do you find related with the docker image?

**Comment by jweyrich** [comment]
Indeed. Looks like a problem on my npm client. Sorry for bothering you.

**Comment by juanpicado** [comment]
> Indeed. Looks like a problem on my npm client. Sorry for bothering you.

No worries, :) happy to help.
