### ISSUE TITLE
Package GONE after update new release Verdaccio

### ISSUE THREAD

**Issue by jk-jx** [verdaccio/verdaccio#276]
I updated to Verdaccio latest version yesterday and my package I uploaded last time are gone to nowhere which I couldn't found. Is this a bug or it happened everytime I update Verdaccio. Someone please help me solve this. Thanks. :)

**Comment by dylanb124** [comment]
This may be irrelevant, but have you tried running `npm dist-tag ls [<pkg>]`? ([See documentation](https://docs.npmjs.com/cli/dist-tag)) This will list the tags of your NPM package, and the latest versions on each. I recently updated Verdaccio and recall reading about changes regarding how Verdaccio handles tagging. I could see a package seemingly vanishing from the UI perspective depending on how it was tagged.

**Comment by juanpicado** [comment]
@jk-jx could you elaborate a bit more? eg: steps, config file, log etc etc

**Comment by Meeeeow** [comment]
Did you run verdaccio with pm2 cluster mode?

**Comment by jk-jx** [comment]
After I installed Verdaccio in my server, I had publish a few package for job purpose. After a few days, I noticed that there's a new update for Verdaccio, so I decided to update. After I updated, all my package I uploaded before had gone. So is that you guys have any solutions to solve this issue?

**Comment by Meeeeow** [comment]
@jk-jx 

We fixed a danger behavior that may cause data loss with: #306, not release yet

If you are experiencing same issue, it's not possible to recover database, at the same time, your npm will auto logout because either database and secret was destroyed. But your packages still store in you disk.

**Comment by jk-jx** [comment]
@Meeeeow I know it's not possible to recover. But the problem is, in future if I update my Verdaccio, impossible I need to republish the package again and again what.

**Comment by Meeeeow** [comment]
@jk-jx This will not happen again in the future release

**Comment by jk-jx** [comment]
@Meeeeow actually where did the package all store? because I wanna do some backup for it.

**Comment by juanpicado** [comment]
I released `v2.4.0` please try again and let us know whether fix your issue

**Comment by Meeeeow** [comment]
@jk-jx For Linux/Unix, default storage path is `~/.config/verdaccio/storage`, for Windows, default storage path is "%appdata%/verdaccio"
