### ISSUE TITLE
PUT 413 error on publishing package 

### ISSUE THREAD

**Issue by darkowic** [verdaccio/verdaccio#277]
#### My reason:

When trying to publish my package, I receive 413 entity too large error
```
$ npm publish
npm ERR! publish Failed PUT 413
npm ERR! code E413
npm ERR! request entity too large : package-name

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dariusz/.npm/_logs/2017-08-01T12_39_31_616Z-debug.log
```

Our verdaccio server runs under nginx server. I checked and maximum body size on nginx size is 50 MB, so it's not the problem.

From supervisor logs I can find verdaccio logs:
```
http <-- 413, user: darkowic(XXX.XXX.XXX.XXX via 127.0.0.1), req: 'PUT /package-name', error: request entity too large
```
So, it is for sure verdaccio server error.

For smaller package it was working well.

#### Steps to reproduce:

Big enough package and just publish the package. My `dist` directory size is 4,3 MB.

####  App Version:	
2.3.1 - newest one

**Comment by darkowic** [comment]
I forgot to add:
In settings/wiki/config I didn't find anything about server configuration (It runs on express server). There is no API/cli to modify express server :confused:

**Comment by darkowic** [comment]
I found in express bodyParser documentation that the limit for json parser is 100kB - https://github.com/expressjs/body-parser
Then this error should not be related to package size.

**Comment by darkowic** [comment]
Just tried with very small package and everything works fine.

**Comment by juanpicado** [comment]
You can set the limit setting the following in your config file


```yaml
max_body_size: 1000mb
````
This is not documented properly as far I can see in the code. I'll document it.

**Comment by darkowic** [comment]
@juanpicado I confirm that this solves the problem. Thanks!

**Comment by darkowic** [comment]
Btw in my case, it was my mistake in the end. After publishing, I checked the size of the package and it was 30MB (!?). The problem was that I accidentally publish package with `node_modules_sth` because I changed the name of `node_modules` when I switch between branches to avoid installing everything again.

**Comment by Meeeeow** [comment]
We are happy to see your problem was solved ;-)

**Comment by radubrehar** [comment]
Just for future reference, I got the same exact issue, but adding `max_body_size` did not help since I was using an NGINX proxy. The problem was with the nginx defaults, and adding
`client_max_body_size 50M` to the http section in the nginx configuration, like below:

```
http {
    client_max_body_size 50M; # allows file uploads up to 50 megabytes
    [...]
}
```
solves the problem.

So if anyone hits this error, make sure you try to adjust both the nginx and the verdaccio configs.

**Comment by juanpicado** [comment]
Could tou PR that to wiki section?
