### ISSUE TITLE
Mention the origin of verdaccio on the readme

### ISSUE THREAD

**Issue by lope** [verdaccio/verdaccio#278]
#### Verdaccio was suggested to me and I did not realize that it's a fork of Sinopia and I had no idea where it came from after reading the readme.

I expect that many people who have been using Sinopia will want to move to a project that is maintained. 

The fact that Verdaccio has a completely different name means it's not obvious that it's a fork of Sinopia. The Github title also doesn't show this etc.

So a simple solution would be to add one line, something like:

------------------------------------------

**The origin of verdaccio**
We were using the great project [rlidwka/sinopia](https://github.com/rlidwka/sinopia/) which became [unmaintained](https://github.com/rlidwka/sinopia/issues/376) so we started Verdaccio, the name Verdaccio is related to Sinopia, see [here](https://github.com/rlidwka/sinopia/issues/376#issuecomment-205904763).

**Comment by juanpicado** [comment]
At the very beginning it was a fork but we asked Github to detach to have more visibility at the web and Github itself.

There is a reference to Sinopia at the Readme first line :)

**Comment by juanpicado** [comment]
Sinopia means 

> Sinopia (also known as sinoper, named after the Turkish city Sinop) is a dark reddish-brown natural earth pigment, whose reddish colour comes from hematite, a dehydrated form of iron oxide.

and Verdaccio means

> Verdaccio is an Italian name for the mixture of black, white, and yellow pigments resulting in a grayish or yellowish (depending on the proportion) soft greenish brown.

So, at the end there is a bit of similarity after all :)

**Comment by juanpicado** [comment]
Oh, I did not read your last paragraph

**Comment by lope** [comment]
Hey @juanpicado thanks buddy. Sorry, I missed that first line of the README.md. But it's nice for people to know where verdaccio came from :)

**Comment by juanpicado** [comment]
Sure, @lope  do you think we can improve that in some way?
