### ISSUE TITLE
Suggestion to state the compatibility with rlidwka/sinopia

### ISSUE THREAD

**Issue by lope** [verdaccio/verdaccio#279]
As one of (possibly many) people who will likely start using your fork instead of the original, the only real question on my mind when I read your readme (which was not answered) is: **Will verdaccio work as a drop-in replacement for sinopia?** Do we need to do anything differently?

Your readme states the compatibility with npm, and while there will be a lot of first time private repo users in future, I expect many new verdaccio users will be moving from sinopia.

Just my 2c
Thanks!

-------------------------

BTW: For each new version of node or each new version of sinopia that I install I just run it like this, and it works every time with zero reconfig or republishing etc.

sinopia --config /my_stuff/sinopia-config.yaml
*/my_stuff/sinopia-config.yaml*
```
# path to a directory with all packages
storage: /my_stuff/my_private_npm_packages
...
```

**Comment by Meeeeow** [comment]
Yes, but you should always backup your data (package storage) before do a major update

**Comment by lope** [comment]
Thanks
