### ISSUE TITLE
On Shared Machine/Server:  'verdaccio' is not recognized as an internal or external command, operable program or batch file. 

### ISSUE THREAD

**Issue by BaamAadmi** [verdaccio/verdaccio#280]
Hi,

#### My reason:

I have been using **Verdaccio** locally on my machine and its been great. Now I tried to set it up on a shared machine/server. But I faced an issue when I try to run the command
`$ verdaccio` 

It says Verdaccio is not an internal or external command..............

#### Steps to reproduce:

Use a shared machine. In my case windows.
Node and Verdaccio  gets installed at C:/Users/Username/Appdata/roaming properly.
 

####  App Version:	

Node -v 7.5.0
Verdaccio 2.3.4

#### Additional information:
	
 To overcome this and run the Verdaccio sever. I went to following location. and ran **verdaccio.cmd**

> C:\Users\username\AppData\Roaming\npm

It worked! and ran the the server as expected on localhost:4873 :+1:   
I have added this in an issue because It is not working as expected. And Might help you guys in development. 

Cheers!
Sudeep

**Comment by juanpicado** [comment]
@BaamAadmi couple of questions

1. What do you mean exectly with *Shared Machine/Server*? 
2. I do not think this an issue with verdaccio, rather it seems you do not have the $PATH set correctly in your server. Have you checked PATH in Environment Variables already?

**Comment by BaamAadmi** [comment]
@juanpicado  Thank you for your response. 

1. What do you mean exactly with Shared Machine/Server?
     It is a machine within our development network, which we will use to deploy code,services etc. In our case I will keep NPM local registry on the same, which can be accessed by multiple resources.  

2. I do not think this an issue with verdaccio, rather it seems you do not have the $PATH set correctly in 
    your server. Have you checked PATH in Environment Variables already?
    Yes. I am sure its not related to **_verdaccio_**. I was hoping if someone could point me in right direction on what $PATH should I set, In case of a multi user server.

**Comment by juanpicado** [comment]
Thanks for the explanation.
Unfortunately, I'm not a windows guy, I hope someone else can help you.

**Comment by juanpicado** [comment]
I will close this one for inactivity, the author can suggest reopening if provides more information,

**Comment by vesrah** [comment]
You could add C:\Users\username\AppData\Roaming\npm to your PATH.

**Comment by BaamAadmi** [comment]
Sorry for the delayed response. As a workaround, I did solve issue by running **verdaccio.cmd** as mentioned in my original question. Copying PATH did not work.
