### ISSUE TITLE
Move from fastify-warning to process-warning

### ISSUE THREAD

**Issue by mcollina** [verdaccio/verdaccio#2821]
I have renamed fastify-warning into process-warning as it's actually a generic module and not tied to Fastify. I plan to deprecate fastify-warning in the coming weeks. You might want to update to process-warning@1.0.0 in the coming weeks.

Ref https://github.com/fastify/process-warning/issues/47

**Comment by juanpicado** [comment]
Thanks @mcollina for the heads up.
@dianmorales since you have introduced it #2595 would you like to take care of it?

**Comment by juanpicado** [comment]
Done https://github.com/verdaccio/verdaccio/pull/2855

**Comment by mcollina** [comment]
Thanks @dianmorales and sorry for the disruption!
