### ISSUE TITLE
How to Change the name of LDAP admin

### ISSUE THREAD

**Issue by pangfd** [verdaccio/verdaccio#2858]
As default, the official config.yaml used the name of admin to login LDAP. Due to the reason of security, I want to change this name, could you provide such parameter, like LdapAdminUser ？

auth:
  ldap:
    type: ldap
    client_options:
      url: "ldap://ldap.verdaccio.private.rocks"
      # Only required if you need auth to bind
      adminDn: "cn=readonly,dc=verdaccio.private,dc=rocks"
      adminPassword: "********"
      # Search base for users
      searchBase: "dc=verdaccio.private,dc=rocks"
      searchFilter: "(&(uid={{username}})(memberOf=cn=npm_users,ou=npm,ou=groups,ou=developers,dc=verdaccio.private,dc=rocks))"
      # # If you are using groups, this is also needed
      groupDnProperty: "cn"
      groupSearchBase: "ou=npm,ou=groups,ou=developers,dc=verdaccio.private,dc=rocks"
      # If you have memberOf support on your ldap
      searchAttributes: ["*", "memberOf"]
      # Else, if you don't (use one or the other):
      # groupSearchFilter: '(memberUid={{dn}})'
      #
      # Optional, default false.
      # If true, then up to 100 credentials at a time will be cached for 5 minutes.
      cache: false
      # Optional
      reconnect: true

**Comment by juanpicado** [comment]
hi @pangfd , please ask here https://github.com/Alexandre-io/verdaccio-ldap
