### ISSUE TITLE
fix priority of readme in webUI

### ISSUE THREAD

**Issue by joebnb** [verdaccio/verdaccio#2866]
if package contain main readme and version beside readme i think version beside should show first.

eg: package.json
```
{
name:'package',
verisions:{
   "1.0.9":{
       readme: 'readme v1.0.9'
    }
    ....
      "1.0.0":{
       readme: 'readme v1.0.0'
    }
},
readme: 'readme v1.0.0'
}
```
current verdaccio in this package.json always show readme v1.0.0

**Comment by juanpicado** [comment]
Could you add a list of steps to reproduce it?

**Comment by joebnb** [comment]
> Could you add a list of steps to reproduce it? Please fill this out https://github.com/verdaccio/verdaccio/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

it's happens on uplink case, the uplink package.json versions contian readme in each version,verdaccio not read readme in latest version ,it just read out readme of package.json

verdaccion version 5.x

i think,it not about platfrom,node version,it's a behavior bug,i expect verdaccio read in versions readme first,and secondary fallback to readme in outer,and if i switch version in web ui,this readme also change.

currently some uplink put readme in version

wish fix it in verdaccio 5.x
