### ISSUE TITLE
nginx server with https not work as expected 

### ISSUE THREAD

**Issue by joebnb** [verdaccio/verdaccio#2868]
**Your Environment**
  
 * **verdaccio version**: 5.4.0
 * **node version**  14.16.1
 * **package manager**: npm@6
 * **os**: centos7
 * **platform**: npm

i start up a verdaccio at http://localhost:8086 and use nginx proxy_pass to visit this service,this nginx exposed 2 port to user -- 80 and 443(http and https).

expect description：
       user visist http://npm.domain.com and nginx proxy this request to http://localhost:8086 **verdaccio response UI HTML link ,package.json and tarball url with http**
       user visist https://npm.domain.com and nginx proxy this request to http://localhost:8086  **verdaccio response UI HTML link ,package.json and tarball url with https**

actual：
       user visist http://npm.domain.com and nginx proxy this request to http://localhost:8086  **verdaccio response with http or 
 https protocol**
       user visist https://npm.domain.com and nginx proxy this request to http://localhost:8086  **verdaccio response UI HTML link ,package.json and tarball url with https**
 https protocol**

could make the  protocol dynamic in every request

![image](https://user-images.githubusercontent.com/1646883/148639711-2235c6f1-72f7-46fa-b8a5-660d356f740f.png)

it's like only decision which protocol use in init,after first time visit it will freeze,not every time response right portal,i'm useing pm2 to start 8 process(load banlance) in each ECS

![2022-01-08 18-28-43 2022-01-08 18_32_51](https://user-images.githubusercontent.com/1646883/148641020-e2a2f65f-f000-4294-8ae8-dcb645970b8b.gif)

**Comment by joebnb** [comment]
it's seems work well in verdaccio 4, this issue is emergency,pls help 😭

**Comment by joebnb** [comment]
did maintainer care about use case? no one reply,this weekend i end my ski by a call beacause this😔

**Comment by joebnb** [comment]
and sunday i back to my company to check it https://github.com/verdaccio/verdaccio/blob/b79266d54e7310ed879e80e0beda95ebbeb2470c/src/lib/utils.ts#L158 
this line i think should not be write like this,this cause tarball url error when memorized

https://github.com/verdaccio/verdaccio/blob/b79266d54e7310ed879e80e0beda95ebbeb2470c/src/api/web/html/renderHTML.ts#L81
and this line should not trim rudeness.


all of this will make i request http it may return https url ,i request https it will contain http url.

and a make 2 PR,no one considered,and one of them about logger the reason is it's affect about Perf,and i have a search about logger performance issue it's seems no one have issue about this,and search logger the issue is it's can't support third part proccess management or log watch tools,lose a great deal through trying to save a little,and i think default success when i start a application is target of software design,this logger can't interactive with any outside system until user found it's a async logger,it's not stdout,even it was handle 10000 req but just show 100,it's fail about usability and cognition

**Comment by juanpicado** [comment]
> and i search about logger performance issue it's seems no one have issue about this,and the issue in top is it's can't support third part proccess management or log watch tools,it's lose a great deal through trying to save a little,did default success when user start a application is one of target of software design,this logger can't interactive with any outside system till user found it's a async behavior,it's not stdout,even it was handle

Ok, please I suggest don't mix personal feelings with reporting an issue because does not help, this place is not for this. As I appreciate you use this software, I also would like you appreciate this is a **voluntary** and _unpaid_ work, I repeat, **voluntary** with all that involves.  A nice sunday reading to [this guide](https://github.com/verdaccio/verdaccio/blob/master/CODE_OF_CONDUCT.md) is also recommened.

Now, back to your issue, we have a demo side also running in Nginx https://registry.verdaccio.org/ and I cannot reproduce what you are reporting. 

I'd recommend extend your description, improve readability as much you possible can, reproducible steps (images helps but need more), you can take adventage of docker https://github.com/verdaccio/verdaccio/tree/master/docker-examples which can help you to reproduce your issue, and patience, don't expect quick answers from my side specially during the week.

**Comment by joebnb** [comment]
> I'd recommend extend your description, improve readability as much you possible can, reproducible steps (images helps but need more), you can take adventage of docker https://github.com/verdaccio/verdaccio/tree/master/docker-examples which can help you to reproduce your issue, and patience, don't expect quick answers from my side specially during the week.

my feeling not  good because this  issue was posted 8 days ago,this problem have chance to solved earlier, i dont want to excuse anyones holiday include me.during these day this issue just ignored.i am also a volunteer who hold a private registry in my company, it's not my object or my job content,even this service not have independent computing resource,it's totaly base on my passion and im happy to get respect from it, it's free and happy, in my opinion i have to promise a SLA to my user even no paied to me(this  just for me,if you want to be like marak the author of color and 
 faker.js node package that's also ok,it's your code and it's your rights,i just misunderstand),in my situation my colleague they overwork in saturday and blocked on error and waiting me to solve it,i also  have rights to continue my ski and ignore this but my choice is abandon. 
i think the respect get from responsibility. 

back to issue, i think i was have a detailed description, if not understand just read your two lines code which was pointed in above URL.

the behavior is: 

if i request use http first time it will  memory protocol,next time use https visit it will respons use first time result.

i just repeat again of first post tldr.and  i also have a hack in my local and fixed,i just report it,if you think it's ok by design,just ignore this
