### ISSUE TITLE
Remove dist-tags deprecated endpoints

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#288]
#### My reason:

The following endpoints are not used, neither `npm` or `yarn` has any reference to and not even is covered by our functional testing. It should not exist.

```
PUT /-/package/:package/dist-tags
DELETE /-/package/:package/dist-tags
```
The valid endpoints used by `npm` or `yarn` always refers to 

```
PUT /-/package/:package/dist-tags/:tag
DELETE /-/package/:package/dist-tags/:tag
```

Where the tag is always present.

#### Proposal

Remove the following lines and correspondent functional test

`dist-tags.js line 73 `
```javascript
route.put('/-/package/:package/dist-tags', can('publish'), media(mime.lookup('json')), expect_json,
    function(req, res, next) {
      storage.replace_tags(req.params.package, req.body, function(err) {
        if (err) {
          return next(err);
        }
        res.status(201);
        return next({ok: 'tags updated'});
      });
    });

  route.delete('/-/package/:package/dist-tags', can('publish'), media(mime.lookup('json')),
    function(req, res, next) {
      storage.replace_tags(req.params.package, {}, function(err) {
        if (err) {
          return next(err);
        }
        res.status(201);
        return next({ok: 'tags removed'});
      });
    });
```

The unique reference I found is https://github.com/npm/npm-registry-client/pull/96/files#diff-4cb095bb06d9188b695c5a90808fe22c and the method `.set()` is not used from `npm`. More info https://github.com/npm/npm-registry-client#clientdisttagsseturi-params-cb

**Comment by nest000** [comment]
please notice, currently id does not work using scoped packages due to lack of scope check in req param. can you fix this please also?

**Comment by juanpicado** [comment]
@nest000 Could you create a ticket with that issue ?
