### ISSUE TITLE
Get dist-tags is not working for scopped package via rest API

### ISSUE THREAD

**Issue by daniel-azu** [verdaccio/verdaccio#2905]
**Your Environment**
verdaccio version: 5.4
node version: v12.22.1
package manager: npm@6.14.12
os: MacOS
platform: npm

**Describe the bug**
Can not get tags of scopped package by Rest API

Reproducing steps:
-Define a module with scope, for instance `@abc/def`
-Add some tag by npm cli
-Try getting it by Rest API -> `.../-/package/@abc/def/dist-tags`.

**Expected behavior**
Get a json with the tags

**Actual behavior**
Get `"error": "File not found"`

Thanks.

**Comment by juanpicado** [comment]
Please fill this template before report an issue, which makes it easier to understand to track the source of the problem.
https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by daniel-azu** [comment]
Updated by the template

**Comment by juanpicado** [comment]
Why do you mean with REST API?

**Comment by daniel-azu** [comment]
I mean if I try to fetch `http://localhost:4873/-/package/<package>/dist-tags` I can get it but if I try to get scopped package like `http://localhost:4873/-/package/<scopped>/<package>/dist-tags` I get:
`{
  "error": "File not found"
}`

**Comment by daniel-azu** [comment]
Is there any estimation when this bug will be fixed?

**Comment by juanpicado** [comment]
First, we need to triague this. Can you reproduce this by using a package manager? If is so would be nice to have the reproducible steps (I'm asking because if it work with package managers is not a bug).

**Comment by daniel-azu** [comment]
It works on npm and doesn't work on verdaccio.
I wrote the reproducing steps.
Can you please try reproducing it?
If the reproducing steps I wrote are not clear I can elaborate.

**Comment by juanpicado** [comment]
I was refering usign this commands https://docs.npmjs.com/cli/v8/commands/npm-dist-tag

**Comment by daniel-azu** [comment]
Any update regarding this?

**Comment by juanpicado** [comment]
As soon I have some space I could keep checking this, but help is welcome.

**Comment by IhToN** [comment]
To add some extra info to this as I'm having the exact same issue, these are the Verdaccio logs when trying to use the `npm dist-tag` command on a scoped package:

```
{"level":25,"time":1652782240198,"pid":10,"hostname":"<REDACTED>","req":{"method":"GET","url":"/-/package/<REDACTED>/<REDACTED>/dist-tags","query":{},"params":{},"headers":{"host":"<REDACTED>","x-real-ip":"<REDACTED>","x-forwarded-for":"<REDACTED>","x-forwarded-proto":"https","connection":"close","user-agent":"npm/8.7.0 node/v14.17.3 win32 x64 workspaces/false","npm-command":"dist-tag","authorization":"<Classified>","accept":"*/*","accept-encoding":"gzip,deflate"},"remoteAddress":"<REDACTED>","remotePort":<REDACTED>},"ip":"<REDACTED>","msg":"@{ip} requested '@{req.method} @{req.url}'"}
{"level":25,"time":1652782240207,"pid":10,"hostname":"<REDACTED>","request":{"method":"GET","url":"/-/package/<REDACTED>/<REDACTED>/dist-tags"},"user":"<REDACTED>","remoteIP":"<REDACTED> via <REDACTED>","status":404,"error":"File not found","bytes":{"in":0,"out":32},"msg":"@{status}, user: @{user}(@{remoteIP}), req: '@{request.method} @{request.url}', error: @{!error}"}
```

I'm using docker and nginx with a reverse proxy configured as specified in Verdaccio docs.

**Comment by mbtools** [comment]
The slash between scope and package must be escaped 😉 

`http://localhost:4873/-/package/<scope>%2F<package>/dist-tags`

Or as code:

```js
const path = `/-/package/${encodeURIComponent(pkgName)}/dist-tags`;
```
