### ISSUE TITLE
packages no longer show up after restarting instance.

### ISSUE THREAD

**Issue by StephenHodgson** [verdaccio/verdaccio#2909]
**Your Environment**
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (2) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
  Binaries:
    npm: 6.14.15 - /usr/bin/npm
  npmGlobalPackages:
    verdaccio: 5.3.0

**Describe the bug**

When upgrading my verdaccio instance from 5.3 -> 5.4  and restarting it my previously published packages are no longer listed.

Oddly enough when I navigate to the package web page it is valid and shows the correct information, but coming back to the home page doesn't show the packages at all. 

**To Reproduce**

1. shut down verdaccio instance
2. upgrade verdaccio
3. restart instance

**Expected behavior**

packages should still be listed

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by StephenHodgson** [comment]
I tried using the absolute path, but it still didn't work and the packages were no longer accessible through their individual urls

**Comment by juanpicado** [comment]
1. You could try to figure out which storage is pointing by enabling extreme trace debug like this.
```
  ~ DEBUG=verdaccio* verdaccio
  verdaccio:logger setup logger +0ms
  verdaccio:logger logging stdout enabled +1ms
  verdaccio:logger has prettifier? true +0ms
 warn --- config file  - /home/user/.config/verdaccio/config.yaml
  verdaccio:logger setup logger +445ms
  verdaccio:logger logging stdout enabled +0ms
  verdaccio:logger has prettifier? true +0ms
  verdaccio:plugin:local-storage sync database started +0ms
  verdaccio:plugin:local-storage sync folder '/home/user/.local/share/verdaccio/storage' created succeed +0ms
  verdaccio:plugin:local-storage sync write succeed +1ms
```
2. I'd check chrome dev tools and check what the `/packages` endpoints returns

You would need to share more info, since what you are doing is what I do every day and I don't have such issue.

**Comment by StephenHodgson** [comment]
I ended up having to rebuild my verdaccio-db.json file to get it working again. Not sure what broke it.

**Comment by juanpicado** [comment]
If you figure it out, please share, the storage logic has been intact for very long time in the version 5.

**Comment by StephenHodgson** [comment]
I think I may have installed it locally instead of globally using npm.
