### ISSUE TITLE
Install auth plugins for pre-built docker image

### ISSUE THREAD

**Issue by ahmadsholehin** [verdaccio/verdaccio#299]
Is there a way to install plugins if the pre-built docker image is used? Specifically, I'm looking to use sinopia-gitlab for auth.

Any help is much appreciated.

**Comment by Meeeeow** [comment]
You can place it into config directory, plugin directory name must same as plugin name

How it works? see here:
[src/lib/plugin-loader.js#L53](https://github.com/verdaccio/verdaccio/blob/master/src/lib/plugin-loader.js#L53)

**Comment by ahmadsholehin** [comment]
Excellent, will try this out and report back. Thanks @Meeeeow !

**Comment by ahmadsholehin** [comment]
Had quite a bit of a problem using a `plugins` directory in relative to the `config` directory.
I ended up downloading the package and putting it in `/usr/local/app/node_modules` directory and setting up a auth gitlab configuration in `config.yaml`. This works.

**Comment by juanpicado** [comment]
@ahmadsholehin that improvement should be addressed on #302
