### ISSUE TITLE
Incorrect handling of dist-tags

### ISSUE THREAD

**Issue by steve-p-com** [verdaccio/verdaccio#3]
I was going to add this to Sinopia, but as we all know, that project seems to be defunct now. So I may as well add it here.

The way `dist-tags` (contained in a module's  `package.json`) is handled appears incorrect. Elements are treated as an array, in other words like this:

    dist-tags": {
        "latest": [
            "1.0.0-beta10",
            "1.0.0-beta11",
            "1.0.0-beta12",
            "1.0.0-beta9"
        ]
    }

This is a real world example (`react-select`). The array is sorted using the `sort` method provided by the `semver` module. When someone requests the latest version, the last element in the array is examined to work out the version to provide.

In most cases, this will be fine, but in this particular case,  `1.0.0-beta9` is returned. Clearly this isn't the latest version, but is the result of a lexical sort (`beta9` is greater than `beta12`).

You could legitimately argue that the authors of `react-select` have not read the Semver.org manual, and the version numbers should be `1.0.0-beta.9`, `1.0.0-beta.10` etc, which would be sorted correctly. However, that doesn't help, and doesn't alter the fact that when someone does `npm install react-select` they want the latest, and not some other version just because the implementation in sinopia/verdaccio is a bit odd.

The reality is that Sinopia/Verdaccio should be replicating what the upstream repository would do (i.e. registry.npmjs.org). That does not return an array. It knows what the latest version is, and returns it as a string, like this:

    dist-tags": {
        "latest": "1.0.0-beta12"
    }

So really, all we need to do is stop Sinopia/Verdaccio treating it as an array, or trying to do anything clever, and just do what the upstream repo tells it to. This should be quite easy, compared to all the complexity of sorting and merging that happens with the array.

If and when I get time, I will sort out a pull request and do it properly, but in the meantime, here's what I changed so far.

in `utils.js`, replace `module.exports.tag_version` with this:

    module.exports.tag_version = function(data, version, tag, config) {
        if (!can_add_tag(tag, config)) return false

        if (data['dist-tags'][tag] !== version) {
            data['dist-tags'][tag] = version;
            return true;
        }
      
        return false;
    }

There are some other places which may need attention. I will add them here as I find them. My intention is to eliminate the 'ignore latest tag' config option, too. I can't see any reason why we shouldn't trust the upstream repo's `latest` tag. I need to investigate publishing local packages, to see what that does, too.

I may be the only person who is having this issue. I take it the consensus is we should fix it, rather than me just patch my local sinopia?

**Comment by cuzzinz** [comment]
I agree this should be fixed.  It should work as people expect upstream to work.... So anything that is different should definitely be made to match since as a proxy the integration should be seamless.

**Comment by steve-p-com** [comment]
I'm almost done testing. Install, update and publish all work, and so does npm dist-tags, and it's not necessary to initialise the cache.  I will submit the changes for merging tomorrow.

**Comment by steve-p-com** [comment]
I have this running now in modified form on our internal server, and it seems to be working fine. I have submitted a pull request to get the changes merged back in.

**Comment by trentearl** [comment]
fixed with #8
