### ISSUE TITLE
[5.x] Bump yarn version

### ISSUE THREAD

**Issue by kuoruan** [verdaccio/verdaccio#3042]
**Is your feature request related to a problem?**
Yes, it's a yarn bug

**Describe the solution you'd like**
```
$ yarn config unset httpsProxy
Unknown Syntax Error: Extraneous positional argument ("unset").
```

The yarn version in Docker image is too old. See yarnpkg/berry#2667

**Describe alternatives you've considered**
```
yarn set version latest
```

to update the yarn version

**Comment by juanpicado** [comment]
I've tried already to upgrade to yarn 3 but breaks all test, I don't want to invest time on this because master brach uses pnpm and works fine, the 5.x branch has expire date.
