### ISSUE TITLE
Hostname should be a per request thing

### ISSUE THREAD

**Issue by loynoir** [verdaccio/verdaccio#3063]
**Your Environment**
  
 * **verdaccio version**: 5.7.0
 * **node version** [12.x.x, 14.x.x]: 14.18.2
 * **package manager**: [npm@7, pnpm@6, yarn@2] docker
 * **os**: [mac, windows@10, linux] docker
 * **platform**: [npm, docker, helm, other] docker

**Describe the bug**

Currently, verdaccio hostname is not a per request thing. Seems the hostname from first req is persist forever.

**To Reproduce**

```sh
$ docker-compose down
$ docker-compose up -d
$ curl http://aaa:4873/foobar | grep tarball
"tarball": "http://aaa:4873/xxx.tgz"
$ curl http://bbb:4873/foobar | grep tarball
"tarball": "http://aaa:4873/xxx.tgz"

$ docker-compose down
$ docker-compose up -d
$ curl http://bbb:4873/foobar | grep tarball
"tarball": "http://bbb:4873/xxx.tgz"
$ curl http://aaa:4873/foobar | grep tarball
"tarball": "http://bbb:4873/xxx.tgz"
```

**Expected behavior**

```sh
$ docker-compose down
$ docker-compose up -d
$ curl http://aaa:4873/foobar | grep tarball
"tarball": "http://aaa:4873/xxx.tgz"
$ curl http://bbb:4873/foobar | grep tarball
"tarball": "http://bbb:4873/xxx.tgz"

$ docker-compose down
$ docker-compose up -d
$ curl http://bbb:4873/foobar | grep tarball
"tarball": "http://bbb:4873/xxx.tgz"
$ curl http://aaa:4873/foobar | grep tarball
"tarball": "http://aaa:4873/xxx.tgz"
```

**Screenshots, server logs, package manager log**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
You might need to reveal what's behind your logic, if you don't provide the `host` header the url returned for the tarball would be whatever you have in the storage and that's by design.

**Comment by loynoir** [comment]
> You might need to reveal what's behind your logic, if you don't provide the `host` header the url returned for the tarball would be whatever you have in the storage and that's by design.

@juanpicado 
1. two different hostnames, points to one same instance
2. two hostnames are different, because they are from different network

**Comment by loynoir** [comment]
@juanpicado 
> that's by design
Is there a way to alter tarball host, according to client's per connection HTTP_HOST?

**Comment by juanpicado** [comment]
You can read logic here https://github.com/verdaccio/verdaccio/blob/5.x/src/lib/utils.ts#L145

**Comment by loynoir** [comment]
@juanpicado 
It's weird. I just checked the source. 

Get different result outside docker using `v6.0.0-6-next.30`, that result is expected.

**Comment by loynoir** [comment]
First request using 127.0.0.1

Without docker, v6.0.0-6-next.30, second req
```
$ curl x.x.x.x:14873/foobar |grep tarball
"tarball": "http://x.x.x.x:14873/foobar.tgz"
```
With docker, 5.7.0, second req
```
$ curl x.x.x.x:24873/foobar |grep tarball
"tarball": "http://127.0.0.1:24873/foobar.tgz"
```

**Comment by loynoir** [comment]
Seems 5.X has this bug, v6.0.0-6-next.30 fixed it.

Wish for v6 docker image. 

Thanks. :)
