### ISSUE TITLE
har-validator@5.1.5: this library is no longer supported

### ISSUE THREAD

**Issue by xiaodiao1212** [verdaccio/verdaccio#3064]
**Your Environment**
  
 * **verdaccio version**: 6.x.x
 * **node version** [v16.0.0, v16.14.1, v17.1.0]:
 * **package manager**: [npm@7.10.0, npm@8.5.0, npm@8.1.2]
 * **os**: [linux]
 * **platform**: [npm]

**Describe the bug**

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/14543505/158552669-21d3c1a1-7253-415c-8642-bfcc490ec9a1.png">

**Comment by juanpicado** [comment]
Thanks for reporting, the idea is remove `request` by v6, here more details https://github.com/verdaccio/verdaccio/issues/1807 

I'll close this because it is already on the roadmap.

**Comment by xiaodiao1212** [comment]
thanks
