### ISSUE TITLE
Add support for new search endpoint

### ISSUE THREAD

**Issue by zybreak** [verdaccio/verdaccio#310]
#### My reason:

The current search endpoint in verdaccio '/-/all' is deprecated in favor of '/-/v1/search'
http://blog.npmjs.org/post/157615772423/deprecating-the-all-registry-endpoint

**Comment by juanpicado** [comment]
It seems reasonable enhancement. If anyone is willing to contribute here there is a good opportunity.

**Comment by ayusharma** [comment]
Hi, I am looking forward to work on this issue. 

I have following doubts : 
- What are the parameters/points to relate search in local storage or Should I send all the packages of local storage to stream? eg. keywords, description etc.
- NPM registry search endpoint now has a score key as well, Do we also need to implement that?
- In https://github.com/verdaccio/verdaccio/blob/ebb033ce1a86f22f3295295b899bf0688189a5bf/src/lib/storage.js#L413  We are first searching up links and after that adding local results to the final stream. Am I getting right? So what would be the criteria for size and pagination?

If I am wrong, Correct me.

Thanks !
