### ISSUE TITLE
Global install failed,successed local.

### ISSUE THREAD

**Issue by Manonicu** [verdaccio/verdaccio#3111]
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v17.9.0/lib/node_modules/verdaccio/node_modules/es5-ext
npm ERR! command failed
npm ERR! command sh -c  node -e "try{require('./_postinstall')}catch(e){}"

**Comment by juanpicado** [comment]
Request is being removed look my last PR
