### ISSUE TITLE
Web user still "kind of" logged in after session expires

### ISSUE THREAD

**Issue by joergrech** [verdaccio/verdaccio#3163]
**Your Environment**
 * **verdaccio version**: v5.10.0
 * **node version**: v16.15.0
 * **package manager**: npm 8.5.5 (but bug is in website)
 * **os**: verdaccio runs on linux, user runs chrome version 101 on MacOS
 * **platform**: Website

> NOTE: the Local Storage in chrome still contains `username`, `darkMode`, and `token`

**Describe the bug**

After the web session expires for a logged-in user (after ~60 minutes) the user is still shown in the user-dropdown but has no access to packages (we use `access: $authenticated`). In order to view the packages again the user has to log-out and then log-in again.

**To Reproduce**

1. Start verdaccio with `access: $authenticated` configuration
2. Log into web server as a valid user
3. wait until session expires (~60 minutes)
4. reload page:
  * No Packages are shown: `Correct`
  * User is still shown (e.g., "Hi joerg.rech"): `Intended?`
  * To log-in the user has to log-out and then log-in again: `Inconvenient`

**Expected behavior**

I expected that the user can directly log-in without having to log-out first. Either by showing a menuitem to log-in in the user dropdown (e.g., where the log-out menuitem is) or by directly showing  the log-in modal dialog.

**Screenshots, server logs, package manager log**

N/A

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

I don't think this will help - but I can provide it if you need it

**Environment information**

Verdaccio is running on AWS ec2 `t2.micro` instance using `pm2 verdaccio` behind a load balancer using a certificate to support https.

```
Environment Info:(node:25430) [LRU_CACHE_OPTION_maxAge] DeprecationWarning: The maxAge option is deprecated. Please use options.ttl instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

  System:
    OS: Linux 5.10 Amazon Linux 2
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
  Binaries:
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  npmGlobalPackages:
    verdaccio: 5.10.0
```

**Debugging output**

N/A for web?

**Comment by Sov3rain** [comment]
I ran into the same exact behaviour today. Verdaccio 5.8.0 on an GCP VM instance running Debian 10.

**Comment by Maros112358** [comment]
Hello, what kind of authentication plugin do you use? @joergrech

**Comment by Sov3rain** [comment]
Hey, I'm using the default one.

**Comment by Maros112358** [comment]
I managed to reproduce the error.

**Environment**

-     verdaccio version: v5.13.1
-     node version: v16.15.1
-     package manager: npm 8.11.0
-     os: debian 11
-     **platform:** Website

**Config**
```
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@*/*":
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  "**":
    proxy: npmjs
    access: $all
    publish: $authenticated
log: { type: stdout, format: pretty, level: http }
```

I published packag `@test/npm-package-1` and `npm-package-1`. One hour after logging in, package `@test/npm-package-1` was not visible.
Corresponding log from verdaccio:
```
 http --- 127.0.0.1 requested 'GET /'
 http --- 200, user: null(127.0.0.1), req: 'GET /', bytes: 0/0
 http --- 127.0.0.1 requested 'GET /-/verdaccio/data/packages'
 http --- 200, user: null(127.0.0.1), req: 'GET /-/verdaccio/data/packages', bytes: 0/0
 info --- auth/allow_action: access granted to: undefined
 info --- allowed access for npm-package-1
 error--- forbidden access for @test/npm-package-1. Error: authorization required to access package @test/npm-package-1
```

I logged out and then logged in. Package `@test/npm-package-1` was now visible. Log:
```
 http --- 127.0.0.1 requested 'GET /'
 http --- 200, user: null(127.0.0.1), req: 'GET /', bytes: 0/0
 http --- 127.0.0.1 requested 'GET /-/verdaccio/data/packages'
 http --- 200, user: null(127.0.0.1), req: 'GET /-/verdaccio/data/packages', bytes: 0/0
 info --- auth/allow_action: access granted to: undefined
 info --- allowed access for npm-package-1
 info --- auth/allow_action: access granted to: undefined
 info --- allowed access for @test/npm-package-1
```

**Comment by Sov3rain** [comment]
I have a feeling of déjà vu, you should take a look at my thread here: https://github.com/verdaccio/verdaccio/discussions/3059

Let me know if you found something helpful.

**Comment by Maros112358** [comment]
> I have a feeling of déjà vu, you should take a look at my thread here: #3059
> 
> Let me know if you found something helpful.

Thank you for the info. I think I found the cause.

Looks like the web UI shows "logged in" status when values `token` and `username` are present in the local storage of the browser (https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), which has no expiration time and is cleaned only by logging out.

![image](https://user-images.githubusercontent.com/98359168/177547849-5973114e-4dc5-4aaf-82c3-aef5e3f587e1.png)

Following the login, the `token` expires after 1 hour (https://verdaccio.org/docs/configuration/#security), but it is still present in the local storage until the user logs out.

**Comment by Sov3rain** [comment]
@juanpicado, can you take a quick look at this?

**Comment by juanpicado** [comment]
> @juanpicado, can you take a quick look at this?

No much time this week sorry, maybe over the next weeks or whenever I find some time next days, no guarantee.

**Comment by MHuberrr** [comment]
Any update on this issue? I can still reproduce it in the latest release.

**Comment by Sov3rain** [comment]
Just FYI, we ended up setting the token expiration duration to 3 months (default is 1 hour). It's not ideal but it made our lives much easier. See https://github.com/verdaccio/verdaccio/discussions/3059#discussioncomment-2406364 for detailed informations.

**Comment by Dentling** [comment]
I am also still experiencing this issue in the latest release. 
Any updates on this?

**Comment by mrcego** [comment]
The issue is reproducible some time ago. I just write here to keep live this issue.
