### ISSUE TITLE
Login dialog and error message box overlapping

### ISSUE THREAD

**Issue by ayusharma** [verdaccio/verdaccio#322]
#### My reason:

<img width="1037" alt="screen shot 2017-09-12 at 11 04 25 pm" src="https://user-images.githubusercontent.com/6918450/30340103-0c20a53e-980f-11e7-911a-5a8490edd7b8.png">

####  App Version:	
All

####  Config file:	
full config file provided in conf directory.

#### Additional information:

screenshot attached.
 
 - Container:
   - I use local environment

#### Additional verbose log:
```sh
warn --- config file  - /Users/ayush/.config/verdaccio/config.yaml
 warn --- http address - http://localhost:4873/ - verdaccio/2.3.6
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /', bytes: 0/1284
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /-/static/style.8410f14de467c42d2f6c14c7df197f3f.css', bytes: 0/47471
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /-/static/main.29190c77c9249937b209.js', bytes: 0/441993
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /-/static/logo.png', bytes: 0/25736
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /-/verdaccio/packages', bytes: 0/1103
 http <-- 401, user: undefined(127.0.0.1), req: 'POST /-/verdaccio/login', error: bad username/password, access denied
 http <-- 401, user: undefined(127.0.0.1), req: 'POST /-/verdaccio/login', error: bad username/password, access denied
 http <-- 401, user: undefined(127.0.0.1), req: 'POST /-/verdaccio/login', error: bad username/password, access denied
```

**Comment by juanpicado** [comment]
I recall a discussion about this topic with @Meeeeow . Do you have any design suggestion already?

**Comment by ayusharma** [comment]
I have worked on this changed dialog box as follows:

<img width="658" alt="screen shot 2017-09-12 at 11 04 54 pm" src="https://user-images.githubusercontent.com/6918450/30340461-3442f9e4-9810-11e7-9508-d69da0d43e15.png">


Sending a PR.

**Comment by Meeeeow** [comment]
Thanks for your great work 😉
