### ISSUE TITLE
Verdacio docker and nginx ssl, error HTTPS request has been blocked

### ISSUE THREAD

**Issue by Tsunani** [verdaccio/verdaccio#3251]
### Discussed in https://github.com/verdaccio/verdaccio/discussions/3250

<div type='discussions-op-text'>

<sup>Originally posted by **Tsunani** June 27, 2022</sup>
If I use recommended conf, page not load:

```
location /verdaccio/ {
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header Host $host;
  proxy_set_header X-NginX-Proxy true;
  proxy_pass http://localhost:6666;
  proxy_redirect off;
}
```
And get some errors:

`Mixed Content: The page at 'https://my.site/verdaccio/' was loaded over HTTPS, but requested an insecure script 'http://my.site/verdaccio/-/static/main.f6e570dfe38870ab429f5.js'. This request has been blocked; the content must be served over HTTPS.`

But HTTP work fine.
Pls help solve the problem.</div>

**Comment by Tsunani** [comment]
```
<!DOCTYPE html>
      <html lang="en-us"> 
      <head>
        <meta charset="utf-8">
        <base href="http://my.site/verdaccio/">
        <title>Verdaccio</title>
```
In index have HTTP, maybe i should change settings verdaccio?

**Comment by Tsunani** [comment]
Env in container set `VERDACCIO_PROTOCOL=http` .
This env need to change and it's work?

**Comment by Tsunani** [comment]
set the **VERDACCIO_PUBLIC_URL** env variable to **https://my.site**
And recreate container, it work

**Comment by Yechuanjie** [comment]
> > set the `VERDACCIO_PUBLIC_URL` env variable to `https://my.site` And recreate container, it work
> 
> i have change `VERDACCIO_PUBLIC_URL ` to my domain. and set url_prefix: '/' but got another error:
> 
> ```
> fatal--- cannot open config file /root/.config/verdaccio/config.yaml: YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key (116:11)
> 
>  113 | #url_prefix: '/'
>  114 | # // url -> https://somedomain.org/my_prefix/
>  115 | VERDACCIO_PUBLIC_URL='https://my.site
>  116 | url_prefix: '/'
> -----------------^
>  117 | # // url -> https://somedomain.org/
>  118 | # VERDACCIO_PUBLIC_URL='https://somedomai ...
> ```

这是它文档的问题，改成这样就可以了

```
VERDACCIO_PUBLIC_URL: 'https://my.site
url_prefix: '/'
```
