### ISSUE TITLE
Google Cloud documentation displays jibberish text

### ISSUE THREAD

**Issue by arnoldsandoval** [verdaccio/verdaccio#3255]
**Your Environment**
Not applicable. The issue is related to documentation.

**Describe the bug**

The Google Cloud documentation is non existent, even worse it displays jibberish.

- Markdown File: https://github.com/verdaccio/verdaccio/blob/master/website/docs/google-cloud.md
- Docs Site Link: https://verdaccio.org/docs/google-cloud/

**To Reproduce**
1. Visit [Docs > Google Cloud](https://verdaccio.org/docs/google-cloud/)
2. Read documentation

**Expected behavior**

There should be instructions on how to setup Verdaccio with GCP

**Screenshots, server logs, package manager log**

![CleanShot 2022-07-05 at 14 08 55](https://user-images.githubusercontent.com/723659/177416881-6e590d9e-5995-4494-907d-10a677bd7b1f.png)

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

N/A

**Environment information**

N/A

**Debugging output**

N/A

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇 

Im new to Verdaccio, setting up npm registries and GCP so I may not be the best person to do this. That said, I'm willing to give it a shot if my time permits.

**Comment by juanpicado** [comment]
Good one, I always forgot remove that file because I have much clue about GCP, or maybe I was just waiting :-) someone fill it out with some nice info.

**Comment by juanpicado** [comment]
I've removed the page https://github.com/verdaccio/verdaccio/commit/bf0f331dfcb59e5d58c03577883b1eec4275cfb2 if someone wants to contribute by put it again with more info be my guest.
