### ISSUE TITLE
Organization logo final stage

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#328]
This is a follow-up of https://github.com/verdaccio/verdaccio/issues/237.

I'll C&P what is described https://github.com/verdaccio/verdaccio/issues/237#issuecomment-325277927 briefly as a reminder of the rules.

### Final steps

The winner should PR  (`src/logo`) his logo including editable assets and render ready according to the use cases defined above.

### Votes

It's pretty hard to count votes using reactions. It's not clear whether 👍 has more value than ❤️. I guess is a matter of taste. So I was looking for a cool methodology and I like this one (https://github.com/postgraphql/postgraphql/issues/394#issue-214537477) so I'll copy it.

- 👍 I vote for this logo (you can vote for as many logos as you want)
- ❤️ Thanks for the submission, we really appreciate the effort you've put in
- 👎 I do NOT want to see this, let's keep it positive!
- 😕 If you think the logo is inappropriate in some way (e.g. violates a trademark, is rude, etc) - if you use this please add a (very polite!) explanation in the comments

I'll create 5 comments for each logo, ordered by votes in the early stage. Please read above how the voting system works. This Final stage will end on **October 24th** and all logos will start from 0 votes. The winner has to PR his logo as is described in the follow-up comment, in short, licensing properly and all assets ready to use. Due some authors have published several versions of the logos I'll pick the most voted one from his collection.

The list of designers will participate in the final stage are
- @kgrubb 
- @rodriguesbreno 
- @admorphit
- @jollycic
- @jmwilkinson 

Thank you guys for all your time and make this project looks more professional

**Update**: I made a mistake about the final date, the final stage is 30 days, not 60. The final deadline date has been updated correctly.

**Comment by juanpicado** [comment]
![kgrubb](https://user-images.githubusercontent.com/558752/30771662-7ac503cc-a04d-11e7-9902-457b6b3a7379.png)

by @kgrubb

**Comment by juanpicado** [comment]
![rodriguesbreno](https://user-images.githubusercontent.com/558752/30771672-a07df056-a04d-11e7-9362-6e08f8627ec8.png)
 
by @rodriguesbreno

**Comment by juanpicado** [comment]
![admorphit](https://user-images.githubusercontent.com/558752/30771679-ad111fa0-a04d-11e7-9836-4ef23a15e9ca.png)

by @admorphit

**Comment by juanpicado** [comment]
![jollycic](https://user-images.githubusercontent.com/558752/30771684-b82635a6-a04d-11e7-8879-26b6baa0423f.png)

by @jollycic

**Comment by juanpicado** [comment]
![jmwilkinson](https://user-images.githubusercontent.com/558752/30771685-be89f022-a04d-11e7-88d2-7a36c3ddb872.png)

by @jmwilkinson

**Comment by silkentrance** [comment]
https://github.com/verdaccio/verdaccio/issues/328#issuecomment-331621051 in combination with the font from https://github.com/verdaccio/verdaccio/issues/328#issuecomment-331621032 would be great.

**Comment by iegik** [comment]
![](https://www.anywayanyday.com/images/logo.svg)

**Comment by rodriguesbreno** [comment]
Hey, guys, I'll commit the files this weekend.
I return from vacation soon

**Comment by juanpicado** [comment]
@rodriguesbreno ???

**Comment by rodriguesbreno** [comment]
@juanpicado I mean. I'll send the SVG, EPS files in the appropriate format.

**Comment by juanpicado** [comment]
@rodriguesbreno let's wait October 24th. That day we will close the poll. Somehow, I'm glad to know your thoughts.  👍

**Comment by juanpicado** [comment]
I'm so glad to see tons of emoji reactions !! 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by juanpicado** [comment]
So, we have a winner :) congrats @rodriguesbreno 🎉 .

Thanks all you guys to support this voting process, a lot of reactions 👍 👎 ❤️ 🎉  !! That's so cool. 

Thanks @kgrubb @admorphit @jollycic @jmwilkinson for your proposals and to be part of this longgg process 💯 💯 💯 💯  !!

**Comment by rodriguesbreno** [comment]
Thank you all for the votes !!! 🙌 🎉🎉🎉
@juanpicado Let me know if the files are needed in other formats.
I'm sending in SVG and the original sketch file.
