### ISSUE TITLE
Verdaccio 2.4 returns wrong package.json

### ISSUE THREAD

**Issue by jackjoy** [verdaccio/verdaccio#329]
#### My reason:
I setup a verdaccio 2.4 server yesterday and found many projects failed to build after reinstall dependencies.After several hours digging,i found verdaccio returns wrong package.json file which remove some info from original package.json, e.g, "main" field. So it cause nodejs to throw many "can not find module' errors. Finally i revert to verdaccio 2.2, and all works fine.

**Comment by juanpicado** [comment]
Can you give me more? ... A quick test does not reveal anything.

**Comment by jackjoy** [comment]
install @angular/cli and create a new angular project, then call "ng build" would fail.

**Comment by jackjoy** [comment]
angular/cli

**Comment by juanpicado** [comment]
Thanks I'll try. Please share configuration file. It might be useful

**Comment by jackjoy** [comment]
configuration file is very normal which i copied from a worked server of verdaccio v2.1.7.

**Comment by juanpicado** [comment]
I cannot reproduce. 😞  . A clean installation works fine with a new storage.

**Comment by juanpicado** [comment]
This is the package.json for `webpack` using latest `angular/cli`. The `main` field is there.

```js
{
  "_from": "webpack@~3.5.5",
  "_id": "webpack@3.5.6",
  "_inBundle": false,
  "_integrity": "sha512-sXnxfx6KoZVrFAGLjdhCCwDtDwkYMfwm8mJjkQv3thr5pjTlbxopVlr/kJwc9Bz317gL+gNjvz++ir9TgG1MDg==",
  "_location": "/webpack",
  "_phantomChildren": {
    "cliui": "3.2.0",
    "decamelize": "1.2.0",
    "execa": "0.7.0",
    "get-caller-file": "1.0.2",
    "graceful-fs": "4.1.11",
    "lcid": "1.0.0",
    "locate-path": "2.0.0",
    "mem": "1.1.0",
    "normalize-package-data": "2.4.0",
    "parse-json": "2.2.0",
    "pify": "2.3.0",
    "require-directory": "2.1.1",
    "require-main-filename": "1.0.1",
    "set-blocking": "2.0.0",
    "y18n": "3.2.1"
  },
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "webpack@~3.5.5",
    "name": "webpack",
    "escapedName": "webpack",
    "rawSpec": "~3.5.5",
    "saveSpec": null,
    "fetchSpec": "~3.5.5"
  },
  "_requiredBy": [
    "/@angular/cli"
  ],
  "_resolved": "http://localhost:5555/webpack/-/webpack-3.5.6.tgz",
  "_shasum": "a492fb6c1ed7f573816f90e00c8fbb5a20cc5c36",
  "_spec": "webpack@~3.5.5",
  "_where": "/Users/user/WebstormProjects/my-project/node_modules/@angular/cli",
  "author": {
    "name": "Tobias Koppers @sokra"
  },
  "bin": {
    "webpack": "./bin/webpack.js"
  },
  "bugs": {
    "url": "https://github.com/webpack/webpack/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "acorn": "^5.0.0",
    "acorn-dynamic-import": "^2.0.0",
    "ajv": "^5.1.5",
    "ajv-keywords": "^2.0.0",
    "async": "^2.1.2",
    "enhanced-resolve": "^3.4.0",
    "escope": "^3.6.0",
    "interpret": "^1.0.0",
    "json-loader": "^0.5.4",
    "json5": "^0.5.1",
    "loader-runner": "^2.3.0",
    "loader-utils": "^1.1.0",
    "memory-fs": "~0.4.1",
    "mkdirp": "~0.5.0",
    "node-libs-browser": "^2.0.0",
    "source-map": "^0.5.3",
    "supports-color": "^4.2.1",
    "tapable": "^0.2.7",
    "uglifyjs-webpack-plugin": "^0.4.6",
    "watchpack": "^1.4.0",
    "webpack-sources": "^1.0.1",
    "yargs": "^8.0.2"
  },
  "deprecated": false,
  "description": "Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.",
  "devDependencies": {
    "beautify-lint": "^1.0.3",
    "benchmark": "^2.1.1",
    "bundle-loader": "~0.5.0",
    "codacy-coverage": "^2.0.1",
    "codecov.io": "^0.1.2",
    "coffee-loader": "~0.7.1",
    "coffee-script": "^1.10.0",
    "coveralls": "^2.11.2",
    "css-loader": "^0.28.3",
    "es6-promise-polyfill": "^1.1.1",
    "eslint": "^4.3.0",
    "eslint-plugin-node": "^5.1.1",
    "express": "~4.13.1",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "i18n-webpack-plugin": "^1.0.0",
    "istanbul": "^0.4.5",
    "jade": "^1.11.0",
    "jade-loader": "~0.8.0",
    "js-beautify": "^1.5.10",
    "less": "^2.5.1",
    "less-loader": "^4.0.3",
    "lodash": "^4.17.4",
    "mocha": "^3.2.0",
    "mocha-lcov-reporter": "^1.0.0",
    "nsp": "^2.6.1",
    "raw-loader": "~0.5.0",
    "react": "^15.2.1",
    "react-dom": "^15.2.1",
    "script-loader": "~0.7.0",
    "should": "^11.1.1",
    "simple-git": "^1.65.0",
    "sinon": "^2.3.2",
    "style-loader": "^0.18.1",
    "url-loader": "~0.5.0",
    "val-loader": "^1.0.2",
    "vm-browserify": "~0.0.0",
    "webpack-dev-middleware": "^1.9.0",
    "worker-loader": "^0.8.0"
  },
  "engines": {
    "node": ">=4.3.0 <5.0.0 || >=5.10"
  },
  "files": [
    "lib/",
    "bin/",
    "buildin/",
    "hot/",
    "web_modules/",
    "schemas/"
  ],
  "homepage": "https://github.com/webpack/webpack",
  "license": "MIT",
  "main": "lib/webpack.js",
  "name": "webpack",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/webpack/webpack.git"
  },
  "scripts": {
    "appveyor:benchmark": "npm run benchmark",
    "appveyor:test": "node node_modules\\mocha\\bin\\mocha --max-old-space-size=4096 --harmony test/*.test.js",
    "beautify-lint": "beautify-lint \"lib/**/*.js\" \"hot/**/*.js\" \"bin/**/*.js\" \"benchmark/*.js\" \"test/*.js\"",
    "benchmark": "mocha --max-old-space-size=4096 --harmony test/*.benchmark.js -R spec",
    "build:examples": "cd examples && node buildAll.js",
    "circleci:lint": "npm run lint-files && npm run nsp",
    "circleci:test": "node node_modules/mocha/bin/mocha --max-old-space-size=4096 --harmony test/*.test.js",
    "cover": "node --max-old-space-size=4096 --harmony ./node_modules/istanbul/lib/cli.js cover -x '**/*.runtime.js' node_modules/mocha/bin/_mocha -- test/*.test.js",
    "cover:min": "node --max-old-space-size=4096 --harmony ./node_modules/.bin/istanbul cover -x '**/*.runtime.js' --report lcovonly node_modules/mocha/bin/_mocha -- test/*.test.js",
    "fix": "npm run lint -- --fix",
    "lint": "eslint lib bin hot buildin \"test/**/webpack.config.js\" \"test/binCases/**/test.js\" \"examples/**/webpack.config.js\"",
    "lint-files": "npm run lint && npm run beautify-lint",
    "nsp": "nsp check --output summary",
    "pretest": "npm run lint-files",
    "publish-patch": "npm run lint && npm run beautify-lint && mocha && npm version patch && git push && git push --tags && npm publish",
    "test": "mocha test/*.test.js --max-old-space-size=4096 --harmony --check-leaks",
    "travis:benchmark": "npm run benchmark",
    "travis:lint": "npm run lint-files && npm run nsp",
    "travis:test": "npm run cover:min"
  },
  "version": "3.5.6",
  "web": "lib/webpack.web.js"
}
```

**Comment by jackjoy** [comment]
I'll do a test again and look what will happen.

**Comment by jackjoy** [comment]
I reproduced the problem, i found the issue is package.json cached by verdaccio is wrong.The uplink server used is "http://registry.npm.taobao.org/" , which another verdaccio server worked well with it.

**Comment by jackjoy** [comment]
{
  "_args": [
    [
      {
        "raw": "typescript@>=2.0.0 <2.6.0",
        "scope": null,
        "escapedName": "typescript",
        "name": "typescript",
        "rawSpec": ">=2.0.0 <2.6.0",
        "spec": ">=2.0.0 <2.6.0",
        "type": "range"
      },
      "C:\\Users\\jackjoy\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli"
    ]
  ],
  "_from": "typescript@>=2.0.0 <2.6.0",
  "_hasShrinkwrap": false,
  "_id": "typescript@2.5.2",
  "_inCache": true,
  "_location": "/@angular/cli/typescript",
  "_phantomChildren": {},
  "_requested": {
    "raw": "typescript@>=2.0.0 <2.6.0",
    "scope": null,
    "escapedName": "typescript",
    "name": "typescript",
    "rawSpec": ">=2.0.0 <2.6.0",
    "spec": ">=2.0.0 <2.6.0",
    "type": "range"
  },
  "_requiredBy": [
    "/@angular/cli",
    "/@angular/cli/@angular-devkit/build-optimizer"
  ],
  "_resolved": "http://127.0.0.1:4873/typescript/-/typescript-2.5.2.tgz",
  "_shasum": "038a95f7d9bbb420b1bf35ba31d4c5c1dd3ffe34",
  "_shrinkwrap": null,
  "_spec": "typescript@>=2.0.0 <2.6.0",
  "_where": "C:\\Users\\jackjoy\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli",
  "bin": {
    "tsc": "./bin/tsc",
    "tsserver": "./bin/tsserver"
  },
  "dependencies": {},
  "devDependencies": {
    "@types/browserify": "latest",
    "@types/chai": "latest",
    "@types/convert-source-map": "latest",
    "@types/del": "latest",
    "@types/glob": "latest",
    "@types/gulp": "3.X",
    "@types/gulp-concat": "latest",
    "@types/gulp-help": "latest",
    "@types/gulp-newer": "latest",
    "@types/gulp-sourcemaps": "latest",
    "@types/merge2": "latest",
    "@types/minimatch": "latest",
    "@types/minimist": "latest",
    "@types/mkdirp": "latest",
    "@types/mocha": "latest",
    "@types/node": "latest",
    "@types/q": "latest",
    "@types/run-sequence": "latest",
    "@types/through2": "latest",
    "browserify": "latest",
    "chai": "latest",
    "convert-source-map": "latest",
    "del": "latest",
    "gulp": "3.X",
    "gulp-clone": "latest",
    "gulp-concat": "latest",
    "gulp-help": "latest",
    "gulp-insert": "latest",
    "gulp-newer": "latest",
    "gulp-sourcemaps": "latest",
    "gulp-typescript": "latest",
    "istanbul": "latest",
    "jake": "latest",
    "merge2": "latest",
    "minimist": "latest",
    "mkdirp": "latest",
    "mocha": "latest",
    "mocha-fivemat-progress-reporter": "latest",
    "q": "latest",
    "run-sequence": "latest",
    "sorcery": "latest",
    "through2": "latest",
    "travis-fold": "latest",
    "ts-node": "latest",
    "tslint": "latest",
    "typescript": "next"
  },
  "directories": {},
  "dist": {
    "shasum": "038a95f7d9bbb420b1bf35ba31d4c5c1dd3ffe34",
    "size": 4465075,
    "noattachment": false,
    "tarball": "http://127.0.0.1:4873/typescript/-/typescript-2.5.2.tgz"
  },
  "engines": {
    "node": ">=4.2.0"
  },
  "name": "typescript",
  "optionalDependencies": {},
  "publish_time": 1504197627647,
  "readme": "ERROR: No README data found!",
  "version": "2.5.2"
}

package.json which under node_modules for angular/cli

**Comment by jackjoy** [comment]
The package.json for typescript cached by verdaccio v2.4 is wrong( no "main" field either).I check the uplink server (taobao) with "http://registry.npm.taobao.org/typescript" and the package.json looks good. And we have another verdaccio server ( v2.1.7) use the same config.yaml and works well for serveral moths.

**Comment by jackjoy** [comment]
It's very strange, the package.json in verdaccio cached 'typescript-2.5.2.tgz' is good.

**Comment by jackjoy** [comment]
node version : v6.10.1
npm version: 3.10.10

**Comment by Meeeeow** [comment]
@jackjoy It's look like your registry problem, i have experienced same issue yesterday, by direct using `registry.npm.taobao.org` with npm, the registry returned corrupted JSON data.

/cc @juanpicado

**Comment by juanpicado** [comment]
`npm version: 3.10.10` might be the key.

**Comment by jackjoy** [comment]
verdaccio v2.4 not compatible with npm v3.10.10? I can't imagine why package.json was modified in such a way.

**Comment by Meeeeow** [comment]
@juanpicado @jackjoy See my last comment, verdaccio works fine with npm@3

**Comment by jackjoy** [comment]
@Meeeeow verdaccio v2.1.7/v2.2 works fine ,but v2.4 has such strange issue.  version between 2.2 to 2.4 not tested.

**Comment by Meeeeow** [comment]
@jackjoy Would you like try to set your uplinks registry to `https://registry.npmjs.org` and test it in clean environment such as `Docker` to exclude external factors?

I tested it with image `node:6-alpine` and `verdaccio@2.4.0`, default configure, no cache

**Comment by jackjoy** [comment]
@Meeeeow I just uninstall verdaccio v2.4 and remove all cached packages,then install v2,2, all works fine. Since access to https://registry.npmjs.org is very very slow, so i always use taobao mirror.

**Comment by jackjoy** [comment]
@Meeeeow I'll do a test with  https://registry.npmjs.org

**Comment by jackjoy** [comment]
@Meeeeow @juanpicado It seems verdaccio v2.4 work fine with https://registry.npmjs.org. So it may  be taobao mirror's issue.I just can't understand why v2,2 always work fine.

**Comment by ayusharma** [comment]
One things I have noticed that you have to use `npm install -g @angular/cli` but in the conversation @jackjoy mentioned `npm install -g angular/cli`. 

`npm install -g angular/cli`  produces following error:

```
➜  verdaccio git:(master) ✗ npm install -g angular/cli
npm ERR! git clone --template=/Users/ayush/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/ayush/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: Cloning into bare repository '/Users/ayush/.npm/_git-remotes/git-github-com-angular-cli-git-05516032'...
npm ERR! git clone --template=/Users/ayush/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/ayush/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: ERROR: Repository not found.
npm ERR! git clone --template=/Users/ayush/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/ayush/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/ayush/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/ayush/.npm/_git-remotes/git-github-com-angular-cli-git-05516032:
npm ERR! git clone --template=/Users/ayush/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/ayush/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/ayush/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/ayush/.npm/_git-remotes/git-github-com-angular-cli-git-05516032: and the repository exists.
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/ayush/.nvm/versions/node/v6.10.1/bin/node" "/Users/ayush/.nvm/versions/node/v6.10.1/bin/npm" "install" "-g" "angular/cli"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/ayush/.npm/_git-remotes/_templates --mirror git@github.com:angular/cli.git /Users/ayush/.npm/_git-remotes/git-github-com-angular-cli-git-05516032
npm ERR! Cloning into bare repository '/Users/ayush/.npm/_git-remotes/git-github-com-angular-cli-git-05516032'...
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ayush/xyz/verdaccio/npm-debug.log
```

**Comment by ayusharma** [comment]
I also tested v2.4.0 in docker installation and everything works fine. I used https://registry.npmjs.org as uplink.

**Comment by juanpicado** [comment]
The same here, it must be another reason.

**Comment by jackjoy** [comment]
Finally, i got such experiment result.
With verdaccio v2.2.0:

`GET http://registry.npm.taobao.org/typescript HTTP/1.1 
Accept: application/json                               
Accept-Encoding: gzip                                  
User-Agent: npm (verdaccio/2.2.0)                      
Via: 1.1 9e345b18e8d3 (Verdaccio)                      
host: registry.npm.taobao.org                          
Connection: close                                      
                                                       
                                                       
                                                       
HTTP/1.1 200 OK                                        
Server: nginx/1.4.6 (Ubuntu)                           
Date: Fri, 29 Sep 2017 02:42:59 GMT                    
Content-Type: application/json; charset=utf-8          
Transfer-Encoding: chunked                             
Connection: close                                      
X-Current-Requests: 1                                  
X-ReadTime: 289                                        
Content-Encoding: gzip                                 
                                                       
600a                                                   
`

**Comment by jackjoy** [comment]
With verdaccio v2.4.0:

GET http://registry.npm.taobao.org/typescript HTTP/1.1	
Accept: application/json; q=0.8, */*                    
Accept-Encoding: gzip                                   
User-Agent: npm (verdaccio/2.4.0)                       
Via: 1.1 ed8945aa45ac (Verdaccio)                       
host: registry.npm.taobao.org                           
Connection: close                                       
                                                        
                                                        
                                                        
HTTP/1.1 200 OK											
Server: nginx/1.4.6 (Ubuntu)                            
Date: Fri, 29 Sep 2017 02:23:00 GMT                     
Content-Type: application/json; charset=utf-8           
Transfer-Encoding: chunked                              
Connection: close                                       
X-Current-Requests: 1                                   
X-ReadTime: 134                                         
Content-Encoding: gzip                                  
                                                        
500a

**Comment by jackjoy** [comment]
We can see the request headers for verdaccio v2.2 and v2.4 has three different fields:

- Accept
- User_agent
- Via

such differences cause the registry.npm.taobao.org to return wrong package.json for verdaccio v2.4, but correct for verdaccio v2.2. I just can't understand why.

**Comment by jackjoy** [comment]
And finally i changed "Accept" header in up-storage.js.Now verdaccio v2.4. works fine with registry.npm.taobao.org.

**Comment by juanpicado** [comment]
@jackjoy You just removed `; q=0.8, */*` ?

**Comment by jackjoy** [comment]
@juanpicado YES !!!

**Comment by juanpicado** [comment]
Ok, related https://github.com/verdaccio/verdaccio/pull/295 . I'll removed an publish a new version. For future reference, all users with using JFrog's Artifactory they have to modify headers via configuration file.

**Comment by juanpicado** [comment]
Can you PR that change @jackjoy ?

**Comment by jackjoy** [comment]
Since i don't use git so i can't PR.You can do that just replace 
```const contenTypeAccept = `${jsonContentType}; q=0.8, */*`;```
with 
```const contenTypeAccept = `${jsonContentType}`;```

in up-storage.js

**Comment by juanpicado** [comment]
yes. exactly.

**Comment by juanpicado** [comment]
Fixed on `v.2.5.0`
