### ISSUE TITLE
Broken link in docs: Gitlab CI

### ISSUE THREAD

**Issue by NotWearingPants** [verdaccio/verdaccio#3291]
**Your Environment**
  
 * **verdaccio version**: 5.x.x
 * **node version** [12.x.x, 14.x.x]:
 * **package manager**: [npm@7, pnpm@6, yarn@2]
 * **os**: [mac, windows@10, linux]
 * **platform**: [npm, docker, helm, other]

**Describe the bug**

There's a broken link in the docs, the link to `Gitlab CI` in [the CI page](https://verdaccio.org/docs/ci/).
Also, this bug template makes it really hard to report this kind of bug, but also warns me not to delete it. Is there a different template for problems with the docs?

**To Reproduce**

**Expected behavior**

I'm not sure what information is supposed to be in this link, so I don't know what should replace it.

**Screenshots, server logs, package manager log**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
hi @NotWearingPants thanks for report it.

> this bug template makes it really hard to report this kind of bug, but also warns me not to delete it.

I don't understand this.

> There's a broken link in the docs, the link to Gitlab CI in [the CI page](https://verdaccio.org/docs/ci/).

Since there is no replacement I think we can just remove it, wanna PR?

**Comment by juanpicado** [comment]
@Suryaprakash1024 I don't understand what you men, could you elaborate?

**Comment by NotWearingPants** [comment]
@juanpicado Awesome, I opened a PR

About the template, I suggest adding a new issue template (in `/.github/ISSUE_TEMPLATE/`) for issues about docs, what do you think? Also the link for `User Interface Report` when opening an issue is broken.

**Comment by juanpicado** [comment]
@NotWearingPants make sense we can try :) go ahead
