### ISSUE TITLE
Files sync'd with S3

### ISSUE THREAD

**Issue by nwhite89** [verdaccio/verdaccio#33]
I am currently planning on having my package files sync'd with S3 in order to back the files up. Running with Sinopia still at the moment using Docker and the packages are mounted. For backing up I am in two minds cronjob doing the syncing but what would be really cool is that this be done automatically on a publish.

Wondering what your thoughts are on this as a possible feature added on to `verdaccio` with it being optionally used.

**Comment by juanpicado** [comment]
Related #103

**Comment by juanpicado** [comment]
`verdaccio` will have soon pluggable storage. Then any developer might create a new one to replace the local storage (https://github.com/verdaccio/verdaccio/pull/291) by any adapter more suitable with S3.

Please follow https://github.com/verdaccio/verdaccio/issues/169 instead. I'll close this one.
