### ISSUE TITLE
installation tracking

### ISSUE THREAD

**Issue by cwmoo740** [verdaccio/verdaccio#330]
### Feature Suggestion

I'd like to track installations of projects in verdaccio by user to see which users/projects are installing which versions of libraries. 

This may just be a documentation task, and it's probably possible to do with a plugin, but guidance would be helpful.

**Comment by juanpicado** [comment]
Interesting, it seems like an Auth plugin. There is not development plugin documentation yet (https://github.com/verdaccio/verdaccio/issues/302) but you can ask whatever you want and perhaps it becomes a future documentation.
Related https://github.com/verdaccio/verdaccio/issues/169

**Comment by juanpicado** [comment]
Hi, after version `2.7.x` a middleware plugin feature was included, to achieve this request I'd suggest creating a middleware plugin for such functionality. 

http://www.verdaccio.org/docs/en/dev-plugins.html#middleware-integration

If you have further questions, let us know.
