### ISSUE TITLE
efile  error while installing socket.io

### ISSUE THREAD

**Issue by harshendra181** [verdaccio/verdaccio#333]
ok let me explain we have a server 11.11.11.11(os-windows 2012 r2) we hv installed node js on this server.
Now we are trying to install Socket.io by command npm install socket.io -g
we are trying to install from commond promt
we hv set the proxy as http://proxyip:port and strict-ssl as false and registr as http://registry.npms.org/"

kindly let me now if you want any other detail

**Comment by juanpicado** [comment]
Please, include

* npm, node version
* config file
* environment details
* error stack strace
* steps to reproduce

**Comment by jachstet-sea** [comment]
And please also tell us on which machine you set up verdaccio :) Is it in the same network as the machine you want to install socket.io on or is it behind the proxy as well?

**Comment by juanpicado** [comment]
I'll close it for inactivity. If the issue persists ask for reopening.
