### ISSUE TITLE
Web user interface don't open in Internet Explorer 11

### ISSUE THREAD

**Issue by tobitux** [verdaccio/verdaccio#334]
#### My reason:

Web user interface don't open in Internet Explorer 11 because of JavaScript error in api.js (46,9).

Internet Exploer doesn't support String.prototype.startsWith().

#### Steps to reproduce:

1. Open web user interface in Internet Explorer 11

Environment: Window 10, Internet Explorer 11.608.15063.0

####  App Version:	

Verdaccio 2.4.0

**Comment by juanpicado** [comment]
Testing

* Microsoft Edge (14.14393) 👍

**Comment by juanpicado** [comment]
This helps to test this kind of use cases:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by juanpicado** [comment]
It should works when `v2.4.1` is available.
![screen shot 2017-10-01 at 2 03 31 pm](https://user-images.githubusercontent.com/558752/31054365-6905ebc8-a6b1-11e7-8551-3bd19e1578b9.png)
