### ISSUE TITLE
Prebuilt npm packages are not downloaded for Windows 10

### ISSUE THREAD

**Issue by anon-mirror** [verdaccio/verdaccio#3388]
**Your Environment**
 * **verdaccio version**: 5.15.3
 * **node version** :18.9.0
 * **package manager**: npm@8.19.1
 * **os**: windows@10
 * **platform**: npm

**Describe the bug**

Without verdaccio it's possible to install npm package with prebuild binaries, e.g. bufferutil.
<>
npm i bufferutil
added 17 packages, and audited 18 packages in 6s
found 0 vulnerabilities
<>

When verdaccio is used, npm cannot detect that prebuilt binaries for my environment exist and tries to build them from source, which I don't want to happen.

**To Reproduce**

1. Use WIndows 10
2. Run verdaccio (default configuration)
3. Configure npm registry to http://localhost:4873 
4. Try to install bufferutil package (npm i bufferutil)
5. Observe that npm tries to build bufferutil from sources

**Expected behavior**

npm+verdaccio detect that binary package of bufferutil for my environment exists and download it

**Screenshots, server logs, package manager log**

npm log attached

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

Environment Info:
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  Virtualization:
    Docker: 20.10.13 - C:\ProgramData\chocolatey\bin\docker.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks): ATTACHED
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints: http://localhost:4873/

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇 

[npm-i-log.txt](https://github.com/verdaccio/verdaccio/files/9605240/npm-i-log.txt)
[verdaccio-request.txt](https://github.com/verdaccio/verdaccio/files/9605313/verdaccio-request.txt)

**Comment by juanpicado** [comment]
Works for me, your problem is other. I'd check the logs.
```
pm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
```
