### ISSUE TITLE
verdaccio resolves versions of unplubished versions of npm.js packages

### ISSUE THREAD

**Issue by rasenfer** [verdaccio/verdaccio#3389]
**verdaccio version**: 5.8.0
 **node version** [14 - 16]:
 **package manager**: [npm@6 - npm@8]
 **os**: [windows@10, linux]
 **platform**: [npm, node:14-alpine]
 
Verdaccio resolves versions o a previously downloaded, but actually unplubished version, of a package from central npm.js.

Example:
- our project uses colors@^1.4.0
- colors uses node-ipc@^9.0.0
- Arround six month ago a npm install resolves colors@1.4.2 and node-ipc@9.2.2 and install works.
- Now colors@1.4.2 and node-ipc@9.2.2 are deleted from central npm.js but npm install tries to download it (also with package-lock.json deleted). 
Errors:
 Not Found - GET http://verdaccio.xxxxxxxxx/colors/-/colors-1.4.2.tgz
 Not Found - GET http://verdaccio.xxxxxxxxx/node-ipc/-/node-ipc-9.2.2.tgz
But install works if we do NOT use verdaccio as global registry and uses previous versions of those packages.
- If we launch "npm view colors versions" using verdaccio as global registry 1.4.2 appears.
- If we launch "npm view colors versions" NOT using verdaccio as global registry 1.4.2 NOT appears.
- If we launch "npm view node-ipc versions" using verdaccio as global registry 9.2.2 appears.
- If we launch "npm view node-ipc versions" NOT using verdaccio as global registry 9.2.2 NOT appears.

We solve this launching .
npm unpublish colors@1.4.2 --force
npm unpublish node-ipc@9.2.2 --force
And for any others packages with the same problem [colors@1.4.1, node-ipc@9.2.1, ...]

But we think that verdaccio its caching versions in bad way and should not response with deleted versions of central.

**Comment by juanpicado** [comment]
Hi Ruben,

btw, I clean up your logs, please be careful don't post sensitive information.

> Verdaccio resolves versions o a previously downloaded, but actually unplubished version, of a package from central npm.js.

I know this `colors@1.4.2` problem, I had the same situation with other proxies, what I recommend is just go to the storage and remove the `colors` folder manually, next time is proxied the colors won't be anymore. 

On next major will be some improvements regarding filtering packages, still not in place but I'll definitely add something easy to add to the configuration, but until then I recommend what I described above.

**Comment by rasenfer** [comment]
Ok, thanks for you response, and for the cleaning too (copy paste oversight), fortunately are local only dns hosts.

**Comment by juanpicado** [comment]
If you want also to avoid installing dependencies don't want, then I'd recommend using 

- [npm (overrides)](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)
- [pnpm (overrides)](https://pnpm.io/package_json#pnpmoverrides)
- [yarn (resolutions)](https://yarnpkg.com/configuration/manifest#resolutions)
