### ISSUE TITLE
 Publish Canary Version

### ISSUE THREAD

**Issue by ramonornela** [verdaccio/verdaccio#339]
#### My reason:
I think it's interesting exists a tag npm to use in development, see: https://martinfowler.com/bliki/CanaryRelease.html.
Something like:
```npm install verdaccio@canary```

There is verdaccio@beta, but do not see in NPM scripts.

Example canary version ionic-cli ```npm info ionic``` return 
```
{ latest: '3.12.0',
     canary: '3.13.0-alpha.36fd2f37', // use commit sha1
     next: '3.0.0',
     legacy: '2.2.3',
     testing: '3.8.0-testing.15a83d68' },
```

**Comment by juanpicado** [comment]
many things still are not automated as that "beta" version. Any suggestion how to add a suffix in order to deploy automatically from circleCI?

**Comment by ramonornela** [comment]
Later I will work on a patch

**Comment by juanpicado** [comment]
We have a canary version already in Docker https://hub.docker.com/r/verdaccio/verdaccio/builds/bi45qtrze76deqqfeqph7n/

**Comment by juanpicado** [comment]
I considered this fixed. Please read

https://github.com/verdaccio/verdaccio#future-releases

```bash
npm install -g verdaccio@alpha
```
For further information

```bash
npm info verdaccio
```
