### ISSUE TITLE
Two "Search" options in header

### ISSUE THREAD

**Issue by mbtools** [verdaccio/verdaccio#3396]
**Your Environment**

 * **verdaccio version**: nightly-master, 5.15.3
 * **platform**: docker

**Describe the bug**

The header shows two options for searching. It's not clear which one is the correct, intended one and which should be removed.

https://github.com/verdaccio/verdaccio/blob/722c88b1d68aa9aa653adc87357d11126ccd7cb2/packages/plugins/ui-theme/src/App/Header/Header.tsx#L32-L47

**To Reproduce**

Start Web UI

**Expected behavior**

One search option is sufficient. If we keep both, they should be tied to different config settings.

**Screenshots, server logs, package manager log**

![image](https://user-images.githubusercontent.com/59966492/192147745-73639454-e92a-4b76-9c4f-e70daf920f87.png)

**Contribute to Verdaccio**

- [x] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
For context, there is two headers, one for mobile and desktop, in theory, they should not be displayed at the same time, so I guess the bug could be fixed either with some with something like https://usehooks-ts.com/react-hook/use-media-query or similar solutions, anyhow is fixed still we need 2.
