### ISSUE TITLE
Apply Git Flow

### ISSUE THREAD

**Issue by ramonornela** [verdaccio/verdaccio#340]
#### My reason:

Apply git flow in project https://danielkummer.github.io/git-flow-cheatsheet/.

It's interesting to use because it can block the branch master as well as gitlab see: https://help.github.com/articles/configuring-protected-branches/, and branch develop all cobarators has access.
This help publish canary version with branch develop #339 with [CircleCI](https://circleci.com/docs/1.0/environment-variables/) with variable name CIRCLE_BRANCH.

**Comment by juanpicado** [comment]
Perhaps is not the best approach, but it works.
https://circleci.com/docs/1.0/configuration/#deployment

Feel free to suggest improvement at any moment.
