### ISSUE TITLE
Docker volumes: "no such file or directory, open '/verdaccio/conf/config.yaml"

### ISSUE THREAD

**Issue by kvolkovich-sc** [verdaccio/verdaccio#341]
OS: Ubuntu 16.04
Docker version 17.05.0-ce

If don't specify volume (no `-v` flag), it works.

But if specify volume:

`docker run --rm -it --name verdaccio -v /home/user/verdaccio-data:/verdaccio -p 4873:4873 verdaccio/verdaccio:2.5.1`

Output:

`fatal--- cannot open config file /verdaccio/conf/config.yaml: ENOENT: no such file or directory, open '/verdaccio/conf/config.yaml'`

**Comment by juanpicado** [comment]
You are trying to override what is defined inside of the Image. Please read https://github.com/verdaccio/verdaccio/blob/master/wiki/docker.md#running-verdaccio-using-docker. 

If you analyze the Dockerfile in detail

```
RUN mkdir -p /verdaccio/storage /verdaccio/conf
...
ADD conf/docker.yaml /verdaccio/conf/config.yaml
...
VOLUME ["/verdaccio"]
```
thus, if you override the whole volume, then, **you have to provide the configuration file by your own**. 

To solve your issue:

```
mkdir -p /home/user/verdaccio-data/conf
mkdir -p /home/user/verdaccio-data/storage
touch /home/user/verdaccio-data/conf/config.yaml // of course fill this file
```

**Comment by kvolkovich-sc** [comment]
Thanks.

**Comment by mauron85** [comment]
@juanpicado do I understand it correctly, that verdcaccio package and it's dependencies are installed directly into container into folder:  /usr/local/app
and configuration and storage for cached npm packages is on volume `/verdaccio`?

**Comment by juanpicado** [comment]
Yeah, you are right according to the Dockerfile

```
ENV APPDIR /usr/local/app
...
RUN mkdir -p /verdaccio/storage /verdaccio/conf
```
