### ISSUE TITLE
Not Found: @verdaccio/file-locking^0.0.3

### ISSUE THREAD

**Issue by gleb-svechnikov** [verdaccio/verdaccio#342]
#### My reason:

I cannot install verdaccio. 
npm returns error:

> npm ERR! code E404
> npm ERR! 404 Not Found: @verdaccio/file-locking^0.0.3
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!         /home/gsvechnikov/.npm/_log/2017-10-02T14_08_34_462Z-debug.log

#### Steps to reproduce:

`npm install --global verdaccio`

####  App Version:	
node v8.6.0
npm v5.3.0
OS Linux version 3.16.0-4-amd64
Debian 3.16.39-1 (2016-12-30)

**Comment by juanpicado** [comment]
```
➜ npm info @verdaccio/file-locking
 
{ name: '@verdaccio/file-locking',
  'dist-tags': { latest: '0.0.3' },
  versions: [ '0.0.1-beta', '0.0.1', '0.0.2', '0.0.3' ],
  maintainers: [ 'jotadeveloper <juanpicado19@gmail.com>' ],
  time: 
   { modified: '2017-07-08T14:07:19.907Z',
     created: '2017-07-06T05:34:06.019Z',
     '0.0.1-beta': '2017-07-06T05:34:06.019Z',
     '0.0.1': '2017-07-08T09:16:42.411Z',
     '0.0.2': '2017-07-08T12:23:03.353Z',
     '0.0.3': '2017-07-08T14:07:19.907Z' },
  keywords: [ 'lock', 'fs' ],
  author: 'Juan Picado <juanpicado19@gmail.com>',
  license: 'MIT',
  readmeFilename: '',
  description: 'library that handle file locking',
  version: '0.0.3',
  main: 'lib/index.js',
  devDependencies: 
   { 'babel-cli': '6.24.1',
     'babel-core': '6.25.0',
     'babel-plugin-istanbul': '4.1.4',
     'babel-polyfill': '6.23.0',
     'babel-preset-es2015': '6.24.1',
     'babel-require': '1.0.1',
     'cross-env': '5.0.1',
     eslint: '4.1.1',
     'eslint-config-google': '0.9.1',
     mocha: '3.4.2',
     nyc: '11.0.3' },
  private: false,
  dependencies: 
   { 'babel-polyfill': '6.23.0',
     lockfile: '1.0.3',
     lodash: '4.17.4' },
  nyc: 
   { include: [ 'src/**/*.js' ],
     all: true,
     cache: true,
     sourceMap: false,
     instrument: false,
     'report-dir': './tests-report',
     reporter: [ 'text', 'html' ] },
  scripts: 
   { test: 'npm run lint && mocha --require babel-polyfill  --compilers js:babel-core/register ./test/**/*.spec.js',
     lint: 'eslint .',
     build: 'babel src/ --out-dir lib/ --copy-files',
     cover: 'cross-env NODE_ENV=test nyc npm t' },
  engines: { node: '>=4.6.1', npm: '>=2.15.9' },
  gitHead: 'aec06aa291e710979e50357647a7b48143023d59',
  dist: 
   { integrity: 'sha512-AW33KbRZ3xAEZzFgnYnMdXrvj2LniqqUqHyMPAxytRvpeGnZj208SqtEiuzrkzNOn4EzSeKglbyg83Hc0jRF3g==',
     shasum: '32d3702ff5184d1d3893f0f1d47629ad33d1c113',
     tarball: 'https://registry.npmjs.org/@verdaccio/file-locking/-/file-locking-0.0.3.tgz' },
  directories: {} }
```
```
 npm i @verdaccio/file-locking@0.0.3
npm WARN nyc-typescript-trouble@1.0.0 No repository field.

+ @verdaccio/file-locking@0.0.3
added 8 packages in 6.028s
```

**Comment by gleb-svechnikov** [comment]
$ npm i @verdaccio/file-locking@0.0.3

> npm ERR! code E404
> npm ERR! 404 Not Found: @verdaccio/file-locking@0.0.3
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/gsvechnikov/.npm/_logs/2017-10-02T15_29_08_553Z-debug.log
> 

$ cat /home/gsvechnikov/.npm/_logs/2017-10-02T15_29_08_553Z-debug.log

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node',
> 1 verbose cli   '/usr/bin/npm',
> 1 verbose cli   'i',
> 1 verbose cli   '@verdaccio/file-locking@0.0.3' ]
> 2 info using npm@5.4.2
> 3 info using node@v8.6.0
> 4 verbose npm-session bb4504ac693368be
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 http fetch GET 404 http://172.16.49.209:4873/@verdaccio%2ffile-locking 432ms
> 8 silly fetchPackageMetaData error for @verdaccio/file-locking@0.0.3 404 Not Found: @verdaccio/file-locking@0.0.3
> 9 verbose stack Error: 404 Not Found: @verdaccio/file-locking@0.0.3
> 9 verbose stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
> 9 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
> 9 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
> 9 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
> 9 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
> 9 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
> 9 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
> 9 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
> 9 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
> 9 verbose stack     at runCallback (timers.js:781:20)
> 9 verbose stack     at tryOnImmediate (timers.js:743:5)
> 9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
> 10 verbose cwd /home/gsvechnikov/Code
> 11 verbose Linux 3.10.0-693.2.2.el7.x86_64
> 12 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "@verdaccio/file-locking@0.0.3"
> 13 verbose node v8.6.0
> 14 verbose npm  v5.4.2
> 15 error code E404
> 16 error 404 Not Found: @verdaccio/file-locking@0.0.3
> 17 verbose exit [ 1, true ]
>

**Comment by gleb-svechnikov** [comment]
I think I got this, I'm using Sinopia and trying to change to Verdaccio, seems like Sinopia somehow interfere with it, I'll try to remove it first.
