### ISSUE TITLE
Unable to load Verdaccio UI

### ISSUE THREAD

**Issue by sarathkcm** [verdaccio/verdaccio#344]
#### My reason:

	<verdacciourl>/-/verdaccio/packages call fails with "500 Internal server error". See screenshot
![image](https://user-images.githubusercontent.com/14143311/31233488-b5265f7a-a9e4-11e7-819a-44b11b7e7d15.png)

#### Steps to reproduce:

	(if it applies)
	Open Verdaccio.

#### Additional information:

	I will give detailed logs if required. Right now don't have access to the server in which it is deployed.
	
 Windows
  - Container:
     Deployed in a server which is present in the same network.

**Comment by juanpicado** [comment]
I'll need more than that. 
* version
* server log
* exact error
* config file

I'm a quick test, works fine for me. It might be file permissions issues in your server.

**Comment by sarathkcm** [comment]
I will share these details tomorrow. Just to add, npm install and npm publish works without any issues.

**Comment by juanpicado** [comment]
@sarathkcm any feedback?

**Comment by sarathkcm** [comment]
@juanpicado sorry  I couldn't get the logs. Will try and get today.

**Comment by sarathkcm** [comment]
I asked for the logs from the team who maintains the server. They did something and it is working now. I guess the issue can be closed.

**Comment by juanpicado** [comment]
Thanks @sarathkcm for the feedback
