### ISSUE TITLE
Connection to registry.npmjs.org not closed after fetching package

### ISSUE THREAD

**Issue by pboguslawski** [verdaccio/verdaccio#3458]
**Your Environment**
  
 * **verdaccio version**: 5.15.4
 * **node version**: `12.22.5~dfsg-2~11u1` from Debian 11
 * **os**: linux

**Describe the bug**

After fetching package from registry.npmjs.org via verdaccio, verdaccio keeps connection to registry.npmjs.org open. 

**To Reproduce**

Start verdaccio configured with fetching packages from registry.npmjs.org; fetch any package and use tcpdump/iptraf to observe that HTTPS connection from verdaccio to registry.npmjs.org is not closed and some data is still transmitted (keep alives maybe?).

**Expected behavior**

verdaccio should close its client connection to  registry.npmjs.org ASAP after fetching package.

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by mbtools** [comment]
AFAICT, this works as designed. The behavior is driven by `agent_options` in the [uplink config](https://verdaccio.org/docs/next/uplinks/#configuration) which has a default of `keep_alive: true`:

https://github.com/verdaccio/verdaccio/blob/a3cf3e7921a8954499c0149af1c015ee5105e26c/packages/proxy/src/proxy.ts#L130-L134

You can change the setting as follows:

```yml
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    agent_options:
      keepAlive: false
```

**Comment by pboguslawski** [comment]
Thank you for explanation.
