### ISSUE TITLE
npm install 500 internal server error uplink is offline

### ISSUE THREAD

**Issue by nicky132** [verdaccio/verdaccio#3490]
**Your Environment**
  
 * **verdaccio version**: Docker version 20.10.17, build 100c701
 * **node version** [12.x.x, 14.x.x]:v14.17.5
 * **package manager**: [npm@6, yarn@1]
 * **os**: [CentOS Linux release 7.9.2009 (Core)]
 * **platform**: [docker]

**Describe the bug**
<img width="873" alt="lALPJwY7VJIjAZ_M1M0G0g_1746_212" src="https://user-images.githubusercontent.com/34881461/200994678-4063e665-a1c0-4f3a-937d-3288c95142a1.png">
![1668051707268_59701E21-264C-4a7e-AAC3-D01603A9D029](https://user-images.githubusercontent.com/34881461/200995459-14beb0cd-6531-4b05-a59e-972a1eb332f3.png)

**To Reproduce**

**Expected behavior**

**Screenshots, server logs, package manager log**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
That error is normal if there is no connection, you are using docker so might have other issues, that's what I got from the little info you have provided, hope it helps.
