### ISSUE TITLE
Google OAuth?

### ISSUE THREAD

**Issue by geekdave** [verdaccio/verdaccio#353]
#### My reason:

For companies that use Google Apps & OAuth for authentication

#### Request:

Allow logging into verdaccio with Google OAuth, so users don't need a specific verdaccio username/password.

**Comment by juanpicado** [comment]
Since an authentication method must be a plugin, to fix this issue it has to be done in a separate repository. We will close this issue until pops up any proposal.

**Comment by rostislav-simonik** [comment]
To create auth plugins with oauth flows, it must must be allowed for plugins to register own middleware, which has already been implemented in sinopia2 fork. 

[makes middlewares pluggable. i.e for custom oauth flows or analytics etc. #18](https://github.com/fl4re/sinopia/pull/18/commits/adcc42dd2c4288ab9b6a2b86abd5a9da4815c6aa#diff-6d186b954a58d5bb740f73d84fe39073)

**Comment by rostislav-simonik** [comment]
Afterwards this plugin [sinopia-github-oauth](https://github.com/soundtrackyourbrand/sinopia-github-oauth) can be easily transformed into bitbucket-oauth and also for other oauth providers.

**Comment by juanpicado** [comment]
Well, there is an easy PR if someone is willing to contribute 👍
