### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by splincode** [verdaccio/verdaccio#356]
#### My reason:

I'm running command and not working then

```bash
$ verdaccio
 warn --- config file  - /home/user/.config/verdaccio/config.yaml
 warn --- http address - http://localhost:4873/ - verdaccio/2.5.1
```

When I try to go from another machine to the address, there is no access
```bash
$ curl http://192.168.137.103:4873
curl: (7) Failed to connect to localhost port 4873: Connection refused
```
But web-server is running!

#### Additional information:

	
 - `$  node -v v8.7.0
 - `$ npm -v 5.4.2
 - `$ npm get prefix
 - /home/user/.npm-global
 - Ubuntu 16?:
 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
 - default

#### Additional verbose log: not shown

**Comment by juanpicado** [comment]
`4783`? ;)

**Comment by splincode** [comment]
@juanpicado Sorry, this is a typo. I wanted to say that I can not remotely connect to the server, because I usage .npmrc in my project.

.npmrc
```text
registry = http://192.168.137.103:4873/
```

**Comment by splincode** [comment]
If I run a server command on the local machine where the server is running

```bash
$ curl http://localhost:4873
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <title>Verdaccio</title>
    <link rel="icon" type="image/png" href="http://localhost:4873/-/static/favicon.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script>
        window.VERDACCIO_API_URL = 'http://localhost:4873/-/verdaccio/';
    </script>
<link href="http://localhost:4873/-/static/style.8410f14de467c42d2f6c14c7df197f3f.css" rel="stylesheet"></head>
<body class="body">
    <div id="root"></div>
<script type="text/javascript" src="http://localhost:4873/-/static/main.e9a5121f39c3bec2f828.js"></script></body>
</html>
```

**Comment by splincode** [comment]
Please, add default settings by listen on all addresses

config.yaml
```
listen:
  - 0.0.0.0:4873
```

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/blob/master/wiki/config.md#listen-port

**Comment by shierro** [comment]
on my EC2 instance case, **http://localhost:4873(which is the default)**didn't work. **http://0.0.0.0:4873** which is mentioned above did
