### ISSUE TITLE
package ban list

### ISSUE THREAD

**Issue by joebnb** [verdaccio/verdaccio#3562]
recently npm poisoning more and more common,if there is a ban list to refuse user visit malicious packages would be better. 

this feature need satisfy ban the package and ban some package specified version and regex expression  supported.

please consider this to make this software have some anti-malware protect functions

**Comment by juanpicado** [comment]
Seems you need this https://www.npmjs.org/verdaccio-plugin-secfilter

**Comment by joebnb** [comment]
> Seems you need this https://www.npmjs.org/verdaccio-plugin-secfilter
> 
> source: https://verdaccio.org/dev/plugins-search

yes, thank you for reply

**Comment by joebnb** [comment]
have a good day

**Comment by juanpicado** [comment]
@joebnb give it a try and would be great to have feedback, maybe we can include it as dependency if is good enough

**Comment by joebnb** [comment]
> @joebnb give it a try and would be great to have feedback, maybe we can include it as dependency if is good enough

ok, I will give feedback after use it,it's probably  in a few months
