### ISSUE TITLE
Allow use custom theme

### ISSUE THREAD

**Issue by ASHV95** [verdaccio/verdaccio#357]
#### My reason:
Hello I have two issues
1) Can we change the logo or i mean can we set our own wallpaper for the local npm repo created ?

2) When i connect to the local npm and then fire npm install <package > , the package gets installed on my machine , is there any way in which only registered users can install packages on their local machines and not anyone who connects to the rep without loging in.
 

#### Additional information:

	
 - `$ set DEBUG=express:* verdaccio` enable extreme verdaccio debug mode
 - `$ npm --verbose` prints:
 - `$ npm config get registry` prints:
 - Verdaccio terminal output
 - Windows, OS X/macOS, or Linux?:
 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
 
 - Container:
   - I use local environment
   - I develop / deploy using Docker.
   - I deploy to a PaaS.

**Comment by ayusharma** [comment]
Yes, You can change logo

```
web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false

  title: Verdaccio

  logo: <specify-url-for-your-logo>
```

in your config.yaml

**Comment by juanpicado** [comment]
Answer point #2 https://github.com/verdaccio/verdaccio/blob/master/wiki/recipes/protect-your-dependencies.md

**Comment by juanpicado** [comment]
When you say `wallpaper` I guess you refer to the `theme` right? @ASHV95

**Comment by ASHV95** [comment]
yes exactly the theme, the background

**Comment by ASHV95** [comment]
i want to put my organizations logo or theme to the npm local repo

**Comment by lgaitan** [comment]
Is anyone responsible for this feature request? I'd be happy to work on it

**Comment by juanpicado** [comment]
Be my guest :-) all yours

**Comment by keerthivasan-r** [comment]
@lgaitan  How are you planning to do this? I can also contribute to theme functionalities. Is it we are going to give different themes for the user to make a choice in the configuration?

**Comment by juanpicado** [comment]
As a choice, default theme unique should change is logo and title. And perhaps icon and some minor custom stuff.

**Comment by juanpicado** [comment]
@lgaitan ping

**Comment by lgaitan** [comment]
The only way i've think to do it is to accept a path to a css file and then embed it on the html.

something like: 
```yaml
webui:
  logo: logo.png
  theme: path-to/custom-theme.css
```

Since the project use sass, we could provide some mixins for making theming easier.

I think this is the best way to do it, and maybe the only one.

**Comment by juanpicado** [comment]
I like the configuration, simple and easy. I haven't checked implementation yet, but, we deliver static file (index.html) and express only serve such static file. I wonder how we can makes this compatible with such configuration.

**Comment by juanpicado** [comment]
cc: @securedeveloper
