### ISSUE TITLE
Error: Cannot find module 'get-port'

### ISSUE THREAD

**Issue by SimonSiefke** [verdaccio/verdaccio#3574]
**Your Environment**
  
 * **verdaccio version**: 6.0.0-6-next.54
 * **node version** 18.13.0
 * **package manager**: npm 8.19.3
 * **os**: linux
 * **platform**: npm

**Describe the bug**

When using the `runServer` function from the verdaccio nodejs api, the process exits immediatly with an error `Error: Cannot find module 'get-port'`.

```js
// index.js
import { runServer } from "verdaccio";
```

**To Reproduce**

See https://github.com/SimonSiefke/verdaccio-bug

**Expected behavior**

Verdaccio can be imported without errors.

**Screenshots, server logs, package manager log**

This is the output when running `node index.js`:

```
node:internal/modules/cjs/loader:1039
  const err = new Error(message);
              ^

Error: Cannot find module 'get-port'
Require stack:
- /tmp/verdaccio-bug/node_modules/verdaccio/build/server/registry.js
- /tmp/verdaccio-bug/node_modules/verdaccio/build/server/index.js
- /tmp/verdaccio-bug/node_modules/verdaccio/build/index.js
```

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

Environment Info:
  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.74

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
Thanks I also noticed, on my lists. Are you testing v6 or how did you get there if I may ask.

**Comment by SimonSiefke** [comment]
Vscode highlights deprecated code with strike-through.

![strike-through](https://user-images.githubusercontent.com/23744935/214031630-0bce7713-5478-4c7f-93a4-bb178fcea63a.png)

 I was trying to update that code to the latest version (v6) - but it's not urgent or anything. :)

**Comment by juanpicado** [comment]
Thanks for raising it, it helps to improve the software, currently I am trying to improve 5.x versions so can take the best of 6.x versions, less those errors 😅.

**Comment by juanpicado** [comment]
> Vscode highlights deprecated code with strike-through.
> 
> ![strike-through](https://user-images.githubusercontent.com/23744935/214031630-0bce7713-5478-4c7f-93a4-bb178fcea63a.png)
> 
> I was trying to update that code to the latest version (v6) - but it's not urgent or anything. :)

You can use also another API which is available in v5 similar to v6 , check https://verdaccio.org/docs/verdaccio-programmatically/#using-the-module-api

```
 const {runServer} = require('verdaccio');
    const app = await runServer(); // default configuration
    const app = await runServer('./config/config.yaml');
    const app = await runServer({ configuration });
    app.listen(4000, (event) => {
      // do something
    });
```

Same shape, it was added in order to facilitate v6 migration, the other one is deprecated should be not longer used.
