### ISSUE TITLE
How to set permission for _uplinks_

### ISSUE THREAD

**Issue by hukacode** [verdaccio/verdaccio#358]
#### My reason:
Hi guys,

I want only admin can fetch from _uplinks_, and the client can only get from Verdaccio. How do I config for that?
Thanks in advance!

Regards,
Huka.

**Comment by Meeeeow** [comment]
No such feature at this time

**Comment by hukacode** [comment]
Hi, @Meeeeow 

Thanks for quick reply, I really appreciate it.

Can I remove _uplink_, and add by manual?
Put modules to:
C:\Users\[User]\AppData\Roaming\npm\node_modules
C:\Users\[User]\AppData\Roaming\verdaccio\storage

Regards,
Huka.

**Comment by juanpicado** [comment]
What do you mean with **manual**? Could you elaborate a bit more your idea?

**Comment by hukacode** [comment]
Hi, @juanpicado 

I'm sorry for my mistake.
All I need to do are remove _uplink in _config.yaml_ and download a git repository (e.g. Angular CLI), then run _npm publish_

Thank you so much for helping me!

Regards,
Huka.

**Comment by ayusharma** [comment]
I think @hukacode want to install packages from some directory or repository. Am I getting it right?

**Comment by hukacode** [comment]
Hi, @ayusharma 
Yes, that is what I want. I just download the repository and run _npm publish_
It works like a charm. :)

**Comment by juanpicado** [comment]
@hukacode that will work well only for those repositories that have a no-published version defined on master branches.  I would imagine that should be the case of 99% all projects. Also, you should keep in mind `verdaccio` always check previous publish a private package whether exist already in any of the uplinks. 

So, for instance, if you try to publish a specific version of `webpack@3.1.x` and exist already in any of uplinks, the `npm publish` will fails (if I'm not wrong).

**Comment by hukacode** [comment]
@juanpicado Thank you for your information.
My boss's requirement is to build a private local repository server. And he wants to control what modules installed on this. (To control license)
That why I created this issue, only admin can fetch data from official, while the developer can fetch only from Verdaccio.
I really really appreciate your efforts.

Regards,
Huka

**Comment by juanpicado** [comment]
Thanks for your feedback @hukacode . I understand how strict can be some companies with licenses. It seems a nice feature that might be quite voted. I'd recommend you elaborate more your main entry in order to get more attention from the audience.

Furthermore, if your company is concerned about licenses, you might be interested in this thread https://github.com/verdaccio/verdaccio/issues/224

**Comment by hukacode** [comment]
Thank you for discussing with me. I'm a Java developer, so I cannot improve Verdaccio.
Have a good day!

Best regards,
Hung.

**Comment by fly2015** [comment]
hi guys
I have the same problems as @hukacode 
Please make role for only admin can fetch from Official npm link  @juanpicado 
I'm also looking forward to this feature.

Thanks a lot and best regards.
