### ISSUE TITLE
SSL certificates in pfx format

### ISSUE THREAD

**Issue by wiggisser** [verdaccio/verdaccio#359]
Working in a windows based environment, I would like to use my pfx certificate which I use in IIS also with verdaccio, but a quick glimpse in the code showed me, that this is not supported ...

As node also supports pfx (even with a certificate chain) it should be quite easy to support this also in verdaccio

**Comment by juanpicado** [comment]
Yes, you are right, but, It should hard to implement.

https://nodejs.org/api/https.html

Here an example. Supported since Node4. 

```
const https = require('https');
const fs = require('fs');

const options = {
  pfx: fs.readFileSync('test/fixtures/test_cert.pfx'),
  passphrase: 'sample'
};

https.createServer(options, (req, res) => {
  res.writeHead(200);
  res.end('hello world\n');
}).listen(8000);
```
