### ISSUE TITLE
Markdown checkboxes are rendered in a broken way

### ISSUE THREAD

**Issue by SanderRonde** [verdaccio/verdaccio#3590]
**Your Environment**
  
 * **verdaccio version**: 5.15.4-1
 * **node version**: 16.2.0
 * **package manager**: yarn@1.22.19
 * **os**: linux
 * **platform**: npm

**Describe the bug**

Markdown checkboxes are not displayed correctly. Any markdown checkbox in a README file (for example:)
```md
Changelog:
- [ ] Some entry
```

Is displayed as `<input type="checkbox" disabled="" checked=""> Some entry`. Note that this is not displayed as HTML, but this HTML content is displayed as raw text. It seems to both parse them as checkboxes and turn them into HTML, but then it escapes the HTML and just renders it plainly instead of as a checkbox.

**To Reproduce**

- Create a package
- Add the following the README.md file:
```md
Changelog:
- [ ] Some entry
```
- Visit listing page for package

**Expected behavior**

- A checkbox is either rendered as plain text (so `[ ]`) or as an actual checkbox element.

**Screenshots, server logs, package manager log**

![image](https://user-images.githubusercontent.com/5385012/213735323-daa4267d-d113-4dbc-b94d-63b5eadad071.png)

[config.yaml.txt](https://github.com/verdaccio/verdaccio/files/10583493/config.yaml.txt)

**Environment information**

Environment Info:
  System:
    OS: Linux 6.0.9 Arch Linux
    CPU: (8) x64 AMD Ryzen 3 3100 4-Core Processor
  Binaries:
    npm: 7.13.0
    node: 16.2.0
  Virtualization:
    None
  Browsers:
    Chrome: 109

**Debugging output**

These seem a bit unnecessary to me for this issue. Will add them when requested though.
- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [x] I'm willing to fix this bug 🥇 

`

**Comment by juanpicado** [comment]
It might be some wrong setup with marked, feel free to fix it, code is on master.

**Comment by SanderRonde** [comment]
Did some more digging, looks like the problem was the `preventXSS` function in `DetailContainerContentReadme` that you removed in [this pull request](https://github.com/verdaccio/verdaccio/pull/3505) was the culprit. When I remove it it works again. I guess it's then just a matter of upgrading for me :). Will close the issue for now then.
