### ISSUE TITLE
capacity of storage folder and htpasswd

### ISSUE THREAD

**Issue by ASHV95** [verdaccio/verdaccio#366]
#### My reason:
Hello i had two issues 
1) what is the capacity of the storage folder ? 

2) how many max users can we register 

#### Additional information:

	
 - `$ set DEBUG=express:* verdaccio` enable extreme verdaccio debug mode
 - `$ npm --verbose` prints:
 - `$ npm config get registry` prints:
 - Verdaccio terminal output
 - Windows, OS X/macOS, or Linux?:
 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
 
 - Container:
   - I use local environment
   - I develop / deploy using Docker.
   - I deploy to a PaaS.

**Comment by juanpicado** [comment]
1. that depends mainly on your hardware
2. as much you can, I've never heard about issues with that.

What's the issue?  🤔

**Comment by ASHV95** [comment]
Juan it is not an issue i just had a general question about the storage folder , the max capacity of the folder
