### ISSUE TITLE
Web UI Error

### ISSUE THREAD

**Issue by sadarshannaiynar** [verdaccio/verdaccio#367]
#### My reason:
I am able to see only loading icon it never finishes loading and I am unable to login in the web ui. There are some visible errors in console.

#### Steps to reproduce:
1. Install verdaccio package
2. Run the "verdaccio" command

####  App Version:	
v2.6.0

####  Config file:	
Default configuration provided by the package

#### Additional information:
OS: OS X

Loading Screen Picture:
![screen shot 2017-10-19 at 7 52 04 pm](https://user-images.githubusercontent.com/8450195/31776003-d925737e-b507-11e7-89de-e44b1a4e513b.png)

Login Picture:
![screen shot 2017-10-19 at 7 58 42 pm](https://user-images.githubusercontent.com/8450195/31776055-00f76448-b508-11e7-9910-60b9a09e8f60.png)

#### Additional verbose log:
```sh
warn --- config file  - /Users/####/.config/verdaccio/config.yaml
 warn --- http address - http://localhost:4873/ - verdaccio/2.6.0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/style.8410f14de467c42d2f6c14c7df197f3f.css', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/main.d23c839b9a7d1aea4144.js', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/verdaccio/logo', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/logo.png', bytes: 0/0
```

**Comment by juanpicado** [comment]
@Thanks @sadarshannaiynar I'll fix it. Something was wrong with dependencies.

**Comment by sadarshannaiynar** [comment]
Sure I wanted to explore the error so I tried forking the repository and building the web ui and running the module. It was working fine. Then I tried packaging and installing it as a local module it was working fine then also. Then I tried downloading the package from NPM and this error shows up again.

**Comment by juanpicado** [comment]
Yeah, my bad, I fucked up deploying from mine computer. In Docker works fine.

**Comment by juanpicado** [comment]
Thanks for the heads up. I'll deploy a new one `v2.6.1`.

**Comment by sadarshannaiynar** [comment]
Sure. Cons of deploying manually why don't you automate it as a part of the build job. It will be more consistent that way.

**Comment by juanpicado** [comment]
Yeah, it was in progress/testing. Circle ci will do it soon automatically.

**Comment by juanpicado** [comment]
Done, we can close it. Thanks again. Take away, use a CI to deploy 👍

**Comment by sadarshannaiynar** [comment]
Nice 😄  Thanks for the real fast response.
