### ISSUE TITLE
__VERDACCIO_BASENAME_UI_OPTIONS is missing version field

### ISSUE THREAD

**Issue by kanoshin** [verdaccio/verdaccio#3671]
**Your Environment**
  
 * **verdaccio version**: 5.22.1
 * **os**: [linux]
 * **platform**: [docker]

**Describe the bug**

After updating from 5.14.0 to 5.22.1, I noticed that verdaccio version is no longer displayed in the website footer. And `__VERDACCIO_BASENAME_UI_OPTIONS` global variable doesn't have a version field as well.

**To Reproduce**

Just run verdaccio via Docker image v5.22.1.

**Expected behavior**

Version is displayed in the footer and in the `__VERDACCIO_BASENAME_UI_OPTIONS`.

**Comment by juanpicado** [comment]
Thanks, yeah probably 😅 I screw up something else again ... refactoring not easy need more test 😬
