### ISSUE TITLE
Use this dockerfile

### ISSUE THREAD

**Issue by RnbWd** [verdaccio/verdaccio#37]
```
FROM node:6
COPY package.json /verdaccio/
RUN npm install
COPY . /verdaccio

RUN adduser --disabled-password --gecos "" verdaccio && \
  mkdir -p /verdaccio/storage && \
  chown -R verdaccio.verdaccio /verdaccio

USER verdaccio
WORKDIR /verdaccio

EXPOSE 4873

VOLUME ["/verdaccio/conf", "/verdaccio/storage"]

CMD ["./bin/sinopia", "--config", "./conf/config.yaml", "--listen", "0.0.0.0:4873"]

```

sorry no time for pr

**Comment by andrewjensen** [comment]
I can try this out and submit a PR.

@RnbWd: Does this mean #21 can be closed?

**Comment by RnbWd** [comment]
yeah this Dockerfile should work, the current one wasn't building for me, and this worked. I'm not actively using it at the moment so it'd be nice to get more feedback, but if the current one is broken (and not just a fluke in my dev env) then I'd replace it with this. If I start using it again (sinopia no longer works for me so I'll probably start here if I get back into using it again)

**Comment by nwhite89** [comment]
How do you feel about using Alpine Node instead the images are extremely small

**Comment by YouriT** [comment]
`RUN npm install` shall be run within `/verdaccio/` therefore `WORKDIR /verdaccio` shall come before `npm install` no?

**Comment by RnbWd** [comment]
@nwhite89 after reading this tweet - https://twitter.com/rvagg/status/742949140641009666 - I think it's time to start building with alpine :metal: 

@YouriT I haven't ran this build since first posting the issue, but it looks like I'm copying the package.json  first - so `npm install` works... then I copy everything back into verdacio a second time.... Don't know why I wrote it like that :confused:

**Comment by YouriT** [comment]
@RnbWd so you agree it should be the other way around right? I changed it in mine and it works fine like I suggested at least :p

**Comment by nwhite89** [comment]
@RnbWd I have been using this one but reading that tweet does that mean it's a official one? https://github.com/mhart/alpine-node

**Comment by RnbWd** [comment]
@YouriT yes - both should work but it should be the other way around like you mentioned

**Comment by juanpicado** [comment]
Since there is a PR https://github.com/verdaccio/verdaccio/pull/110 already pretty close to the suggestions in this thread and the suggestion of @RnbWd is a mix that currently committed and the previous PR, I'll close this one.
