### ISSUE TITLE
Package Search does not work anymore

### ISSUE THREAD

**Issue by olhaar** [verdaccio/verdaccio#3709]
Hi there,

- verdaccio version: 5.23.1
- node version: v19.8.1
- package manager: npm@9.5.1
- os: Ubuntu 20.04

I've updated to verdaccio 5.23.1 from 5.15.x I think.
Since this update the package search does not work anymore. When I type in some chars, Ican see "Loading..." for a split second followed by nothing.

**Comment by juanpicado** [comment]
could you be more concrete? like find the version that stoped to work would be helpful.

**Comment by olhaar** [comment]
Unfortunately not. 😞

**Comment by jzhangdev** [comment]
I have the same issue, after my research I found that newer search component need a flag to compatibility older version search api data structure.
https://github.com/verdaccio/verdaccio/blob/701d2bae7cffbc0bb8d1b4f042d22d9811e63845/packages/ui-components/src/components/Search/Search.tsx#L26

So need to add the flag to `config.yaml` file.
```yaml
flags:
  searchRemote: false
```

**Comment by juanpicado** [comment]
> I have the same issue, after my research I found that newer search component need a flag to compatibility older version search api data structure.
> 
> https://github.com/verdaccio/verdaccio/blob/701d2bae7cffbc0bb8d1b4f042d22d9811e63845/packages/ui-components/src/components/Search/Search.tsx#L26
> 
> So need to add the flag to `config.yaml` file.
> 
> ```yaml
> flags:
>   searchRemote: false
> ```

Thanks for the research and the PR, I'll look at it when I have some time.
