### ISSUE TITLE
Reverse Proxy - Cannot create server: listen EADDRINUSE

### ISSUE THREAD

**Issue by lgaitan** [verdaccio/verdaccio#372]
#### My reason:
After verdaccio process quit it's socket file is not deleted from disk.
Running verdaccio again will cause a fatal `EADDRINUSE` error.

#### Steps to reproduce:
Setup Verdaccio to run on an unix socket and then restart it

####  App Version:
Any

####  Config file:	
listen: unix:/tmp/verdaccio.sock

#### Additional information:
 - Verdaccio terminal output
fatal--- cannot create server: listen EADDRINUSE /tmp/verdaccio.sock

**Comment by lucasfrey** [comment]
I still have this issue, I updated verdaccio to 2.7.4 and I can't create a server anymore

`fatal--- cannot create server: listen EADDRINUSE 127.0.0.1:4873`

I am listening to 
```listen:
  - https://localhost:4873```
