### ISSUE TITLE
Search just does not work at all?

### ISSUE THREAD

**Issue by gengshenghong** [verdaccio/verdaccio#375]
#### My reason:

Search does not work for me. I've tried to test verdaccio on my machine, everything works (by some struggling in fact, as I got same issue as mentioned in #367 at the beginning...) 
#### Steps to reproduce:
1. npm install verdaccio with v2.6.1 (latest one)
2. start it
3. tried to adduser and just publish two simple projects named `aa` and `zz` (made by `npm init` with all defaults stuff)
4. search is not work in webui, search with "z" or "zz" or anything...always show: No items were found with that query
I wonder if search work at all :(

####  Config file:	
Nothing changed, all default, for test only...

#### Additional information:
Both server and client on the machine, for test only....
```
#cat /etc/issue
Ubuntu 14.04.3 LTS \n \l

#node -v
v6.10.3
#npm -v
3.10.10
#
```

**Comment by gengshenghong** [comment]
I see #257 , but hope search by name is not missing too :)

**Comment by juanpicado** [comment]
What do you mean by name? Do you mean by author?

**Comment by juanpicado** [comment]
Does the #257 will fix this issue?

**Comment by gengshenghong** [comment]
@juanpicado name is the package name, as I mentioned, I just publish too default package (created by npm init) and the packages are "aa" and "zz" (folder name and package name also).

And the latest information is that, I found the search works (partially maybe, explained below) suddenly just now (I did nothing....). Partially because, I found "aa" and "zz" works (I mean it can be searched), and even "z" will show the "zz", but "a" does not show "aa"!!! Whatever, I am new to this tool and I just found the search seems not reliable.

![image](https://user-images.githubusercontent.com/1018468/31851365-f7d873a8-b696-11e7-95cf-0400874eb9b1.png)
![image](https://user-images.githubusercontent.com/1018468/31851370-0a555492-b697-11e7-9f24-56e9bd1894fc.png)
If using "z" to query, it will display the project "zz". Strange issue.

**Comment by gengshenghong** [comment]
@juanpicado I've checked with #257 branch, I can confirm it works to search by version (example: "1" or "1.0.0" will search out both "aa" and "zz"), but still, it does not find "aa" when search with "a". Did I find a corner case ("a" is special?!)! I was just trying to do some tests by randomly created "aa" and "zz"...

**Comment by juanpicado** [comment]
@gengshenghong yes, the indexer `lunr` we use either is not 100% reliable or is not well configured, also seems to be a bit abandoned, #257 tries to fix that and use a new indexer `elasticlunr` that increase functionality as search by version and so on. I hope we can a bit help in that branch in order to fix this issue.

**Comment by juanpicado** [comment]
@gengshenghong I'll close this one and follow up on https://github.com/verdaccio/verdaccio/issues/345 which is the same thing. We have to update the library `"lunr": "0.7.0"` for something better.
