### ISSUE TITLE
local downloaded angular/cli package.json bug

### ISSUE THREAD

**Issue by asafMasa** [verdaccio/verdaccio#377]
#### My reason:

Downloading **angular/cli** creates package.json and a tgz files
the package.json file contains node-sass as a **regular dependency** in addition to it's definition as **optional dependency** 
It is supposed to be only an **optional dependency** (as opening the tgz will show)

#### Steps to reproduce:

npm install angular/cli

####  App Version:	
latest

####  Config file:	
default

**Comment by juanpicado** [comment]
I don't get the issue @asafMasa

**Comment by asafMasa** [comment]
in the original angular/cli package.json the node-sass is in the "optional dependency" section like this:
"optionalDependencies": {
			"node-sass": "^4.3.0"
		},
but when i download the package via verdaccio i get something like this (in the package.json at the storage folder):
		"dependencies": {
                        ...
			"zone.js": "^0.8.14",
			**"node-sass": "^4.3.0"**  --> why?
		},
		"optionalDependencies": {
			"node-sass": "^4.3.0"
		},

Note: that in the tgz file, the node-sass is ok (only in the "optionalDependencies" section), hope this helps

**Comment by asafMasa** [comment]
Have my prev comment explained the issue properly?

**Comment by juanpicado** [comment]
Ok. I can see something interesting, but I'll need more detailed information. Steps to reproduce, exact versions of your tooling, all you can provide me to replicate your environment, then I can start to dive into it. @asafMasa

**Comment by asafMasa** [comment]
ok, i don't have much..

**Comment by asafMasa** [comment]
verdaccio version

**Comment by asafMasa** [comment]
@juanpicado  any progress?

**Comment by lgaitan** [comment]
On npm website, it states

>  If a dependency can be used, but you would like npm to proceed if it cannot be found or fails to install, then you may put it in the optionalDependencies object. This is a map of package name to version or url, just like the dependencies object. The difference is that build failures do not cause installation to fail.

> It is still your program's responsibility to handle the lack of the dependency. For example, something like this:

[https://docs.npmjs.com/files/package.json#optionaldependencies](optionalDependencies)

**Comment by asafMasa** [comment]
@juanpicado  @lgaitan i've opened this issue at cli's https://github.com/angular/angular-cli/issues/7813
But they say that they don't put it in the "dependecies" section only in the "optionaldependencies" section

But when i use verdaccio the "node-sass" get's inside the "dependecies", but if you extract the inner .tgz file you will see it is supposed to be only in the "optionaldependencies" section

**Comment by asafMasa** [comment]
again the problem is not that it is in "optionaldependencies" the problem is that verdaccio **insert** it to the "dependencies" section

**Comment by juanpicado** [comment]
@asafMasa ok I'll check that during the week.

**Comment by asafMasa** [comment]
@juanpicado was there any progress?

**Comment by asafMasa** [comment]
@juanpicado ?

**Comment by asafMasa** [comment]
@juanpicado ?

**Comment by juanpicado** [comment]
> again the problem is not that it is in "optionaldependencies" the problem is that verdaccio insert it to the "dependencies" section

Verdaccio does not handle client-side business, that's `npm`|`yarn` job. Verdaccio only resolves what the clients ask for.

Sorry @asafMasa . the todo is getting huge. :( I hope anyone else helps you with this.
