### ISSUE TITLE
when i publish package to the server,shows 'one of the uplinks is down, refuse to publish'

### ISSUE THREAD

**Issue by wlddong** [verdaccio/verdaccio#381]
#### Additional information:

	
 - `$ set DEBUG=express:* verdaccio` enable extreme verdaccio debug mode
 - `$ npm --verbose` prints:
 - `$ npm config get registry` prints:
 - Verdaccio terminal output
 - Windows, OS X/macOS, or Linux?:
 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
 
 - Container:
   - I use local environment
   - I develop / deploy using Docker.
   - I deploy to a PaaS.

**Comment by juanpicado** [comment]
Yeah, that's intended behaviour, to allow that you have to enable https://github.com/verdaccio/verdaccio/blob/master/wiki/config.md#offline-publish
