### ISSUE TITLE
Where are the packages installed on the caching server?

### ISSUE THREAD

**Issue by splincode** [verdaccio/verdaccio#382]
I would like to clear the cache on my own, how?

**Comment by juanpicado** [comment]
`verdaccio`  uses  `$XDG_DATA_HOME` environment variable to locate the storage by default which [should be the same as](https://askubuntu.com/questions/538526/is-home-local-share-the-default-value-for-xdg-data-home-in-ubuntu-14-04) `$HOME/.local/share`. 

You can see the implementation here https://github.com/verdaccio/verdaccio/blob/master/src/lib/config-path.js#L34

**Comment by splincode** [comment]
Can you write about this in the documentation (readme.md)?

**Comment by juanpicado** [comment]
Sure we shall do :) thanks for the suggestion you are right.
