### ISSUE TITLE
Documentation mistake: (depending) instead of (depenging)

### ISSUE THREAD

**Issue by yassine-klilich** [verdaccio/verdaccio#3879]
Actually this is not a bug, but rather a documentation mistake, I was reading how to use Verdaccio and I came across the highlighted word in the image. I think the author meant to write (depending) instead of (depenging).

![image](https://github.com/verdaccio/verdaccio/assets/24640070/3e1be5b8-2d89-4f16-8c13-ee53193c7993)

**Comment by juanpicado** [comment]
thanks for reporting it, :) maybe you could just fix it? 

https://github.com/verdaccio/verdaccio/blob/master/website/docs/cli-registry.md

**Comment by yassine-klilich** [comment]
@juanpicado sure, i will be glad

**Comment by juanpicado** [comment]
Thank u welcome to verdaccio world !
