### ISSUE TITLE
Log Rotation

### ISSUE THREAD

**Issue by mlucool** [verdaccio/verdaccio#388]
#### My reason:
Is there support for log rotation? If not can it be added to make sure logs do not grow indefinitely. IMO daily logs are best and as it switches between days it archives yesterday's logs.

**Comment by Meeeeow** [comment]
It's not a built-in feature at this time, if you are using process monitor tool such as `pm2`, it's possible to do this with a plugin.

Or you can just write some cron task, copy content to another place then clear file log file

**Comment by juanpicado** [comment]
@mlucool  We have to rewrite the built-in`logger` in the future, it would be great to see a PR with a better approach the one we use now.

**Comment by jsumners** [comment]
I started a rewrite of the logger to switch it to Pino a while back, but the way the logger is written in Verdaccio made that basically impossible to do transparently. I'm still willing to implement it if people do not care about a complete change in how logging works.

**Comment by juanpicado** [comment]
Do you have an example how big would the change for the final user ?

**Comment by jsumners** [comment]
In short, the output as shown in http://getpino.io/#/?id=usage

**Comment by juanpicado** [comment]
Any thoughts @Meeeeow ?

**Comment by mlucool** [comment]
As long as it is bunyan compatible (which it looks like it is), I don't think anyone will care that we change from bunyan to pino.

**Comment by jsumners** [comment]
@mlucool it is. The difference though is that Verdaccio doesn't output actual Bunyan logs. It outputs reformatted logs to show communication with upstream repositories. While that can be handy, my opinion is that the logs should be parseable.

**Comment by mlucool** [comment]
I'd prefer jsonl logs personally

**Comment by jsumners** [comment]
@mlucool that's what Pino does.

**Comment by juanpicado** [comment]
@jsumners how the configuration would look like in comparison the current one ?

```
logs:
  - {type: stdout, format: pretty, level: http}
```

**Comment by jsumners** [comment]
@juanpicado I'd say just a plain Pino config object:

```js
{
  logger: {
    level: 'http', // Pino supports custom levels
    prettyPrint: false // default is false, just illustration
  }
}
```

**Comment by juanpicado** [comment]
Could you translate that to `yaml` ?

**Comment by jsumners** [comment]
Uh,

```yaml
logger:
  level: http
  prettyPrint: false
```

**Comment by juanpicado** [comment]
We have a `format: pretty` field, how would be using files or different formats with `pino` in such configuration?

**Comment by jsumners** [comment]
To be clear: I would be ripping out all of the customized logger stuff and making Verdaccio depend solely on Pino's published API. Pretty printing would be up to the person viewing the logs by either enabling it in their config or piping the logs through the `pino` CLI. And Verdaccio itself would not deal with log file management/rotation. That's better left up to the system tools. 

See http://getpino.io/#/?id=transports for information on Pino's philosophy regarding log storage and http://getpino.io/#/docs/transports for a list of ways to deal with logs.

**Comment by juanpicado** [comment]
> I would be ripping out all of the customized logger stuff and making Verdaccio depend solely on Pino's published API. 

Your idea makes sense, that's one of the reasons why I did not touch at all such files on refactoring phases.

>  And Verdaccio itself would not deal with log file management/rotation. That's better left up to the system tools.

That's exactly what we need, how big would be your implementation in comparison the current one?

I'm not afraid for breaking changes, but, what we need to be careful is not crash the app due bad configuration set up, as much, a nicely warning and disable log until user fix his configuration.

FYI: Any change has to be based on branch `3.x` instead master branch.

**Comment by jsumners** [comment]
It sounds like you are on board with at least considering a PR. I will work one up as soon as I can and that will answer all questions.

**Comment by juanpicado** [comment]
Sure, I think worth to see the final result, currently, I do not like the current logger and I think `v3.x` is a good moment for such change. We are trying to delegate functionality to third-party modules whether is possible.

**Comment by mlucool** [comment]
Is it possible to include some sort internal log rotation still? I have seen https://github.com/verdaccio/verdaccio/issues/420#issuecomment-349470130 which implies external rotation. For example, expose stream type [rotating-file](https://github.com/trentm/node-bunyan#stream-type-rotating-file)

**Comment by juanpicado** [comment]
@mlucool right now logging has been out of the agenda for lack of resources, we would like to put some order in such part of the app. We do not have yet a strategy for it. Looking forward to someone tasks the flag here and help us to make a better logging for verdaccio, including rotating files. Verdaccio 4 seems to be a good candidate for breaking changes in this area.

**Comment by mlucool** [comment]
After https://github.com/verdaccio/verdaccio/pull/893 is merged, I can make a PR for extending [RotatingFileStream](https://github.com/trentm/node-bunyan#stream-type-rotating-file) (I build off this commit is why the prerequisite). This will handle things better than `logrotate` as it knows how to buffer. The change is minimal and non-breaking, but not ideal given you still need to zip and you can't name files like `logrotate`, but its a start!
