### ISSUE TITLE
Possible to run verdaccio on port 80 / 443 using a configuration instead of code change?

### ISSUE THREAD

**Issue by aannuujj** [verdaccio/verdaccio#395]
#### My reason:
I run verdaccio behind HAProxy and HAProxy is having trouble detecting verdaccio on port 4873.
I am also using the verdaccio docker image.

**Comment by juanpicado** [comment]
Have you tried ? https://github.com/verdaccio/verdaccio/blob/master/wiki/config.md#listen-port

**Comment by aannuujj** [comment]
@juanpicado I am using the [docker image](https://hub.docker.com/r/verdaccio/verdaccio/) I was hoping there was a simpler (and quicker) config option instead of building my own docker image - which is my next option.

**Comment by juanpicado** [comment]
Have you tried with docker-compose https://github.com/verdaccio/docker-examples/tree/master/docker-local-storage-volume ?

**Comment by aannuujj** [comment]
cool. thanks for the links, I ended up using nginx example from your link instead.

**Comment by kopax** [comment]
Hi @aannuujj , I want to run verdaccio in http and load balance using consul dns and HA proxy.

We also have a public ssl reverse nginx proxy.

Unfortunately it doesn't work with HA proxy, could we see how you manage to configure it?

**Comment by aannuujj** [comment]
@kopax can you post your current configurations? I can check against mine or point out any changes required.

**Comment by kopax** [comment]
Thanks @aannuujj we finally managed to do it by sending the header to the upstream one. Thanks for offering your help still!
