### ISSUE TITLE
Missing "onClick" prop in @verdaccio/ui-components Link component preventing handleDownload call in Package.tsx

### ISSUE THREAD

**Issue by moglerdev** [verdaccio/verdaccio#3988]
**Your Environment**
  
 * **verdaccio version**: 7.x.x (see PR)
 * **node version**: 18.x.x
 * **package manager**: pnpm@8
 * **os**: linux 
 * **platform**: other

**Describe the bug**

At present, attempting to download the "tar" file from the Package List on the homepage does not work as expected. Clicking on the link only opens a new tab, but no download action occurs.

The root cause of this problem lies in the `Link` Component within `@verdaccio/ui-components`. It lacks a necessary `onClick` prop, preventing the execution of the `handleDownload` function in `Package.tsx`.

**To Reproduce**

 
- Step 1: After publishing a package (if the list is empty) and potentially reloading the page, you navigate to a package's details page.
- Step 2: On this page, you click the "Download tar" (Download Icon)
- Step 3: Instead of initiating the download, a new tab opens, and the URL has a "#" appended to it.

**Expected behavior**

Should download the latest tar file of the selected package. 

**Screenshots, server logs, package manager log**

Package.tsx try to create the Component `Link` with property `onClick`

![image](https://github.com/verdaccio/verdaccio/assets/39583780/7417f3c3-25df-4fe1-bb64-dc224198226b)

Problem, there is nor supported prop `onClick` in `Link`

![image](https://github.com/verdaccio/verdaccio/assets/39583780/a93c3e66-75b6-4d75-bfa9-4b4cf990b043)

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [X] I'm willing to fix this bug 🥇

**Comment by moglerdev** [comment]
#3989 PR to fix this issue

**Comment by moglerdev** [comment]
Hey @juanpicado,
At the moment, the fix is functional exclusively for version 7.x, with versions 5.x and 6.x remaining unaffected. Should the dependency be adjusted for broader compatibility?

6.x ["@verdaccio/ui-theme": "6.0.0-6-next.74",](https://github.com/verdaccio/verdaccio/blob/6.x/package.json#L31)
5.x ["@verdaccio/ui-theme": "6.0.0-6-next.74",](https://github.com/verdaccio/verdaccio/blob/5.x/package.json#L31)

current version 7.0.0-next.1

**Comment by juanpicado** [comment]
I will update all versions this weekend. 6.x is same as 5.x just need it to bump up to get rid of node 12

**Comment by juanpicado** [comment]
`v5.26.2`
