### ISSUE TITLE
Copy authorization from request to proxy

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#4028]
### Discussed in https://github.com/verdaccio/verdaccio/discussions/3708

<div type='discussions-op-text'>

<sup>Originally posted by **jeffrson** March 28, 2023</sup>
Hi,
I have a private registry, publicly accessible, but requires user account credentials.

Now I'm setting up another registry, which should use my private registry (this is in a company which usually has all clients protected, but allows access from a special endpoint to the outside). This second registry of course needs to authenticate against the former private registry.

How can this be done? I know, in "Uplinks" there are "auth" settings. These settings work fine. Unfortunately, I set up my logins to expire after about 3 months, so I would need to update the auth token (locally in this company) and restart Verdaccio. A lot may go wrong here.

Any better idea? Real copy of auth request (bearer and basic) will probably not work, because every instance has its own key for signing afaict.
</div>

**Comment by mbtools** [comment]
same as #4541 🤷

**Comment by juanpicado** [comment]
Thanks I didn't notice :) I will close this one
