### ISSUE TITLE
Search for plug-ins crashes

### ISSUE THREAD

**Issue by mbtools** [verdaccio/verdaccio#4050]
1. Go to https://verdaccio.org/dev/plugins-search

![image](https://github.com/verdaccio/verdaccio/assets/59966492/28a32d2e-beda-4683-8659-61311053467a)

2. Type anything like "theme"

3. Crashes on the first keystroke

![image](https://github.com/verdaccio/verdaccio/assets/59966492/5929385e-f662-40a4-9b6a-0eab8e47e567)

**Comment by juanpicado** [comment]
Thanks :) might be the library was upgraded and well website does not have test :)

**Comment by mbtools** [comment]
Still an issue. Looks like https://github.com/oramasearch/orama/issues/446, fixed in https://github.com/oramasearch/orama/pull/471 which is part of 1.2.2. 

You picked 1.2.1 but 1.2.10 is latest. Or is there some caching on the backend?
