### ISSUE TITLE
please don`t use sass.. it is very slow..and weight.

### ISSUE THREAD

**Issue by txiaocao** [verdaccio/verdaccio#407]
⊙﹏⊙
```
[root@kemao-workstation verdaccio]# yarn
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > webpack-dev-server@2.5.0" has incorrect peer dependency "webpack@^2.2.0".
[5/5] Building fresh packages...
[-/3] ⠄ waiting...
[-/3] ⠄ waiting...
[3/3] ⡀ node-sass: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-57_binding.node
[-/3] ⡀ waiting...
^C/3] ⡀ waiting...
```

**Comment by Meeeeow** [comment]
The "Great Firewall" can't be a reason to stop use good tool, here is an article about how to install node-sass in China mainland:

https://github.com/lmk123/blog/issues/28 (Article content is Chinese)

**Comment by juanpicado** [comment]
Ok :-) I think we can close this.

**Comment by txiaocao** [comment]
thanks, but I think also the Less or css is strong...:-)

**Comment by juanpicado** [comment]
Yes, We have even tried styled-components in previous versions. For now is OK. Let see in the future, I will keep in mind your suggestions for sure.

**Comment by Meeeeow** [comment]
Still prefer sass for better syntax

**Comment by txiaocao** [comment]
Using CSS module and react,
So we don't have to rely on too many dynamic CSS features. Components is css&js&html together。:)
![](https://txiaocao.github.io/image/TIM20171127183835.png)

**Comment by Kochiya-Yoru** [comment]
Now, we have a no binary version, [dart-sass](https://github.com/sass/dart-sass).
