### ISSUE TITLE
Login and New User are the Same

### ISSUE THREAD

**Issue by jamesdalel** [verdaccio/verdaccio#409]
#### My reason:

Once I have added a user and logout I can't publish with that user as it exists already.

#### Steps to reproduce:

	I have created a new user using yarn and logged in and then used `yarn logout`.  I then tried to do yarn publish. I entered the user credentials but I just get a 

> this user already exists error

#### Additional information:

yarn publish
yarn publish v0.24.6
[1/4] Bumping version...
info Current version: 21.10.0
question New version: 21.11.0
info New version: 21.11.0
[2/4] Logging in...
question npm username: username
question npm email: email
question npm password:
error An unexpected error occurred: "reg:username: this user already exists".
info If you think this is a bug, please open a bug report with the information provided in "file.log".
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.

**Comment by gkaran** [comment]
I second that. The login dialog is exactly the same as adduser which in turn results to a conflict.

**Comment by richardklose** [comment]
Same here using npm.
`npm login` leads to
```
...
npm ERR! this user already exists ...
```

**Comment by juanpicado** [comment]
Would make sense for you some sort of password admin from the UI?

**Comment by gkaran** [comment]
@juanpicado it would but this is not the issue here. The problem here is that you cannot login from the cli with a user that is already created.

**Comment by juanpicado** [comment]
Ok @gkaran I'll take a look.

**Comment by ayusharma** [comment]
It is working fine in verdaccio-htpasswd@0.1.4

Ref: https://www.npmjs.com/package/verdaccio-htpasswd

Please feel free to open, if issue persist.

**Comment by kub1x** [comment]
Hey, running to the same issue. I want my registry to be kinda private. Want to manually create users on server and then only allow them to login, publish, etc. I didn't manage to create users manually using `htpasswd` tool from apache, so allowed users to register temporarily and then disabled it as follows: 
```
auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1
```
When I run `npm login` now, I get the `maximum amount of users reached` error. 
When I run `npm login --help` I can see, that it is aliased as `adduser`. 

How can I login to verdaccio when registration is disabled using `max_users: -1`?

**Comment by kub1x** [comment]
Just for anyone who end up here searching for this error. I solved the issue by setting `max_users` to the number of users/lines in the `htpasswd` file.

**Comment by MichielDeMey** [comment]
Just ran into the same problem, I've set `max_users` to `-1` to disallow user registrations and ran into the same problem when trying to authenticate using the CLI.

```shell
npm adduser --registry=https://foo.bar --scope=@foo --always-auth
Username: foo
Password:
Email: (this IS public) foo@bar.com

npm ERR! code E403
npm ERR! Registry returned 403 for PUT on https://npm.poppy.be/-/user/org.couchdb.user:michiel: maximum amount of users reached
```

Maybe we should re-open this issue?

**Comment by ayusharma** [comment]
@MichielDeMey  This PR fixes this https://github.com/verdaccio/verdaccio-htpasswd/pull/30 . Could you please verify?

**Comment by MichielDeMey** [comment]
Won't that PR just throw a new error instead of allowing logins through the CLI when registration is disabled?
