### ISSUE TITLE
which module make the package aync to my server

### ISSUE THREAD

**Issue by jackple** [verdaccio/verdaccio#412]
If I download a package which only at the npmjs.com, verdaccio will make it sync to my server. How? Which module is doing this?

**Comment by juanpicado** [comment]
I'm not 100% what you ask, but I'd say `storage.js`

**Comment by jackple** [comment]
@juanpicado 
![image](https://user-images.githubusercontent.com/6183232/33509824-fdfa3cf2-d73f-11e7-9c22-74395e112add.png)
Is it here?
