### ISSUE TITLE
npm ERR! 404 Not Found: body-parser@~1.13.2

### ISSUE THREAD

**Issue by jamesliauw** [verdaccio/verdaccio#413]
#### My reason:
npm ERR! 404 Not Found: body-parser@~1.13.2

####  App Version:	
2.6.6

####  Config file:	
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

#### Additional information:

	
 - `$ set DEBUG=express:* verdaccio` enable extreme verdaccio debug mode
 - `$ npm --verbose` prints:
 - `$ npm config get registry` prints:
 - Verdaccio terminal output
 - Windows, OS X/macOS, or Linux?:
 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
 
 - Container:
   - I use local environment
   - I develop / deploy using Docker.
   - I deploy to a PaaS.

#### Additional verbose log:

npm ERR! code E404
npm ERR! 404 Not Found: body-parser@~1.13.2

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-01T13_37_51_659Z-debug.log

2899 silly resolveWithNewModule utility@1.13.1 checking installable status
2900 silly pacote range manifest for ylru@^1.2.0 fetched in 6ms
2901 silly resolveWithNewModule ylru@1.2.0 checking installable status
2902 verbose stack Error: 404 Not Found: @types/accepts@^1.3.3
2902 verbose stack     at fetch.then.res (/opt/node-v8.9.0-linux-x64/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
2902 verbose stack     at tryCatcher (/opt/node-v8.9.0-linux-x64/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2902 verbose stack     at Promise._settlePromiseFromHandler (/opt/node-v8.9.0-linux-x64/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
2902 verbose stack     at Promise._settlePromise (/opt/node-v8.9.0-linux-x64/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
2902 verbose stack     at Promise._settlePromise0 (/opt/node-v8.9.0-linux-x64/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
2902 verbose stack     at Promise._settlePromises (/opt/node-v8.9.0-linux-x64/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
2902 verbose stack     at Async._drainQueue (/opt/node-v8.9.0-linux-x64/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
2902 verbose stack     at Async._drainQueues (/opt/node-v8.9.0-linux-x64/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
2902 verbose stack     at Immediate.Async.drainQueues (/opt/node-v8.9.0-linux-x64/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
2902 verbose stack     at runCallback (timers.js:789:20)
2902 verbose stack     at tryOnImmediate (timers.js:751:5)
2902 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
2903 verbose cwd /www/test
2904 verbose Linux 2.6.32-431.el6.x86_64
2905 verbose argv "/opt/node-v8.9.0-linux-x64/bin/node" "/opt/node-v8.9.0-linux-x64/bin/npm" "i"
2906 verbose node v8.9.0
2907 verbose npm  v5.5.1
2908 error code E404
2909 error 404 Not Found: @types/accepts@^1.3.3
2910 verbose exit [ 1, true ]

**Comment by juanpicado** [comment]
I'm not sure what are you trying to report, perhaps if you provide more info we can help you. As far I can see you seem to have network connection issues.
