### ISSUE TITLE
Add existing packages

### ISSUE THREAD

**Issue by ryandigital** [verdaccio/verdaccio#418]
#### My reason:

Ability to bulk add existing packages to a Docker container and to load automatically

#### Steps to reproduce:

Add packages to the storage folder and update json file

#### Additional information:

	
 - `$ set DEBUG=express:* verdaccio` enable extreme verdaccio debug mode
 - `$ npm --verbose` prints:
 - `$ npm config get registry` prints:
 - Verdaccio terminal output
 - Windows, OS X/macOS, or Linux?:
 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
 
 - Container:
   - I use local environment
   - I develop / deploy using Docker.
   - I deploy to a PaaS.

**Comment by juanpicado** [comment]
> Ability to bulk add existing packages

The current storage does not allow that. You might to modify manually the `sinopia-db.json` file if you want such packages are displayed in the UI. 

For me this sound as a future improvement as a import feature.

**Comment by sarathkcm** [comment]
I would upvote for a feature which can export packages from one Verdaccio instance and import into another instance while keeping the old packages in the second instance unchanged. This way I can solve #451, by installing a new package in my local instance, exporting it and importing it into the server.

**Comment by juanpicado** [comment]
@sarathkcm perhaps https://github.com/verdaccio/verdaccio/issues/343 might call your attention

**Comment by juanpicado** [comment]
I'd check https://github.com/patrikx3/verdaccio-cli
