### ISSUE TITLE
Having issues with proxy behind firewall

### ISSUE THREAD

**Issue by hibumbapartha** [verdaccio/verdaccio#421]
#### My reason:

My Issue is exactly same as issue raised in sinopia : https://github.com/rlidwka/sinopia/issues/372
```
$>npm adduser --registry http://localhost:4873
Username: chaitrika
Password:
Email: (this IS public) mytestmail@gmail.com
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "adduser" "--registry" "http://localhost:4873"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <HTML>
npm ERR! <HEAD><TITLE>Redirection</TITLE></HEAD>
npm ERR! <BODY><H1>Redirect</H1></BODY>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     .......\npm-debug.log
```

#### Steps to reproduce:
1. Install verdaccio in a proxy enabled system. (You need to setup npm proxy)
2. npm adduser --registry http://localhost:4873

####  App Version:	
node : 6.9.1
npm: 3.10.8

#### Additional information: debug log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'adduser',
1 verbose cli   '--registry',
1 verbose cli   'http://localhost:4873' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose config Skipping project config: C:\Users\XY50062/.npmrc. (matches userconfig)
5 verbose adduser before first PUT { _id: 'org.couchdb.user:partha',
5 verbose adduser   name: 'partha',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'test.test@gmail.com',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2017-12-05T06:15:29.609Z' }
6 verbose request uri http://localhost:4873/-/user/org.couchdb.user:partha
7 verbose request new user, so can't send auth
8 info attempt registry request try #1 at 11:45:29 AM
9 verbose request id 19f2ed7ec35cd9ec
10 http request PUT http://localhost:4873/-/user/org.couchdb.user:partha
11 http 301 http://localhost:4873/-/user/org.couchdb.user:partha
12 verbose bad json <HTML>
12 verbose bad json <HEAD><TITLE>Redirection</TITLE></HEAD>
12 verbose bad json <BODY><H1>Redirect</H1></BODY>
13 error registry error parsing json
14 verbose headers { server: 'BlueCoat-Security-Appliance',
14 verbose headers   location: 'http://10.110.11.191',
14 verbose headers   connection: 'Close' }
15 verbose request invalidating C:\Users\XY50062\AppData\Roaming\npm-cache\localhost_4873\-\user\org.couchdb.user_3Apartha on PUT
16 verbose adduser back [ SyntaxError: Unexpected token < in JSON at position 0
16 verbose adduser   <HTML>
16 verbose adduser   <HEAD><TITLE>Redirection</TITLE></HEAD>
16 verbose adduser   <BODY><H1>Redirect</H1></BODY>
16 verbose adduser
16 verbose adduser       at Object.parse (native)
16 verbose adduser       at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
16 verbose adduser       at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
16 verbose adduser       at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
16 verbose adduser       at emitTwo (events.js:106:13)
16 verbose adduser       at Request.emit (events.js:191:7)
16 verbose adduser       at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
16 verbose adduser       at emitOne (events.js:96:13)
16 verbose adduser       at Request.emit (events.js:188:7)
16 verbose adduser       at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:965:12),
16 verbose adduser   null,
16 verbose adduser   '<HTML>\r\n<HEAD><TITLE>Redirection</TITLE></HEAD>\r\n<BODY><H1>Redirect</H1></BODY>\r\n' ]
17 verbose stack SyntaxError: Unexpected token < in JSON at position 0
17 verbose stack <HTML>
17 verbose stack <HEAD><TITLE>Redirection</TITLE></HEAD>
17 verbose stack <BODY><H1>Redirect</H1></BODY>
17 verbose stack
17 verbose stack     at Object.parse (native)
17 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
17 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
17 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
17 verbose stack     at emitTwo (events.js:106:13)
17 verbose stack     at Request.emit (events.js:191:7)
17 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
17 verbose stack     at emitOne (events.js:96:13)
17 verbose stack     at Request.emit (events.js:188:7)
17 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:965:12)
18 verbose cwd C:\Users\XY50062
19 error Windows_NT 6.1.7601
20 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "adduser" "--registry" "http://localhost:4873"
21 error node v6.9.1
22 error npm  v3.10.8
23 error Unexpected token < in JSON at position 0
23 error <HTML>
23 error <HEAD><TITLE>Redirection</TITLE></HEAD>
23 error <BODY><H1>Redirect</H1></BODY>
24 error If you need help, you may report this error at:
24 error     <https://github.com/npm/npm/issues>
25 verbose exit [ 1, true ]
```

**Comment by juanpicado** [comment]
Config file?

**Comment by hibumbapartha** [comment]
No change in config file. It is default as it installed.
Here it is.

`#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

`

**Comment by juanpicado** [comment]
Have you read https://github.com/verdaccio/verdaccio/blob/master/wiki/reverse-proxy.md ?

**Comment by hibumbapartha** [comment]
But I am not using Apache where to setup those reverse proxy things?

**Comment by juanpicado** [comment]
Sorry, I read wrong.

**Comment by juanpicado** [comment]
Have you tried https://github.com/rlidwka/sinopia/pull/268/files this fix?

**Comment by hibumbapartha** [comment]
But it is for sinopia and it is not accepted. Same issue I believe is here in verdaccio also. So I raised the issue. Let me try to clone the verdacccio and try the fix. Thanks for your prompt help.

**Comment by hibumbapartha** [comment]
I want to create a pull request from verdaccio. Can you please from which branch will I try?

**Comment by juanpicado** [comment]
`sinopia` is dead. Don't bother there https://github.com/rlidwka/sinopia/issues/376

I wait for your feedback then.

**Comment by hibumbapartha** [comment]
I am behind a firewall and behind the proxy also. I do not have any permission for clone. So not able to test the code directly. Looking for other way to test it (by downloading the code as zip).

**Comment by hibumbapartha** [comment]
I have added the code in src/api/index.js file. Can you please guide me how do I build this project and test it?

**Comment by juanpicado** [comment]
You don't have to build anything, it's node (Javascript).  Just modify the file and restart verdaccio.

**Comment by hibumbapartha** [comment]
No. It does not solve the problem. Is there any way to add the user directly somewhere? So that I can proceed other steps till this is been fixed?

**Comment by hibumbapartha** [comment]
I am able to bypass the issue by createing a **htpasswd** file with the help of this online tool http://www.htaccesstools.com/htpasswd-generator/

**Comment by juanpicado** [comment]
Really? ... 🤔

**Comment by juanpicado** [comment]
You can ask here https://gitter.im/verdaccio/ perhaps others have run in the same issue.

**Comment by cjkumaresh** [comment]
Hi @hibumbapartha 
I was able to resolve this by adding localhost to the environment variable NO_PROXY

**Comment by juanpicado** [comment]
https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables
