### ISSUE TITLE
Release 5.28.1

### ISSUE THREAD

**Issue by legobeat** [verdaccio/verdaccio#4229]
Would be nice to get a release with the dependency fixes and updates merged since `5.27.0`.

~376eb5378 could affect users who extend the Docker image but that lives outside the npm package itself and otherwise it looks like all non-breaking maintenance changes.~

**Comment by juanpicado** [comment]
What do you mean extacly, do you refer to docker image only?, that commit is from master, v5 lives on branch 5.x.

**Comment by juanpicado** [comment]
Yes on branch 6.x, there is a discussion about it you can check why. Both branches benefit highly of any update from master. Whenever 5.x is out of support 6.x will move to master and the idea is have one single branch, unfortunately I am not dedicated 100% and the world moves faster than my contributions :) so is some sort of workaround to make my life easier.
