### ISSUE TITLE
The uplinks configuration does not take effect during query

### ISSUE THREAD

**Issue by xiangshoulai** [verdaccio/verdaccio#4260]
![screenshot-20231211-204955](https://github.com/verdaccio/verdaccio/assets/4157695/f9032c04-0049-4efb-be06-54c82dc05848)

**Describe the bug**

**Comment by xiangshoulai** [comment]
uplinks:
  npmjs:
    url: https://registry.npm.taobao.org/
    timeout: 10s
    cache: false
  npmjs2:
    url: https://registry.npmjs.org/
    timeout: 10s
    cache: false

# Learn how to protect your packages
# https://verdaccio.org/docs/protect-your-dependencies/
# https://verdaccio.org/docs/configuration#packages
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy:  npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy:  npmjs

**Comment by xiangshoulai** [comment]
`
uplinks:
  npmjs:
    url: https://registry.npm.taobao.org/
    timeout: 10s
    cache: false
  npmjs2:
    url: https://registry.npmjs.org/
    timeout: 10s
    cache: false

# Learn how to protect your packages
# https://verdaccio.org/docs/protect-your-dependencies/
# https://verdaccio.org/docs/configuration#packages
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy:  npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy:  npmjs

`

**Comment by juanpicado** [comment]
I don't see any bug here, add reproducible steps first.
