### ISSUE TITLE
Resetting the DB

### ISSUE THREAD

**Issue by AviFix** [verdaccio/verdaccio#43]
Hi

Is there a way to reset reset the db (clear all packages)?

reinstalling didn't hellpe.

Thanks
Avi

**Comment by steve-p-com** [comment]
You can simply stop the service, empty whatever directory you set for 'storage' in the configuration file, and restart the service.

If you are on a Unix-like operating system, you need to make sure you have deleted the file called `.sinopia-db.json` within the storage directory. If you are just doing `rm /path/to/storage/*` then that may not remove files beginning with `.`.
