### ISSUE TITLE
拉取 500错误

### ISSUE THREAD

**Issue by aa2086500** [verdaccio/verdaccio#430]
我本机电脑进行项目的离线拉取，拉取全部都是200状态，但是同一网络下其他电脑拉取就是500错误请问是怎么回事
![0eac595792e3dd9c0fce0b1dd2e6a324](https://user-images.githubusercontent.com/15921352/33930503-146c264e-e028-11e7-9264-8313cc4e6a0d.png)

**Comment by juanpicado** [comment]
I'll try to figure out since I do not speak Chinese. Your uplink fails as the image describes, Do you have internet access?

If you do not speak English,  I think @Meeeeow might help you.

**Comment by es3154** [comment]
Does verdaccio have to be networked ？

**Comment by dlouzan** [comment]
Probably yes if you have configured an uplink. Try disabling it.

**Comment by es3154** [comment]
@dlouzan  My configuration allow_offline prefixes two Spaces
