### ISSUE TITLE
Is there any solution to use verdaccio on AWS ECS using S3 as synced package storage?

### ISSUE THREAD

**Issue by aremishevsky** [verdaccio/verdaccio#432]
It would be very good to have some purposes or suggestions how to implement verdaccio registry using AWS ECS with shared storage for couple instances (using S3).
If there is some solution about this - could someone share a link about that?

Also would be awesome to have a full list of possible config values passed in config of verdaccio

**Comment by juanpicado** [comment]
@aremishevsky `verdaccio` works only with file system right now, we are working on https://github.com/verdaccio/verdaccio/pull/376 next big release to allow scale using different sort of storages. Hopefully beginning next year

**Comment by aremishevsky** [comment]
Will wait for you updates a lot!!!

**Comment by aremishevsky** [comment]
Hi guys,
I'm currently using 2.7.2 version and can't find a way to use storage as a plugin.
I saw that some functionality was implemented for this in here https://github.com/verdaccio/verdaccio/pull/291
Is there any way to implement this feature (custom pluggable storage) in some 2.x version?

**Comment by juanpicado** [comment]
@aremishevsky `2.x` remains as it is. `3.x` will have this feature, actually is possible to start creating your own storage plugin, but, there is no documentation yet and the API might change. We are moving slowly but constant.

**Comment by aremishevsky** [comment]
@juanpicado thanks for so quick response.
Actually i'm trying to combine work of your stock local_storage with syncUp to s3 script.
Is there any option to subscribe on some events using custom middleware?

**Comment by juanpicado** [comment]
https://github.com/asynchrony/docker-verdaccio-s3

**Comment by juanpicado** [comment]
I just pushed the first storage plugin, It's a good template to deal with different kinds of storages.

https://github.com/verdaccio/verdaccio-memory

Perhaps someone comes up with a plugin for of https://www.npmjs.com/package/s3

**Comment by tvb** [comment]
@aremishevsky you should use Amazon EFS until S3 is supported. Mount the volume at `/verdaccio`

**Comment by juanpicado** [comment]
@tvb could you elaborate more the process?. I think worth to document it somewhere.
