### ISSUE TITLE
Missing manual to run verdaccio in JS way (not node way)

### ISSUE THREAD

**Issue by aremishevsky** [verdaccio/verdaccio#435]
#### My reason:
I need to run verdaccio in a JS way. 

#### Steps to reproduce:
I've tried to run it as:

in **index.js**

```
var verdaccio = require('verdaccio'),
    config = {
        storage: './storage',
        web: 'enable:true',
        auth: {htpasswd: {file: './htpasswd'}},
        uplinks: {
            npmjs: {url: 'https://registry.npmjs.org/'}
        },
        packages: {
            '@*/*': {access: '$all', publish: '$authenticated', proxy: 'npmjs'},
            '*': {access: '$all', publish: '$authenticated', proxy: 'npmjs'}
        },
        logs: [{type: 'stdout', format: 'pretty', level: 'http'}],
        listen: ['0.0.0.0:4873'],
        self_path: '~/config.yaml',
        https: {enable: false}
    };
verdaccio(config);
```

and run it as: 
`node index.js`

As result I just have that verdaccio is initialized but nothing happen next.
What did I make wrong?

**Comment by juanpicado** [comment]
There is no way yet to do such things yet, in branch `3.x` we are getting close to achieve such thing but is not ready yet https://github.com/verdaccio/verdaccio/blob/3.x/src/lib/cli.js#L59

**Comment by juanpicado** [comment]
Since `verdaccio@3.0.0-alpha.10` we provide a Node API.
http://www.verdaccio.org/verdaccio/docs/en/node-api.html
