### ISSUE TITLE
Local verdaccio cache is much slower than NPM

### ISSUE THREAD

**Issue by StarpTech** [verdaccio/verdaccio#437]
I'm using verdaccio as local cache server.

```
npm install --registry http://npm.local

added 230 packages in 17.972s
```
```
npm install

added 230 packages in 10.596s
```
```
{
  "name": "npm-test",
  "version": "1.0.0",
  "description": "Example package",
  "main": "index.js",
  "license": "ISC",
  "devDependencies": {
    "np": "^2.18.3"
  }
}

```
**Hardware:**
- Virtual machine
- 8GB RAM
- Intel Xeon 2.20GHz, 4 Core(s)
- Microsoft Windows Server

**Drive:**
- NTFS
- No SSD

**Comment by StarpTech** [comment]
Before we can discuss about improvements are you able to reproduce it? I want to exclude misconfiguration refer to networking, bandwidth limits etc...

**Comment by juanpicado** [comment]
I'll give it a try, but it will take a while.. you know ...... But I'm quite interested on improving the performance in any way, if you find something odd, let us know. Thanks for reporting

**Comment by StarpTech** [comment]
I think there is a lot of space for improvements. One possible solution is to use a database for saving blobs. This will also speed up the lookup process. Using [rqlite](https://github.com/rqlite/rqlite) would fit very well refer to scale and performance.

https://github.com/rqlite/rqlite
https://www.sqlite.org/fasterthanfs.html

**Comment by juanpicado** [comment]
@StarpTech yeah the branch `3.x` aims to achieve such thing, get rid of the file system as default and allow people to use their own storages if they want. (WIP)

**Comment by StarpTech** [comment]
> verdaccio asks the uplinks for updates (versions, dist-tar, etc ...

Also when I specify a fixed version?

> yeah the branch 3.x aims to achieve such thing, get rid of the file system as default and allow people to use their own storages if they want. (WIP)

That's great, is there any roadmap or deadline to follow?

**Comment by juanpicado** [comment]
> Also when I specify a fixed version?

 I'm not quite sure about that, I'll have to check

>That's great, is there any roadmap or deadline to follow?

The roadmap (https://github.com/verdaccio/verdaccio/pull/376)

**Comment by StarpTech** [comment]
@juanpicado thanks!

**Comment by mlurker** [comment]
We have similar issue. It takes much more time getting packages from cache, rather than downloading them directly. Is there any setting to disable public modules caching?

**Comment by StarpTech** [comment]
@mlurker define "much more" and what is your environment and hardware?

**Comment by mlurker** [comment]
@StarpTech sure. I have a VM with 4 cores Xeon E5-2643 and 16GB RAM. Verdaccio is installed on this machine.

Results:

`npm install --registry http://localhost:4873/
added 1070 packages in 152.512s
`

`npm install
added 230 packages in 68.299s
`

**Comment by juanpicado** [comment]
@mlurker 

> We have similar issue. It takes much more time getting packages from cache, rather than downloading them directly. Is there any setting to disable public modules caching?

Yes, there are two options. Either use `cache` to do not download tarballs or do not define `proxy` on package definition, that will avoid look up for metadata on any registry.

http://www.verdaccio.org/docs/en/uplinks.html#you-must-know

Closing, it seems you have resolved your issue.
