### ISSUE TITLE
No binary files are cached only a package.json file

### ISSUE THREAD

**Issue by Martin-Andersen** [verdaccio/verdaccio#45]
I am trying to cache public npm packages on my TeamCity build server.

verdaccio creates a directory for each npm packages but no binaries are saved.
Requests looks like this:
`http  <-- 200, user: mha, req: 'GET /pako', bytes: 0/4391
 http  --> 304, req: 'GET https://registry.npmjs.org/ieee754', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/base64-js', bytes: 0/0
 http  <-- 304, user: mha, req: 'GET /ieee754', bytes: 0/0
 http  <-- 304, user: mha, req: 'GET /base64-js', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/date-now', bytes: 0/0
 http  <-- 304, user: mha, req: 'GET /date-now', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/ripemd160', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/pbkdf2-compat', bytes: 0/0
 http  --> 304, req: 'GET https://registry.npmjs.org/sha.js', bytes: 0/0
 http  <-- 304, user: mha, req: 'GET /ripemd160', bytes: 0/0
 http  <-- 304, user: mha, req: 'GET /sha.js', bytes: 0/0`

Am I missing something?

**Comment by thkprado** [comment]
Try to clean the npm cache before npm install so it can request the package again: **npm cache clean**
