### ISSUE TITLE
Verdaccio is always listening on IPv6 port on `ubuntu-latest` on GitHub Actions 

### ISSUE THREAD

**Issue by cortinico** [verdaccio/verdaccio#4678]
**Your Environment**
 * **verdaccio version**: `@latest`
 * **node version** [12.x.x, 14.x.x]:
 * **package manager**: [npm@7, pnpm@6, yarn@2]
 * **os**: `ubuntu-latest` on GHA
 * **platform**: GHA

**Describe the bug**

Hey all,
Nicola Corti from the React Native Team at Meta.
We do use Verdaccio on GitHub actions on our setup

I've just noticed that the latest deployment of the `ubuntu-latest` runner on GitHub actions (version `20240609.1.0`) is breaking our CI on React Native causing it to take 6+ hours to complete.

This happens because Verdaccio starts to listen on a IPv6 address.
We do use Verdaccio in our CI setup to test NPM packages. For some reasons, Verdaccio is always listening on a IPv6 port since `20240609.1.0`.
I'm unsure what could be causing this, but I tried all possible ways to force Verdaccio to listen on a IPv4 address/port. It seems like to always fallback to an IPv6.

I've also reported this bug to the runner-images repo (see https://github.com/actions/runner-images/issues/10061). I'm wondering if you folks have any insights on what could be happening here.

I also created a reproducer here:
https://github.com/cortinico/repro-ipv6-gha-issue/

You can see in the latest run how I'm running Verdaccio and using `net-stat` to show the open ports:
https://github.com/cortinico/repro-ipv6-gha-issue/actions/runs/9503903039/job/26195373761
Seems like Verdaccio is listening on a IPv6 port:
![Screenshot 2024-06-13 at 18.16.35.png](https://github.zendesk.com/attachments/token/MXaSHTKeUKrTbTQJyDjAiJBhR/?name=Screenshot+2024-06-13+at+18.16.35.png)

**To Reproduce**

Minimal Reproducer is here: https://github.com/cortinico/repro-ipv6-gha-issue/

**Expected behavior**

Verdaccio should listen on http://localhost:4873 IPv4 by default

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

https://github.com/cortinico/repro-ipv6-gha-issue/blob/main/verdaccio.yml

**Comment by mbtools** [comment]
I can't tell. Did you try setting `listen` to both ipv4 and ipv6?
https://github.com/orgs/verdaccio/discussions/4086#discussioncomment-7393623
https://verdaccio.org/docs/configuration#listen-port

**Comment by mbtools** [comment]
Is it working now?
