### ISSUE TITLE
New Helm Chart

### ISSUE THREAD

**Issue by chainlink** [verdaccio/verdaccio#468]
Hi there,
I added some features to your helm chart, available here. Happy to update your docs if you like the changes!

https://github.com/kubernetes/charts/pull/3304

**Comment by juanpicado** [comment]
Hi @chainlink sure !! Thanks a lot ... Just PR after merge you will see your changes here

http://www.verdaccio.org/verdaccio/docs/en/kubernetes.html

**Comment by juanpicado** [comment]
Reference https://github.com/verdaccio/docker-examples/issues/8

**Comment by juanpicado** [comment]
@chainlink ping

**Comment by chainlink** [comment]
Thanks for the ping! They haven't merged it yet sadly, but will PR the docs anyway

**Comment by chainlink** [comment]
It's been merged! I think we can close this?

**Comment by juanpicado** [comment]
Yes ! Thanks @chainlink for take care of this 🥇

**Comment by juanpicado** [comment]
@chainlink hi I was wondering why Kubernetes +1.7 is a prerequisite?

https://github.com/kubernetes/charts/blob/master/stable/verdaccio/README.md#prerequisites

I installed Kubernetes 1.6 with homebrew. It's not supported?

**Comment by juanpicado** [comment]
Nevermind :) I was trying to do this https://github.com/verdaccio/docker-examples/tree/master/kubernetes-helm-example
