### ISSUE TITLE
Minor issue in middleware test snapshots

### ISSUE THREAD

**Issue by mbtools** [verdaccio/verdaccio#4688]
There's some inconsistency in generating the favicon URL:

https://github.com/verdaccio/verdaccio/blob/0f94336a9edd76db104e386678fed9da7211e7b8/packages/middleware/test/__snapshots__/template.test.ts.snap#L11

https://github.com/verdaccio/verdaccio/blob/0f94336a9edd76db104e386678fed9da7211e7b8/packages/middleware/test/__snapshots__/template.test.ts.snap#L36

I'm not sure if this is a problem with the test or the template 🤷 Is `base` supposed to have a trailing `/` or is `/` missing in the template?

https://github.com/verdaccio/verdaccio/blob/0f94336a9edd76db104e386678fed9da7211e7b8/packages/middleware/test/template.test.ts#L14

https://github.com/verdaccio/verdaccio/blob/0f94336a9edd76db104e386678fed9da7211e7b8/packages/middleware/src/middlewares/web/utils/template.ts#L33

**Comment by juanpicado** [comment]
Is this solved with the latest PR? @mbtools
