### ISSUE TITLE
Different pnpm versions used for local and docker builds

### ISSUE THREAD

**Issue by mbtools** [verdaccio/verdaccio#4714]
For local builds, it uses 8.14.0, for docker it's 8.9.0. Should we bump the docker to 8.14.0? 

https://github.com/verdaccio/verdaccio/blob/3b3cf86b54dfbcd4cabb50b8cd3ae79821f3cf83/package.json#L187

https://github.com/verdaccio/verdaccio/blob/3b3cf86b54dfbcd4cabb50b8cd3ae79821f3cf83/Dockerfile#L14

**Comment by juanpicado** [comment]
Oh yeah, well the Dockerfile at root is not entirely used right now, the official one is 5.x but I think the whole docker file on the master branch might need some big clean up.

**Comment by mbtools** [comment]
I did a 3way comparison. I now see the docker setup in master is very different from 5x and 6x. Learning more about the incredible automation setup in this project 👍
