### ISSUE TITLE
Create storage plugin for Amazon S3

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#472]
https://www.npmjs.com/package/s3

Example:

https://github.com/verdaccio/verdaccio-memory
https://github.com/verdaccio/local-storage

**Comment by drubin** [comment]
Just some feedback I started building this plugin and ran into issues using the https://www.npmjs.com/package/s3 package. Its incredibly slow and the built-in aws package is incredibly old.

https://github.com/andrewrk/node-s3-client/issues/111 

S3 ~2.4.9 vs aws-sdk-js 2.188.0

https://github.com/aws/aws-sdk-js/blob/master/package.json#L4 

There are workarounds like injecting a newer version, but I really don't see much point, The only thing the s3 package provided over the official library was the ability to split the package into multiple parts - Which is now handled by the official client.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property

**Comment by dmk255** [comment]
I would really appreciate this sort of plugin. I've just found verdaccio recently and having this sort of persistence would be great for my (small) team.

**Comment by juanpicado** [comment]
@mohsen1 it would be great to have either a guide, docs or something to show people how to do it. 

btw. I'm working on Google Cloud plugin https://github.com/verdaccio/verdaccio/issues/473

and I think @ayusharma was experimenting with Amazon S3 as storage.

**Comment by apexskier** [comment]
FYI, working on this at https://github.com/Remitly/verdaccio-s3-storage/pull/1

**Comment by cjsfj** [comment]
Would be awesome if we had the option to use any S3 hostname, and not be locked into Amazon proper. There are open source (Minio, Zenko) and commercial (Dell ECS, IBM CoS) that act as S3 object storage, and I think all that would be needed is a way to provide the URL of the service in the config.

**Comment by apexskier** [comment]
My plugin is working (at least for my setup). If anyone wants to help test it, feel free! Open PRs or issues for any confusion, bugs, or feature requests.

https://github.com/remitly/verdaccio-s3-storage

**Comment by juanpicado** [comment]
Thanks @apexskier !! I'll try to test as well :-) ... Closing this, great work.

**Comment by lenovouser** [comment]
@apexskier thanks for creating the plugin! Is it possible to migrate from the standard FS storage to S3 somehow?

**Comment by apexskier** [comment]
@lenovouser Should be, I'm going to open a new discussion in an issue in https://github.com/remitly/verdaccio-s3-storage so folks can find it in the future.
