### ISSUE TITLE
Show version in web user interface

### ISSUE THREAD

**Issue by tvb** [verdaccio/verdaccio#486]
It would be nice to display the current running version or git hash in the web user interface to quickly identify which version is installed

**Comment by juanpicado** [comment]
It makes total sense. Since we do not have a footer, do you have any idea?

**Comment by tvb** [comment]
Can't you just create a footer? 😂

**Comment by juanpicado** [comment]
Well, let me ask @Meeeeow and @ayusharma . Perhaps they have an idea.

**Comment by Meeeeow** [comment]
@juanpicado 😄 Just add it, put some words such as "Built with ❤️ in Country, Country, Country..." with helpful links, about, document, version, etc.

**Comment by juanpicado** [comment]
@Meeeeow lol I'd love that for sure :) and that's true, our unique budget now is only --> ❤️

**Comment by juanpicado** [comment]
Lovely ❤️  . I think @tvb will be happy with your work @Meeeeow 
![Uploading Opera Snapshot_2018-01-29_011532_localhost.png…]()

**Comment by juanpicado** [comment]
Final result, it will be released in the next alpha
![gif](https://user-images.githubusercontent.com/558752/35767103-ddc6fdee-08e5-11e8-997f-2d1b45cda05a.gif)

**Comment by tvb** [comment]
Sexy 😍
