### ISSUE TITLE
logging is broken in 8.x

### ISSUE THREAD

**Issue by mbtools** [verdaccio/verdaccio#4873]
**Your Environment**

 * **verdaccio version**: 8.0.0-next-8.2
 * **node version** 20.17.0
 * **package manager**: npm@10.8.2, pnpm@8.14.0
 * **os**: windows@10
 * **platform**: win32

**Describe the bug**

Logging stops after initial startup messages:

![image](https://github.com/user-attachments/assets/ac1da65e-0c79-46c5-b40e-774dc67e42a7)

**To Reproduce**

- Start verdaccio 8.x
- Run any npm command like `npm install lodash`
- There's no logging of requests

**Expected behavior**

- Should work as before
- It works fine in 5.x, 6.x, 7.x 

7.0.0-next-8.21 works (see "Get Logs" step):

https://github.com/mbtools/verdaccio-proxy-config-test-case/actions/runs/11095626797/job/30824505316

8.0.0-next-8.0 no logging (see "Get Logs" step):

https://github.com/mbtools/verdaccio-proxy-config-test-case/actions/runs/11096350384/job/30826093296
 
Maybe something went wrong with https://github.com/verdaccio/verdaccio/pull/4839

**Comment by juanpicado** [comment]
Thanks, I'll take a look when I'm finished with the vitest migration.

**Comment by mbtools** [comment]
Looks like it's working now. Ty
