### ISSUE TITLE
Docker `latest` tag missing

### ISSUE THREAD

**Issue by jonnyt886** [verdaccio/verdaccio#488]
Attempting to pull the latest docker image results in

    Unable to find image 'verdaccio/verdaccio:latest' locally
    docker: Error response from daemon: manifest for verdaccio/verdaccio:latest not found.

...the documentation seems to suggest that this tag should be supported. It's always worked in the past.

Could you re-introduce the tag or update the docs on the Docker Hub page to explain that `:latest` is not supported?

#### Steps to reproduce:
`docker run verdaccio/verdaccio` or similar.

Edit: just to clarify, `docker run verdaccio/verdaccio:2` works fine.

**Comment by juanpicado** [comment]
Fixed it already. You guys are super fast 😆  ... it was down only 20 minutes.

**Comment by jonnyt886** [comment]
;-)
