### ISSUE TITLE
Push 2.7.3 to dockerhub

### ISSUE THREAD

**Issue by chainlink** [verdaccio/verdaccio#489]
Hi there,
I'm trying to pull 2.7.3, but it's not in docker hub. Could you please build and push it?

It was requested for this helm chart upgrade https://github.com/kubernetes/charts/pull/3304

**Comment by juanpicado** [comment]
I did it already. Could you check again?

**Comment by juanpicado** [comment]
```
➜ docker pull verdaccio/verdaccio:2.7.3
2.7.3: Pulling from verdaccio/verdaccio
Digest: sha256:c68c0b96b0cf89ec97bc27e5eddc2000bc5f15c1f57dac16613c2ee29c07fe3d
Status: Downloaded newer image for verdaccio/verdaccio:2.7.3
```

**Comment by chainlink** [comment]
Perfect thanks!
