### ISSUE TITLE
CORS errors in web interface after alternating access with different host names

### ISSUE THREAD

**Issue by nkolotov** [verdaccio/verdaccio#4919]
**Your Environment**
 * **verdaccio version**: 5.32.2
 * **node version** none
 * **package manager**: none
 * **os**:  mac, windows@10, linux
 * **platform**: docker

**Describe the bug**

For example i have verdaccio container running on server with IP `10.30.2.2`  with `vdtest.com` domain name. It starts fine and i can open `http://vdtest.com:4873/` in browser and see package list. Everything works fine so far.

Now if i open `http://10.30.2.2:4873/` then i will see page with "No Package Published Yet." message with some mentions of vdtest.com. 
![vdtest](https://github.com/user-attachments/assets/f8d18cc7-f621-4de8-9b36-105423e9c61b)

Opening dev tools in browser shows CORS errors:
```
main.55cdd4aea43adabcb109.js:2 Refused to connect to 'http://vdtest.com:4873/-/verdaccio/data/packages' because it violates the following Content Security Policy directive: "connect-src 'self'".
```
Also page pulls some static resources from `vdtest.com`, such as `vdtest.com:4873/-/static/Home.55cdd4aea43adabcb109.js`, `vdtest.com:4873/-/static/main.55cdd4aea43adabcb109.js`, `vdtest.com:4873/-/static/runtime.55cdd4aea43adabcb109.js`, `vdtest.com:4873/-/static/vendors.55cdd4aea43adabcb109.js`.

If i restart server and access `http://10.30.2.2:4873/` first then it will work fine however subsequent access using url with domain name `http://vdtest.com:4873/` will yield similar CORS errors.

It seems that there is a problem with the way verdaccio server populates its internal cache. It does not take hostname used in request into consideration so the host from very first request gets memorized and served for all the users regardless of the host name they use until server cache is expired or server is restarted. As a result access using multiple host names is broken. I believe the proper term for this kind of problem is "cache poisoning".

**Comment by juanpicado** [comment]
Disable html_cache that might work but this topic has been discussed few times, please take a look at the other discussion and issues.

**Comment by nkolotov** [comment]
@juanpicado Thank you for the quick reply. Using `html_cache` as a keyword i've managed to find some previous issues, such a [General cache issue in Verdaccio Web UI](https://github.com/verdaccio/verdaccio/issues/3769) so i guess this one is indeed a duplicate. Setting `html_cache` to `false` in config seems to make access from different host names work. However it looks more like a workaround rather than a proper fix. Is behavior with `html_cache: true` actually intentional? Even if it supposed to handle only a single host name then it would make sense to perform a redirect or return an error when page is accessed at mismatching host rather than silently serve broken page.
