### ISSUE TITLE
Ability to restrict unpublish action to certain users

### ISSUE THREAD

**Issue by ghost** [verdaccio/verdaccio#492]
#### My reason:

This is likely more of a question, however it's a functionality that may not be available. 
I've looked in the config file examples and only seeing control over publish actions, but not unpublish. 

I'm working on configuring the `config.yaml`

**My Goals:**
- Any user can authenticate (create acct/login)
- Any authenticated user can publish new packages or package versions
- Only certain users can **unpublish** any package

####  Config file:	
I already have 
```publish: $authenticated```
but I'm looking for something similar to that but for deleting packages (unpublish)

Something like: 
```
publish: $authenticated
unpublish: myuser1
```

Is this possible?

**Comment by e-sathya** [comment]
We are looking for similar feature +1

**Comment by fisherw** [comment]
We are looking for similar feature +1

**Comment by juanpicado** [comment]
Be aware of #1223 PR that will provide this feature. Please leave your thoughts there if you have still some 🤓

**Comment by dlarr** [comment]
Hello, this is awsome feature. Do you know when we can hope for this to be available ? 

Regards

**Comment by juanpicado** [comment]
Documentation for `unpublish` settings
https://github.com/verdaccio/website/blob/master/docs/packages.md#unpublishing-packages

**Comment by dlarr** [comment]
Thank you so much @juanpicado 

I am looking for to using this awsome new feature. Can you tell me wich version of verdaccio will implement it ? And where I can find the information if into github project 

regards,
Denis.

**Comment by juanpicado** [comment]
Hi @dlarr , next alpha, this week at any moment. We are waiting to finish a couple of things.

**Comment by juanpicado** [comment]
Testable here

```
docker pull verdaccio/verdaccio:4.x-next
```
