### ISSUE TITLE
Accessing uplink with a client certificate

### ISSUE THREAD

**Issue by michaelschneiderdaimler** [verdaccio/verdaccio#493]
#### My reason:

I would like to setup verdaccio as a internal npm registry, proxying npmjs.org (we do have some firewall issues) and an internal JFrog registry. Unfortunately, JFrog is hiding behind a HTTPS connection, requiring the connecting app to supply a client certificate. 
I do have a technical user's certificate that I could supply, but I haven't figured out a way to do this in verdaccio. Is this possible at all?
Apparently, the npm-registry-client package could do this, but as far as I can see, this is not used within verdaccio, right?
Thank you!

####  App Version:	
Verdaccio 2.7.2

**Comment by juanpicado** [comment]
hi @michaelschneiderdaimler the documentation is outdated. If you want to add a custom certificate for an uplink you need to do the following:

```yaml
uplinks:
  jfrog:
    url: https://local.jfrog.domain/
    ca: ~/foo/bar/cert.crt
```

I think that will solve the issue. Let me know whether it works

**Comment by michaelschneiderdaimler** [comment]
Hi Juan,
many thanks, that helps a lot!
regards
michael
