### ISSUE TITLE
Should handle resolution errors gracefully

### ISSUE THREAD

**Issue by Wildhoney** [verdaccio/verdaccio#495]
We use `verdaccio` at work; it's accessible when on the private network either in the office or via VPN. However, when the private npm registry is inaccessible I can't use `npm` any more because:

```
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to http://bs-stevedore01.lonres.lan:4873/leaflet failed, reason: getaddrinfo ENOTFOUND bs-stevedore01.lonres.lan bs-stevedore01.lonres.lan:4873
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

Is there any way for `npm` to handle that gracefully, because I don't want to have to modify my `.npmrc` file when I'm not at work (or on the VPN)?

**Comment by juanpicado** [comment]
hi @Wildhoney I'm not sure how we can help here because verdaccio is a server-side tool, `npm` is a different tool out of our control.

**Comment by Wildhoney** [comment]
Thanks. I’ll take it up with npm 👍
