### ISSUE TITLE
Mirroring of the Verdaccio image in Artifactory fails due to emojis in its description

### ISSUE THREAD

**Issue by pre** [verdaccio/verdaccio#4963]
We have a Donald Duck issue with mirroring the Verdaccio container images in our corporate Artifactory container image registry:
* Artifactory does not support emojis in the container image metadata.

Verdaccio has two emoji characters in its container image metadata `description` field. 

This request might sound silly but this is a real pain for us. Due to enterprise reasons, we need to mirror this image in order to use it. And we have no other alternative than the enterprise Artifactory. We wish not to setup any custom build pipelines or custom processing which would remove these emojis.

Pretty please 🍰  
* Could you remove the emoji characters from the container image metadata? 

![image](https://github.com/user-attachments/assets/ddbd710e-e673-4aa1-89e7-8859738b10a8)

**Comment by juanpicado** [comment]
Funny 😁 but reasonable, done ✅

**Comment by mbtools** [comment]
I thought a DD issue looked like this:

![image](https://github.com/user-attachments/assets/7beb028e-1191-47f3-bc94-f312f51466c0)

First time I hear the term but it makes sense to name an issue like this 😄 Did you just come up with it?

**Comment by pre** [comment]
My elementary school mathematics teacher called all silly problems Donald Duck issues & Mickey Mouse problems in the 90’s. I’ve used the term ever since.

**Comment by mbtools** [comment]
I shall borrow it :-) 

Did "corporate" mean SAP? How about sponsoring this great project via Open Collective?

**Comment by juanpicado** [comment]
It was released, I guess I can close this.
