### ISSUE TITLE
How do I install verdaccio plugins on kubernetes?

### ISSUE THREAD

**Issue by ujc** [verdaccio/verdaccio#532]
_**question:**_

I've read the docs on using verdaccio on kubernetes (not using Helm).
I know how to configure verdaccio using the config-map.

But how do I install plugins using kubernetes?
I want to install a gitlab auth plugin..

Thx in adv!

**Comment by juanpicado** [comment]
@ujc are you using Docker? Could you describe ore your environment?

**Comment by ujc** [comment]
Yes, using Docker as the container engine.

So it's a Kubernetes Node, inside which is a Kubernetes Pod, that runs the Docker container, executing the Verdaccior Docker Image.

I've also set up persistent storage.
Wondering if I should just SSH into the pod, install the plugin, and hope it will persist... do you think that should work?

*Thx for the help in anycase.. really like using Verdaccio (used it in the past on our own server - was awesome!)

**Comment by juanpicado** [comment]
Hi @ujc . I'm not a Kubernetes expert, but let me see how we can help you with the best approach to install plugins, there is one suggestion never was merged we might take a look to see whether works or not. https://github.com/verdaccio/verdaccio/pull/232

**Comment by MichielDeMey** [comment]
Just stumbled on this issue, seems like the original PR (#232) was going in the right direction for loading plugins in a Docker/Kubernetes environment.

**Comment by juanpicado** [comment]
New PR is welcome, I'll be happy to review it asap.

**Comment by MichielDeMey** [comment]
I'll try to get in a PR today based on the original idea of loading plugins from a separate directory.
