### ISSUE TITLE
htpasswd issue with docker container and mounted folders

### ISSUE THREAD

**Issue by bouchezb** [verdaccio/verdaccio#557]
#### My reason:

Hi, i installed Verdaccio on my VPS and got an issue with user management.
First, I used the docker image and everything was fine (UI + npm publish).
After that, i decided to use the same image, but i mounted local folders for config and storage.
When i started my container, i was unable to connect to the UI.
`npm publish` don't work anymore.

I found that default `htpasswd` file was not created. I don't know why.
When i inspect my old container, i can find an htpasswd file with correct data.

Seems that `npm adduser` doesn't work the way it is supposed to do.
I checked my directory rights and everything seems ok.
Am I missing something ?

Thanks

#### Steps to reproduce:

* Start a docker image with commands provided in documentation.
```
V_PATH=/path/for/verdaccio; docker run -it --rm --name verdaccio -p 4873:4873 \
  -v $V_PATH/conf:/verdaccio/conf \
  -v $V_PATH/storage:/verdaccio/storage \
  verdaccio/verdaccio
```
* run `npm adduser` and try to log in UI. It will fail even if `npm adduser` give a OK.
* Back to a container without mounted folders will solve the issue.
 
####  App Version:	
latest docker image

####  Config file:	
default

#### Additional information:

Will try to provide additional informations with debug mode asap

**Comment by juanpicado** [comment]
It seems those files have to exist already as this example describes. https://github.com/verdaccio/docker-examples/tree/master/docker-local-storage-volume/conf

````
➜ docker run -it --rm --name verdaccio -p 4873:4873 \
-v /Users/user/verdaccio_storage/conf/:/verdaccio/conf \
-v /Users/user/verdaccio_storage/storage/:/verdaccio/storage \
verdaccio/verdaccio:v2.1.5
Unable to find image 'verdaccio/verdaccio:v2.1.5' locally
v2.1.5: Pulling from verdaccio/verdaccio
8b87079b7a06: Pull complete 
a3ed95caeb02: Pull complete 
1bb8eaf3d643: Pull complete 
3e04171ce2e5: Pull complete 
0b73d3fea769: Pull complete 
639c270113c9: Pull complete 
c9ca6f8bff52: Pull complete 
aebed29b5cd3: Pull complete 
b7c9d444bfba: Pull complete 
71a11331552d: Pull complete 
9df9a9c66c45: Pull complete 
81dd169018dd: Pull complete 
1744ece8f6f7: Pull complete 
Digest: sha256:23dd0a87475fbe9a869cc4d7f66d3371f7ed483993d0e32a6b6d051ac0315884
Status: Downloaded newer image for verdaccio/verdaccio:v2.1.5
Verdaccio doesn't need superuser privileges. Don't run it under root.
 fatal --- cannot open config file /verdaccio/conf/config.yaml: ENOENT: no such file or directory, open '/verdaccio/conf/config.yaml'
````
It might be a a bug or a Docker limitation, verdaccio should create those files if Docker allow it (which I'm not sure).

**Comment by bouchezb** [comment]
Hi,

Thanks for your feedback.
I did a rollback on my config and use the container without mounted folders.
Works fine so far.
