### ISSUE TITLE
Reset htpasswd database

### ISSUE THREAD

**Issue by alexmngn** [verdaccio/verdaccio#559]
Hello,
I've forgot my password and can't login with my user. I tried to reinstall verdaccio globally but it seems like the data stays in the computer. How can I reset the database and reinstall everything from 0? Where is the config file?
Thanks

**Comment by juanpicado** [comment]
Look into your local storage (http://www.verdaccio.org/docs/en/cli.html#default-config-file-location) and open the file `htpasswd` and edit it manually. That's a quick way.

**Comment by alexmngn** [comment]
I don't have anything at `~/.local/verdaccio/config.yaml`, I'm running a Mac.

**Comment by ayusharma** [comment]
@alexmngn Please try to find your config file using this `cat ~/.config/verdaccio/config.yaml`
