### ISSUE TITLE
Capitalization on package name

### ISSUE THREAD

**Issue by oltodo** [verdaccio/verdaccio#583]
Hi,

I'm not comfortable with package name's capitalization on package detail page. It's probably the best and more natural way to copy the entire package name. However the point is that it's capitalized makes its use less relevant.

![image](https://user-images.githubusercontent.com/483842/36416654-f890b9b6-1629-11e8-8dfb-4a6cf21bd2e6.png)

What do you think?

**Comment by juanpicado** [comment]
You are totally right. Are you willing to PR?

**Comment by oltodo** [comment]
No but I can!

**Comment by juanpicado** [comment]
Please :) and I'll ship it in the next alpha release.

**Comment by oltodo** [comment]
Done https://github.com/verdaccio/verdaccio/pull/584. Thanks for you respond!

**Comment by juanpicado** [comment]
Thanks you for reporting :) and contributing
