### ISSUE TITLE
Add support for strictSSL in upstream repos

### ISSUE THREAD

**Issue by ajlozier** [verdaccio/verdaccio#587]
#### My reason:

I am using upstream repos which use self-signed certificates. Without this enhancement, my repos are taken offline immediately due to a self-signed certificate in chain error.

#### Steps to reproduce:

Add uplink repo which is secured using self-signed certificate. Attempts to install any modules will result in this repo being taken offline by verdaccio.

####  App Version:	

2.x

####  Config file:	

Suggested change to config file:

`# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

    # amount of time to wait for repository to respond
    # before giving up and use the local cached copy
    #timeout: 30s

    # maximum time in which data is considered up to date
    #
    # default is 2 minutes, so server won't request the same data from
    # uplink if a similar request was made less than 2 minutes ago
    #maxage: 2m

    # if two subsequent requests fail, no further requests will be sent to
    # this uplink for five minutes
    #max_fails: 2
    #fail_timeout: 5m

    # timeouts are defined in the same way as nginx, see:
    # http://wiki.nginx.org/ConfigNotation

    # add/override HTTP headers sent to the uplink server
    # this allows for HTTP Basic auth for example:
    #headers:
    #  authorization: "Basic YourBase64EncodedCredentials=="

    # set this to false to prevent tarballs from this upstream
    # to be stored in the local storage (defaults to true)
    #cache: false
    
    # set this to false to disable strict SSL checking (defaults to true)
    #strictSSL: false`

#### Additional information:

Tentative fix here: https://github.com/ajlozier/verdaccio/tree/Branch_v2.7.4

I wanted to submit as an issue before issuing PR to get feedback and also to provide background.

**Comment by juanpicado** [comment]
Nice ... could you PR? :) In any case would be only available in `v3`. If you PR please do not forget to update documentation in `/docs` folder.

**Comment by ajlozier** [comment]
Ok, I will create a new branch based off master and will be sure to update the docs as well. Thanks!
