### ISSUE TITLE
Maximum cache length?

### ISSUE THREAD

**Issue by philip-peterson** [verdaccio/verdaccio#59]
I am wondering if there is some way to set a maximum cache length (e.g. 2 days)? In my scenario what I would really like to do is have the cache length set to 0 days, so that verdaccio always checks if there is a newer version (even when a local version satisfying the semver exists), and only if there isn't, it should serve the one in the cache.

This is so that we can always be using the latest versions of everything but have older versions for backups just in case.

**Comment by ChadKillingsworth** [comment]
Can you give an example with a specific package and semver scenario where it doesn't work this way?

**Comment by juanpicado** [comment]
I think `verdaccio` always ask by default to the uplinks after 2 minutes by default. All documentation about uplinks is available here. https://github.com/verdaccio/verdaccio/blob/master/wiki/uplinks.md#configuration
