### ISSUE TITLE
Can't get tokens for existing users

### ISSUE THREAD

**Issue by mariomarin** [verdaccio/verdaccio#61]
When I run `npm adduser --registry http://npm.example.com:4873` I expect a _NPM_TOKEN_ inside _~/.npmrc_ but I get the following error instead:

```
this user already exists : -/user/org.couchdb.user:johndoe/-rev/undefined
```

We are using ansible to populate an htpasswd file, here is the authentication configuration:

```
auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
```

Do you plan to add support to generate NPM_TOKENs? Is there a workaround to generate them?

How can I prevent the creation of a new user? It seems that anyone can create users;  get the registry's url, run `npm adduser` and you can access the packages. To prevent access from unexpected users, I changed the permissions of _/verdaccio/conf/htpasswd_ to 0444.

**Comment by ChadKillingsworth** [comment]
The server doesn't keep tokens. Instead, the "token" it returns is your encrypted credentials. So I don't expect this to ever be supported.

**Comment by juanpicado** [comment]
@mariomarin as @ChadKillingsworth said, there is no way to sign in a existing user, always is going to return a new token. I guess depends of the auth plugin you use. So, natively verdaccio delegates the plugin how to handle tokens. I'll let you a list of plugins I collected in the wiki https://github.com/verdaccio/verdaccio/wiki/Plugins
