### ISSUE TITLE
Flowtype Performance Issues

### ISSUE THREAD

**Issue by ryyppy** [verdaccio/verdaccio#610]
Hi!
So as a follow up for the ViennaJS meetup, I was looking a little bit into the flow setup and I think the culprit is not the number of source files in the repository, but more like the parsing process of the library definitions in `flow-typed`.

Since you are using `lodash_4.x.x`, I think this flow issue is related:
https://github.com/facebook/flow/issues/5784

Not entirely sure how to fix that :-/

**Comment by juanpicado** [comment]
Thanks for dive into it, I'll try to run it avoiding `lodash` and let's see the difference.

**Comment by juanpicado** [comment]
Actually, without `lodash` (I created a stub) is super fast

```
npx flow  0.11s user 0.04s system 5% cpu 2.979 total
```
vs `lodash_v4.x.x.js`

```
npx flow  0.11s user 0.06s system 0% cpu 1:08.64 total
```

**Comment by juanpicado** [comment]
@ryyppy with Flow 0.69.0 flies again 🚀 🚀 🚀 🚀 . No more concerns with Flow anymore 👍
