### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by taylk808** [verdaccio/verdaccio#611]
OS: Ubuntu 16
Node 8.9
NPM 3.3

I've installed verdaccio using NPM.  It was installed and then started without error. When accessing site http://localhost:4873/, I get error ERR_EMPTY_RESPONSE in Chrome.  Did installation to two different servers, but same issue.  Anyone have any suggestions on how to resolve?

**Comment by juanpicado** [comment]
Try to access it via curl or wget. Also hit with npm and see the outcome.

**Comment by taylk808** [comment]
curl returns the following on one of the two servers:

<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <title>Verdaccio</title>
    <link rel="icon" type="image/png" href="http://localhost:4873/-/static/favicon.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script>
        window.VERDACCIO_API_URL = 'http://localhost:4873/-/verdaccio/';
    </script>
<link href="http://localhost:4873/-/static/style.8410f14de467c42d2f6c14c7df197f3f.css" rel="stylesheet"></head>
<body class="body">
    <div id="root"></div>
<script type="text/javascript" src="http://localhost:4873/-/static/main.54a8238b472a2df05ec1.js"></script></body>
</html>

**Comment by juanpicado** [comment]
Well, I'm blind unless you provide more detailed information. Please read https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/issue_template.md and try to fulfill all the steps

**Comment by taylk808** [comment]
Here are the outputs:
config.yaml
------------
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
 web:
  enable: true
  title: Verdaccio
  logo: logo.png
packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
      access: $all
    publish: $authenticated
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}
url_prefix: http://localhost/verdaccio/
listen:
 - localhost:4873

NODE_DEBUG=request verdaccio
-------------------------------------
 warn --- config file  - /root/.config/verdaccio/config.yaml
 warn --- http address - http://localhost:4873/ - verdaccio/2.7.4
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /', bytes: 0/662
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /', bytes: 0/662

npm -ddd
npm info it worked if it ends with ok
npm verb cli [ '/root/.nvm/versions/node/v8.9.3/bin/node',
npm verb cli   '/root/.nvm/versions/node/v8.9.3/bin/npm',
npm verb cli   '-ddd' ]
npm info using npm@5.5.1
npm info using node@v8.9.3
npm verb config Skipping project config: /root/.npmrc. (matches userconfig)

npm config get registry
------------------------
https://registry.npmjs.org/

DEBUG=express:* verdaccio
--------------------------------
 warn --- config file  - /root/.config/verdaccio/config.yaml
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +2ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'int' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +1ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +1ms
  express:application booting in int mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/root/views' +1ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:application set "env" to 'int' +0ms
  express:router use '/' query +1ms
  express:router:layer new '/' +1ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +1ms
  express:router use '/' corsMiddleware +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +0ms
  express:router use '/' error_reporting_middleware +0ms
  express:router:layer new '/' +1ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +0ms
  express:router use '/' compression +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/favicon.ico' +1ms
  express:router:layer new '/favicon.ico' +0ms
  express:router:route get '/favicon.ico' +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +39ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/whoami' +0ms
  express:router:layer new '/whoami' +1ms
  express:router:route get '/whoami' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/whoami' +1ms
  express:router:layer new '/-/whoami' +0ms
  express:router:route get '/-/whoami' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/:package/:version?' +0ms
  express:router:layer new '/:package/:version?' +1ms
  express:router:route get '/:package/:version?' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/:package/:version?' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/-/:filename' +1ms
  express:router:layer new '/:package/-/:filename' +0ms
  express:router:route get '/:package/-/:filename' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/:package/-/:filename' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/-/all(/since)?' +0ms
  express:router:layer new '/-/all(/since)?' +1ms
  express:router:route get '/-/all(/since)?' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/user/:org_couchdb_user' +1ms
  express:router:layer new '/-/user/:org_couchdb_user' +0ms
  express:router:route get '/-/user/:org_couchdb_user' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/user/:org_couchdb_user/:_rev?/:revision?' +1ms
  express:router:layer new '/-/user/:org_couchdb_user/:_rev?/:revision?' +0ms
  express:router:route put '/-/user/:org_couchdb_user/:_rev?/:revision?' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/user/token/*' +0ms
  express:router:layer new '/-/user/token/*' +1ms
  express:router:route delete '/-/user/token/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/_session' +1ms
  express:router:layer new '/_session' +0ms
  express:router:route post '/_session' +0ms
  express:router:layer new '/' +1ms
  express:router:route post '/_session' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/:tag' +1ms
  express:router:layer new '/:package/:tag' +0ms
  express:router:route put '/:package/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/:package/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:route post '/-/package/:package/dist-tags/:tag' +1ms
  express:router:layer new '/' +0ms
  express:router:route post '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/-/package/:package/dist-tags/:tag' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:route put '/-/package/:package/dist-tags/:tag' +1ms
  express:router:layer new '/' +0ms
  express:router:route put '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/-/package/:package/dist-tags/:tag' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:route delete '/-/package/:package/dist-tags/:tag' +1ms
  express:router:layer new '/' +0ms
  express:router:route delete '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/-/package/:package/dist-tags' +1ms
  express:router:route get '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/-/package/:package/dist-tags' +1ms
  express:router:route post '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/-/package/:package/dist-tags' +1ms
  express:router:layer new '/' +0ms
  express:router:route post '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/-/package/:package/dist-tags' +0ms
  express:router:route put '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/-/package/:package/dist-tags' +1ms
  express:router:route delete '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route delete '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route delete '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/:_rev?/:revision?' +1ms
  express:router:layer new '/:package/:_rev?/:revision?' +1ms
  express:router:route put '/:package/:_rev?/:revision?' +2ms
  express:router:layer new '/' +1ms
  express:router:route put '/:package/:_rev?/:revision?' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:_rev?/:revision?' +1ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:_rev?/:revision?' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/:package/-rev/*' +0ms
  express:router:layer new '/:package/-rev/*' +0ms
  express:router:route delete '/:package/-rev/*' +1ms
  express:router:layer new '/' +0ms
  express:router:route delete '/:package/-rev/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/-/:filename/-rev/:revision' +1ms
  express:router:layer new '/:package/-/:filename/-rev/:revision' +0ms
  express:router:route delete '/:package/-/:filename/-rev/:revision' +0ms
  express:router:layer new '/' +1ms
  express:router:route delete '/:package/-/:filename/-rev/:revision' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/-/:filename/*' +0ms
  express:router:layer new '/:package/-/:filename/*' +0ms
  express:router:route put '/:package/-/:filename/*' +1ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/-/:filename/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/-/:filename/*' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/:version/-tag/:tag' +1ms
  express:router:layer new '/:package/:version/-tag/:tag' +0ms
  express:router:route put '/:package/:version/-tag/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/:package/:version/-tag/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:version/-tag/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:version/-tag/:tag' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/ping' +0ms
  express:router:layer new '/-/ping' +0ms
  express:router:route get '/-/ping' +1ms
  express:router:layer new '/' +0ms
  express:router use '/' router +0ms
  express:router:layer new '/' +1ms
  express:router use '/' <anonymous> +2ms
  express:router:layer new '/' +0ms
  express:router use '/' securityIframe +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/static/:filename' +0ms
  express:router:layer new '/-/static/:filename' +1ms
  express:router:route get '/-/static/:filename' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/verdaccio/logo' +0ms
  express:router:layer new '/-/verdaccio/logo' +1ms
  express:router:route get '/-/verdaccio/logo' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +1ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +1ms
  express:router:layer new '/' +1ms
  express:router use '/' router +0ms
  express:router:layer new '/' +0ms
  express:router use '/' urlencodedParser +4ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +1ms
  express:router use '/' securityIframe +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/packages' +0ms
  express:router:layer new '/packages' +0ms
  express:router:route get '/packages' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/package/readme(/@:scope?)?/:package/:version?' +1ms
  express:router:layer new '/package/readme(/@:scope?)?/:package/:version?' +0ms
  express:router:route get '/package/readme(/@:scope?)?/:package/:version?' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/package/readme(/@:scope?)?/:package/:version?' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/search/:anything' +0ms
  express:router:layer new '/search/:anything' +0ms
  express:router:route get '/search/:anything' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/login' +0ms
  express:router:layer new '/login' +1ms
  express:router:route post '/login' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/logout' +1ms
  express:router:layer new '/-/logout' +0ms
  express:router:route post '/-/logout' +0ms
  express:router:layer new '/' +1ms
  express:router use '/-/verdaccio/' router +0ms
  express:router:layer new '/-/verdaccio/' +0ms
  express:router:route new '/*' +1ms
  express:router:layer new '/*' +0ms
  express:router:route get '/*' +0ms
  express:router:layer new '/' +1ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +1ms
 warn --- http address - http://localhost:4873/ - verdaccio/2.7.4
  express:router dispatching GET / +7s
  express:router query  : / +4ms
  express:router expressInit  : / +0ms
  express:router corsMiddleware  : / +1ms
  express:router <anonymous>  : / +1ms
  express:router error_reporting_middleware  : / +1ms
  express:router <anonymous>  : / +0ms
  express:router <anonymous>  : / +1ms
  express:router compression  : / +0ms
  express:router router  : / +1ms
  express:router dispatching GET / +0ms
  express:router <anonymous>  : / +0ms
  express:router jsonParser  : / +1ms
  express:router <anonymous>  : / +1ms
  express:router <anonymous>  : / +0ms
  express:router router  : / +1ms
  express:router dispatching GET / +0ms
  express:router <anonymous>  : / +1ms
  express:router securityIframe  : / +0ms
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /', bytes: 0/662

**Comment by ayusharma** [comment]
@juanpicado Everything seems fine. I gave a try to replicate it but not able to reproduce. The error 324 ERR_EMPTY_RESPONSE – No data received can be occurred due to connection. 

@taylk808 could you please provide network information (screenshot) from chrome dev tools.

**Comment by juanpicado** [comment]
yeah @ayusharma  I'm sure is not `verdaccio`. It might be something related with his set up.

**Comment by taylk808** [comment]
@ayusharma @juanpicado you folks are right after a number of testing, ERR_EMPTY_RESPONSE is caused by bad configuration on NGINX reverse proxy.  Issue has been resolved.
