### ISSUE TITLE
shasum check failed

### ISSUE THREAD

**Issue by wghust** [verdaccio/verdaccio#627]
version: 2.7.4

when I install a package from npm, I got the problem below.

![image](https://user-images.githubusercontent.com/3960935/37381418-0b0e0968-2778-11e8-8af2-1638c109444b.png)

**Comment by juanpicado** [comment]
I’ve seen that before, but, I do no think is a verdaccio issue. Most likely a npm. Please clean your cache an let reopen wether you are sure verdaccio causes that.

**Comment by tvb** [comment]
I have the same issue. No cache or package-lock is used:
```
Step 14/16 : RUN npm install 2>&1
 ---> Running in f5643120f3d9
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm ERR! code EINTEGRITY
npm ERR! sha1-RPebActo7QYbCqnkcFyNUiKvO08= integrity checksum failed when using sha1: wanted sha1-RPebActo7QYbCqnkcFyNUiKvO08= but got sha512-3pnd06wz5/YTIsVbvh4jGogA0B1vI3dyNgqjvxrVmYA5RqMqxk9Nn49LgPARME3hLkjQfqj7S8XB6CWQoKe/vQ== sha1-FQpWPXwvG0AGji19Or7brKjXeSo=. (18955 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-03T19_54_58_856Z-debug.log
The command '/bin/sh -c npm install 2>&1' returned a non-zero code: 1
```

total clueless what's going on.

**Comment by juanpicado** [comment]
It happened last week at work, the issue was the connection was failing and the tarball was being fetched from uplink corrupted, thus, integrity error. I'd try clean that specific tarball from storage, clean cache and try again. Compare bytes to ensure the tarball is complete.
