### ISSUE TITLE
Is 2.0.0 breaking compat compared with sinopia?

### ISSUE THREAD

**Issue by jakub-g** [verdaccio/verdaccio#63]
Hi, I'd like to migrate from sinopia, but it's not clear if it will be a smooth upgrade?

I don't see any CHANGELOG or wiki entries or [release info](https://github.com/verdaccio/verdaccio/releases) about breaking changes.

Thx in advance!

**Comment by trentearl** [comment]
I can't guarantee you a smooth upgrade, but it worked fine for me ;)
If you used the default sinopia configuration you should just need to move `~/.config/sinopia` to `~/.config/verdaccio`

I know it doesnt help you now but I added a changelog for future versions: https://github.com/verdaccio/verdaccio/blob/master/CHANGELOG.md

**Comment by jakub-g** [comment]
Finally I had to `npm install -g sinopia-htpasswd` after an upgrade, and then it works fine (with node 0.12.15). With node 4.x not exactly, I will open another issue

**Comment by jakub-g** [comment]
Ok in fact it seems I managed to migrate to node 4.x :) but it was not easy and I was lucky that you released 2.1.0 today

sinopia@latest + server nodejs 0.12.15 ok
verdaccio 2.0.1 + server nodejs 0.12.15 ok
sinopia@latest + server nodejs 4.4.7: `npm view packagename` takes forever
verdaccio 2.0.1 + server nodejs 4.6.0: `Error: socket hang up` when trying to `npm publish`
verdaccio 2.1.0 + server nodejs 4.6.0: finally works

Thanks
