### ISSUE TITLE
verdaccio prefix plugins

### ISSUE THREAD

**Issue by Nighthawk22** [verdaccio/verdaccio#64]
Hello,

I think for writing new plugins it would be really nice to be able to load plugins with verdaccio- prefix.

With kind regards,
Nighthawk

**Comment by juanpicado** [comment]
It's seems good for me, maybe the rename of #88 solves that.

**Comment by juanpicado** [comment]
There is some work related in this branch https://github.com/verdaccio/verdaccio/tree/refactoring-plugin, also you may visit https://github.com/verdaccio and see the future yeoman generator for plugins.

**Comment by juanpicado** [comment]
I think we can close this issue, actually you can create your own `verdaccio-` prefixed plugins as this set of plugins already done https://github.com/verdaccio/verdaccio/blob/master/wiki/plugins.md#verdaccio-plugins-since-21x.
