### ISSUE TITLE
Missing readme data inside a registry for external packages

### ISSUE THREAD

**Issue by aremishevsky** [verdaccio/verdaccio#640]
Hey guys.

I've noticed that we have missing Readme data of some packages (including verdaccio package) inside a registry:

{registry-url}/#/detail/verdaccio
{registry-url}/-/verdaccio/package/readme/verdaccio
{registry-url}/-/verdaccio/package/readme/react
{registry-url}/-/verdaccio/package/readme/redux
As result we have `<p>ERROR: No README data found!</p>`
But they exists and showing up on npmjs 
 - https://www.npmjs.com/package/verdaccio
 - https://www.npmjs.com/package/react
 - https://www.npmjs.com/package/redux

As an example - we have the correct data for lodash, fs-extra or some other external packages:
{registry-url}/-/verdaccio/package/readme/lodash
{registry-url}/-/verdaccio/package/readme/fs-extra

Can someone investigate why some packages are showing up correctly, but some not?

**Comment by juanpicado** [comment]
@aremishevsky could you provide more info, version, etc.

**Comment by aremishevsky** [comment]
Version is 3.0.0.beta-5

Verdaccio package
<img width="1165" alt="_local__npm_registry___chegg_" src="https://user-images.githubusercontent.com/32752187/38047463-4ca8fda2-32cb-11e8-8a68-a2df8d6e9b37.png">

React package
<img width="1171" alt="_local__npm_registry___chegg_" src="https://user-images.githubusercontent.com/32752187/38047493-62ec4be6-32cb-11e8-93a7-a45b10732b1c.png">

However Lodash package
<img width="1180" alt="_local__npm_registry___chegg_" src="https://user-images.githubusercontent.com/32752187/38047517-756c6ec2-32cb-11e8-96b3-0a6774b442a2.png">

Please let me know if you need some more details

**Comment by juanpicado** [comment]
Thanks @aremishevsky for details. I'll take a look 👍

**Comment by juanpicado** [comment]
For some reason when we parse `body = JSON.parse(body.toString('utf8'));` https://github.com/verdaccio/verdaccio/blob/master/src/lib/up-storage.js#L162 just wipe out the readme (HTML), I'm still do not understand.

**Comment by juanpicado** [comment]
> Can someone investigate why some packages are showing up correctly, but some not?

It seems only the new ones has this issue. It also affects branch `2.x`.

**Comment by juanpicado** [comment]
Even on the browser is not able to parse the `readme`. Just try. 🤕 
```
fetch('http://registry.npmjs.org/core-js').then(response => response.json()).then(data => console.log(data));
```

**Comment by juanpicado** [comment]
Ok, I just figured out.

```
http://registry.npm.taobao.org/core-js
```

vs

```
http://registry.npmjs.org/core-js
```

npmjs is returning a different metadata format, I did not notice that. Now we need to find a way to get the `readme` from the latest tag instead, we cannot rely readme would be in the root of the metadata

**Comment by aremishevsky** [comment]
@juanpicado maybe we should get the readme data from the global level of response (like it is now) and overriding it by the lates tag's readme (if it's set and not empty) ...

I mean not just get the readme from the lates tag - but try to get it from both places (latest tag's readme should have a higher priority)
So that your fix could cover both packages versions structure (old and new)

What do you think about this way?

**Comment by juanpicado** [comment]
I've been thinking about such approach, make sense for me. The problem is, npmjs is inconsistent, sometimes the latest version does not contain readme at all and the same in the root, the readme is empty (but not missing), but, if you go through recent versions, they have readme. 

So, I right now I cannot guarantee readme is gonna be displayed from npmjs. I'd wait until npmjs response for a while, otherwise, we can go with your approach as a workaround.

**Comment by aremishevsky** [comment]
Hi @juanpicado .
Could you please take a look on a fix here?
https://github.com/verdaccio/verdaccio/pull/654

**Comment by juanpicado** [comment]
@aremishevsky  I'll check it out.
