### ISSUE TITLE
Verdaccio don't work anymore with npm 5.8.0 ??????

### ISSUE THREAD

**Issue by aminechir** [verdaccio/verdaccio#649]
With npm 5.8.0

In a  console, I run verdaccio

In another console, when I try the command

 npm adduser --registry  http://localhost:4873

I get this error message: 

npm ERR! code E503
npm ERR! Registry returned 503 for POST on http://localhost:4873/-/v1/login

**Comment by aminechir** [comment]
Thank you for you answer; Here are your requests:


============================================
Environement
============================================

Windows 7
No docker
No Kubernetes

I am behind a proxy, here is my .npmrc:

bin-links=true
proxy=http://<myproxyadress>:<myproxyport>/
https-proxy=http://<myproxyadress>:<myproxyport>/
http-proxy=http://<myproxyadress>:<myproxyport>/
python=C:/Python2.7.10/Python.exe
msvs_version=2013
VisualStudioVersion=12.0
strict-ssl=true
registry=https://registry.npmjs.org/
//registry.npmjs.org/:_authToken=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


============================================
When I run verdaccio on the first console:
============================================


 warn --- config file  - C:\Users\a0h72255\AppData\Roaming\verdaccio\config.yaml

  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +3ms
  express:application set "etag fn" to [Function: generateETag] +1ms
  express:application set "env" to 'development' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryStri
ng] +1ms
  express:application set "subdomain offset" to 2 +1ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +1ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +1ms
  express:application set "views" to 'E:\\CHIR\\Code\\test\\views' +0ms
  express:application set "jsonp callback name" to 'callback' +1ms
  express:application set "env" to 'production' +1ms
  express:router use '/' query +1ms
  express:router:layer new '/' +1ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +1ms
  express:router use '/' corsMiddleware +0ms
  express:router:layer new '/' +1ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +1ms
  express:router use '/' error_reporting_middleware +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +0ms
  express:router use '/' compression +1ms
  express:router:layer new '/' +1ms
  express:router:route new '/favicon.ico' +0ms
  express:router:layer new '/favicon.ico' +0ms
  express:router:route get '/favicon.ico' +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +71ms
  express:router:layer new '/' +1ms
  express:router use '/' jsonParser +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +1ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/whoami' +1ms
  express:router:layer new '/whoami' +0ms
  express:router:route get '/whoami' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/whoami' +1ms
  express:router:layer new '/-/whoami' +0ms
  express:router:route get '/-/whoami' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/:version?' +1ms
  express:router:layer new '/:package/:version?' +0ms
  express:router:route get '/:package/:version?' +1ms
  express:router:layer new '/' +1ms
  express:router:route get '/:package/:version?' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/:package/-/:filename' +0ms
  express:router:layer new '/:package/-/:filename' +1ms
  express:router:route get '/:package/-/:filename' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/:package/-/:filename' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/all(/since)?' +1ms
  express:router:layer new '/-/all(/since)?' +1ms
  express:router:route get '/-/all(/since)?' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/user/:org_couchdb_user' +1ms
  express:router:layer new '/-/user/:org_couchdb_user' +0ms
  express:router:route get '/-/user/:org_couchdb_user' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/user/:org_couchdb_user/:_rev?/:revision?' +1ms
  express:router:layer new '/-/user/:org_couchdb_user/:_rev?/:revision?' +0ms
  express:router:route put '/-/user/:org_couchdb_user/:_rev?/:revision?' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/user/token/*' +1ms
  express:router:layer new '/-/user/token/*' +0ms
  express:router:route delete '/-/user/token/*' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/_session' +0ms
  express:router:layer new '/_session' +1ms
  express:router:route post '/_session' +0ms
  express:router:layer new '/' +1ms
  express:router:route post '/_session' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/:package/:tag' +0ms
  express:router:layer new '/:package/:tag' +1ms
  express:router:route put '/:package/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/:package/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/:package/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/-/package/:package/dist-tags/:tag' +1ms
  express:router:layer new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:route post '/-/package/:package/dist-tags/:tag' +1ms
  express:router:layer new '/' +0ms
  express:router:route post '/-/package/:package/dist-tags/:tag' +1ms
  express:router:layer new '/' +0ms
  express:router:route post '/-/package/:package/dist-tags/:tag' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags/:tag' +1ms
  express:router:layer new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:route put '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/-/package/:package/dist-tags/:tag' +1ms
  express:router:route delete '/-/package/:package/dist-tags/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route delete '/-/package/:package/dist-tags/:tag' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags' +1ms
  express:router:layer new '/-/package/:package/dist-tags' +0ms
  express:router:route get '/-/package/:package/dist-tags' +1ms
  express:router:layer new '/' +0ms
  express:router:route get '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/-/package/:package/dist-tags' +1ms
  express:router:route post '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +1ms
  express:router:route post '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +1ms
  express:router:route post '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/-/package/:package/dist-tags' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/package/:package/dist-tags' +1ms
  express:router:layer new '/-/package/:package/dist-tags' +1ms
  express:router:route put '/-/package/:package/dist-tags' +1ms
  express:router:layer new '/' +1ms
  express:router:route put '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/-/package/:package/dist-tags' +0ms
  express:router:layer new '/-/package/:package/dist-tags' +0ms
  express:router:route delete '/-/package/:package/dist-tags' +1ms
  express:router:layer new '/' +0ms
  express:router:route delete '/-/package/:package/dist-tags' +1ms
  express:router:layer new '/' +0ms
  express:router:route delete '/-/package/:package/dist-tags' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/:_rev?/:revision?' +1ms
  express:router:layer new '/:package/:_rev?/:revision?' +0ms
  express:router:route put '/:package/:_rev?/:revision?' +1ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:_rev?/:revision?' +1ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:_rev?/:revision?' +1ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:_rev?/:revision?' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/:package/-rev/*' +0ms
  express:router:layer new '/:package/-rev/*' +1ms
  express:router:route delete '/:package/-rev/*' +0ms
  express:router:layer new '/' +1ms
  express:router:route delete '/:package/-rev/*' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/:package/-/:filename/-rev/:revision' +0ms
  express:router:layer new '/:package/-/:filename/-rev/:revision' +1ms
  express:router:route delete '/:package/-/:filename/-rev/:revision' +0ms
  express:router:layer new '/' +1ms
  express:router:route delete '/:package/-/:filename/-rev/:revision' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/-/:filename/*' +1ms
  express:router:layer new '/:package/-/:filename/*' +0ms
  express:router:route put '/:package/-/:filename/*' +1ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/-/:filename/*' +1ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/-/:filename/*' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/:package/:version/-tag/:tag' +0ms
  express:router:layer new '/:package/:version/-tag/:tag' +1ms
  express:router:route put '/:package/:version/-tag/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/:package/:version/-tag/:tag' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/:package/:version/-tag/:tag' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:package/:version/-tag/:tag' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/ping' +1ms
  express:router:layer new '/-/ping' +0ms
  express:router:route get '/-/ping' +1ms
  express:router:layer new '/' +0ms
  express:router use '/' router +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +6ms
  express:router:layer new '/' +0ms
  express:router use '/' securityIframe +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/-/static/:filename' +1ms
  express:router:layer new '/-/static/:filename' +0ms
  express:router:route get '/-/static/:filename' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/-/verdaccio/logo' +0ms
  express:router:layer new '/-/verdaccio/logo' +1ms
  express:router:route get '/-/verdaccio/logo' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/' +1ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +1ms
  express:router:layer new '/' +0ms
  express:router use '/' router +0ms
  express:router:layer new '/' +1ms
  express:router use '/' urlencodedParser +6ms
  express:router:layer new '/' +1ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +1ms
  express:router use '/' securityIframe +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/packages' +0ms
  express:router:layer new '/packages' +0ms
  express:router:route get '/packages' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/package/readme(/@:scope?)?/:package/:version?' +1ms

  express:router:layer new '/package/readme(/@:scope?)?/:package/:version?' +0ms

  express:router:route get '/package/readme(/@:scope?)?/:package/:version?' +1ms

  express:router:layer new '/' +0ms
  express:router:route get '/package/readme(/@:scope?)?/:package/:version?' +1ms

  express:router:layer new '/' +0ms
  express:router:route new '/search/:anything' +1ms
  express:router:layer new '/search/:anything' +0ms
  express:router:route get '/search/:anything' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/login' +0ms
  express:router:layer new '/login' +1ms
  express:router:route post '/login' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/-/logout' +0ms
  express:router:layer new '/-/logout' +0ms
  express:router:route post '/-/logout' +1ms
  express:router:layer new '/' +0ms
  express:router use '/-/verdaccio/' router +1ms
  express:router:layer new '/-/verdaccio/' +0ms
  express:router:route new '/*' +1ms
  express:router:layer new '/*' +0ms
  express:router:route get '/*' +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +1ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +1ms
 warn --- http address - http://localhost:4873/ - verdaccio/2.7.4


============================================
Verdaccio config file
============================================

#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $all

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}




============================================
When I run in the 2nd console:  npm -ddd
============================================


npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\a0h72255\\AppData\\Roaming\\npm\\node_modules\\npm\\b
in\\npm-cli.js',
npm verb cli   '-ddd' ]
npm info using npm@5.8.0
npm info using node@v8.2.1

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, ci, completion,
    config, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\a0h72255\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.8.0 C:\Users\a0h72255\AppData\Roaming\npm\node_modules\npm



============================================
When I run in the 2nd console:  npm config get registry
============================================

https://registry.npmjs.org/


============================================
When I run in the 2nd console:  npm adduser --registry  http://localhost:4873
============================================

npm ERR! code E503
npm ERR! Registry returned 503 for POST on http://localhost:4873/-/v1/login


and the console never stops, i have to CTRL+C to kill the command


============================================
If i open the browser at http://localhost:4873/#/, the first console prints:
============================================


  express:router dispatching GET / +8m
  express:router query  : / +2ms
  express:router expressInit  : / +0ms
  express:router corsMiddleware  : / +1ms
  express:router <anonymous>  : / +1ms
  express:router error_reporting_middleware  : / +1ms
  express:router <anonymous>  : / +1ms
  express:router <anonymous>  : / +0ms
  express:router compression  : / +1ms
  express:router router  : / +1ms
  express:router dispatching GET / +0ms
  express:router <anonymous>  : / +0ms
  express:router jsonParser  : / +1ms
  express:router <anonymous>  : / +1ms
  express:router <anonymous>  : / +0ms
  express:router router  : / +1ms
  express:router dispatching GET / +0ms
  express:router <anonymous>  : / +1ms
  express:router securityIframe  : / +0ms
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /', bytes: 0/642
  express:router dispatching GET /-/static/style.8410f14de467c42d2f6c14c7df197f3
f.css +29ms
  express:router query  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f.css +
0ms
  express:router expressInit  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f
.css +1ms
  express:router corsMiddleware  : /-/static/style.8410f14de467c42d2f6c14c7df197
f3f.css +0ms
  express:router <anonymous>  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f
.css +0ms
  express:router error_reporting_middleware  : /-/static/style.8410f14de467c42d2
f6c14c7df197f3f.css +1ms
  express:router <anonymous>  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f
.css +0ms
  express:router <anonymous>  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f
.css +1ms
  express:router compression  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f
.css +0ms
  express:router router  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f.css
+0ms
  express:router dispatching GET /-/static/style.8410f14de467c42d2f6c14c7df197f3
f.css +1ms
  express:router <anonymous>  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f
.css +0ms
  express:router jsonParser  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f.
css +1ms
  express:router <anonymous>  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f
.css +0ms
  express:router <anonymous>  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f
.css +0ms
  express:router router  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f.css
+1ms
  express:router dispatching GET /-/static/style.8410f14de467c42d2f6c14c7df197f3
f.css +0ms
  express:router <anonymous>  : /-/static/style.8410f14de467c42d2f6c14c7df197f3f
.css +1ms
  express:router securityIframe  : /-/static/style.8410f14de467c42d2f6c14c7df197
f3f.css +0ms
  express:router dispatching GET /-/static/main.54a8238b472a2df05ec1.js +3ms
  express:router query  : /-/static/main.54a8238b472a2df05ec1.js +1ms
  express:router expressInit  : /-/static/main.54a8238b472a2df05ec1.js +0ms
  express:router corsMiddleware  : /-/static/main.54a8238b472a2df05ec1.js +1ms
  express:router <anonymous>  : /-/static/main.54a8238b472a2df05ec1.js +0ms
  express:router error_reporting_middleware  : /-/static/main.54a8238b472a2df05e
c1.js +0ms
  express:router <anonymous>  : /-/static/main.54a8238b472a2df05ec1.js +1ms
  express:router <anonymous>  : /-/static/main.54a8238b472a2df05ec1.js +0ms
  express:router compression  : /-/static/main.54a8238b472a2df05ec1.js +0ms
  express:router router  : /-/static/main.54a8238b472a2df05ec1.js +1ms
  express:router dispatching GET /-/static/main.54a8238b472a2df05ec1.js +0ms
  express:router <anonymous>  : /-/static/main.54a8238b472a2df05ec1.js +0ms
  express:router jsonParser  : /-/static/main.54a8238b472a2df05ec1.js +1ms
  express:router <anonymous>  : /-/static/main.54a8238b472a2df05ec1.js +0ms
  express:router <anonymous>  : /-/static/main.54a8238b472a2df05ec1.js +0ms
  express:router router  : /-/static/main.54a8238b472a2df05ec1.js +1ms
  express:router dispatching GET /-/static/main.54a8238b472a2df05ec1.js +0ms
  express:router <anonymous>  : /-/static/main.54a8238b472a2df05ec1.js +0ms
  express:router securityIframe  : /-/static/main.54a8238b472a2df05ec1.js +1ms
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/style.8410f14de46
7c42d2f6c14c7df197f3f.css', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/main.54a8238b472a
2df05ec1.js', bytes: 0/0
  express:router dispatching GET /-/verdaccio/logo +220ms
  express:router query  : /-/verdaccio/logo +1ms
  express:router expressInit  : /-/verdaccio/logo +0ms
  express:router corsMiddleware  : /-/verdaccio/logo +0ms
  express:router <anonymous>  : /-/verdaccio/logo +1ms
  express:router error_reporting_middleware  : /-/verdaccio/logo +0ms
  express:router <anonymous>  : /-/verdaccio/logo +0ms
  express:router <anonymous>  : /-/verdaccio/logo +1ms
  express:router compression  : /-/verdaccio/logo +0ms
  express:router router  : /-/verdaccio/logo +0ms
  express:router dispatching GET /-/verdaccio/logo +0ms
  express:router <anonymous>  : /-/verdaccio/logo +1ms
  express:router jsonParser  : /-/verdaccio/logo +0ms
  express:router <anonymous>  : /-/verdaccio/logo +0ms
  express:router <anonymous>  : /-/verdaccio/logo +1ms
  express:router router  : /-/verdaccio/logo +0ms
  express:router dispatching GET /-/verdaccio/logo +0ms
  express:router <anonymous>  : /-/verdaccio/logo +1ms
  express:router securityIframe  : /-/verdaccio/logo +0ms
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/verdaccio/logo', bytes:
0/0
  express:router dispatching GET /-/verdaccio/packages +5ms
  express:router query  : /-/verdaccio/packages +0ms
  express:router expressInit  : /-/verdaccio/packages +0ms
  express:router corsMiddleware  : /-/verdaccio/packages +1ms
  express:router <anonymous>  : /-/verdaccio/packages +0ms
  express:router error_reporting_middleware  : /-/verdaccio/packages +1ms
  express:router <anonymous>  : /-/verdaccio/packages +0ms
  express:router <anonymous>  : /-/verdaccio/packages +0ms
  express:router compression  : /-/verdaccio/packages +1ms
  express:router router  : /-/verdaccio/packages +0ms
  express:router dispatching GET /-/verdaccio/packages +0ms
  express:router <anonymous>  : /-/verdaccio/packages +1ms
  express:router jsonParser  : /-/verdaccio/packages +0ms
  express:router <anonymous>  : /-/verdaccio/packages +0ms
  express:router <anonymous>  : /-/verdaccio/packages +1ms
  express:router router  : /-/verdaccio/packages +0ms
  express:router dispatching GET /-/verdaccio/packages +0ms
  express:router <anonymous>  : /-/verdaccio/packages +1ms
  express:router securityIframe  : /-/verdaccio/packages +0ms
  express:router trim prefix (/-/verdaccio) from url /-/verdaccio/packages +0ms
  express:router router /-/verdaccio : /-/verdaccio/packages +1ms
  express:router dispatching GET /packages +0ms
  express:router urlencodedParser  : /-/verdaccio/packages +0ms
  express:router <anonymous>  : /-/verdaccio/packages +1ms
  express:router securityIframe  : /-/verdaccio/packages +0ms
  express:router <anonymous>  : /-/verdaccio/packages +2ms
  express:router <anonymous>  : /-/verdaccio/packages +0ms
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/verdaccio/packages', byt
es: 0/0
  express:router dispatching GET /-/static/logo.png +5ms
  express:router query  : /-/static/logo.png +1ms
  express:router expressInit  : /-/static/logo.png +0ms
  express:router corsMiddleware  : /-/static/logo.png +0ms
  express:router <anonymous>  : /-/static/logo.png +0ms
  express:router error_reporting_middleware  : /-/static/logo.png +1ms
  express:router <anonymous>  : /-/static/logo.png +0ms
  express:router <anonymous>  : /-/static/logo.png +0ms
  express:router compression  : /-/static/logo.png +1ms
  express:router router  : /-/static/logo.png +0ms
  express:router dispatching GET /-/static/logo.png +0ms
  express:router <anonymous>  : /-/static/logo.png +1ms
  express:router jsonParser  : /-/static/logo.png +0ms
  express:router <anonymous>  : /-/static/logo.png +0ms
  express:router <anonymous>  : /-/static/logo.png +1ms
  express:router router  : /-/static/logo.png +0ms
  express:router dispatching GET /-/static/logo.png +0ms
  express:router <anonymous>  : /-/static/logo.png +1ms
  express:router securityIframe  : /-/static/logo.png +0ms
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /-/static/logo.png', bytes:
 0/25736

**Comment by juanpicado** [comment]
I'll debug later, I'll let you know @aminechir

**Comment by juanpicado** [comment]
It works for me as well.

**Comment by aminechir** [comment]
Ok. Do you think the proxy could involve a problem ?

**Comment by juanpicado** [comment]
First, How your environment looks like ?

**Comment by aminechir** [comment]
All my env is described in my first response. 

Windows 7 + npm 5.8.0 + verdaccio 2.7.4


I launch the server with **verdaccio**
When i try the command **npm adduser --registry http://localhost:4873/**

I get this error message

`npm ERR! code E503
npm ERR! Registry returned 503 for POST on http://localhost:4873/-/v1/login`

**Comment by juanpicado** [comment]
Yeah, I read that, but, you are mentioning a proxy ... are you behind a proxy ?

**Comment by aminechir** [comment]
Yes i used the command 

npm config set proxy <my proxy adress>:<my port>
npm config set http-proxy <my proxy adress>:<my port>
npm config set https-proxy <my proxy adress>:<my port>

**Comment by juanpicado** [comment]
Still , works for me using `npm 5.8.0` and `verdaccio@2.7.4`
```
➜ npm adduser --registry http://localhost:4873/
Username: test
Password: 
Email: (this IS public) dsadsa@test.com
Logged in as test on http://localhost:4873/.
```
verdaccio log server

```
➜ verdaccio
 warn --- config file  - /Users/juan.c/.config/verdaccio/config.yaml
 warn --- http address - http://localhost:4873/ - verdaccio/2.7.4
 http <-- 404, user: undefined(127.0.0.1), req: 'POST /-/v1/login', bytes: 38/150
 http <-- 409, user: undefined(127.0.0.1), req: 'PUT /-/user/org.couchdb.user:jpicado', error: this user already exists
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /-/user/org.couchdb.user:jpicado?write=true', bytes: 0/53
 http <-- 409, user: undefined(127.0.0.1), req: 'PUT /-/user/org.couchdb.user:jpicado/-rev/undefined', error: this user already exists
 http <-- 409, user: undefined(127.0.0.1), req: 'PUT /-/user/org.couchdb.user:jpicado', error: this user already exists
 http <-- 404, user: undefined(127.0.0.1), req: 'POST /-/v1/login', bytes: 38/150
 http <-- 201, user: test(127.0.0.1), req: 'PUT /-/user/org.couchdb.user:test', bytes: 122/73
```

Please, increase log on verdaccio http://www.verdaccio.org/docs/en/logger.html and share the outcome.

**Comment by aminechir** [comment]
When I run the server, the following logs appear: 

`{"name":"verdaccio","hostname":"ACSLRD16216","pid":11208,"level":30,"content":"htpasswd","msg":"Plugin successfully loaded: @{content}","time":"2018-04-10T08:04:23.056Z","v":0}
{"name":"verdaccio","hostname":"ACSLRD16216","pid":11208,"level":40,"addr":"http://localhost:4873/","version":"verdaccio/2.7.4","msg":"http address - @{addr} - @{version}","time":"2018-04-10T08:04:23.146Z","v":0}
`


When i run the command npm adduser --registry http://localhost:4873/ ,

nothing happens to the server, the log is still the same and the output on the server console is still:

` warn --- config file  - C:\Users\a0h72255\AppData\Roaming\verdaccio\config.yaml

 warn --- http address - http://localhost:4873/ - verdaccio/2.7.4
`


However, when i go to http://localhost:4873/#/ , I see the stdout of the server changing into:

` http <-- 304, user: undefined(127.0.0.1), req: 'GET /', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/style.8410f14de46
7c42d2f6c14c7df197f3f.css', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/main.54a8238b472a
2df05ec1.js', bytes: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/verdaccio/logo', bytes:
0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/verdaccio/packages', byt
es: 0/0
 http <-- 304, user: undefined(127.0.0.1), req: 'GET /-/static/logo.png', bytes:
 0/0`


and the log is updated to this file:

[verdaccio.log](https://github.com/verdaccio/verdaccio/files/1893670/verdaccio.log)

**Comment by juanpicado** [comment]
> nothing happens to the server, the log is still the same and the output on the server console is still:

So, clearly, you are not hitting verdaccio server with `npm`. It might be your npm configuration or something else in your env that you will need to check by yourself. Also, you might try with `yarn`.

 I'lll close this since is not a verdaccio issue.

**Comment by aminechir** [comment]
I tried something else:

I first run the command `npm config set registry http://localhost:4873/`
Then i run `npm adduser`

In this way, i get a response from the server : 

` http --> ERR, req: 'GET https://registry.npmjs.org/npm', error: connect ETIMEDO
UT xxxxxxxxxxxxxxxxxxx
 http <-- 404, user: undefined(127.0.0.1), req: 'GET /npm', error: no such packa
ge available
 http --> ERR, req: 'GET https://registry.npmjs.org/npm', error: connect ETIMEDO
UT xxxxxxxxxxxxxxxxxxx
 http <-- 404, user: undefined(127.0.0.1), req: 'GET /npm', error: no such packa
ge available
 warn --> host registry.npmjs.org is now offline
 http <-- 404, user: undefined(127.0.0.1), req: 'GET /npm', error: no such packa
ge available`



Is it okay to process like that ? Or will still have to use the official npm registry as npm config ?

**Comment by jachstet-sea** [comment]
connection timeouts usually mean that verdaccio is not using your proxy server to connect to the remote. Make you sure you set the environment variables "http_proxy", "https_proxy" and "no_proxy" correctly before starting verdaccio
