### ISSUE TITLE
_npmUser / author not showing up

### ISSUE THREAD

**Issue by kachkaev** [verdaccio/verdaccio#65]
There is a small problem about displaying author names in the web interface - they do not show up:

![empty author](https://cloud.githubusercontent.com/assets/608862/19085006/97c84082-8a60-11e6-821a-6bdb1639cf90.png)

The same issue in the original repo: https://github.com/rlidwka/sinopia/issues/173
A merged PR in another fork: https://github.com/fl4re/sinopia/pull/4

I checked the contents of my `storage/@supercompany/supermodule/package.json` and can confirm that `"_npmUser"` is an empty object for some reason. Running `npm whoami` on a machine I'm publishing from does return some username though. Publishing is only allowed from authenticated users, so I'm confident I'm logged in. I'm not sure if this is a problem with NPM or verdaccio and I'm also wondering if replacing `_npmUser` with `author` is a good idea. That field should in theory show the name of the publisher, not the package creator (these may be different).

What do you guys think of this?

**P.S.:** My npm version is 3.10.3.

**Comment by juanpicado** [comment]
It doesn't work in the published package at npm but form trunk the name appears, investigating ..

**Comment by sfandersen** [comment]
I have just installed verdaccio and I am seeing the same issue. ("By:" is blank). It would be very helpfull, if it was possible to see who published the package (I will rather see the name of the publisher then the name of the author).

**Comment by guyspronck** [comment]
Also adding to this, I can confirm what @kachkaev said as it's the same on my instance (running in docker). When you manually set the _npmUser however, it loads correctly. So seems like this is not getting set somehow.

**Comment by kachkaev** [comment]
@guyspronck I could not get a proper workaround to this and a couple of other issues with verdaccio and ended up using Sonata Nexus as a private NPM registry. It's also open-source and is available as a docker image.

**Comment by mikedevita** [comment]
👍  another here with the same problem...

**Comment by pranay06** [comment]
I tried to verify this on the latest version of verdaccio available on git and this bug still persists.

**Comment by juanpicado** [comment]
@pranay06  Please share a `npm info --registry http://xxx.xxx:4873/` of your package.

**Comment by pranay06** [comment]
@juanpicado my bad. It is working ! I have raised two new issues - https://github.com/verdaccio/verdaccio/issues/250
https://github.com/verdaccio/verdaccio/issues/249
Would be glad if you could help me in these.
Thanks
