### ISSUE TITLE
Using Docker

### ISSUE THREAD

**Issue by robbybooker** [verdaccio/verdaccio#653]
I hope that this is the place for Verdaccio queries. I'm having trouble working out what the convention is when using Docker. The verdaccio/verdaccio image works fine but I'm unable to use apk inside it (I get message `ERROR: Unable to lock database: Permission denied` etc) in order to install eg nano in order to edit the auto-created config.yaml, and if I copy in my own config.yaml (using the Dockerfile) then that file is overwritten when the container and verdaccio start up. So given those troubles I've tried to create my own Dockerfile and build up a working image. The Dockerfile I have is:
```FROM node
RUN yarn global add verdaccio
RUN yarn global add forever
COPY conf/. verdaccio/conf/.
CMD forever start `which verdaccio`
```

I'm using forever because that's what the docs suggest however the container doesn't stay up: Starting the container with **docker-compose up** results in:

```
Starting verdaccio_myverdaccio_1 ... done
Attaching to verdaccio_myverdaccio_1
myverdaccio_1  | warn:    --minUptime not set. Defaulting to: 1000ms
myverdaccio_1  | warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
myverdaccio_1  | info:    Forever processing file: /usr/local/bin/verdaccio
verdaccio_myverdaccio_1 exited with code 0
```
And so I don't seem to be able to get right creating my own container. So:

1. In general how can I use the verdaccio/verdaccio image in a live environment where I need to change the config (config.yaml)?
2. What am I doing wrong when trying to create my own container from my own Dockerfile?

Thanks!

**Comment by juanpicado** [comment]
Hi @robbybooker 

> In general how can I use the verdaccio/verdaccio image in a live environment where I need to change the config (config.yaml)?

Something like this?

http://www.verdaccio.org/docs/en/docker.html#running-verdaccio-using-docker

> What am I doing wrong when trying to create my own container from my own Dockerfile?

Have you seen https://github.com/verdaccio/docker-examples already?

**Comment by robbybooker** [comment]
Thanks Juan! I've been a bit snowed under with work this week but hopefully I can get back onto this next week :D
