### ISSUE TITLE
List all versions of a package in Web UI

### ISSUE THREAD

**Issue by mcmillhj-wta** [verdaccio/verdaccio#655]
### Question
Is there a way to see all published versions of a single package in the Web UI? Currently I can only see the latest version that was published in Verdaccio.

This is how versions appear on npmjs:

![screen shot 2018-04-12 at 10 17 11 am](https://user-images.githubusercontent.com/20663938/38683105-b2eb474e-3e3a-11e8-9115-4b9644635f99.png)

When making a GET request for my package, I can see all of the versions and the time that they were published. Is this just a feature that hasn't been added to the Web UI? If so I would be happy to make a PR for it. 

```
  "dist-tags": {
    "latest": "1.0.3"
  },
  "time": {
    "modified": "2018-04-12T14:07:10.070Z",
    "created": "2018-04-12T13:59:16.668Z",
    "1.0.1": "2018-04-12T13:59:16.668Z",
    "1.0.2": "2018-04-12T14:03:20.463Z",
    "1.0.21": "2018-04-12T14:06:30.840Z",
    "1.0.3": "2018-04-12T14:07:10.070Z"
  }
```

**Comment by mcmillhj-wta** [comment]
@juanpicado Is this something you all would want a hand with? I am happy to submit a PR.

**Comment by securedeveloper** [comment]
Hey @mcmillhj-wta If you already have prepared something for this please do so, else I'm gonna do it at my earliest.

**Comment by mcmillhj-wta** [comment]
So it looks like this is already done? 

When I build the docker image from the latest commit, I see a sidebar with version history:

![screen shot 2018-04-12 at 11 53 25 am](https://user-images.githubusercontent.com/20663938/38688883-32b3bf08-3e48-11e8-90e3-4167a7559e9f.png)

**Comment by juanpicado** [comment]
Were you testing on `v2`?

**Comment by mcmillhj-wta** [comment]
No, it looks like `master` points to `3.0.0-beta.6`

**Comment by juanpicado** [comment]
I meant, when before you reported the issue.

**Comment by mcmillhj-wta** [comment]
Oh sorry, yes I assume so. It was the latest Docker image when I pulled `verdaccio/verdaccio`

**Comment by mcmillhj-wta** [comment]
but as long as I can see the versions I am happy to pull either the beta or alpha channel.

**Comment by juanpicado** [comment]
All versions are currently not displayed, you are right, but I think @priscilawebdev and @ayusharma will have that on the mind with the development of the new UI #955
