### ISSUE TITLE
npm install babel-plugin-import --save Error

### ISSUE THREAD

**Issue by pk002** [verdaccio/verdaccio#661]
npm ERR! 404 not found:@babel/helper-module-imports@^7.0.0-beta.34

**Comment by juanpicado** [comment]
https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/issue_template.md

**Comment by jachstet-sea** [comment]
I've just had the same issue last week and was able to solve it today:
- Make sure you have the latest (2.x) version of verdaccio)
- Remove the affected package from the storage so it will be re-downloaded
- Retry :)

**Comment by juanpicado** [comment]
Works for me. Just follow @jachstet-sea recomendations and you are good. 

![screen shot 2018-04-25 at 8 26 45 am](https://user-images.githubusercontent.com/558752/39229293-70df46e8-4862-11e8-886d-4c4b3bde5e0d.png)
