### ISSUE TITLE
How to uninstall verdaccio

### ISSUE THREAD

**Issue by george-norris-salesforce** [verdaccio/verdaccio#668]
Ever since I installed this I've had nonstop problems with installing packages from NPM. 
Every request gets a `FetchError: request to http://localhost:4873/**`
I can't install or uninstall anything.
Even npm uninstall verdaccio fails. 
PLEASE help me delete this library! Thank you..

**Comment by juanpicado** [comment]
I replied you already in gitter, but, anyhow, for general information there I go. 

Uninstall verdaccio and set another registry are two different things.

This will set back the main registry as default
```
npm config set registry https://registry.npmjs.org/
```
and uninstall `verdaccio` you can do it as another node global package.

```
npm uninstall -g verdaccio
```
