### ISSUE TITLE
Don't require setting `storage` key in config when using a storage plugin

### ISSUE THREAD

**Issue by apexskier** [verdaccio/verdaccio#673]
Verdaccio currently requires setting the storage key (used to set a storage file system path) even when you're using a non-filesystem based storage plugin.

For example, this works, even though `./storage` isn't used.
```yaml
# necessary
storage: ./storage

store:
  s3-storage:
    bucket: bucket
```

Without `storage`, I get this:
```
▻ yarn start
yarn run v1.5.1
$ verdaccio --config config.yaml
 warn --- config file  - config.yaml
(node:14453) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: CONFIG: storage path not defined
```

I think the solution is simple as changing [this assertion](https://github.com/verdaccio/verdaccio/blob/b89559b25ea981dd3692201bc771b743e163a91e/src/lib/config.js#L94) to check for `store` first. However, I don't know exactly how plugins are loaded, so this might not be quite right. It also would be nice to remove `storage` entirely and replace it with `store` so there's a single config mechanism.

**Comment by juanpicado** [comment]
@apexskier that's one of the things still pending to fix. Thanks for the reminder.

**Comment by juanpicado** [comment]
One of the big problems removing things are the tests. Just to keep on mind.

**Comment by juanpicado** [comment]
According to the new design, if there is no storage plugin defined, we fallback to `local-storage`.  I think there is something called self_path, still, we need to clean up some part of the code to make it more scalable.
