### ISSUE TITLE
@开头的包安装404，如@babel/helper-module-imports和@babel/code-frame

### ISSUE THREAD

**Issue by pk002** [verdaccio/verdaccio#680]
解决方法，因为我在配置文件中设置了@开头的私包，需要在配置文件的中添加poxy

**Comment by juanpicado** [comment]
Unfortunately, I do not speak Chinese. Google Translate helps to understand more or less your point, but anyway, please try English.

**Comment by juanpicado** [comment]
@Meeeeow ping
