### ISSUE TITLE
favicon refers to .png while only .ico exists

### ISSUE THREAD

**Issue by clintwood** [verdaccio/verdaccio#681]
The [`src/webui/template/index.html`](https://github.com/verdaccio/verdaccio/blob/master/src/webui/template/index.html#L6) refers to `icon/png`, `favicon.png` whereas in `verdaccio/website/static/img/` only a `favicon.ico` exists and as such browsers give a 404 for favicon.

**Comment by lgaitan** [comment]
I'm open to fixing this.

@juanpicado 
Do you think the project is open to some changes in the web ui?

I think that we could match the verdaccio design on the web ui. (colors, buttons, etc)

![opera snapshot_2018-05-08_221617_localhost](https://user-images.githubusercontent.com/5970350/39790634-909e86a0-530d-11e8-8144-830a7b3d2326.png)

**Comment by juanpicado** [comment]
One of the reasons we introduced React was been able to scale, add new stuff and btw I think people will love #357 

About the logo in the header, I wonder how would looks like with https://github.com/verdaccio/verdaccio/blob/master/assets/bitmap/verdaccio-blackwhite.png

**Comment by lgaitan** [comment]
for me it feels like something is missing. what do you think?

![opera snapshot_2018-05-12_134511_localhost](https://user-images.githubusercontent.com/5970350/39959652-2979210c-55eb-11e8-8db9-c481e50f7762.png)

**Comment by juanpicado** [comment]
Yeah, you are right. Well, I'm not a designer, but I think the first option is taking a lot of space, maybe, should be a bit subtle. What do you think?
cc: @ayusharma

**Comment by lgaitan** [comment]
What about this one?

This way we can even insert the `title` on the header.

![opera snapshot_2018-05-12_140737_localhost](https://user-images.githubusercontent.com/5970350/39959816-e0a19786-55ed-11e8-8328-3b920bf83ca4.png)

**Comment by juanpicado** [comment]
About the tile ... something to keep on mind .. I live in Austria and all the time I see stuff like this `Donaudampfschiffahrtsgesellschaftskapitän` ... which means "Danube steamship company captain". 

I like the logo and the title. I'd like to have more opinions on this topic. I hope someone pop ups around here.

**Comment by juanpicado** [comment]
@lgaitan do you have plans to deliver theme soon? ... It'd be cool to release it on `v3`.

**Comment by juanpicado** [comment]
I was thinking in the new skin.  The custom theme I guess can wait.

**Comment by juanpicado** [comment]
I think we have invaded this ticket which is a completely different topic, sorry for that.

**Comment by juanpicado** [comment]
Fixed @clintwood next beta you will be able to see the icon
