### ISSUE TITLE
Change host address using docker 

### ISSUE THREAD

**Issue by copycatam** [verdaccio/verdaccio#682]
Hi,

TH's for the amazing work.    

I want to change the default host address to http://mydomain.com when I run verdaccio using docker. How can i do that?

**Comment by juanpicado** [comment]
Have you read https://www.verdaccio.org/docs/en/docker.html#docker-and-custom-port-configuration ?

**Comment by juanpicado** [comment]
Have you read https://www.verdaccio.org/docs/en/docker.html#running-verdaccio-using-docker ?

You can use an external config file.

https://github.com/verdaccio/docker-examples/tree/master/docker-local-storage-volume

**Comment by copycatam** [comment]
Thank's a lot,
   
      It's working now.
