### ISSUE TITLE
Support for npm audit

### ISSUE THREAD

**Issue by beeing** [verdaccio/verdaccio#689]
**Is your feature request related to a problem? Please describe.**
Just tried running `npm audit` command and it returns:

`Your configured registry (https://npm.mycompany.com/) does not support audit requests.`

Looking at the npm logs, it shows that npm sends a request to the following:

`http fetch POST 404 https://npm.mycompany.com/-/npm/v1/security/audits`

**Describe the solution you'd like**

To implement the security/audits API endpoint.

**Comment by juanpicado** [comment]
Maybe, as a middleware plugin ... https://www.verdaccio.org/docs/en/dev-plugins.html#middleware-plugin

**Comment by todojs** [comment]
@juanpicado it's a good solution. I'm working with a very stupid workaround:

`npm audit --registry https://registry.npmjs.org/`

Your solution is fine.

**Comment by juanpicado** [comment]
I created a basic scaffolding whether someone wants to fork and start to work on it. 

https://github.com/verdaccio/verdaccio-audit
https://www.npmjs.com/package/verdaccio-audit

**Comment by juanpicado** [comment]
Well. I just make it work. Publishing soon ...

**Comment by beeing** [comment]
Thanks, that's great!

**Comment by juanpicado** [comment]
Go and try :) It's available right now. It needs further testing. Check the PR.

**Comment by beeing** [comment]
@juanpicado is this published?

**Comment by juanpicado** [comment]
@beeing follow instructions here https://github.com/verdaccio/verdaccio/pull/704

The PR is just to make it built-in in a future beta. You can use it right away if you want globally.

**Comment by mufaawan** [comment]
If your project was initiated sometime back, remove yarn.lock, packag-lock.json and node modules. then run npm i. It should work. It worked in my case.
