### ISSUE TITLE
verdaccio 3.0.0-test.1 is seen as newer than 3.0.0-beta.10

### ISSUE THREAD

**Issue by edmorley** [verdaccio/verdaccio#699]
**Describe the bug**
The latest beta release of verdaccio is `3.0.0-beta.10`, however tools (such as `npm outdated` or Renovate) report `3.0.0-test.1` as the latest version due to the way the semver spec works.

**To Reproduce**
1. `npm install verdaccio@3.0.0-beta.9`
2. `npm outdated`

**Expected behavior**
The latest version is reported as `3.0.0-beta.10`.

**Actual behavior**
The latest version is reported as `3.0.0-test.1`, which is in fact older.

**Additional context**
This caused renovateapp/renovate#1988.

I think one solution would be to mark the `3.0.0-test.1` version as deprecated, such that tools ignore it:
https://docs.npmjs.com/cli/deprecate

Many thanks!

**Comment by juanpicado** [comment]
`3.0.0-test.1': '2018-02-17T08:12:52.899Z'` is just a self-reminder **what do I do not have to do with npm** . Thanks for the heads up 👍 


It's fixed already.
```
➜ npm outdated verdaccio                                      
Package          Current         Wanted  Latest  
verdaccio  3.0.0-beta.10  3.0.0-beta.10   2.7.4 
```

**Comment by edmorley** [comment]
Many thanks! :-)
