### ISSUE TITLE
Pages for cached npm packages

### ISSUE THREAD

**Issue by MKRhere** [verdaccio/verdaccio#706]
I'm currently using verdaccio because I have to be somewhere without internet for a few days. I've cached a lot of npm modules via verdaccio, and everything seems good, but I'd love to see pages generated for them on the localhost frontend like it appears on npmjs.com. This already happens when you publish from verdaccio, but I'd like to (optionally?) enable these pages for packages pulled from npm as well.

Oh, and well done! I love what you've been doing so far.

Thoughts on this?

**Comment by juanpicado** [comment]
> I'm currently using verdaccio because I have to be somewhere without internet for a few days. 

I needed to quote this 👍 

> but I'd love to see pages generated for them on the localhost frontend like it appears on npmjs.com

This is not possible right now, but, why not? I'd love it as well. I think would be a nice and loved PR.

> Oh, and well done! I love what you've been doing so far.

🙃😊

**Comment by MKRhere** [comment]
Aww, I would love to make a PR. I can't now, but I can't now. I'll keep an eye on it if I ever get time :smile:  If someone else can, it'd be a welcome addition! :smile:

**Comment by TheILPlace** [comment]
Hi, 
currently i am using verdaccio with several projects, in which there is NO internet connection at all.
i use verdaccio to cache the npm packages in an external network. zip the storage folder, move it into the disconnected network, and merge it with the existing storage folder.

as far as using verdaccio to install the npm packages in the disconnected env. - perfect.
the main problem - you cannot search for a package using the webpage !

this looks like a trivial query - check what is in the cache.
is this not a simple task to accomplish ?

**Comment by nanchen** [comment]
Starting verdaccio will generate a file called ".sinopia-db.json"  under storage folder, adding package names to "list" array will do the trick to show the cached packages. Though I don't know if it's recommended.

my file content: 
{"list":["blob"],"secret":"1adfa7e39bd3fc88c4106fbe6808620de6361237e920edce77c45a71e928639c"}

So package 'blob' is shown in my web page:
![image](https://user-images.githubusercontent.com/557324/48593556-254fe700-e902-11e8-9c77-e63e564a493f.png)

**Comment by juanpicado** [comment]
Once https://github.com/verdaccio/verdaccio/pull/1126 is merged, we can experiment easily to solve this.

**Comment by juanpicado** [comment]
Currently, as a first step, I'm adding required logic to the `local-storage` for retrieving all packages from storage + private ones.  Once that's done let's see how is the performance with huge storages. In any case, this will be optional and enabled by config demand. I haven't chosen any possible config name but I'd love to listen to proposals.

**Comment by MKRhere** [comment]
When does the retrieving happen? On starting the server? Once the server has started it can persist when fetching new packages and if a package was deleted from fs, and the page was navigated to, you can say package was deleted and go to previous page and remove from storage. How is it handled with private packages though? 🤔

**Comment by chauthai** [comment]
Do you still help for this issue? I've just found your project and I want to help out.

**Comment by juanpicado** [comment]
@chauthai yes, I was working on this, the current status is the following 

- https://github.com/verdaccio/local-storage must be modified in order to be able to fetch all packages, this is a design change, not that trivial that might affect other plugins.
- Once that is solved, we need to modify verdaccio Storage and LocalStorage handlers. 

If you want more insights about this. Feel free join our chat (discord).

**Comment by artemdudkin** [comment]
pls look at 
https://github.com/verdaccio/local-storage/pull/164
https://github.com/verdaccio/verdaccio/pull/1281
https://github.com/verdaccio/ui/pull/35

<img width="589" alt="verdaccio-pr" src="https://user-images.githubusercontent.com/8177502/56594611-d5cebf00-65f5-11e9-9abe-299ee11d9cd3.png">

**Comment by g3ngar** [comment]
Perhaps you might like [verdaccio-offline-storage](https://www.npmjs.com/package/verdaccio-offline-storage): it lists all the locally available packages in the web ui AND rewrites on-the-fly the packages definitions so only locally available versions are recognized. Hope it helps.

**Comment by juanpicado** [comment]
> Perhaps you might like [verdaccio-offline-storage](https://www.npmjs.com/package/verdaccio-offline-storage): it lists all the locally available packages in the web ui AND rewrites on-the-fly the packages definitions so only locally available versions are recognized. Also, it's compatible with the default local-storage plugin, so the registry won't get broken. Hope it helps.

Excellent move 👏

**Comment by g3ngar** [comment]
> Excellent move 👏

Thanks!
