### ISSUE TITLE
Unexpected token { in verdaccio beta

### ISSUE THREAD

**Issue by brennerm** [verdaccio/verdaccio#718]
**Describe the bug**
Executing the verdaccio beta executable results in an syntax error. This seems to be an issue with my Node version. Executing the same commands with version 10.2.1 works perfectly fine. I'd propose to add a hint in the README that points to the supported Node versions.

**To Reproduce**
1. `npm install verdaccio@beta`
2. `node node_modules/verdaccio/bin/verdaccio --version`
```
/root/verdaccio-beta/node_modules/verdaccio/build/lib/up-storage.js:274
    const { auth } = this.config;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/verdaccio-beta/node_modules/verdaccio/build/lib/storage.js:23:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Expected behavior**
I'm expecting to get the version information.

**Debugging output**
 ```
$ node --version
v4.2.6
```

**Comment by lgaitan** [comment]
Hello @brennerm,

Unfortunately this project minimum requirement for node is `v6.12.0`.
Node 4.x is already End of Life and is no longer supported.

Please upgrade your node version, and this error will be gone.

**Comment by lgaitan** [comment]
Hello @brennerm,


Yes, node 4 is no longer supported on `@beta`.
If you need to use an old version of node you can still try verdaccio 2.x (doesn't get new features)

According to Node [(more info)](https://medium.com/the-node-js-collection/april-2018-release-updates-from-the-node-js-project-71687e1f7742) 

>  4.x release line is going end of life April 30th

> The 6.x release line is moving into maintenance mode April 30th

So you really should upgrade your version of node

The docs installation guide covers this topic
[Installation · Verdaccio](https://www.verdaccio.org/docs/en/installation.html)

**Comment by brennerm** [comment]
Thanks for clarification. Btw can you give an estimate on when 3.0 will be released?

**Comment by juanpicado** [comment]
The next weekend will be available already. I'm working on update README and some blog articles.
