### ISSUE TITLE
How to invalidate user auth token on the server?

### ISSUE THREAD

**Issue by okv** [verdaccio/verdaccio#724]
#### My reason:
I need to prohibit access to the repository for the user that already got auth token.

#### Steps to reproduce:
1) Add user to config file
2) Login via npm using user credentials
3) Remove user from config file

After that user is not at config file but got access because he already have token.
Is there some way to invalidate token for the user on the server side?

**Comment by lgaitan** [comment]
I'd have to check, but it think that when you change the users password its token will become invalid

**Comment by okv** [comment]
I tried that with verdaccio 2.6.6 and after changing password at config user still logged in.

**Comment by juanpicado** [comment]
@okv there is no way (API, no UI) to change password yet.  https://github.com/verdaccio/verdaccio/issues/401 PR-Welcome

**Comment by juanpicado** [comment]
@okv I'll close this one, please follow up on #168
