### ISSUE TITLE
[Bug] What are verdaccio requirements? verdaccio and verdaccio-ldap can't support a CI process

### ISSUE THREAD

**Issue by kopax** [verdaccio/verdaccio#730]
I have a `verdaccio@2.7.4` and `verdaccio-ldap@2.0.0` in `http`, and a nginx a `https` ssl proxy in front.

We have GItLab CI runner that are doing `npm install --registry https://our.registry.com`

Verdaccio talk to openldap in the background for the user account.

We try to build and our  CI (which have the verdaccio and ldap  server in the local) keep failing and the verdaccio server is restarting.

I don't know why but it do login to ldap **many times** during the installation process.

```js
http <-- 200, user: me(172.18.0.1 via 172.16.14.10), req: 'GET /node-int64', bytes: 0/2481
 http --> 304, req: 'GET https://registry.npmjs.org/multicast-dns-service-types' (streaming)
 http --> 304, req: 'GET https://registry.npmjs.org/multicast-dns-service-types', bytes: 0/0
 debug--- connected after 1 attempt(s)
 debug--- connected after 1 attempt(s)
 debug--- connected after 1 attempt(s)
 debug--- failed to connect after 1 attempts
 fatal--- uncaught exception, please report this
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1092:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Is there a way to prevent such bug ? 
Ldap and verdaccio are in the same intranet as the CI, but all the module that get proxied from npmjs make a tons of request and I supposed there is a minimum requirement?

What are the requirement ? We use 2GB of ram, and 1 Core CPU.

**Comment by juanpicado** [comment]
`verdaccio-ldap` has their own repository, I suggest ask there.

**Comment by kopax** [comment]
@juanpicado , is `verdaccio-ldap` the issue here ? 
I presume it's the way the authentication work. Why do we need to authenticate between each request ?
What are the recommended resources ?
