### ISSUE TITLE
How to load balance with consul and HA proxy?

### ISSUE THREAD

**Issue by kopax** [verdaccio/verdaccio#731]
We are experiencing issues with verdaccio and we want to load balance a few instance to get through.

We use verdaccio behind a https public reverse proxy nginx.

We want to use many verdaccio instance behind HA proxy then the nginx ssl.

Did anyone ever made a good configuration for verdaccio using HA proxy load balancing (TCP or HTTP) ?

**Comment by kopax** [comment]
Solve by using `proxy_set_header Host $upstream`

**Comment by juanpicado** [comment]
You should document it in `docs` folder `proxy` section. PR-welcome

**Comment by kopax** [comment]
@juanpicado It is already documented:

```md
For this case, `url_prefix` should NOT set in verdaccio config
````

If you set it, then you should use the upstream. I wonder if `$http:$server_port` produce the same result.
