### ISSUE TITLE
get publisher name for webhook

### ISSUE THREAD

**Issue by ilyaztsv** [verdaccio/verdaccio#739]
**Is your feature request related to a problem? Please describe.**
As described in the docs, we can use `{{ name }}` and `{{ dist-tags.latest }}` in notification message.
I didn't find an option which allows to use name of user which published package.

**Describe the solution you'd like**
Add `{{ publisher-name }}` option which will be contain the name or email of the user (if the user is authorized) which published package.

**Comment by juanpicado** [comment]
Mmm .. so you want to know who is publishing the package? or the package author?

**Comment by ilyaztsv** [comment]
> Mmm .. so you want to know who is publishing the package? or the package author?

Thank for the reply.

It will be perfect to know the package author and who published the package at the same time.

**Comment by juanpicado** [comment]
@ilyaztsv I'll dive into the code, but I think is not possible yet. Verdaccio injects only the package metadata, so, the unique information you can access is the one is on `package.json` file in your storage for each package.

**Comment by ilyaztsv** [comment]
Thanks!

I'll try the approach above. About `publisher data`, I'll try to send a PR when I have a time.
