### ISSUE TITLE
Yarn authentication not working

### ISSUE THREAD

**Issue by ameesme** [verdaccio/verdaccio#74]
Hi. We've been running Sinopia for a while and recently switched to Verdaccio as a private registry.

I looked into Yarn, but didn't get this to work with Verdaccio. Yarn's authentication flow is as follows:
- `yarn login`
- Enter username and email
- `yarn install`
- Enter password if needed
- Authenticated

However, this method of authentication does not seem to work. The following error is thrown:
`Error: https://*.*/isomorphic-fetch: unregistered users are not allowed to access package isomorphic-fetch`

I'm not sure whether this is an issue with Yarn or Verdaccio. Do any of you have experiences with using the combination of the two?

**Comment by Nicholaiii** [comment]
Yarn is a completely different beast than NPM. While I would like to use this approach as well, I think it's a lot more work than simply just doing it.

**Comment by qballer** [comment]
Can we have a yarn connector for verdaccio? 
It's a PR and development, I know. Yarn is just so much faster.

**Comment by ameesme** [comment]
I am interested in contributing to resolve this issue. Are there any guidelines available?

**Comment by qballer** [comment]
@ameesme can I help, I also would like yarn to work well with sinopia. Testing it as we speak.

**Comment by jonaskello** [comment]
According to [this PR](https://github.com/yarnpkg/yarn/pull/839) and [this PR](https://github.com/yarnpkg/yarn/pull/1666) yarn should work with scoped packages on private repositories the same way npm does (with autentication information in .npmrc). However I just tested the nightly build of yarn (0.18.0-20161127.0346) and it does not work. I get the same error as in the first comment. I guess this is a problem with yarn rather than verdaccio.

**Comment by jonaskello** [comment]
I started to monitor things with tcpdump to see what was going wrong, and suddenly it just stared working. So now the [nightly build](https://yarnpkg.com/en/docs/nightly) of yarn (0.18.0-20161127.0346) is working and installing packages from verdaccio for me :-).

**Comment by jonaskello** [comment]
Seems it only works if you have prefixed the registry with a scope in .npmrc. Like this:

```
@foo:registry=https://my.reg.com/
```

If I omit the `@foo:` part it gives the same error as in the first comment (`unregistered users are not allowed to access package`).

**Comment by agrcrobles** [comment]
Thanks @jonaskello prefixing fixes it!

**Comment by zifeo** [comment]
Is this still working with latest yarn? I'm currently facing:
```shell
verdaccio_1  |  http  --> 404, req: 'GET https://registry.npmjs.org/@scope%2Fpackage', bytes: 0/21
verdaccio_1  |  http  <-- 200, user: test, req: 'GET /@scope%2fpackage', bytes: 0/1145
verdaccio_1  |  http  <-- 403, user: undefined, req: 'GET /@scope%2fpackage/-/package-0.1.2.tgz', error: unregistered users are not allowed to access package @scope/package
```
Fetching the archive does not seem to be done as registered user.

**Comment by ameesme** [comment]
You seem to have a different issue. The first request is a 404, so I assume that the module does not exist. `@scope/package` seems like a weird name for a package.

**Comment by zifeo** [comment]
@ameesme NPM works fine on this case. Is this the regular way of using scoped packages?

**Comment by ameesme** [comment]
@zifeo 
`http  --> 404, req: 'GET https://registry.npmjs.org/@scope%2Fpackage', bytes: 0/21`

Unless NPM messed up their status-codes, that package does not exist (otherwise it should probably be a 403). If I'm correct, scoped packages are often private and use the `@username/`-prefix and I assume `scope` isn't the username  you're looking for.

**Comment by zifeo** [comment]
@ameesme Yes, the scoped package is on Verdaccio's side. Shall I open another issue for it even though the issue seems to be the yarn authentification?

**Comment by ahmadsholehin** [comment]
@zifeo Sorry for resurrecting. Did you manage to solve the issue you faced?
I faced similar issue in which fetching the archive is not done as a registered user.

```
http <-- 200, user: mudd(192.168.1.1 via 172.17.0.1), req: 'GET /@datavis%2ftransformer', bytes: 0/798
http <-- 403, user: undefined(192.168.1.1 via 172.17.0.1), req: 'GET /@datavis%2ftransformer/-/transformer-0.0.1.tgz', error: unregistered users are not allowed to access package @datavis/transformer
```

I'm using sinopia-gitlab-heres for auth.
