### ISSUE TITLE
verdaccio/verdaccio not being listed in github search result when searching for verdaccio.

### ISSUE THREAD

**Issue by feluxe** [verdaccio/verdaccio#75]
I just noticed if I search github for 'verdaccio' it does not return verdaccio/verdaccio.

The only repositories it show me are:
- Global-Solutions/docker-verdaccio
- coldrye-docker/coldrye-debian-verdaccio

I wonder why that is and just wanted to mention it.

**Comment by eephillip** [comment]
I just ran into that as well. Instead of listing under Repositories, it lists under users when searching within github.

**Comment by developit** [comment]
FYI this is because github does not perform search on forks (ever). Likely no way around this other then recreating the repo as a non-fork of sinopia.

**Comment by juanpicado** [comment]
@trentearl ping

**Comment by jmwilkinson** [comment]
Do we have a possible solution for this? Or do we simply close it?

**Comment by juanpicado** [comment]
@jmwilkinson If you are agreed with @developit I think is pretty clear. You decide. In my case I would do it.

**Comment by jmwilkinson** [comment]
@juanpicado The problem I have with removing it as a fork is that it will no longer show up for people who are looking for an (at least somewhat) active fork of sinopia. We still have quite a few people finding verdaccio through the old sinopia project.

**Comment by feluxe** [comment]
Someone could create a repo named verdaccio which has something link this in README.md:

> ### The verdaccio-project repository, can be found here:
> < add a link to this repo here >

This repo would pop up in github-search and redirect people to the main repo until it is removed as a fork.

**Comment by juanpicado** [comment]
@feluxe  I'd have to eliminate this repository and recreating it again losing issues, starts, wiki and so on. I'm agree with @jmwilkinson

**Comment by juanpicado** [comment]
Some freedom finally !! `verdaccio` 🥇 is not a fork anymore . Thanks Github.
