### ISSUE TITLE
Capitalise name of logged in user in header

### ISSUE THREAD

**Issue by ayusharma** [verdaccio/verdaccio#752]
**Is your feature request related to a problem? Please describe.**
currently, the name is in lowercase. 

**Describe the solution you'd like**
The name can be capitalised. eg. `Ayush Sharma`

**Describe alternatives you've considered**
Not required. 
<img width="501" alt="screen shot 2018-06-12 at 19 37 00" src="https://user-images.githubusercontent.com/6918450/41306934-04e69932-6e78-11e8-8ff5-bb5a04f246f1.png">

**Additional context**
Not required.

**Comment by cgomezmendez** [comment]
I'll take this one if is not already taken :)

**Comment by juanpicado** [comment]
All yours , go ahead :-)

**Comment by juanpicado** [comment]
@ayusharma @priscilawebdev I think you both worked on the same ticket. Sorry about that. @ayusharma PR was merge early this week  :(

**Comment by priscilawebdev** [comment]
It was still open, so I took it..but fine :)

**Comment by juanpicado** [comment]
Thanks for your effort @priscilawebdev

**Comment by ayusharma** [comment]
@priscilawebdev Sorry for the misunderstanding.  :(
