### ISSUE TITLE
Broken links when using reverse proxy with prefix

### ISSUE THREAD

**Issue by kenske** [verdaccio/verdaccio#753]
**Describe the bug**
When connecting to verdaccio through a reverse proxy with a prefix, links break.

**To Reproduce**
1. Clone the examples repo: https://github.com/verdaccio/docker-examples
2. Modify the nginx config to include a prefix in the location, as specified in the [documentation](https://github.com/verdaccio/verdaccio/blob/master/docs/reverse-proxy.md) (look for "sub-directory installation"):
```
  location ~ ^/node/(.*)$ {
    resolver 127.0.0.11;
    proxy_pass http://verdaccio:4873/$1;
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_redirect off;
  }
```

2. Run docker-compose up
3. Open browser
4. Get blank page

**Expected behavior**
The landing page should load, just like it does when using verdaccio 2.x.

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio:3

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```
url_prefix: /node/
```

**Additional context**
This same scenario works perfectly when using verdaccio 2.x.

**Comment by broekema41** [comment]
I ran into this problem while updating our verdaccio server that is running behind a reverse proxy.
Not sure if the webpack config is the correct location to fix the problem but it worked for me.
see pull request https://github.com/verdaccio/verdaccio/pull/755 for details.

kind regards,

**Comment by juanpicado** [comment]
It will be released asap.

**Comment by juanpicado** [comment]
`verdaccio@3.2.0`
