### ISSUE TITLE
Web UI not listing packages because of 'time' property unavailability in package.json in storage dir

### ISSUE THREAD

**Issue by kumarvi** [verdaccio/verdaccio#758]
**Describe the bug**

We're trying to migrate from sinopia to verdaccio for our internal npm registry, and noticed that the internal packages that were published using our existing setup (using sinopia) aren't showing up in the Web UI with the latest verdaccio (version: 3.1.2), even though we're able to install them. This is happening because of the some of the packages that were published earlier seem to be missing the `time` property in the package.json

**To Reproduce**

Ensure a module is already published once to verdaccio. Remove the `time` member from the package.json inside the storage directory. Then try to load the Web UI home page.

Results:
 * The published package doesn't show up in the Web UI
 * The below exception shows up in the `verdaccio.log` during server start-up
```

TypeError: Cannot read property '2.1.0' of undefined
 at ../node_modules-v8/lib/node_modules/verdaccio/build/lib/storage.js:389:37
 at storage.readPackage (../node_modules-v8/lib/node_modules/verdaccio/build/lib/local-storage.js:616:7)
 at ../node_modules-v8/lib/node_modules/verdaccio/node_modules/@verdaccio/local-storage/lib/local-fs.js:167:9
 at <anonymous>
```

**Additional context**
There has to be a `isNil` check for the `time` property in https://github.com/verdaccio/verdaccio/blob/master/src/lib/storage.js#L374, similar to the fix done in https://github.com/verdaccio/verdaccio/commit/e977d50c8a1b005acf81bf3b2bc5d71e0c6d2755 to support backward compatibility.

**Comment by juanpicado** [comment]
Please try with `verdaccio@3.2.0`

**Comment by kumarvi** [comment]
Verified, thank you! @juanpicado 

One related minor UI (alignment) issue in the home page I noticed when there are packages with/without the `time` details in their package.json, attaching the screenshot below:

![image](https://user-images.githubusercontent.com/6780628/41450928-f8c64406-7087-11e8-8a00-9c3b1261bd69.png)

**Comment by kumarvi** [comment]
The license div is not right aligned, for the older packages, because of the missing time info div on the left side.

**Comment by juanpicado** [comment]
Ohh !! I must be blind. I'll create a ticket. Thanks 👍

**Comment by ayusharma** [comment]
@kumarvi @juanpicado I am creating a separate issue for this. 🥇

**Comment by ayusharma** [comment]
@kumarvi I confirm the License alignment issue. It will be solved soon. Thanks 😀

Ref #761
