### ISSUE TITLE
Disable 'adduser'.

### ISSUE THREAD

**Issue by feluxe** [verdaccio/verdaccio#76]
I run the verdaccio docker image on a remote server and it works fine so far. I blocked public accessibility with this setting:

	auth:
	  htpasswd:
	    file: /verdaccio/conf/htpasswd
	packages:
	  '@*/*':
	    access: $authenticated
	    publish: $authenticated

	  '*':
	    access: $authenticated
	    publish: $authenticated

This prevents anyone from uploading/downloading packages without being logged in.

There is just one thing: Anyone can still create a new account on the server by running: `npm adduser --registry http://ip_addr:port` and login.

I tried to put a `chmod 400` on `/verdaccio/conf/htpasswd` to prevent write access but it did not help.

Does anyone know what I could do to prevent anyone from creating new accounts and login?

**Comment by petrutoader** [comment]
```
# Maximum amount of users allowed to register, defaults to "+inf".
# You can set this to -1 to disable registration.
max_users: -1
```

**Comment by feluxe** [comment]
This solved the problem. Must have overlooked it...
Thanks! :)
