### ISSUE TITLE
Implement Web UI support for changing user's password

### ISSUE THREAD

**Issue by ahoracek** [verdaccio/verdaccio#766]
**Is your feature request related to a problem? Please describe.**
Verdaccio currently missing support for changing password via Verdaccio site

**Describe the solution you'd like**
Create web API for changing user password
Create components and UI implementation to consume change password web API

**Describe alternatives you've considered**
Alternatively you can use plugin, however built in support for npm profile api can serve as basic for profile/role management

**Comment by juanpicado** [comment]
Dupe https://github.com/verdaccio/verdaccio/issues/401

**Comment by ahoracek** [comment]
Should I close it and implement PR based on #401 as we discussed there? That was intended to cover points 4 and 5 of the list you suggested.

**Comment by juanpicado** [comment]
Ok, let's keep it, I'll rename the other one as kinda of "EPIC" ...

**Comment by juanpicado** [comment]
@ahoracek Are you going to work on the whole implementation?

**Comment by ahoracek** [comment]
yes, that was my plan, create 3 PRs, api, web and htpasswd

**Comment by juanpicado** [comment]
Ok :-) Perfect.

**Comment by juanpicado** [comment]
Dupe #401
