### ISSUE TITLE
How to use the static resource path after npm publish in readme.md

### ISSUE THREAD

**Issue by lovewinders** [verdaccio/verdaccio#775]
### step1:config:package.json
```
             "files": [
                "dist",
                "public"
             ]
```
### step2:resource path
```
             -dist
                  -index.js
             -public
                  -images
                       -preview.png
             -README.md
             -package.json
```
## Preview
      ![images path](public/images/preview.png)  -----> (question:how to write static resource??? thank you)
### step5:web:server
      image:url:http://ip/#/detail/@packagename/public/images/preview.png is not find static resource

**Comment by lgaitan** [comment]
Hi @lovewinders,

Unfortunately this is not possible, by default when you publish a package, yarn | npm will compress the 
entire project and publish it to the registry.

The only file registries access from your package is README.md

If you want to set an image on your own README, you'll need to host the image on a separate domain.

Take a look at verdaccio own's README for an example

**Comment by juanpicado** [comment]
I agree with @lgaitan . Closing this one.

**Comment by lovewinders** [comment]
thank you！
