### ISSUE TITLE
Package Version Limit

### ISSUE THREAD

**Issue by danbrianwhite** [verdaccio/verdaccio#779]
**Is your feature request related to a problem? Please describe.**
When building dev and production environments, I'm always frustrated by the NPM versioning process breaking builds. When a dependency's dependency updates because of a fuzzy version and breaks my application, it can become problematic to debug or even identify the issue.

**Describe the solution you'd like**
I would like a way to limit installing updated packages. I would like to have an admin install/pull the base package and Verdaccio pull all dependencies. Then I would like to limit dev users to only installing the package versions found on Verdaccio based on the admin's install. Alternatively, I would like to set specific dependency version limits within Verdaccio's web UI. 

**Describe alternatives you've considered**
Alternatively, I would like to set a list in Verdaccio's UI of packages and versions that are allowed to be downloaded via a json object similar to a package.json or lock file.

**Comment by danbrianwhite** [comment]
If there are any suggestions on how or where something like version limiting could be added other than in just the config please point me in the direction so I can take a look at the code and see what can be done.

Since I'm not as familiar with Verdaccio, is there currently way to add a plugin that would allow me to achieve this?

**Comment by danbrianwhite** [comment]
Would a custom middleware plugin allow me to limit this? Sounds like I can possibly restrict api calls based on version.

**Comment by ayusharma** [comment]
Hi @danbrianwhite,

Thanks for asking a question. I am not getting a clear picture of your requirements but as far as I understand: 

> I'm always frustrated by the NPM versioning process breaking builds. When a dependency's dependency updates because of a fuzzy version and breaks my application

I think as a maintainer you have to define/publish versions very carefully. You can keep the fix versions in that case.  https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-consumers

>  Alternatively, I would like to set specific dependency version limits within Verdaccio's web UI.

I think it is not the objective of npm registry, You publish some packages it serves them. Limiting them is another kind of thing.  It will require to develop a new project here. 

> Since I'm not as familiar with Verdaccio, is there currently way to add a plugin that would allow me to achieve this?

We have some plugins. You can find more here https://www.verdaccio.org/docs/en/dev-plugins 

> Would a custom middleware plugin allow me to limit this? Sounds like I can possibly restrict api calls based on version.
We have middleware functionality but It is not applicable here.

Please feel free to ask or discuss your issue in more depth.

**Comment by ayusharma** [comment]
Please feel free to open the issue again if you have any questions. I am closing this as of now.
