### ISSUE TITLE
Add banner plugin to webpack to tag bundle with current version

### ISSUE THREAD

**Issue by ayusharma** [verdaccio/verdaccio#784]
Currently, There is no build/version information in the webpack bundle. It would be very helpful to find this information. 

https://webpack.js.org/plugins/banner-plugin/

**Comment by satyamyadav** [comment]
@ayusharma  I will work on this, will be sharing a banner template.

**Comment by juanpicado** [comment]
I'd remove the following. 
```
 *     Author: Alex Kocharin <alex@kocharin.ru>
 *     Description: Private npm repository server
 *     Source: git://github.com/verdaccio/verdaccio
 *     Hash: 3ca0f911a9154709a7fc 
 *     Chunkhash: ff808475141b55913510
 *     File: 0.style.b86c5878ee2935af83e9.css
```

**Comment by ayusharma** [comment]
@juanpicado All looks good. @satyamyadav waiting for a PR ❤️

**Comment by satyamyadav** [comment]
@ayusharma  Created PR #786 , please review the changes.

**Comment by ayusharma** [comment]
I have two suggestions here:

1. I think we can modify current`getPackageVersion.js` file to get other` package.json` properties.  `getPackageVersion.js` can be renamed to `getPackageJsonInformation.js` and it can export multiple `package.json` properties. Ref: https://github.com/verdaccio/verdaccio/blob/master/tools/getPackageVersion.js 

2. Banner config can be written in `webpack.prod.config.babel.js`.

@juanpicado What do you think?
