### ISSUE TITLE
Package still appears in registry despite being unpublished in the NPM registry

### ISSUE THREAD

**Issue by mgroenhoff** [verdaccio/verdaccio#788]
**Describe the bug**
There was a bug in the latest version of `nanomatch` and the author decided to unpublish that version (https://github.com/micromatch/nanomatch/issues/15). Verdaccio however seems to return the wrong version (the unpublished one).

We have configured Verdaccio with an uplink to the NPM registry (https://registry.npmjs.org/).

When i run `npm info nanomatch` against our repository the output looks like:
```
nanomatch@1.2.12 | MIT | deps: 12 | versions: 30
<omitted>

dist
.tarball http://<omitted>/nanomatch/-/nanomatch-1.2.12.tgz
.shasum: 25488d885861be8a4e3fb6f5506c3fe328f411b5
.integrity: sha512-7SnwnJy93JXezEB7+djz3tRRK6WL0615zc2AY2eRXKv3tw4GcGb5ScBokiSM3uWXlbQcC6OZusSCSeDrtNqmsQ==
.unpackedSize: 86.6 kB

<omitted>

dist-tags:
latest: 1.2.12

published an hour ago by jonschlinkert <github@sellside.com>
```

But when I run `npm info --registry https://registry.npmjs.org/ nanomatch` I get:

```
nanomatch@1.2.9 | MIT | deps: 12 | versions: 27
<omitted>

dist
.tarball https://registry.npmjs.org/nanomatch/-/nanomatch-1.2.9.tgz
.shasum: 879f7150cb2dab7a471259066c104eee6e0fa7c2
.integrity: sha512-n8R9bS8yQ6eSXaV6jHUpKzD8gLsin02w1HSFiegwrs9E098Ylhw5jdyKPaYqvHknHaSCKTPp7C8dGCQ0q9koXA==
.unpackedSize: 99.9 kB

<omitted>

dist-tags:
latest: 1.2.9

published 4 months ago by jonschlinkert <github@sellside.com>
```

**To Reproduce**
Not sure. I guess you need to have a repository with an uplink to NPM and have requested the nanomatch package at the time it was still published.

**Expected behavior**
I expect `npm info nanomatch` to return the same version as `npm info --registry https://registry.npmjs.org/ nanomatch` would.

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio:3
 - Docker commands:
 - Docker Version: 18.05.0-ce on linux, amd64

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```yaml
storage: /verdaccio/storage
auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    max_users: -1
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $all
    proxy: npmjs
    storage: '/verdaccio/storage/storage-default'
  '*':
    access: $all
    proxy: npmjs
    storage: '/verdaccio/storage/storage-default'
logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, path: /verdaccio/storage/verdaccio.log, level: warn}
listen:
  - 0.0.0.0:4873
```

**Comment by juanpicado** [comment]
https://github.com/rlidwka/sinopia/issues/427

**Comment by juanpicado** [comment]
@ayusharma any thought?

**Comment by juanpicado** [comment]
@mgroenhoff does https://github.com/rlidwka/sinopia/issues/219#issuecomment-87783174 answer your question ?

**Comment by mgroenhoff** [comment]
Well. First of all, it is not really a question but a bug report. Second, I am not the owner of nanomatch so I was not aware that is was unpublished.

I got a runtime error and it pointed me to nanomatch and I found out that the version was unpublished. So I removed the node_modules directory expecting the working, older version of nanomatch to be downloaded if I did an npm install agaon just like it would if I had used the NPM registry.

In the meantime I removed the package from the storage and that helped but I am surprised that it does not automatically do this since this can lead to serious bugs because they're unpublished for a reason.

**Comment by ayusharma** [comment]
Just adding my thoughts here. @juanpicado @mgroenhoff correct me If I am wrong: 

As npm document says : 

> It is generally considered bad behaviour to remove versions of a library that others are depending on! Consider using the deprecate command instead, if your intent is to encourage users to upgrade.

Also, https://github.com/rlidwka/sinopia/issues/219#issuecomment-87783174 mentioned to publish a new pakcage after bug fix. 

Just giving a example of verdaccio:

You can publish webpack@8.0.0 if you want but verdaccio can not remove it. It might be present in some other registry. NPM is not the default one.  It caches packages for you or host the packages you want to publish in your reach.

**Comment by mgroenhoff** [comment]
I fully agree with the fact that in unpublishing should be the last resort but I have no say in what the package maintainers can and can not do with their own packages. Since this is a feature that the NPM registry provides I expect any other registry to mirror this behavior.

**Comment by juanpicado** [comment]
> Since this is a feature that the NPM registry provides I expect any other registry to mirror this behavior.

Mmm, I differ here. 

Verdaccio hooks by default `npmjs`, but, **does not means this project is a mirror of npmjs**. Verdaccio allows to unpublish while [npmjs it does not after 24 hours](https://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy). By the time of this comment (https://github.com/rlidwka/sinopia/issues/219#issuecomment-87783174) `npmjs` was not allowing to wildly unpublish whatever.

> I got a runtime error and it pointed me to nanomatch and I found out that the version was unpublished. So I removed the node_modules directory expecting the working, older version of nanomatch to be downloaded if I did an npm install agaon just like it would if I had used the NPM registry.
> In the meantime I removed the package from the storage and that helped but I am surprised that it does not automatically do this since this can lead to serious bugs because they're unpublished for a reason.

I think the author did not unpublish https://github.com/micromatch/nanomatch/issues/15#issuecomment-400653829 , rather published a new minor release, which is the right approach. 

```
// https://registry.npmjs.org/nanomatch
"time": {
    "modified": "2018-06-27T13:02:45.042Z",
    "created": "2016-09-06T22:48:30.976Z",
    "0.1.0": "2016-09-06T22:48:30.976Z",
    "0.1.1": "2016-10-08T11:39:15.527Z",
    "0.1.2": "2016-10-08T11:47:21.318Z",
    "0.1.3": "2016-10-08T11:53:02.865Z",
     ....
    "1.2.8": "2018-02-18T14:04:07.896Z",
    "1.2.9": "2018-02-18T18:35:01.344Z",
    "1.2.10": "2018-06-27T02:17:58.156Z",
    "1.2.11": "2018-06-27T03:54:28.258Z",
    "1.2.12": "2018-06-27T07:15:18.116Z",
    "1.2.13": "2018-06-27T13:02:41.391Z"
  },
```

Anyway, in your description you do not provide how the `package.json` looks like, either you have `@latest` or a specific version. So, I cannot provide any feedback about it.

As @ayusharma mentioned, `npm` provides nice tools as `npm dist-tags` to create your own tags and avoid such kind of things, tags are mixed with remote one and never removed, so, next time you are running in such similar issue I'd suggest rather do something like  `npm dist-tags add nanomatch@1.2.9 fix-dep` or merely if you are admin just disconnect `nanomatch` from outside world do not proxying at all.

**Comment by mgroenhoff** [comment]
@juanpicado It was unpublished (https://github.com/micromatch/nanomatch/issues/15#issuecomment-401114628). A new version was indeed published but only after a short while. Anyway, if verdaccio can't keep its registry in sync without manual intervention I might need to start looking for an alternative.

**Comment by juanpicado** [comment]
@mgroenhoff the original objective of sinopia are described here https://github.com/verdaccio/verdaccio/blob/master/docs/use-cases.md#using-private-packages if your needs do not match which such necessity, then you are right, you might need a different solution.

Unfortunately these incidents happen more often that it seems so.

* https://blog.npmjs.org/post/169432444640/npm-operational-incident-6-jan-2018
* https://github.com/npm/registry/issues?q=is%3Aopen+is%3Aissue
