### ISSUE TITLE
 Please provide badge on private repository

### ISSUE THREAD

**Issue by kslhunter** [verdaccio/verdaccio#789]
Please provide badge on private repository like "verdaccio: v0.8.0"

**Comment by juanpicado** [comment]
@kslhunter I don't get it

**Comment by kslhunter** [comment]
like this
![badge](https://user-images.githubusercontent.com/6203799/42113492-666a0caa-7c26-11e8-8aa3-7484df6202b8.png)

**Comment by juanpicado** [comment]
Yeah, I got that. But, where? We have one already.
![screen shot 2018-06-29 at 11 12 57 pm](https://user-images.githubusercontent.com/558752/42115135-0e234df6-7bf2-11e8-86d5-99c7d874bac7.png)

**Comment by kslhunter** [comment]
Sorry. My English is not good enough.

1. Installing verdaccio on my private server
2. Upload a new private package to verdaccio

In this case, I need the version badge of the private package to be included in my README.md.

**Comment by juanpicado** [comment]
No worries, we are humans, I'm not English native speaker anyway. 

Ok, now let me explain that what you are asking for it's not something that Verdaccio will do for you, you have to do it your self before `npm publish --registry http://localhost:4873`

In order you add a badge in your readme, you can follow how we did it in ours 

https://raw.githubusercontent.com/verdaccio/verdaccio/master/README.md

Either HTML format
```
<a href="https://www.npmjs.org/package/verdaccio"><img alt="npm version" src="https://img.shields.io/npm/v/verdaccio.svg"></a>
```
or generate yours here

https://shields.io/

in markdown format, then publish on Verdaccio and you will be able to see your badge there. 

I hope that helps.

**Comment by kslhunter** [comment]
Thank you for your consideration.

I think there was a misunderstanding.

For example,
* Is the following link not able to provide badge image of the latest version?

```
https://myhost:4873/badge/version.svg?package=@myscope/mypackage
```
=> ![package version](https://img.shields.io/badge/verdaccio-3.1.4-green.svg)

*Examples of similar situations*:
[Jenkins Embeddable+Build+Status+Plugin](https://wiki.jenkins.io/display/JENKINS/Embeddable+Build+Status+Plugin)

**Comment by kslhunter** [comment]
Oh, sorry i solved this issue using https://shields.io/ like following:

https://img.shields.io/npm/v/@myscope/mypackage.svg?registry_uri=http://myhost:myport

thank you!!.

**Comment by juanpicado** [comment]
Happy to help!

**Comment by cdtinney** [comment]
Unfortunately the Shields.IO solution only works if your private registry is publicly accessible.

Supporting this natively would be a cool feature.

**Comment by juanpicado** [comment]
🤔 some sort of built-in https://github.com/badges/shields ?

**Comment by cdtinney** [comment]
Yeah. It would be a subset of the badges they offer -- maybe just the package name/version to start?

**Comment by juanpicado** [comment]
Sounds interesting, I'd love to see a PR of it.  👍
