### ISSUE TITLE
Add possibility to allow publish a package for "author(s)"/"contributor(s)"

### ISSUE THREAD

**Issue by aremishevsky-chegg** [verdaccio/verdaccio#790]
Hey guys.

Currently we have ability to set "all"/"authorized"/"someUser" to grand a publish access for packages as described in here:
https://github.com/verdaccio/verdaccio/blob/master/docs/packages.md

It would be awesome to have ability to set access as "author"/"contributor"
Also please think about separation of permissions for publish and unpublish packages.
F.E.
access: @all
publish:  @author @contributor someAdminUser
unpublish: @author someAdminUser

or
access: @all
publish:  @authorized
unpublish: @author someAdminUser

**Comment by juanpicado** [comment]
@aremishevsky-chegg but, how do you match a user logged with an author or contributor?  You might find many things there, since empty or names + emails and so on.

eg: 
http://registry.npmjs.org/abc

```
 },
  "author": {
    "name": "Golubev Fedor",
    "email": "gregof@yandex.ru",
    "url": "http://github.com/gregof"
  },
```

**Comment by aremishevsky-chegg** [comment]
@juanpicado verification by email with the full match

**Comment by juanpicado** [comment]
Unfortunately we do not store the email. Let see what ideas comes up.

**Comment by chengjianhua** [comment]
@juanpicado Why not store the email? Data complexity?

Just curious to ask that keep data in `db.json` is lightweight and straightforward, is whether the ways to store data right now limit some decision like this?

**Comment by juanpicado** [comment]
imho, email is an entity related with the authentification, while the `db.json` aims to store packages. I like the separation of corcerns. 

The htpasswd has some limitations, it's a key value plain and the storage format does not allow save more than that. 

So, right now the email has no place to be storaged. The same problem was hit on this discussion https://github.com/verdaccio/verdaccio/issues/541#issuecomment-427932910 

Currently I'm not 100% sure where and how we might store data, I'm open to suggestions.

**Comment by chengjianhua** [comment]
#541 and #790 issues relate to data storage, and this is a rather hard question, I have no ideas about this. One side is simplicity and fewer dependents; another party is the excellent data storage and query (e.g., CouchDB, or SQLite which also store data in a single file).

I hope that you can get a great idea about this. In my honest thoughts, give `htpasswd` a structure like JSON can solve this. The `email` is relevant to the user, do also `username`, `password` and colocate them together is reasonable IMO.

**Comment by juanpicado** [comment]
>  another party is the excellent data storage and query (e.g., CouchDB, or SQLite which also store data in a single file).

If it follows the zero-config approach, we can give it a try. 

> In my honest thoughts, give htpasswd a structure like JSON can solve this. The email is relevant to the user, do also username, password and colocate them together is reasonable IMO.

I'd love to read your proposal, perhaps I'm missing something.

**Comment by juanpicado** [comment]
In the next alfa we are shipping the `unpublish` property in packages, more context https://github.com/verdaccio/verdaccio/issues/492

**Comment by juanpicado** [comment]
Since no more ideas came from the last 12 months, I'm closing this, but it does not mean someone else can show a doable proposal, feel free to PR or keep discussing. We have been trying `level` for data storage of tokens, that might be a path to explore.
