### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by wariorx** [verdaccio/verdaccio#792]
Whenever I try to publish by running 
`npm publish --registry http://localhost:4873`
I run into this: 
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object (While processing pre
set: "C:\\Users\\rcalcam\\Documents\\verdaccio-master\\node_modules\\env\\index.js")
    at assertPath (path.js:39:11)
    at Object.join (path.js:434:7)`

**Comment by juanpicado** [comment]
Please, version, environment. etc etc.

**Comment by wariorx** [comment]
- Verdaccio 
Version: 3.2.0

- Config:
Default Config

- Env:
 Windows 7 (Version 6.1)

Is it possible that this is related to [](https://github.com/timarney/react-app-rewired/issues/)170 ?

**Comment by juanpicado** [comment]
I think is not directly related with verdaccio, if you find the real reason, please feel free to reopen.
