### ISSUE TITLE
safe list (filter packages by license)

### ISSUE THREAD

**Issue by Jeffrey1029** [verdaccio/verdaccio#803]
Sometimes we need to filter resources on public networks to prevent erroneous references. For example, the inappropriate license. When we downloaded resources from the public network, can we provide the function of configuring the security list?

**Comment by juanpicado** [comment]
@Jeffrey1029 I think you will need to elaborate much better what you want to achieve. Examples, etc etc.

**Comment by Jeffrey1029** [comment]
I'm very sorry,my English a little poor.I'll try my best to make me understood.

I have a request like this:
we can only use MIT license package, others is not allowed.
I want my private server can help me to filter which npm package is conform to my request
I remember that npm package often own a file like License.md
I don't know if it's possible to implement this function?

**Comment by Jeffrey1029** [comment]
anyway  thank you very much

**Comment by skipjack** [comment]
@juanpicado what about filtering on `tags` from the `package.json`. This should yield some flexibility since users can tag packages however they'd like (e.g. `deprecated`). Maybe the better question is what DO we have access to from the verdaccio web ui?

If it's possible -- and if you're open to it -- there's a good chance I'd be willing to submit a PR to add support for filtering (at least on tags but maybe a broader system). Seemed like a good idea to touch base here first before creating a new issue/pr though.

**Comment by juanpicado** [comment]
> what about filtering on tags from the package.json. This should yield some flexibility since users can tag packages however they'd like (e.g. deprecated). Maybe the better question is what DO we have access to from the verdaccio web ui?

I'm not sure whether I got it correctly. Do you mean list packages by license in the UI?

**Comment by skipjack** [comment]
No, I mean filter packages by `tags` in the UI. However I'm also interested in what's available for us to filter on, e.g. anything from the `package.json`?

**Comment by skipjack** [comment]
Sorry I meant the `keywords` field. Looks pretty straightforward if I edit this the top-level state manager (and maybe add a component or two):

https://github.com/verdaccio/verdaccio/blob/master/src/webui/modules/home/index.js

I just wasn't sure what contained in the data exposed to the UI, i.e. what's returned by the following:

```
API.request('packages', 'GET')
```

Just realized I could check the ajax call (doh!) though and it does look like most (if not all) `package.json` fields are returned. So would you be open to a PR that adds filtering to the UI? Probably starting with `keywords`?
