### ISSUE TITLE
add some auth/security options to the web UI

### ISSUE THREAD

**Issue by xavierpriour** [verdaccio/verdaccio#804]
**Is your feature request related to a problem? Please describe.**
I want only authorized users to be able to use the Web UI, I don't want my list of private packages to be exposed to the internet.
But currently, I can only enable/disable it for everyone.

**Describe the solution you'd like**
Have some options in the `web` config to limit access.
Maybe use same syntax/plugins as for packages access?

**Describe alternatives you've considered**
I've tried adding a reverse proxy with Basic Auth in front of Verdaccio. This worked ok for UI access, but:

- I had to define a set of authorized users in the reverse proxy itself
- `npm` commands no longer worked (as Verdaccio uses the same port for npm and web UI)

**Additional context**
Currently, I've disabled the web UI completely.

**Comment by juanpicado** [comment]
Have you read https://www.verdaccio.org/docs/en/protect-your-dependencies ?

**Comment by xavierpriour** [comment]
Thanks a lot for the speedy answer!

Yes, I use this to protect npm access: I put `access: $authenticated` on **.
But it does not protect **web UI** access (opening browser to http://myverdacciodomain.com:4873), so even unauthenticated people can see my package list, and I would like to block that as well.

**Comment by juanpicado** [comment]
Would you share an example of your config file and see how it looks like?

If you have something like this.
```
'my-company-*':
    access: admin teamA teamB teamC
    publish: admin teamA
    proxy: npmjs
```
Nobody unless teamA, teamB or teamC are logged will see anything in the webUI.

**Comment by xavierpriour** [comment]
Oh my, I'm so sorry, you're right, it works perfectly! I don't know how/why I missed it, but indeed nothing is showing.
If you're ok, I'll make a quick PR on the docs to make up for your time!

**Comment by juanpicado** [comment]
Sure, any PR is very welcome :)
