### ISSUE TITLE
global install with pnpm kills verdaccio

### ISSUE THREAD

**Issue by DanielRuf** [verdaccio/verdaccio#809]
**Describe the bug**
Installing `gatsby-cli` globally seems to corrupt the verdaccio install.
Afterwards I can not start verdaccio again as it seems the binary is gone.

cc 

**To Reproduce**
1. run `pnpm install --global gatsby-cli`

```
$ pnpm install --global gatsby-cli
Packages: +155
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 199, reused 199, downloaded 0, done
 ERROR  EPERM: operation not permitted, open 'C:\Users\Daniel\AppData\Roaming\npm\verdaccio'
```

**Expected behavior**
verdaccio should not be affected

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
```
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\Daniel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '-ddd' ]
npm info using npm@6.1.0
npm info using node@v10.2.1
npm verb config Skipping project config: C:\Users\Daniel/.npmrc. (matches userconfig)

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    completion, config, create, ddp, dedupe, deprecate,
    dist-tag, docs, doctor, edit, explore, get, help,
    help-search, hook, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, profile, prune, publish, rb, rebuild, repo, restart,
    root, run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Daniel\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.1.0 C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm
```
 - `$ npm config get registry` prints: http://localhost:4873/

**Additional context**
I am using Windows 10, already disabled realtime scanner of Windows Defender.

**Comment by juanpicado** [comment]
I cannot reproduce it locally (Mac).  It must be something related to Windows

```
~/WebstormProjects via ⬢ v8.9.4 at ☸️  minikube took 36s 
➜ pnpm install --global gatsby-cli
Packages: +199
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 199, reused 149, downloaded 50, done

dependencies:
+ gatsby-cli 1.1.58
```

**Comment by DanielRuf** [comment]
So running `verdaccio` will work afterwards? Hm, weird. Will test this further, maybe I have to upgrade pnpm or check the permissions of the folders.

I guess a clean reinstall of everything might be the best approach to rule out some outdated or broken packages and caches caused by the underlying filesystem or network conditions.

I will keep you updated.

**Comment by juanpicado** [comment]
> So running verdaccio will work afterwards? Hm, weird. Will test this further, maybe I have to upgrade pnpm or check the permissions of the folders.

No, It did not kill my verdaccio at all.
