### ISSUE TITLE
Can't use scope with local packages

### ISSUE THREAD

**Issue by macdasi** [verdaccio/verdaccio#81]
I want to publish my package to http://localhost:4873/ the name of the package is @local/my-lib
If I try to do it I get error : 

>  one of the uplinks is down, refuse to publish

without the scope it is working . 
My command is 

> call npm config set @local:registry http://localhost:4873
> call npm publish

In my packages.json :

> "publishConfig":{
>     "registry":"http://localhost:4873"
>   },

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/issues/55

**Comment by jonaskello** [comment]
This is working for me. I think maybe you are missing the proxy part in your config?

```
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
    storage: /verdaccio/local_storage
```

**Comment by juanpicado** [comment]
@macdasi related tickets
https://github.com/verdaccio/verdaccio/issues/118
https://github.com/verdaccio/verdaccio/issues/50
