### ISSUE TITLE
Block Versions Based on Some Filter

### ISSUE THREAD

**Issue by mlucool** [verdaccio/verdaccio#818]
**Is your feature request related to a problem? Please describe.**
Recent issues with community published libraries either [malicious](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes) or [not](https://www.theregister.co.uk/2018/02/23/npm_undoes_patch/) are generally caught by the community quickly. I'd like to come up with a defense against these types of issues.

**Describe the solution you'd like**
The ability to create a plugin that allows for fine grained, rule based control of if a package appears to exist to npm clients.

For example, I could create a rule that says a package must have been published at least X days ago before the registry proxy claims it exists to clients. This would take us off bleeding edge, but lower the risk of major issues. I would also be able to do things like feed it a blacklist of libraries that no one should be able to download (e.g. in the days before [npm grabbed this](https://www.npmjs.com/package/child_process), we would block it). A good design would allow for easy admin and escape hatches to let new versions flow through. It may also consider allowing clients the ability to override this depending on the design and trust model we want to build.

There is clear risk here and moving away from a simple proxy and increasing the complexity and management of a proxy, but given the seriousness of recent issues, I believe would add a good line of defense. 

What do you think?

**Comment by juanpicado** [comment]
It relates with https://github.com/verdaccio/verdaccio/issues/810

**Comment by juanpicado** [comment]
I like the idea, but we would need to elaborate a bit more what are the boundaries and whether is possible with the current design + being optional

**Comment by mlucool** [comment]
Hi @juanpicado, any more thoughts on this?

**Comment by juanpicado** [comment]
@mlucool I haven't had time yet, sorry.

**Comment by mlucool** [comment]
I spent some time on this. I would I was able to remove packages by adding in a function in [storage.getPackage](https://github.com/verdaccio/verdaccio/blob/master/src/lib/storage.js#L290) that pruned the result by deleting both the time and versions key for that specific version. 
e.g.
```
delete result.versions[badVersion];
delete result.time[badVersion];
```

The only major issue with this approach is if you delete something that is a also a `dist-tag` you have to do some sort of repair. I also don't know if this is all that is necessary, but testing showed this is sufficient for the `npm i` case.

Therefore, I propose we add in a plugin with an API of one function, `filter`. This will be called on every call to getPackage. A noop implementation of this is the identity function.

What do you think? Worth pursuing?

**Comment by mlucool** [comment]
@juanpicado I created an WIP in https://github.com/verdaccio/verdaccio/pull/1161 for what I think could create a plugin based approach to solve this. What do you think of this concept? If you like it, what do you think are the next steps to get this ready for merging? I know I need to refactor this so external plugins can be created and add unit testing.

**Comment by mlucool** [comment]
Closing as this was completed via https://github.com/verdaccio/verdaccio/pull/1161

**Comment by robcresswell** [comment]
@mlucool Was this documented anywhere? I see all the PRs merged, but I can't see anything about filters on the docs site

**Comment by juanpicado** [comment]
@robcresswell not extensively https://verdaccio.org/docs/en/dev-plugins#filter-plugin but yes, also the PR contains some information.
