### ISSUE TITLE
Is there a server health path for liveness check?

### ISSUE THREAD

**Issue by cncolder** [verdaccio/verdaccio#828]
**Is your feature request related to a problem? Please describe.**

If deploy `verdaccio` into k8s or back load balance. I need setup a liveness check url for detect if server has running up.

k8s use http GET and my load balance use http HEAD.

This need a path. If point to `/`. It works. But the log is too noise.

```shell
[verdaccio-bb84f5d78-slv9v] [verdaccio] http <-- 200, user: undefined(172.16.1.1), req: 'HEAD /', bytes: 0/0
```

I have try different paths: `/-/verdaccio/logo` `/-/static/index.html`. But all cannot skip express logger.

**Describe the solution you'd like**

Add a check endpoint `/.well-known/verdaccio/server-health`

**Describe alternatives you've considered**

**Additional context**

**Comment by juanpicado** [comment]
@cncolder no there is no such thing, but you might create a simple middleware plugin adding a custom endpoint.

On testing mode, we have this endpoint https://github.com/verdaccio/verdaccio/blob/master/src/api/debug/index.js#L9 that provide some information. I do not recommend it enable it on production environments.

**Comment by paulbrimicombe** [comment]
There is a `/-/ping` endpoint you can use for server health which only returns an empty javascript object (probably better than `/`). It does still get logged in the access logs, however.

Do you use verdaccio to log to file or do you pipe the output via the console? If you're piping from the console you could pipe it through `grep` or similar to filter out the lines that don't interest you.

**Comment by juanpicado** [comment]
Exactly as @paulbrimicombe pointed out (https://github.com/verdaccio/verdaccio/blob/master/src/api/endpoint/api/ping.js#L7). Is it that good enough for you @cncolder ?

**Comment by cncolder** [comment]
Thanks your answer. It works but not good enough.

I still thinking we need a endpoint that give a health feedback to load balance (like kubernetes ingress or another api gateway) but skip log.

Add middleware or plugin is an option. But the docker user must build a custom image.

**Comment by paulbrimicombe** [comment]
The point of the ping endpoint is so tools like `npm` can check that the registry is up (i.e. server health). See the `npm ping` command.

@cncolder Do you use console logging and can you filter using something like `grep` as a work-around? Do you need the access logs or would warning / info logging be OK for you? What docker image are you using?

**Comment by cncolder** [comment]
I use `https://hub.docker.com/r/verdaccio/verdaccio/`

config.yaml
```yaml
# copy from https://verdaccio.org/docs/en/logger
  logs:
    - {type: stdout, format: pretty, level: http}
```

If I change log level to warn. `verdaccio` skip all http relate log.

Just config it like this now.

Thank you.

**Comment by juanpicado** [comment]
@cncolder It seems they are doing more or less what you were looking for https://github.com/helm/charts/pull/6616#issue-200874132

**Comment by juanpicado** [comment]
:-) cool I'll close this one.
