### ISSUE TITLE
Package repeat-element@1.1.2 brakes website when published

### ISSUE THREAD

**Issue by pavels555** [verdaccio/verdaccio#829]
**Describe the bug**
When the package repeat-element@1.1.2 is published to the registry it break the webui for some reason.

**To Reproduce**
1. Remove uplinks from config.
2. Download repeat-element@1.1.2 from npm (https://registry.npmjs.org/repeat-element/-/repeat-element-1.1.2.tgz)
3. Publish the .tgz to verdaccio
4. Surf to verdaccio ui
5. See error

**Expected behavior**
Expected the site to load regulary

**Screenshots**
![image](https://user-images.githubusercontent.com/1210768/42964364-7d7a769a-8b9f-11e8-8038-0ca556aa0ebc.png)

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: 3.2.0

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
default without uplinks.

**Comment by ayusharma** [comment]
It's a valid issue. @juanpicado I'll provide a hotfix for this.
