### ISSUE TITLE
Add bundlesize 

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/verdaccio#835]
Related to #773, we are going to add bundlesize to now the size in every build. Also, we integrate it in our CircleCI workflow

**Comment by ayusharma** [comment]
@sergiohgz Any progress on this? :) Today, I have also added a dependency in master. So it's good to have this asap.  Thanks 😀

**Comment by sergiohgz** [comment]
@ayusharma I was trying to add but something happens in my repo that reject install as devDependency. I see that you added and @juanpicado set limits. I will integrate it in CircleCI workflow tomorrow 😉
