### ISSUE TITLE
Add mailto: link to the contributors list in the sidebar

### ISSUE THREAD

**Issue by dmstern** [verdaccio/verdaccio#837]
In the sidebar of the package detail view it would be nice if I could click on the contributor's name or avatar to send him/her an email.

Maybe with some metadata prefilled, like:

Subject: `${packageName}@${version} on ${verdaccioHost}"

**Comment by juanpicado** [comment]
@dmstern is there PR for this?

**Comment by dmstern** [comment]
@juanpicado No, unfortunately, I did not manage the tests pass.
I already tried to re-create the snapshots, but I have got an issue with the `last-synced` component, which always produces different times than specified in the specs. There is always an offset of one hour, I think this is a timezone issue.

**Comment by juanpicado** [comment]
Please post the branch and I will review it
