### ISSUE TITLE
ansible support

### ISSUE THREAD

**Issue by 030** [verdaccio/verdaccio#84]
https://github.com/030/ansible-verdaccio

**Comment by juanpicado** [comment]
@030 questions to move this:
* It needs his own repository or can coexist with the main repository, what do you suggest?
* It would make sense to move your repo to the `verdaccio` organization and you take care of it?

**Comment by 030** [comment]
@juanpicado Once the repository has been moved, am I still able to merge PRs?

**Comment by 030** [comment]
@juanpicado 1) It needs to be in the own repository. According to ansible galaxy all roles have an own repo. 2) I will transfer the repo to the verdaccio org.

**Comment by juanpicado** [comment]
Sure, @030 that repo would be your responsibility.  Are you agreed?

**Comment by 030** [comment]
```You don’t have the permission to create repositories on verdaccio ```

**Comment by juanpicado** [comment]
@030 Give me one second. I'll solve that.

**Comment by juanpicado** [comment]
@030 try again

**Comment by 030** [comment]
@juanpicado it works. Thank you!

**Comment by juanpicado** [comment]
welcome aboard ! 🚢

**Comment by 030** [comment]
@juanpicado Thank you. Is there an organization logo?

**Comment by juanpicado** [comment]
No 😢  we need a kind person + designer + open source lover that support us with that.

**Comment by juanpicado** [comment]
@030 you are the admin of that repo, all yours.

**Comment by 030** [comment]
![verdaccio-logo](https://user-images.githubusercontent.com/7524528/27743864-ac8da3fa-5dbd-11e7-9fc3-c61b8dcbb7bd.png)

**Comment by juanpicado** [comment]
Let's people vote :)

**Comment by jmwilkinson** [comment]
Needs to be green, same color as the current image. Also would be nice if it was kinda old-timey, something like: 
![verdaccio](https://user-images.githubusercontent.com/17836030/27748692-31c6ca58-5d85-11e7-88fe-674adbcf341f.png)

**Comment by juanpicado** [comment]
We should open a new thread for this.

**Comment by Meeeeow** [comment]
Hmm... We need a designer...

**Comment by 030** [comment]
https://github.com/verdaccio/verdaccio/issues/237
