### ISSUE TITLE
webui: atob not support unicode strings

### ISSUE THREAD

**Issue by calledT** [verdaccio/verdaccio#840]
**Describe the bug**
I use verdaccio-ldap for auth and the token payload has unicode strings. webui use atob decode payload will throw error.  

https://github.com/verdaccio/verdaccio/blob/eecc98f6716331f88b83b9302ddd47b59fd9b75d/src/webui/components/Header/index.js#L111

I just replace atob with https://github.com/dankogai/js-base64 `Base64.decode`  manually and it work well.

**Comment by ayusharma** [comment]
`atob` has the problem with Unicode. Read it here https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding

Also, Implement the solution described in the above article.

**Comment by juanpicado** [comment]
shipped `verdaccio@3.4.0`
