### ISSUE TITLE
Update Gitter links to Discord links

### ISSUE THREAD

**Issue by ayusharma** [verdaccio/verdaccio#843]
**Describe the bug**
In our documentation, we still have the link to our Gitter channel. Update it to Discord.
Updated Link: http://chat.verdaccio.org

You can take the help of this:
https://github.com/search?l=Markdown&q=org%3Averdaccio+Gitter&type=Code

**Comment by ashishsurana** [comment]
@juanpicado You can close this issue as this has been fixed with [PR: #876](https://github.com/verdaccio/verdaccio/pull/876)
