### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by MichielDeMey** [verdaccio/verdaccio#844]
**Describe the bug**
Using `verdaccio-htpasswd`, the following error throws when trying to publish an NPM package.

```
TypeError: Cannot read property 'some' of undefined
```

Note: authenticating with the registry does work.

**To Reproduce**
1. Mount a `htpasswd` file
2. Authenticate with the registry
3. Push an NPM package
4. See error (500 Internal Server Error)

**Expected behavior**
Publishing a package should not throw a 500 Internal Server Error

**Docker && Kubernetes:**
 - Docker verdaccio tag: verdaccio:beta

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```
...
auth:
    htpasswd:
      file: /auth/htpasswd
      max_users: -1

packages:
    '@*/*':
      access: $all
      publish: $authenticated
      proxy: npmjs
...
```

**Debugging output**
 ```
info &lt;-- 10.117.12.3 requested 'PUT /poppy-sftp'
 info --- basic authentication is deprecated, please use JWT instead
 error--- unexpected error: Cannot read property 'some' of undefined
TypeError: Cannot read property 'some' of undefined
    at Object.allow_publish (/usr/local/app/build/lib/auth-utils.js:16:39)
    at next (/usr/local/app/build/lib/auth.js:165:14)
    at next (/usr/local/app/build/lib/auth.js:162:16)
    at Auth.allow_publish (/usr/local/app/build/lib/auth.js:175:7)
    at /usr/local/app/build/api/middleware.js:125:30
    at Layer.handle [as handle_request] (/usr/local/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/app/node_modules/express/lib/router/index.js:281:22
 http &lt;-- 500, user: michiel(84.198.87.116, 35.241.10.246 via 10.117.12.3), req: 'PUT /poppy-sftp', error: internal server error
```
**Additional context**
I believe this is caused because the `verdaccio-htpasswd` package has not yet been updated for the refactor introduced in https://github.com/verdaccio/verdaccio/pull/800 and the function `allow_publish` is missing.

Link to the line causing the issue: https://github.com/verdaccio/verdaccio/pull/800/files#diff-27264c6d2e54aef927237fa20c7e08efR7

**Comment by juanpicado** [comment]
@MichielDeMey we have tried to reproduce it but we could not.

**Comment by MichielDeMey** [comment]
Ok, I've been able to reproduce it.
It seems I was trying to publish a non-scoped package but my configuration did not specify anything for non-scoped packages. If that makes sense?
