### ISSUE TITLE
HTLM rendering issues in docker hub docs

### ISSUE THREAD

**Issue by dlouzan** [verdaccio/verdaccio#848]
**Describe the bug**
The official documentation for the docker image in the docker hub shows html tags and is not rendered correctly.  

**To Reproduce**
Visit https://hub.docker.com/r/verdaccio/verdaccio/

**Comment by juanpicado** [comment]
Yeah ... but I guess we cannot do anything about it. They do not accept html on readme.  Any idea ?

**Comment by ayusharma** [comment]
I think it's the docker hub issue. We can close it.  @dlouzan If you find a way to fix, Please feel free to open it again.
