### ISSUE TITLE
chef support

### ISSUE THREAD

**Issue by 030** [verdaccio/verdaccio#86]
does the cookbook defined in the readme still work?

**Comment by kgrubb** [comment]
I've created a new verdaccio cookbook: 

[source](https://github.com/kgrubb/verdaccio-cookbook)

[supermarket](https://supermarket.chef.io/cookbooks/verdaccio). 

I've been messing around with it and it seems to work so far.

**Comment by juanpicado** [comment]
Awesome :+1:

**Comment by juanpicado** [comment]
@kgrubb could you update the readme.md ?

**Comment by hdost** [comment]
Should this be closed now?

**Comment by juanpicado** [comment]
Sorry, I did not close it before :)

**Comment by juanpicado** [comment]
@kgrubb I wonder, would you like to bring your project to the organization? as it was did with ansible last month.

**Comment by juanpicado** [comment]
@kgrubb I made you admin of the repository  Welcome aboard.
