### ISSUE TITLE
puppet support

### ISSUE THREAD

**Issue by 030** [verdaccio/verdaccio#87]
should sinopia not be renamed or a new module be created in puppetforge?

**Comment by juanpicado** [comment]
@030 I'd need more elaborate information, I have no clue about `puppet`. Perhaps you can enlighten us.

**Comment by juanpicado** [comment]
https://github.com/Dharmender-Singh/puppet-verdaccio

**Comment by juanpicado** [comment]
Puppet is part of the organization already. Closing this.
