### ISSUE TITLE
Verdaccio instead of Sinopia

### ISSUE THREAD

**Issue by 030** [verdaccio/verdaccio#88]
```Sinopia doesn't need superuser privileges. Don't run it under root.```

should be

```Verdaccio doesn't need ...```

**Comment by lengziyu** [comment]
Me too,+1

**Comment by juanpicado** [comment]
Considere change some internal sinopia references will affect sinopia plugins used by verdaccio

**Comment by kgrubb** [comment]
Ah, didn't think about plugin support. If that's the case, maybe we should fork or replace sinopia plugins for use with verdaccio, since sinopia is still at a standstill in development? or is that more of a headache than its worth?

**Comment by juanpicado** [comment]
Well, I think duplicate them is not a good idea, it will create more confusion, maybe we should add some kind of backward compatible plugin support.

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/issues/64 this issue claims that anyway, so, maybe is good idea after all.

**Comment by Nighthawk22** [comment]
Yeah but you have to be carefull because no plugin / existing db will work with this plugin anymore.

**Comment by juanpicado** [comment]
What do you mean @Nighthawk22 ? I don't get it

**Comment by Nighthawk22** [comment]
i meant, that the PR also dropped the support for the old sinopia plugins. But the author of the PR already changed the specific line.

**Comment by juanpicado** [comment]
This is already fixed https://github.com/verdaccio/verdaccio/blob/master/lib/cli.js#L6 . About the plugins I'll commit the related PR
