### ISSUE TITLE
Recommended way to extend or change the built in UI

### ISSUE THREAD

**Issue by dejitaiza** [verdaccio/verdaccio#880]
Hello everyone,

I have an internal deployment of verdaccio, and I needed to change the color, logo size and other things.

I couldn't find a recommended way to make advancee changes to the UI besides the title and the logo image.

I went ahead and modified the compiled css files directly (and I hate myself for doing that).

Now, I'd like to make deeper changes to the UI, for example to retrieve metrics associated with a package from a different web service.

Is there any recommendation from the contributors or the community on how to address these scenarios in a clean and future proof way?

Thank you for your time.

**Comment by juanpicado** [comment]
cc: @ayusharma @priscilawebdev @sergiohgz

**Comment by juanpicado** [comment]
@dejitaiza the team is working on re-think the new UI, we are looking for new ideas. I'm sure your suggestion will be part of the new UI soon.

**Comment by dejitaiza** [comment]
@juanpicado that sounds great! Is there a place to follow the new UI discussion, or potentially chime in with ideas? I'd like to get involved if possible.

**Comment by juanpicado** [comment]
@dejitaiza  http://chat.verdaccio.org/

**Comment by bufferoverflow** [comment]
My favorite solution whould be a dedicated verdaccio-ui repo for the frontend code and to implement all ui topics via api only.

**Comment by sergiohgz** [comment]
@bufferoverflow I like that idea, a good separation of the front and the back would be great for development. What do you think @juanpicado @ayusharma @priscilawebdev?

**Comment by priscilawebdev** [comment]
@sergiohgz @bufferoverflow I also like the idea...what do you think  @juanpicado @ayusharma?

**Comment by juanpicado** [comment]
It is fine for me, but I am thinking in some Lerns approach.

**Comment by dlouzan** [comment]
I really love this part:
> I went ahead and modified the compiled css files directly (and I hate myself for doing that)

Just saying, we've all been there

**Comment by juanpicado** [comment]
Update:

- We are moving UI to -> https://github.com/verdaccio/ui  in hands of @priscilawebdev 
- UI will be a dependency https://github.com/verdaccio/verdaccio/pull/1215 and perhaps a plugin, let's see. 

I'd recommend following #1215 and UI repo instead, closing this one.
