### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#883]
**Describe the bug**

https://hub.docker.com/r/verdaccio/verdaccio/builds/b2n7pe8mpyve3satfwhg5td/
```
[91merror /usr/local/app/node_modules/iltorb: Command failed.
Exit code: 1
Command: detect-libc prebuild-install || node-gyp rebuild
Arguments: 
Directory: /usr/local/app/node_modules/iltorb
Output:
prebuild-install WARN install No prebuilt binaries found (target=10.3.0 runtime=node arch=x64 platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.3.0 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/app/node_modules/iltorb/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/app/node_modules/iltorb/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/app/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/app/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/app/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/app/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/app/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Linux 4.4.0-1060-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/app/node_modules/iltorb/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/app/node_modules/iltorb
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
```

Locally fails

```
yarn run build:docker
```

**Expected behavior**
It should not fails

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: beta

**Additional context**

cc: @sergiohgz @dlouzan 🆘 

refers:
* https://github.com/nodejs/docker-node/issues/384

**Comment by albi34** [comment]
Looks like Python is missing from the docker build, I had it work from my local after manually adding python  back but I'm wondering why it stopped working 2 days ago, I'm not seeing any related commits.

**Comment by juanpicado** [comment]
@albi34 exactly, we haven't changed anything. Odd stuff.

**Comment by juanpicado** [comment]
Solved https://hub.docker.com/r/verdaccio/verdaccio/builds/bodwgdhk4xpkwmxgskvxcxd/

**Comment by dlouzan** [comment]
I don't understand: there has been an upstream incompatible change in the base node image?

**Comment by dlouzan** [comment]
I have just executed this locally by removing my cached `node:10.3-alpine` images, and it fails now, something has been changed in the alpine image. I'm not sure if they removed python as default installed package, or it was listed as transitivie dependency of one of our apk dependencies and it's not anymore.

This extra step increases the size of the image quite a bit, but in the refactored dockerfile we'll just do this in the build step :-)

I'm opening a PR to backport this change to 4.x

**Comment by dlouzan** [comment]
@juanpicado Before doing the PR, how are managing keeping the 4.x branch up to date? are you just copying selected commits from 3.x to 4.x, are you just going to do a long chery-pick later, should I continue with the backporting of this...?

**Comment by juanpicado** [comment]
> how are managing keeping the 4.x branch up to date? 

if we can merge, merge, in the worse case rebase.

**Comment by juanpicado** [comment]
But, we still have to decide when `4.x` will be released, based on that, any new feature will go to `4.x` minimizing the conflicts.

**Comment by juanpicado** [comment]
@dlouzan welcome on board. Now you should be able to create your own branches if you wish.
