### ISSUE TITLE
NewRelic Agent throwing errors after update to 3.3.0 version

### ISSUE THREAD

**Issue by aremishevsky** [verdaccio/verdaccio#884]
**Describe the bug**
NewRelic Agent throwing errors after update to 3.3.0 version. 
Error is following:
```
{"v":0,"level":50,"name":"newrelic","hostname":"5538dce32c23","pid":75,"time":"2018-08-01T14:20:12.118Z","msg":"Unable to serialize payload for method connect.","component":"remote_method","stack":"TypeError: this is not a Date object.\n    at Object.valueOf (<anonymous>)\n    at Object.[Symbol.toPrimitive] (<anonymous>)\n    at Object.toJSON (<anonymous>)\n    at JSON.stringify (<anonymous>)\n    at stringify (/www/docker/node_modules/json-stringify-safe/stringify.js:5:15)\n    at RemoteMethod.serialize (/www/docker/node_modules/newrelic/lib/collector/remote-method.js:42:15)\n    at RemoteMethod.call [as invoke] (/www/docker/node_modules/newrelic/lib/collector/remote-method.js:64:8)\n    at CollectorAPI._connect (/www/docker/node_modules/newrelic/lib/collector/api.js:186:21)\n    at getEnvDict (/www/docker/node_modules/newrelic/lib/collector/api.js:178:10)\n    at factMapCb (/www/docker/node_modules/newrelic/lib/collector/facts.js:67:12)","message":"this is not a Date object."}
```

As result - empty NewRelic logs

**After some investigation**

After some investigation in diffs:
https://github.com/verdaccio/verdaccio/compare/v3.2.0...v3.3.0
I've found a PR https://github.com/verdaccio/verdaccio/pull/764. 
After that PR merge it breaks NewRelic logic.

It works well after the commit https://github.com/verdaccio/verdaccio/commit/825f5a57eaa04a895fbf9673481fcf647b0a0d68

But after the https://github.com/verdaccio/verdaccio/commit/29bb57ad5f5d762e8f1f4e3267f5bd11f8caa272 commit it is broken.

**Screenshots**

![comparing_v3_2_0___v3_3_0_ _verdaccio_verdaccio](https://user-images.githubusercontent.com/32752187/43534433-04d92490-95c0-11e8-8860-a795a8fdacdb.png)

**Comment by ayusharma** [comment]
Adding formatted stack trace:
```
{
  "v":0,
  "level":50,
  "name":"newrelic",
  "hostname":"5538dce32c23",
  "pid":75,
  "time":"2018-08-01T14:20:12.118Z",
  "msg":"Unable to serialize payload for method connect.",
  "component":"remote_method",
  "stack":"TypeError: this is not a Date object.\n 
            at Object.valueOf (<anonymous>)\n    
            at Object.[Symbol.toPrimitive] (<anonymous>)\n    
            at Object.toJSON (<anonymous>)\n    
            at JSON.stringify (<anonymous>)\n    
            at stringify (/www/docker/node_modules/json-stringify-safe/stringify.js:5:15)\n    
            at RemoteMethod.serialize (/www/docker/node_modules/newrelic/lib/collector/remote-method.js:42:15)\n    
            at RemoteMethod.call [as invoke] (/www/docker/node_modules/newrelic/lib/collector/remote-method.js:64:8)\n    
            at CollectorAPI._connect (/www/docker/node_modules/newrelic/lib/collector/api.js:186:21)\n    
            at getEnvDict (/www/docker/node_modules/newrelic/lib/collector/api.js:178:10)\n    
            at factMapCb (/www/docker/node_modules/newrelic/lib/collector/facts.js:67:12)",
  "message":"this is not a Date object."
}
```

**Comment by juanpicado** [comment]
@aremishevsky please we need some log from the server or client side, otherwise, we cannot track any issue.

**Comment by aremishevsky** [comment]
Here you go:

The first one is a stdout logs on start of the verdaccio 3.2.0 server:
[3.2.0-OK.txt](https://github.com/verdaccio/verdaccio/files/2252515/3.2.0-OK.txt)

This one is with verdaccio 3.4.1 (errors are the same for version 3.3.0-3.4.1)
[3.3.0-3.4.1-Errors.txt](https://github.com/verdaccio/verdaccio/files/2252514/3.3.0-3.4.1-Errors.txt)

I hope this could help you to find an issue and fix it as soon as possible.

Thanks.

**Comment by priscilawebdev** [comment]
@aremishevsky we have analyzed the log and the error seems to come from YOUR plugin.
If the problem is due to the library conflict, as you said, we would like you to prove it to us.. Please feel free to create a bug simulation and post the link here ... Thanks!

**Comment by aremishevsky** [comment]
Hey @priscilawebdev .

What kind of simulation do you need?
I've already sent you logs from working(...-3.2.0 verdaccio version) and not working (3.3.0-... verdaccio versions).
I've already found a commit after what NewRelic NodeJS Agent starts to fail. (Please note that it is NOT my plugin - it is a global and official NewRelic plugin designed for work with NodeJS applications)
https://www.npmjs.com/package/newrelic
I've already tried to decrease the version of the NewRelic Agent - no results.

The only thing to have it working correct is to use 3.2.0 version or to revert "asciidoctor.js" https://github.com/verdaccio/verdaccio/commit/29bb57ad5f5d762e8f1f4e3267f5bd11f8caa272 changes.

In case you need to provide you a manual how to implement a NewRelic NodeJS Agent - in the verdaccio engine - just let me know.

Thanks!

**Comment by priscilawebdev** [comment]
Hi @aremishevsky !

> What kind of simulation do you need?
     I'm talking about provide a full example that prove is not working..maybe you can create a private 
     repository or use codepen, code sandbox...whatever..

> I've already tried to decrease the version of the NewRelic Agent - no results.
   Without access to the new relic integration we cannot debug.

> In case you need to provide you a manual how to implement a NewRelic NodeJS Agent - in the verdaccio engine - just let me know.

   Sorry but I would prefer your  full example.

Thank you!

**Comment by ayusharma** [comment]
@aremishevsky Please reopen the issue if the problem persists.

**Comment by aremishevsky** [comment]
Hi @ayusharma . Yes this issue still exists.

Here is the same issue that i've found of "opal-runtime" module (that is using by "asciidoctor.js" package)
https://github.com/opal/opal/issues/1684#issuecomment-370683649

**Comment by ayusharma** [comment]
@aremishevsky Thanks for reporting. I am investigating it again.

**Comment by aremishevsky** [comment]
@ayusharma In case you need some help with NewRelic agent integration - just let me know

**Comment by aremishevsky** [comment]
@ayusharma .

Seams like i've found a solution - could you please update "asciidoctor.js" package to the latest "1.5.7-rc.1" version? (it already includes the "opal-runtime" latest 1.0.7 version)
https://www.npmjs.com/package/asciidoctor.js?activeTab=versions

Current 1.5.6 version of "asciidoctor.js" requires only "1.0.3" version of the "opal-runtime" module.

I've changed it manually in the verdaccio's package.json, rebuilt it and newRelic become alive.)))

**Comment by aremishevsky** [comment]
@ayusharma could you please review this PR?
https://github.com/verdaccio/verdaccio/pull/934

**Comment by aremishevsky** [comment]
For now I've restored the registry update using `npm-shrinkwrap.json` file
```
{
  "dependencies": {
    "verdaccio":{
      "version": "3.5.1",
      "from": "verdaccio@3.5.1",
      "dependencies": {
        "asciidoctor.js": {
          "version": "1.5.7-rc.1",
          "from": "asciidoctor.js@1.5.7-rc.1",
          "dependencies": {
            "opal-runtime": {
              "version": "1.0.6",
              "from": "opal-runtime@~1.0.7"
            }
          }
        }
      }
    }
  }
}
```
I think have this here would be useful.

**Comment by davedoesdev** [comment]
Are there plans to put AsciiDoc support back it?

**Comment by juanpicado** [comment]
@davedoesdev I'll be glad to add it again if someone finds a way using something different as the library `asciidoctor.js` which does some sort of monkey patching to native libraries.
