### ISSUE TITLE
Redirect to npmjs.com when a package is not found locally

### ISSUE THREAD

**Issue by axelrindle** [verdaccio/verdaccio#888]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I click on a package dependency and all I get is this:
```json
{
  "error": "File not found"
}

```

**Describe the solution you'd like**
I would like to see a redirection to **npmjs.com**, whenever a package is not found locally.

**Describe alternatives you've considered**
An alternative option would be to display a page with a little notice, indicating that the requested package does not exist locally, but on **npmjs.com**.

**Comment by juanpicado** [comment]
@axelrindle I don't get it. Could you elaborate?

**Comment by coolsp** [comment]
Was thinking about same type of feature request.
I'm using verdaccio only for scoped modules not to cache the official npm modules (at least for now).
My scoped modules depend on some official modules but as those are not cached on verdaccio, clicking on them in the webui results in:
```
Error 404 - debug
Oops, The package you are trying to access does not exist.
```
Would be nice that in the webui you immediately include the npmjs link with a little icon next to it to indicate that it is an external link.
This would mean you would have to identify those modules prior to rendering the page.
Or alternatively, as suggested by @axelrindle, redirect requests for non-cached modules to npmjs.

**Comment by bufferoverflow** [comment]
One option would be to handle that 404 within web ui logic and fetch the data from upstream direct via browser.

**Comment by axelrindle** [comment]
@juanpicado Do I still need to elaborate or has it become clear by what @coolsp and @bufferoverflow mentioned?

**Comment by juanpicado** [comment]
@axelrindle 
> I'm always frustrated when I click on a package dependency and all I get is this:

I wonder how is that possible since any `npm` client will download all dependencies (unless the process fails) and should be not possible to click around UI and get a 404.

> An alternative option would be to display a page with a little notice, indicating that the requested package does not exist locally, but on npmjs.com

verdaccio is just a proxy, it fetch only when a `npm` CLI request, verdaccio never acts on his own. The UI only represents what's remains on storage. Futhermore, `npmjs` is just a registry (the default one) and we cannot hook verdaccio to specific registry and it relies on what's on uplink configuration.

If you are getting 404 please elaborate some reproduce steps, perhaps I'm missing something.

**Comment by coolsp** [comment]
Steps to reproduce:
- Setup verdaccio as scoped private repository only, in config.yaml
-Remove any uplinks under _uplinks_
-Remove any proxies under _packages_
-Set a scope under _web_ (e.g.: @coolsp)
- Publish a private scoped module with a dependency to a public module (e.g. debug)
-npm publish @coolsp/myprivate --registry https://<my-repo>:4873
- Logon to the webui
- Click on module _@coolsp/myprivate_
- Click in right-pane on dependency (e.g. debug)

```
Error 404 - debug
Oops, The package you are trying to access does not exist.
```
Quod erat demonstrandum

**Comment by juanpicado** [comment]
Thanks @coolsp I'll try later and I'll let you know what I found.

**Comment by coolsp** [comment]
Any update/progress on this one?

**Comment by juanpicado** [comment]
@coolsp, unfortunately, no, this ticket was wrongly tagged.

**Comment by Meeeeow** [comment]
It's not possible to install any dependencies that not available in local with a private only registry, so i think it should be a 404 page when trying to access dependencies.

**Comment by coolsp** [comment]
Showing a 404 is a bad user-experience and leaves users with the impression something is broken hence bad reputation on Verdaccio.
To make a better UX and prevent the feeling of it being broken I would:
* Forward the link to the standard registry, npmjs.com (e.g.: https://www.npmjs.com/package/debug) or make it configurable.

Or even better:

* Identify the dependency is not within the private registry when generating the view
* Include and show and external link (&#x1f517;) next to the dependency
* When clicked, open a new tab in the browser (&lt;a ... target="_blank"&gt; ) showing the details of the external dependency.
or
* Pull data from npmjs.com into Verdaccio page (not sure what type of open-APIs are available to do so, should be possible with a bit more work).

**Comment by axelrindle** [comment]
@coolsp There is an API, documented [over here](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md). It's just the npm registry which can be used to fetch data in JSON format ([example](http://registry.npmjs.com/verdaccio)).

**Comment by juanpicado** [comment]
> https://github.com/verdaccio/verdaccio/issues/888#issuecomment-410606953

Confirmed.

> Showing a 404 is a bad user-experience and leaves users with the impression something is broken hence bad reputation on Verdaccio.
To make a better UX and prevent the feeling of it being broken I would:

> Forward the link to the standard registry, npmjs.com (e.g.: https://www.npmjs.com/package/debug) > or make it configurable.

The problem I see here is according to your provided steps, actually the fact to remove all packages `Setup verdaccio as scoped private repository only, in config.yaml` you are restricting users to access any package, either public or private. See the error in the UI while you can see 404 in the UI. 

![screen shot 2018-12-21 at 5 56 24 pm](https://user-images.githubusercontent.com/558752/50353922-10422580-054a-11e9-85a7-b90661486774.png)

So, the error here is the UX experience, we should display correctly the error.

Or even better:

> Pull data from npmjs.com into Verdaccio page (not sure what type of open-APIs are available to do so, should be possible with a bit more work).

I have the same thoughts https://github.com/verdaccio/verdaccio/issues/888#issuecomment-410590569 and if the permissions are correct, the dependency should be already on the storage.

So, I'll delegate this to the UI contributors (cc: @ayusharma @priscilawebdev ) to display properly the error according to the HTTP STATUS code.

**Comment by coolsp** [comment]
Still a bad UX...
See my suggestions: [#888 (comment)](https://github.com/verdaccio/verdaccio/issues/888#issuecomment-428079718)
