### ISSUE TITLE
search crashes on entering ' ' (spaces) as a value

### ISSUE THREAD

**Issue by ashishsurana** [verdaccio/verdaccio#898]
**Description**
While searching for a package, if I put a ' ' (spaces), it searches for spaces as well and consequently API returs 404 which is a obvious behaviour

**To Reproduce**
1. Go to installed verdaccio
2. Click on search input & enter space bar ( ' ' as a value )

**Expected behavior**
No action should happen on searching such values. A string must be trimmed before searching.

**Screenshot for reference**

![image](https://user-images.githubusercontent.com/5610944/43731350-d1596980-99cb-11e8-9eac-0eb6871cd7ae.png)

**Comment by ashishsurana** [comment]
@juanpicado Please review and assign it to me so that I can send the PR. I have already fixed this issue 😄

**Comment by juanpicado** [comment]
it's valid :) Will you PR @ashishsurana ?
