### ISSUE TITLE
Some tests don't run on Windows

### ISSUE THREAD

**Issue by steve-p-com** [verdaccio/verdaccio#9]
This is more of a problem for contributors than users, but some tests don't run on Windows. For example, `test/functional/index.js` assumes it will be able to use `lsof`, which has no Windows equivalent:

```
exec('lsof -p ' + Number(server.pid), function(err, result) {
```

I'm not sure how to make it more multiplatform. I use both OS X and Windows platforms, so it's a partial problem for me.

**Comment by juanpicado** [comment]
I haven't found a replacement for `lsof` in windows, maybe a person with more experience on Windows can help here.

**Comment by steve-p-com** [comment]
I don't think you will find a replacement. It would require operating system level support which Windows just does not make available. I think this is insurmountable.

Are any tests still failing because of this? If so, those tests need changing so that they are skipped on Windows. It's not ideal, but then neither is writing tests that use functionality beyond what is universally available.

**Comment by juanpicado** [comment]
The list of unit test affected are around 120 of 191. It's a big amount. I could skip them somehow, but still the windows platform will remain untested. Let's see if someone comes up with a solution/suggestion about this.

**Comment by juanpicado** [comment]
related https://github.com/fbsamples/f8app/issues/147#issuecomment-281972807 a hint to fix it on Windows

**Comment by juanpicado** [comment]
Future contributors with Windows machines won't be able to run the test, but, the whole testing architecture was created thinking on UNIX and the CI runs on UNIX machines anyway and is not optimal. I'll close this one due to inactivity and pretty likely there is no a solution unless rewriting the whole thing.

**Comment by juanpicado** [comment]
The future big release will fix this issue, no `lsof` needs it to run the test.
