### ISSUE TITLE
Maintainers section is only populated by package.json:author

### ISSUE THREAD

**Issue by joshdcomp** [verdaccio/verdaccio#900]
**Describe the bug**
With `verdaccio@3.4.0`, the `Maintainers` section of the sidebar is only populated by the `author` field in package.json, neither the `maintainers` nor `contributors` fields are considered.

**To Reproduce**
1. Publish a package with `maintainers` or `contributors` fields as arrays in package.json either alongside `author` or with `author` omitted
2. Navigate to package page in Verdaccio
3. Note that _only_ the value for `author` is rendered under `Maintainers` in the sidebar

**Expected behavior**
I would like for either `maintainers` or `contributors` to accumulate alongisde `author` in the `Maintainers` sidebar

**Comment by ayusharma** [comment]
Please comment further on #853
