### ISSUE TITLE
verdaccio not starting on Windows 7

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [verdaccio/verdaccio#901]
Verdaccio does not work on windows 7

Install latest node
npm install -g yarn 
yarn global add verdaccio
verdaccio

**Expected behavior**
Verdaccio should start

**Screenshots**
![image](https://user-images.githubusercontent.com/5713776/43752579-49a7b236-9a1f-11e8-89a8-10b31152492a.png)

If possible create a doc for windows and also if possible for running it as a service on windows.
If already available please link it to github docs.

**Comment by juanpicado** [comment]
Check your nodejs env variables or try installing a different cli and see wether works properly

**Comment by dlouzan** [comment]
That doesn't seem to be a verdaccio issue, but as @juanpicado said, more like an issue with your node environment.

**Comment by rajjaiswalsaumya** [comment]
Well if you see the screenshot, there is no issue with yarn. My shell is able to find yarn but not verdaccio.

**Comment by sergiohgz** [comment]
Can you provide us you Windows PATH environment variable? This seems like Yarn global binaries directory is not set there
