### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jingxin2015** [verdaccio/verdaccio#903]
**Describe the bug**
python: 3.7.0
npm: 5.6.0
node: 8.11.3

**To Reproduce**
1. npm install -g verdaccio

**Screenshots**
![11](https://user-images.githubusercontent.com/16143766/43825082-57f7bcde-9b26-11e8-9683-c12090e896a1.png)

**Comment by juanpicado** [comment]
Python is not related to this project, all indicate your environment is not properly configured. I'd suggest checking on google how to fix it. Sorry, I cannot help with this one.

**Comment by jingxin2015** [comment]
The problem with the python version should be 2.7.x
Please close the issue, thank you.
