### ISSUE TITLE
run verdaccio error

### ISSUE THREAD

**Issue by jingxin2015** [verdaccio/verdaccio#906]
**Describe the bug**
Installation is normal on my own local machine(win 7 64bit), but running verdaccio command prompts after installation on the server(windows server 2008 R2 SP1) is not an internal or external command.

**Screenshots**
![111](https://user-images.githubusercontent.com/16143766/43871651-43c40616-9bb0-11e8-987c-63c3b3b0bfb3.png)

**Comment by juanpicado** [comment]
Please check your Node.js setup, the problem seems to be there. 

https://github.com/verdaccio/verdaccio/issues/901
https://github.com/verdaccio/verdaccio/issues/903

**Comment by jingxin2015** [comment]
you're right

The global module path of nodejs is modified by me, which results in the default global path of nodejs stored in the PATH of the current user variables.
