### ISSUE TITLE
Can't configure verdaccio to foreword npm

### ISSUE THREAD

**Issue by macdasi** [verdaccio/verdaccio#91]
I want to configure .npmrc at my project to use our local verdaccion repository , so I set
registry=http://git.local.co.il
@types:registry=https://registry.npmjs.org/
@angular:registry=https://registry.npmjs.org/

I have a ng2-translate to install in my packages.json , so I run "npm i" and it can't download it  because it tries to do it from the http://git.local.co.il . I tried to write in the config.yml : 
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
but still doesn't work , It works only if I remove the .npmrc file . so How can I work with private local repository and npm together packages at the same project ?

**Comment by hdost** [comment]
did you tab it?
```
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
```

**Comment by juanpicado** [comment]
@macdasi please feel free to reopen whether the problem persist, ticket too old.
