### ISSUE TITLE
Collisions between main verdaccio and plugins configuration

### ISSUE THREAD

**Issue by dlouzan** [verdaccio/verdaccio#928]
**Describe the bug**
The current configuration mapping for plugins allows collisions to happen that shadow settings in the main configuration when they share the same name as the plugin setting.

This causes two potential issues:
1. Plugins expecting to read some specific configuration in the main file cannot see the value since it's shadowed by the same key in the plugin configuration
2. Future-proofing: if a plugin is using a specific unused key today, and verdaccio adds the same key in a future update, those plugins cannot see the verdaccio value, and would be forced to make breaking changes in their codebase.

**To Reproduce**
As an example, let's assume the following verdaccio configuration using the plugin `verdaccio-myplugin`:

```yaml
...
auth:
  myplugin:
    foo: bar

foo: qux
...  
```

In the plugin code, the value read will be `config.foo = qux`, which is the plugin configuration. There's no way (I could find) to read the main `config.foo = bar` value.

**Expected behavior**
This is a design choice, so there could be a bunch of possibilities:
- Keep the plugin configuration prefix (`auth.<plugin-id>`) in the configuration, so we ensure no collisions can happen. Not sure how this is compatible with plugins that are more than one type (e.g. auth, middleware)
- Break the plugins API configuration object in two, one for the main configuration and another for the plugin
- Keep the current model, but at least warn in the logs that collisions have been detected, so that plugin developers can choose unused config keys
- ...

**Additional context**
The signature of the plugin options object in code is as follows:
```
declare type verdaccio$PluginOptions = {
  config: $Subtype<verdaccio$Config>;
  logger: verdaccio$Logger
}
```

This is the relevant [code in the plugin loader](https://github.com/verdaccio/verdaccio/blob/1fc1a33c4cb95de963917350064599a8186c3a4c/src/lib/plugin-loader.js#L25). It will receive the sub-object in the configuration `auth.<plugin-id>` as `pluginConfig` and merge it with the `appConfig` object using lodash:
```
function mergeConfig(appConfig, pluginConfig) {
  return _.merge(appConfig, pluginConfig);
}
```

@bufferoverflow @ercanucan

**Comment by juanpicado** [comment]
fixed on v6
