### ISSUE TITLE
Skip install for particular dep

### ISSUE THREAD

**Issue by ORESoftware** [verdaccio/verdaccio#930]
I am looking for this kind of feature with NPM/verdaccio:

https://stackoverflow.com/questions/51888198/skip-install-for-particular-dep

Is there a way to run npm install but skip a particular dependency?

Something like:

```bash
npm install --skip=lodash --skip=rxjs
```

In my case, I have some developer tooling and some dependencies may not actually be in the NPM registry yet, so I want to skip those.

**Comment by juanpicado** [comment]
@ORESoftware if the clients do not support that. I really doubt `verdaccio` can deal with that.
https://docs.npmjs.com/cli/install
https://yarnpkg.com/en/docs/cli/add

Anway, the general policy of all those clients is ALL or NOTHING, whether one dep is missing, the whole process fails.

**Comment by ORESoftware** [comment]
Yeah the problem I have, is for development, sometimes I want to run an `npm install` for a package that hasn't been published to the NPM registry yet...after the install command finishes, then I link the local dependency with npm link, but `npm install` will always fail as it stands if there is a missing dep (something isn't in the registry).

**Comment by juanpicado** [comment]
Then if the package is not published anywhere, I only recommend do not include it in your dependencies or use a git reference instead. I think you should double check your workflow there.

I'll close this due is not related with `verdaccio`.

**Comment by ORESoftware** [comment]
Thanks, I created an idea/feature request in the NPM community forum:

https://npm.community/t/allow-npm-install-to-work-with-missing-dependency/1526

I tagged this issue on there.
