### ISSUE TITLE
Support npm access command

### ISSUE THREAD

**Issue by cncolder** [verdaccio/verdaccio#937]
**Is your feature request related to a problem? Please describe.**

lerna publish run command: `npm access ls-packages --fetch-retries=0 --loglevel=http --registry http://npm.example.com`

The error log:
```shell
npm http request GET http://npm.example.com/-/whoami
npm http 200 http://npm.example.com/-/whoami
npm http request GET http://npm.example.com/-/org/foo/package?format=cli
npm http 404 http://npm.example.com/-/org/foo/package?format=cli
npm http request GET http://npm.example.com/-/user/foo/package?format=cli
npm http 404 http://npm.example.com/-/user/foo/package?format=cli
npm ERR! code E404
npm ERR! 404 File not found : -/user/foo/package

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/foo/.npm/_logs/2018-08-22T07_33_14_558Z-debug.log
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

verdaccio docker 3.6.0
node 10.9.0
npm 6.2.0
lerna 3.1.2

https://github.com/lerna/lerna/blob/42f4fdd0ddbb04bb95c69ad7296d3829eea34d91/commands/publish/lib/verify-npm-package-access.js#L13

**Comment by vegawong** [comment]
I also has the same problem when i use learn to publish packages. Is there would be supported in Verdacccio 4?

**Comment by juanpicado** [comment]
I cannot guarantee 100% but, it's on my plans. I don't know yet whether is completely possible. But we are open to PR if someone wishes to do it.

**Comment by vegawong** [comment]
thanks at all!

**Comment by MarkLyck** [comment]
Are there any updates on this? npm access is a pretty vital feature and this ticket is from summer 2018 :( over a year ago.

**Comment by DanielRuf** [comment]
As you can see there was no progress documented in this issue so we might still need some help and a PR for this.
