### ISSUE TITLE
Verdaccio on Cloudron

### ISSUE THREAD

**Issue by gramakri** [verdaccio/verdaccio#938]
Hi Verdaccio team,
Thanks for this project. We use it to host private npm packages ourselves.

Just wanted to inform you that the Verdaccio app package for Cloudron is available (Cloudron is a platform for running self-hosted web apps). The code for the package itself is at https://git.cloudron.io/cloudron/verdaccio-app/. We have automated browser tests as well to test automatic updates in the tests/ directory. The initial package was contributed to us by Ævar Eggertsson and we have kept it updated since (all the way back from 2.1.x actually). I guess you guys know the package already exists since @juanpicado  actually provided us the updated logo for the package a while ago :-) 

If you want to try it, you can install verdaccio from our demo instance at https://my-demo.cloudron.me (username: cloudron password: cloudron).

Would be great it if you could add us to one of the installation methods to advertise it a bit.

**Comment by juanpicado** [comment]
Hi @gramakri I'll be super happy to merge 👍 👍 👍
