### ISSUE TITLE
Malformed http response with '+' char on package version

### ISSUE THREAD

**Issue by pantoninho** [verdaccio/verdaccio#953]
When publishing packages with a '+' character on the npm package version, apache reverse proxy is reporting a 502, stating problems parsing the response. At this moment I can't give you the exact response that is being given, but monday I'll be able to post it here.

I've also tried the same thing running nginx, and the problem persisted.

To be clear about my intentions, I'm trying to publish nightly releases using the following convention: `x.x.x-next.y+{COMMIT-SHA}`.

Thanks for this great project.

**Comment by juanpicado** [comment]
Closing, feel free to reopen if you provide more info to dig into it. 👍 

> Thanks for this great project.
😃

**Comment by pantoninho** [comment]
I'm sorry not answering sooner, but appears the problem is not coming from verdaccio.

its' actually yarn's problem.
yarnpkg/yarn#6313

my bad.

**Comment by juanpicado** [comment]
Thanks @pantoninho it's good to know :) I'm sure others will land on the same issue soon or later. Thanks for sharing.
