### ISSUE TITLE
UI change details page issue of package readme

### ISSUE THREAD

**Issue by aremishevsky** [verdaccio/verdaccio#959]
**Describe the bug**

The readme of the package is not loading on change package using current package redirection.

**To Reproduce**
1. Go to [your-npm-registry]/#/detail/react (react package is just an example. The same issue exists for any package)
2. Click on 'prop-types' for example in sidebar dependencies
3. Please note that URL was changed, sidebar information was loaded, but the readme block is still from previous package ("react" in our case). But the H1 element was changed.

After the full reload of the page we have a correct readme but once you go to new dependencie - we have the same issue

It can be reproduced only starting from the 3.6.0 version.

**Expected behavior**
The readme of the package should be loaded.

**Screenshots**
<img width="1288" alt="_local__npm_registry_1" src="https://user-images.githubusercontent.com/32752187/44655697-bcda2380-a9fe-11e8-877d-b80f8af2c82a.png">

<img width="1312" alt="_local__npm_registry_2" src="https://user-images.githubusercontent.com/32752187/44655788-12163500-a9ff-11e8-850b-f58ef9b7c42f.png">

**Comment by ayusharma** [comment]
@aremishevsky I'll check as soon as possible.

**Comment by aremishevsky** [comment]
@juanpicado @ayusharma thanks for so fast progress in this bugfix.

Please let me know once the new version would be published.

**Comment by juanpicado** [comment]
@aremishevsky GitHub will send you an ✉️  after the release is done. 👍 , but, pretty soon.

**Comment by ayusharma** [comment]
@aremishevsky Please install `verdaccio@3.7.1 `

**Comment by coolsp** [comment]
Pulled the latest docker images and can confirm this is fixed.
