### ISSUE TITLE
Unable build with install --production

### ISSUE THREAD

**Issue by vdakalov** [verdaccio/verdaccio#962]
**Describe the bug**
Can't build, if dependencies was installed with flag `--production`. Problem with `cross-env`. It used for building scripts, but include to "devDependencies" section of package.json file. I think problem not only with this package. Production environment can related to other packages from `devDependencies`.

**To Reproduce**
1. Clone
2. npm install --no-save yarn
3. ./node_modules/.bin/yarn install --production
4. npm run code:build

**Expected behavior**
Expected "dependencies" section of package.json file contains all required for build and start application.

**Comment by juanpicado** [comment]
hi @vdakalov could you describe what are you trying to do? I'm a bit lost.

**Comment by vdakalov** [comment]
I read my issue again and now I think it a bit prematurely. I generally did not understand how to use `yarn install --production` in building process? May be first I should:
1. clone repo
2. install all dependencies
3. run `npm run code:build` and `webui:build`
4. extract builded scripts to target directory
5. copy to target directory package.json
6. and then, in target directory run `yarn install --production`
Ok. I need to think to formulate my question more specifically))

**Comment by juanpicado** [comment]
fyi
https://github.com/verdaccio/verdaccio/wiki/Build-Source-Code
https://github.com/verdaccio/verdaccio/wiki/Running-and-Debugging-tests

**Comment by vdakalov** [comment]
Thanks, I seen it. I reopen this issue later :)
