### ISSUE TITLE
Option to turn on https redirect for the web UI

### ISSUE THREAD

**Issue by fiws** [verdaccio/verdaccio#966]
**Is your feature request related to a problem? Please describe.**
Security is important. Verdaccio should be able to redirect to https.

**Describe the solution you'd like**
Have a option to turn on https redirects.

**Comment by juanpicado** [comment]
@fiws assuming if `https` is correctly set, right?

**Comment by fiws** [comment]
actually no. in my use case i have verdaccio behind a reverse-proxy (that has no option for https redirects)

**Comment by juanpicado** [comment]
🤔  I guess you can achieve that with at proxy level. https://stackoverflow.com/questions/43131915/nginx-reverse-proxy-force-https?rq=1

**Comment by fiws** [comment]
I know that this usually can be done at the proxy level.
I've deployed verdaccio to appengine, and there is no https redirect options. It has to be done in the application.

**Comment by fiws** [comment]
I think I was wrong. App engine allows to configure "handlers" which seem to allow https redirects.

https://cloud.google.com/appengine/docs/standard/nodejs/config/appref#handlers_element
