### ISSUE TITLE
🎃🎃 Hacktoberfest Tasks for Contributors 🎃🎃

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#973]
**If you are willing to contribute to verdaccio and have no idea how to start, here we have a list of task that might be a good starting point for you.**

![Verdaccio](https://github.com/verdaccio/verdaccio/blob/master/assets/bitmap/verdaccio-banner@2x.png?raw=true)

Before putting your hands into the code I'd recommend the following links:

* [Don't miss our contributing guidelines](https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md)
* [Wiki](https://github.com/verdaccio/verdaccio/wiki)
* [Build Project](https://github.com/verdaccio/verdaccio/wiki/Build-Source-Code)
* [Check all our repos](https://github.com/verdaccio/verdaccio/wiki/Repositories)
* [How to Debug Verdaccio](https://github.com/verdaccio/verdaccio/wiki/Running-and-Debugging-tests)
* [Any ticket is tagged with PR-Welcome](https://github.com/verdaccio/verdaccio/issues?q=is%3Aissue+is%3Aopen+label%3APR-Welcome)
* [Do you need some guidance? Chat with us](https://chat.verdaccio.org)
* [Do you want to help translating the documentation?](https://crowdin.com/project/verdaccio)
* [Next Major Release Roadmap](https://github.com/verdaccio/verdaccio/projects/10)

🚨All these tasks should be started **branching from `4.x` and try to keep them as small as possible to simplify the code reviews**. 🚨

⛑ If you start a new task, comment here with the reference of your PR and the name of the task to mark it as done when PR is being merged. ⛑

# Refactoring Tasks for Contributors

- [x] remove all `import assert from 'assert';` in favor of Jest matchers in testing (https://jestjs.io/docs/en/expect) #1042 @awshanks (still many test files `(test/**/*.js)` to update) 
- [ ] Improve flow types, eg: remove `any` and create custom types
- [ ] Remove `async` dependency in favor of ES6 features
- [x] Enforce use `HTTP_STATUS` namespaces instead `.expect(404)` in multiple files
- [ ] All API errors used on test or any core file should be on `API_ERROR`
- [ ] Increase coverage in utilities files (https://codecov.io/gh/verdaccio/verdaccio/tree/master/src/lib) one PR peer file
- [ ]  Replace with better code the recursive functions https://github.com/verdaccio/verdaccio/blob/master/src/lib/auth.js#L126
- [x] Camel case for all functions eg: https://github.com/verdaccio/verdaccio/blob/master/src/lib/utils.js#L550 (one PR peer file) @ashishsurana
- [x] Get rid off `require('../lib/logger');` in favor of ES modules `import xxx from xxx`. @varijkapil13
- [x] Replace `import * as Utils from '../../lib/utils';` by destructuring format `import {xxx, yyy} from '../../lib/utils';` @varijkapil13
- [ ] Refactor `logger.js` with better and clean code
- [x] Remove `status-cats.js` middleware, I'm looking for suggestions here
- [x] `// $FlowFixMe` was added to fix temporary Flow lack of types, check places where is not need it anymore @Utwo
- [ ] Refactor configuration https://github.com/verdaccio/verdaccio/issues/991
- [ ] Add Flow and apply Flow types, create new ones in some cases to the files are not tagged with `//@flow`
- [ ] Refactor `normalizeUserList(oldFormat: any, newFormat: any)` Avoid use **arguments** within the function (unit test included)

🤙🤙🤙🤙🤙 Feel free to suggest new things

🚨**Don't forget sign up here**🚨 https://hacktoberfest.digitalocean.com/
https://twitter.com/github/status/1044315660342505473

**Comment by priscilawebdev** [comment]
@juanpicado I am in!!! 💃

**Comment by varijkapil13** [comment]
Created #1040 for 
> Get rid off require('../lib/logger'); in favor of ES modules import xxx from xxx. WIP @varijkapil13

**Comment by varijkapil13** [comment]
Created #1041 for 

> Replace import * as Utils from '../../lib/utils'; by destructuring format import {xxx, yyy} from '../../lib/utils'; WIP @varijkapil13

**Comment by Utwo** [comment]
Created #1049 for

> remove all import assert from 'assert'; in favor of Jest matchers in testing

**Comment by Utwo** [comment]
Created #1050 for

> Enforce use HTTP_STATUS namespaces instead .expect(404) in multiple files

**Comment by Utwo** [comment]
Created #1051 for

> // $FlowFixMe was added to fix temporary Flow lack of types, check places where is not need it anymore

**Comment by juanpicado** [comment]
Thanks guys 🎃🎃🎃🎃
