### ISSUE TITLE
Create safe-mode to prevent publishing/writing to official NPM registry

### ISSUE THREAD

**Issue by ORESoftware** [verdaccio/verdaccio#975]
To a certain extent, I am afraid of using verdaccio b/c I am afraid of accidentally publishing packages to the non-local registry. Right now, the commands are to use:

`npm publish --registry=x`

where x is local, but what might be nice is for verdaccio to wrap the npm command, and in that case never publish to anything that is not localhost.

`verdaccio publish --registry=x`

the verdaccio publish command could never write to anything but local server, etc. Just an idea.
As far as proper command line design, the best way is to wrap another command is to do it like so:

`verdaccio --exec npm publish`

aka, everything that follows the --exec flag is part of a subcommand.

**Comment by juanpicado** [comment]
> To a certain extent, I am afraid of using verdaccio b/c I am afraid of accidentally publishing packages to the non-local registry. Right now, the commands are to use:

This is currently impossible, verdaccio does not publish on remote uplinks. 

> where x is local, but what might be nice is for verdaccio to wrap the npm command, and in that case never publish to anything that is not localhost.

I think this is out of our scope, we cannot do it.

Anyway, thanks for your concern, closing this, feel free to keep commenting on this topic if is quired.
