### ISSUE TITLE
Docker version tags

### ISSUE THREAD

**Issue by jonaskello** [verdaccio/verdaccio#98]
Would be nice if the docker images had version tags. This would mean docker installations could be more predictable in which version they run. As it is today there is only the `latest` tag so you don't know which version you will get when you do `docker pull`.

**Comment by juanpicado** [comment]
@jonaskello this repo does not handle the docker version. I think you are looking for this project https://github.com/wzrdtales/docker-sinopia don't you? Please correct me if I'm wrong.

**Comment by jonaskello** [comment]
@juanpicado If you look at the [docker hub](https://hub.docker.com/r/verdaccio/verdaccio/) it lists this repo as source. Also there is a Dockerfile in this repo, I thought that is what is used to build to docker hub but maybe it isn't?

**Comment by jmwilkinson** [comment]
I created the docker image as an easy way for people to pull the latest image. If someone wants to help out and tag builds, let me know so I can add you.

**Comment by Richie765** [comment]
If you like I can manage the Docker stuff for this project. I have my own Drone.io installation, it would automatically generate and publish a new Docker image whenever you create a new release. It will be tagged with the version number. I see there are quite some improvements possible to the Dockerfile, I can handle that as well.

Just let me know, I can start with it soon.

**Comment by juanpicado** [comment]
@Richie765 please feel free to PR any change

**Comment by Richie765** [comment]
@juanpicado, I've looked into it and there's an easier way to do it. You can setup automated builds on Docker Hub. I've outlined the steps:

* Link your Docker Hub account with Github (settings, linked accounts).
* Delete your current Docker Hub verdaccio/verdaccio repo.
* Choose: Create Automated Build. Select your verdaccio/verdaccio repo.
* Go to the build settings and fill out as follows:

```
Type    Name            Docker Tag Name
Tag     /v([0-9.]+)/    {\1}
Tag     /v(\d+\.\d+)/   {\1}
Tag     /v([0-9]+)/     {\1}
Tag     /v([0-9.]+)/    latest
```

When you push new tags (releases) an automatic build will be triggered. You can see how it will look like here:

https://hub.docker.com/r/richie765/verdaccio/tags/

There's probably more tweaking that you could do but this should get you started quickly.

**Comment by juanpicado** [comment]
As soon I got permissions on Docker Hub I'll take care of this one.

**Comment by Richie765** [comment]
Great! Since you already have automated builds, you only need to do the last step, the build settings.

**Comment by juanpicado** [comment]
@Richie765 done 👍

**Comment by jonaskello** [comment]
Nice work! 👍
