### ISSUE TITLE
HELP: How to publish package trough exposed API

### ISSUE THREAD

**Issue by zolekm** [verdaccio/verdaccio#99]
Hi, 
i'm working on project where i want to implement publishing new package trough web interface(API).
When i was searching for API i found endpoint to publish new package, but i can't found any example how to do it.

API method that i referencing to: https://github.com/verdaccio/verdaccio/blob/master/lib/index-api.js#L289

There is requirement for tar file and handler for tarball upload but i don't found any specification of structure for that file.

@rlidwka i found that you are the main contributer for API maybe you will know the right solution?

Any answer would be helpful.

Best, Matija

**Comment by juanpicado** [comment]
@zolekm about @rlidwka refer to https://github.com/rlidwka/sinopia/issues/376

**Comment by juanpicado** [comment]
About the endpoint question, verdaccio works as a webserver that works assuming the user will use NPM cli, thus, verdaccio just exposes the same enpoind npm will use and acts as a proxy with private storage. 

I haven't found any npm documentation that describe such endpoints, but their repo seems a good point to start.

https://github.com/npm/npm/blob/latest/lib/publish.js

**Comment by zolekm** [comment]
@juanpicado tnx a lot i will try:)
