### ISSUE TITLE
Custom HTTP header name for Protocol

### ISSUE THREAD

**Issue by marcoreni** [verdaccio/verdaccio#990]
**Is your feature request related to a problem? Please describe.**
CloudFront uses (for unknown reasons) a custom header name for Protocol; instead of `X-Forwarded-Proto` the header name is `CloudFront-Forwarded-Proto`. There is no way to change this name.

**Describe the solution you'd like**
There could be a new config value that allows to override the default header name.

**Additional context**
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-protocol

**Comment by juanpicado** [comment]
Just looking it seems can be solved at Proxy level or configuration at AWS. It seems the link is no longer valid, the anchor is missing. 
https://forum.ghost.org/t/ghost-behind-aws-cloudfront/6597/5

**Comment by marcoreni** [comment]
The link still works for me.

If someone wants to use the solution you linked, there must be a proxy between cloudfront and the Verdaccio process (if you use an EC2 machine it may be an nginx installed alongside Verdaccio, or if you use ECS/Docker you have to have a sidecar container).

There is currently no way to change the header configuration in Cloudfront , so there is currently no way to use Verdaccio in HTTPS directly behind it.

I created a fork to customise the header a while ago and it worked fine, but since then I stopped using Verdaccio so I'm not maintaining it directly.

**Comment by DanielRuf** [comment]
Can you point us to the change that you have applied? `patch-package` could have also been an option. ;-)

**Comment by marcoreni** [comment]
Here is the quick&dirty change I made at the time. I never created a config value for it (therefore never created a PR for it) because of #991 .

https://github.com/marcoreni/verdaccio/blob/feature/cloudfront-support/src/lib/utils.js#L395

**Comment by juanpicado** [comment]
It will be a environment variable `VERDACCIO_FORWARDED_PROTO` in Verdaccio 5.
