### ISSUE TITLE
Issue - private registry - scoped package - gitlab -  debug--- [gitlab] deny user: <empty> access to package: @scopename/packagename

### ISSUE THREAD

**Issue by brommer** [verdaccio/verdaccio#999]
**Describe the bug**
I have setup a private verdaccio (default 3.6.0 and manually increased to 3.8.1) registry with verdaccio-gitlab plugin (2.0.0). 

I am able to download non-scoped packages (from public repo via proxy) but I am not able to download scoped packages from via proxy and my npm registry. I require authentication for both, publish and access.

Trace log:
```
 info <-- 172.19.0.1 requested 'GET /@scopename/packagename'
 trace--- api middleware using legacy auth token
 trace--- authenticating yetanotherusername
 trace--- [gitlab] authenticate called for user: yetanotherusername
 trace--- [gitlab] user: yetanotherusername not found in cache
 trace--- [gitlab] querying gitlab user groups with params: { min_access_level: 40 }
 debug--- [gitlab] saving data in cache for user: yetanotherusername
 info --- [gitlab] user: yetanotherusername successfully authenticated
 debug--- [gitlab] user: yetanotherusername, with groups: { publish: [ 'yetanotherusername', 'indeework' ] }
 trace--- authentication for user yetanotherusername was successfully. Groups: [ 'yetanotherusername', 'indeework' ]
 trace--- allow access for @scopename/packagename
 debug--- [gitlab] allow user: yetanotherusername access to package: @scopename/packagename
 trace--- allowed access for @scopename/packagename
 debug-=- updating package @scopename/packagename info
 http <-- 200, user: yetanotherusername(95.212.221.17 via 172.19.0.1), req: 'GET /@scopename/packagename', bytes: 0/1367
 http <-- 200, user: yetanotherusername(95.212.221.17 via 172.19.0.1), req: 'GET /@scopename/packagename', bytes: 0/1367
 info <-- 172.19.0.1 requested 'GET /@scopename/packagename/-/packagename-0.0.1.tgz'
 trace--- allow access for @scopename/packagename
 debug--- [gitlab] deny user: <empty> access to package: @scopename/packagename
 trace--- forbidden access for @scopename/packagename. Error: access denied, user not authenticated in gitlab and unauthenticated package access disabled
 http <-- 401, user: null(95.212.221.17 via 172.19.0.1), req: 'GET /@scopename/packagename/-/packagename-0.0.1.tgz', error: access denied, user not authenticated in gitlab and unauthenticated package access disabled
 http <-- 401, user: null(95.212.221.17 via 172.19.0.1), req: 'GET /@scopename/packagename/-/packagename-0.0.1.tgz', error: access denied, user not authenticated in gitlab and unauthenticated package access disabled
```
The first authentication call is successful. However, the second call to the gitlab auth plugin seems to provide an empty user to the plugin, resulting in: [gitlab] deny user: <empty> access to package: @scopename/packagename

I know, the error is thrown in the plugin code, but it looks like Verdaccio is not providing the proper user.name to the plugin?

**To Reproduce**
- Create a scoped top level group in Gitlab
- Use the provided configuration and start Verdaccio
- Make sure the user has maintainer or owner rights on the group
- Publish a package with the name "@<gitlabgroupname>/packagename>" to the Verdaccio registry
- Try to add the package as a dependency to another project

**Expected behavior**
Must be possible to download the package after initial (npm login) authentication and successful (see first success message) authorization.

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```
storage: /verdaccio/storage/data

plugins: /verdaccio/plugins

listen:
  - 0.0.0.0:4873

url_prefix: /verdaccio/

auth:
  gitlab:
    url: http://gitlab/gitlab
    authCache:
      enabled: true
      ttl: 300
    publish: $maintainer

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@scopename/*':
    # scopename packages
    access: $authenticated
    publish: $authenticated
    gitlab: true

  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
    gitlab: true

logs:
  - { type: stdout, format: pretty, level: trace }
  #- {type: file, path: verdaccio.log, level: info}

web:
  enable: true
```

**Debugging output**
```
npm install @scopename/packagename
npm ERR! code E401
npm ERR! 401 Unauthorized: @scopename/packagename@0.0.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2018-09-15T21_05_29_180Z-debug.log
```

**Additional context**
Maybe the user.name is not properly provided to the allow_access call when trying to download the .tgz from the registry.

**Comment by brommer** [comment]
I found a hint in https://github.com/verdaccio/verdaccio/issues/586
Adding always-auth=true to ~/.npmrc solves the issue. Do you have an idea, why this is needed?

**Comment by juanpicado** [comment]
Are you using yarn?

**Comment by brommer** [comment]
I am using npm

**Comment by juanpicado** [comment]
Have you tried to ask for help their repository? I think this issue is quite specific for Gitlab plugin  and here you might not get too much help because we do not maintain that plugin.
